Terraria Decompiled: System.Reflection.Emit.TypeBuilder.CreateTypeInfo
CreateTypeInfo()
TypeInfo System.Reflection.Emit.TypeBuilder.CreateTypeInfo () inline
Definition at line 822 of file TypeBuilder.cs.
        {
            if (this.createTypeCalled)
            {
                return this.created;
            }
            if (!base.IsInterface && this.parent == null && this != this.pmodule.assemblyb.corlib_object_type && this.FullName != "<Module>")
            {
                this.SetParent(this.pmodule.assemblyb.corlib_object_type);
            }
            if (this.fields != null)
            {
                foreach (FieldBuilder fieldBuilder in this.fields)
                {
                    if (!(fieldBuilder == null))
                    {
                        Type fieldType = fieldBuilder.FieldType;
                        if (!fieldBuilder.IsStatic && fieldType is TypeBuilder && fieldType.IsValueType && fieldType != this && this.is_nested_in(fieldType))
{
                            TypeBuilder typeBuilder = (TypeBuilder)fieldType;
                            if (!typeBuilder.is_created)
{
                                AppDomain.CurrentDomain.DoTypeBuilderResolve(typeBuilder);
                                bool is_created = typeBuilder.is_created;
                            }
                        }
                    }
                }
            }
            if (!base.IsInterface && !base.IsValueType && this.ctors == null && this.tname != "<Module>" && ((this.GetAttributeFlagsImpl() & TypeAttributes.Abstract) | TypeAttributes.Sealed) != (TypeAttributes.Abstract | TypeAttributes.Sealed) && !this.has_ctor_method())
            {
                this.DefineDefaultConstructor(MethodAttributes.Public);
            }
            this.createTypeCalled = true;
            if (this.parent != null && this.parent.IsSealed)
            {
                string[] array2 = new string[5];
                array2[0] = "Could not load type '";
                array2[1] = this.FullName;
                array2[2] = "' from assembly '";
                int num = 3;
                Assembly assembly = this.Assembly;
                array2[num] = ((assembly != null) ? assembly.ToString() : null);
                array2[4] = "' because the parent type is sealed.";
                throw new TypeLoadException(string.Concat(array2));
            }
            if (this.parent == this.pmodule.assemblyb.corlib_enum_type && this.methods != null)
            {
                string[] array3 = new string[5];
                array3[0] = "Could not load type '";
                array3[1] = this.FullName;
                array3[2] = "' from assembly '";
                int num2 = 3;
                Assembly assembly2 = this.Assembly;
                array3[num2] = ((assembly2 != null) ? assembly2.ToString() : null);
                array3[4] = "' because it is an enum with methods.";
                throw new TypeLoadException(string.Concat(array3));
            }
            if (this.interfaces != null)
            {
                foreach (Type type in this.interfaces)
                {
                    if (type.IsNestedPrivate && type.Assembly != this.Assembly)
                    {
                        string[] array5 = new string[7];
                        array5[0] = "Could not load type '";
                        array5[1] = this.FullName;
                        array5[2] = "' from assembly '";
                        int num3 = 3;
                        Assembly assembly3 = this.Assembly;
                        array5[num3] = ((assembly3 != null) ? assembly3.ToString() : null);
                        array5[4] = "' because it is implements the inaccessible interface '";
                        array5[5] = type.FullName;
                        array5[6] = "'.";
                        throw new TypeLoadException(string.Concat(array5));
                    }
                }
            }
            if (this.methods != null)
            {
                bool flag = !base.IsAbstract;
                for (int j = 0; j < this.num_methods; j++)
                {
                    MethodBuilder methodBuilder = this.methods[j];
                    if (flag && methodBuilder.IsAbstract)
                    {
                        string text = "Type is concrete but has abstract method ";
                        MethodBuilder methodBuilder2 = methodBuilder;
                        throw new InvalidOperationException(text + ((methodBuilder2 != null) ? methodBuilder2.ToString() : null));
                    }
                    methodBuilder.check_override();
                    methodBuilder.fixup();
                }
            }
            if (this.ctors != null)
            {
                ConstructorBuilder[] array6 = this.ctors;
                for (int i = 0; i < array6.Length; i++)
                {
                    array6[i].fixup();
                }
            }
            this.ResolveUserTypes();
            this.created = this.create_runtime_class();
            if (this.created != null)
            {
                return this.created;
            }
            return this;
        }
References System.Reflection.Emit.TypeBuilder.Assembly, System.Type.Assembly, System.Reflection.Emit.ModuleBuilder.assemblyb, System.Reflection.Emit.MethodBuilder.check_override(), System.Reflection.Emit.AssemblyBuilder.corlib_enum_type, System.Reflection.Emit.AssemblyBuilder.corlib_object_type, System.Reflection.Emit.TypeBuilder.create_runtime_class(), System.Reflection.Emit.TypeBuilder.created, System.Reflection.Emit.TypeBuilder.createTypeCalled, System.Reflection.Emit.TypeBuilder.ctors, System.AppDomain.CurrentDomain, System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor(), System.AppDomain.DoTypeBuilderResolve(), System.Reflection.Emit.TypeBuilder.fields, System.Reflection.Emit.FieldBuilder.FieldType, System.Reflection.Emit.ConstructorBuilder.fixup(), System.Reflection.Emit.MethodBuilder.fixup(), System.Reflection.Emit.TypeBuilder.FullName, System.Type.FullName, System.Reflection.Emit.TypeBuilder.has_ctor_method(), System.Reflection.Emit.TypeBuilder.interfaces, System.Reflection.Emit.TypeBuilder.is_created, System.Reflection.MethodBase.IsAbstract, System.Type.IsNestedPrivate, System.Type.IsSealed, System.Reflection.FieldInfo.IsStatic, System.Type.IsValueType, System.Reflection.Emit.TypeBuilder.methods, System.Reflection.Emit.TypeBuilder.num_methods, System.Reflection.Emit.TypeBuilder.parent, System.Reflection.Emit.TypeBuilder.pmodule, System.Reflection.Emit.TypeBuilder.ResolveUserTypes(), System.Reflection.Emit.TypeBuilder.SetParent(), System.text, System.Reflection.Assembly.ToString(), System.Reflection.Emit.MethodBuilder.ToString(), System.Reflection.TypeInfo.type, and System.Reflection.Emit.TypeBuilder.TypeBuilder().
Referenced by System.Reflection.Emit.TypeBuilder.CreateType(), and System.Reflection.Emit.EnumBuilder.CreateTypeInfo().