Terraria Decompiled: System.Reflection.Emit.TypeBuilder.SetConstantValue
SetConstantValue()
static bool System.Reflection.Emit.TypeBuilder.SetConstantValue (Type destType, object value, ref object destValue) inline static package
Definition at line 2312 of file TypeBuilder.cs.
        {
            if (value != null)
            {
                Type type = value.GetType();
                if (destType.IsByRef)
                {
                    destType = destType.GetElementType();
                }
                destType = Nullable.GetUnderlyingType(destType) ?? destType;
                if (destType.IsEnum)
                {
                    EnumBuilder enumBuilder;
                    Type type2;
                    TypeBuilder typeBuilder;
                    if ((enumBuilder = destType as EnumBuilder) != null)
                    {
                        type2 = enumBuilder.GetEnumUnderlyingType();
                        if ((!enumBuilder.GetTypeBuilder().is_created || !(type == enumBuilder.GetTypeBuilder().created)) && !(type == type2))
{
                            TypeBuilder.throw_argument_ConstantDoesntMatch();
                        }
                    }
                    else if ((typeBuilder = destType as TypeBuilder) != null)
                    {
                        type2 = typeBuilder.underlying_type;
                        if (type2 == null || (type != typeBuilder.UnderlyingSystemType && type != type2))
{
                            TypeBuilder.throw_argument_ConstantDoesntMatch();
                        }
                    }
                    else
                    {
                        type2 = Enum.GetUnderlyingType(destType);
                        if (type != destType && type != type2)
{
                            TypeBuilder.throw_argument_ConstantDoesntMatch();
                        }
                    }
                    type = type2;
                }
                else if (!destType.IsAssignableFrom(type))
                {
                    TypeBuilder.throw_argument_ConstantDoesntMatch();
                }
                switch (Type.GetTypeCode(type))
                {
                case TypeCode.Boolean:
                case TypeCode.Char:
                case TypeCode.SByte:
                case TypeCode.Byte:
                case TypeCode.Int16:
                case TypeCode.UInt16:
                case TypeCode.Int32:
                case TypeCode.UInt32:
                case TypeCode.Int64:
                case TypeCode.UInt64:
                case TypeCode.Single:
                case TypeCode.Double:
                    destValue = value;
                    return true;
                case TypeCode.DateTime:
                {
                    long ticks = ((DateTime)value).Ticks;
                    destValue = ticks;
                    return true;
                }
                case TypeCode.String:
                    destValue = value;
                    return true;
                }
                throw new ArgumentException(type.ToString() + " is not a supported constant type.");
            }
            destValue = null;
            return true;
        }
References System.Reflection.Emit.TypeBuilder.created, System.DateTime, System.Type.GetElementType(), System.Reflection.Emit.EnumBuilder.GetEnumUnderlyingType(), System.Type.GetType(), System.Reflection.Emit.EnumBuilder.GetTypeBuilder(), System.Type.GetTypeCode(), System.Enum.GetUnderlyingType(), System.Nullable< T >.GetUnderlyingType(), System.Reflection.Emit.TypeBuilder.is_created, System.Type.IsAssignableFrom(), System.Type.IsByRef, System.Type.IsEnum, System.Reflection.Emit.TypeBuilder.throw_argument_ConstantDoesntMatch(), System.Type.ToString(), System.Reflection.TypeInfo.type, System.Reflection.Emit.TypeBuilder.underlying_type, System.Reflection.Emit.TypeBuilder.UnderlyingSystemType, and System.value.
Referenced by System.Reflection.Emit.ParameterBuilder.SetConstant().