Terraria Decompiled: System.Reflection.Emit.TypeBuilder.DefineUninitializedData
DefineUninitializedData()
FieldBuilder System.Reflection.Emit.TypeBuilder.DefineUninitializedData (string name, int size, FieldAttributes attributes) inline
Definition at line 1838 of file TypeBuilder.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            if (name.Length == 0)
            {
                throw new ArgumentException("Empty name is not legal", "name");
            }
            if (size <= 0 || size > 4128768)
            {
                throw new ArgumentException("Data size must be > 0 and < 0x3f0000");
            }
            this.check_not_created();
            string text = "$ArrayType$" + size.ToString();
            TypeIdentifier typeIdentifier = TypeIdentifiers.WithoutEscape(text);
            Type type = this.pmodule.GetRegisteredType(this.fullname.NestedName(typeIdentifier));
            if (type == null)
            {
                TypeBuilder typeBuilder = this.DefineNestedType(text, TypeAttributes.Public | TypeAttributes.NestedPublic | TypeAttributes.ExplicitLayout | TypeAttributes.Sealed, this.pmodule.assemblyb.corlib_value_type, null, PackingSize.Size1, size);
                typeBuilder.CreateType();
                type = typeBuilder;
            }
            return this.DefineField(name, type, attributes | FieldAttributes.Static | FieldAttributes.HasFieldRVA);
        }
References System.Reflection.Emit.TypeBuilder.check_not_created(), System.Reflection.Emit.TypeBuilder.CreateType(), System.Reflection.Emit.TypeBuilder.DefineField(), System.Reflection.Emit.TypeBuilder.DefineNestedType(), System.Reflection.Emit.TypeBuilder.fullname, System.Reflection.Emit.ModuleBuilder.GetRegisteredType(), System.name, System.TypeName.NestedName(), System.Reflection.Emit.TypeBuilder.pmodule, System.text, System.Reflection.TypeInfo.type, and System.TypeIdentifiers.WithoutEscape().
Referenced by System.Reflection.Emit.TypeBuilder.DefineInitializedData().