Terraria Decompiled: System.Reflection.Emit.TypeBuilder.ResolveUserTypes
ResolveUserTypes() [1/2]
void System.Reflection.Emit.TypeBuilder.ResolveUserTypes () inline private
Definition at line 934 of file TypeBuilder.cs.
        {
            this.parent = TypeBuilder.ResolveUserType(this.parent);
            TypeBuilder.ResolveUserTypes(this.interfaces);
            if (this.fields != null)
            {
                foreach (FieldBuilder fieldBuilder in this.fields)
                {
                    if (fieldBuilder != null)
                    {
                        fieldBuilder.ResolveUserTypes();
                    }
                }
            }
            if (this.methods != null)
            {
                foreach (MethodBuilder methodBuilder in this.methods)
                {
                    if (methodBuilder != null)
                    {
                        methodBuilder.ResolveUserTypes();
                    }
                }
            }
            if (this.ctors != null)
            {
                foreach (ConstructorBuilder constructorBuilder in this.ctors)
                {
                    if (constructorBuilder != null)
                    {
                        constructorBuilder.ResolveUserTypes();
                    }
                }
            }
        }
References System.Reflection.Emit.TypeBuilder.ctors, System.Reflection.Emit.TypeBuilder.fields, System.Reflection.Emit.TypeBuilder.interfaces, System.Reflection.Emit.TypeBuilder.methods, System.Reflection.Emit.TypeBuilder.parent, System.Reflection.Emit.TypeBuilder.ResolveUserType(), System.Reflection.Emit.ConstructorBuilder.ResolveUserTypes(), System.Reflection.Emit.FieldBuilder.ResolveUserTypes(), System.Reflection.Emit.MethodBuilder.ResolveUserTypes(), and System.Reflection.Emit.TypeBuilder.ResolveUserTypes().
Referenced by System.Reflection.Emit.TypeBuilder.CreateTypeInfo(), System.Reflection.Emit.SignatureHelper.GetSignature(), System.Reflection.Emit.ConstructorBuilder.ResolveUserTypes(), System.Reflection.Emit.FieldBuilder.ResolveUserTypes(), System.Reflection.Emit.MethodBuilder.ResolveUserTypes(), and System.Reflection.Emit.TypeBuilder.ResolveUserTypes().