Terraria Decompiled: System.Reflection.Emit.TypeBuilder.DefineMethod
DefineMethod() [4/5]
MethodBuilder System.Reflection.Emit.TypeBuilder.DefineMethod (string name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type parameterTypeRequiredCustomModifiers[][], Type parameterTypeOptionalCustomModifiers[][]) inline
Definition at line 606 of file TypeBuilder.cs.
        {
            this.check_name("name", name);
            this.check_not_created();
            if (base.IsInterface && ((attributes & MethodAttributes.Abstract) == MethodAttributes.PrivateScope || (attributes & MethodAttributes.Virtual) == MethodAttributes.PrivateScope) && (attributes & MethodAttributes.Static) == MethodAttributes.PrivateScope)
            {
                throw new ArgumentException("Interface method must be abstract and virtual.");
            }
            if (returnType == null)
            {
                returnType = this.pmodule.assemblyb.corlib_void_type;
            }
            MethodBuilder methodBuilder = new MethodBuilder(this, name, attributes, callingConvention, returnType, returnTypeRequiredCustomModifiers, returnTypeOptionalCustomModifiers, parameterTypes, parameterTypeRequiredCustomModifiers, parameterTypeOptionalCustomModifiers);
            this.append_method(methodBuilder);
            return methodBuilder;
        }
References System.Reflection.Emit.TypeBuilder.append_method(), System.Reflection.Emit.ModuleBuilder.assemblyb, System.Reflection.Emit.TypeBuilder.check_name(), System.Reflection.Emit.TypeBuilder.check_not_created(), System.Reflection.Emit.AssemblyBuilder.corlib_void_type, System.name, and System.Reflection.Emit.TypeBuilder.pmodule.