Terraria Decompiled: System.Reflection.Emit.TypeBuilder.GetConstructor
GetConstructor()
static ConstructorInfo System.Reflection.Emit.TypeBuilder.GetConstructor (Type type, ConstructorInfo constructor) inline static
Definition at line 2157 of file TypeBuilder.cs.
        {
            if (type == null)
            {
                throw new ArgumentException("Type is not generic", "type");
            }
            if (!type.IsGenericType)
            {
                throw new ArgumentException("Type is not a generic type", "type");
            }
            if (type.IsGenericTypeDefinition)
            {
                throw new ArgumentException("Type cannot be a generic type definition", "type");
            }
            if (constructor == null)
            {
                throw new NullReferenceException();
            }
            if (!constructor.DeclaringType.IsGenericTypeDefinition)
            {
                throw new ArgumentException("constructor declaring type is not a generic type definition", "constructor");
            }
            if (constructor.DeclaringType != type.GetGenericTypeDefinition())
            {
                throw new ArgumentException("constructor declaring type is not the generic type definition of type", "constructor");
            }
            ConstructorInfo constructor2 = type.GetConstructor(constructor);
            if (constructor2 == null)
            {
                throw new ArgumentException("constructor not found");
            }
            return constructor2;
        }
References System.Reflection.MemberInfo.DeclaringType, System.Type.GetConstructor(), System.Type.GetGenericTypeDefinition(), System.Type.IsGenericType, System.Type.IsGenericTypeDefinition, and System.Reflection.TypeInfo.type.
Referenced by System.Reflection.Emit.EnumBuilder.GetConstructorImpl().