Terraria Decompiled: System.Reflection.Emit.TypeBuilder.GenerateDebugInfo
GenerateDebugInfo()
void System.Reflection.Emit.TypeBuilder.GenerateDebugInfo (ISymbolWriter symbolWriter) inline package
Definition at line 1026 of file TypeBuilder.cs.
        {
            symbolWriter.OpenNamespace(this.Namespace);
            if (this.methods != null)
            {
                for (int i = 0; i < this.num_methods; i++)
                {
                    this.methods[i].GenerateDebugInfo(symbolWriter);
                }
            }
            if (this.ctors != null)
            {
                ConstructorBuilder[] array = this.ctors;
                for (int j = 0; j < array.Length; j++)
                {
                    array[j].GenerateDebugInfo(symbolWriter);
                }
            }
            symbolWriter.CloseNamespace();
            if (this.subtypes != null)
            {
                for (int k = 0; k < this.subtypes.Length; k++)
                {
                    this.subtypes[k].GenerateDebugInfo(symbolWriter);
                }
            }
        }
References System.array, System.Diagnostics.SymbolStore.ISymbolWriter.CloseNamespace(), System.Reflection.Emit.TypeBuilder.ctors, System.Reflection.Emit.ConstructorBuilder.GenerateDebugInfo(), System.Reflection.Emit.MethodBuilder.GenerateDebugInfo(), System.Reflection.Emit.TypeBuilder.GenerateDebugInfo(), System.Reflection.Emit.TypeBuilder.methods, System.Reflection.Emit.TypeBuilder.Namespace, System.Reflection.Emit.TypeBuilder.num_methods, System.Diagnostics.SymbolStore.ISymbolWriter.OpenNamespace(), and System.Reflection.Emit.TypeBuilder.subtypes.
Referenced by System.Reflection.Emit.TypeBuilder.GenerateDebugInfo().