Terraria Decompiled: System.Reflection.Emit.TypeBuilder.SetCustomAttribute
SetCustomAttribute() [2/2]
void System.Reflection.Emit.TypeBuilder.SetCustomAttribute (CustomAttributeBuilder customBuilder) inline
Definition at line 1676 of file TypeBuilder.cs.
        {
            if (customBuilder == null)
            {
                throw new ArgumentNullException("customBuilder");
            }
            string fullName = customBuilder.Ctor.ReflectedType.FullName;
            if (fullName == "System.Runtime.InteropServices.StructLayoutAttribute")
            {
                byte[] data = customBuilder.Data;
                int num = (int)data[2] | ((int)data[3] << 8);
                this.attrs &= ~TypeAttributes.LayoutMask;
                switch (num)
                {
                case 0:
                    this.attrs |= TypeAttributes.SequentialLayout;
                    goto IL_00A5;
                case 2:
                    this.attrs |= TypeAttributes.ExplicitLayout;
                    goto IL_00A5;
                case 3:
                    this.attrs |= TypeAttributes.NotPublic;
                    goto IL_00A5;
                }
                throw new Exception("Error in customattr");
                IL_00A5:
                Type type = ((customBuilder.Ctor is ConstructorBuilder) ? ((ConstructorBuilder)customBuilder.Ctor).parameters[0] : customBuilder.Ctor.GetParametersInternal()[0].ParameterType);
                int num2 = 6;
                if (type.FullName == "System.Int16")
                {
                    num2 = 4;
                }
                int num3 = (int)data[num2++];
                num3 |= (int)data[num2++] << 8;
                for (int i = 0; i < num3; i++)
                {
                    num2++;
                    int num4;
                    if (data[num2++] == 85)
                    {
                        num4 = CustomAttributeBuilder.decode_len(data, num2, out num2);
                        CustomAttributeBuilder.string_from_bytes(data, num2, num4);
                        num2 += num4;
                    }
                    num4 = CustomAttributeBuilder.decode_len(data, num2, out num2);
                    string text = CustomAttributeBuilder.string_from_bytes(data, num2, num4);
                    num2 += num4;
                    int num5 = (int)data[num2++];
                    num5 |= (int)data[num2++] << 8;
                    num5 |= (int)data[num2++] << 16;
                    num5 |= (int)data[num2++] << 24;
                    if (!(text == "CharSet"))
                    {
                        if (!(text == "Pack"))
{
                            if (text == "Size")
{
                                this.class_size = num5;
                            }
                        }
                        else
{
                            this.packing_size = (PackingSize)num5;
                        }
                    }
                    else
                    {
                        switch (num5)
{
                        case 1:
                        case 2:
                            this.attrs &= ~TypeAttributes.StringFormatMask;
                            break;
                        case 3:
                            this.attrs &= ~TypeAttributes.AutoClass;
                            this.attrs |= TypeAttributes.UnicodeClass;
                            break;
                        case 4:
                            this.attrs &= ~TypeAttributes.UnicodeClass;
                            this.attrs |= TypeAttributes.AutoClass;
                            break;
                        }
                    }
                }
                return;
            }
            if (fullName == "System.Runtime.CompilerServices.SpecialNameAttribute")
            {
                this.attrs |= TypeAttributes.SpecialName;
                return;
            }
            if (fullName == "System.SerializableAttribute")
            {
                this.attrs |= TypeAttributes.Serializable;
                return;
            }
            if (fullName == "System.Runtime.InteropServices.ComImportAttribute")
            {
                this.attrs |= TypeAttributes.Import;
                return;
            }
            if (fullName == "System.Security.SuppressUnmanagedCodeSecurityAttribute")
            {
                this.attrs |= TypeAttributes.HasSecurity;
            }
            if (this.cattrs != null)
            {
                CustomAttributeBuilder[] array = new CustomAttributeBuilder[this.cattrs.Length + 1];
                this.cattrs.CopyTo(array, 0);
                array[this.cattrs.Length] = customBuilder;
                this.cattrs = array;
                return;
            }
            this.cattrs = new CustomAttributeBuilder[1];
            this.cattrs[0] = customBuilder;
        }
References System.array, System.Reflection.Emit.TypeBuilder.cattrs, System.Reflection.Emit.CustomAttributeBuilder.Ctor, System.Reflection.Emit.CustomAttributeBuilder.Data, System.Reflection.Emit.CustomAttributeBuilder.decode_len(), System.Type.FullName, System.Reflection.MethodBase.GetParametersInternal(), int, System.Reflection.Emit.TypeBuilder.PackingSize, System.Reflection.ParameterInfo.ParameterType, System.Reflection.MemberInfo.ReflectedType, System.Reflection.Emit.CustomAttributeBuilder.string_from_bytes(), System.text, and System.Reflection.TypeInfo.type.
Referenced by System.RuntimeType.GetTypeFromCLSIDImpl(), System.Reflection.Emit.TypeBuilder.SetCustomAttribute(), and System.Reflection.Emit.EnumBuilder.SetCustomAttribute().