Terraria Decompiled: System.Reflection.Emit.TypeBuilder.FixupTokens
FixupTokens()
void System.Reflection.Emit.TypeBuilder.FixupTokens (Dictionary< int, int > token_map, Dictionary< int, MemberInfo > member_map) inline package
Definition at line 998 of file TypeBuilder.cs.
        {
            if (this.methods != null)
            {
                for (int i = 0; i < this.num_methods; i++)
                {
                    this.methods[i].FixupTokens(token_map, member_map);
                }
            }
            if (this.ctors != null)
            {
                ConstructorBuilder[] array = this.ctors;
                for (int j = 0; j < array.Length; j++)
                {
                    array[j].FixupTokens(token_map, member_map);
                }
            }
            if (this.subtypes != null)
            {
                TypeBuilder[] array2 = this.subtypes;
                for (int j = 0; j < array2.Length; j++)
                {
                    array2[j].FixupTokens(token_map, member_map);
                }
            }
        }
References System.array, System.Reflection.Emit.TypeBuilder.ctors, System.Reflection.Emit.ConstructorBuilder.FixupTokens(), System.Reflection.Emit.MethodBuilder.FixupTokens(), System.Reflection.Emit.TypeBuilder.FixupTokens(), System.Reflection.Emit.TypeBuilder.methods, System.Reflection.Emit.TypeBuilder.num_methods, and System.Reflection.Emit.TypeBuilder.subtypes.
Referenced by System.Reflection.Emit.TypeBuilder.FixupTokens().