Terraria Decompiled: System.Reflection.Emit.TypeBuilder.GetMethod
GetMethod()
static MethodInfo System.Reflection.Emit.TypeBuilder.GetMethod (Type type, MethodInfo method) inline static
Definition at line 2222 of file TypeBuilder.cs.
        {
            if (!TypeBuilder.IsValidGetMethodType(type))
            {
                string text = "type is not TypeBuilder but ";
                Type type2 = type.GetType();
                throw new ArgumentException(text + ((type2 != null) ? type2.ToString() : null), "type");
            }
            if (type is TypeBuilder && type.ContainsGenericParameters)
            {
                type = type.MakeGenericType(type.GetGenericArguments());
            }
            if (!type.IsGenericType)
            {
                throw new ArgumentException("type is not a generic type", "type");
            }
            if (!method.DeclaringType.IsGenericTypeDefinition)
            {
                throw new ArgumentException("method declaring type is not a generic type definition", "method");
            }
            if (method.DeclaringType != type.GetGenericTypeDefinition())
            {
                throw new ArgumentException("method declaring type is not the generic type definition of type", "method");
            }
            if (method == null)
            {
                throw new NullReferenceException();
            }
            MethodInfo method2 = type.GetMethod(method);
            if (method2 == null)
            {
                throw new ArgumentException(string.Format("method {0} not found in type {1}", method.Name, type));
            }
            return method2;
        }
References System.Type.ContainsGenericParameters, System.Runtime.InteropServices._MethodInfo.DeclaringType, System.Format, System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Type.GetMethod(), System.Type.GetType(), System.Type.IsGenericType, System.Type.IsGenericTypeDefinition, System.Reflection.Emit.TypeBuilder.IsValidGetMethodType(), System.Type.MakeGenericType(), System.Runtime.InteropServices._MethodInfo.Name, System.text, System.Type.ToString(), and System.Reflection.TypeInfo.type.
Referenced by System.Reflection.Emit.EventOnTypeBuilderInst.GetAddMethod(), System.Reflection.Emit.PropertyOnTypeBuilderInst.GetGetMethod(), System.Reflection.Emit.EnumBuilder.GetMethodImpl(), System.Reflection.Emit.EventOnTypeBuilderInst.GetOtherMethods(), System.Reflection.Emit.EventOnTypeBuilderInst.GetRaiseMethod(), System.Reflection.Emit.EventOnTypeBuilderInst.GetRemoveMethod(), and System.Reflection.Emit.PropertyOnTypeBuilderInst.GetSetMethod().