Terraria Decompiled: System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor
DefineDefaultConstructor()
ConstructorBuilder System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor (MethodAttributes attributes) inline
Definition at line 543 of file TypeBuilder.cs.
        {
            Type type;
            if (this.parent != null)
            {
                type = this.parent;
            }
            else
            {
                type = this.pmodule.assemblyb.corlib_object_type;
            }
            Type type2 = type;
            type = type.InternalResolve();
            if (type == typeof(object) || type == typeof(ValueType))
            {
                type = type2;
            }
            ConstructorInfo constructor = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);
            if (constructor == null)
            {
                throw new NotSupportedException("Parent does not have a default constructor. The default constructor must be explicitly defined.");
            }
            ConstructorBuilder constructorBuilder = this.DefineConstructor(attributes, CallingConventions.Standard, Type.EmptyTypes);
            ILGenerator ilgenerator = constructorBuilder.GetILGenerator();
            ilgenerator.Emit(OpCodes.Ldarg_0);
            ilgenerator.Emit(OpCodes.Call, constructor);
            ilgenerator.Emit(OpCodes.Ret);
            return constructorBuilder;
        }
References System.Reflection.Emit.ModuleBuilder.assemblyb, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.AssemblyBuilder.corlib_object_type, System.Reflection.Emit.TypeBuilder.DefineConstructor(), System.Reflection.Emit.ILGenerator.Emit(), System.Type.EmptyTypes, System.Type.GetConstructor(), System.Reflection.Emit.ConstructorBuilder.GetILGenerator(), System.Type.InternalResolve(), System.Reflection.Emit.OpCodes.Ldarg_0, System.Reflection.Emit.TypeBuilder.parent, System.Reflection.Emit.TypeBuilder.pmodule, System.Reflection.Emit.OpCodes.Ret, and System.Reflection.TypeInfo.type.
Referenced by System.Reflection.Emit.TypeBuilder.CreateTypeInfo().