Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentManager.CheckRawExtensions
CheckRawExtensions()
Stream Microsoft.Xna.Framework.Content.ContentManager.CheckRawExtensions (string assetName, string[] extensions) inline private
Definition at line 380 of file ContentManager.cs.
        {
            string text = FileHelpers.NormalizeFilePathSeparators(Path.Combine(this.RootDirectoryFullPath, assetName));
            if (File.Exists(text))
            {
                return TitleContainer.OpenStream(text);
            }
            foreach (string text2 in extensions)
            {
                string text3 = text + text2;
                if (File.Exists(text3))
                {
                    return TitleContainer.OpenStream(text3);
                }
            }
            text = FileHelpers.NormalizeFilePathSeparators(assetName);
            try
            {
                return this.OpenStream(text);
            }
            catch
            {
                foreach (string text4 in extensions)
                {
                    string text5 = text + text4;
                    try
                    {
                        return this.OpenStream(text5);
                    }
                    catch
                    {
                    }
                }
            }
            return null;
        }
References System.IO.Path.Combine(), System.IO.File.Exists(), MonoGame.Utilities.FileHelpers.NormalizeFilePathSeparators(), Microsoft.Xna.Framework.Content.ContentManager.OpenStream(), Microsoft.Xna.Framework.TitleContainer.OpenStream(), and System.text.
Referenced by Microsoft.Xna.Framework.Content.ContentManager.OpenStreamRaw< T >().