Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb
GetContentReaderFromXnb()
ContentReader Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb (string originalAssetName, ref Stream stream, BinaryReader xnbReader, char platform, Action< IDisposable > recordDisposableObject) inline private
Definition at line 316 of file ContentManager.cs.
        {
            byte b = xnbReader.ReadByte();
            bool flag = (xnbReader.ReadByte() & 128) > 0;
            if (b != 5 && b != 4)
            {
                throw new ContentLoadException("Invalid XNB version");
            }
            int num = xnbReader.ReadInt32();
            ContentReader contentReader;
            if (flag)
            {
                int num2 = num - 14;
                int num3 = xnbReader.ReadInt32();
                MemoryStream memoryStream = new MemoryStream(new byte[num3], 0, num3, true, true);
                MemoryStream memoryStream2 = new MemoryStream(new byte[num2], 0, num2, true, true);
                stream.Read(memoryStream2.GetBuffer(), 0, num2);
                LzxDecoder lzxDecoder = new LzxDecoder(16);
                int num4 = 0;
                long num5 = 0L;
                while (num5 < (long)num2)
                {
                    int num6 = memoryStream2.ReadByte();
                    int num7 = memoryStream2.ReadByte();
                    int num8 = (num6 << 8) | num7;
                    int num9 = 32768;
                    if (num6 == 255)
                    {
                        int num10 = num7;
                        num7 = (int)((byte)memoryStream2.ReadByte());
                        num9 = (num10 << 8) | num7;
                        int num11 = (int)((byte)memoryStream2.ReadByte());
                        num7 = (int)((byte)memoryStream2.ReadByte());
                        num8 = (num11 << 8) | num7;
                        num5 += 5L;
                    }
                    else
                    {
                        num5 += 2L;
                    }
                    if (num8 == 0 || num9 == 0)
                    {
                        break;
                    }
                    lzxDecoder.Decompress(memoryStream2, num8, memoryStream, num9);
                    num5 += (long)num8;
                    num4 += num9;
                    memoryStream2.Seek(num5, SeekOrigin.Begin);
                }
                if (memoryStream.Position != (long)num3)
                {
                    throw new ContentLoadException("Decompression of " + originalAssetName + " failed. ");
                }
                memoryStream.Seek(0L, SeekOrigin.Begin);
                contentReader = new ContentReader(this, memoryStream, originalAssetName, (int)b, platform, recordDisposableObject);
            }
            else
            {
                contentReader = new ContentReader(this, stream, originalAssetName, (int)b, platform, recordDisposableObject);
            }
            return contentReader;
        }
References Microsoft.Xna.Framework.Content.LzxDecoder.Decompress(), System.IO.MemoryStream.GetBuffer(), int, System.L, long, System.IO.MemoryStream.Position, System.IO.BinaryReader.ReadByte(), System.IO.MemoryStream.ReadByte(), System.IO.BinaryReader.ReadInt32(), and System.IO.MemoryStream.Seek().
Referenced by Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >().