Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >
ReadAsset< T >()
T Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T > (string assetName, Action< IDisposable > recordDisposableObject) inline protected
Definition at line 179 of file ContentManager.cs.
        {
            if (string.IsNullOrEmpty(assetName))
            {
                throw new ArgumentNullException("assetName");
            }
            if (this.disposed)
            {
                throw new ObjectDisposedException("ContentManager");
            }
            object obj = null;
            Stream stream = null;
            try
            {
                stream = this.OpenStream(assetName);
            }
            catch (Exception ex)
            {
                stream = this.OpenStreamRaw<T>(assetName);
                if (stream == null)
                {
                    throw new ContentLoadException("Could not load asset " + assetName + "! Error: " + ex.Message, ex);
                }
            }
            stream.Read(ContentManager.xnbHeader, 0, ContentManager.xnbHeader.Length);
            if (ContentManager.xnbHeader[0] == 88 && ContentManager.xnbHeader[1] == 78 && ContentManager.xnbHeader[2] == 66 && ContentManager.targetPlatformIdentifiers.Contains((char)ContentManager.xnbHeader[3]))
            {
                using (BinaryReader binaryReader = new BinaryReader(stream))
                {
                    using (ContentReader contentReaderFromXnb = this.GetContentReaderFromXnb(assetName, ref stream, binaryReader, (char)ContentManager.xnbHeader[3], recordDisposableObject))
                    {
                        obj = contentReaderFromXnb.ReadAsset<T>();
                        GraphicsResource graphicsResource = obj as GraphicsResource;
                        if (graphicsResource != null)
{
                            graphicsResource.Name = assetName;
                        }
                        goto IL_031F;
                    }
                }
            }
            stream.Seek(0L, SeekOrigin.Begin);
            if (typeof(T) == typeof(Texture2D) || typeof(T) == typeof(Texture))
            {
                Texture2D texture2D;
                if (ContentManager.xnbHeader[0] == 68 && ContentManager.xnbHeader[1] == 68 && ContentManager.xnbHeader[2] == 83 && ContentManager.xnbHeader[3] == 32)
                {
                    texture2D = Texture2D.DDSFromStreamEXT(this.GetGraphicsDevice(), stream);
                }
                else
                {
                    texture2D = Texture2D.FromStream(this.GetGraphicsDevice(), stream);
                }
                texture2D.Name = assetName;
                obj = texture2D;
            }
            else if (typeof(T) == typeof(TextureCube))
            {
                TextureCube textureCube = TextureCube.DDSFromStreamEXT(this.GetGraphicsDevice(), stream);
                textureCube.Name = assetName;
                obj = textureCube;
            }
            else if (typeof(T) == typeof(SoundEffect))
            {
                SoundEffect soundEffect = SoundEffect.FromStream(stream);
                soundEffect.Name = assetName;
                obj = soundEffect;
            }
            else if (typeof(T) == typeof(Effect))
            {
                byte[] array = new byte[stream.Length];
                stream.Read(array, 0, (int)stream.Length);
                obj = new Effect(this.GetGraphicsDevice(), array)
                {
                    Name = assetName
                };
            }
            else if (typeof(T) == typeof(Song))
            {
                string name = (stream as FileStream).Name;
                stream.Close();
                obj = new Song(name, null);
            }
            else
            {
                if (!(typeof(T) == typeof(Video)))
                {
                    stream.Close();
                    throw new ContentLoadException("Could not load " + assetName + " asset!");
                }
                string name2 = (stream as FileStream).Name;
                stream.Close();
                obj = new Video(name2, this.GetGraphicsDevice());
                FNALoggerEXT.LogWarn("Video " + name2 + " does not have an XNB file! Hacking Duration property!");
            }
            IDisposable disposable = obj as IDisposable;
            if (disposable != null)
            {
                if (recordDisposableObject != null)
                {
                    recordDisposableObject(disposable);
                }
                else
                {
                    this.disposableAssets.Add(disposable);
                }
            }
            stream.Close();
            IL_031F:
            return (T)((object)obj);
        }
References System.Collections.Generic.List< T >.Add(), System.array, System.IO.Stream.Close(), System.Collections.Generic.List< T >.Contains(), Microsoft.Xna.Framework.Graphics.Texture2D.DDSFromStreamEXT(), Microsoft.Xna.Framework.Graphics.TextureCube.DDSFromStreamEXT(), Microsoft.Xna.Framework.Content.ContentManager.disposableAssets, Microsoft.Xna.Framework.Content.ContentManager.disposed, Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), Microsoft.Xna.Framework.Audio.SoundEffect.FromStream(), Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb(), Microsoft.Xna.Framework.Content.ContentManager.GetGraphicsDevice(), System.L, System.IO.Stream.Length, Microsoft.Xna.Framework.FNALoggerEXT.LogWarn, System.Exception.Message, System.name, System.Name, System.obj, Microsoft.Xna.Framework.Content.ContentManager.OpenStream(), Microsoft.Xna.Framework.Content.ContentManager.OpenStreamRaw< T >(), System.IO.Stream.Read(), System.IO.Stream.Seek(), Microsoft.Xna.Framework.Content.ContentManager.targetPlatformIdentifiers, and Microsoft.Xna.Framework.Content.ContentManager.xnbHeader.
Referenced by Microsoft.Xna.Framework.Content.ContentManager.Load< T >().