Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentManager.OpenStream
OpenStream()
virtual Stream Microsoft.Xna.Framework.Content.ContentManager.OpenStream (string assetName) inline protected virtual
Reimplemented in Microsoft.Xna.Framework.Content.ResourceContentManager, and ReLogic.Content.Readers.XnbReader.InternalContentManager.
Definition at line 156 of file ContentManager.cs.
        {
            Stream stream;
            try
            {
                stream = TitleContainer.OpenStream(Path.Combine(this.RootDirectory, assetName) + ".xnb");
            }
            catch (FileNotFoundException ex)
            {
                throw new ContentLoadException("The content file was not found.", ex);
            }
            catch (DirectoryNotFoundException ex2)
            {
                throw new ContentLoadException("The directory was not found.", ex2);
            }
            catch (Exception ex3)
            {
                throw new ContentLoadException("Opening stream error.", ex3);
            }
            return stream;
        }
References System.IO.Path.Combine(), and Microsoft.Xna.Framework.TitleContainer.OpenStream().
Referenced by Microsoft.Xna.Framework.Content.ContentManager.CheckRawExtensions(), and Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >().