Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentManager.Unload
Unload()
virtual void Microsoft.Xna.Framework.Content.ContentManager.Unload () inline virtual
Definition at line 142 of file ContentManager.cs.
        {
            foreach (IDisposable disposable in this.disposableAssets)
            {
                if (disposable != null)
                {
                    disposable.Dispose();
                }
            }
            this.disposableAssets.Clear();
            this.loadedAssets.Clear();
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Microsoft.Xna.Framework.Content.ContentManager.disposableAssets, System.IDisposable.Dispose(), and Microsoft.Xna.Framework.Content.ContentManager.loadedAssets.
Referenced by Microsoft.Xna.Framework.Content.ContentManager.Dispose().