Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentManager.GetGraphicsDevice
GetGraphicsDevice()
GraphicsDevice Microsoft.Xna.Framework.Content.ContentManager.GetGraphicsDevice () inline package
Definition at line 301 of file ContentManager.cs.
        {
            if (this.graphicsDevice == null)
            {
                IGraphicsDeviceService graphicsDeviceService = this.ServiceProvider.GetService(typeof(IGraphicsDeviceService)) as IGraphicsDeviceService;
                if (graphicsDeviceService == null)
                {
                    throw new ContentLoadException("No Graphics Device Service");
                }
                this.graphicsDevice = graphicsDeviceService.GraphicsDevice;
            }
            return this.graphicsDevice;
        }
References System.IServiceProvider.GetService(), Microsoft.Xna.Framework.Content.ContentManager.graphicsDevice, Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService.GraphicsDevice, and Microsoft.Xna.Framework.Content.ContentManager.ServiceProvider.
Referenced by Microsoft.Xna.Framework.Content.ModelReader.Read(), Microsoft.Xna.Framework.Content.Texture2DReader.Read(), Microsoft.Xna.Framework.Content.Texture3DReader.Read(), Microsoft.Xna.Framework.Content.TextureCubeReader.Read(), and Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >().