Terraria Decompiled: System.Security.Cryptography.DSACryptoServiceProvider.Common
Common() [2/2]
void System.Security.Cryptography.DSACryptoServiceProvider.Common (int dwKeySize, bool parameters) inline private
Definition at line 47 of file DSACryptoServiceProvider.cs.
        {
            this.LegalKeySizesValue = new KeySizes[1];
            this.LegalKeySizesValue[0] = new KeySizes(512, 1024, 64);
            this.KeySize = dwKeySize;
            this.dsa = new DSAManaged(dwKeySize);
            this.dsa.KeyGenerated += this.OnKeyGenerated;
            this.persistKey = parameters;
            if (parameters)
            {
                return;
            }
            CspParameters cspParameters = new CspParameters(13);
            if (DSACryptoServiceProvider.useMachineKeyStore)
            {
                cspParameters.Flags |= CspProviderFlags.UseMachineKeyStore;
            }
            this.store = new KeyPairPersistence(cspParameters);
        }
References System.Security.Cryptography.AsymmetricAlgorithm.LegalKeySizesValue, System.Security.Cryptography.DSACryptoServiceProvider.OnKeyGenerated(), and System.Security.Cryptography.DSACryptoServiceProvider.useMachineKeyStore.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.DSACryptoServiceProvider(), and System.Security.Cryptography.DSACryptoServiceProvider.DSACryptoServiceProvider().