Terraria Decompiled: System.Security.Cryptography.DSACryptoServiceProvider.OnKeyGenerated
OnKeyGenerated()
void System.Security.Cryptography.DSACryptoServiceProvider.OnKeyGenerated (object sender, EventArgs e) inline private
Definition at line 275 of file DSACryptoServiceProvider.cs.
        {
            if (this.persistKey && !this.persisted)
            {
                this.store.KeyValue = this.ToXmlString(!this.dsa.PublicOnly);
                this.store.Save();
                this.persisted = true;
            }
        }
References System.Security.Cryptography.DSACryptoServiceProvider.dsa, System.Security.Cryptography.DSACryptoServiceProvider.persisted, System.Security.Cryptography.DSACryptoServiceProvider.persistKey, Mono.Security.Cryptography.DSAManaged.PublicOnly, Mono.Security.Cryptography.KeyPairPersistence.Save(), System.Security.Cryptography.DSACryptoServiceProvider.store, and System.Security.Cryptography.DSA.ToXmlString().
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.Common().