Terraria Decompiled: System.Security.Cryptography.DSACryptoServiceProvider.ImportCspBlob
ImportCspBlob()
void System.Security.Cryptography.DSACryptoServiceProvider.ImportCspBlob (byte[] keyBlob) inline
Implements System.Security.Cryptography.ICspAsymmetricAlgorithm.
Definition at line 315 of file DSACryptoServiceProvider.cs.
        {
            if (keyBlob == null)
            {
                throw new ArgumentNullException("keyBlob");
            }
            DSA dsa = CryptoConvert.FromCapiKeyBlobDSA(keyBlob);
            if (dsa is DSACryptoServiceProvider)
            {
                DSAParameters dsaparameters = dsa.ExportParameters(!(dsa as DSACryptoServiceProvider).PublicOnly);
                this.ImportParameters(dsaparameters);
                return;
            }
            try
            {
                DSAParameters dsaparameters2 = dsa.ExportParameters(true);
                this.ImportParameters(dsaparameters2);
            }
            catch
            {
                DSAParameters dsaparameters3 = dsa.ExportParameters(false);
                this.ImportParameters(dsaparameters3);
            }
        }
References System.Security.Cryptography.DSACryptoServiceProvider.dsa, Mono.Security.Cryptography.DSAManaged.ExportParameters(), Mono.Security.Cryptography.CryptoConvert.FromCapiKeyBlobDSA(), System.Security.Cryptography.DSACryptoServiceProvider.ImportParameters(), and System.Security.Cryptography.DSACryptoServiceProvider.PublicOnly.