Terraria Decompiled: System.IO.StreamReader.d__66.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.StreamReader.d__66.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1548 of file StreamReader.cs.
            {
                int num2;
                int num = num2;
                StreamReader streamReader = this;
                int num3;
                try
                {
                    ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter3;
                    ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                    bool flag;
                    switch (num)
                    {
                    case 0:
                        configuredTaskAwaiter3 = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                        num2 = -1;
                        break;
                    case 1:
                    {
                        ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                        num2 = -1;
                        goto IL_01D1;
                    }
                    case 2:
                    {
                        ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                        num2 = -1;
                        goto IL_030F;
                    }
                    default:
                        flag = streamReader._charPos == streamReader._charLen;
                        if (!flag)
{
                            goto IL_009E;
                        }
                        configuredTaskAwaiter3 = streamReader.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter3.IsCompleted)
{
                            num2 = 0;
                            configuredTaskAwaiter2 = configuredTaskAwaiter3;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter, StreamReader.<ReadAsyncInternal>d__66>(ref configuredTaskAwaiter3, ref this);
                            return;
                        }
                        break;
                    }
                    flag = configuredTaskAwaiter3.GetResult() == 0;
                    IL_009E:
                    if (flag)
                    {
                        num3 = 0;
                        goto IL_0507;
                    }
                    charsRead = 0;
                    readToUserBuffer = false;
                    tmpByteBuffer = streamReader._byteBuffer;
                    tmpStream = streamReader._stream;
                    count = buffer.Length;
                    goto IL_04CB;
                    IL_0136:
                    if (streamReader._checkPreamble)
                    {
                        int bytePos = streamReader._bytePos;
                        configuredValueTaskAwaiter = tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer, bytePos, tmpByteBuffer.Length - bytePos), cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num2 = 1;
                            ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, StreamReader.<ReadAsyncInternal>d__66>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        configuredValueTaskAwaiter = tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer), cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num2 = 2;
                            ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, StreamReader.<ReadAsyncInternal>d__66>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                        goto IL_030F;
                    }
                    IL_01D1:
                    int result = configuredValueTaskAwaiter.GetResult();
                    if (result == 0)
                    {
                        if (streamReader._byteLen > 0)
{
                            if (readToUserBuffer)
{
                                i = streamReader._decoder.GetChars(new ReadOnlySpan<byte>(tmpByteBuffer, 0, streamReader._byteLen), buffer.Span.Slice(charsRead), false);
                                streamReader._charLen = 0;
                            }
                            else
{
                                i = streamReader._decoder.GetChars(tmpByteBuffer, 0, streamReader._byteLen, streamReader._charBuffer, 0);
                                streamReader._charLen += i;
                            }
                        }
                        streamReader._isBlocked = true;
                        goto IL_0423;
                    }
                    streamReader._byteLen += result;
                    goto IL_0334;
                    IL_030F:
                    int result2 = configuredValueTaskAwaiter.GetResult();
                    streamReader._byteLen = result2;
                    if (streamReader._byteLen == 0)
                    {
                        streamReader._isBlocked = true;
                        goto IL_0423;
                    }
                    IL_0334:
                    streamReader._isBlocked = streamReader._byteLen < tmpByteBuffer.Length;
                    if (!streamReader.IsPreamble())
                    {
                        if (streamReader._detectEncoding && streamReader._byteLen >= 2)
{
                            streamReader.DetectEncoding();
                            readToUserBuffer = count >= streamReader._maxCharsPerBuffer;
                        }
                        streamReader._charPos = 0;
                        if (readToUserBuffer)
{
                            i += streamReader._decoder.GetChars(new ReadOnlySpan<byte>(tmpByteBuffer, 0, streamReader._byteLen), buffer.Span.Slice(charsRead), false);
                            streamReader._charLen = 0;
                        }
                        else
{
                            i = streamReader._decoder.GetChars(tmpByteBuffer, 0, streamReader._byteLen, streamReader._charBuffer, 0);
                            streamReader._charLen += i;
                        }
                    }
                    if (i == 0)
                    {
                        goto IL_0136;
                    }
                    IL_0423:
                    if (i == 0)
                    {
                        goto IL_04D7;
                    }
                    IL_042E:
                    if (i > count)
                    {
                        i = count;
                    }
                    if (!readToUserBuffer)
                    {
                        new Span<char>(streamReader._charBuffer, streamReader._charPos, i).CopyTo(buffer.Span.Slice(charsRead));
                        streamReader._charPos += i;
                    }
                    charsRead += i;
                    count -= i;
                    if (streamReader._isBlocked)
                    {
                        goto IL_04D7;
                    }
                    IL_04CB:
                    if (count > 0)
                    {
                        i = streamReader._charLen - streamReader._charPos;
                        if (i == 0)
{
                            streamReader._charLen = 0;
                            streamReader._charPos = 0;
                            if (!streamReader._checkPreamble)
{
                                streamReader._byteLen = 0;
                            }
                            readToUserBuffer = count >= streamReader._maxCharsPerBuffer;
                            goto IL_0136;
                        }
                        goto IL_042E;
                    }
                    IL_04D7:
                    num3 = charsRead;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    tmpByteBuffer = null;
                    tmpStream = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_0507:
                num2 = -2;
                tmpByteBuffer = null;
                tmpStream = null;
                this.<>t__builder.SetResult(num3);
            }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._bytePos, System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._decoder, System.IO.StreamReader._detectEncoding, System.IO.StreamReader._isBlocked, System.IO.StreamReader._maxCharsPerBuffer, System.IO.StreamReader._stream, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Span< T >.CopyTo(), System.count, System.IO.StreamReader.DetectEncoding(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Text.Decoder.GetChars(), System.IO.StreamReader.IsPreamble(), System.Memory< T >.Length, System.IO.StreamReader.ReadAsyncInternal(), System.IO.StreamReader.ReadBufferAsync(), and System.Memory< T >.Span.