Terraria Decompiled: Terraria.Player.TryDroppingSingleItem
TryDroppingSingleItem() [2/2]
void Terraria.Player.TryDroppingSingleItem (IEntitySource source, Item theItem, int stack) inline
Definition at line 53701 of file Player.cs.
        {
            if (stack > 0 && Main.netMode != 1)
            {
                int num = Item.NewItem(source, (int)this.position.X, (int)this.position.Y, this.width, this.height, theItem.type, stack, true, (int)theItem.prefix, false);
                WorldItem worldItem = Main.item[num];
                worldItem.velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                worldItem.velocity.X = (float)Main.rand.Next(-20, 21) * 0.2f;
                NetMessage.SendData(21, -1, -1, null, num, 0f, 0f, 0f, 0, 0, 0);
            }
            theItem.stack -= stack;
            if (theItem.stack <= 0)
            {
                theItem.TurnToAir(true);
            }
        }
References Terraria.Main.item, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.prefix, Terraria.Main.rand, Terraria.NetMessage.SendData(), System.source, System.stack, Terraria.Item.stack, Terraria.Item.TurnToAir(), and Terraria.Item.type.