Terraria Decompiled: Terraria.Player.CheckIceBreak
CheckIceBreak()
void Terraria.Player.CheckIceBreak () inline
Definition at line 21834 of file Player.cs.
        {
            if (this.velocity.Y > 7f)
            {
                Vector2 vector = this.position + this.velocity;
                int num = (int)(vector.X / 16f);
                int num2 = (int)((vector.X + (float)this.width) / 16f);
                int num3 = (int)((this.position.Y + (float)this.height + 1f) / 16f);
                for (int i = num; i <= num2; i++)
                {
                    int num4 = num3;
                    while (num4 <= num3 + 1 && Main.tile[i, num4] != null)
                    {
                        if (Main.tile[i, num4].nactive() && Main.tile[i, num4].type == 162 && !WorldGen.SolidTile(i, num4 - 1, false))
{
                            WorldGen.KillTile(i, num4, false, false, false);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)num4, 0f, 0, 0, 0);
                            }
                        }
                        num4++;
                    }
                }
            }
        }
References int, Terraria.WorldGen.KillTile(), Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.type, and Microsoft.Xna.Framework.Vector2.X.