Terraria Decompiled: Terraria.Player.DropSelectedItem_InterruptActionsThatUseAnimations
DropSelectedItem_InterruptActionsThatUseAnimations()
void Terraria.Player.DropSelectedItem_InterruptActionsThatUseAnimations () inline private
Definition at line 2499 of file Player.cs.
        {
            if (this.heldProj >= 0)
            {
                Projectile projectile = Main.projectile[this.heldProj];
                if (projectile.active && projectile.owner == this.whoAmI)
                {
                    projectile.Kill();
                }
            }
            for (int i = 0; i < 1000; i++)
            {
                Projectile projectile2 = Main.projectile[i];
                if (projectile2.active && projectile2.owner == this.whoAmI && (projectile2.aiStyle == 61 || projectile2.aiStyle == 160))
                {
                    projectile2.Kill();
                }
            }
        }
References Terraria.Projectile.active, Terraria.Projectile.aiStyle, Terraria.Player.heldProj, Terraria.Projectile.Kill(), Terraria.Projectile.owner, and Terraria.Main.projectile.
Referenced by Terraria.Player.DropSelectedItem(), and Terraria.Player.PlayDroppedItemAnimation().