Terraria Decompiled: Terraria.Player.Spawn_IsAreaValidSpawn
Spawn_IsAreaValidSpawn()
static bool Terraria.Player.Spawn_IsAreaValidSpawn (int floorX, int floorY, bool generatingSpawn = false) inline static
Definition at line 36853 of file Player.cs.
        {
            for (int i = floorX - 1; i < floorX + 2; i++)
            {
                for (int j = floorY - 3; j < floorY; j++)
                {
                    if (WorldGen.InWorld(i, j, 0) && Main.tile[i, j] != null)
                    {
                        Tile tile = Main.tile[i, j];
                        if (tile.nactive() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type])
{
                            return false;
                        }
                        if (tile.liquid > 0)
{
                            return false;
                        }
                        if (generatingSpawn && Main.dualDungeonsSeed && ((tile.active() && DungeonUtils.IsConsideredDungeonTile((int)tile.type, true)) || DungeonUtils.IsConsideredDungeonWall((int)tile.wall, true)))
{
                            return false;
                        }
                    }
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Main.dualDungeonsSeed, Terraria.WorldGen.InWorld(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.Player.Shellphone_Spawn(), Terraria.Player.Spawn_GetPositionAtSpawn(), Terraria.Player.Spawn_SetPositionAtTeamSpawn(), and Terraria.Player.Spawn_SetPositionAtWorldSpawn().