Terraria Decompiled: Terraria.Player.PlaceThing_XMasTreeTops
PlaceThing_XMasTreeTops()
void Terraria.Player.PlaceThing_XMasTreeTops () inline private
Definition at line 40736 of file Player.cs.
        {
            if (this.inventory[this.selectedItem].type >= 1874 && this.inventory[this.selectedItem].type <= 1905 && Main.tile[Player.tileTargetX, Player.tileTargetY].active() && Main.tile[Player.tileTargetX, Player.tileTargetY].type == 171 && this.IsInTileInteractionRange(Player.tileTargetX, Player.tileTargetY, TileReachCheckSettings.Simple, this.inventory[this.selectedItem].tileBoost + this.blockRange) && this.ItemTimeIsZero && this.itemAnimation > 0 && this.controlUseItem)
            {
                int num = this.inventory[this.selectedItem].type;
                if (num >= 1874 && num <= 1877)
                {
                    num -= 1873;
                    if (WorldGen.checkXmasTreeDrop(Player.tileTargetX, Player.tileTargetY, 0) != num)
                    {
                        this.ApplyItemTime(this.inventory[this.selectedItem]);
                        WorldGen.dropXmasTree(Player.tileTargetX, Player.tileTargetY, 0);
                        WorldGen.setXmasTree(Player.tileTargetX, Player.tileTargetY, 0, num);
                        int num2 = Player.tileTargetX;
                        int num3 = Player.tileTargetY;
                        if (Main.tile[Player.tileTargetX, Player.tileTargetY].frameX < 10)
{
                            num2 -= (int)Main.tile[Player.tileTargetX, Player.tileTargetY].frameX;
                            num3 -= (int)Main.tile[Player.tileTargetX, Player.tileTargetY].frameY;
                        }
                        NetMessage.SendTileSquare(-1, num2, num3, TileChangeType.None);
                        return;
                    }
                }
                else if (num >= 1878 && num <= 1883)
                {
                    num -= 1877;
                    if (WorldGen.checkXmasTreeDrop(Player.tileTargetX, Player.tileTargetY, 1) != num)
                    {
                        this.ApplyItemTime(this.inventory[this.selectedItem]);
                        WorldGen.dropXmasTree(Player.tileTargetX, Player.tileTargetY, 1);
                        WorldGen.setXmasTree(Player.tileTargetX, Player.tileTargetY, 1, num);
                        int num4 = Player.tileTargetX;
                        int num5 = Player.tileTargetY;
                        if (Main.tile[Player.tileTargetX, Player.tileTargetY].frameX < 10)
{
                            num4 -= (int)Main.tile[Player.tileTargetX, Player.tileTargetY].frameX;
                            num5 -= (int)Main.tile[Player.tileTargetX, Player.tileTargetY].frameY;
                        }
                        NetMessage.SendTileSquare(-1, num4, num5, TileChangeType.None);
                        return;
                    }
                }
                else if (num >= 1884 && num <= 1894)
                {
                    num -= 1883;
                    if (WorldGen.checkXmasTreeDrop(Player.tileTargetX, Player.tileTargetY, 2) != num)
                    {
                        this.ApplyItemTime(this.inventory[this.selectedItem]);
                        WorldGen.dropXmasTree(Player.tileTargetX, Player.tileTargetY, 2);
                        WorldGen.setXmasTree(Player.tileTargetX, Player.tileTargetY, 2, num);
                        int num6 = Player.tileTargetX;
                        int num7 = Player.tileTargetY;
                        if (Main.tile[Player.tileTargetX, Player.tileTargetY].frameX < 10)
{
                            num6 -= (int)Main.tile[Player.tileTargetX, Player.tileTargetY].frameX;
                            num7 -= (int)Main.tile[Player.tileTargetX, Player.tileTargetY].frameY;
                        }
                        NetMessage.SendTileSquare(-1, num6, num7, TileChangeType.None);
                        return;
                    }
                }
                else if (num >= 1895 && num <= 1905)
                {
                    num -= 1894;
                    if (WorldGen.checkXmasTreeDrop(Player.tileTargetX, Player.tileTargetY, 3) != num)
                    {
                        this.ApplyItemTime(this.inventory[this.selectedItem]);
                        WorldGen.dropXmasTree(Player.tileTargetX, Player.tileTargetY, 3);
                        WorldGen.setXmasTree(Player.tileTargetX, Player.tileTargetY, 3, num);
                        int num8 = Player.tileTargetX;
                        int num9 = Player.tileTargetY;
                        if (Main.tile[Player.tileTargetX, Player.tileTargetY].frameX < 10)
{
                            num8 -= (int)Main.tile[Player.tileTargetX, Player.tileTargetY].frameX;
                            num9 -= (int)Main.tile[Player.tileTargetX, Player.tileTargetY].frameY;
                        }
                        NetMessage.SendTileSquare(-1, num8, num9, TileChangeType.None);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.checkXmasTreeDrop(), Terraria.WorldGen.dropXmasTree(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.setXmasTree(), Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, and Terraria.Tile.type.