Terraria Decompiled: Terraria.Player.QuickMana
QuickMana()
void Terraria.Player.QuickMana () inline
Definition at line 2859 of file Player.cs.
        {
            if (Main.LocalPlayerHasPendingInventoryActions())
            {
                return;
            }
            if (this.cursed || this.CCed || this.dead)
            {
                return;
            }
            if (this.statMana == this.statManaMax2)
            {
                return;
            }
            Item item = this.QuickMana_GetItemToUse();
            if (item == null)
            {
                return;
            }
            if (!this.ItemCheck_TryStartUse(item, false))
            {
                return;
            }
            if (this.mount.Active && Mount.DismountsOnItemUse(this.mount.Type))
            {
                this.mount.TryEarlyDismount(this);
            }
            SoundEngine.PlaySound(item.UseSound, this.position, 0f, 1f);
            if (item.potion)
            {
                this.ApplyPotionDelay(item);
            }
            this.ApplyLifeAndOrMana(item);
            if (this.CanConsumeConsumableItem(item))
            {
                item.stack--;
                if (item.stack <= 0)
                {
                    item.TurnToAir(false);
                }
            }
        }
References Terraria.Mount.Active, Terraria.Player.ApplyLifeAndOrMana(), Terraria.Player.ApplyPotionDelay(), Terraria.Player.CanConsumeConsumableItem(), Terraria.Player.CCed, Terraria.Player.cursed, Terraria.Player.dead, Terraria.Mount.DismountsOnItemUse(), System.item, Terraria.Player.ItemCheck_TryStartUse(), Terraria.Main.LocalPlayerHasPendingInventoryActions(), Terraria.Player.mount, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.QuickMana_GetItemToUse(), Terraria.Player.statMana, Terraria.Player.statManaMax2, and Terraria.Mount.TryEarlyDismount().