Terraria Decompiled: Terraria.Player.ChangeDir
ChangeDir()
void Terraria.Player.ChangeDir (int dir) inline
Definition at line 41147 of file Player.cs.
        {
            if (dir == this.direction)
            {
                return;
            }
            if (this.pulley && this.pulleyDir == 2)
            {
                int num = (int)(this.position.X + (float)(this.width / 2)) / 16 * 16 + 8 - this.width / 2;
                if (Collision.SolidCollision(new Vector2((float)num, this.position.Y), this.width, this.height))
                {
                    return;
                }
                if (this.whoAmI == Main.myPlayer)
                {
                    Main.cameraX = Main.cameraX + this.position.X - (float)num;
                }
                this.pulleyDir = 1;
                this.position.X = (float)num;
            }
            this.direction = dir;
            this.compositeBackArm.rotation = this.compositeBackArm.rotation * -1f;
            this.compositeFrontArm.rotation = this.compositeFrontArm.rotation * -1f;
            this.itemRotation *= -1f;
            this.itemLocation.X = this.MountedCenter.X + (this.MountedCenter.X - this.itemLocation.X);
        }
References int, Terraria.Main.myPlayer, and Terraria.Collision.SolidCollision().
Referenced by Terraria.Projectile.AI(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_015_Flails_Old(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_075(), Terraria.Projectile.AI_099_1_Counterweights(), Terraria.Projectile.AI_099_2_Yoyos(), Terraria.Projectile.AI_100_Medusa(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.Projectile.AI_198_Flint(), Terraria.Projectile.KiteLogic(), Terraria.GameContent.PlayerSittingHelper.SitDown(), Terraria.GameContent.PlayerSleepingHelper.StartSleeping(), and Terraria.Cinematics.DSTFilm.TurnPlayerToTheLeft().