Terraria Decompiled: Terraria.Player.HandleSpectatingControls
HandleSpectatingControls()
void Terraria.Player.HandleSpectatingControls () inline private
Definition at line 15323 of file Player.cs.
        {
            if (PlayerInput.Triggers.JustReleased.Jump || this.controlInv || this.controlThrow || this.controlTorch || this.controlSmart || this.controlMount || this.controlQuickHeal || this.controlQuickMana || this.controlCreativeMenu || this.controlDash || this.controlArmorSetAbility || PlayerInput.Triggers.Current.Hotbar1 || PlayerInput.Triggers.Current.Hotbar2 || PlayerInput.Triggers.Current.Hotbar3 || PlayerInput.Triggers.Current.Hotbar4 || PlayerInput.Triggers.Current.Hotbar5 || PlayerInput.Triggers.Current.Hotbar6 || PlayerInput.Triggers.Current.Hotbar7 || PlayerInput.Triggers.Current.Hotbar8 || PlayerInput.Triggers.Current.Hotbar9 || PlayerInput.Triggers.Current.Hotbar10 || PlayerInput.Triggers.Current.HotbarPlus || PlayerInput.Triggers.Current.HotbarMinus || PlayerInput.ScrollWheelDelta != 0)
            {
                this.afkCounter = Math.Min(this.afkCounter, Player.AFKTimeNeededForNoWormSpawns);
                this.afkCounterForKiting = Math.Min(this.afkCounterForKiting, Player.AFKTimeNeededForAutoKiting);
                this.SetOrRequestSpectating(-1);
                return;
            }
            if (this.CanWormholeToSpectating() && PlayerInput.Triggers.JustPressed.QuickBuff)
            {
                Player player = Main.player[this.spectating];
                this.UnityTeleport(this.position + player.Bottom - base.Bottom);
                this.TakeUnityPotion();
                return;
            }
            int num = 0;
            if (PlayerInput.Triggers.JustPressed.Right || (!PlayerInput.UsingGamepad && PlayerInput.Triggers.JustPressed.MouseLeft))
            {
                num++;
            }
            if (PlayerInput.Triggers.JustPressed.Left || (!PlayerInput.UsingGamepad && PlayerInput.Triggers.JustPressed.MouseRight))
            {
                num--;
            }
            if (num != 0)
            {
                bool flag = this.SpectateNextPlayer(num, this.dead);
                if (!this.dead && this.inventory[this.selectedItem].type == 5644)
                {
                    if (flag)
                    {
                        SoundEngine.PlaySound(SoundID.Item197, -1, -1, 0f, 1f);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item198, -1, -1, 0f, 1f);
                    }
                }
                if (!flag && !this.dead)
                {
                    PunchCameraModifier punchCameraModifier = new PunchCameraModifier(this.position, new Vector2(1f, 0f), 5f, 6f, 15, -1f, "NoMoreTargets");
                    punchCameraModifier.IsAScreenShake = false;
                    Main.instance.CameraModifiers.Add(punchCameraModifier);
                }
            }
        }
References Terraria.Graphics.CameraModifiers.CameraModifierStack.Add(), Terraria.Player.AFKTimeNeededForAutoKiting, Terraria.Player.AFKTimeNeededForNoWormSpawns, Terraria.Entity.Bottom, Terraria.Main.CameraModifiers, Terraria.GameInput.TriggersPack.Current, Terraria.GameInput.TriggersSet.Hotbar1, Terraria.GameInput.TriggersSet.Hotbar10, Terraria.GameInput.TriggersSet.Hotbar2, Terraria.GameInput.TriggersSet.Hotbar3, Terraria.GameInput.TriggersSet.Hotbar4, Terraria.GameInput.TriggersSet.Hotbar5, Terraria.GameInput.TriggersSet.Hotbar6, Terraria.GameInput.TriggersSet.Hotbar7, Terraria.GameInput.TriggersSet.Hotbar8, Terraria.GameInput.TriggersSet.Hotbar9, Terraria.GameInput.TriggersSet.HotbarMinus, Terraria.GameInput.TriggersSet.HotbarPlus, Terraria.Main.instance, Terraria.ID.SoundID.Item197, Terraria.ID.SoundID.Item198, Terraria.GameInput.TriggersSet.Jump, Terraria.GameInput.TriggersPack.JustPressed, Terraria.GameInput.TriggersPack.JustReleased, Terraria.GameInput.TriggersSet.Left, System.Math.Min(), Terraria.GameInput.TriggersSet.MouseLeft, Terraria.GameInput.TriggersSet.MouseRight, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameInput.TriggersSet.QuickBuff, Terraria.GameInput.TriggersSet.Right, Terraria.GameInput.PlayerInput.ScrollWheelDelta, Terraria.GameInput.PlayerInput.Triggers, and Terraria.GameInput.PlayerInput.UsingGamepad.