Terraria Decompiled: Terraria.Player.TryGetFlexibleWandAvailableUsageCount
TryGetFlexibleWandAvailableUsageCount()
bool Terraria.Player.TryGetFlexibleWandAvailableUsageCount (Item wandItem, out int amount) inline
Definition at line 40554 of file Player.cs.
        {
            amount = 0;
            FlexibleTileWand flexibleTileWand = wandItem.GetFlexibleTileWand();
            if (flexibleTileWand == null)
            {
                return false;
            }
            if (!flexibleTileWand.ConsumesAmmoItem)
            {
                return false;
            }
            FlexibleTileWand.PlacementOption placementOption;
            Item item;
            if (!flexibleTileWand.TryGetPlacementOption(this, Player.FlexibleWandRandomSeed, Player.FlexibleWandCycleOffset, out placementOption, out item))
            {
                return false;
            }
            amount = this.CountItem(item.type, 0);
            return true;
        }
References Terraria.GameContent.FlexibleTileWand.ConsumesAmmoItem, Terraria.Player.FlexibleWandCycleOffset, Terraria.Player.FlexibleWandRandomSeed, Terraria.Item.GetFlexibleTileWand(), System.item, and Terraria.GameContent.FlexibleTileWand.TryGetPlacementOption().
Referenced by Terraria.UI.ItemSlot.Draw().