Terraria Decompiled: Terraria.Player.QuickHeal
QuickHeal()
void Terraria.Player.QuickHeal () inline
Definition at line 2747 of file Player.cs.
        {
            if (Main.LocalPlayerHasPendingInventoryActions())
            {
                return;
            }
            if (this.cursed || this.CCed || this.dead)
            {
                return;
            }
            if (this.statLife == this.statLifeMax2 || this.potionDelay > 0)
            {
                return;
            }
            Item item = this.QuickHeal_GetItemToUse();
            if (item == null)
            {
                return;
            }
            if (!this.ItemCheck_TryStartUse(item, false))
            {
                return;
            }
            if (this.mount.Active && Mount.DismountsOnItemUse(this.mount.Type))
            {
                this.mount.TryEarlyDismount(this);
            }
            SoundEngine.PlaySound(item.UseSound, this.position, 0f, 1f);
            if (item.potion)
            {
                this.ApplyPotionDelay(item);
            }
            this.ApplyLifeAndOrMana(item);
            if (item.type == 5)
            {
                this.TryToResetHungerToNeutral();
            }
            if (item.buffType > 0)
            {
                int num = item.buffTime;
                if (num == 0)
                {
                    num = 3600;
                }
                this.AddBuff(item.buffType, num, false);
            }
            if (this.CanConsumeConsumableItem(item))
            {
                item.stack--;
                if (item.stack <= 0)
                {
                    item.TurnToAir(false);
                }
            }
            if (Main.myPlayer == this.whoAmI && item.type == 126 && this.breath == 0)
            {
                AchievementsHelper.HandleSpecialEvent(this, 25);
            }
        }
References Terraria.Mount.Active, Terraria.Player.AddBuff(), Terraria.Player.ApplyLifeAndOrMana(), Terraria.Player.ApplyPotionDelay(), Terraria.Item.buffType, Terraria.Player.CanConsumeConsumableItem(), Terraria.Player.CCed, Terraria.Player.cursed, Terraria.Player.dead, Terraria.Mount.DismountsOnItemUse(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), System.item, Terraria.Player.ItemCheck_TryStartUse(), Terraria.Main.LocalPlayerHasPendingInventoryActions(), Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.potionDelay, Terraria.Player.QuickHeal_GetItemToUse(), Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Mount.TryEarlyDismount(), and Terraria.Player.TryToResetHungerToNeutral().