Terraria Decompiled: Terraria.Player.OpenBossBag
OpenBossBag()
void Terraria.Player.OpenBossBag (int type) inline
Definition at line 4460 of file Player.cs.
        {
            bool masterMode = Main.masterMode;
            IEntitySource itemSource_OpenItem = this.GetItemSource_OpenItem(type);
            if (type == 3318)
            {
                if (Main.rand.Next(2) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2430, 1);
                }
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2493, 1);
                }
                int num = Main.rand.Next(256, 259);
                int num2;
                for (num2 = Main.rand.Next(256, 259); num2 == num; num2 = Main.rand.Next(256, 259))
                {
                }
                this.QuickSpawnItem(itemSource_OpenItem, num, 1);
                this.QuickSpawnItem(itemSource_OpenItem, num2, 1);
                if (Main.rand.Next(2) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2610, 1);
                }
                else
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2585, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 998, 1);
                if (Main.rand.Next(30) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1309, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 3090, 1);
            }
            else if (type == 3319)
            {
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2112, 1);
                }
                if (Main.rand.Next(30) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1299, 1);
                }
                short num3 = (WorldGen.crimson ? 880 : 56);
                int num4 = Main.rand.Next(21) + 10;
                num4 += Main.rand.Next(21) + 10;
                num4 += Main.rand.Next(21) + 10;
                this.QuickSpawnItem(itemSource_OpenItem, (int)num3, num4);
                num3 = (WorldGen.crimson ? 2171 : 59);
                num4 = Main.rand.Next(3) + 1;
                this.QuickSpawnItem(itemSource_OpenItem, (int)num3, num4);
                num4 = Main.rand.Next(31) + 20;
                this.QuickSpawnItem(itemSource_OpenItem, 47, num4);
                this.QuickSpawnItem(itemSource_OpenItem, 3097, 1);
            }
            else if (type == 3320)
            {
                int num5 = Main.rand.Next(15, 30);
                if (masterMode)
                {
                    num5 = Main.rand.Next(110, 136);
                    this.QuickSpawnItem(itemSource_OpenItem, 56, num5);
                }
                else
                {
                    num5 = Main.rand.Next(80, 111);
                    this.QuickSpawnItem(itemSource_OpenItem, 56, num5);
                }
                if (masterMode)
                {
                    num5 = Main.rand.Next(30, 51);
                    this.QuickSpawnItem(itemSource_OpenItem, 86, num5);
                }
                else
                {
                    num5 = Main.rand.Next(20, 41);
                    this.QuickSpawnItem(itemSource_OpenItem, 86, num5);
                }
                if (Main.rand.Next(20) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 994, 1);
                }
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2111, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 3224, 1);
            }
            else if (type == 3321)
            {
                int num6 = Main.rand.Next(20, 46);
                if (masterMode)
                {
                    num6 = Main.rand.Next(110, 136);
                    this.QuickSpawnItem(itemSource_OpenItem, 880, num6);
                }
                else
                {
                    num6 = Main.rand.Next(80, 111);
                    this.QuickSpawnItem(itemSource_OpenItem, 880, num6);
                }
                if (masterMode)
                {
                    num6 = Main.rand.Next(30, 51);
                    this.QuickSpawnItem(itemSource_OpenItem, 1329, num6);
                }
                else
                {
                    num6 = Main.rand.Next(20, 41);
                    this.QuickSpawnItem(itemSource_OpenItem, 1329, num6);
                }
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2104, 1);
                }
                if (Main.rand.Next(20) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3060, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 3223, 1);
            }
            else if (type == 3322)
            {
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2108, 1);
                }
                int num7 = Main.rand.Next(3);
                if (num7 == 0)
                {
                    num7 = 1121;
                }
                else if (num7 == 1)
                {
                    num7 = 1123;
                }
                else if (num7 == 2)
                {
                    num7 = 2888;
                }
                this.QuickSpawnItem(itemSource_OpenItem, num7, 1);
                this.QuickSpawnItem(itemSource_OpenItem, 3333, 1);
                if (Main.rand.Next(3) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1132, 1);
                }
                if (Main.rand.Next(9) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1170, 1);
                }
                if (Main.rand.Next(9) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2502, 1);
                }
                if (Main.rand.Next(9) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5483, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 1129, 1);
                this.QuickSpawnItem(itemSource_OpenItem, Main.rand.Next(842, 845), 1);
                this.QuickSpawnItem(itemSource_OpenItem, 1130, Main.rand.Next(10, 31));
                this.QuickSpawnItem(itemSource_OpenItem, 2431, Main.rand.Next(17, 31));
            }
            else if (type == 3323)
            {
                this.QuickSpawnItem(itemSource_OpenItem, 3245, 1);
                int num8 = Main.rand.Next(3);
                if (num8 == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1281, 1);
                }
                else if (num8 == 1)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1273, 1);
                }
                else
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1313, 1);
                }
            }
            else if (type == 3324)
            {
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2105, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 367, 1);
                if (!this.extraAccessory)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3335, 1);
                }
                int num9 = Main.rand.Next(4);
                if (num9 == 3)
                {
                    num9 = 2998;
                }
                else
                {
                    num9 = 489 + num9;
                }
                this.QuickSpawnItem(itemSource_OpenItem, num9, 1);
                int num10 = Main.rand.Next(4);
                if (num10 == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 514, 1);
                }
                else if (num10 == 1)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 426, 1);
                }
                else if (num10 == 2)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 434, 1);
                }
                else if (num10 == 3)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4912, 1);
                }
            }
            else if (type == 3325)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2113, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 548, Main.rand.Next(25, 41));
                this.QuickSpawnItem(itemSource_OpenItem, 1225, Main.rand.Next(20, 36));
                this.QuickSpawnItem(itemSource_OpenItem, 3355, 1);
            }
            else if (type == 3326)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2106, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 549, Main.rand.Next(25, 41));
                this.QuickSpawnItem(itemSource_OpenItem, 1225, Main.rand.Next(20, 36));
                this.QuickSpawnItem(itemSource_OpenItem, 3354, 1);
            }
            else if (type == 3327)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2107, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 547, Main.rand.Next(25, 41));
                this.QuickSpawnItem(itemSource_OpenItem, 1225, Main.rand.Next(20, 36));
                this.QuickSpawnItem(itemSource_OpenItem, 3356, 1);
            }
            else if (type == 3328)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2109, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 1141, 1);
                this.QuickSpawnItem(itemSource_OpenItem, 3336, 1);
                if (Main.rand.Next(15) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1182, 1);
                }
                if (Main.rand.Next(20) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1305, 1);
                }
                if (Main.rand.Next(2) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1157, 1);
                }
                if (Main.rand.Next(10) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3021, 1);
                }
                int num11 = Main.rand.Next(8);
                if (num11 == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 758, 1);
                    this.QuickSpawnItem(itemSource_OpenItem, 771, Main.rand.Next(50, 151));
                }
                else if (num11 == 1)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1255, 1);
                }
                else if (num11 == 2)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 788, 1);
                }
                else if (num11 == 3)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1178, 1);
                }
                else if (num11 == 4)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1259, 1);
                }
                else if (num11 == 5)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1155, 1);
                }
                else if (num11 == 6)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3018, 1);
                }
                else if (num11 == 7)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5477, 1);
                }
            }
            else if (type == 3329)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                this.QuickSpawnItem(itemSource_OpenItem, 3337, 1);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2110, 1);
                }
                if (Main.rand.Next(3) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1294, 1);
                }
                int num12 = Main.rand.Next(7);
                if (num12 == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1258, 1);
                    this.QuickSpawnItem(itemSource_OpenItem, 1261, Main.rand.Next(60, 181));
                }
                else if (num12 == 1)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1122, 1);
                }
                else if (num12 == 2)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 899, 1);
                }
                else if (num12 == 3)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1248, 1);
                }
                else if (num12 == 4)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1295, 1);
                }
                else if (num12 == 5)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1296, 1);
                }
                else
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 1297, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 2218, Main.rand.Next(18, 24));
            }
            else if (type == 3330)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                this.QuickSpawnItem(itemSource_OpenItem, 3367, 1);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2588, 1);
                }
                if (Main.rand.Next(10) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2609, 1);
                }
                int num13 = Main.rand.Next(6);
                if (num13 == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5526, 1);
                }
                else if (num13 == 1)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2624, 1);
                }
                else if (num13 == 2)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2622, 1);
                }
                else if (num13 == 3)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 2621, 1);
                }
                else if (num13 == 4)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5478, 1);
                }
                else if (num13 == 5)
                {
                    if (Main.remixWorld)
                    {
                        this.QuickSpawnItem(itemSource_OpenItem, 157, 1);
                    }
                    else
                    {
                        this.QuickSpawnItem(itemSource_OpenItem, 2623, 1);
                    }
                }
            }
            else if (type == 3331)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3372, 1);
                }
            }
            else if (type == 3860)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3863, 1);
                }
                int num14 = Main.rand.Next(4);
                if (num14 == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3859, 1);
                }
                else if (num14 == 1)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3827, 1);
                }
                else if (num14 == 2)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3870, 1);
                }
                else
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3858, 1);
                }
                if (Main.rand.Next(4) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3883, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 3817, Main.rand.Next(30, 51));
            }
            else if (type == 4782)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                this.QuickSpawnItem(itemSource_OpenItem, 4989, 1);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4784, 1);
                }
                if (Main.rand.Next(10) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4823, 1);
                }
                if (Main.rand.Next(20) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4715, 1);
                }
                if (Main.rand.Next(4) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4778, 3);
                }
                if (Main.rand.Next(20) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5075, 1);
                }
                int num15 = Main.rand.Next(4);
                if (num15 == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4923, 1);
                }
                else if (num15 == 1)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4952, 1);
                }
                else if (num15 == 2)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4953, 1);
                }
                else if (num15 == 3)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4914, 1);
                }
            }
            else if (type == 4957)
            {
                this.QuickSpawnItem(itemSource_OpenItem, 4987, 1);
                this.QuickSpawnItem(itemSource_OpenItem, 4986, Main.rand.Next(25, 76));
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4959, 1);
                }
                if (Main.rand.Next(2) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4981, 1);
                }
                if (Main.rand.Next(3) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4758, 1);
                }
                if (Main.rand.Next(2) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4980, 1);
                }
                int num16 = Main.rand.Next(4982, 4985);
                int num17 = Main.rand.Next(4982, 4985);
                while (num17 == num16)
                {
                    num16 = Main.rand.Next(4982, 4985);
                }
                this.QuickSpawnItem(itemSource_OpenItem, num16, 1);
                this.QuickSpawnItem(itemSource_OpenItem, num17, 1);
            }
            if (type == 5111)
            {
                this.QuickSpawnItem(itemSource_OpenItem, 5100, 1);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5109, 1);
                }
                if (Main.rand.Next(14) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5385, 1);
                }
                if (Main.rand.Next(3) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5098, 1);
                }
                if (Main.rand.Next(3) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5101, 1);
                }
                if (Main.rand.Next(3) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5113, 1);
                }
                int num18 = Main.rand.Next(4);
                if (num18 == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5117, 1);
                }
                else if (num18 == 1)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5118, 1);
                }
                else if (num18 == 2)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5119, 1);
                }
                else if (num18 == 3)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 5095, 1);
                }
            }
            else if (type == 3332)
            {
                this.TryGettingDevArmor(itemSource_OpenItem);
                if (Main.rand.Next(7) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3373, 1);
                }
                if (Main.rand.Next(10) == 0)
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 4469, 1);
                }
                if (!this.HasItem(3384))
                {
                    this.QuickSpawnItem(itemSource_OpenItem, 3384, 1);
                }
                this.QuickSpawnItem(itemSource_OpenItem, 3460, Main.rand.Next(90, 111));
                this.QuickSpawnItem(itemSource_OpenItem, 1131, 1);
                this.QuickSpawnItem(itemSource_OpenItem, 3577, 1);
                this.QuickSpawnItem(itemSource_OpenItem, 4954, 1);
                List<int> list = new List<int> { 3063, 3389, 3065, 1553, 3930, 3541, 3570, 3571, 3569, 5480 };
                for (int i = 0; i < 2; i++)
                {
                    int num19 = Main.rand.Next(list.Count);
                    int num20 = list[num19];
                    this.QuickSpawnItem(itemSource_OpenItem, num20, 1);
                    list.RemoveAt(num19);
                }
            }
            int num21 = -1;
            if (type == 3318)
            {
                num21 = 50;
            }
            if (type == 3319)
            {
                num21 = 4;
            }
            if (type == 3320)
            {
                num21 = 13;
            }
            if (type == 3321)
            {
                num21 = 266;
            }
            if (type == 3322)
            {
                num21 = 222;
            }
            if (type == 3323)
            {
                num21 = 35;
            }
            if (type == 3324)
            {
                num21 = 113;
            }
            if (type == 3325)
            {
                num21 = 134;
            }
            if (type == 3326)
            {
                num21 = 125;
            }
            if (type == 3327)
            {
                num21 = 127;
            }
            if (type == 3328)
            {
                num21 = 262;
            }
            if (type == 3329)
            {
                num21 = 245;
            }
            if (type == 3330)
            {
                num21 = 370;
            }
            if (type == 3331)
            {
                num21 = 439;
            }
            if (type == 3332)
            {
                num21 = 398;
            }
            if (type == 3860)
            {
                num21 = 551;
            }
            if (type == 3861)
            {
                num21 = 576;
            }
            if (type == 3862)
            {
                num21 = 564;
            }
            if (type == 4782)
            {
                num21 = 636;
            }
            if (type == 4957)
            {
                num21 = 657;
            }
            if (type == 5111)
            {
                num21 = 668;
            }
            if (num21 > 0)
            {
                NPC npc = new NPC();
                npc.SetDefaults(num21, default(NPCSpawnParams));
                float num22 = npc.value;
                num22 *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                if (Main.rand.Next(5) == 0)
                {
                    num22 *= 1f + (float)Main.rand.Next(5, 11) * 0.01f;
                }
                if (Main.rand.Next(10) == 0)
                {
                    num22 *= 1f + (float)Main.rand.Next(10, 21) * 0.01f;
                }
                if (Main.rand.Next(15) == 0)
                {
                    num22 *= 1f + (float)Main.rand.Next(15, 31) * 0.01f;
                }
                if (Main.rand.Next(20) == 0)
                {
                    num22 *= 1f + (float)Main.rand.Next(20, 41) * 0.01f;
                }
                while ((int)num22 > 0)
                {
                    if (num22 > 1000000f)
                    {
                        int num23 = (int)(num22 / 1000000f);
                        num22 -= (float)(1000000 * num23);
                        this.QuickSpawnItem(itemSource_OpenItem, 74, num23);
                    }
                    else if (num22 > 10000f)
                    {
                        int num24 = (int)(num22 / 10000f);
                        num22 -= (float)(10000 * num24);
                        this.QuickSpawnItem(itemSource_OpenItem, 73, num24);
                    }
                    else if (num22 > 100f)
                    {
                        int num25 = (int)(num22 / 100f);
                        num22 -= (float)(100 * num25);
                        this.QuickSpawnItem(itemSource_OpenItem, 72, num25);
                    }
                    else
                    {
                        int num26 = (int)num22;
                        if (num26 < 1)
{
                            num26 = 1;
                        }
                        num22 -= (float)num26;
                        this.QuickSpawnItem(itemSource_OpenItem, 71, num26);
                    }
                }
            }
        }
References Terraria.Player.extraAccessory, Terraria.Player.GetItemSource_OpenItem(), Terraria.Player.HasItem(), int, System.list, Terraria.Main.masterMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Enums.NPC, Terraria.Player.QuickSpawnItem(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NPC.SetDefaults(), Terraria.Player.TryGettingDevArmor(), and Terraria.NPC.value.
Referenced by Terraria.UI.ItemSlot.TryOpenContainer_GrantItems().