Terraria Decompiled: Terraria.Player.DoBootsEffect_PlaceFlowersOnTile
DoBootsEffect_PlaceFlowersOnTile()
bool Terraria.Player.DoBootsEffect_PlaceFlowersOnTile (int X, int Y) inline
Definition at line 11723 of file Player.cs.
        {
            Tile tile = Main.tile[X, Y];
            if (tile == null)
            {
                return false;
            }
            if (!tile.active() && tile.liquid == 0 && Main.tile[X, Y + 1] != null && WorldGen.SolidTile(X, Y + 1, false))
            {
                tile.frameY = 0;
                tile.slope(0);
                tile.halfBrick(false);
                if (Main.tile[X, Y + 1].type == 2 || Main.tile[X, Y + 1].type == 477)
                {
                    int num = Main.rand.NextFromList(new int[]
                    {
                        6, 7, 9, 10, 11, 12, 13, 14, 15, 16,
                        17, 18, 19, 20, 21, 24, 27, 30, 33, 36,
                        39, 42
                    });
                    if (num <= 30)
                    {
                        if (num <= 24)
{
                            if (num != 21 && num != 24)
{
                                goto IL_00FA;
                            }
                        }
                        else if (num != 27 && num != 30)
{
                            goto IL_00FA;
                        }
                    }
                    else if (num <= 36)
                    {
                        if (num != 33 && num != 36)
{
                            goto IL_00FA;
                        }
                    }
                    else if (num != 39 && num != 42)
                    {
                        goto IL_00FA;
                    }
                    num += Main.rand.Next(3);
                    IL_00FA:
                    tile.active(true);
                    tile.type = 3;
                    tile.frameX = (short)(num * 18);
                    tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendTileSquare(-1, X, Y, TileChangeType.None);
                    }
                    return true;
                }
                if (Main.tile[X, Y + 1].type == 109 || Main.tile[X, Y + 1].type == 492)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        tile.active(true);
                        tile.type = 110;
                        tile.frameX = (short)(18 * Main.rand.Next(4, 7));
                        tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                        while (tile.frameX == 90)
{
                            tile.frameX = (short)(18 * Main.rand.Next(4, 7));
                        }
                    }
                    else
                    {
                        tile.active(true);
                        tile.type = 113;
                        tile.frameX = (short)(18 * Main.rand.Next(2, 8));
                        tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                        while (tile.frameX == 90)
{
                            tile.frameX = (short)(18 * Main.rand.Next(2, 8));
                        }
                    }
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendTileSquare(-1, X, Y, TileChangeType.None);
                    }
                    return true;
                }
                if (Main.tile[X, Y + 1].type == 60)
                {
                    tile.active(true);
                    tile.type = 74;
                    tile.frameX = (short)(18 * Main.rand.Next(9, 17));
                    tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendTileSquare(-1, X, Y, TileChangeType.None);
                    }
                    return true;
                }
                if (Main.tile[X, Y + 1].type == 633)
                {
                    tile.active(true);
                    tile.type = 637;
                    tile.frameX = (short)(18 * Main.rand.Next(6, 11));
                    tile.CopyPaintAndCoating(Main.tile[X, Y + 1]);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendTileSquare(-1, X, Y, TileChangeType.None);
                    }
                    return true;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.CopyPaintAndCoating(), Terraria.Tile.frameX, Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.type, System.X, and System.Y.