Terraria Decompiled: Terraria.Player.TileInteractionsCheckLongDistance
TileInteractionsCheckLongDistance()
void Terraria.Player.TileInteractionsCheckLongDistance (int myX, int myY) inline private
Definition at line 30694 of file Player.cs.
        {
            if (!WorldGen.InWorld(myX, myY, 10))
            {
                return;
            }
            if (Main.tile[myX, myY] == null || !Main.tile[myX, myY].active())
            {
                return;
            }
            if (TileID.Sets.BasicChest[(int)Main.tile[myX, myY].type])
            {
                this.TileInteractionsMouseOver_Containers(myX, myY);
                if (this.cursorItemIconText == "")
                {
                    this.cursorItemIconEnabled = false;
                    this.cursorItemIconID = 0;
                }
            }
            if (Main.tile[myX, myY].type == 88)
            {
                Tile tile = Main.tile[myX, myY];
                int num = myY;
                int num2 = myX - (int)(tile.frameX % 54 / 18);
                if (tile.frameY % 36 != 0)
                {
                    num--;
                }
                int num3 = Chest.FindChest(num2, num);
                this.cursorItemIconID = -1;
                if (num3 < 0)
                {
                    this.cursorItemIconText = Lang.dresserType[0].Value;
                }
                else
                {
                    if (Main.chest[num3].name != "")
                    {
                        this.cursorItemIconText = Main.chest[num3].name;
                    }
                    else
                    {
                        this.cursorItemIconText = Lang.dresserType[(int)(tile.frameX / 54)].Value;
                    }
                    if (this.cursorItemIconText == Lang.dresserType[(int)(tile.frameX / 54)].Value)
                    {
                        this.cursorItemIconID = Chest.dresserTypeToIcon[(int)(tile.frameX / 54)];
                        this.cursorItemIconText = "";
                    }
                }
                this.noThrow = 2;
                this.cursorItemIconEnabled = true;
                if (this.cursorItemIconText == "")
                {
                    this.cursorItemIconEnabled = false;
                    this.cursorItemIconID = 0;
                }
            }
            if (Main.tileSign[(int)Main.tile[myX, myY].type])
            {
                this.noThrow = 2;
                int num4 = (int)(Main.tile[myX, myY].frameX / 18);
                int num5 = (int)(Main.tile[myX, myY].frameY / 18);
                num4 %= 2;
                int num6 = myX - num4;
                int num7 = myY - num5;
                Main.signBubble = true;
                Main.signX = num6 * 16 + 16;
                Main.signY = num7 * 16;
                int num8 = Sign.ReadSign(num6, num7, false);
                if (num8 != -1 && Player.tileTargetX >= num6 && Player.tileTargetY >= num7 && Player.tileTargetX <= num6 + 1 && Player.tileTargetY <= num7 + 1)
                {
                    Main.signHover = num8;
                    this.cursorItemIconEnabled = false;
                    this.cursorItemIconID = -1;
                }
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BasicChest, Terraria.Main.chest, Terraria.Lang.dresserType, Terraria.Chest.dresserTypeToIcon, Terraria.Chest.FindChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.WorldGen.InWorld(), Terraria.Chest.name, Terraria.Sign.ReadSign(), Terraria.Main.tile, Terraria.Main.tileSign, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Tile.type, and Terraria.Localization.LocalizedText.Value.