Terraria Decompiled: Terraria.Player.CollectTaxes
CollectTaxes()
void Terraria.Player.CollectTaxes () inline
Definition at line 22609 of file Player.cs.
        {
            int num = Item.buyPrice(0, 0, 0, 50);
            int num2 = Item.buyPrice(0, 25, 0, 0);
            if (Main.tenthAnniversaryWorld)
            {
                num2 *= 2;
                num *= 2;
            }
            if (!NPC.taxCollector)
            {
                return;
            }
            if (this.taxMoney >= num2)
            {
                return;
            }
            int num3 = 0;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && !Main.npc[i].homeless && !NPCID.Sets.IsTownPet[Main.npc[i].type] && NPC.TypeToDefaultHeadIndex(Main.npc[i].type) > 0)
                {
                    num3++;
                }
            }
            this.taxMoney += num * num3;
            if (this.taxMoney > num2)
            {
                this.taxMoney = num2;
            }
        }
References Terraria.NPC.active, Terraria.Item.buyPrice(), Terraria.NPC.homeless, Terraria.ID.NPCID.Sets.IsTownPet, Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.NPC.taxCollector, Terraria.Main.tenthAnniversaryWorld, Terraria.NPC.type, and Terraria.NPC.TypeToDefaultHeadIndex().
Referenced by Terraria.Main.UpdateTime().