Terraria Decompiled: Terraria.Player.GetFishingConditions
GetFishingConditions()
PlayerFishingConditions Terraria.Player.GetFishingConditions () inline
Definition at line 41255 of file Player.cs.
        {
            PlayerFishingConditions playerFishingConditions = default(PlayerFishingConditions);
            this.Fishing_GetBestFishingPole(out playerFishingConditions.PolePower, out playerFishingConditions.PoleItemType);
            this.Fishing_GetBait(out playerFishingConditions.BaitPower, out playerFishingConditions.BaitItemType);
            if (playerFishingConditions.BaitItemType == 2673)
            {
                return playerFishingConditions;
            }
            if (playerFishingConditions.BaitPower == 0 || playerFishingConditions.PolePower == 0)
            {
                return playerFishingConditions;
            }
            int num = 0;
            if (this.FindBuffIndex(25) != -1)
            {
                num += 5;
            }
            if (this.canFloatInWater && this.wet)
            {
                num += 5;
            }
            Tile tile;
            if (this.sitting.TryGetSittingBlock(this, out tile))
            {
                num += 5;
            }
            int num2 = playerFishingConditions.BaitPower + playerFishingConditions.PolePower + this.fishingSkill + num;
            playerFishingConditions.LevelMultipliers = Player.Fishing_GetPowerMultiplier();
            playerFishingConditions.FinalFishingLevel = (int)((float)num2 * playerFishingConditions.LevelMultipliers);
            return playerFishingConditions;
        }
References Terraria.DataStructures.PlayerFishingConditions.BaitItemType, Terraria.DataStructures.PlayerFishingConditions.BaitPower, Terraria.Player.Fishing_GetPowerMultiplier(), int, Terraria.DataStructures.PlayerFishingConditions.LevelMultipliers, Terraria.DataStructures.PlayerFishingConditions.PoleItemType, and Terraria.DataStructures.PlayerFishingConditions.PolePower.
Referenced by Terraria.Projectile.AI_061_FishingBobber(), Terraria.Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Terraria.Main.DrawInfoAccs(), and Terraria.Projectile.TryBuildFishingContext().