Terraria Decompiled: Terraria.Player.SellItem
SellItem()
bool Terraria.Player.SellItem (Item item, int stack = -1) inline
Definition at line 33931 of file Player.cs.
        {
            long num;
            long num2;
            this.GetItemExpectedPrice(item, out num, out num2);
            if (num <= 0L)
            {
                return false;
            }
            if (stack == -1)
            {
                stack = item.stack;
            }
            Item[] array = new Item[58];
            for (int i = 0; i < 58; i++)
            {
                array[i] = this.inventory[i].Clone();
            }
            long num3 = num / 5L;
            if (num3 < 1L)
            {
                num3 = 1L;
            }
            long num4 = num3;
            num3 *= (long)stack;
            int amount = Main.shopSellbackHelper.GetAmount(item);
            if (amount > 0)
            {
                num3 += (-num4 + num2) * (long)Math.Min(amount, item.stack);
            }
            bool flag = false;
            while (num3 >= 1000000L)
            {
                if (flag)
                {
                    break;
                }
                int num5 = -1;
                for (int j = 53; j >= 0; j--)
                {
                    if (num5 == -1 && (this.inventory[j].type == 0 || this.inventory[j].stack == 0))
                    {
                        num5 = j;
                    }
                    while (this.inventory[j].type == 74 && this.inventory[j].stack < this.inventory[j].maxStack && num3 >= 1000000L)
                    {
                        this.inventory[j].stack++;
                        num3 -= 1000000L;
                        this.DoCoins(j);
                        if (this.inventory[j].stack == 0 && num5 == -1)
{
                            num5 = j;
                        }
                    }
                }
                if (num3 >= 1000000L)
                {
                    if (num5 == -1)
                    {
                        flag = true;
                    }
                    else
                    {
                        this.inventory[num5].SetDefaults(74, null);
                        num3 -= 1000000L;
                    }
                }
            }
            while (num3 >= 10000L)
            {
                if (flag)
                {
                    break;
                }
                int num6 = -1;
                for (int k = 53; k >= 0; k--)
                {
                    if (num6 == -1 && (this.inventory[k].type == 0 || this.inventory[k].stack == 0))
                    {
                        num6 = k;
                    }
                    while (this.inventory[k].type == 73 && this.inventory[k].stack < this.inventory[k].maxStack && num3 >= 10000L)
                    {
                        this.inventory[k].stack++;
                        num3 -= 10000L;
                        this.DoCoins(k);
                        if (this.inventory[k].stack == 0 && num6 == -1)
{
                            num6 = k;
                        }
                    }
                }
                if (num3 >= 10000L)
                {
                    if (num6 == -1)
                    {
                        flag = true;
                    }
                    else
                    {
                        this.inventory[num6].SetDefaults(73, null);
                        num3 -= 10000L;
                    }
                }
            }
            while (num3 >= 100L)
            {
                if (flag)
                {
                    break;
                }
                int num7 = -1;
                for (int l = 53; l >= 0; l--)
                {
                    if (num7 == -1 && (this.inventory[l].type == 0 || this.inventory[l].stack == 0))
                    {
                        num7 = l;
                    }
                    while (this.inventory[l].type == 72 && this.inventory[l].stack < this.inventory[l].maxStack && num3 >= 100L)
                    {
                        this.inventory[l].stack++;
                        num3 -= 100L;
                        this.DoCoins(l);
                        if (this.inventory[l].stack == 0 && num7 == -1)
{
                            num7 = l;
                        }
                    }
                }
                if (num3 >= 100L)
                {
                    if (num7 == -1)
                    {
                        flag = true;
                    }
                    else
                    {
                        this.inventory[num7].SetDefaults(72, null);
                        num3 -= 100L;
                    }
                }
            }
            while (num3 >= 1L && !flag)
            {
                int num8 = -1;
                for (int m = 53; m >= 0; m--)
                {
                    if (num8 == -1 && (this.inventory[m].type == 0 || this.inventory[m].stack == 0))
                    {
                        num8 = m;
                    }
                    while (this.inventory[m].type == 71 && this.inventory[m].stack < this.inventory[m].maxStack && num3 >= 1L)
                    {
                        this.inventory[m].stack++;
                        num3 -= 1L;
                        this.DoCoins(m);
                        if (this.inventory[m].stack == 0 && num8 == -1)
{
                            num8 = m;
                        }
                    }
                }
                if (num3 >= 1L)
                {
                    if (num8 == -1)
                    {
                        flag = true;
                    }
                    else
                    {
                        this.inventory[num8].SetDefaults(71, null);
                        num3 -= 1L;
                    }
                }
            }
            if (flag)
            {
                for (int n = 0; n < 58; n++)
                {
                    this.inventory[n] = array[n];
                }
                return false;
            }
            return true;
        }
References System.array, Terraria.Item.Clone(), Terraria.GameContent.ItemShopSellbackHelper.GetAmount(), System.item, System.L, long, System.Math.Min(), Terraria.Main.shopSellbackHelper, and System.stack.
Referenced by Terraria.UI.ItemSlot.LeftClick(), and Terraria.UI.ItemSlot.OverrideLeftClick().