Terraria Decompiled: Terraria.Player.GetCurrentContainer
GetCurrentContainer()
Chest Terraria.Player.GetCurrentContainer () inline
Definition at line 32207 of file Player.cs.
        {
            switch (this.chest)
            {
            case -5:
                return this.bank4;
            case -4:
                return this.bank3;
            case -3:
                return this.bank2;
            case -2:
                return this.bank;
            case -1:
                return null;
            default:
                return Main.chest[this.chest];
            }
        }
References Terraria.Main.chest.
Referenced by Terraria.Recipe.CollectItemsFromChests(), Terraria.UI.ChestUI.DepositAll(), Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), Terraria.UI.ItemSlot.PickItemMovementAction(), Terraria.UI.ChestUI.QuickStack(), Terraria.UI.ItemSorting.SortChest(), Terraria.Main.TryInteractingWithMoneyTrough(), Terraria.Main.TryInteractingWithVoidLens(), and Terraria.UI.ChestUI.TryPlacingInChest().