Terraria Decompiled: Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings
PlaceThing_Tiles_BlockPlacementForAssortedThings()
bool Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings (bool canPlace) inline private
Definition at line 40012 of file Player.cs.
        {
            if (this.HeldItem.type == 213 || this.HeldItem.type == 5295)
            {
                this.staffOfRegrowthBonus = true;
            }
            bool flag = this.staffOfRegrowthBonus;
            if (flag)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY].type == 0 || Main.tile[Player.tileTargetX, Player.tileTargetY].type == 1 || Main.tile[Player.tileTargetX, Player.tileTargetY].type == 38)
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 2 || this.inventory[this.selectedItem].createTile == 109)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY].nactive() && Main.tile[Player.tileTargetX, Player.tileTargetY].type == 0)
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile >= 0 && Main.tileMoss[this.inventory[this.selectedItem].createTile])
            {
                Tile tile = Main.tile[Player.tileTargetX, Player.tileTargetY];
                if (tile.nactive() && (tile.type == 1 || tile.type == 38))
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 23 || this.inventory[this.selectedItem].createTile == 199)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY].nactive())
                {
                    if (Main.tile[Player.tileTargetX, Player.tileTargetY].type == 0)
                    {
                        canPlace = true;
                    }
                    else if (Main.tile[Player.tileTargetX, Player.tileTargetY].type == 59)
                    {
                        canPlace = true;
                    }
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 227)
            {
                canPlace = true;
            }
            else if (TileID.Sets.IsADripTile[this.inventory[this.selectedItem].createTile])
            {
                int num = Player.tileTargetX;
                int num2 = Player.tileTargetY - 1;
                if (Main.tile[num, num2].nactive() && Main.tileSolid[(int)Main.tile[num, num2].type] && !Main.tileSolidTop[(int)Main.tile[num, num2].type])
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 60 || this.inventory[this.selectedItem].createTile == 70 || this.inventory[this.selectedItem].createTile == 661 || this.inventory[this.selectedItem].createTile == 662)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY].nactive() && Main.tile[Player.tileTargetX, Player.tileTargetY].type == 59)
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 633)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY].nactive() && Main.tile[Player.tileTargetX, Player.tileTargetY].type == 57)
                {
                    canPlace = true;
                }
            }
            else if (TileID.Sets.Torches[this.inventory[this.selectedItem].createTile] || this.inventory[this.selectedItem].createTile == 136)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY].wall > 0)
                {
                    canPlace = true;
                }
                else
                {
                    if (!WorldGen.SolidTileNoAttach(Player.tileTargetX, Player.tileTargetY + 1) && !WorldGen.SolidTileNoAttach(Player.tileTargetX - 1, Player.tileTargetY) && !WorldGen.SolidTileNoAttach(Player.tileTargetX + 1, Player.tileTargetY))
                    {
                        if (!WorldGen.SolidTileNoAttach(Player.tileTargetX, Player.tileTargetY + 1) && (Main.tile[Player.tileTargetX, Player.tileTargetY + 1].halfBrick() || Main.tile[Player.tileTargetX, Player.tileTargetY + 1].slope() != 0))
{
                            if (!TileID.Sets.Platforms[(int)Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type])
{
                                WorldGen.SlopeTile(Player.tileTargetX, Player.tileTargetY + 1, 0, false, true);
                                if (Main.netMode == 1)
{
                                    NetMessage.SendData(17, -1, -1, null, 14, (float)Player.tileTargetX, (float)(Player.tileTargetY + 1), 0f, 0, 0, 0);
                                }
                            }
                        }
                        else if (!WorldGen.SolidTileNoAttach(Player.tileTargetX, Player.tileTargetY + 1) && !WorldGen.SolidTileNoAttach(Player.tileTargetX - 1, Player.tileTargetY) && (Main.tile[Player.tileTargetX - 1, Player.tileTargetY].halfBrick() || Main.tile[Player.tileTargetX - 1, Player.tileTargetY].slope() != 0))
{
                            if (!TileID.Sets.Platforms[(int)Main.tile[Player.tileTargetX - 1, Player.tileTargetY].type])
{
                                WorldGen.SlopeTile(Player.tileTargetX - 1, Player.tileTargetY, 0, false, true);
                                if (Main.netMode == 1)
{
                                    NetMessage.SendData(17, -1, -1, null, 14, (float)(Player.tileTargetX - 1), (float)Player.tileTargetY, 0f, 0, 0, 0);
                                }
                            }
                        }
                        else if (!WorldGen.SolidTileNoAttach(Player.tileTargetX, Player.tileTargetY + 1) && !WorldGen.SolidTileNoAttach(Player.tileTargetX + 1, Player.tileTargetY) && (Main.tile[Player.tileTargetX + 1, Player.tileTargetY].halfBrick() || Main.tile[Player.tileTargetX + 1, Player.tileTargetY].slope() != 0) && !TileID.Sets.Platforms[(int)Main.tile[Player.tileTargetX + 1, Player.tileTargetY].type])
{
                            WorldGen.SlopeTile(Player.tileTargetX + 1, Player.tileTargetY, 0, false, true);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 14, (float)(Player.tileTargetX + 1), (float)Player.tileTargetY, 0f, 0, 0, 0);
                            }
                        }
                    }
                    int num3 = (int)Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type;
                    if (Main.tile[Player.tileTargetX, Player.tileTargetY].halfBrick())
                    {
                        num3 = -1;
                    }
                    int num4 = (int)Main.tile[Player.tileTargetX - 1, Player.tileTargetY].type;
                    int num5 = (int)Main.tile[Player.tileTargetX + 1, Player.tileTargetY].type;
                    int num6 = (int)Main.tile[Player.tileTargetX - 1, Player.tileTargetY - 1].type;
                    int num7 = (int)Main.tile[Player.tileTargetX + 1, Player.tileTargetY - 1].type;
                    int num8 = (int)Main.tile[Player.tileTargetX - 1, Player.tileTargetY - 1].type;
                    int num9 = (int)Main.tile[Player.tileTargetX + 1, Player.tileTargetY + 1].type;
                    if (!Main.tile[Player.tileTargetX, Player.tileTargetY + 1].nactive())
                    {
                        num3 = -1;
                    }
                    if (!Main.tile[Player.tileTargetX - 1, Player.tileTargetY].nactive())
                    {
                        num4 = -1;
                    }
                    if (!Main.tile[Player.tileTargetX + 1, Player.tileTargetY].nactive())
                    {
                        num5 = -1;
                    }
                    if (!Main.tile[Player.tileTargetX - 1, Player.tileTargetY - 1].nactive())
                    {
                        num6 = -1;
                    }
                    if (!Main.tile[Player.tileTargetX + 1, Player.tileTargetY - 1].nactive())
                    {
                        num7 = -1;
                    }
                    if (!Main.tile[Player.tileTargetX - 1, Player.tileTargetY + 1].nactive())
                    {
                        num8 = -1;
                    }
                    if (!Main.tile[Player.tileTargetX + 1, Player.tileTargetY + 1].nactive())
                    {
                        num9 = -1;
                    }
                    if (num3 >= 0 && Main.tileSolid[num3] && (!Main.tileNoAttach[num3] || (num3 >= 0 && TileID.Sets.Platforms[num3])))
                    {
                        canPlace = true;
                    }
                    else if ((num4 >= 0 && Main.tileSolid[num4] && !Main.tileNoAttach[num4]) || (WorldGen.IsTreeType(num4) && WorldGen.IsTreeType(num6) && WorldGen.IsTreeType(num8)) || (num4 >= 0 && TileID.Sets.IsBeam[num4]))
                    {
                        canPlace = true;
                    }
                    else if ((num5 >= 0 && Main.tileSolid[num5] && !Main.tileNoAttach[num5]) || (WorldGen.IsTreeType(num5) && WorldGen.IsTreeType(num7) && WorldGen.IsTreeType(num9)) || (num5 >= 0 && TileID.Sets.IsBeam[num5]))
                    {
                        canPlace = true;
                    }
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 78 || this.inventory[this.selectedItem].createTile == 98 || this.inventory[this.selectedItem].createTile == 100 || this.inventory[this.selectedItem].createTile == 173 || this.inventory[this.selectedItem].createTile == 174 || this.inventory[this.selectedItem].createTile == 324)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY + 1].nactive() && (Main.tileSolid[(int)Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type] || Main.tileTable[(int)Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type]))
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 419)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY + 1].active() && (Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type == 419 || (this.inventory[this.selectedItem].placeStyle != 2 && Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type == 420)))
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 13 || this.inventory[this.selectedItem].createTile == 29 || this.inventory[this.selectedItem].createTile == 33 || this.inventory[this.selectedItem].createTile == 49 || this.inventory[this.selectedItem].createTile == 50 || this.inventory[this.selectedItem].createTile == 103)
            {
                if (Main.tile[Player.tileTargetX, Player.tileTargetY + 1].nactive() && Main.tileTable[(int)Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type])
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 275 || this.inventory[this.selectedItem].createTile == 276 || this.inventory[this.selectedItem].createTile == 277)
            {
                canPlace = true;
            }
            else if (this.inventory[this.selectedItem].createTile == 51 || this.inventory[this.selectedItem].createTile == 697 || this.inventory[this.selectedItem].createTile == 330 || this.inventory[this.selectedItem].createTile == 331 || this.inventory[this.selectedItem].createTile == 332 || this.inventory[this.selectedItem].createTile == 333 || this.inventory[this.selectedItem].createTile == 336 || this.inventory[this.selectedItem].createTile == 340 || this.inventory[this.selectedItem].createTile == 342 || this.inventory[this.selectedItem].createTile == 341 || this.inventory[this.selectedItem].createTile == 343 || this.inventory[this.selectedItem].createTile == 344 || this.inventory[this.selectedItem].createTile == 379 || this.inventory[this.selectedItem].createTile == 351)
            {
                if (Main.tile[Player.tileTargetX + 1, Player.tileTargetY].active() || Main.tile[Player.tileTargetX + 1, Player.tileTargetY].wall > 0 || Main.tile[Player.tileTargetX - 1, Player.tileTargetY].active() || Main.tile[Player.tileTargetX - 1, Player.tileTargetY].wall > 0 || Main.tile[Player.tileTargetX, Player.tileTargetY + 1].active() || Main.tile[Player.tileTargetX, Player.tileTargetY + 1].wall > 0 || Main.tile[Player.tileTargetX, Player.tileTargetY - 1].active() || Main.tile[Player.tileTargetX, Player.tileTargetY - 1].wall > 0)
                {
                    canPlace = true;
                }
            }
            else if (this.inventory[this.selectedItem].createTile == 314)
            {
                for (int i = Player.tileTargetX - 1; i <= Player.tileTargetX + 1; i++)
                {
                    for (int j = Player.tileTargetY - 1; j <= Player.tileTargetY + 1; j++)
                    {
                        Tile tile2 = Main.tile[i, j];
                        if (tile2.active() || tile2.wall > 0)
{
                            canPlace = true;
                            break;
                        }
                    }
                }
            }
            else
            {
                Tile tile3 = Main.tile[Player.tileTargetX - 1, Player.tileTargetY];
                Tile tile4 = Main.tile[Player.tileTargetX + 1, Player.tileTargetY];
                Tile tile5 = Main.tile[Player.tileTargetX, Player.tileTargetY - 1];
                Tile tile6 = Main.tile[Player.tileTargetX, Player.tileTargetY + 1];
                if ((tile4.active() && (Main.tileSolid[(int)tile4.type] || TileID.Sets.IsBeam[(int)tile4.type] || Main.tileRope[(int)tile4.type] || tile4.type == 314)) || (tile4.wall > 0 || (tile3.active() && (Main.tileSolid[(int)tile3.type] || TileID.Sets.IsBeam[(int)tile3.type] || Main.tileRope[(int)tile3.type] || tile3.type == 314))) || (tile3.wall > 0 || (tile6.active() && (Main.tileSolid[(int)tile6.type] || TileID.Sets.IsBeam[(int)tile6.type] || Main.tileRope[(int)tile6.type] || tile6.type == 314))) || (tile6.wall > 0 || (tile5.active() && (Main.tileSolid[(int)tile5.type] || TileID.Sets.IsBeam[(int)tile5.type] || Main.tileRope[(int)tile5.type] || tile5.type == 314))) || tile5.wall > 0)
                {
                    canPlace = true;
                }
                else if (Main.tile[Player.tileTargetX, Player.tileTargetY].wall > 0)
                {
                    canPlace = true;
                }
            }
            if (flag && Main.tile[Player.tileTargetX, Player.tileTargetY].active())
            {
                int num10 = Player.tileTargetX;
                int num11 = Player.tileTargetY;
                if (Main.tile[num10, num11].type == 3 || Main.tile[num10, num11].type == 73 || Main.tile[num10, num11].type == 84)
                {
                    int type = (int)Main.tile[num10, num11].type;
                    int num12 = (int)(Main.tile[num10, num11].frameX / 18);
                    WorldGen.KillTile(Player.tileTargetX, Player.tileTargetY, false, false, false);
                    if (!Main.tile[Player.tileTargetX, Player.tileTargetY].active())
                    {
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                        if (type == 84)
{
                            this.TryReplantingHerbs(num12);
                        }
                    }
                }
                else if (Main.tile[num10, num11].type == 83)
                {
                    int num13 = (int)(Main.tile[num10, num11].frameX / 18);
                    if (WorldGen.IsAlchemyPlantHarvestable(num13, num11))
                    {
                        WorldGen.KillTile(Player.tileTargetX, Player.tileTargetY, false, false, false);
                        NetMessage.SendData(17, -1, -1, null, 0, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        this.TryReplantingHerbs(num13);
                    }
                }
            }
            if (Main.tileAlch[this.inventory[this.selectedItem].createTile])
            {
                canPlace = true;
            }
            bool flag2 = true;
            if (flag && !canPlace)
            {
                flag2 = false;
            }
            if (flag2 && Main.tile[Player.tileTargetX, Player.tileTargetY].active() && (Main.tileCut[(int)Main.tile[Player.tileTargetX, Player.tileTargetY].type] || TileID.Sets.BreakableWhenPlacing[(int)Main.tile[Player.tileTargetX, Player.tileTargetY].type] || TileID.Sets.IsADripTile[(int)Main.tile[Player.tileTargetX, Player.tileTargetY].type]))
            {
                if ((int)Main.tile[Player.tileTargetX, Player.tileTargetY].type != this.inventory[this.selectedItem].createTile)
                {
                    bool flag3 = Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type != 78 && Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type != 380 && Main.tile[Player.tileTargetX, Player.tileTargetY + 1].type != 579;
                    bool flag4 = Main.tile[Player.tileTargetX, Player.tileTargetY].type == 3 || Main.tile[Player.tileTargetX, Player.tileTargetY].type == 73;
                    bool flag5 = TileID.Sets.IsVine[(int)Main.tile[Player.tileTargetX, Player.tileTargetY].type];
                    bool flag6 = TileID.Sets.IsADripTile[(int)Main.tile[Player.tileTargetX, Player.tileTargetY].type];
                    bool flag7 = Main.tile[Player.tileTargetX, Player.tileTargetY].type == 165;
                    bool flag8 = Main.tileAlch[(int)Main.tile[Player.tileTargetX, Player.tileTargetY].type] && WorldGen.IsHarvestableHerbWithSeed((int)Main.tile[Player.tileTargetX, Player.tileTargetY].type, (int)(Main.tile[Player.tileTargetX, Player.tileTargetY].frameX / 18), Player.tileTargetY);
                    bool flag9 = Main.tileAlch[this.inventory[this.selectedItem].createTile];
                    if (flag3 || ((flag4 || flag5 || flag6 || flag7 || flag8) && flag9))
                    {
                        WorldGen.KillTile(Player.tileTargetX, Player.tileTargetY, false, false, false);
                        if (!Main.tile[Player.tileTargetX, Player.tileTargetY].active() && Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                    }
                    else
                    {
                        canPlace = false;
                    }
                }
                else
                {
                    canPlace = false;
                }
            }
            if (!canPlace && this.inventory[this.selectedItem].createTile >= 0 && TileID.Sets.Platforms[this.inventory[this.selectedItem].createTile])
            {
                for (int k = Player.tileTargetX - 1; k <= Player.tileTargetX + 1; k++)
                {
                    for (int l = Player.tileTargetY - 1; l <= Player.tileTargetY + 1; l++)
                    {
                        if (Main.tile[k, l].active())
{
                            canPlace = true;
                            break;
                        }
                    }
                }
            }
            if (this.inventory[this.selectedItem].createTile == 3)
            {
                canPlace = WorldGen.IsFitToPlaceFlowerIn(Player.tileTargetX, Player.tileTargetY, 3);
                if (canPlace)
                {
                    WorldGen.KillTile(Player.tileTargetX, Player.tileTargetY, false, false, false);
                    if (Main.netMode == 1 && !Main.tile[Player.tileTargetX, Player.tileTargetY].active())
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                    }
                }
            }
            this.staffOfRegrowthBonus = false;
            return canPlace;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.Tile.frameX, Terraria.Tile.halfBrick(), int, Terraria.ID.TileID.Sets.IsADripTile, Terraria.WorldGen.IsAlchemyPlantHarvestable(), Terraria.ID.TileID.Sets.IsBeam, Terraria.WorldGen.IsFitToPlaceFlowerIn(), Terraria.WorldGen.IsHarvestableHerbWithSeed(), Terraria.WorldGen.IsTreeType(), Terraria.ID.TileID.Sets.IsVine, Terraria.WorldGen.KillTile(), Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.ID.TileID.Sets.Platforms, Terraria.NetMessage.SendData(), Terraria.Tile.slope(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SolidTileNoAttach(), Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileCut, Terraria.Main.tileMoss, Terraria.Main.tileNoAttach, Terraria.Main.tileRope, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.tileTable, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.ID.TileID.Sets.Torches, Terraria.Tile.type, and Terraria.Tile.wall.