Terraria Decompiled: Terraria.Player.KazzymodusWingDust
KazzymodusWingDust()
void Terraria.Player.KazzymodusWingDust (bool noDustLight, bool justSwitched) inline private
Definition at line 29269 of file Player.cs.
        {
            if (Main.netMode == 2 || this.wingFrame == 0)
            {
                return;
            }
            Color color = new Color(50, 120, 255, 200);
            if (justSwitched && this.wingFrame == 1)
            {
                float num = -20f * this.gravDir;
                Point point = new Point(30, 10);
                for (int i = 0; i < 16; i++)
                {
                    int num2 = ((i < 4) ? (-25 * this.direction) : (-5 * this.direction));
                    Vector2 vector = base.Center + new Vector2((float)num2, num) - point.ToVector2() / 2f;
                    float num3 = 1.2f;
                    Dust dust = Dust.NewDustDirect(vector, point.X, point.Y, 6, 0f, 0f, 100, color, num3);
                    dust.velocity.X = Main.rand.NextFloatDirection() * 5f;
                    dust.velocity.Y = Main.rand.NextFloatDirection() * 2f;
                    dust.fadeIn = num3;
                    dust.noGravity = true;
                    dust.noLightEmittance = noDustLight;
                    dust.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                }
            }
            if (Main.rand.Next(4) == 0)
            {
                bool flag = Main.rand.Next(2) == 0;
                Point point2 = new Point(25, 20);
                int num4 = this.direction * (flag ? (-30) : 10);
                float num5 = this.gravDir * (float)((this.wingFrame == 1) ? (-25) : (-5));
                Vector2 vector2 = base.Center + new Vector2((float)num4, num5) - point2.ToVector2() / 2f;
                float num6 = 1.2f;
                Dust dust2 = Dust.NewDustDirect(vector2, point2.X, point2.Y, 6, 0f, 0f, 100, color, num6);
                dust2.velocity.X = Main.rand.NextFloatDirection() * 2.5f;
                dust2.velocity.Y = Main.rand.NextFloat() * 3f;
                dust2.fadeIn = num6;
                dust2.noGravity = true;
                dust2.noLightEmittance = noDustLight;
                dust2.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Main.netMode, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.