Terraria Decompiled: Terraria.Player.CanSnapToPosition
CanSnapToPosition()
bool Terraria.Player.CanSnapToPosition (Vector2 offset) inline
Definition at line 32108 of file Player.cs.
        {
            bool flag = !Collision.SolidCollision(this.position + offset, this.width, this.height);
            if (flag && this.mount.Active)
            {
                Mount.MountDelegatesData.OverrideSizeMethod playerSize = this.mount.Delegations.PlayerSize;
                Vector2? vector;
                if (playerSize != null && playerSize(this, out vector) && vector != null)
                {
                    Vector2 value = vector.Value;
                    if (value.X < 20f || value.Y < 42f)
                    {
                        flag = this.CanFitInSpaceWithSize(this.DefaultSize, offset);
                    }
                }
            }
            if (!flag)
            {
                return false;
            }
            bool flag2 = Collision.CanHit(this.position, this.width, this.height, this.position + offset, this.width, this.height);
            if (!flag2)
            {
                this.TryAllowingSnappingToPosition(ref flag2, this.position, this.position + offset);
                if (!flag2)
                {
                    int num = Math.Sign(offset.X);
                    if (num != 0)
                    {
                        Vector2 vector2 = new Vector2((float)(num * this.width), 0f);
                        if (this.TileCollision(this.position, vector2, true, true) == vector2)
{
                            this.TryAllowingSnappingToPosition(ref flag2, this.position + vector2, this.position + offset);
                        }
                    }
                }
            }
            return flag2;
        }
References Terraria.Collision.CanHit(), System.offset, System.Math.Sign(), Terraria.Collision.SolidCollision(), and System.value.
Referenced by Terraria.GameContent.PlayerSittingHelper.SitDown(), and Terraria.GameContent.PlayerSleepingHelper.StartSleeping().