Terraria Decompiled: Terraria.Player.TryGettingDevArmor
TryGettingDevArmor()
void Terraria.Player.TryGettingDevArmor (IEntitySource source) inline private
Definition at line 5184 of file Player.cs.
        {
            if (Main.rand.Next(Main.tenthAnniversaryWorld ? 8 : 16) != 0)
            {
                return;
            }
            switch (Main.rand.Next(21))
            {
            case 0:
                this.QuickSpawnItem(source, 666, 1);
                this.QuickSpawnItem(source, 667, 1);
                this.QuickSpawnItem(source, 668, 1);
                this.QuickSpawnItem(source, 665, 1);
                this.QuickSpawnItem(source, 3287, 1);
                return;
            case 1:
                this.QuickSpawnItem(source, 1554, 1);
                this.QuickSpawnItem(source, 1555, 1);
                this.QuickSpawnItem(source, 1556, 1);
                this.QuickSpawnItem(source, 1586, 1);
                return;
            case 2:
                this.QuickSpawnItem(source, 1554, 1);
                this.QuickSpawnItem(source, 1587, 1);
                this.QuickSpawnItem(source, 1588, 1);
                this.QuickSpawnItem(source, 1586, 1);
                return;
            case 3:
                this.QuickSpawnItem(source, 1557, 1);
                this.QuickSpawnItem(source, 1558, 1);
                this.QuickSpawnItem(source, 1559, 1);
                this.QuickSpawnItem(source, 1585, 1);
                return;
            case 4:
                this.QuickSpawnItem(source, 1560, 1);
                this.QuickSpawnItem(source, 1561, 1);
                this.QuickSpawnItem(source, 1562, 1);
                this.QuickSpawnItem(source, 1584, 1);
                return;
            case 5:
                this.QuickSpawnItem(source, 1563, 1);
                this.QuickSpawnItem(source, 1564, 1);
                this.QuickSpawnItem(source, 1565, 1);
                this.QuickSpawnItem(source, 3582, 1);
                return;
            case 6:
                this.QuickSpawnItem(source, 1566, 1);
                this.QuickSpawnItem(source, 1567, 1);
                this.QuickSpawnItem(source, 1568, 1);
                return;
            case 7:
                this.QuickSpawnItem(source, 1580, 1);
                this.QuickSpawnItem(source, 1581, 1);
                this.QuickSpawnItem(source, 1582, 1);
                this.QuickSpawnItem(source, 1583, 1);
                return;
            case 8:
                this.QuickSpawnItem(source, 3226, 1);
                this.QuickSpawnItem(source, 3227, 1);
                this.QuickSpawnItem(source, 3228, 1);
                this.QuickSpawnItem(source, 3288, 1);
                return;
            case 9:
                this.QuickSpawnItem(source, 3583, 1);
                this.QuickSpawnItem(source, 3581, 1);
                this.QuickSpawnItem(source, 3578, 1);
                this.QuickSpawnItem(source, 3579, 1);
                this.QuickSpawnItem(source, 3580, 1);
                return;
            case 10:
                this.QuickSpawnItem(source, 3585, 1);
                this.QuickSpawnItem(source, 3586, 1);
                this.QuickSpawnItem(source, 3587, 1);
                this.QuickSpawnItem(source, 3588, 1);
                this.QuickSpawnItem(source, 3024, 4);
                return;
            case 11:
                this.QuickSpawnItem(source, 3589, 1);
                this.QuickSpawnItem(source, 3590, 1);
                this.QuickSpawnItem(source, 3591, 1);
                this.QuickSpawnItem(source, 3592, 1);
                this.QuickSpawnItem(source, 3599, 4);
                return;
            case 12:
                this.QuickSpawnItem(source, 3368, 1);
                this.QuickSpawnItem(source, 3921, 1);
                this.QuickSpawnItem(source, 3922, 1);
                this.QuickSpawnItem(source, 3923, 1);
                this.QuickSpawnItem(source, 3924, 1);
                return;
            case 13:
                this.QuickSpawnItem(source, 3925, 1);
                this.QuickSpawnItem(source, 3926, 1);
                this.QuickSpawnItem(source, 3927, 1);
                this.QuickSpawnItem(source, 3928, 1);
                this.QuickSpawnItem(source, 3929, 1);
                return;
            case 14:
                this.QuickSpawnItem(source, 4732, 1);
                this.QuickSpawnItem(source, 4733, 1);
                this.QuickSpawnItem(source, 4734, 1);
                this.QuickSpawnItem(source, 4730, 1);
                return;
            case 15:
                this.QuickSpawnItem(source, 4747, 1);
                this.QuickSpawnItem(source, 4748, 1);
                this.QuickSpawnItem(source, 4749, 1);
                this.QuickSpawnItem(source, 4746, 1);
                return;
            case 16:
                this.QuickSpawnItem(source, 4751, 1);
                this.QuickSpawnItem(source, 4752, 1);
                this.QuickSpawnItem(source, 4753, 1);
                this.QuickSpawnItem(source, 4750, 1);
                return;
            case 17:
                this.QuickSpawnItem(source, 4755, 1);
                this.QuickSpawnItem(source, 4756, 1);
                this.QuickSpawnItem(source, 4757, 1);
                this.QuickSpawnItem(source, 4754, 1);
                return;
            case 18:
                this.QuickSpawnItem(source, 5583, 1);
                this.QuickSpawnItem(source, 5584, 1);
                this.QuickSpawnItem(source, 5585, 1);
                this.QuickSpawnItem(source, 5586, 1);
                this.QuickSpawnItem(source, 5587, 1);
                return;
            case 19:
                this.QuickSpawnItem(source, 5683, 1);
                this.QuickSpawnItem(source, 5684, 1);
                this.QuickSpawnItem(source, 5685, 1);
                this.QuickSpawnItem(source, 5686, 1);
                return;
            case 20:
                this.QuickSpawnItem(source, 6137, 1);
                this.QuickSpawnItem(source, 6138, 1);
                this.QuickSpawnItem(source, 6139, 1);
                this.QuickSpawnItem(source, 6140, 1);
                this.QuickSpawnItem(source, 6141, 1);
                return;
            default:
                return;
            }
        }
References Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.QuickSpawnItem(), Terraria.Main.rand, and Terraria.Main.tenthAnniversaryWorld.
Referenced by Terraria.Player.OpenBossBag().