Terraria Decompiled: Terraria.Player.GetAnglerReward_Decoration
GetAnglerReward_Decoration()
void Terraria.Player.GetAnglerReward_Decoration (IEntitySource source, int questsDone, float rarityReduction) inline private
Definition at line 55810 of file Player.cs.
        {
            float num = 1f - rarityReduction;
            int num2 = 100;
            float num3 = MathHelper.Lerp(num, 1f, Math.Min(1f, (float)questsDone / (float)num2));
            if (num3 >= 1f || Main.rand.NextFloat() <= num3)
            {
                Item item = new Item();
                item.type = 0;
                int num4;
                switch (Main.rand.Next(19))
                {
                default:
                    num4 = 2442;
                    break;
                case 1:
                    num4 = 2443;
                    break;
                case 2:
                    num4 = 2444;
                    break;
                case 3:
                    num4 = 2445;
                    break;
                case 4:
                    num4 = 2497;
                    break;
                case 5:
                    num4 = 2495;
                    break;
                case 6:
                    num4 = 2446;
                    break;
                case 7:
                    num4 = 2447;
                    break;
                case 8:
                    num4 = 2448;
                    break;
                case 9:
                    num4 = 2449;
                    break;
                case 10:
                    num4 = 2490;
                    break;
                case 11:
                    num4 = 2496;
                    break;
                case 12:
                    num4 = 5235;
                    break;
                case 13:
                    num4 = 5252;
                    break;
                case 14:
                    num4 = 5256;
                    break;
                case 15:
                    num4 = 5259;
                    break;
                case 16:
                    num4 = 5263;
                    break;
                case 17:
                    num4 = 5264;
                    break;
                case 18:
                    num4 = 5265;
                    break;
                }
                item.SetDefaults(num4, null);
                this.QuickSpawnItem(source, item, GetItemSettings.GiftRecieved);
            }
        }
References Terraria.GetItemSettings.GiftRecieved, System.item, Microsoft.Xna.Framework.MathHelper.Lerp(), System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and System.source.