Terraria Decompiled: Terraria.Player.ItemCheck_ApplyHoldStyle
ItemCheck_ApplyHoldStyle()
void Terraria.Player.ItemCheck_ApplyHoldStyle (float mountOffset, Item sItem, Rectangle heldItemFrame) inline private
Definition at line 49573 of file Player.cs.
        {
            bool flag = !this.isDisplayDollOrInanimate;
            if (this.petting.isPetting)
            {
                if (this.mount.Active && (this.mount.Type == 62 || this.mount.Type == 63))
                {
                    int num = this.miscCounter % 14 / 7;
                    Player.CompositeArmStretchAmount compositeArmStretchAmount = Player.CompositeArmStretchAmount.ThreeQuarters;
                    if (num == 1)
                    {
                        compositeArmStretchAmount = Player.CompositeArmStretchAmount.Full;
                    }
                    float num2 = 0.36f;
                    this.SetCompositeArmBack(true, compositeArmStretchAmount, -6.2831855f * num2 * (float)this.direction);
                }
                else
                {
                    int num3 = this.miscCounter % 14 / 7;
                    Player.CompositeArmStretchAmount compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.ThreeQuarters;
                    if (num3 == 1)
                    {
                        compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.Full;
                    }
                    float num4 = 0.3f;
                    if (this.petting.isPetSmall)
                    {
                        num4 = 0.2f;
                    }
                    this.SetCompositeArmBack(true, compositeArmStretchAmount2, -6.2831855f * num4 * (float)this.direction);
                }
            }
            if (!this.CanVisuallyHoldItem(sItem))
            {
                return;
            }
            if (sItem.holdStyle == 1 && !this.pulley)
            {
                if (Main.dedServ)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + 20f * (float)this.direction;
                }
                else if (sItem.type == 930)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f - (float)(2 * this.direction);
                    float num5 = this.position.X + (float)(this.width / 2) + (float)(38 * this.direction);
                    if (this.direction == 1)
                    {
                        num5 -= 10f;
                    }
                    float num6 = this.MountedCenter.Y - 4f * this.gravDir;
                    if (this.gravDir == -1f)
                    {
                        num6 -= 8f;
                    }
                    this.RotateRelativePoint(ref num5, ref num6);
                    int num7 = 0;
                    for (int i = 54; i < 58; i++)
                    {
                        if (this.inventory[i].stack > 0 && this.inventory[i].ammo == 931)
{
                            num7 = this.inventory[i].type;
                            break;
                        }
                    }
                    if (num7 == 0)
                    {
                        for (int j = 0; j < 54; j++)
{
                            if (this.inventory[j].stack > 0 && this.inventory[j].ammo == 931)
{
                                num7 = this.inventory[j].type;
                                break;
                            }
                        }
                    }
                    if (num7 != 931)
                    {
                        if (num7 != 1614)
{
                            switch (num7)
{
                            case 5377:
                                num7 = 169;
                                break;
                            case 5378:
                                num7 = 75;
                                break;
                            case 5379:
                                num7 = 66;
                                break;
                            case 5380:
                                num7 = 310;
                                break;
                            }
                        }
                        else
{
                            num7 = 187;
                        }
                    }
                    else
                    {
                        num7 = 127;
                    }
                    if (num7 > 0)
                    {
                        int num8 = Dust.NewDust(new Vector2(num5, num6 + this.gfxOffY), 6, 6, num7, 0f, 0f, 100, default(Color), 1.6f);
                        Main.dust[num8].noGravity = true;
                        Dust dust = Main.dust[num8];
                        dust.velocity.Y = dust.velocity.Y - 4f * this.gravDir;
                        if (num7 == 66)
{
                            Main.dust[num8].color = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.6f % 1f, 1f, 0.5f, byte.MaxValue);
                            Main.dust[num8].scale *= 0.5f;
                            Main.dust[num8].velocity *= 0.75f;
                        }
                    }
                }
                else if (sItem.type == 968)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + (float)(8 * this.direction);
                    if (this.whoAmI == Main.myPlayer && flag)
                    {
                        int num9 = (int)(this.itemLocation.X + (float)heldItemFrame.Width * 0.8f * (float)this.direction) / 16;
                        int num10 = (int)(this.itemLocation.Y + mountOffset + (float)(heldItemFrame.Height / 2)) / 16;
                        if (Main.tile[num9, num10] == null)
{
                            Main.tile[num9, num10] = new Tile();
                        }
                        if (Main.tile[num9, num10].active() && TileID.Sets.Campfires[(int)Main.tile[num9, num10].type] && Main.tile[num9, num10].frameY < 54)
{
                            this.miscTimer++;
                            if (Main.rand.Next(5) == 0)
{
                                this.miscTimer++;
                            }
                            if (this.miscTimer > 900)
{
                                this.miscTimer = 0;
                                this.QuickSpawnItem(this.GetItemSource_Item(sItem), 969, 1);
                                sItem.stack--;
                                if (sItem.stack == 0)
{
                                    sItem.TurnToAir(false);
                                }
                                if (this.selectedItem == 58)
{
                                    Main.mouseItem.stack--;
                                    if (Main.mouseItem.stack == 0)
{
                                        Main.mouseItem.TurnToAir(false);
                                    }
                                }
                            }
                        }
                        else
{
                            this.miscTimer = 0;
                        }
                    }
                }
                else if (sItem.type == 856)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + (float)(4 * this.direction);
                }
                else if (sItem.fishingPole > 0)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + (float)((int)((float)heldItemFrame.Width * 0.18f) * this.direction);
                }
                else
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f + 2f) * (float)this.direction;
                    if (sItem.type == 282 || sItem.type == 286 || sItem.type == 3112 || sItem.type == 4776 || sItem.type == 5643)
                    {
                        this.itemLocation.X = this.itemLocation.X - (float)(this.direction * 2);
                        this.itemLocation.Y = this.itemLocation.Y + 4f;
                    }
                    else if (sItem.type == 3002)
                    {
                        this.itemLocation.X = this.itemLocation.X - (float)(4 * this.direction);
                        this.itemLocation.Y = this.itemLocation.Y + 2f;
                    }
                }
                this.itemLocation.Y = this.position.Y + 24f + mountOffset;
                if (sItem.type == 1304)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + (float)(6 * this.direction);
                    this.itemLocation.Y = this.itemLocation.Y + 2f;
                }
                if (sItem.type == 856)
                {
                    this.itemLocation.Y = this.position.Y + 34f + mountOffset;
                }
                if (sItem.type == 930)
                {
                    this.itemLocation.Y = this.position.Y + 9f + mountOffset;
                }
                if (sItem.fishingPole > 0)
                {
                    this.itemLocation.Y = this.itemLocation.Y + 4f;
                }
                else if (sItem.type == 3476)
                {
                    this.itemLocation.X = base.Center.X + (float)(14 * this.direction);
                    this.itemLocation.Y = this.MountedCenter.Y;
                }
                else if (sItem.type == 3779)
                {
                    this.itemLocation.X = base.Center.X + (float)(6 * this.direction);
                    this.itemLocation.Y = this.MountedCenter.Y + 6f;
                }
                else if (sItem.type == 4952)
                {
                    this.itemLocation.X = base.Center.X + (float)(2 * this.direction);
                    this.itemLocation.Y = this.MountedCenter.Y + 26f;
                }
                else if (sItem.type == 353)
                {
                    this.itemLocation.X = base.Center.X + (float)(6 * this.direction);
                    this.itemLocation.Y = this.MountedCenter.Y + 11f;
                }
                else if (ItemID.Sets.IsFood[sItem.type])
                {
                    this.itemLocation.X = base.Center.X + (float)(4 * this.direction);
                    this.itemLocation.Y = this.MountedCenter.Y + (float)(heldItemFrame.Height / 2);
                }
                else if (sItem.type == 4049 && this.stealth >= 1f && Main.rand.Next(4) == 0)
                {
                    Dust dust2 = Dust.NewDustPerfect(base.Center + new Vector2((float)(this.direction * 23), this.gravDir * 6f), 31, new Vector2?(Vector2.Zero), 127, default(Color), 0.7f);
                    dust2.noGravity = true;
                    dust2.velocity = Main.rand.NextVector2Circular(1f, 1f) + new Vector2(0f, -1f);
                }
                this.itemRotation = 0f;
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y) + mountOffset;
                    if (sItem.type == 930)
                    {
                        this.itemLocation.Y = this.itemLocation.Y - 24f;
                        return;
                    }
                }
            }
            else if (sItem.holdStyle == 2 && !this.pulley)
            {
                if (sItem.type == 946 || sItem.type == 4707)
                {
                    this.itemRotation = 0f;
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f - (float)(16 * this.direction);
                    this.itemLocation.Y = this.position.Y + 22f + mountOffset;
                    if (flag)
                    {
                        this.fallStart = (int)(this.position.Y / 16f);
                    }
                    if (this.gravDir == -1f)
                    {
                        this.itemRotation = -this.itemRotation;
                        this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                        if (this.velocity.Y < -2f && !this.controlDown)
{
                            this.velocity.Y = -2f;
                            return;
                        }
                    }
                    else if (this.velocity.Y > 2f && !this.controlDown)
                    {
                        this.velocity.Y = 2f;
                        return;
                    }
                }
                else
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + (float)(6 * this.direction);
                    this.itemLocation.Y = this.position.Y + 16f + mountOffset;
                    this.itemRotation = 0.79f * (float)(-(float)this.direction);
                    if (this.gravDir == -1f)
                    {
                        this.itemRotation = -this.itemRotation;
                        this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                        return;
                    }
                }
            }
            else if (sItem.holdStyle == 3 && !this.pulley)
            {
                if (!Main.dedServ)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f - (float)(this.direction * 2);
                    this.itemLocation.Y = this.MountedCenter.Y - (float)heldItemFrame.Height * 0.5f;
                    this.itemRotation = 0f;
                    return;
                }
            }
            else if (sItem.holdStyle == 4)
            {
                if (Main.dedServ)
                {
                    return;
                }
                float num11 = new Vector2((float)(10 * this.direction), 10f).ToRotation() + 0.7853982f;
                this.itemRotation = num11;
                if (this.direction == -1)
                {
                    this.itemRotation += 1.5707964f;
                }
                Player.CompositeArmStretchAmount compositeArmStretchAmount3 = Player.CompositeArmStretchAmount.Full;
                Player.CompositeArmStretchAmount compositeArmStretchAmount4 = Player.CompositeArmStretchAmount.ThreeQuarters;
                float num12 = -0.31415927f;
                if (this.direction == -1)
                {
                    num12 *= -1f;
                }
                float num13 = this.itemRotation - 0.7853982f + 3.1415927f;
                if (this.direction == 1)
                {
                    num13 += 1.5707964f;
                }
                float num14 = num13 + num12;
                float num15 = num13 - num12;
                Vector2 vector = (num13 + 1.5707964f).ToRotationVector2() * 2f;
                this.itemLocation = this.MountedCenter.Floor() + vector;
                this.SetCompositeArmFront(true, compositeArmStretchAmount3, num14);
                this.SetCompositeArmBack(true, compositeArmStretchAmount4, num15);
                this.FlipItemLocationAndRotationForGravity();
                return;
            }
            else if (sItem.holdStyle == 5 && !this.pulley)
            {
                if (Main.dedServ)
                {
                    return;
                }
                this.itemRotation = 0f;
                this.itemLocation.X = base.Center.X - (float)(8 * this.direction);
                this.itemLocation.Y = this.position.Y + 40f + mountOffset;
                Vector2 vector2 = Main.OffsetsPlayerHeadgear[this.bodyFrame.Y / 56];
                this.itemLocation += vector2;
                Player.CompositeArmStretchAmount compositeArmStretchAmount5 = Player.CompositeArmStretchAmount.Quarter;
                this.SetCompositeArmBack(true, compositeArmStretchAmount5, -0.7853982f * (float)this.direction);
                Player.CompositeArmStretchAmount compositeArmStretchAmount6 = Player.CompositeArmStretchAmount.Full;
                this.SetCompositeArmFront(true, compositeArmStretchAmount6, -0.39269912f * (float)this.direction);
                this.FlipItemLocationAndRotationForGravity();
                return;
            }
            else if (sItem.holdStyle == 6 && !this.pulley)
            {
                if (Main.dedServ)
                {
                    return;
                }
                this.itemRotation = 0f;
                this.itemLocation.X = base.Center.X + (float)(8 * this.direction);
                this.itemLocation.Y = this.position.Y + 40f + mountOffset - 2f;
                Vector2 vector3 = Main.OffsetsPlayerHeadgear[this.bodyFrame.Y / 56];
                this.itemLocation += vector3;
                Player.CompositeArmStretchAmount compositeArmStretchAmount7 = Player.CompositeArmStretchAmount.ThreeQuarters;
                this.SetCompositeArmBack(true, compositeArmStretchAmount7, -1.8849556f * (float)this.direction);
                this.FlipItemLocationAndRotationForGravity();
                return;
            }
            else if (sItem.holdStyle == 8)
            {
                this.itemRotation = 0f;
                this.itemLocation.X = base.Center.X + (float)(6 * this.direction);
                this.itemLocation.Y = this.position.Y + 30f + mountOffset - 2f;
                Vector2 vector4 = Main.OffsetsPlayerHeadgear[this.bodyFrame.Y / 56];
                this.itemLocation += vector4;
                this.SetCompositeArmBack(true, Player.CompositeArmStretchAmount.ThreeQuarters, -1.2566371f * (float)this.direction);
                this.SetCompositeArmFront(true, Player.CompositeArmStretchAmount.Full, -1.2566371f * (float)this.direction);
                this.FlipItemLocationAndRotationForGravity();
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Campfires, Terraria.Dust.color, Terraria.Main.dedServ, Terraria.Main.dust, Terraria.Item.fishingPole, Terraria.Tile.frameY, Terraria.Main.GlobalTimeWrappedHourly, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Item.holdStyle, Terraria.Main.hslToRgb(), int, Terraria.ID.ItemID.Sets.IsFood, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.OffsetsPlayerHeadgear, Terraria.Main.rand, Terraria.Dust.scale, System.stack, Terraria.Item.stack, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Item.TurnToAir(), Terraria.Item.type, Terraria.Tile.type, Terraria.Dust.velocity, and Microsoft.Xna.Framework.Vector2.Zero.