Terraria Decompiled: Terraria.Player.ItemCheck_UseMiningTools_TryFindingWallToHammer
ItemCheck_UseMiningTools_TryFindingWallToHammer()
static void Terraria.Player.ItemCheck_UseMiningTools_TryFindingWallToHammer (out int wX, out int wY) inline static private
Definition at line 45116 of file Player.cs.
        {
            wX = Player.tileTargetX;
            wY = Player.tileTargetY;
            bool flag = true;
            if (Main.tile[wX, wY].wall > 0)
            {
                if (!Main.wallHouse[(int)Main.tile[wX, wY].wall])
                {
                    for (int i = wX - 1; i < wX + 2; i++)
                    {
                        for (int j = wY - 1; j < wY + 2; j++)
{
                            if (Main.tile[i, j].wall != Main.tile[wX, wY].wall)
{
                                flag = false;
                                break;
                            }
                        }
                    }
                }
                else
                {
                    flag = false;
                }
            }
            if (flag && !Main.tile[wX, wY].active())
            {
                int num = -1;
                if ((double)(((float)Main.mouseX + Main.screenPosition.X) / 16f) < Math.Round((double)(((float)Main.mouseX + Main.screenPosition.X) / 16f)))
                {
                    num = 0;
                }
                int num2 = -1;
                if ((double)(((float)Main.mouseY + Main.screenPosition.Y) / 16f) < Math.Round((double)(((float)Main.mouseY + Main.screenPosition.Y) / 16f)))
                {
                    num2 = 0;
                }
                for (int k = Player.tileTargetX + num; k <= Player.tileTargetX + num + 1; k++)
                {
                    for (int l = Player.tileTargetY + num2; l <= Player.tileTargetY + num2 + 1; l++)
                    {
                        if (flag)
{
                            wX = k;
                            wY = l;
                            if (Main.tile[wX, wY].wall > 0)
{
                                if (!Main.wallHouse[(int)Main.tile[wX, wY].wall])
{
                                    for (int m = wX - 1; m < wX + 2; m++)
{
                                        for (int n = wY - 1; n < wY + 2; n++)
{
                                            if (Main.tile[m, n].wall != Main.tile[wX, wY].wall)
{
                                                flag = false;
                                                break;
                                            }
                                        }
                                    }
                                }
                                else
{
                                    flag = false;
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Main.mouseX, Terraria.Main.mouseY, System.Math.Round(), Terraria.Main.screenPosition, Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Tile.wall, Terraria.Main.wallHouse, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.ItemCheck_UseMiningTools().