Terraria Decompiled: Terraria.Player.UpdateSunScorchValues
UpdateSunScorchValues()
void Terraria.Player.UpdateSunScorchValues () inline private
Definition at line 26956 of file Player.cs.
        {
            int num = 6;
            if (this.dead)
            {
                this.vampireBurningInSunlight = false;
                num = 2;
            }
            this.sunScorchCounter = Utils.Clamp<int>(this.sunScorchCounter + (this.vampireBurningInSunlight ? 1 : (-num)), 0, 300);
            float lerpValue = Utils.GetLerpValue(0f, 120f, (float)this.sunScorchCounter, true);
            ActiveSound activeSound = SoundEngine.GetActiveSound(this._sizzleAudioHandle);
            if (activeSound == null && lerpValue != 0f)
            {
                SoundPlayOverrides soundPlayOverrides = default(SoundPlayOverrides);
                soundPlayOverrides.Volume = new float?(lerpValue);
                this._sizzleAudioHandle = SoundEngine.PlayTrackedLoopedSound(SoundID.VampireSizzle, base.Center, new ActiveSound.LoopedPlayCondition(new VampireSizzleTracker(this.whoAmI).IsActiveAndInGame), soundPlayOverrides);
                activeSound = SoundEngine.GetActiveSound(this._sizzleAudioHandle);
            }
            if (activeSound != null)
            {
                activeSound.Volume = lerpValue;
                activeSound.Position = base.Center;
            }
        }
References Terraria.Utils.Clamp(), Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Utils.GetLerpValue(), Terraria.Audio.VampireSizzleTracker.IsActiveAndInGame(), Terraria.Audio.ActiveSound.LoopedPlayCondition(), Terraria.Audio.SoundEngine.PlayTrackedLoopedSound(), and Terraria.ID.SoundID.VampireSizzle.