Terraria Decompiled: Terraria.Player.OpenChest
OpenChest()
void Terraria.Player.OpenChest (int x, int y, int newChest) inline private
Definition at line 32227 of file Player.cs.
        {
            this.chest = newChest;
            if (this.chest != -1 && Main.myPlayer == this.whoAmI)
            {
                Chest currentContainer = this.GetCurrentContainer();
                if (currentContainer != null)
                {
                    ItemSlot.SetGlowForChest(currentContainer);
                }
            }
            NewCraftingUI.Close(true, false);
            Main.playerInventory = true;
            UILinkPointNavigator.ForceMovementCooldown(PlayerInput.CurrentProfile.InventoryMoveCD);
            if (PlayerInput.GrappleAndInteractAreShared)
            {
                PlayerInput.Triggers.JustPressed.Grapple = false;
            }
            Main.PipsUseGrid = false;
            this.chestX = x;
            this.chestY = y;
        }
References Terraria.GameContent.UI.NewCraftingUI.Close(), Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.UI.Gamepad.UILinkPointNavigator.ForceMovementCooldown(), Terraria.GameInput.PlayerInput.GrappleAndInteractAreShared, Terraria.GameInput.PlayerInputProfile.InventoryMoveCD, Terraria.Main.myPlayer, and Terraria.UI.ItemSlot.SetGlowForChest().