Terraria Decompiled: Terraria.Player.TorchGodsFlavor
TorchGodsFlavor()
void Terraria.Player.TorchGodsFlavor () inline private
Definition at line 39045 of file Player.cs.
        {
            if (this.whoAmI != Main.myPlayer)
            {
                return;
            }
            if (Main.rand.Next(10) == 0)
            {
                for (int i = 0; i < 1000; i++)
                {
                    if (Main.projectile[i].active && Main.projectile[i].type == 1084 && Main.projectile[i].owner == this.whoAmI)
                    {
                        return;
                    }
                }
                int num = 0;
                int num2 = 4;
                this.BiomeTorchPlaceStyle(ref num2, ref num, true);
                int num3 = (int)(base.Center.X - (float)(NPC.sWidth / 2)) / 16;
                int num4 = (int)(base.Center.X + (float)(NPC.sWidth / 2)) / 16;
                int num5 = (int)(base.Center.Y - (float)(NPC.sHeight / 2)) / 16;
                int num6 = (int)(base.Center.Y + (float)(NPC.sHeight / 2)) / 16;
                int num7 = 1000;
                for (int j = 0; j < num7; j++)
                {
                    int num8 = Main.rand.Next(num3, num4 + 1);
                    int num9 = Main.rand.Next(num5, num6 + 1);
                    if (WorldGen.InWorld(num8, num9, 0))
                    {
                        Tile tile = Main.tile[num8, num9];
                        if (tile != null && tile.active() && (int)tile.type == num2 && !(this.ZoneDungeon ^ Main.wallDungeon[(int)tile.wall]))
{
                            int num10 = (int)(tile.frameY / 22);
                            if (TorchID.Sets.IsABiomeTorch[num10] && num10 != num)
{
                                Vector2 vector = new Vector2((float)num8 - base.Center.X / 16f, (float)num9 - base.Center.Y / 16f);
                                vector.Normalize();
                                vector *= 1500f;
                                Vector2 vector2 = base.Center - vector;
                                vector2.X += (float)Main.rand.Next(400, 401);
                                vector2.Y += (float)Main.rand.Next(400, 401);
                                Vector2 vector3 = new Vector2((float)(num8 * 16 + 8) - vector2.X, (float)(num9 * 16 + 8) - vector2.Y);
                                vector3.Normalize();
                                vector3 *= 16f;
                                Projectile.NewProjectile(this.GetProjectileSource_Misc(10), vector2, vector3, 1084, 0, 0f, this.whoAmI, (float)num, (float)num8, (float)num9, null);
                                return;
                            }
                        }
                    }
                }
            }
        }
References Terraria.Projectile.active, Terraria.Tile.active(), Terraria.Tile.frameY, int, Terraria.WorldGen.InWorld(), Terraria.ID.TorchID.Sets.IsABiomeTorch, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Main.tile, Terraria.Projectile.type, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallDungeon, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.