Terraria Decompiled: Terraria.Player.Spawn_DescendFromDefaultSpace
Spawn_DescendFromDefaultSpace()
static int Terraria.Player.Spawn_DescendFromDefaultSpace (int x, int y) inline static
Definition at line 36787 of file Player.cs.
        {
            for (int i = 0; i < 50; i++)
            {
                bool flag = false;
                bool flag2 = false;
                bool flag3 = false;
                for (int j = -1; j <= 1; j++)
                {
                    int num = x + j;
                    int num2 = y + i;
                    if (WorldGen.InWorld(num, num2, 5) && Main.tile[num, num2] != null && Main.tile[num, num2 - 1] != null)
                    {
                        Tile tile = Main.tile[num, num2];
                        Main.tile[num, num2 - 1];
                        if (tile.nactive() && ((Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type]) || TileID.Sets.Platforms[(int)tile.type] || tile.type == 380) && tile.type != 379)
{
                            if (j == -1)
{
                                flag = true;
                            }
                            else if (j == 1)
{
                                flag3 = true;
                            }
                            else
{
                                flag2 = true;
                            }
                        }
                    }
                }
                if (flag2 && (flag || flag3))
                {
                    y += i;
                    break;
                }
            }
            return y;
        }
References Terraria.WorldGen.InWorld(), Terraria.Tile.nactive(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.Player.Spawn_GetPositionAtSpawn().