Terraria Decompiled: Terraria.Player.clientClone
clientClone()
Player Terraria.Player.clientClone (Player clonePlayer) inline
Definition at line 53769 of file Player.cs.
        {
            clonePlayer.zone1 = this.zone1;
            clonePlayer.zone2 = this.zone2;
            clonePlayer.zone3 = this.zone3;
            clonePlayer.zone4 = this.zone4;
            clonePlayer.zone5 = this.zone5;
            clonePlayer.townNPCs = this.townNPCs;
            clonePlayer.voidVaultInfo = this.voidVaultInfo;
            clonePlayer.luck = this.luck;
            clonePlayer.extraAccessory = this.extraAccessory;
            clonePlayer.MinionRestTargetPoint = this.MinionRestTargetPoint;
            clonePlayer.MinionAttackTargetNPC = this.MinionAttackTargetNPC;
            clonePlayer.direction = this.direction;
            clonePlayer.selectedItemState = this.selectedItemState;
            clonePlayer.controlUp = this.controlUp;
            clonePlayer.controlDown = this.controlDown;
            clonePlayer.controlLeft = this.controlLeft;
            clonePlayer.controlRight = this.controlRight;
            clonePlayer.controlJump = this.controlJump;
            clonePlayer.controlUseItem = this.controlUseItem;
            clonePlayer.controlDownHold = this.controlDownHold;
            clonePlayer.isOperatingAnotherEntity = this.isOperatingAnotherEntity;
            clonePlayer.autoReuseAllWeapons = this.autoReuseAllWeapons;
            clonePlayer.statLife = this.statLife;
            clonePlayer.statLifeMax = this.statLifeMax;
            clonePlayer.statMana = this.statMana;
            clonePlayer.statManaMax = this.statManaMax;
            clonePlayer.position.X = this.position.X;
            clonePlayer.tileEntityAnchor = this.tileEntityAnchor;
            clonePlayer.chest = this.chest;
            clonePlayer.talkNPC = this.talkNPC;
            clonePlayer.piggyBankProjTracker = this.piggyBankProjTracker;
            clonePlayer.voidLensChest = this.voidLensChest;
            clonePlayer.hideVisibleAccessory = this.hideVisibleAccessory;
            clonePlayer.hideMisc = this.hideMisc;
            clonePlayer.shieldRaised = this.shieldRaised;
            clonePlayer.lastItemUseAttemptSuccess = this.lastItemUseAttemptSuccess;
            Player.clientCloneItem(this.trashItem, clonePlayer.trashItem);
            Player.clientCloneItemArray(this.inventory, clonePlayer.inventory);
            Player.clientCloneItemArray(this.armor, clonePlayer.armor);
            Player.clientCloneItemArray(this.dye, clonePlayer.dye);
            Player.clientCloneItemArray(this.miscEquips, clonePlayer.miscEquips);
            Player.clientCloneItemArray(this.miscDyes, clonePlayer.miscDyes);
            Player.clientCloneItemArray(this.bank.item, clonePlayer.bank.item);
            Player.clientCloneItemArray(this.bank2.item, clonePlayer.bank2.item);
            Player.clientCloneItemArray(this.bank3.item, clonePlayer.bank3.item);
            Player.clientCloneItemArray(this.bank4.item, clonePlayer.bank4.item);
            this.clientCloneLoadouts(clonePlayer);
            Array.Copy(this.buffType, clonePlayer.buffType, this.buffType.Length);
            Array.Copy(this.buffTime, clonePlayer.buffTime, this.buffTime.Length);
            this.DpadRadial.CopyTo(clonePlayer.DpadRadial);
            this.CircularRadial.CopyTo(clonePlayer.CircularRadial);
            return clonePlayer;
        }
References Terraria.Player.armor, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.Player.CircularRadial, Terraria.Player.clientCloneItem(), Terraria.Player.clientCloneItemArray(), System.Array.Copy(), Terraria.Player.DpadRadial, Terraria.Player.dye, Terraria.Player.inventory, Terraria.Chest.item, Terraria.Player.miscDyes, Terraria.Player.miscEquips, and Terraria.Player.trashItem.
Referenced by Terraria.Netplay.ClientLoopSetup(), and Terraria.Main.TrySyncingMyPlayer().