Terraria Decompiled: Terraria.Player.ItemCheck_CheckFishingBobber_ConsumeBait
ItemCheck_CheckFishingBobber_ConsumeBait()
bool Terraria.Player.ItemCheck_CheckFishingBobber_ConsumeBait (Projectile bobber, out int baitTypeUsed) inline private
Definition at line 51758 of file Player.cs.
        {
            int num = -1;
            for (int i = 54; i < 58; i++)
            {
                if (this.inventory[i].stack > 0 && (float)this.inventory[i].type == bobber.localAI[2])
                {
                    num = i;
                    break;
                }
            }
            if (num == -1)
            {
                for (int j = 0; j < 50; j++)
                {
                    if (this.inventory[j].stack > 0 && (float)this.inventory[j].type == bobber.localAI[2])
                    {
                        num = j;
                        break;
                    }
                }
            }
            if (num == -1)
            {
                baitTypeUsed = 0;
                return false;
            }
            Item item = this.inventory[num];
            bool flag = false;
            float num2 = 1f + (float)item.bait / 6f;
            if (num2 < 1f)
            {
                num2 = 1f;
            }
            if (this.accTackleBox)
            {
                num2 += 1f;
            }
            if (Main.rand.NextFloat() * num2 < 1f)
            {
                flag = true;
            }
            if (bobber.localAI[1] == -1f)
            {
                flag = true;
            }
            if (bobber.localAI[1] > 0f)
            {
                Item item2 = new Item();
                item2.SetDefaults((int)bobber.localAI[1], null);
                if (item2.rare < 0)
                {
                    flag = false;
                }
            }
            baitTypeUsed = item.type;
            if (baitTypeUsed == 2895)
            {
                flag = Main.rand.Next(20) == 0;
            }
            if (baitTypeUsed == 2673)
            {
                flag = true;
            }
            if (flag)
            {
                if (item.type == 4361 || item.type == 4362)
                {
                    NPC.LadyBugKilled(base.Center, item.type == 4362);
                }
                item.stack--;
                if (item.stack <= 0)
                {
                    item.SetDefaults(0, null);
                }
            }
            return true;
        }
References Terraria.Item.bait, System.item, Terraria.NPC.LadyBugKilled(), Terraria.Projectile.localAI, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Item.rare, Terraria.Item.SetDefaults(), and System.stack.