Terraria Decompiled: Terraria.Player.DropSelectedItem
DropSelectedItem() [1/2]
void Terraria.Player.DropSelectedItem () inline
Definition at line 2411 of file Player.cs.
        {
            if (Main.mouseItem != null && Main.mouseItem.type > 0 && Main.mouseItem.stack > 0)
            {
                this.DropSelectedItem(58, ref this.inventory[58]);
                return;
            }
            if (!this.inventoryChestStack[this.selectedItem])
            {
                this.DropSelectedItem(this.selectedItem, ref this.inventory[this.selectedItem]);
            }
        }
References Terraria.Player.DropSelectedItem(), Terraria.Player.inventory, Terraria.Player.inventoryChestStack, Terraria.Main.mouseItem, Terraria.Player.selectedItem, Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.Player.dropItemCheck(), and Terraria.Player.DropSelectedItem().