Terraria Decompiled: Terraria.Player.TryPlacingAGolfBallNearANearbyTee
TryPlacingAGolfBallNearANearbyTee()
bool Terraria.Player.TryPlacingAGolfBallNearANearbyTee (Vector2 placePosition) inline
Definition at line 48895 of file Player.cs.
        {
            int num;
            int num2;
            int num3;
            int num4;
            TileReachCheckSettings.Simple.GetTileRegion(this, out num, out num2, out num3, out num4, 0);
            num = Utils.Clamp<int>(num, 10, Main.maxTilesX - 10);
            num3 = Utils.Clamp<int>(num3, 10, Main.maxTilesX - 10);
            num2 = Utils.Clamp<int>(num2, 10, Main.maxTilesY - 10);
            num4 = Utils.Clamp<int>(num4, 10, Main.maxTilesY - 10);
            Vector2 vector = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY);
            if (this.gravDir == -1f)
            {
                vector.Y = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY;
            }
            Point point = placePosition.ToTileCoordinates();
            List<Tuple<int, int>> list = new List<Tuple<int, int>>();
            for (int i = -2; i <= 2; i++)
            {
                for (int j = -2; j <= 2; j++)
                {
                    int num5 = point.X + i;
                    int num6 = point.Y + j;
                    if (WorldGen.InWorld(num5, num6, 1))
                    {
                        Tile tileSafely = Framing.GetTileSafely(num5, num6);
                        if (tileSafely.active() && tileSafely.type == 494)
{
                            list.Add(new Tuple<int, int>(num5, num6));
                            break;
                        }
                    }
                }
            }
            bool flag = false;
            if (list.Count > 0)
            {
                float num7 = -1f;
                Tuple<int, int> tuple = list[0];
                for (int k = 0; k < list.Count; k++)
                {
                    float num8 = Vector2.Distance(new Vector2((float)list[k].Item1, (float)list[k].Item2) * 16f + Vector2.One * 8f, vector);
                    if (num7 == -1f || num8 < num7)
                    {
                        num7 = num8;
                        tuple = list[k];
                    }
                }
                if (Collision.InTileBounds(tuple.Item1, tuple.Item2, num, num2, num3, num4))
                {
                    flag = true;
                    for (int l = 0; l < 1000; l++)
                    {
                        if (ProjectileID.Sets.IsAGolfBall[Main.projectile[l].type] && Main.projectile[l].owner == this.whoAmI)
{
                            Main.projectile[l].Kill();
                        }
                    }
                    int num9;
                    this.GetPreferredGolfBallToUse(out num9);
                    Projectile.NewProjectile(this.GetProjectileSource_TileInteraction(tuple.Item1, tuple.Item2), (float)(tuple.Item1 * 16) + 8.5f, (float)(tuple.Item2 * 16 + 6), 0f, 0f, num9, 0, 0f, this.whoAmI, 0f, -1f, 0f, null);
                }
            }
            return flag;
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.DataStructures.TileReachCheckSettings.GetTileRegion(), Terraria.Framing.GetTileSafely(), Terraria.Collision.InTileBounds(), Terraria.WorldGen.InWorld(), Terraria.ID.ProjectileID.Sets.IsAGolfBall, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, Terraria.Projectile.Kill(), System.list, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Projectile.NewProjectile(), Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.Main.screenHeight, Terraria.DataStructures.TileReachCheckSettings.Simple, and Terraria.Projectile.type.
Referenced by Terraria.Projectile.AI_150_GolfClubHelper().