Terraria Decompiled: Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids
PlaceThing_Tiles_PlaceIt_KillGrassForSolids()
void Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids () inline private
Definition at line 39457 of file Player.cs.
        {
            if (this.inventory[this.selectedItem].createTile < 0)
            {
                return;
            }
            if (Main.tileSolid[this.inventory[this.selectedItem].createTile])
            {
                for (int i = Player.tileTargetX - 1; i <= Player.tileTargetX + 1; i++)
                {
                    for (int j = Player.tileTargetY - 1; j <= Player.tileTargetY + 1; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if (tile.active() && this.inventory[this.selectedItem].createTile != (int)tile.type && (tile.type == 2 || tile.type == 23 || tile.type == 60 || tile.type == 70 || tile.type == 109 || tile.type == 199 || tile.type == 477 || tile.type == 492 || tile.type == 633))
{
                            bool flag = true;
                            for (int k = i - 1; k <= i + 1; k++)
{
                                for (int l = j - 1; l <= j + 1; l++)
{
                                    if (!WorldGen.SolidTile(k, l, false))
{
                                        flag = false;
                                    }
                                }
                            }
                            if (flag)
{
                                WorldGen.KillTile(i, j, true, false, false);
                                if (Main.netMode == 1)
{
                                    NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 1f, 0, 0, 0);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), int, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, and Terraria.Tile.type.