Terraria Decompiled: Terraria.Player.PlayerNoSpaceTeleport
PlayerNoSpaceTeleport()
void Terraria.Player.PlayerNoSpaceTeleport () inline
Definition at line 3240 of file Player.cs.
        {
            this.FailedNoSpaceCount = 0;
            Vector2 vector;
            if (TeleportHelpers.FindClosestTeleportSpotNoSpace(this, out vector))
            {
                this.Teleport(vector, 11, 0);
                if (Main.netMode == 2)
                {
                    RemoteClient.CheckSection(this.whoAmI, vector, 1);
                    NetMessage.SendData(65, -1, -1, null, 0, (float)this.whoAmI, vector.X, vector.Y, 11, false.ToInt(), 0);
                    return;
                }
            }
            else
            {
                this.Shellphone_Spawn();
            }
        }
References Terraria.RemoteClient.CheckSection(), Terraria.GameContent.TeleportHelpers.FindClosestTeleportSpotNoSpace(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Player.Shellphone_Spawn(), Terraria.Player.Teleport(), Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.QuickMount().