Terraria Decompiled: Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag
GetItem_FillEmptyInventorySlot_VoidBag()
bool Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag (Item[] inv, Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
Definition at line 38377 of file Player.cs.
        {
            if (inv[i].type != 0)
            {
                return false;
            }
            if (!settings.NoSound)
            {
                SoundEngine.PlaySound(newItem.IsACoin ? 38 : 7, -1, -1, 1, 1f, 0f);
            }
            inv[i] = returnItem;
            Player.GetItemLogger.Add(inv, i, 32, returnItem.stack);
            if (!settings.NoText)
            {
                PopupText.NewText(PopupTextContext.ItemPickupToVoidContainer, newItem, base.Center, newItem.stack, false, settings.LongText);
            }
            if (!settings.NoCoinMerge)
            {
                this.DoCoins(i);
            }
            AchievementsHelper.NotifyItemPickup(this, returnItem);
            settings.HandlePostAction(inv[i]);
            return true;
        }
References Terraria.DataStructures.PlayerGetItemLogger.Add(), Terraria.Player.GetItemLogger, Terraria.GetItemSettings.HandlePostAction(), Terraria.Item.IsACoin, Terraria.GetItemSettings.LongText, Terraria.PopupText.NewText(), Terraria.GetItemSettings.NoCoinMerge, Terraria.GetItemSettings.NoSound, Terraria.GetItemSettings.NoText, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Item.stack.