Terraria Decompiled: Terraria.Player.DoDeadCellsBeheadedParticles
DoDeadCellsBeheadedParticles()
void Terraria.Player.DoDeadCellsBeheadedParticles () inline private
Definition at line 22799 of file Player.cs.
        {
            if (Main.netMode == 2 || Main.gamePaused || this.dead || this.ghost || this.stoned || this.frozen)
            {
                return;
            }
            if (this.head != 282)
            {
                return;
            }
            if (this.sitting.isSitting || this.sleeping.isSleeping)
            {
                return;
            }
            if (this.mount.Active && this.mount.Type >= 0 && MountID.Sets.PlayerIsHidden[this.mount.Type])
            {
                return;
            }
            Vector2 vector = this.MountedTop + new Vector2(0f, 8f * this.gravDir + this.gfxOffY + Utils.Remap(Math.Abs(this.velocity.X), 0f, 3f, 0f, -4f, true) * this.gravDir);
            if (this.fullRotation != 0f)
            {
                vector = vector.RotatedBy((double)this.fullRotation, this.position + this.fullRotationOrigin);
            }
            Vector2 vector2 = this.velocity;
            if (this.fullRotation != 0f && this.mount.Active && this.mount.AnyTrackRider)
            {
                vector2 = vector2.RotatedBy((double)this.fullRotation, Vector2.Zero);
            }
            ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.DeadCellsBeheadedEffect, new ParticleOrchestraSettings
            {
                PositionInWorld = vector,
                MovementVector = vector2
            }, new int?(this.whoAmI));
        }
References System.Math.Abs(), Terraria.Main.gamePaused, Terraria.Main.netMode, Terraria.ID.MountID.Sets.PlayerIsHidden, Terraria.Utils.Remap(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), and Microsoft.Xna.Framework.Vector2.Zero.