Terraria Decompiled: Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag
GetItem_FillIntoOccupiedSlot_VoidBag()
bool Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag (Item[] inv, Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
Definition at line 38286 of file Player.cs.
        {
            if (inv[i].type > 0 && inv[i].stack < inv[i].maxStack && Item.CanStack(returnItem, inv[i]))
            {
                if (!settings.NoSound)
                {
                    SoundEngine.PlaySound(newItem.IsACoin ? 38 : 7, -1, -1, 1, 1f, 0f);
                }
                if (returnItem.stack + inv[i].stack <= inv[i].maxStack)
                {
                    inv[i].stack += returnItem.stack;
                    Player.GetItemLogger.Add(inv, i, 32, returnItem.stack);
                    if (!settings.NoText)
                    {
                        PopupText.NewText(PopupTextContext.ItemPickupToVoidContainer, newItem, base.Center, returnItem.stack, false, settings.LongText);
                    }
                    AchievementsHelper.NotifyItemPickup(this, returnItem);
                    settings.HandlePostAction(inv[i]);
                    return true;
                }
                int num = inv[i].maxStack - inv[i].stack;
                Player.GetItemLogger.Add(inv, i, 32, num);
                AchievementsHelper.NotifyItemPickup(this, returnItem, num);
                returnItem.stack -= num;
                if (!settings.NoText)
                {
                    PopupText.NewText(PopupTextContext.ItemPickupToVoidContainer, newItem, base.Center, inv[i].maxStack - inv[i].stack, false, settings.LongText);
                }
                inv[i].stack = inv[i].maxStack;
                settings.HandlePostAction(inv[i]);
            }
            return false;
        }
References Terraria.DataStructures.PlayerGetItemLogger.Add(), Terraria.Item.CanStack(), Terraria.Player.GetItemLogger, Terraria.GetItemSettings.HandlePostAction(), Terraria.Item.IsACoin, Terraria.GetItemSettings.LongText, Terraria.Item.maxStack, Terraria.PopupText.NewText(), Terraria.GetItemSettings.NoSound, Terraria.GetItemSettings.NoText, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Audio.SoundEngine.PlaySound(), System.stack, and Terraria.Item.stack.