Terraria Decompiled: Terraria.Player.WouldSpotOverlapWithSentry
WouldSpotOverlapWithSentry()
static bool Terraria.Player.WouldSpotOverlapWithSentry (int worldX, int worldY, bool lightningAura) inline static
Definition at line 52261 of file Player.cs.
        {
            Point point = new Point(worldX, worldY - 8);
            Point point2 = new Point(worldX + 16, worldY - 8);
            Point point3 = new Point(worldX - 16, worldY - 8);
            bool flag = false;
            for (int i = 0; i < 1000; i++)
            {
                Projectile projectile = Main.projectile[i];
                if (projectile.active && projectile.sentry)
                {
                    Rectangle hitbox = projectile.Hitbox;
                    if (lightningAura)
                    {
                        hitbox.Inflate(8, 0);
                    }
                    else if (hitbox.X > 30)
                    {
                        hitbox.X += hitbox.Width / 2;
                        hitbox.Width = 30;
                        hitbox.X -= hitbox.Width / 2;
                    }
                    if (hitbox.Contains(point) || hitbox.Contains(point2) || hitbox.Contains(point3))
                    {
                        flag = true;
                        break;
                    }
                }
            }
            return flag;
        }
References Terraria.Projectile.active, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Main.projectile, Terraria.Projectile.sentry, and Microsoft.Xna.Framework.Rectangle.X.
Referenced by Terraria.Player.ItemCheck_CheckCanUse_Inner().