Terraria Decompiled: Terraria.Player.UpdateBuffs
UpdateBuffs()
void Terraria.Player.UpdateBuffs (int i) inline
Definition at line 7510 of file Player.cs.
        {
            if (this.soulDrain > 0 && this.whoAmI == Main.myPlayer)
            {
                this.AddBuff(151, 2, false);
            }
            if (Main.dontStarveWorld)
            {
                this.UpdateStarvingState(true);
            }
            for (int j = 0; j < Player.maxBuffs; j++)
            {
                if (this.buffType[j] > 0 && this.buffTime[j] > 0)
                {
                    if (this.whoAmI == Main.myPlayer && !BuffID.Sets.TimeLeftDoesNotDecrease[this.buffType[j]])
                    {
                        this.buffTime[j]--;
                    }
                    if (this.buffType[j] == 1)
                    {
                        this.lavaImmune = true;
                        this.fireWalk = true;
                        this.buffImmune[24] = true;
                    }
                    else if (BuffID.Sets.MountType[this.buffType[j]] != -1)
                    {
                        this.mount.SetMount(BuffID.Sets.MountType[this.buffType[j]], this);
                        this.buffTime[j] = 10;
                        if (this.buffType[j] == 131)
{
                            this.ignoreWater = true;
                            this.accFlipper = true;
                        }
                        else if (this.buffType[j] == 168)
{
                            this.ignoreWater = true;
                            this.accFlipper = true;
                        }
                        else if (this.buffType[j] == 265)
{
                            this.canFloatInWater = true;
                            this.accFlipper = true;
                        }
                        else if (this.buffType[j] == 279)
{
                            this.ignoreWater = true;
                            this.accFlipper = true;
                        }
                        else if (this.buffType[j] == 305)
{
                            this.ignoreWater = true;
                            this.accFlipper = true;
                            this.lavaImmune = true;
                            this.lavaVision = true;
                            this.fireWalk = true;
                        }
                    }
                    else if (this.buffType[j] == 383)
                    {
                        this.moveSpeed += 0.25f;
                        this.pickSpeed -= 0.15f;
                        this.tileSpeed += 0.15f;
                        this.wallSpeed += 0.15f;
                        byte b = (byte)Utils.Clamp<int>(this.buffTime[j] / 10800, 0, 3);
                        if (b != this.kiteLuckLevel)
{
                            this.kiteLuckLevel = b;
                            this.luckNeedsSync = true;
                        }
                    }
                    else if (this.buffType[j] == 159)
                    {
                        this.meleeArmorPenetration += 12;
                    }
                    else if (this.buffType[j] == 158)
                    {
                        this.manaRegenDelayBonus += 0.5f;
                        this.manaRegenBonus += 10;
                    }
                    else if (this.buffType[j] == 192)
                    {
                        this.pickSpeed -= 0.2f;
                        this.moveSpeed += 0.2f;
                    }
                    else if (this.buffType[j] == 321)
                    {
                        int num = 10;
                        this.meleeCrit += num;
                        this.rangedCrit += num;
                        this.magicCrit += num;
                        this.minionDamage += (float)num / 100f;
                    }
                    else if (this.buffType[j] == 2)
                    {
                        this.lifeRegen += 4;
                    }
                    else if (this.buffType[j] == 3)
                    {
                        this.moveSpeed += 0.25f;
                    }
                    else if (this.buffType[j] == 4)
                    {
                        this.gills = true;
                    }
                    else if (this.buffType[j] == 5)
                    {
                        this.statDefense += 8;
                    }
                    else if (this.buffType[j] == 6)
                    {
                        this.manaRegenBuff = true;
                    }
                    else if (this.buffType[j] == 7)
                    {
                        this.magicDamage += 0.2f;
                    }
                    else if (this.buffType[j] == 8)
                    {
                        this.slowFall = true;
                    }
                    else if (this.buffType[j] == 9)
                    {
                        this.findTreasure = true;
                    }
                    else if (this.buffType[j] == 343)
                    {
                        this.biomeSight = true;
                    }
                    else if (this.buffType[j] == 10)
                    {
                        this.invis = true;
                    }
                    else if (this.buffType[j] == 11)
                    {
                        Lighting.AddLight((int)(this.position.X + (float)(this.width / 2)) / 16, (int)(this.position.Y + (float)(this.height / 2)) / 16, 0.8f, 0.95f, 1f);
                    }
                    else if (this.buffType[j] == 12)
                    {
                        this.nightVision = true;
                    }
                    else if (this.buffType[j] == 13)
                    {
                        this.enemySpawns = true;
                    }
                    else if (this.buffType[j] == 14)
                    {
                        if (this.thorns < 1f)
{
                            this.thorns = 1f;
                        }
                    }
                    else if (this.buffType[j] == 15)
                    {
                        this.waterWalk = true;
                    }
                    else if (this.buffType[j] == 16)
                    {
                        this.archery = true;
                        this.arrowDamage *= 1.1f;
                    }
                    else if (this.buffType[j] == 17)
                    {
                        this.detectCreature = true;
                    }
                    else if (this.buffType[j] == 18)
                    {
                        this.gravControl = true;
                    }
                    else if (this.buffType[j] == 30)
                    {
                        this.bleed = true;
                    }
                    else if (this.buffType[j] == 31)
                    {
                        this.confused = true;
                    }
                    else if (this.buffType[j] == 32)
                    {
                        this.slow = true;
                    }
                    else if (this.buffType[j] == 35)
                    {
                        this.silence = true;
                    }
                    else if (this.buffType[j] == 160)
                    {
                        this.dazed = true;
                    }
                    else if (this.buffType[j] == 46)
                    {
                        this.chilled = true;
                    }
                    else if (this.buffType[j] == 47)
                    {
                        this.frozen = true;
                    }
                    else if (this.buffType[j] == 156)
                    {
                        this.stoned = true;
                    }
                    else if (this.buffType[j] == 69)
                    {
                        this.ichor = true;
                        this.statDefense -= 15;
                    }
                    else if (this.buffType[j] == 36)
                    {
                        this.brokenArmor = true;
                    }
                    else if (this.buffType[j] == 48)
                    {
                        this.honey = true;
                    }
                    else if (this.buffType[j] == 59)
                    {
                        this.shadowDodge = true;
                    }
                    else if (this.buffType[j] == 93)
                    {
                        this.ammoBox = true;
                    }
                    else if (this.buffType[j] == 58)
                    {
                        this.palladiumRegen = true;
                    }
                    else if (this.buffType[j] == 306)
                    {
                        this.hasTitaniumStormBuff = true;
                    }
                    else if (this.buffType[j] == 88)
                    {
                        this.chaosState = true;
                    }
                    else if (this.buffType[j] == 215)
                    {
                        this.statDefense += 5;
                    }
                    else if (this.buffType[j] == 311)
                    {
                        this.summonerWeaponSpeedBonus += 0.35f;
                    }
                    else if (this.buffType[j] == 308)
                    {
                        this.summonerWeaponSpeedBonus += 0.25f;
                    }
                    else if (this.buffType[j] == 314)
                    {
                        this.summonerWeaponSpeedBonus += 0.12f;
                    }
                    else if (this.buffType[j] == 312)
                    {
                        this.coolWhipBuff = true;
                    }
                    else if (this.buffType[j] == 365)
                    {
                        this.cobWhipBuff = true;
                    }
                    else if (this.buffType[j] == 63)
                    {
                        this.moveSpeed += 1f;
                    }
                    else if (this.buffType[j] == 104)
                    {
                        this.pickSpeed -= 0.25f;
                    }
                    else if (this.buffType[j] == 105)
                    {
                        this.lifeMagnet = true;
                    }
                    else if (this.buffType[j] == 106)
                    {
                        this.calmed = true;
                    }
                    else if (this.buffType[j] == 121)
                    {
                        this.fishingSkill += 15;
                    }
                    else if (this.buffType[j] == 122)
                    {
                        this.sonarPotion = true;
                    }
                    else if (this.buffType[j] == 123)
                    {
                        this.cratePotion = true;
                    }
                    else if (this.buffType[j] == 107)
                    {
                        this.tileSpeed += 0.25f;
                        this.wallSpeed += 0.25f;
                        this.blockRange++;
                    }
                    else if (this.buffType[j] == 108)
                    {
                        this.kbBuff = true;
                    }
                    else if (this.buffType[j] == 109)
                    {
                        this.ignoreWater = true;
                        this.accFlipper = true;
                    }
                    else if (this.buffType[j] == 110)
                    {
                        this.maxMinions++;
                    }
                    else if (this.buffType[j] == 150)
                    {
                        this.maxMinions++;
                    }
                    else if (this.buffType[j] == 348)
                    {
                        this.maxTurrets++;
                    }
                    else if (this.buffType[j] == 366)
                    {
                        this.deadCellsPotionStation = true;
                    }
                    else if (this.buffType[j] == 111)
                    {
                        this.dangerSense = true;
                    }
                    else if (this.buffType[j] == 112)
                    {
                        this.ammoPotion = true;
                    }
                    else if (this.buffType[j] == 113)
                    {
                        this.lifeForce = true;
                        this.statLifeMax2 += this.statLifeMax / 5 / 20 * 20;
                    }
                    else if (this.buffType[j] == 114)
                    {
                        this.endurance += 0.1f;
                    }
                    else if (this.buffType[j] == 115)
                    {
                        this.meleeCrit += 10;
                        this.rangedCrit += 10;
                        this.magicCrit += 10;
                    }
                    else if (this.buffType[j] == 116)
                    {
                        this.inferno = true;
                        Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), 0.65f, 0.4f, 0.1f);
                        int num2 = 323;
                        float num3 = 200f;
                        bool flag = this.infernoCounter % 60 == 0;
                        int num4 = 20;
                        if (this.whoAmI == Main.myPlayer)
{
                            for (int k = 0; k < Main.maxNPCs; k++)
{
                                NPC npc = Main.npc[k];
                                if (npc.active && !npc.friendly && npc.damage > 0 && !npc.dontTakeDamage && !npc.buffImmune[num2] && this.CanNPCBeHitByPlayerOrPlayerProjectile(npc, null) && Vector2.Distance(base.Center, npc.Center) <= num3)
{
                                    if (npc.FindBuffIndex(num2) == -1)
{
                                        npc.AddBuff(num2, 120, false);
                                    }
                                    if (flag)
{
                                        this.ApplyDamageToNPC(npc, num4, 0f, 0, false);
                                    }
                                }
                            }
                            if (this.hostile)
{
                                for (int l = 0; l < 255; l++)
{
                                    Player player = Main.player[l];
                                    if (player != this && player.active && !player.dead && player.hostile && !player.buffImmune[num2] && (player.team != this.team || player.team == 0) && Vector2.Distance(base.Center, player.Center) <= num3)
{
                                        if (player.FindBuffIndex(num2) == -1)
{
                                            player.AddBuff(num2, 120, false);
                                        }
                                        if (flag)
{
                                            PlayerDeathReason playerDeathReason = PlayerDeathReason.ByOther(16);
                                            player.Hurt(playerDeathReason, num4, 0, true, false, false, -1, true);
                                            if (Main.netMode != 0)
{
                                                NetMessage.SendPlayerHurt(l, playerDeathReason, num4, 0, false, true, ImmunityCooldownID.General, -1, -1);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    else if (this.buffType[j] == 117)
                    {
                        this.meleeDamage += 0.1f;
                        this.rangedDamage += 0.1f;
                        this.magicDamage += 0.1f;
                        this.minionDamage += 0.1f;
                    }
                    else if (this.buffType[j] == 119)
                    {
                        this.loveStruck = true;
                    }
                    else if (this.buffType[j] == 120)
                    {
                        this.talkNPC = -1;
                        this.stinky = true;
                    }
                    else if (this.buffType[j] == 124)
                    {
                        this.resistCold = true;
                    }
                    else if (this.buffType[j] == 257)
                    {
                        if (Main.myPlayer == this.whoAmI)
{
                            if (this.buffTime[j] > 36000)
{
                                this.luckPotion = 3;
                            }
                            else if (this.buffTime[j] > 18000)
{
                                this.luckPotion = 2;
                            }
                            else
{
                                this.luckPotion = 1;
                            }
                        }
                    }
                    else if (this.buffType[j] == 165)
                    {
                        this.lifeRegen += 6;
                        this.statDefense += 8;
                        this.dryadWard = true;
                        if (this.thorns < 1f)
{
                            this.thorns += 0.5f;
                        }
                    }
                    else if (this.buffType[j] == 144)
                    {
                        this.electrified = true;
                        Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.3f, 0.8f, 1.1f);
                    }
                    else if (this.buffType[j] == 94)
                    {
                        this.manaSick = true;
                        this.manaSickReduction = Player.manaSickLessDmg * ((float)this.buffTime[j] / (float)Player.manaSickTime);
                    }
                    else if (this.buffType[j] >= 95 && this.buffType[j] <= 97)
                    {
                        this.buffTime[j] = 5;
                        int num5 = (int)((byte)(1 + this.buffType[j] - 95));
                        if (this.beetleOrbs > 0 && this.beetleOrbs != num5)
{
                            if (this.beetleOrbs > num5)
{
                                this.DelBuff(j);
                                j--;
                            }
                            else
{
                                for (int m = 0; m < Player.maxBuffs; m++)
{
                                    if (this.buffType[m] >= 95 && this.buffType[m] <= 95 + num5 - 1)
{
                                        this.DelBuff(m);
                                        m--;
                                    }
                                }
                            }
                        }
                        this.beetleOrbs = num5;
                        if (!this.beetleDefense)
{
                            this.beetleOrbs = 0;
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.beetleBuff = true;
                        }
                    }
                    else if (this.buffType[j] >= 170 && this.buffType[j] <= 172)
                    {
                        this.buffTime[j] = 5;
                        int num6 = (int)((byte)(1 + this.buffType[j] - 170));
                        if (this.solarShields > 0 && this.solarShields != num6)
{
                            if (this.solarShields > num6)
{
                                this.DelBuff(j);
                                j--;
                            }
                            else
{
                                for (int n = 0; n < Player.maxBuffs; n++)
{
                                    if (this.buffType[n] >= 170 && this.buffType[n] <= 170 + num6 - 1)
{
                                        this.DelBuff(n);
                                        n--;
                                    }
                                }
                            }
                        }
                        this.solarShields = num6;
                        if (!this.setSolar)
{
                            this.solarShields = 0;
                            this.DelBuff(j);
                            j--;
                        }
                    }
                    else if (this.buffType[j] >= 98 && this.buffType[j] <= 100)
                    {
                        int num7 = (int)((byte)(1 + this.buffType[j] - 98));
                        if (this.beetleOrbs > 0 && this.beetleOrbs != num7)
{
                            if (this.beetleOrbs > num7)
{
                                this.DelBuff(j);
                                j--;
                            }
                            else
{
                                for (int num8 = 0; num8 < Player.maxBuffs; num8++)
{
                                    if (this.buffType[num8] >= 98 && this.buffType[num8] <= 98 + num7 - 1)
{
                                        this.DelBuff(num8);
                                        num8--;
                                    }
                                }
                            }
                        }
                        this.beetleOrbs = num7;
                        this.meleeDamage += 0.1f * (float)this.beetleOrbs;
                        this.meleeSpeed += 0.1f * (float)this.beetleOrbs;
                        if (!this.beetleOffense)
{
                            this.beetleOrbs = 0;
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.beetleBuff = true;
                        }
                    }
                    else if (this.buffType[j] >= 176 && this.buffType[j] <= 178)
                    {
                        this.UpdateBuffs_NebulaBuffs(ref this.nebulaLevelMana, 176, j);
                    }
                    else if (this.buffType[j] >= 173 && this.buffType[j] <= 175)
                    {
                        this.UpdateBuffs_NebulaBuffs(ref this.nebulaLevelLife, 173, j);
                        this.lifeRegen += 6 * this.nebulaLevelLife;
                    }
                    else if (this.buffType[j] >= 179 && this.buffType[j] <= 181)
                    {
                        this.UpdateBuffs_NebulaBuffs(ref this.nebulaLevelDamage, 179, j);
                        float num9 = 0.15f * (float)this.nebulaLevelDamage;
                        this.meleeDamage += num9;
                        this.rangedDamage += num9;
                        this.magicDamage += num9;
                        this.minionDamage += num9;
                    }
                    else if (this.buffType[j] == 62)
                    {
                        if ((double)this.statLife <= (double)this.statLifeMax2 * 0.5)
{
                            Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), 0.1f, 0.2f, 0.45f);
                            this.iceBarrier = true;
                            this.endurance += 0.25f;
                            this.iceBarrierFrameCounter += 1;
                            if (this.iceBarrierFrameCounter > 2)
{
                                this.iceBarrierFrameCounter = 0;
                                this.iceBarrierFrame += 1;
                                if (this.iceBarrierFrame >= 12)
{
                                    this.iceBarrierFrame = 0;
                                }
                            }
                        }
                        else
{
                            this.DelBuff(j);
                            j--;
                        }
                    }
                    else if (this.buffType[j] == 49)
                    {
                        for (int num10 = 191; num10 <= 194; num10++)
{
                            if (this.ownedProjectileCounts[num10] > 0)
{
                                this.pygmy = true;
                            }
                        }
                        if (!this.pygmy)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 83)
                    {
                        if (this.ownedProjectileCounts[317] > 0)
{
                            this.raven = true;
                        }
                        if (!this.raven)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 64)
                    {
                        if (this.ownedProjectileCounts[266] > 0)
{
                            this.slime = true;
                        }
                        if (!this.slime)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 125)
                    {
                        if (this.ownedProjectileCounts[373] > 0)
{
                            this.hornetMinion = true;
                        }
                        if (!this.hornetMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 126)
                    {
                        if (this.ownedProjectileCounts[375] > 0)
{
                            this.impMinion = true;
                        }
                        if (!this.impMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 133)
                    {
                        if (this.ownedProjectileCounts[390] > 0 || this.ownedProjectileCounts[391] > 0 || this.ownedProjectileCounts[392] > 0)
{
                            this.spiderMinion = true;
                        }
                        if (!this.spiderMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 134)
                    {
                        if (this.ownedProjectileCounts[387] > 0 || this.ownedProjectileCounts[388] > 0)
{
                            this.twinsMinion = true;
                        }
                        if (!this.twinsMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 135)
                    {
                        if (this.ownedProjectileCounts[393] > 0 || this.ownedProjectileCounts[394] > 0 || this.ownedProjectileCounts[395] > 0)
{
                            this.pirateMinion = true;
                        }
                        if (!this.pirateMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 214)
                    {
                        if (this.ownedProjectileCounts[758] > 0)
{
                            this.vampireFrog = true;
                        }
                        if (!this.vampireFrog)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 139)
                    {
                        if (this.ownedProjectileCounts[407] > 0)
{
                            this.sharknadoMinion = true;
                        }
                        if (!this.sharknadoMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 140)
                    {
                        if (this.ownedProjectileCounts[423] > 0)
{
                            this.UFOMinion = true;
                        }
                        if (!this.UFOMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 182)
                    {
                        if (this.ownedProjectileCounts[613] > 0)
{
                            this.stardustMinion = true;
                        }
                        if (!this.stardustMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 213)
                    {
                        if (this.ownedProjectileCounts[755] > 0)
{
                            this.batsOfLight = true;
                        }
                        if (!this.batsOfLight)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 216)
                    {
                        bool flag2 = true;
                        if (this.ownedProjectileCounts[759] > 0)
{
                            this.babyBird = true;
                        }
                        else if (this.whoAmI == Main.myPlayer)
{
                            if (this.numMinions < this.maxMinions)
{
                                int num11 = this.FindItem(4281);
                                if (num11 != -1)
{
                                    Item item = this.inventory[num11];
                                    int num12 = Projectile.NewProjectile(this.GetProjectileSource_Item(item), base.Top, Vector2.Zero, item.shoot, item.damage, item.knockBack, this.whoAmI, 0f, 0f, 0f, null);
                                    Main.projectile[num12].originalDamage = item.damage;
                                    this.babyBird = true;
                                }
                            }
                            if (!this.babyBird)
{
                                this.DelBuff(j);
                                j--;
                                flag2 = false;
                            }
                        }
                        if (flag2)
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 355)
                    {
                        if (this.ownedProjectileCounts[1022] > 0)
{
                            this.deadCellsMushroomBoiMinion = true;
                        }
                        if (!this.deadCellsMushroomBoiMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 385)
                    {
                        if (this.ownedProjectileCounts[1093] > 0)
{
                            this.palworldCattivaMinion = true;
                        }
                        if (!this.palworldCattivaMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 386)
                    {
                        if (this.ownedProjectileCounts[1094] > 0)
{
                            this.palworldFoxsparksMinion = true;
                        }
                        if (!this.palworldFoxsparksMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 325)
                    {
                        if (this.ownedProjectileCounts[951] > 0)
{
                            this.flinxMinion = true;
                        }
                        if (!this.flinxMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 335)
                    {
                        if (this.ownedProjectileCounts[970] > 0)
{
                            this.abigailMinion = true;
                        }
                        if (!this.abigailMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                        if (this.whoAmI == Main.myPlayer)
{
                            this.UpdateAbigailStatus();
                        }
                    }
                    else if (this.buffType[j] == 263)
                    {
                        if (this.ownedProjectileCounts[831] > 0)
{
                            this.stormTiger = true;
                        }
                        if (!this.stormTiger)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                        if (this.whoAmI == Main.myPlayer)
{
                            this.UpdateStormTigerStatus();
                        }
                    }
                    else if (this.buffType[j] == 271)
                    {
                        if (this.ownedProjectileCounts[864] > 0)
{
                            this.smolstar = true;
                        }
                        if (!this.smolstar)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 322)
                    {
                        if (this.ownedProjectileCounts[946] > 0)
{
                            this.empressBlade = true;
                        }
                        if (!this.empressBlade)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 187)
                    {
                        if (this.ownedProjectileCounts[623] > 0)
{
                            this.stardustGuardian = true;
                        }
                        if (!this.stardustGuardian)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 188)
                    {
                        if (this.ownedProjectileCounts[625] > 0)
{
                            this.stardustDragon = true;
                        }
                        if (!this.stardustDragon)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 161)
                    {
                        if (this.ownedProjectileCounts[533] > 0)
{
                            this.DeadlySphereMinion = true;
                        }
                        if (!this.DeadlySphereMinion)
{
                            this.DelBuff(j);
                            j--;
                        }
                        else
{
                            this.buffTime[j] = 18000;
                        }
                    }
                    else if (this.buffType[j] == 37)
                    {
                        if (Main.wofNPCIndex >= 0 && Main.npc[Main.wofNPCIndex].type == 113)
{
                            this.gross = true;
                            this.buffTime[j] = 10;
                        }
                        else
{
                            this.DelBuff(j);
                            j--;
                        }
                    }
                    else if (this.buffType[j] == 38)
                    {
                        this.buffTime[j] = 10;
                        this.tongued = true;
                    }
                    else if (this.buffType[j] == 376 && this.whoAmI == Main.myPlayer)
                    {
                        this.TorchGodsFlavor();
                    }
                    else if (this.buffType[j] == 146)
                    {
                        this.moveSpeed += 0.1f;
                        this.moveSpeed *= 1.1f;
                        this.sunflower = true;
                    }
                    else if (this.buffType[j] == 19)
                    {
                        this.buffTime[j] = 18000;
                        this.lightOrb = true;
                        bool flag3 = true;
                        if (this.ownedProjectileCounts[18] > 0)
{
                            flag3 = false;
                        }
                        if (flag3 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 18, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 155)
                    {
                        this.buffTime[j] = 18000;
                        this.crimsonHeart = true;
                        bool flag4 = true;
                        if (this.ownedProjectileCounts[500] > 0)
{
                            flag4 = false;
                        }
                        if (flag4 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 500, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 191)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.companionCube, 653, 18000);
                    }
                    else if (this.buffType[j] == 202)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDD2Dragon, 701, 18000);
                    }
                    else if (this.buffType[j] == 217)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagUpbeatStar, 764, 18000);
                    }
                    else if (this.buffType[j] == 219)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagBabyShark, 774, 18000);
                    }
                    else if (this.buffType[j] == 258)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagLilHarpy, 815, 18000);
                    }
                    else if (this.buffType[j] == 259)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagFennecFox, 816, 18000);
                    }
                    else if (this.buffType[j] == 260)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagGlitteryButterfly, 817, 18000);
                    }
                    else if (this.buffType[j] == 261)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagBabyImp, 821, 18000);
                    }
                    else if (this.buffType[j] == 262)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagBabyRedPanda, 825, 18000);
                    }
                    else if (this.buffType[j] == 264)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagPlantero, 854, 18000);
                    }
                    else if (this.buffType[j] == 266)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDynamiteKitten, 858, 18000);
                    }
                    else if (this.buffType[j] == 267)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagBabyWerewolf, 859, 18000);
                    }
                    else if (this.buffType[j] == 268)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagShadowMimic, 860, 18000);
                    }
                    else if (this.buffType[j] == 274)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagVoltBunny, 875, 18000);
                    }
                    else if (this.buffType[j] == 284)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagKingSlimePet, 881, 18000);
                    }
                    else if (this.buffType[j] == 285)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagEyeOfCthulhuPet, 882, 18000);
                    }
                    else if (this.buffType[j] == 286)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagEaterOfWorldsPet, 883, 18000);
                    }
                    else if (this.buffType[j] == 287)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagBrainOfCthulhuPet, 884, 18000);
                    }
                    else if (this.buffType[j] == 288)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagSkeletronPet, 885, 18000);
                    }
                    else if (this.buffType[j] == 289)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagQueenBeePet, 886, 18000);
                    }
                    else if (this.buffType[j] == 290)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDestroyerPet, 887, 18000);
                    }
                    else if (this.buffType[j] == 291)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagTwinsPet, 888, 18000);
                    }
                    else if (this.buffType[j] == 292)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagSkeletronPrimePet, 889, 18000);
                    }
                    else if (this.buffType[j] == 293)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagPlanteraPet, 890, 18000);
                    }
                    else if (this.buffType[j] == 294)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagGolemPet, 891, 18000);
                    }
                    else if (this.buffType[j] == 295)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDukeFishronPet, 892, 18000);
                    }
                    else if (this.buffType[j] == 296)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagLunaticCultistPet, 893, 18000);
                    }
                    else if (this.buffType[j] == 297)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagMoonLordPet, 894, 18000);
                    }
                    else if (this.buffType[j] == 298)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagFairyQueenPet, 895, 18000);
                    }
                    else if (this.buffType[j] == 299)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagPumpkingPet, 896, 18000);
                    }
                    else if (this.buffType[j] == 300)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagEverscreamPet, 897, 18000);
                    }
                    else if (this.buffType[j] == 301)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagIceQueenPet, 898, 18000);
                    }
                    else if (this.buffType[j] == 302)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagMartianPet, 899, 18000);
                    }
                    else if (this.buffType[j] == 303)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDD2OgrePet, 900, 18000);
                    }
                    else if (this.buffType[j] == 304)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDD2BetsyPet, 901, 18000);
                    }
                    else if (this.buffType[j] == 317)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagQueenSlimePet, 934, 18000);
                    }
                    else if (this.buffType[j] == 327)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagBerniePet, 956, 18000);
                    }
                    else if (this.buffType[j] == 328)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagGlommerPet, 957, 18000);
                    }
                    else if (this.buffType[j] == 329)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDeerclopsPet, 958, 18000);
                    }
                    else if (this.buffType[j] == 330)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagPigPet, 959, 18000);
                    }
                    else if (this.buffType[j] == 331)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagChesterPet, 960, 18000);
                    }
                    else if (this.buffType[j] == 341)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagKingSlimePet, 881, 18000);
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagQueenSlimePet, 934, 18000);
                    }
                    else if (this.buffType[j] == 345)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagJunimoPet, 994, 18000);
                    }
                    else if (this.buffType[j] == 349)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagBlueChickenPet, 998, 18000);
                    }
                    else if (this.buffType[j] == 351)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagSpiffo, 1003, 18000);
                    }
                    else if (this.buffType[j] == 352)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagCaveling, 1004, 18000);
                    }
                    else if (this.buffType[j] == 354)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDirtiestBlock, 1018, 18000);
                    }
                    else if (this.buffType[j] == 373)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagBoulderPet, 1056, 18000);
                    }
                    else if (this.buffType[j] == 382)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagRainbowBoulderPet, 1090, 18000);
                    }
                    else if (this.buffType[j] == 356)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDeadCellsSwarmBiter, 1027, 18000);
                    }
                    else if (this.buffType[j] == 371)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagPufferfish, 1046, 18000);
                    }
                    else if (this.buffType[j] == 372)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagAxeFairyPet, 1050, 18000);
                    }
                    else if (this.buffType[j] == 200)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDD2Gato, 703, 18000);
                    }
                    else if (this.buffType[j] == 201)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagDD2Ghost, 702, 18000);
                    }
                    else if (this.buffType[j] == 218)
                    {
                        this.BuffHandle_SpawnPetIfNeededAndSetTime(j, ref this.petFlagSugarGlider, 765, 18000);
                    }
                    else if (this.buffType[j] == 190)
                    {
                        this.buffTime[j] = 18000;
                        this.suspiciouslookingTentacle = true;
                        bool flag5 = true;
                        if (this.ownedProjectileCounts[650] > 0)
{
                            flag5 = false;
                        }
                        if (flag5 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 650, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 27 || this.buffType[j] == 101 || this.buffType[j] == 102)
                    {
                        this.buffTime[j] = 18000;
                        bool flag6 = true;
                        short num13 = 72;
                        int num14 = this.buffType[j];
                        if (num14 != 101)
{
                            if (num14 == 102)
{
                                num13 = 87;
                            }
                        }
                        else
{
                            num13 = 86;
                        }
                        if (this.head == 45 && this.body == 26 && this.legs == 25)
{
                            num13 = 72;
                        }
                        if (num13 != 72)
{
                            if (num13 != 86)
{
                                if (num13 == 87)
{
                                    this.greenFairy = true;
                                }
                            }
                            else
{
                                this.redFairy = true;
                            }
                        }
                        else
{
                            this.blueFairy = true;
                        }
                        if (this.ownedProjectileCounts[(int)num13] > 0)
{
                            flag6 = false;
                        }
                        if (flag6 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, (int)num13, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 40)
                    {
                        this.buffTime[j] = 18000;
                        this.bunny = true;
                        bool flag7 = true;
                        if (this.ownedProjectileCounts[111] > 0)
{
                            flag7 = false;
                        }
                        if (flag7 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 111, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 148)
                    {
                        this.rabid = true;
                        if (Main.rand.Next(1200) == 0)
{
                            int num15 = Main.rand.Next(6);
                            float num16 = (float)Main.rand.Next(60, 100) * 0.01f;
                            if (num15 == 0)
{
                                this.AddBuff(22, (int)(60f * num16 * 3f), false);
                            }
                            else if (num15 == 1)
{
                                this.AddBuff(23, (int)(60f * num16 * 0.75f), false);
                            }
                            else if (num15 == 2)
{
                                this.AddBuff(31, (int)(60f * num16 * 1.5f), false);
                            }
                            else if (num15 == 3)
{
                                this.AddBuff(32, (int)(60f * num16 * 3.5f), false);
                            }
                            else if (num15 == 4)
{
                                this.AddBuff(33, (int)(60f * num16 * 5f), false);
                            }
                            else if (num15 == 5)
{
                                this.AddBuff(35, (int)(60f * num16 * 1f), false);
                            }
                        }
                        this.meleeDamage += 0.2f;
                        this.magicDamage += 0.2f;
                        this.rangedDamage += 0.2f;
                        this.minionDamage += 0.2f;
                    }
                    else if (this.buffType[j] == 41)
                    {
                        this.buffTime[j] = 18000;
                        this.penguin = true;
                        bool flag8 = true;
                        if (this.ownedProjectileCounts[112] > 0)
{
                            flag8 = false;
                        }
                        if (flag8 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 112, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 152)
                    {
                        this.buffTime[j] = 18000;
                        this.magicLantern = true;
                        if (this.ownedProjectileCounts[492] == 0 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 492, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 91)
                    {
                        this.buffTime[j] = 18000;
                        this.puppy = true;
                        bool flag9 = true;
                        if (this.ownedProjectileCounts[334] > 0)
{
                            flag9 = false;
                        }
                        if (flag9 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 334, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 92)
                    {
                        this.buffTime[j] = 18000;
                        this.grinch = true;
                        bool flag10 = true;
                        if (this.ownedProjectileCounts[353] > 0)
{
                            flag10 = false;
                        }
                        if (flag10 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 353, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 84)
                    {
                        this.buffTime[j] = 18000;
                        this.blackCat = true;
                        bool flag11 = true;
                        if (this.ownedProjectileCounts[319] > 0)
{
                            flag11 = false;
                        }
                        if (flag11 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 319, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 61)
                    {
                        this.buffTime[j] = 18000;
                        this.dino = true;
                        bool flag12 = true;
                        if (this.ownedProjectileCounts[236] > 0)
{
                            flag12 = false;
                        }
                        if (flag12 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 236, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 154)
                    {
                        this.buffTime[j] = 18000;
                        this.babyFaceMonster = true;
                        bool flag13 = true;
                        if (this.ownedProjectileCounts[499] > 0)
{
                            flag13 = false;
                        }
                        if (flag13 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 499, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 65)
                    {
                        this.buffTime[j] = 18000;
                        this.eyeSpring = true;
                        bool flag14 = true;
                        if (this.ownedProjectileCounts[268] > 0)
{
                            flag14 = false;
                        }
                        if (flag14 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 268, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 66)
                    {
                        this.buffTime[j] = 18000;
                        this.snowman = true;
                        bool flag15 = true;
                        if (this.ownedProjectileCounts[269] > 0)
{
                            flag15 = false;
                        }
                        if (flag15 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 269, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 42)
                    {
                        this.buffTime[j] = 18000;
                        this.turtle = true;
                        bool flag16 = true;
                        if (this.ownedProjectileCounts[127] > 0)
{
                            flag16 = false;
                        }
                        if (flag16 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 127, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 45)
                    {
                        this.buffTime[j] = 18000;
                        this.eater = true;
                        bool flag17 = true;
                        if (this.ownedProjectileCounts[175] > 0)
{
                            flag17 = false;
                        }
                        if (flag17 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 175, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 50)
                    {
                        this.buffTime[j] = 18000;
                        this.skeletron = true;
                        bool flag18 = true;
                        if (this.ownedProjectileCounts[197] > 0)
{
                            flag18 = false;
                        }
                        if (flag18 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 197, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 51)
                    {
                        this.buffTime[j] = 18000;
                        this.hornet = true;
                        bool flag19 = true;
                        if (this.ownedProjectileCounts[198] > 0)
{
                            flag19 = false;
                        }
                        if (flag19 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 198, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 52)
                    {
                        this.buffTime[j] = 18000;
                        this.tiki = true;
                        bool flag20 = true;
                        if (this.ownedProjectileCounts[199] > 0)
{
                            flag20 = false;
                        }
                        if (flag20 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 199, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 53)
                    {
                        this.buffTime[j] = 18000;
                        this.lizard = true;
                        bool flag21 = true;
                        if (this.ownedProjectileCounts[200] > 0)
{
                            flag21 = false;
                        }
                        if (flag21 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 200, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 54)
                    {
                        this.buffTime[j] = 18000;
                        this.parrot = true;
                        bool flag22 = true;
                        if (this.ownedProjectileCounts[208] > 0)
{
                            flag22 = false;
                        }
                        if (flag22 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 208, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 55)
                    {
                        this.buffTime[j] = 18000;
                        this.truffle = true;
                        bool flag23 = true;
                        if (this.ownedProjectileCounts[209] > 0)
{
                            flag23 = false;
                        }
                        if (flag23 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 209, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 56)
                    {
                        this.buffTime[j] = 18000;
                        this.sapling = true;
                        bool flag24 = true;
                        if (this.ownedProjectileCounts[210] > 0)
{
                            flag24 = false;
                        }
                        if (flag24 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 210, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 85)
                    {
                        this.buffTime[j] = 18000;
                        this.cSapling = true;
                        bool flag25 = true;
                        if (this.ownedProjectileCounts[324] > 0)
{
                            flag25 = false;
                        }
                        if (flag25 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 324, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 81)
                    {
                        this.buffTime[j] = 18000;
                        this.spider = true;
                        bool flag26 = true;
                        if (this.ownedProjectileCounts[313] > 0)
{
                            flag26 = false;
                        }
                        if (flag26 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 313, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 82)
                    {
                        this.buffTime[j] = 18000;
                        this.squashling = true;
                        bool flag27 = true;
                        if (this.ownedProjectileCounts[314] > 0)
{
                            flag27 = false;
                        }
                        if (flag27 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 314, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 57)
                    {
                        this.buffTime[j] = 18000;
                        this.wisp = true;
                        bool flag28 = true;
                        if (this.ownedProjectileCounts[211] > 0)
{
                            flag28 = false;
                        }
                        if (flag28 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 211, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 60)
                    {
                        this.buffTime[j] = 18000;
                        this.crystalLeaf = true;
                        bool flag29 = true;
                        for (int num17 = 0; num17 < 1000; num17++)
{
                            if (Main.projectile[num17].active && Main.projectile[num17].owner == this.whoAmI && Main.projectile[num17].type == 226)
{
                                if (!flag29)
{
                                    Main.projectile[num17].Kill();
                                }
                                flag29 = false;
                            }
                        }
                        if (flag29 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 226, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 127)
                    {
                        this.buffTime[j] = 18000;
                        this.zephyrfish = true;
                        bool flag30 = true;
                        if (this.ownedProjectileCounts[380] > 0)
{
                            flag30 = false;
                        }
                        if (flag30 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 380, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 136)
                    {
                        this.buffTime[j] = 18000;
                        this.miniMinotaur = true;
                        bool flag31 = true;
                        if (this.ownedProjectileCounts[398] > 0)
{
                            flag31 = false;
                        }
                        if (flag31 && this.whoAmI == Main.myPlayer)
{
                            Projectile.NewProjectile(this.GetProjectileSource_Buff(j), this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), 0f, 0f, 398, 0, 0f, this.whoAmI, 0f, 0f, 0f, null);
                        }
                    }
                    else if (this.buffType[j] == 70)
                    {
                        this.venom = true;
                    }
                    else if (this.buffType[j] == 20)
                    {
                        this.poisoned = true;
                    }
                    else if (this.buffType[j] == 21)
                    {
                        this.potionDelay = this.buffTime[j];
                    }
                    else if (this.buffType[j] == 22)
                    {
                        this.blind = true;
                    }
                    else if (this.buffType[j] == 80)
                    {
                        this.blackout = true;
                    }
                    else if (this.buffType[j] == 23)
                    {
                        this.noItems = true;
                        this.cursed = true;
                    }
                    else if (this.buffType[j] == 24)
                    {
                        this.onFire = true;
                    }
                    else if (this.buffType[j] == 103)
                    {
                        if (this.lavaWet)
{
                            this.DelBuff(j);
                        }
                        else
{
                            this.dripping = true;
                            this.buffImmune[24] = true;
                            this.buffImmune[323] = true;
                            this.buffImmune[67] = true;
                        }
                    }
                    else if (this.buffType[j] == 137)
                    {
                        this.drippingSlime = true;
                    }
                    else if (this.buffType[j] == 320)
                    {
                        this.drippingSparkleSlime = true;
                    }
                    else if (this.buffType[j] == 67)
                    {
                        this.burned = true;
                    }
                    else if (this.buffType[j] == 68)
                    {
                        this.suffocating = true;
                    }
                    else if (this.buffType[j] == 39)
                    {
                        this.onFire2 = true;
                    }
                    else if (this.buffType[j] == 323)
                    {
                        this.onFire3 = true;
                    }
                    else if (this.buffType[j] == 44)
                    {
                        this.onFrostBurn = true;
                    }
                    else if (this.buffType[j] == 324)
                    {
                        this.onFrostBurn2 = true;
                    }
                    else if (this.buffType[j] == 353)
                    {
                        this.shimmering = true;
                        this.frozen = true;
                        this.fallStart = (int)(this.position.Y / 16f);
                        if (Main.myPlayer == this.whoAmI)
{
                            if (this.position.Y / 16f > (float)Main.UnderworldLayer)
{
                                if (Main.myPlayer == this.whoAmI)
{
                                    this.DelBuff(j);
                                }
                            }
                            else if (this.shimmerWet)
{
                                this.buffTime[j] = 60;
                            }
                            else
{
                                bool flag32 = false;
                                int num18 = (int)(this.position.X / 16f);
                                while ((float)num18 <= (this.position.X + (float)this.width) / 16f)
{
                                    int num19 = (int)(this.position.Y / 16f);
                                    while ((float)num19 <= (this.position.Y + (float)this.height) / 16f)
{
                                        if (WorldGen.SolidTile3(num18, num19))
{
                                            flag32 = true;
                                        }
                                        num19++;
                                    }
                                    num18++;
                                }
                                if (flag32)
{
                                    this.buffTime[j] = 6;
                                }
                                else
{
                                    this.DelBuff(j);
                                }
                            }
                        }
                    }
                    else if (this.buffType[j] == 163)
                    {
                        this.headcovered = true;
                        this.bleed = true;
                    }
                    else if (this.buffType[j] == 164)
                    {
                        this.vortexDebuff = true;
                    }
                    else if (this.buffType[j] == 194)
                    {
                        this.windPushed = true;
                    }
                    else if (this.buffType[j] == 195)
                    {
                        this.witheredArmor = true;
                    }
                    else if (this.buffType[j] == 205)
                    {
                        this.ballistaPanic = true;
                    }
                    else if (this.buffType[j] == 196)
                    {
                        this.witheredWeapon = true;
                    }
                    else if (this.buffType[j] == 197)
                    {
                        this.slowOgreSpit = true;
                    }
                    else if (this.buffType[j] == 198)
                    {
                        this.parryDamageBuff = true;
                    }
                    else if (this.buffType[j] == 145)
                    {
                        this.moonLeech = true;
                    }
                    else if (this.buffType[j] == 149)
                    {
                        this.webbed = true;
                        if (this.velocity.Y != 0f)
{
                            this.velocity = new Vector2(0f, 1E-06f);
                        }
                        else
{
                            this.velocity = Vector2.Zero;
                        }
                        Player.jumpHeight = 0;
                        this.gravity = 0f;
                        this.moveSpeed = 0f;
                        this.dash = 0;
                        this.dashType = 0;
                        this.noKnockback = true;
                        this.RemoveAllGrapplingHooks();
                    }
                    else if (this.buffType[j] == 43)
                    {
                        this.defendedByPaladin = true;
                    }
                    else if (this.buffType[j] == 29)
                    {
                        this.magicCrit += 2;
                        this.magicDamage += 0.05f;
                        this.statManaMax2 += 20;
                        this.manaCost -= 0.02f;
                    }
                    else if (this.buffType[j] == 28)
                    {
                        if (!Main.dayTime && this.wolfAcc && !this.merman)
{
                            this.lifeRegen++;
                            this.wereWolf = true;
                            this.meleeCrit += 2;
                            this.meleeDamage += 0.051f;
                            this.meleeSpeed += 0.051f;
                            this.statDefense += 3;
                            this.moveSpeed += 0.05f;
                        }
                        else
{
                            this.DelBuff(j);
                            j--;
                        }
                    }
                    else if (this.buffType[j] == 33)
                    {
                        this.meleeDamage -= 0.051f;
                        this.meleeSpeed -= 0.051f;
                        this.statDefense -= 4;
                        this.moveSpeed -= 0.1f;
                    }
                    else if (this.buffType[j] == 25)
                    {
                        this.tipsy = true;
                        this.statDefense -= 4;
                        this.meleeCrit += 2;
                        this.meleeDamage += 0.1f;
                        this.meleeSpeed += 0.1f;
                    }
                    else if (this.buffType[j] == 26)
                    {
                        this.wellFed = true;
                        this.statDefense += 2;
                        this.meleeCrit += 2;
                        this.meleeDamage += 0.05f;
                        this.meleeSpeed += 0.05f;
                        this.magicCrit += 2;
                        this.magicDamage += 0.05f;
                        this.rangedCrit += 2;
                        this.rangedDamage += 0.05f;
                        this.minionDamage += 0.05f;
                        this.minionKB += 0.5f;
                        this.moveSpeed += 0.2f;
                        this.pickSpeed -= 0.05f;
                    }
                    else if (this.buffType[j] == 206)
                    {
                        this.wellFed = true;
                        this.statDefense += 3;
                        this.meleeCrit += 3;
                        this.meleeDamage += 0.075f;
                        this.meleeSpeed += 0.075f;
                        this.magicCrit += 3;
                        this.magicDamage += 0.075f;
                        this.rangedCrit += 3;
                        this.rangedDamage += 0.075f;
                        this.minionDamage += 0.075f;
                        this.minionKB += 0.75f;
                        this.moveSpeed += 0.3f;
                        this.pickSpeed -= 0.1f;
                    }
                    else if (this.buffType[j] == 207)
                    {
                        this.wellFed = true;
                        this.statDefense += 4;
                        this.meleeCrit += 4;
                        this.meleeDamage += 0.1f;
                        this.meleeSpeed += 0.1f;
                        this.magicCrit += 4;
                        this.magicDamage += 0.1f;
                        this.rangedCrit += 4;
                        this.rangedDamage += 0.1f;
                        this.minionDamage += 0.1f;
                        this.minionKB += 1f;
                        this.moveSpeed += 0.4f;
                        this.pickSpeed -= 0.15f;
                    }
                    else if (this.buffType[j] == 333)
                    {
                        this.hungry = true;
                        this.statDefense -= 2;
                        this.meleeCrit -= 2;
                        this.meleeDamage -= 0.05f;
                        this.meleeSpeed -= 0.05f;
                        this.magicCrit -= 2;
                        this.magicDamage -= 0.05f;
                        this.rangedCrit -= 2;
                        this.rangedDamage -= 0.05f;
                        this.minionDamage -= 0.05f;
                        this.minionKB -= 0.5f;
                        this.pickSpeed += 0.05f;
                    }
                    else if (this.buffType[j] == 334)
                    {
                        this.starving = true;
                        this.statDefense -= 4;
                        this.meleeCrit -= 4;
                        this.meleeDamage -= 0.1f;
                        this.meleeSpeed -= 0.1f;
                        this.magicCrit -= 4;
                        this.magicDamage -= 0.1f;
                        this.rangedCrit -= 4;
                        this.rangedDamage -= 0.1f;
                        this.minionDamage -= 0.1f;
                        this.minionKB -= 1f;
                        this.pickSpeed += 0.15f;
                    }
                    else if (this.buffType[j] == 336)
                    {
                        this.heartyMeal = true;
                    }
                    else if (this.buffType[j] == 71)
                    {
                        this.meleeEnchant = 1;
                    }
                    else if (this.buffType[j] == 73)
                    {
                        this.meleeEnchant = 2;
                    }
                    else if (this.buffType[j] == 74)
                    {
                        this.meleeEnchant = 3;
                    }
                    else if (this.buffType[j] == 75)
                    {
                        this.meleeEnchant = 4;
                    }
                    else if (this.buffType[j] == 76)
                    {
                        this.meleeEnchant = 5;
                    }
                    else if (this.buffType[j] == 77)
                    {
                        this.meleeEnchant = 6;
                    }
                    else if (this.buffType[j] == 78)
                    {
                        this.meleeEnchant = 7;
                    }
                    else if (this.buffType[j] == 79)
                    {
                        this.meleeEnchant = 8;
                    }
                }
            }
            this.UpdateHungerBuffs();
            if (this.whoAmI == Main.myPlayer && this.luckPotion != this.oldLuckPotion)
            {
                this.luckNeedsSync = true;
                this.oldLuckPotion = this.luckPotion;
            }
            if (this.lavaVision && this.lavaWet && this.lavaOpacity > 0.4f)
            {
                this.lavaOpacity -= 0.04f;
                if (this.lavaOpacity < 0.4f)
                {
                    this.lavaOpacity = 0.4f;
                    return;
                }
            }
            else if (this.lavaOpacity < 1f)
            {
                this.lavaOpacity += 0.04f;
                if (this.lavaOpacity > 1f)
                {
                    this.lavaOpacity = 1f;
                }
            }
        }
References Terraria.NPC.active, Terraria.Player.active, Terraria.Projectile.active, Terraria.Player.AddBuff(), Terraria.NPC.AddBuff(), Terraria.Lighting.AddLight(), Terraria.NPC.buffImmune, Terraria.Player.buffImmune, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Entity.Center, Terraria.Utils.Clamp(), Terraria.NPC.damage, Terraria.Main.dayTime, Terraria.Player.dead, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dontStarveWorld, Terraria.NPC.dontTakeDamage, System.E, Terraria.NPC.FindBuffIndex(), Terraria.Player.FindBuffIndex(), Terraria.NPC.friendly, Terraria.ID.ImmunityCooldownID.General, Terraria.Player.hostile, Terraria.Player.Hurt(), int, System.item, Terraria.Projectile.Kill(), Terraria.Player.manaSickTime, Terraria.Player.maxBuffs, Terraria.Main.maxNPCs, Terraria.ID.BuffID.Sets.MountType, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Projectile.originalDamage, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Main.projectile, Terraria.Main.rand, Terraria.NetMessage.SendPlayerHurt(), Terraria.WorldGen.SolidTile3(), Terraria.Player.team, Terraria.ID.BuffID.Sets.TimeLeftDoesNotDecrease, Terraria.NPC.type, Terraria.Projectile.type, Terraria.Main.UnderworldLayer, Terraria.Main.wofNPCIndex, and Microsoft.Xna.Framework.Vector2.Zero.