Terraria Decompiled: Terraria.Player.ItemCheck_TryStartUse
ItemCheck_TryStartUse()
bool Terraria.Player.ItemCheck_TryStartUse (Item sItem, bool ignoreCursed = false) inline private
Definition at line 51312 of file Player.cs.
        {
            bool flag = this.ItemCheck_CheckCanUse_Inner(sItem, ignoreCursed);
            if (flag)
            {
                if (!this.ItemCheck_ActuallyPayMana(sItem))
                {
                    flag = false;
                }
                if (!this.ItemCheck_CheckCanUse_KillDirtBlock(sItem))
                {
                    flag = false;
                }
                if (!this.ItemCheck_PullFishingBobbers(sItem))
                {
                    flag = false;
                }
            }
            return flag;
        }
Referenced by Terraria.Player.QuickBuff(), Terraria.Player.QuickBuff_ShouldUseItem(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickHeal(), and Terraria.Player.QuickMana().