Terraria Decompiled: Terraria.Player.UpdateTouchingTiles
UpdateTouchingTiles()
void Terraria.Player.UpdateTouchingTiles () inline
Definition at line 56485 of file Player.cs.
        {
            this.TouchedTiles.Clear();
            List<Point> list = null;
            List<Point> list2 = null;
            if (!Collision.IsClearSpotTest(this.position + this.velocity, 16f, this.width, this.height, false, false, (int)this.gravDir, true, true))
            {
                list = Collision.FindCollisionTile((Math.Sign(this.velocity.Y) == 1) ? 2 : 3, this.position + this.velocity, 16f, this.width, this.height, false, false, (int)this.gravDir, true, false);
            }
            if (!Collision.IsClearSpotTest(this.position, Math.Abs(this.velocity.Y), this.width, this.height, false, false, (int)this.gravDir, true, true))
            {
                list2 = Collision.FindCollisionTile((Math.Sign(this.velocity.Y) == 1) ? 2 : 3, this.position, Math.Abs(this.velocity.Y), this.width, this.height, false, false, (int)this.gravDir, true, true);
            }
            if (list != null && list2 != null)
            {
                for (int i = 0; i < list2.Count; i++)
                {
                    if (!list.Contains(list2[i]))
                    {
                        list.Add(list2[i]);
                    }
                }
            }
            if (list == null && list2 != null)
            {
                list = list2;
            }
            if (list != null)
            {
                this.TouchedTiles = list;
            }
        }
References System.Math.Abs(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Count, Terraria.Collision.FindCollisionTile(), int, Terraria.Collision.IsClearSpotTest(), System.list, and System.Math.Sign().