Terraria Decompiled: Terraria.Player.UpdateBlacklistedTilesForGrappling
UpdateBlacklistedTilesForGrappling()
void Terraria.Player.UpdateBlacklistedTilesForGrappling () inline
Definition at line 3446 of file Player.cs.
        {
            this.ClearGrapplingBlacklist();
            for (int i = 0; i < 1000; i++)
            {
                if (Main.projectile[i].active && Main.projectile[i].owner == this.whoAmI && Main.projectile[i].aiStyle == 7 && Main.projectile[i].ai[0] == 2f)
                {
                    Point point = Main.projectile[i].Center.ToTileCoordinates();
                    for (int j = -1; j <= 1; j++)
                    {
                        for (int k = -1; k <= 1; k++)
{
                            if (!WorldGen.SolidTile(point.X + j, point.Y + k, false))
{
                                this._blackListedTileCoordsForGrappling.Add(new Point(point.X + j, point.Y + k));
                            }
                        }
                    }
                    Tile tileSafely = Framing.GetTileSafely(point);
                    if (tileSafely.type == 314 || TileID.Sets.Platforms[(int)tileSafely.type])
                    {
                        for (int l = -2; l <= 2; l++)
{
                            for (int m = -2; m <= 2; m++)
{
                                Point point2 = new Point(point.X + l, point.Y + m);
                                Tile tileSafely2 = Framing.GetTileSafely(point2);
                                if (tileSafely2.type == 314 || TileID.Sets.Platforms[(int)tileSafely2.type])
{
                                    this._blackListedTileCoordsForGrappling.Add(point2);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Player._blackListedTileCoordsForGrappling, Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.Entity.Center, Terraria.Player.ClearGrapplingBlacklist(), Terraria.Framing.GetTileSafely(), Terraria.Projectile.owner, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.projectile, Terraria.WorldGen.SolidTile(), Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Projectile.AI_007_GrapplingHooks(), and Terraria.Player.QuickGrapple().