Terraria Decompiled: Terraria.Player.TrySwitchingLoadout
TrySwitchingLoadout()
void Terraria.Player.TrySwitchingLoadout (int loadoutIndex) inline
Definition at line 2940 of file Player.cs.
        {
            if (this.whoAmI == Main.myPlayer && (this.UsingOrReusingItem || this.CCed || this.dead))
            {
                return;
            }
            if (loadoutIndex == this.CurrentLoadoutIndex)
            {
                return;
            }
            if (loadoutIndex < 0 || loadoutIndex >= this.Loadouts.Length)
            {
                return;
            }
            this.Loadouts[this.CurrentLoadoutIndex].Swap(this);
            this.Loadouts[loadoutIndex].Swap(this);
            this.CurrentLoadoutIndex = loadoutIndex;
            if (this.whoAmI == Main.myPlayer)
            {
                this.clientCloneLoadouts(Main.clientPlayer);
                Main.mouseLeftRelease = false;
                ItemSlot.RecordLoadoutChange();
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                NetMessage.TrySendData(147, -1, -1, null, this.whoAmI, (float)loadoutIndex, 0f, 0f, 0, 0, 0);
                ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.LoadoutChange, new ParticleOrchestraSettings
                {
                    PositionInWorld = base.Center,
                    UniqueInfoPiece = loadoutIndex
                }, new int?(this.whoAmI));
            }
        }
References Terraria.Player.clientCloneLoadouts(), Terraria.Main.clientPlayer, Terraria.Player.CurrentLoadoutIndex, Terraria.Player.Loadouts, Terraria.Main.myPlayer, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.ItemSlot.RecordLoadoutChange(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.EquipmentLoadout.Swap(), Terraria.NetMessage.TrySendData(), and Terraria.Entity.whoAmI.
Referenced by Terraria.GameInput.TriggersSet.CopyInto(), Terraria.Main.DrawLoadoutButtons(), Terraria.Player.TrySwitchingToNextLoadout(), and Terraria.Player.TrySwitchingToPreviousLoadout().