Terraria Decompiled: Terraria.Player.DropTombstone
DropTombstone()
void Terraria.Player.DropTombstone (long coinsOwned, NetworkText deathText, int hitDirection) inline
Definition at line 37938 of file Player.cs.
        {
            if (Main.netMode != 1)
            {
                float num = (float)Main.rand.Next(-35, 36) * 0.1f;
                while (num < 2f && num > -2f)
                {
                    num += (float)Main.rand.Next(-30, 31) * 0.1f;
                }
                int num2 = Main.rand.Next(6);
                if (coinsOwned > 100000L)
                {
                    num2 = Main.rand.Next(5);
                    num2 += 527;
                }
                else if (num2 == 0)
                {
                    num2 = 43;
                }
                else
                {
                    num2 = 200 + num2;
                }
                IEntitySource projectileSource_Misc = this.GetProjectileSource_Misc(9);
                int num3 = 0;
                int num4 = 0;
                if (Main.getGoodWorld)
                {
                    num3 = 70;
                    num4 = 10;
                }
                int whoAmI = this.whoAmI;
                int num5;
                if (Main.getGoodWorld)
                {
                    num5 = Projectile.NewProjectile(projectileSource_Misc, this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), ((float)Main.rand.Next(10, 30) * 0.1f * (float)hitDirection + num) * 1.5f, (float)Main.rand.Next(-40, -20) * 0.1f * 1.5f, num2, num3, (float)num4, Main.myPlayer, (float)whoAmI, 0f, 0f, null);
                }
                else
                {
                    num5 = Projectile.NewProjectile(projectileSource_Misc, this.position.X + (float)(this.width / 2), this.position.Y + (float)(this.height / 2), (float)Main.rand.Next(10, 30) * 0.1f * (float)hitDirection + num, (float)Main.rand.Next(-40, -20) * 0.1f, num2, num3, (float)num4, Main.myPlayer, (float)whoAmI, 0f, 0f, null);
                }
                DateTime now = DateTime.Now;
                string text = now.ToString("D");
                if (GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive)
                {
                    text = now.ToString("MMMM d, yyy");
                }
                string text2 = deathText.ToString() + "\n" + text;
                Main.projectile[num5].miscText = text2;
            }
        }
References Terraria.Localization.GameCulture.FromCultureName(), Terraria.Main.getGoodWorld, Terraria.Localization.GameCulture.IsActive, System.L, Terraria.Projectile.miscText, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), System.DateTime.Now, Terraria.Main.projectile, Terraria.Main.rand, System.text, System.DateTime.ToString(), and Terraria.Localization.NetworkText.ToString().