Terraria Decompiled: Terraria.Player.GetImmuneAlpha
GetImmuneAlpha()
Color Terraria.Player.GetImmuneAlpha (Color newColor, float alphaReduction) inline
Definition at line 53485 of file Player.cs.
        {
            float num = (float)(255 - this.immuneAlpha) / 255f;
            if (alphaReduction > 0f)
            {
                num *= 1f - alphaReduction;
            }
            if (this.shimmerTransparency > 0f)
            {
                if ((double)this.shimmerTransparency >= 0.8)
                {
                    return Color.Transparent;
                }
                num *= 1f - this.shimmerTransparency;
                num *= 1f - this.shimmerTransparency;
                num *= 1f - this.shimmerTransparency;
            }
            if (this.immuneAlpha > 125)
            {
                return Color.Transparent;
            }
            return Color.Multiply(newColor, num);
        }
References Microsoft.Xna.Framework.Color.Multiply(), and Microsoft.Xna.Framework.Color.Transparent.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup(), and Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawGhost().