Terraria Decompiled: Terraria.Player.ChestChangeEvents
ChestChangeEvents()
void Terraria.Player.ChestChangeEvents () inline
Definition at line 27161 of file Player.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            if (this.chest == -1 && this.lastChest >= 0 && Main.chest[this.lastChest] != null)
            {
                int x = Main.chest[this.lastChest].x;
                int y = Main.chest[this.lastChest].y;
                NPC.BigMimicSummonCheck(x, y, this);
            }
            if (this.lastChest != this.chest && this.chest >= 0 && Main.chest[this.chest] != null)
            {
                int x2 = Main.chest[this.chest].x;
                int y2 = Main.chest[this.chest].y;
                Projectile.GasTrapCheck(x2, y2, this);
                ItemSlot.forceClearGlowsOnChest = true;
            }
            this.lastChest = this.chest;
        }
References Terraria.NPC.BigMimicSummonCheck(), Terraria.Main.chest, Terraria.Projectile.GasTrapCheck(), Terraria.Main.netMode, Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.Main.DoUpdate_WhilePaused().