Terraria Decompiled: Terraria.Player.InternalSaveMap
InternalSaveMap()
static void Terraria.Player.InternalSaveMap (bool isCloudSave) inline static
Definition at line 54369 of file Player.cs.
        {
            if (!string.IsNullOrEmpty(Main.playerPathName))
            {
                try
                {
                    if (Main.mapEnabled)
                    {
                        Main.Map.Save();
                    }
                }
                catch
                {
                }
                if (!isCloudSave)
                {
                    Utils.TryCreatingDirectory(Main.PlayerPath);
                }
            }
        }
References Terraria.Main.Map, Terraria.Main.mapEnabled, Terraria.Main.PlayerPath, Terraria.Main.playerPathName, Terraria.Map.WorldMap.Save(), and Terraria.Utils.TryCreatingDirectory().
Referenced by Terraria.Player.SavePlayer().