Terraria Decompiled: Terraria.Player.QuickSpawnItem
QuickSpawnItem() [1/3]
void Terraria.Player.QuickSpawnItem (IEntitySource source, int item, int stack = 1) inline
Definition at line 4416 of file Player.cs.
        {
            if (stack <= 0)
            {
                return;
            }
            Item item2 = new Item();
            item2.SetDefaults(item, null);
            item2.Prefix(-1);
            item2.stack = stack;
            this.QuickSpawnItem(source, item2);
        }
References System.item, Terraria.Item.Prefix(), Terraria.Player.QuickSpawnItem(), Terraria.Item.SetDefaults(), and System.stack.
Referenced by Terraria.Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Terraria.Lang.BartenderHelpText(), Terraria.GameContent.ConditionalDialogue.FreeCakeDialogue.GetChatAndClearCondition(), Terraria.GameContent.BannerSystem.HandleBannerClaimResponse(), Terraria.Player.OpenBossBag(), Terraria.Player.OpenFishingCrate(), Terraria.Player.OpenLegacyPresent(), Terraria.Player.OpenPresent(), Terraria.Player.QuickSpawnItem(), Terraria.Player.QuickSpawnItem(), Terraria.UI.ItemSorting.SortCoins(), and Terraria.Player.TryGettingDevArmor().