Terraria Decompiled: Terraria.Player.FixLoadedData_EliminiateDuplicateAccessories
FixLoadedData_EliminiateDuplicateAccessories()
static void Terraria.Player.FixLoadedData_EliminiateDuplicateAccessories (Item[] armorArray) inline static
Definition at line 55146 of file Player.cs.
        {
            for (int i = 3; i < 10; i++)
            {
                Item item = armorArray[i];
                if (!item.IsAir)
                {
                    for (int j = i + 1; j < 10; j++)
                    {
                        Item item2 = armorArray[j];
                        if (item2.type == item.type)
{
                            item2.TurnToAir(false);
                        }
                    }
                }
            }
        }
References System.item, Terraria.Item.TurnToAir(), and Terraria.Item.type.
Referenced by Terraria.EquipmentLoadout.FixLoadedData(), and Terraria.Player.FixLoadedData().