Terraria Decompiled: Terraria.Player.GetAutoDoorVelocityContribution
GetAutoDoorVelocityContribution()
float Terraria.Player.GetAutoDoorVelocityContribution () inline
Definition at line 22841 of file Player.cs.
        {
            float num = this.velocity.X;
            if (this.mount.Active && this.mount.Type >= 0 && MountID.Sets.IsRollerSkates[this.mount.Type] && Math.Abs(num) < 3f)
            {
                num = 3f * (float)Math.Sign(num);
            }
            return num;
        }
References System.Math.Abs(), Terraria.ID.MountID.Sets.IsRollerSkates, and System.Math.Sign().
Referenced by Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor().