Terraria Decompiled: Terraria.Player.PlaceThing_Tiles_CheckRopeUsability
PlaceThing_Tiles_CheckRopeUsability()
bool Terraria.Player.PlaceThing_Tiles_CheckRopeUsability (bool canUse) inline private
Definition at line 40498 of file Player.cs.
        {
            int num = 5;
            if (Main.tileRope[this.inventory[this.selectedItem].createTile] && canUse && Main.tile[Player.tileTargetX, Player.tileTargetY].active() && Main.tileRope[(int)Main.tile[Player.tileTargetX, Player.tileTargetY].type])
            {
                int num2 = 0;
                int num3 = Player.tileTargetY;
                int num4 = Player.tileTargetX;
                bool flag = this.inventory[this.selectedItem].createTile == 214;
                while (Main.tile[num4, num3].active() && (Main.tileRope[(int)Main.tile[num4, num3].type] || Main.tile[num4, num3].type == 314 || TileID.Sets.Platforms[(int)Main.tile[num4, num3].type] || Main.tile[num4, num3].type == 380) && num3 < Main.maxTilesY - 5 && (flag || !Main.tile[num4, num3 + 1].lava()))
                {
                    if (Main.tile[num4, num3].type == 314 || TileID.Sets.Platforms[(int)Main.tile[num4, num3].type] || Main.tile[num4, num3].type == 380)
                    {
                        num2++;
                        if (num2 > num)
{
                            break;
                        }
                    }
                    else
                    {
                        num2 = 0;
                    }
                    num3++;
                    if (Main.tile[num4, num3 + 1] == null)
                    {
                        if (this.controlUseItem)
{
                            NetMessage.SendData(159, -1, -1, null, num4 / 200, (float)((num3 + 1) / 150), 0f, 0f, 0, 0, 0);
                        }
                        return false;
                    }
                }
                Tile tile = Main.tile[num4, num3];
                if (!tile.active() || (tile.type >= 0 && tile.type < TileID.Count && (Main.tileCut[(int)tile.type] || TileID.Sets.BreakableWhenPlacing[(int)tile.type])))
                {
                    Player.tileTargetY = num3;
                }
            }
            return canUse;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.ID.TileID.Count, Terraria.Tile.lava(), Terraria.Main.maxTilesY, Terraria.ID.TileID.Sets.Platforms, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileRope, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, and Terraria.Tile.type.