Terraria Decompiled: Terraria.Player.DoubleJumpVisuals
DoubleJumpVisuals()
void Terraria.Player.DoubleJumpVisuals () inline
Definition at line 20295 of file Player.cs.
        {
            if (this.isPerformingJump_Cloud && this.hasJumpOption_Cloud && !this.canJumpAgain_Cloud && (this.canJumpAgain_Sandstorm || !this.hasJumpOption_Sandstorm) && ((this.gravDir == 1f && this.velocity.Y < 0f) || (this.gravDir == -1f && this.velocity.Y > 0f)))
            {
                int num = this.height;
                if (this.gravDir == -1f)
                {
                    num = -6;
                }
                int num2 = Dust.NewDust(new Vector2(this.position.X - 4f, this.position.Y + (float)num), this.width + 8, 4, 16, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 100, default(Color), 1.5f);
                Main.dust[num2].velocity.X = Main.dust[num2].velocity.X * 0.5f - this.velocity.X * 0.1f;
                Main.dust[num2].velocity.Y = Main.dust[num2].velocity.Y * 0.5f - this.velocity.Y * 0.3f;
            }
            if (this.isPerformingJump_Sandstorm && this.hasJumpOption_Sandstorm && !this.canJumpAgain_Sandstorm && ((this.gravDir == 1f && this.velocity.Y < 0f) || (this.gravDir == -1f && this.velocity.Y > 0f)))
            {
                int num3 = this.height;
                if (this.gravDir == -1f)
                {
                    num3 = -6;
                }
                float num4 = ((float)this.jump / 75f + 1f) / 2f;
                for (int i = 0; i < 3; i++)
                {
                    int num5 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)(num3 / 2)), this.width, 32, 124, this.velocity.X * 0.3f, this.velocity.Y * 0.3f, 150, default(Color), 1f * num4);
                    Main.dust[num5].velocity *= 0.5f * num4;
                    Main.dust[num5].fadeIn = 1.5f * num4;
                }
                this.sandStorm = true;
                if (this.miscCounter % 3 == 0)
                {
                    int num6 = Gore.NewGore(new Vector2(this.position.X + (float)(this.width / 2) - 18f, this.position.Y + (float)(num3 / 2)), new Vector2(-this.velocity.X, -this.velocity.Y), Main.rand.Next(220, 223), num4);
                    Main.gore[num6].velocity = this.velocity * 0.3f * num4;
                    Main.gore[num6].alpha = 100;
                }
            }
            if (this.isPerformingJump_Fart && this.hasJumpOption_Fart && !this.canJumpAgain_Fart && ((this.gravDir == 1f && this.velocity.Y < 0f) || (this.gravDir == -1f && this.velocity.Y > 0f)))
            {
                int num7 = this.height;
                if (this.gravDir == -1f)
                {
                    num7 = -6;
                }
                int num8 = Dust.NewDust(new Vector2(this.position.X - 4f, this.position.Y + (float)num7), this.width + 8, 4, 188, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 100, default(Color), 1.5f);
                Main.dust[num8].velocity.X = Main.dust[num8].velocity.X * 0.5f - this.velocity.X * 0.1f;
                Main.dust[num8].velocity.Y = Main.dust[num8].velocity.Y * 0.5f - this.velocity.Y * 0.3f;
                Main.dust[num8].velocity *= 0.5f;
            }
            if (this.isPerformingJump_Unicorn && this.hasJumpOption_Unicorn && !this.canJumpAgain_Unicorn && ((this.gravDir == 1f && this.velocity.Y < 0f) || (this.gravDir == -1f && this.velocity.Y > 0f)))
            {
                Dust dust = Main.dust[Dust.NewDust(this.position, this.width, this.height, Utils.SelectRandom<int>(Main.rand, new int[] { 176, 177, 179 }), 0f, 0f, 0, default(Color), 1f)];
                dust.velocity = Vector2.Zero;
                dust.noGravity = true;
                dust.scale = 0.5f + Main.rand.NextFloat() * 0.8f;
                dust.fadeIn = 1f + Main.rand.NextFloat() * 2f;
                dust.shader = GameShaders.Armor.GetSecondaryShader(this.cMount, this);
            }
            if (this.isPerformingJump_Sail && this.hasJumpOption_Sail && !this.canJumpAgain_Sail && ((this.gravDir == 1f && this.velocity.Y < 1f) || (this.gravDir == -1f && this.velocity.Y > 1f)))
            {
                int num9 = 1;
                if (this.jump > 0)
                {
                    num9 = 2;
                }
                int num10 = this.height - 6;
                if (this.gravDir == -1f)
                {
                    num10 = 6;
                }
                for (int j = 0; j < num9; j++)
                {
                    int num11 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)num10), this.width, 12, 253, this.velocity.X * 0.3f, this.velocity.Y * 0.3f, 100, default(Color), 1.5f);
                    Main.dust[num11].scale += (float)Main.rand.Next(-5, 3) * 0.1f;
                    if (this.jump <= 0)
                    {
                        Main.dust[num11].scale *= 0.8f;
                    }
                    else
                    {
                        Main.dust[num11].velocity -= this.velocity / 5f;
                    }
                    Main.dust[num11].noGravity = true;
                    Vector2 vector = new Vector2((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                    vector.Normalize();
                    vector *= (float)Main.rand.Next(81) * 0.1f;
                }
            }
            if (this.isPerformingJump_Blizzard && this.hasJumpOption_Blizzard && !this.canJumpAgain_Blizzard && ((this.gravDir == 1f && this.velocity.Y < 0f) || (this.gravDir == -1f && this.velocity.Y > 0f)))
            {
                int num12 = this.height - 6;
                if (this.gravDir == -1f)
                {
                    num12 = 6;
                }
                for (int k = 0; k < 2; k++)
                {
                    int num13 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)num12), this.width, 12, 76, this.velocity.X * 0.3f, this.velocity.Y * 0.3f, 0, default(Color), 1f);
                    Main.dust[num13].velocity *= 0.1f;
                    if (k == 0)
                    {
                        Main.dust[num13].velocity += this.velocity * 0.03f;
                    }
                    else
                    {
                        Main.dust[num13].velocity -= this.velocity * 0.03f;
                    }
                    Main.dust[num13].velocity -= this.velocity * 0.1f;
                    Main.dust[num13].noGravity = true;
                    Main.dust[num13].noLight = true;
                }
                for (int l = 0; l < 3; l++)
                {
                    int num14 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)num12), this.width, 12, 76, this.velocity.X * 0.3f, this.velocity.Y * 0.3f, 0, default(Color), 1f);
                    Main.dust[num14].fadeIn = 1.5f;
                    Main.dust[num14].velocity *= 0.6f;
                    Main.dust[num14].velocity += this.velocity * 0.8f;
                    Main.dust[num14].noGravity = true;
                    Main.dust[num14].noLight = true;
                }
                for (int m = 0; m < 3; m++)
                {
                    int num15 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)num12), this.width, 12, 76, this.velocity.X * 0.3f, this.velocity.Y * 0.3f, 0, default(Color), 1f);
                    Main.dust[num15].fadeIn = 1.5f;
                    Main.dust[num15].velocity *= 0.6f;
                    Main.dust[num15].velocity -= this.velocity * 0.8f;
                    Main.dust[num15].noGravity = true;
                    Main.dust[num15].noLight = true;
                }
            }
        }
References Terraria.Gore.alpha, Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Main.gore, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.rand, Terraria.Dust.scale, Terraria.Dust.velocity, Terraria.Gore.velocity, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.