Terraria Decompiled: Terraria.Player.VampireSeedSunlightExposure
VampireSeedSunlightExposure()
void Terraria.Player.VampireSeedSunlightExposure () inline private
Definition at line 27060 of file Player.cs.
        {
            int num = (int)base.Center.X / 16;
            int num2 = (int)(base.Bottom.Y - 1f) / 16;
            if (!Main.vampireSeed)
            {
                return;
            }
            float num3 = 0.5f;
            bool flag = (double)num2 < Main.worldSurface && Main.dayTime && !Main.raining && !Main.eclipse && !this.ZoneGraveyard && !this.ZoneGlowshroom;
            if (flag && Player.SceneMetrics.MoonLordSkyIntensity != null && Player.SceneMetrics.MoonLordSkyIntensity.Value > num3)
            {
                flag = false;
            }
            if (!flag)
            {
                return;
            }
            if (this.wet)
            {
                return;
            }
            bool flag2 = this.inventory[this.selectedItem].type == 946 || this.inventory[this.selectedItem].type == 4707;
            if (this.mount.Active && this.mount.Type == 56)
            {
                flag2 = false;
            }
            if (flag2)
            {
                return;
            }
            int i = 15;
            while (i > 0)
            {
                Tile tile = Main.tile[num, num2];
                if (tile == null)
                {
                    return;
                }
                if (tile.wall == 0 || tile.wall == 21 || tile.wall == 318 || (!Main.ShouldShowInvisibleBlocksAndWalls() && tile.invisibleWall()))
                {
                    this.vampireBurningInSunlight = true;
                    return;
                }
                i--;
                num2--;
                if (WorldGen.SolidTile3(num, num2) && tile.type != 54 && (!tile.invisibleBlock() || Main.ShouldShowInvisibleBlocksAndWalls()) && (tile.type != 541 || Main.ShouldShowInvisibleBlocksAndWalls()))
                {
                    return;
                }
            }
        }
References Terraria.Main.dayTime, Terraria.Main.eclipse, int, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.SceneMetrics.MoonLordSkyIntensity, Terraria.Main.raining, Terraria.Player.SceneMetrics, Terraria.Main.ShouldShowInvisibleBlocksAndWalls(), Terraria.WorldGen.SolidTile3(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.vampireSeed, Terraria.Tile.wall, and Terraria.Main.worldSurface.