Terraria Decompiled: Terraria.Player.CheckDrowning
CheckDrowning()
void Terraria.Player.CheckDrowning () inline
Definition at line 21625 of file Player.cs.
        {
            bool flag = Collision.DrownCollision(this.position, this.width, this.height, this.gravDir, false);
            if (this.armor[0].type == 250 || this.armor[0].type == 4275)
            {
                flag = true;
            }
            if (this.hasBreathingReed && this.itemAnimation == 0)
            {
                try
                {
                    int num = (int)((this.position.X + (float)(this.width / 2) + (float)(6 * this.direction)) / 16f);
                    int num2 = 0;
                    if (this.gravDir == -1f)
                    {
                        num2 = this.height;
                    }
                    int num3 = (int)((this.position.Y + (float)num2 - 44f * this.gravDir) / 16f);
                    if (Main.tile[num, num3] != null && Main.tile[num, num3].liquid < 128)
                    {
                        if (Main.tile[num, num3] == null)
{
                            Main.tile[num, num3] = new Tile();
                        }
                        if (!Main.tile[num, num3].active() || !Main.tileSolid[(int)Main.tile[num, num3].type] || Main.tileSolidTop[(int)Main.tile[num, num3].type])
{
                            flag = false;
                        }
                    }
                }
                catch
                {
                }
            }
            if (this.gills)
            {
                flag = Main.getGoodWorld && !flag;
            }
            if (this.shimmering)
            {
                flag = false;
            }
            if (this.mount.Active && this.mount.Type == 4)
            {
                flag = false;
            }
            if (Main.myPlayer == this.whoAmI)
            {
                if (this.accMerman)
                {
                    if (flag)
                    {
                        this.merman = true;
                    }
                    flag = false;
                }
                if (flag)
                {
                    this.breathCD++;
                    if (this.breathCD >= this.breathCDMax)
                    {
                        this.breathCD = 0;
                        this.breath--;
                        if (this.breath == 0)
{
                            SoundEngine.PlaySound(23, -1, -1, 1, 1f, 0f);
                        }
                        if (this.breath <= 0)
{
                            this.lifeRegenTime = 0f;
                            this.breath = 0;
                            this.statLife -= 2;
                            this.SetOrRequestSpectating(-1);
                            if (this.statLife <= 0)
{
                                this.statLife = 0;
                                this.KillMe(PlayerDeathReason.ByOther(1), 10.0, 0, false);
                            }
                        }
                    }
                }
                else
                {
                    this.breath += 3;
                    if (this.breath > this.breathMax)
                    {
                        this.breath = this.breathMax;
                    }
                    this.breathCD = 0;
                }
            }
            if (flag && Main.rand.Next(20) == 0 && !this.lavaWet && !this.honeyWet)
            {
                int num4 = 0;
                if (this.gravDir == -1f)
                {
                    num4 += this.height - 12;
                }
                Vector2 vector = new Vector2(this.position.X + (float)(12 * this.direction), this.position.Y + (float)num4 + 4f * this.gravDir);
                if (this.hasBreathingReed)
                {
                    vector += new Vector2((float)(-2 * this.direction), -58f * this.gravDir);
                }
                if (this.mount.Active && this.MouthPosition != null)
                {
                    if (this.mount.Type == 52)
                    {
                        vector = this.MouthPosition.Value + new Vector2(-6f, 0f);
                        if (this.hasBreathingReed)
{
                            vector += new Vector2(0f, -60f) * this.Directions;
                        }
                    }
                    if (this.mount.Type == 54)
                    {
                        vector = this.MouthPosition.Value + new Vector2(-6f, -2f);
                        if (this.hasBreathingReed)
{
                            vector += new Vector2(-14f, -58f) * this.Directions;
                        }
                    }
                }
                Dust.NewDust(vector, this.width - 8, 8, 34, 0f, 0f, 0, default(Color), 1.2f);
            }
        }
References Terraria.Tile.active(), Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Collision.DrownCollision(), int, Terraria.Tile.liquid, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.