Terraria Decompiled: Terraria.Player.PickupItem
PickupItem()
void Terraria.Player.PickupItem (WorldItem itemToPickUp) inline private
Definition at line 33805 of file Player.cs.
        {
            if (ItemID.Sets.NebulaPickup[itemToPickUp.type])
            {
                SoundEngine.PlaySound(7, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                int num = itemToPickUp.buffType;
                itemToPickUp.ClearOut();
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(102, -1, -1, null, this.whoAmI, (float)num, base.Center.X, base.Center.Y, 0, 0, 0);
                }
                else
                {
                    this.NebulaLevelup(num);
                }
            }
            else if (itemToPickUp.type == 58 || itemToPickUp.type == 1734 || itemToPickUp.type == 1867)
            {
                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                this.Heal(20);
                itemToPickUp.ClearOut();
            }
            else if (itemToPickUp.type == 184 || itemToPickUp.type == 1735 || itemToPickUp.type == 1868)
            {
                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                this.statMana += 100;
                if (Main.myPlayer == this.whoAmI)
                {
                    this.ManaEffect(100);
                }
                if (this.statMana > this.statManaMax2)
                {
                    this.statMana = this.statManaMax2;
                }
                itemToPickUp.ClearOut();
            }
            else if (itemToPickUp.type == 4143)
            {
                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                this.statMana += 50;
                if (Main.myPlayer == this.whoAmI)
                {
                    this.ManaEffect(50);
                }
                if (this.statMana > this.statManaMax2)
                {
                    this.statMana = this.statManaMax2;
                }
                itemToPickUp.ClearOut();
            }
            else
            {
                int stack = itemToPickUp.stack;
                Item item = this.GetItem(itemToPickUp, GetItemSettings.PickupItemFromWorld);
                itemToPickUp.OverrideWith(item);
                if (item.stack == stack)
                {
                    return;
                }
            }
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, itemToPickUp.whoAmI, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.WorldItem.buffType, Terraria.WorldItem.ClearOut(), System.item, Terraria.Main.myPlayer, Terraria.ID.ItemID.Sets.NebulaPickup, Terraria.Main.netMode, Terraria.WorldItem.OverrideWith(), Terraria.GetItemSettings.PickupItemFromWorld, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), System.stack, Terraria.WorldItem.stack, Terraria.WorldItem.type, and Terraria.Entity.whoAmI.