Terraria Decompiled: Terraria.Player.PlayHurtSound
PlayHurtSound()
void Terraria.Player.PlayHurtSound () inline
Definition at line 37433 of file Player.cs.
        {
            Vector2 position = this.position;
            if (this.whoAmI == Main.myPlayer)
            {
                position = new Vector2(-1f, -1f);
            }
            if (this.stoned)
            {
                SoundEngine.PlaySound(0, position, 1, 0f);
                return;
            }
            switch (this.voiceOverride)
            {
            case 1:
                SoundEngine.PlaySound(1, position, 1, 0f);
                return;
            case 2:
                SoundEngine.PlaySound(20, position, 1, 0f);
                return;
            case 3:
                SoundEngine.PlaySound(SoundID.DSTMaleHurt, position, 0f, 1f);
                return;
            case 4:
                SoundEngine.PlaySound(SoundID.DSTFemaleHurt, position, 0f, 1f);
                return;
            case 5:
                SoundEngine.PlaySound(SoundID.BellHurt, position, 0f, 1f);
                return;
            case 6:
                if (Main.rand.Next(5) == 0)
                {
                    SoundEngine.PlaySound(SoundID.ChickenHurtRare, position, 0f, 1f);
                    return;
                }
                SoundEngine.PlaySound(SoundID.ChickenHurt, position, 0f, 1f);
                return;
            case 7:
                SoundEngine.PlaySound(SoundID.FrogHurt, position, 0f, 1f);
                return;
            case 8:
                SoundEngine.PlaySound(SoundID.GoatHurt, position, 0f, 1f);
                return;
            case 9:
                SoundEngine.PlaySound(SoundID.RetroHurt, position, 0f, 1f);
                return;
            case 10:
                SoundEngine.PlaySound(SoundID.CatHurt, position, 0f, 1f);
                return;
            case 11:
                SoundEngine.PlaySound(SoundID.DogHurt, position, 0f, 1f);
                return;
            case 12:
                SoundEngine.PlaySound(SoundID.TurkeyHurt, position, 0f, 1f);
                return;
            case 13:
                SoundEngine.PlaySound(SoundID.GoblinHurt, position, 0f, 1f);
                return;
            case 14:
                SoundEngine.PlaySound(SoundID.CrowHurt, position, 0f, 1f);
                return;
            case 15:
                SoundEngine.PlaySound(SoundID.BalloonHurt, position, 0f, 1f);
                return;
            case 16:
                SoundEngine.PlaySound(SoundID.UndeadHurt, position, 0f, 1f);
                return;
            case 17:
                SoundEngine.PlaySound(SoundID.VampireHurt, position, 0f, 1f);
                return;
            case 18:
                SoundEngine.PlaySound(SoundID.FairyHurt, position, 0f, 1f);
                return;
            case 19:
                SoundEngine.PlaySound(SoundID.Item16, position, 0f, 1f);
                return;
            case 20:
                SoundEngine.PlaySound(SoundID.DefaultPlayerHurt, position, 0f, 1f);
                return;
            default:
            {
                if (this.mount.Active)
                {
                    if (this.mount.Type == 52)
                    {
                        SoundEngine.PlaySound(3, position, 6, 0f);
                        return;
                    }
                    if (this.mount.Type == 54)
                    {
                        SoundEngine.PlaySound(3, position, 47, 0f);
                        return;
                    }
                    if (this.mount.Type == 55)
                    {
                        SoundEngine.PlaySound(4, position, 4, 0f);
                        return;
                    }
                    if (this.mount.Type == 56)
                    {
                        SoundEngine.PlaySound(4, position, 4, 0f);
                        return;
                    }
                    if (this.mount.Type == 61)
                    {
                        SoundEngine.PlaySound(3, position, 5, 0f);
                        return;
                    }
                }
                if ((this.wereWolf || this.forceWerewolf) && !this.hideWolf)
                {
                    SoundEngine.PlaySound(3, position, 6, 0f);
                    return;
                }
                if (this.frostArmor)
                {
                    SoundEngine.PlaySound(SoundID.Item27, position, 0f, 1f);
                    return;
                }
                if (this.boneArmor)
                {
                    SoundEngine.PlaySound(3, position, 2, 0f);
                    return;
                }
                if (Main.dontStarveWorld && !Main.remixWorld)
                {
                    SoundEngine.PlaySound(this.Male ? SoundID.DSTMaleHurt : SoundID.DSTFemaleHurt, position, 0f, 1f);
                    return;
                }
                float num = 0.7f;
                float num2 = Utils.Remap(this.voicePitchOffset, -1f, 1f, -num, num, true);
                switch (this.voiceVariant)
                {
                case 1:
                    SoundEngine.PlaySound(1, position, 1, num2);
                    return;
                case 2:
                    SoundEngine.PlaySound(20, position, 1, num2);
                    return;
                case 3:
                    SoundEngine.PlaySound(SoundID.DefaultPlayerHurt, position, num2, 1f);
                    return;
                default:
                    return;
                }
                break;
            }
            }
        }
References Terraria.ID.SoundID.BalloonHurt, Terraria.ID.SoundID.BellHurt, Terraria.ID.SoundID.CatHurt, Terraria.ID.SoundID.ChickenHurt, Terraria.ID.SoundID.ChickenHurtRare, Terraria.ID.SoundID.CrowHurt, Terraria.ID.SoundID.DefaultPlayerHurt, Terraria.ID.SoundID.DogHurt, Terraria.Main.dontStarveWorld, Terraria.ID.SoundID.DSTFemaleHurt, Terraria.ID.SoundID.DSTMaleHurt, Terraria.ID.SoundID.FairyHurt, Terraria.ID.SoundID.FrogHurt, Terraria.ID.SoundID.GoatHurt, Terraria.ID.SoundID.GoblinHurt, Terraria.ID.SoundID.Item16, Terraria.ID.SoundID.Item27, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Main.remixWorld, Terraria.ID.SoundID.RetroHurt, Terraria.ID.SoundID.TurkeyHurt, Terraria.ID.SoundID.UndeadHurt, and Terraria.ID.SoundID.VampireHurt.
Referenced by Terraria.Main.DrawClothesWindow(), Terraria.GameContent.UI.States.UICharacterCreation.PlayVoicePreview(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PlayerVoiceOverrideSound().