Terraria Decompiled: Terraria.Player.RocketBootVisuals
RocketBootVisuals()
void Terraria.Player.RocketBootVisuals () inline private
Definition at line 27787 of file Player.cs.
        {
            if (this.vanityRocketBoots == 0)
            {
                return;
            }
            int num = this.height;
            if (this.gravDir == -1f)
            {
                num = 4;
            }
            int i = 0;
            while (i < 2)
            {
                int num2 = ((i == 0) ? 2 : (-2));
                Vector2 vector = this.position + this.netOffset;
                Rectangle rectangle;
                if (i == 0)
                {
                    rectangle = new Rectangle((int)vector.X - 4, (int)vector.Y + num - 10, 8, 8);
                }
                else
                {
                    rectangle = new Rectangle((int)vector.X + this.width - 4, (int)vector.Y + num - 10, 8, 8);
                }
                if (this.direction == -1)
                {
                    rectangle.X -= 4;
                }
                int num3 = 6;
                float num4 = 2.5f;
                int num5 = 100;
                float num6 = 1f;
                Vector2 vector2 = new Vector2((float)(-(float)num2) - this.velocity.X * 0.3f, 2f * this.gravDir - this.velocity.Y * 0.3f);
                Dust dust;
                switch (this.vanityRocketBoots)
                {
                case 1:
                    if (this.socialShadowRocketBoots)
                    {
                        num3 = 27;
                        num4 = 1.5f;
                        goto IL_031B;
                    }
                    goto IL_031B;
                case 2:
                    if (this.fairyBoots)
                    {
                        num3 = (int)Main.rand.NextFromList(new short[] { 61, 61, 61, 242, 64, 63 });
                        num4 = 2f;
                        num5 = 120;
                        goto IL_031B;
                    }
                    num3 = 16;
                    num4 = 1.5f;
                    num5 = 20;
                    goto IL_031B;
                case 3:
                    num3 = 76;
                    num4 = 1f;
                    num5 = 20;
                    goto IL_031B;
                case 4:
                {
                    int num7 = Main.rand.Next(6);
                    if (this.cShoe > 0)
                    {
                        num7 = 2;
                    }
                    rectangle.Y += 2 * (int)this.gravDir;
                    if (num7 != 0 && num7 != 1)
                    {
                        num3 = 107;
                        num5 = 100;
                        num4 = 0.7f;
                        num6 = 0.5f;
                        goto IL_031B;
                    }
                    dust = Dust.NewDustDirect(rectangle.TopLeft(), rectangle.Width, rectangle.Height, 278, 0f, 0f, 100, Color.Lerp(Color.LimeGreen, Color.White, Main.rand.NextFloat() * 0.3f), 1f);
                    dust.shader = GameShaders.Armor.GetSecondaryShader(this.cShoe, this);
                    dust.scale = 0.66f;
                    dust.noGravity = true;
                    dust.velocity *= 0.25f;
                    dust.velocity -= this.velocity * 0.5f;
                    dust.velocity += vector2 * 0.5f;
                    dust.position += dust.velocity * 4f;
                    if (Main.rand.Next(5) == 0)
                    {
                        dust.fadeIn = 0.8f;
                    }
                    break;
                }
                case 5:
                    num3 = 6;
                    num4 = 2.5f;
                    goto IL_031B;
                case 6:
                    num3 = 186;
                    num4 = 1.5f;
                    num5 = 20;
                    goto IL_031B;
                default:
                    goto IL_031B;
                }
                IL_0469:
                i++;
                continue;
                IL_031B:
                dust = Dust.NewDustDirect(rectangle.TopLeft(), rectangle.Width, rectangle.Height, num3, 0f, 0f, num5, default(Color), num4);
                dust.shader = GameShaders.Armor.GetSecondaryShader(this.cShoe, this);
                dust.velocity += vector2;
                dust.velocity *= num6;
                switch (this.vanityRocketBoots)
                {
                case 1:
                    dust.noGravity = true;
                    break;
                case 2:
                    dust.velocity *= 0.1f;
                    break;
                case 3:
                {
                    dust.velocity *= 0.05f;
                    Dust dust2 = dust;
                    dust2.velocity.Y = dust2.velocity.Y + 0.15f;
                    dust.noLight = true;
                    if (Main.rand.Next(2) == 0)
                    {
                        dust.noGravity = true;
                        dust.scale = 1.75f;
                    }
                    break;
                }
                case 5:
                    dust.noGravity = true;
                    break;
                case 6:
                    dust.velocity *= 0.1f;
                    break;
                }
                if (this.fairyBoots)
                {
                    dust.noGravity = true;
                    dust.noLightEmittance = true;
                    goto IL_0469;
                }
                goto IL_0469;
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Microsoft.Xna.Framework.Rectangle.Height, int, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Color.LimeGreen, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.