Terraria Decompiled: Terraria.Player.WingFrame
WingFrame()
void Terraria.Player.WingFrame (bool wingFlap) inline
Definition at line 27946 of file Player.cs.
        {
            bool flag = this.wingsLogic != this.wings;
            if (this.wings == 4)
            {
                if (wingFlap || this.jump > 0)
                {
                    this.rocketDelay2--;
                    if (this.rocketDelay2 <= 0)
                    {
                        SoundEngine.PlaySound(SoundID.Item13, this.position, 0f, 1f);
                        this.rocketDelay2 = 60;
                    }
                    int num = 2;
                    if (this.TryingToHoverUp)
                    {
                        num = 4;
                    }
                    for (int i = 0; i < num; i++)
                    {
                        int num2 = 6;
                        if (this.head == 41)
{
                            int num3 = this.body;
                        }
                        float num4 = 1.75f;
                        int num5 = 100;
                        float num6 = this.position.X + (float)(this.width / 2) + 16f;
                        if (this.direction > 0)
{
                            num6 = this.position.X + (float)(this.width / 2) - 26f;
                        }
                        float num7 = this.position.Y + (float)this.height - 18f;
                        if (i == 1 || i == 3)
{
                            num6 = this.position.X + (float)(this.width / 2) + 8f;
                            if (this.direction > 0)
{
                                num6 = this.position.X + (float)(this.width / 2) - 20f;
                            }
                            num7 += 6f;
                        }
                        if (i > 1)
{
                            num7 += this.velocity.Y;
                        }
                        int num8 = Dust.NewDust(new Vector2(num6, num7), 8, 8, num2, 0f, 0f, num5, default(Color), num4);
                        Dust dust = Main.dust[num8];
                        dust.velocity.X = dust.velocity.X * 0.1f;
                        Main.dust[num8].velocity.Y = Main.dust[num8].velocity.Y * 1f + 2f * this.gravDir - this.velocity.Y * 0.3f;
                        Main.dust[num8].noGravity = true;
                        Main.dust[num8].noLightEmittance = flag;
                        Main.dust[num8].shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                        if (num == 4)
{
                            Dust dust2 = Main.dust[num8];
                            dust2.velocity.Y = dust2.velocity.Y + 6f;
                        }
                    }
                    this.wingFrameCounter++;
                    if (this.wingFrameCounter > 4)
                    {
                        this.wingFrame++;
                        this.wingFrameCounter = 0;
                        if (this.wingFrame >= 3)
{
                            this.wingFrame = 0;
                            return;
                        }
                    }
                }
                else if (!this.controlJump || this.velocity.Y == 0f)
                {
                    this.wingFrame = 3;
                    return;
                }
            }
            else if (this.wings == 28 && this.ShouldDrawWingsThatAreAlwaysAnimated(false))
            {
                if (!flag && this.velocity.Y != 0f)
                {
                    Lighting.AddLight(base.Bottom, 0.3f, 0.1f, 0.4f);
                    return;
                }
            }
            else if (this.wings == 22)
            {
                if (!this.controlJump)
                {
                    this.wingFrame = 0;
                    this.wingFrameCounter = 0;
                    return;
                }
                if (this.wingTime > 0f)
                {
                    if (this.TryingToHoverDown)
                    {
                        if (this.velocity.X != 0f)
{
                            this.wingFrameCounter++;
                            int num9 = 2;
                            if (this.wingFrameCounter < num9)
{
                                this.wingFrame = 1;
                                return;
                            }
                            if (this.wingFrameCounter < num9 * 2)
{
                                this.wingFrame = 2;
                                return;
                            }
                            if (this.wingFrameCounter < num9 * 3)
{
                                this.wingFrame = 3;
                                return;
                            }
                            if (this.wingFrameCounter < num9 * 4 - 1)
{
                                this.wingFrame = 2;
                                return;
                            }
                            this.wingFrame = 2;
                            this.wingFrameCounter = 0;
                            return;
                        }
                        else
{
                            this.wingFrameCounter++;
                            int num10 = 6;
                            if (this.wingFrameCounter < num10)
{
                                this.wingFrame = 4;
                                return;
                            }
                            if (this.wingFrameCounter < num10 * 2)
{
                                this.wingFrame = 5;
                                return;
                            }
                            if (this.wingFrameCounter < num10 * 3 - 1)
{
                                this.wingFrame = 4;
                                return;
                            }
                            this.wingFrame = 4;
                            this.wingFrameCounter = 0;
                            return;
                        }
                    }
                    else
                    {
                        this.wingFrameCounter++;
                        int num11 = 2;
                        if (this.wingFrameCounter < num11)
{
                            this.wingFrame = 4;
                            return;
                        }
                        if (this.wingFrameCounter < num11 * 2)
{
                            this.wingFrame = 5;
                            return;
                        }
                        if (this.wingFrameCounter < num11 * 3)
{
                            this.wingFrame = 6;
                            return;
                        }
                        if (this.wingFrameCounter < num11 * 4 - 1)
{
                            this.wingFrame = 5;
                            return;
                        }
                        this.wingFrame = 5;
                        this.wingFrameCounter = 0;
                        return;
                    }
                }
                else
                {
                    this.wingFrameCounter++;
                    int num12 = 6;
                    if (this.wingFrameCounter < num12)
                    {
                        this.wingFrame = 4;
                        return;
                    }
                    if (this.wingFrameCounter < num12 * 2)
                    {
                        this.wingFrame = 5;
                        return;
                    }
                    if (this.wingFrameCounter < num12 * 3 - 1)
                    {
                        this.wingFrame = 4;
                        return;
                    }
                    this.wingFrame = 4;
                    this.wingFrameCounter = 0;
                    return;
                }
            }
            else if (this.wings == 12)
            {
                if (wingFlap || this.jump > 0)
                {
                    this.wingFrameCounter++;
                    int num13 = 5;
                    if (this.wingFrameCounter < num13)
                    {
                        this.wingFrame = 1;
                        return;
                    }
                    if (this.wingFrameCounter < num13 * 2)
                    {
                        this.wingFrame = 2;
                        return;
                    }
                    if (this.wingFrameCounter < num13 * 3)
                    {
                        this.wingFrame = 3;
                        return;
                    }
                    if (this.wingFrameCounter < num13 * 4 - 1)
                    {
                        this.wingFrame = 2;
                        return;
                    }
                    this.wingFrame = 2;
                    this.wingFrameCounter = 0;
                    return;
                }
                else
                {
                    if (this.velocity.Y != 0f)
                    {
                        this.wingFrame = 2;
                        return;
                    }
                    this.wingFrame = 0;
                    return;
                }
            }
            else if (this.wings == 24)
            {
                if (wingFlap || this.jump > 0)
                {
                    this.wingFrameCounter++;
                    int num14 = 1;
                    if (this.wingFrameCounter < num14)
                    {
                        this.wingFrame = 1;
                        return;
                    }
                    if (this.wingFrameCounter < num14 * 2)
                    {
                        this.wingFrame = 2;
                        return;
                    }
                    if (this.wingFrameCounter < num14 * 3)
                    {
                        this.wingFrame = 3;
                        return;
                    }
                    this.wingFrame = 2;
                    if (this.wingFrameCounter >= num14 * 4 - 1)
                    {
                        this.wingFrameCounter = 0;
                        return;
                    }
                }
                else
                {
                    if (this.velocity.Y == 0f)
                    {
                        this.wingFrame = 0;
                        return;
                    }
                    if (this.controlJump)
                    {
                        this.wingFrameCounter++;
                        int num15 = 3;
                        if (this.wingFrameCounter < num15)
{
                            this.wingFrame = 1;
                            return;
                        }
                        if (this.wingFrameCounter < num15 * 2)
{
                            this.wingFrame = 2;
                            return;
                        }
                        if (this.wingFrameCounter < num15 * 3)
{
                            this.wingFrame = 3;
                            return;
                        }
                        this.wingFrame = 2;
                        if (this.wingFrameCounter >= num15 * 4 - 1)
{
                            this.wingFrameCounter = 0;
                            return;
                        }
                    }
                    else
                    {
                        if (this.wingTime == 0f)
{
                            this.wingFrame = 0;
                            return;
                        }
                        this.wingFrame = 1;
                        return;
                    }
                }
            }
            else if (this.wings == 30)
            {
                bool flag2 = false;
                if (wingFlap || this.jump > 0)
                {
                    this.wingFrameCounter++;
                    int num16 = 2;
                    if (this.wingFrameCounter >= num16 * 3)
                    {
                        this.wingFrameCounter = 0;
                    }
                    this.wingFrame = 1 + this.wingFrameCounter / num16;
                    flag2 = true;
                }
                else if (this.velocity.Y != 0f)
                {
                    if (this.controlJump)
                    {
                        this.wingFrameCounter++;
                        int num17 = 2;
                        if (this.wingFrameCounter >= num17 * 3)
{
                            this.wingFrameCounter = 0;
                        }
                        this.wingFrame = 1 + this.wingFrameCounter / num17;
                        flag2 = true;
                    }
                    else if (this.wingTime == 0f)
                    {
                        this.wingFrame = 0;
                    }
                    else
                    {
                        this.wingFrame = 0;
                    }
                }
                else
                {
                    this.wingFrame = 0;
                }
                if (flag2)
                {
                    for (int j = 0; j < 4; j++)
                    {
                        if (Main.rand.Next(4) == 0)
{
                            Vector2 vector = (-0.74539816f + 0.3926991f * (float)j + 0.03f * (float)j).ToRotationVector2() * new Vector2((float)(-(float)this.direction * 20), 20f);
                            Dust dust3 = Main.dust[Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, Color.White, 0.8f)];
                            dust3.noGravity = true;
                            dust3.noLightEmittance = flag;
                            dust3.position = base.Center + vector;
                            dust3.velocity = base.DirectionTo(dust3.position) * 2f;
                            if (Main.rand.Next(10) != 0)
{
                                dust3.customData = this;
                            }
                            else
{
                                dust3.fadeIn = 0.5f;
                            }
                            dust3.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                        }
                    }
                    for (int k = 0; k < 4; k++)
                    {
                        if (Main.rand.Next(8) == 0)
{
                            Vector2 vector2 = (-0.7053982f + 0.3926991f * (float)k + 0.03f * (float)k).ToRotationVector2() * new Vector2((float)(this.direction * 20), 24f) + new Vector2((float)(-(float)this.direction) * 16f, 0f);
                            Dust dust4 = Main.dust[Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, Color.White, 0.5f)];
                            dust4.noGravity = true;
                            dust4.noLightEmittance = flag;
                            dust4.position = base.Center + vector2;
                            dust4.velocity = Vector2.Normalize(dust4.position - base.Center - new Vector2((float)(-(float)this.direction) * 16f, 0f)) * 2f;
                            dust4.position += dust4.velocity * 5f;
                            if (Main.rand.Next(10) != 0)
{
                                dust4.customData = this;
                            }
                            else
{
                                dust4.fadeIn = 0.5f;
                            }
                            dust4.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                        }
                    }
                    return;
                }
            }
            else if (this.wings == 34 && this.ShouldDrawWingsThatAreAlwaysAnimated(false))
            {
                if (wingFlap || this.jump > 0)
                {
                    this.wingFrameCounter++;
                    int num18 = 4;
                    if (this.wingFrameCounter >= num18 * 6)
                    {
                        this.wingFrameCounter = 0;
                    }
                    this.wingFrame = this.wingFrameCounter / num18;
                    return;
                }
                if (this.velocity.Y == 0f)
                {
                    this.wingFrameCounter++;
                    int num19 = 4;
                    if (this.wingFrameCounter >= num19 * 6)
                    {
                        this.wingFrameCounter = 0;
                    }
                    this.wingFrame = this.wingFrameCounter / num19;
                    return;
                }
                if (this.controlJump)
                {
                    this.wingFrameCounter++;
                    int num20 = 9;
                    if (this.wingFrameCounter >= num20 * 6)
                    {
                        this.wingFrameCounter = 0;
                    }
                    this.wingFrame = this.wingFrameCounter / num20;
                    return;
                }
                this.wingFrameCounter++;
                int num21 = 6;
                if (this.wingFrameCounter >= num21 * 6)
                {
                    this.wingFrameCounter = 0;
                }
                this.wingFrame = this.wingFrameCounter / num21;
                return;
            }
            else if (this.wings == 51)
            {
                int num22 = 2;
                int num23 = 8;
                if (wingFlap || this.jump > 0)
                {
                    this.wingFrameCounter++;
                    int num24 = 4;
                    if (this.wingFrameCounter >= num24 * num23)
                    {
                        this.wingFrameCounter = num24 * num22;
                    }
                    this.wingFrame = this.wingFrameCounter / num24;
                    return;
                }
                if (this.velocity.Y == 0f)
                {
                    this.wingFrame = 0;
                    this.wingFrameCounter = 0;
                    return;
                }
                if (this.controlJump)
                {
                    this.wingFrameCounter++;
                    int num25 = 6;
                    if (this.wingFrameCounter >= num25 * num23)
                    {
                        this.wingFrameCounter = num25 * num22;
                    }
                    this.wingFrame = this.wingFrameCounter / num25;
                    return;
                }
                this.wingFrameCounter++;
                int num26 = 8;
                if (this.wingFrameCounter >= num26 * num23)
                {
                    this.wingFrameCounter = num26 * num22;
                }
                this.wingFrame = this.wingFrameCounter / num26;
                return;
            }
            else
            {
                if (this.wings == 47)
                {
                    bool flag3 = false;
                    bool flag4 = false;
                    bool flag5 = false;
                    this.GetWingsFunctionalityForVisuals(this.wingsLogic, out flag3, out flag4, out flag5);
                    bool flag6 = false;
                    bool flag7 = true;
                    int num27 = 0;
                    if (wingFlap)
                    {
                        if (this.velocity.Y * this.gravDir > 0f)
{
                            num27 = 2;
                        }
                        else if (flag5 && this.TryingToHoverUp)
{
                            num27 = 3;
                        }
                        else if (flag3 && this.TryingToHoverDown)
{
                            if (flag4 && (this.controlLeft || this.controlRight))
{
                                num27 = 4;
                            }
                            else
{
                                num27 = 6;
                            }
                        }
                        else
{
                            num27 = 4;
                        }
                    }
                    else if (this.velocity.Y != 0f)
                    {
                        num27 = 6;
                        if (this.velocity.Y * this.gravDir > 0f)
{
                            flag6 = this.controlJump && !this.isPerformingJump_DownDash;
                            if (flag6)
{
                                num27 = 3;
                                if (this.wingFrame == 1)
{
                                    flag7 = false;
                                }
                            }
                            else if (this.wingFrame == 2)
{
                                flag7 = false;
                            }
                        }
                    }
                    else
                    {
                        flag7 = false;
                        this.wingFrame = 0;
                    }
                    bool flag8 = false;
                    if (flag7)
                    {
                        if (this.wingFrame == 0)
{
                            this.wingFrame = 2;
                        }
                        this.wingFrameCounter++;
                        if (this.wingFrameCounter >= num27)
{
                            flag8 = true;
                            this.wingFrameCounter = 0;
                            if (this.wingFrame == 1)
{
                                this.wingFrame = 10;
                            }
                            else if (this.wingFrame == 3 && flag6)
{
                                this.wingFrame = 1;
                            }
                            else
{
                                int num28 = this.wingFrame + 1;
                                this.wingFrame = num28;
                                if (num28 > 10)
{
                                    this.wingFrame = 2;
                                }
                            }
                        }
                    }
                    else
                    {
                        this.wingFrameCounter = 0;
                    }
                    this.ChickenBonesWingDust(flag, flag8);
                    return;
                }
                if (this.wings == 49)
                {
                    bool flag9 = false;
                    bool flag10 = false;
                    bool flag11 = false;
                    this.GetWingsFunctionalityForVisuals(this.wingsLogic, out flag9, out flag10, out flag11);
                    bool flag12 = false;
                    bool flag13 = true;
                    int num29 = 0;
                    if (wingFlap)
                    {
                        if (this.velocity.Y * this.gravDir > 0f)
{
                            num29 = 2;
                        }
                        else if (flag11 && this.TryingToHoverUp)
{
                            num29 = 3;
                        }
                        else if (flag9 && this.TryingToHoverDown)
{
                            if (flag10 && (this.controlLeft || this.controlRight))
{
                                num29 = 4;
                            }
                            else
{
                                num29 = 6;
                            }
                        }
                        else
{
                            num29 = 4;
                        }
                    }
                    else if (this.velocity.Y != 0f)
                    {
                        num29 = 6;
                        if (this.velocity.Y * this.gravDir > 0f)
{
                            flag12 = this.controlJump && !this.isPerformingJump_DownDash;
                            if (flag12)
{
                                num29 = 3;
                                if (this.wingFrame == 1)
{
                                    flag13 = false;
                                }
                            }
                            else if (this.wingFrame == 2)
{
                                flag13 = false;
                            }
                        }
                    }
                    else
                    {
                        flag13 = false;
                        this.wingFrame = 0;
                    }
                    bool flag14 = false;
                    if (flag13)
                    {
                        if (this.wingFrame == 0)
{
                            this.wingFrame = 2;
                        }
                        this.wingFrameCounter++;
                        if (this.wingFrameCounter >= num29)
{
                            flag14 = true;
                            this.wingFrameCounter = 0;
                            if (this.wingFrame == 1)
{
                                this.wingFrame = 10;
                            }
                            else if (this.wingFrame == 3 && flag12)
{
                                this.wingFrame = 1;
                            }
                            else
{
                                int num28 = this.wingFrame + 1;
                                this.wingFrame = num28;
                                if (num28 > 10)
{
                                    this.wingFrame = 2;
                                }
                            }
                        }
                    }
                    else
                    {
                        this.wingFrameCounter = 0;
                    }
                    this.HeroicisWingDust(flag, flag14);
                    return;
                }
                if (this.wings == 50)
                {
                    bool flag15 = false;
                    bool flag16 = false;
                    bool flag17 = false;
                    this.GetWingsFunctionalityForVisuals(this.wingsLogic, out flag15, out flag16, out flag17);
                    bool flag18 = false;
                    bool flag19 = true;
                    int num30 = 0;
                    if (wingFlap)
                    {
                        if (this.velocity.Y * this.gravDir > 0f)
{
                            num30 = 2;
                        }
                        else if (flag17 && this.TryingToHoverUp)
{
                            num30 = 3;
                        }
                        else if (flag15 && this.TryingToHoverDown)
{
                            if (flag16 && (this.controlLeft || this.controlRight))
{
                                num30 = 4;
                            }
                            else
{
                                num30 = 6;
                            }
                        }
                        else
{
                            num30 = 4;
                        }
                    }
                    else if (this.velocity.Y != 0f)
                    {
                        num30 = 5;
                        if (this.velocity.Y * this.gravDir > 0f)
{
                            flag18 = this.controlJump && !this.isPerformingJump_DownDash;
                            if (flag18)
{
                                num30 = 3;
                                if (this.wingFrame == 1)
{
                                    flag19 = false;
                                }
                            }
                            else if (this.wingFrame == 2)
{
                                flag19 = false;
                            }
                        }
                    }
                    else
                    {
                        flag19 = false;
                        this.wingFrame = 0;
                    }
                    bool flag20 = false;
                    if (flag19)
                    {
                        if (this.wingFrame == 0)
{
                            this.wingFrame = 2;
                        }
                        this.wingFrameCounter++;
                        if (this.wingFrameCounter >= num30)
{
                            flag20 = true;
                            this.wingFrameCounter = 0;
                            if (this.wingFrame == 1)
{
                                this.wingFrame = 3;
                            }
                            else if (this.wingFrame == 2 && flag18)
{
                                this.wingFrame = 1;
                            }
                            else
{
                                int num28 = this.wingFrame + 1;
                                this.wingFrame = num28;
                                if (num28 > 9)
{
                                    this.wingFrame = 2;
                                }
                            }
                        }
                    }
                    else
                    {
                        this.wingFrameCounter = 0;
                    }
                    this.KazzymodusWingDust(flag, flag20);
                    return;
                }
                if (this.wings == 45 && this.ShouldDrawWingsThatAreAlwaysAnimated(false))
                {
                    if (this.wingTime > 0f)
                    {
                        this.rocketDelay2--;
                        if (this.rocketDelay2 <= 0)
{
                            SoundEngine.PlaySound(SoundID.Item24, this.position, 0f, 1f);
                            this.rocketDelay2 = 30;
                        }
                    }
                    if (this.velocity.Y == 0f)
                    {
                        this.wingFrameCounter = 0;
                        this.wingFrame = 0;
                    }
                    else
                    {
                        this.wingFrameCounter++;
                        int num31 = 3;
                        if (this.wingTime == 0f)
{
                            num31 = 5;
                        }
                        if (this.wingFrameCounter >= num31 * 6)
{
                            this.wingFrameCounter = 0;
                        }
                        this.wingFrame = this.wingFrameCounter / num31;
                    }
                    if (Main.netMode != 2 && Main.rand.Next(8) == 0)
                    {
                        Rectangle rectangle = Utils.CenteredRectangle(Main.ReverseGravitySupport(base.Bottom - Main.screenPosition, 0f) + Main.screenPosition, new Vector2(40f, 24f));
                        Dust dust5 = Dust.NewDustDirect(rectangle.TopLeft(), rectangle.Width, rectangle.Height, 43, 0f, 0f, 0, Color.White * 0.5f, 0.2f);
                        dust5.fadeIn = 0.4f;
                        dust5.velocity += this.velocity;
                        dust5.velocity *= 0.35f;
                        dust5.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                        return;
                    }
                }
                else if (this.wings == 44 && this.ShouldDrawWingsThatAreAlwaysAnimated(false))
                {
                    int num32 = 5;
                    if (wingFlap || this.jump > 0)
                    {
                        this.wingFrameCounter++;
                        if (this.wingFrameCounter >= num32 * 6)
{
                            this.wingFrameCounter = 0;
                        }
                        this.wingFrame = 1 + this.wingFrameCounter / num32;
                        return;
                    }
                    if (this.velocity.Y == 0f)
                    {
                        this.wingFrameCounter++;
                        if (this.wingFrameCounter >= num32 * 6)
{
                            this.wingFrameCounter = 0;
                        }
                        this.wingFrame = 1 + this.wingFrameCounter / num32;
                        return;
                    }
                    if (this.controlJump)
                    {
                        this.wingFrame = 2;
                        return;
                    }
                    if (this.ShouldFloatInWater && this.wet)
                    {
                        this.wingFrame = 0;
                        return;
                    }
                    this.wingFrame = 3;
                    return;
                }
                else
                {
                    if (this.wings == 39 && this.ShouldDrawWingsThatAreAlwaysAnimated(false))
                    {
                        if (wingFlap || this.jump > 0)
{
                            this.wingFrameCounter++;
                            int num33 = 4;
                            if (this.wingFrameCounter >= num33 * 6)
{
                                this.wingFrameCounter = 0;
                            }
                            this.wingFrame = this.wingFrameCounter / num33;
                        }
                        else if (this.velocity.Y != 0f)
{
                            if (this.controlJump)
{
                                this.wingFrameCounter++;
                                int num34 = 9;
                                if (this.wingFrameCounter >= num34 * 6)
{
                                    this.wingFrameCounter = 0;
                                }
                                this.wingFrame = this.wingFrameCounter / num34;
                            }
                            else
{
                                this.wingFrameCounter++;
                                int num35 = 6;
                                if (this.wingFrameCounter >= num35 * 6)
{
                                    this.wingFrameCounter = 0;
                                }
                                this.wingFrame = this.wingFrameCounter / num35;
                            }
                        }
                        else
{
                            this.wingFrameCounter++;
                            int num36 = 4;
                            if (this.wingFrameCounter >= num36 * 6)
{
                                this.wingFrameCounter = 0;
                            }
                            this.wingFrame = this.wingFrameCounter / num36;
                        }
                        int num37 = 1;
                        if (this.wingFrame == 3)
{
                            num37 = 5;
                        }
                        if (this.velocity.Y == 0f)
{
                            num37 = 0;
                        }
                        Rectangle rectangle2 = Utils.CenteredRectangle((this.gravDir == 1f) ? (base.Bottom + new Vector2(0f, -10f)) : (base.Top + new Vector2(0f, 10f)), new Vector2(50f, 20f));
                        for (int l = 0; l < num37; l++)
{
                            Dust dust6 = Dust.NewDustDirect(rectangle2.TopLeft(), rectangle2.Width, rectangle2.Height, 31, 0f, 0f, 0, Color.Black, 1f);
                            dust6.scale = 0.7f;
                            dust6.velocity *= 0.4f;
                            dust6.velocity.Y = dust6.velocity.Y + this.gravDir * 0.5f;
                            dust6.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                        }
                        return;
                    }
                    if (this.wings == 33)
                    {
                        bool flag21 = false;
                        if (wingFlap || this.jump > 0)
{
                            flag21 = true;
                        }
                        else if (this.velocity.Y != 0f && this.controlJump)
{
                            flag21 = true;
                        }
                        if (flag21)
{
                            Color color = Main.hslToRgb(Main.rgbToHsl(this.eyeColor).X, 1f, 0.5f, byte.MaxValue);
                            int num38 = ((this.direction == 1) ? 0 : (-4));
                            int num39 = ((this.gravDir == 1f) ? this.height : 0);
                            for (int m = 0; m < 2; m++)
{
                                Dust dust7 = Main.dust[Dust.NewDust(this.position, this.width, this.height, 182, this.velocity.X, this.velocity.Y, 127, color, 1f)];
                                dust7.noGravity = true;
                                dust7.fadeIn = 1f;
                                dust7.scale = 1f;
                                dust7.noLight = true;
                                dust7.noLightEmittance = flag;
                                dust7.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                                if (m == 0)
{
                                    dust7.position = new Vector2(this.position.X + (float)num38, this.position.Y + (float)num39);
                                    dust7.velocity.X = dust7.velocity.X * 1f - 2f - this.velocity.X * 0.3f;
                                    dust7.velocity.Y = dust7.velocity.Y * 1f + 2f * this.gravDir - this.velocity.Y * 0.3f;
                                }
                                else if (m == 1)
{
                                    dust7.position = new Vector2(this.position.X + (float)this.width + (float)num38, this.position.Y + (float)num39);
                                    dust7.velocity.X = dust7.velocity.X * 1f + 2f - this.velocity.X * 0.3f;
                                    dust7.velocity.Y = dust7.velocity.Y * 1f + 2f * this.gravDir - this.velocity.Y * 0.3f;
                                }
                                if (dust7.dustIndex != 6000)
{
                                    Dust dust8 = Dust.CloneDust(dust7);
                                    dust8.scale *= 0.65f;
                                    dust8.fadeIn *= 0.65f;
                                    dust8.color = new Color(255, 255, 255, 255);
                                    dust7.noLight = true;
                                    dust7.noLightEmittance = flag;
                                    dust7.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                                }
                            }
                            return;
                        }
                    }
                    else if (this.wings == 38)
                    {
                        bool flag22 = false;
                        if (wingFlap || this.jump > 0)
{
                            this.wingFrameCounter++;
                            if (this.wingFrameCounter >= 32)
{
                                this.wingFrameCounter = 0;
                            }
                            this.wingFrame = 1 + this.wingFrameCounter / 8;
                            if (this.wingFrame == 4)
{
                                this.wingFrame = 2;
                            }
                            flag22 = true;
                        }
                        else if (this.velocity.Y != 0f)
{
                            if (this.controlJump)
{
                                this.wingFrameCounter++;
                                if (this.wingFrameCounter >= 32)
{
                                    this.wingFrameCounter = 0;
                                }
                                this.wingFrame = 1 + this.wingFrameCounter / 8;
                                if (this.wingFrame == 4)
{
                                    this.wingFrame = 2;
                                }
                                flag22 = true;
                            }
                            else
{
                                this.wingFrame = 0;
                            }
                        }
                        else
{
                            this.wingFrame = 0;
                        }
                        if (flag22)
{
                            Vector2 vector3 = new Vector2((float)this.direction, this.gravDir);
                            Vector2 vector4 = this.velocity * 0.5f;
                            int num40 = 267;
                            int num41 = this.miscCounter * this.direction;
                            for (int n = 0; n < 3; n++)
{
                                Vector2 vector5 = Vector2.Zero;
                                if (n != 1)
{
                                    if (n == 2)
{
                                        vector5 = this.velocity * -0.66f;
                                    }
                                }
                                else
{
                                    vector5 = this.velocity * -0.33f;
                                }
                                Vector2 vector6 = new Vector2(-39f, 6f) * vector3 + new Vector2(2f, 0f).RotatedBy((double)((float)num41 / -15f * 6.2831855f), default(Vector2));
                                Dust dust9 = Dust.NewDustPerfect(base.Center + vector6 + vector5, num40, new Vector2?(vector4), 0, this.underShirtColor, 1f);
                                dust9.noGravity = true;
                                dust9.noLight = true;
                                dust9.noLightEmittance = flag;
                                dust9.scale = 0.47f;
                                dust9.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                                vector6 = new Vector2(-23f, 2f) * vector3 + new Vector2(2f, 0f).RotatedBy((double)((float)num41 / -15f * 6.2831855f), default(Vector2));
                                Dust dust10 = Dust.NewDustPerfect(base.Center + vector6 + vector5, num40, new Vector2?(vector4), 0, this.underShirtColor, 1f);
                                dust10.noGravity = true;
                                dust10.noLight = true;
                                dust10.noLightEmittance = flag;
                                dust10.scale = 0.35f;
                                dust10.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                                vector6 = new Vector2(-31f, -6f) * vector3 + new Vector2(2f, 0f).RotatedBy((double)((float)num41 / -20f * 6.2831855f), default(Vector2));
                                Dust dust11 = Dust.NewDustPerfect(base.Center + vector6 + vector5, num40, new Vector2?(vector4), 0, this.underShirtColor, 1f);
                                dust11.noGravity = true;
                                dust11.noLight = true;
                                dust11.noLightEmittance = flag;
                                dust11.scale = 0.49f;
                                dust11.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                            }
                            return;
                        }
                    }
                    else
                    {
                        int num42 = 4;
                        int num43 = 4;
                        int num44 = 0;
                        int num45 = 0;
                        int num46 = 1;
                        if (this.wings == 43)
{
                            num43 = 7;
                            num44 = 1;
                            num42 = 3;
                        }
                        if (this.wings == 48)
{
                            num43 = 8;
                            num44 = 0;
                            num42 = 2;
                        }
                        if (this.wings == 32)
{
                            num42 = 3;
                        }
                        if (wingFlap || this.jump > 0)
{
                            this.wingFrameCounter++;
                            if (this.wingFrameCounter > num42)
{
                                this.wingFrame++;
                                this.wingFrameCounter = 0;
                                if (this.wingFrame >= num43)
{
                                    this.wingFrame = num44;
                                    return;
                                }
                            }
                        }
                        else if (this.velocity.Y != 0f)
{
                            this.wingFrame = num46;
                            if (this.wings == 32)
{
                                this.wingFrame = 3;
                            }
                            if (this.wings == 43)
{
                                this.wingFrame = 2;
                                if (this.ShouldFloatInWater && this.wet)
{
                                    this.wingFrame = num45;
                                }
                            }
                            if (this.wings == 49)
{
                                this.wingFrame = 1;
                                if (this.ShouldFloatInWater && this.wet)
{
                                    this.wingFrame = num45;
                                }
                            }
                            if (this.wings == 29 && Main.rand.Next(5) == 0)
{
                                int num47 = 4;
                                if (this.direction == 1)
{
                                    num47 = -40;
                                }
                                int num48 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) + (float)num47, this.position.Y + (float)(this.height / 2) - 15f), 30, 30, 6, 0f, 0f, 100, default(Color), 2.4f);
                                Main.dust[num48].noGravity = true;
                                Main.dust[num48].noLightEmittance = flag;
                                Main.dust[num48].velocity *= 0.3f;
                                if (Main.rand.Next(10) == 0)
{
                                    Main.dust[num48].fadeIn = 2f;
                                }
                                Main.dust[num48].shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                                return;
                            }
                        }
                        else
{
                            this.wingFrame = num45;
                        }
                    }
                }
            }
        }
References Terraria.Lighting.AddLight(), Terraria.Graphics.Shaders.GameShaders.Armor, Microsoft.Xna.Framework.Color.Black, Terraria.Utils.CenteredRectangle(), Terraria.Dust.CloneDust(), Terraria.Main.dust, Terraria.Dust.dustIndex, Terraria.Dust.fadeIn, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.hslToRgb(), Terraria.ID.SoundID.Item13, Terraria.ID.SoundID.Item24, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLightEmittance, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.Main.rand, Terraria.Main.ReverseGravitySupport(), Terraria.Main.rgbToHsl(), Terraria.Main.screenPosition, Terraria.Dust.shader, Terraria.Dust.velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.Elements.UICharacter.UpdateAnim().