Terraria Decompiled: Terraria.Player.CanMasterModeAccessoryBeShown
CanMasterModeAccessoryBeShown()
bool Terraria.Player.CanMasterModeAccessoryBeShown () inline
Definition at line 295 of file Player.cs.
        {
            return this.IsItemSlotUnlockedAndUsable(9) || this.armor[9].type > 0 || this.armor[19].type > 0 || this.dye[9].type > 0;
        }
References Terraria.Player.armor, Terraria.Player.dye, Terraria.Player.IsItemSlotUnlockedAndUsable(), and Terraria.Item.type.
Referenced by Terraria.Main.DrawInventory(), and Terraria.Player.GetAmountOfExtraAccessorySlotsToShow().