Terraria Decompiled: Terraria.Player.MakeFloorDust
MakeFloorDust()
void Terraria.Player.MakeFloorDust (bool Falling, int type, int frameX, int frameY, int paintColor) inline private
Definition at line 22264 of file Player.cs.
        {
            if (type == 659 || type == 667)
            {
                bool flag = true;
                if (!Falling)
                {
                    float num = Math.Abs(this.velocity.X) / 3f;
                    if ((float)Main.rand.Next(100) > num * 50f)
                    {
                        flag = false;
                    }
                }
                if (!flag)
                {
                    return;
                }
                Vector2 vector = new Vector2(this.position.X, this.position.Y + (float)this.height - 2f) + new Vector2((float)this.width * Main.rand.NextFloat(), 6f * Main.rand.NextFloat());
                Vector2 vector2 = Main.rand.NextVector2Circular(0.8f, 0.8f);
                if (vector2.Y > 0f)
                {
                    vector2.Y *= -1f;
                }
                ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.ShimmerBlock, new ParticleOrchestraSettings
                {
                    PositionInWorld = vector,
                    MovementVector = vector2
                }, new int?(this.whoAmI));
            }
            bool flag2 = type == 19 && frameY / 18 == 49;
            if (type == 147 || type == 25 || type == 53 || type == 189 || flag2 || type == 0 || type == 123 || type == 57 || type == 112 || type == 116 || type == 196 || type == 193 || type == 195 || type == 197 || type == 199 || type == 229 || type == 234 || type == 371 || type == 460 || type == 666 || type == 712 || type == 717 || type == 718 || type == 719)
            {
                int num2 = 1;
                if (Falling)
                {
                    num2 = 20;
                    if (type == 666 || type == 712)
                    {
                        SoundEngine.PlaySound(SoundID.Item177, (int)base.Center.X, (int)base.Bottom.Y, 0f, 1f);
                    }
                }
                for (int i = 0; i < num2; i++)
                {
                    bool flag3 = true;
                    int num3 = 76;
                    if (type == 666 || type == 712)
                    {
                        if (paintColor != 0)
{
                            return;
                        }
                        num3 = 322;
                    }
                    if (type == 53)
                    {
                        num3 = 32;
                    }
                    if (type == 189 || flag2)
                    {
                        num3 = 16;
                    }
                    if (type == 717)
                    {
                        num3 = 326;
                    }
                    if (type == 718)
                    {
                        num3 = 327;
                    }
                    if (type == 719)
                    {
                        num3 = 328;
                    }
                    if (type == 0)
                    {
                        num3 = 0;
                    }
                    if (type == 123)
                    {
                        num3 = 53;
                    }
                    if (type == 57)
                    {
                        num3 = 36;
                    }
                    if (type == 112)
                    {
                        num3 = 14;
                    }
                    if (type == 234)
                    {
                        num3 = 122;
                    }
                    if (type == 116)
                    {
                        num3 = 51;
                    }
                    if (type == 196)
                    {
                        num3 = 108;
                    }
                    if (type == 193)
                    {
                        num3 = 4;
                    }
                    if (type == 195 || type == 199)
                    {
                        num3 = 5;
                    }
                    if (type == 197)
                    {
                        num3 = 4;
                    }
                    if (type == 229)
                    {
                        num3 = 153;
                    }
                    if (type == 371)
                    {
                        num3 = 243;
                    }
                    if (type == 460)
                    {
                        num3 = 108;
                    }
                    if (type == 25)
                    {
                        num3 = 37;
                    }
                    if (num3 == 32 && Main.rand.Next(2) == 0)
                    {
                        flag3 = false;
                    }
                    if (num3 == 14 && Main.rand.Next(2) == 0)
                    {
                        flag3 = false;
                    }
                    if (num3 == 51 && Main.rand.Next(2) == 0)
                    {
                        flag3 = false;
                    }
                    if (num3 == 36 && Main.rand.Next(2) == 0)
                    {
                        flag3 = false;
                    }
                    if (num3 == 0 && Main.rand.Next(3) != 0)
                    {
                        flag3 = false;
                    }
                    if (num3 == 53 && Main.rand.Next(3) != 0)
                    {
                        flag3 = false;
                    }
                    Color color = default(Color);
                    if (type == 193)
                    {
                        color = new Color(30, 100, 255, 100);
                    }
                    if (type == 197)
                    {
                        color = new Color(97, 200, 255, 100);
                    }
                    if (type == 460)
                    {
                        color = new Color(100, 150, 130, 100);
                    }
                    if (!Falling)
                    {
                        float num4 = Math.Abs(this.velocity.X) / 3f;
                        if ((float)Main.rand.Next(100) > num4 * 100f)
{
                            flag3 = false;
                        }
                    }
                    if (flag3)
                    {
                        float num5 = this.velocity.X;
                        if (num5 > 6f)
{
                            num5 = 6f;
                        }
                        if (num5 < -6f)
{
                            num5 = -6f;
                        }
                        if (this.CanSpawnWalkingEffects() || Falling)
{
                            int num6 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)this.height - 2f), this.width, 6, num3, 0f, 0f, 50, color, 1f);
                            if (this.gravDir == -1f)
{
                                Dust dust = Main.dust[num6];
                                dust.position.Y = dust.position.Y - (float)(this.height + 4);
                            }
                            if (num3 == 76)
{
                                Main.dust[num6].scale += (float)Main.rand.Next(3) * 0.1f;
                                Main.dust[num6].noLight = true;
                            }
                            if (num3 == 16 || num3 == 108 || num3 == 153 || num3 == 326 || num3 == 327 || num3 == 328)
{
                                Main.dust[num6].scale += (float)Main.rand.Next(6) * 0.1f;
                            }
                            if (num3 == 37)
{
                                Main.dust[num6].scale += 0.25f;
                                Main.dust[num6].alpha = 50;
                            }
                            if (num3 == 5)
{
                                Main.dust[num6].scale += (float)Main.rand.Next(2, 8) * 0.1f;
                            }
                            Main.dust[num6].noGravity = true;
                            if (num3 == 322)
{
                                if (Main.rand.Next(4) == 0)
{
                                    Main.dust[num6].noGravity = false;
                                    Main.dust[num6].scale *= 1.1f;
                                }
                                else
{
                                    Main.dust[num6].scale *= 1.2f;
                                }
                            }
                            if (num2 > 1)
{
                                Dust dust2 = Main.dust[num6];
                                dust2.velocity.X = dust2.velocity.X * 1.2f;
                                Dust dust3 = Main.dust[num6];
                                dust3.velocity.Y = dust3.velocity.Y * 0.8f;
                                Dust dust4 = Main.dust[num6];
                                dust4.velocity.Y = dust4.velocity.Y - 1f;
                                Main.dust[num6].velocity *= 0.8f;
                                Main.dust[num6].scale += (float)Main.rand.Next(3) * 0.1f;
                                Main.dust[num6].velocity.X = (Main.dust[num6].position.X - (this.position.X + (float)(this.width / 2))) * 0.2f;
                                if (Main.dust[num6].velocity.Y > 0f)
{
                                    Dust dust5 = Main.dust[num6];
                                    dust5.velocity.Y = dust5.velocity.Y * -1f;
                                }
                                Dust dust6 = Main.dust[num6];
                                dust6.velocity.X = dust6.velocity.X + num5 * 0.3f;
                            }
                            else
{
                                Main.dust[num6].velocity *= 0.2f;
                            }
                            Dust dust7 = Main.dust[num6];
                            dust7.position.X = dust7.position.X - num5 * 1f;
                            if (this.gravDir == -1f)
{
                                Dust dust8 = Main.dust[num6];
                                dust8.velocity.Y = dust8.velocity.Y * -1f;
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Dust.alpha, Terraria.Main.dust, Terraria.ID.SoundID.Item177, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Dust.scale, Terraria.Dust.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.