Terraria Decompiled: Terraria.Player.DemonConch
DemonConch()
void Terraria.Player.DemonConch () inline
Definition at line 55501 of file Player.cs.
        {
            bool flag = false;
            int num = 100;
            int num2 = Main.maxTilesX / 2;
            int num3 = num;
            int num4 = num3 / 2;
            int num5 = Main.UnderworldLayer + 20;
            int num6 = 80;
            Utils.RandomTeleportationAttemptSettings randomTeleportationAttemptSettings = new Utils.RandomTeleportationAttemptSettings
            {
                teleporteeSize = base.Size,
                teleporteeVelocity = this.velocity,
                teleporteeGravityDirection = this.gravDir,
                mostlySolidFloor = true,
                avoidAnyLiquid = true,
                avoidLava = true,
                avoidHurtTiles = true,
                avoidWalls = true,
                attemptsBeforeGivingUp = 1000,
                maximumFallDistanceFromOrignalPoint = 100,
                allowSolidTopFloor = true
            };
            Vector2 vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 - num4, num3, num5, num6, randomTeleportationAttemptSettings);
            if (!flag)
            {
                vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 - num3, num4, num5, num6, randomTeleportationAttemptSettings);
            }
            if (!flag)
            {
                vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 + num4, num4, num5, num6, randomTeleportationAttemptSettings);
            }
            if (!flag)
            {
                bool flag2 = Main.rand.Next(2) == 0;
                num2 = (flag2 ? (num3 * 3) : (Main.maxTilesX - num3 * 3));
                vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 - num4, num4, num5, num6, randomTeleportationAttemptSettings);
                if (!flag)
                {
                    vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 - num3, num4, num5, num6, randomTeleportationAttemptSettings);
                }
                if (!flag)
                {
                    vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 + num4, num4, num5, num6, randomTeleportationAttemptSettings);
                }
                if (!flag)
                {
                    num2 = (flag2 ? (Main.maxTilesX - num3 * 3) : (num3 * 3));
                    vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 - num4, num4, num5, num6, randomTeleportationAttemptSettings);
                    if (!flag)
                    {
                        vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 - num3, num4, num5, num6, randomTeleportationAttemptSettings);
                    }
                    if (!flag)
                    {
                        vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2 + num4, num4, num5, num6, randomTeleportationAttemptSettings);
                    }
                }
            }
            if (flag)
            {
                Vector2 vector2 = vector;
                this.Teleport(vector2, 7, 0);
                this.velocity = Vector2.Zero;
                if (Main.netMode == 2)
                {
                    RemoteClient.CheckSection(this.whoAmI, this.position, 1);
                    NetMessage.SendData(65, -1, -1, null, 0, (float)this.whoAmI, vector2.X, vector2.Y, 7, 0, 0);
                    return;
                }
            }
            else
            {
                Vector2 position = this.position;
                this.Teleport(position, 7, 0);
                this.velocity = new Vector2(0f, 0.001f);
                if (Main.netMode == 2)
                {
                    RemoteClient.CheckSection(this.whoAmI, this.position, 1);
                    NetMessage.SendData(65, -1, -1, null, 0, (float)this.whoAmI, position.X, position.Y, 7, 1, 0);
                }
            }
        }
References Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.RemoteClient.CheckSection(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.