Terraria Decompiled: Terraria.Player.ItemCheck_OwnerOnlyCode
ItemCheck_OwnerOnlyCode()
void Terraria.Player.ItemCheck_OwnerOnlyCode (ref Player::ItemCheckContext context, Item sItem, int weaponDamage, Rectangle heldItemFrame) inline private
Definition at line 42538 of file Player.cs.
        {
            bool flag = true;
            if (this.selectedItemState.HasBufferedChange && sItem.useTime > this.itemAnimation)
            {
                flag = false;
            }
            int type = sItem.type;
            if ((type == 65 || type == 676 || type == 723 || type == 724 || type == 757 || type == 674 || type == 675 || type == 989 || type == 1226 || type == 1227) && !this.ItemAnimationJustStarted)
            {
                flag = false;
            }
            if (type == 5097 && this.ItemAnimationJustStarted)
            {
                this._batbatCanHeal = true;
            }
            if (type == 5094 && this.ItemAnimationJustStarted)
            {
                this._spawnTentacleSpikes = true;
            }
            if (type == 795 && this.ItemAnimationJustStarted)
            {
                this._spawnBloodButcherer = true;
            }
            if (type == 121 && this.ItemAnimationJustStarted)
            {
                this._spawnVolcanoExplosion = true;
            }
            if (type == 155 && this.ItemAnimationJustStarted)
            {
                this._spawnMuramasaCut = true;
            }
            if (type == 3852)
            {
                if (this.itemAnimation < this.itemAnimationMax - 12)
                {
                    flag = false;
                }
                if (this.altFunctionUse == 2 && !this.ItemAnimationJustStarted)
                {
                    flag = false;
                }
            }
            if ((type == 4956 || type == 5669) && this.itemAnimation < this.itemAnimationMax - 3 * sItem.useTime)
            {
                flag = false;
            }
            if (type == 4952 && this.itemAnimation < this.itemAnimationMax - 8)
            {
                flag = false;
            }
            if (type == 4953 && this.itemAnimation < this.itemAnimationMax - 10)
            {
                flag = false;
            }
            if (type == 5451 && this.ownedProjectileCounts[1020] > 0)
            {
                flag = false;
            }
            if (type == 5738 && this.ownedProjectileCounts[1105] > 0)
            {
                flag = false;
            }
            if (ItemID.Sets.ShootsOnUseRelease[sItem.type] && this.controlUseItem)
            {
                flag = false;
            }
            bool flag2 = ItemID.Sets.PlaceTileOnAltUse[type];
            bool flag3 = false;
            if (this.altFunctionUse == 2 && flag2)
            {
                flag3 = true;
            }
            if (this.altFunctionUse == 2 && ItemID.Sets.IsAKite[type] && sItem.holdStyle != 0)
            {
                flag3 = false;
                this.StartChanneling();
            }
            this.ItemCheck_TurretAltFeatureUse(sItem, flag);
            this.ItemCheck_MinionAltFeatureUse(sItem, flag);
            bool flag4 = this.itemAnimation > 0 && this.ItemTimeIsZero && flag;
            if (type == 1156 && this.channel)
            {
                int num = 0;
                for (int i = 0; i < 1000; i++)
                {
                    if (Main.projectile[i].active && Main.projectile[i].owner == this.whoAmI && Main.projectile[i].type == this.HeldItem.shoot)
                    {
                        num++;
                    }
                }
                if (num > 0 && num < 3)
                {
                    flag4 = true;
                }
            }
            if (sItem.shootsEveryUse)
            {
                flag4 = this.ItemAnimationJustStarted;
            }
            if (flag3)
            {
                flag4 = false;
            }
            if (sItem.shoot > 0 && flag4)
            {
                this.ItemCheck_Shoot(this.whoAmI, sItem, weaponDamage, true);
            }
            this.ItemCheck_UseWiringTools(sItem);
            this.ItemCheck_UseLawnMower(sItem);
            this.ItemCheck_PlayInstruments(sItem);
            this.ItemCheck_UseBuckets(sItem);
            if (!this.channel)
            {
                this.toolTime = this.itemTime;
            }
            else
            {
                this.toolTime--;
                if (this.toolTime < 0)
                {
                    int num2 = sItem.useTime - 1;
                    this.toolTime = num2;
                }
            }
            if (this.cannonCooldown > 0)
            {
                this.cannonCooldown -= 1;
            }
            this.ItemCheck_TryDestroyingDrones(sItem);
            this.ItemCheck_UseMiningTools(sItem);
            this.ItemCheck_UseTeleportRod(sItem);
            this.ItemCheck_UseLifeCrystal(sItem);
            this.ItemCheck_UseLifeFruit(sItem);
            this.ItemCheck_UseManaCrystal(sItem);
            this.ItemCheck_UseDemonHeart(sItem);
            this.ItemCheck_UseMinecartPowerUp(sItem);
            this.ItemCheck_UseTorchGodsFavor(sItem);
            this.ItemCheck_UseArtisanLoaf(sItem);
            this.ItemCheck_UseEventItems(sItem);
            this.ItemCheck_UseBossSpawners(this.whoAmI, sItem);
            this.ItemCheck_UseCombatBook(sItem);
            this.ItemCheck_UsePeddlersSatchel(sItem);
            this.ItemCheck_UsePetLicenses(sItem);
            this.ItemCheck_UseShimmerPermanentItems(sItem);
            this.ItemCheck_UsePlayerSoundOverrideAccessory(sItem);
            if (sItem.type == 4095 && this.itemAnimation == 2)
            {
                Main.LocalGolfState.ResetGolfBall();
            }
            bool flag5 = flag3 || !flag2;
            this.PlaceThing(flag5, ref context);
            if (sItem.makeNPC > 0)
            {
                if (!Main.GamepadDisableCursorItemIcon && this.IsInTileInteractionRange(Player.tileTargetX, Player.tileTargetY, TileReachCheckSettings.Simple, sItem.tileBoost))
                {
                    this.cursorItemIconEnabled = true;
                    Main.ItemIconCacheUpdate(sItem.type);
                }
                if (this.ItemTimeIsZero && this.itemAnimation > 0 && this.controlUseItem && this.altFunctionUse == 0)
                {
                    this.ItemCheck_ReleaseCritter(sItem);
                }
            }
            if (this.boneGloveItem != null && !this.boneGloveItem.IsAir && this.boneGloveTimer == 0 && this.itemAnimation > 0 && sItem.damage > 0)
            {
                this.boneGloveTimer = 60;
                Vector2 center = base.Center;
                Vector2 vector = base.DirectionTo(this.ApplyRangeCompensation(0.2f, center, Main.MouseWorld)) * 10f;
                Projectile.NewProjectile(this.GetProjectileSource_Accessory(this.boneGloveItem), center.X, center.Y, vector.X, vector.Y, 532, 25, 5f, this.whoAmI, 0f, 0f, 0f, null);
            }
            if (sItem.type == 1124 && this.itemAnimation > 0)
            {
                bool flag6;
                Rectangle rectangle;
                this.ItemCheck_GetMeleeHitbox(sItem, heldItemFrame, out flag6, out rectangle);
                if (Main.rand.Next(30) == 0)
                {
                    Vector2 center2 = base.Center;
                    Vector2 vector2 = base.DirectionTo(Main.MouseWorld) * 6f;
                    int num3 = 5;
                    int num4 = Projectile.NewProjectile(this.GetProjectileSource_Item(sItem), (float)(rectangle.X + rectangle.Width / 2), (float)(rectangle.Y + rectangle.Height / 2), vector2.X, vector2.Y, this.beeType(), this.beeDamage(num3), this.beeKB(0f), this.whoAmI, 0f, 0f, 0f, null);
                    Main.projectile[num4].melee = true;
                }
            }
            if (sItem.type > 0 && this.itemAnimation > 0)
            {
                this.ItemCheck_GetMeleeHitboxParticles(sItem, heldItemFrame);
            }
            if (((sItem.damage >= 0 && sItem.type > 0 && !sItem.noMelee) || sItem.type == 1991 || sItem.type == 3183 || sItem.type == 4821) && this.itemAnimation > 0)
            {
                bool flag7;
                Rectangle rectangle2;
                this.ItemCheck_GetMeleeHitbox(sItem, heldItemFrame, out flag7, out rectangle2);
                if (!flag7)
                {
                    this.ItemCheck_EmitUseVisuals(sItem, rectangle2);
                    if (Main.myPlayer == this.whoAmI && (sItem.type == 1991 || sItem.type == 3183 || sItem.type == 4821))
                    {
                        this.ItemCheck_CatchCritters(sItem, rectangle2);
                    }
                    if (sItem.type == 3183 || sItem.type == 4821)
                    {
                        bool[] array = this.ItemCheck_GetTileCutIgnoreList(sItem);
                        this.ItemCheck_CutTiles(sItem, rectangle2, array, true);
                    }
                    if (sItem.damage > 0)
                    {
                        this.UpdateMeleeHitCooldowns();
                        float num5 = sItem.knockBack;
                        float num6 = 1f;
                        if (this.kbGlove)
{
                            num6 += 1f;
                        }
                        if (this.kbBuff)
{
                            num6 += 0.5f;
                        }
                        num5 *= num6;
                        if (this.inventory[this.selectedItem].type == 3106)
{
                            num5 += num5 * (1f - this.stealth);
                        }
                        bool[] array2 = this.ItemCheck_GetTileCutIgnoreList(sItem);
                        this.ItemCheck_CutTiles(sItem, rectangle2, array2, false);
                        this.ItemCheck_MeleeHitNPCs(sItem, rectangle2, weaponDamage, num5);
                        this.ItemCheck_MeleeHitPVP(sItem, rectangle2, weaponDamage, num5);
                        this.ItemCheck_EmitHammushProjectiles(this.whoAmI, sItem, rectangle2, weaponDamage);
                    }
                }
            }
            if (sItem.type == 5464 && this.itemAnimation == this.itemAnimationMax - 1)
            {
                Vector2 vector3 = Main.MouseWorld - this.MountedCenter;
                this.ChangeDir((vector3.X > 0f) ? 1 : (-1));
                this.itemRotation = (vector3 * (float)this.direction).ToRotation();
                NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(41, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
            }
            if (sItem.type == 5644 && this.ItemAnimationJustStarted)
            {
                if (this.AnyoneToSpectate())
                {
                    IngameUIWindows.CloseAll(false);
                    SoundEngine.PlaySound(SoundID.Item197, -1, -1, 0f, 1f);
                    this.SpectateNextPlayer(1, false);
                    return;
                }
                SoundEngine.PlaySound(SoundID.Item198, -1, -1, 0f, 1f);
                if (Main.netMode == 0)
                {
                    ChatHelper.DisplayMessage(NetworkText.FromKey("Game.SpectateSinglePlayer", new object[0]), ChatColors.ServerMessage, byte.MaxValue);
                    return;
                }
                ChatHelper.DisplayMessage(NetworkText.FromKey("Game.SpectateNoTargets", new object[0]), ChatColors.ServerMessage, byte.MaxValue);
            }
        }
References Terraria.Projectile.active, System.array, Terraria.UI.IngameUIWindows.CloseAll(), Terraria.Item.damage, Terraria.Chat.ChatHelper.DisplayMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.Main.GamepadDisableCursorItemIcon, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Item.holdStyle, Terraria.ID.ItemID.Sets.IsAKite, Terraria.ID.SoundID.Item197, Terraria.ID.SoundID.Item198, Terraria.Main.ItemIconCacheUpdate(), Terraria.Item.knockBack, Terraria.Main.LocalGolfState, Terraria.Item.makeNPC, Terraria.Projectile.melee, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.noMelee, Terraria.Projectile.owner, Terraria.ID.ItemID.Sets.PlaceTileOnAltUse, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.projectile, Terraria.Main.rand, Terraria.GameContent.Golf.GolfState.ResetGolfBall(), Terraria.NetMessage.SendData(), Terraria.Chat.ChatColors.ServerMessage, Terraria.Item.shoot, Terraria.Item.shootsEveryUse, Terraria.ID.ItemID.Sets.ShootsOnUseRelease, Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Item.tileBoost, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Item.type, Terraria.Projectile.type, Terraria.Item.useTime, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Y.