Terraria Decompiled: Terraria.Player.CollideWithNPCs
CollideWithNPCs()
int Terraria.Player.CollideWithNPCs (Rectangle myRect, float Damage, float Knockback, int NPCImmuneTime, int PlayerImmuneTime) inline
Definition at line 18698 of file Player.cs.
        {
            int num = 0;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc = Main.npc[i];
                if (npc.active && !npc.dontTakeDamage && !npc.friendly && npc.immune[this.whoAmI] == 0 && this.CanNPCBeHitByPlayerOrPlayerProjectile(npc, null))
                {
                    Rectangle rect = npc.getRect();
                    if (myRect.Intersects(rect) && (npc.noTileCollide || Collision.CanHit(this.position, this.width, this.height, npc.position, npc.width, npc.height)))
                    {
                        int num2 = this.direction;
                        if (this.velocity.X < 0f)
{
                            num2 = -1;
                        }
                        if (this.velocity.X > 0f)
{
                            num2 = 1;
                        }
                        if (this.whoAmI == Main.myPlayer)
{
                            this.ApplyDamageToNPC(npc, (int)Damage, Knockback, num2, false);
                        }
                        npc.immune[this.whoAmI] = NPCImmuneTime;
                        this.GiveImmuneTimeForCollisionAttack(PlayerImmuneTime);
                        num++;
                        break;
                    }
                }
            }
            return num;
        }
References Terraria.NPC.active, Terraria.Collision.CanHit(), Terraria.GameContent.Damage, Terraria.NPC.dontTakeDamage, Terraria.NPC.friendly, Terraria.NPC.getRect(), Terraria.Entity.height, Terraria.NPC.immune, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Entity.position, and Terraria.Entity.width.