Terraria Decompiled: Terraria.Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck
PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck()
bool Terraria.Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck (bool placed) inline private
Definition at line 39827 of file Player.cs.
        {
            bool flag = this.inventory[this.selectedItem].type == 213 || this.inventory[this.selectedItem].type == 5295;
            if (flag && !placed && Main.tile[Player.tileTargetX, Player.tileTargetY].type == 1 && Main.tile[Player.tileTargetX, Player.tileTargetY].active())
            {
                int num = 0;
                int num2 = 0;
                Point point = base.Center.ToTileCoordinates();
                Dictionary<ushort, int> dictionary = new Dictionary<ushort, int>();
                WorldUtils.Gen(new Point(point.X - 25, point.Y - 25), new Shapes.Rectangle(50, 50), new Actions.TileScanner(new ushort[]
                {
                    182, 515, 180, 513, 179, 512, 183, 516, 181, 514,
                    381, 517, 534, 535, 536, 537, 539, 540, 625, 626,
                    627, 628
                }).Output(dictionary));
                foreach (KeyValuePair<ushort, int> keyValuePair in dictionary)
                {
                    if (keyValuePair.Value > num2)
                    {
                        num2 = keyValuePair.Value;
                        num = (int)keyValuePair.Key;
                    }
                }
                if (num <= 537)
                {
                    switch (num)
                    {
                    case 512:
                        num = 179;
                        break;
                    case 513:
                        num = 180;
                        break;
                    case 514:
                        num = 181;
                        break;
                    case 515:
                        num = 182;
                        break;
                    case 516:
                        num = 183;
                        break;
                    case 517:
                        num = 381;
                        break;
                    default:
                        if (num != 535)
{
                            if (num == 537)
{
                                num = 536;
                            }
                        }
                        else
{
                            num = 534;
                        }
                        break;
                    }
                }
                else if (num != 540)
                {
                    if (num != 626)
                    {
                        if (num == 628)
{
                            num = 627;
                        }
                    }
                    else
                    {
                        num = 625;
                    }
                }
                else
                {
                    num = 539;
                }
                if (num2 == 0)
                {
                    num = Utils.SelectRandom<int>(Main.rand, new int[] { 182, 180, 179, 183, 181 });
                }
                if (num != 0)
                {
                    Main.tile[Player.tileTargetX, Player.tileTargetY].type = (ushort)num;
                    WorldGen.SquareTileFrame(Player.tileTargetX, Player.tileTargetY, true);
                    NetMessage.SendTileSquare(-1, Player.tileTargetX, Player.tileTargetY, TileChangeType.None);
                    placed = true;
                }
            }
            if (flag && !placed && Main.tile[Player.tileTargetX, Player.tileTargetY].type == 38 && Main.tile[Player.tileTargetX, Player.tileTargetY].active())
            {
                int num3 = 0;
                int num4 = 0;
                Point point2 = base.Center.ToTileCoordinates();
                Dictionary<ushort, int> dictionary2 = new Dictionary<ushort, int>();
                WorldUtils.Gen(new Point(point2.X - 25, point2.Y - 25), new Shapes.Rectangle(50, 50), new Actions.TileScanner(new ushort[]
                {
                    182, 515, 180, 513, 179, 512, 183, 516, 181, 514,
                    381, 517, 534, 535, 536, 537, 539, 540, 625, 626,
                    627, 628
                }).Output(dictionary2));
                foreach (KeyValuePair<ushort, int> keyValuePair2 in dictionary2)
                {
                    if (keyValuePair2.Value > num4)
                    {
                        num4 = keyValuePair2.Value;
                        num3 = (int)keyValuePair2.Key;
                    }
                }
                if (num3 <= 534)
                {
                    switch (num3)
                    {
                    case 179:
                        num3 = 512;
                        break;
                    case 180:
                        num3 = 513;
                        break;
                    case 181:
                        num3 = 514;
                        break;
                    case 182:
                        num3 = 515;
                        break;
                    case 183:
                        num3 = 516;
                        break;
                    default:
                        if (num3 != 381)
{
                            if (num3 == 534)
{
                                num3 = 535;
                            }
                        }
                        else
{
                            num3 = 517;
                        }
                        break;
                    }
                }
                else if (num3 <= 539)
                {
                    if (num3 != 536)
                    {
                        if (num3 == 539)
{
                            num3 = 540;
                        }
                    }
                    else
                    {
                        num3 = 537;
                    }
                }
                else if (num3 != 625)
                {
                    if (num3 == 627)
                    {
                        num3 = 628;
                    }
                }
                else
                {
                    num3 = 626;
                }
                if (num4 == 0)
                {
                    num3 = Utils.SelectRandom<int>(Main.rand, new int[] { 515, 513, 512, 516, 514 });
                }
                if (num3 != 0)
                {
                    Main.tile[Player.tileTargetX, Player.tileTargetY].type = (ushort)num3;
                    WorldGen.SquareTileFrame(Player.tileTargetX, Player.tileTargetY, true);
                    NetMessage.SendTileSquare(-1, Player.tileTargetX, Player.tileTargetY, TileChangeType.None);
                    placed = true;
                }
            }
            return placed;
        }
References Terraria.Tile.active(), System.dictionary, Terraria.WorldBuilding.WorldUtils.Gen(), int, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.WorldBuilding.Actions.TileScanner.Output(), Terraria.Main.rand, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Tile.type, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.