Terraria Decompiled: Terraria.Player.GetSmartPlatformSlope
GetSmartPlatformSlope()
static int Terraria.Player.GetSmartPlatformSlope (int x, int y) inline static
Definition at line 39682 of file Player.cs.
        {
            int num = 0;
            int num2 = 0;
            Tile tile = Main.tile[x, y - 1];
            bool flag = tile.active() && TileID.Sets.Platforms[(int)tile.type];
            tile = Main.tile[x - 1, y - 1];
            if (tile.active() && TileID.Sets.Platforms[(int)tile.type] && tile.slope() != 2)
            {
                num += ((tile.slope() == 1) ? 2 : ((!flag) ? 1 : 0));
            }
            tile = Main.tile[x + 1, y - 1];
            if (tile.active() && TileID.Sets.Platforms[(int)tile.type] && tile.slope() != 1)
            {
                num2 += ((tile.slope() == 2) ? 2 : ((!flag) ? 1 : 0));
            }
            tile = Main.tile[x, y + 1];
            bool flag2 = tile.active() && TileID.Sets.Platforms[(int)tile.type];
            tile = Main.tile[x - 1, y + 1];
            if (tile.active() && TileID.Sets.Platforms[(int)tile.type] && tile.slope() != 1)
            {
                num2 += ((tile.slope() == 2) ? 2 : ((!flag2) ? 1 : 0));
            }
            tile = Main.tile[x + 1, y + 1];
            if (tile.active() && TileID.Sets.Platforms[(int)tile.type] && tile.slope() != 2)
            {
                num += ((tile.slope() == 1) ? 2 : ((!flag2) ? 1 : 0));
            }
            tile = Main.tile[x - 1, y];
            if (WorldGen.SolidTile(tile))
            {
                num++;
            }
            tile = Main.tile[x + 1, y];
            if (WorldGen.SolidTile(tile))
            {
                num2++;
            }
            int num3 = 0;
            if (num > num2)
            {
                num3 = 1;
            }
            if (num2 > num)
            {
                num3 = 2;
            }
            tile = Main.tile[x - 1, y];
            if (tile.active() && TileID.Sets.Platforms[(int)tile.type])
            {
                num3 = 0;
            }
            tile = Main.tile[x + 1, y];
            if (tile.active() && TileID.Sets.Platforms[(int)tile.type])
            {
                num3 = 0;
            }
            return num3;
        }
References Terraria.Tile.active(), int, Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform().