Terraria Decompiled: Terraria.Player.PlaceThing_ValidTileForReplacement
PlaceThing_ValidTileForReplacement()
bool Terraria.Player.PlaceThing_ValidTileForReplacement () inline private
Definition at line 38772 of file Player.cs.
        {
            int createTile = this.HeldItem.createTile;
            int placeStyle = this.HeldItem.placeStyle;
            if (this.UsingBiomeTorches && createTile == 4)
            {
                this.BiomeTorchPlaceStyle(ref createTile, ref placeStyle, false);
            }
            if (this.UsingBiomeTorches && createTile == 215)
            {
                this.BiomeCampfirePlaceStyle(ref createTile, ref placeStyle);
            }
            Tile tile = Main.tile[Player.tileTargetX, Player.tileTargetY];
            if (ItemID.Sets.SortingPriorityRopes[this.HeldItem.type] != -1)
            {
                return false;
            }
            if (Main.tileMoss[createTile])
            {
                return false;
            }
            if (TileID.Sets.DoesntPlaceWithTileReplacement[createTile])
            {
                return false;
            }
            if (TileID.Sets.DoesntGetReplacedWithTileReplacement[(int)tile.type])
            {
                return false;
            }
            if (!this.PlaceThing_CheckSpecificValidtyCaseForBlockSwap(createTile, (int)tile.type, (int)tile.liquidType(), (int)tile.liquid))
            {
                return false;
            }
            if (!this.PlaceThing_CheckPlatformSolidityForBlockSwap(createTile, (int)tile.type, Player.tileTargetX, Player.tileTargetY))
            {
                return false;
            }
            if (Main.tileCut[(int)tile.type])
            {
                return false;
            }
            if (TileID.Sets.Platforms[(int)tile.type] && (int)tile.type == createTile)
            {
                return (int)tile.frameY != placeStyle * 18;
            }
            if (TileID.Sets.Torches[(int)tile.type])
            {
                if (tile.liquid > 0)
                {
                    if (createTile == 4 && placeStyle != 8 && placeStyle != 11 && placeStyle != 17)
                    {
                        return false;
                    }
                    TileObjectData tileData = TileObjectData.GetTileData(createTile, placeStyle, 0);
                    if (tileData != null && tileData.WaterPlacement != LiquidPlacement.Allowed)
                    {
                        return false;
                    }
                }
                if ((int)tile.type == createTile)
                {
                    return (int)tile.frameY != placeStyle * 22;
                }
            }
            if (TileID.Sets.Campfires[(int)tile.type])
            {
                if (tile.liquid > 0)
                {
                    TileObjectData tileData2 = TileObjectData.GetTileData(createTile, placeStyle, 0);
                    if (tileData2 != null && tileData2.WaterPlacement != LiquidPlacement.Allowed)
                    {
                        return false;
                    }
                }
                if ((int)tile.type == createTile)
                {
                    return (int)(tile.frameX / 54) != placeStyle;
                }
            }
            if (TileID.Sets.BasicChest[(int)tile.type] && TileID.Sets.BasicChest[createTile])
            {
                return (int)(tile.frameX / 36) != placeStyle || (int)tile.type != createTile;
            }
            if (TileID.Sets.BasicDresser[(int)tile.type] && TileID.Sets.BasicDresser[createTile])
            {
                return (int)(tile.frameX / 54) != placeStyle || (int)tile.type != createTile;
            }
            bool flag = false;
            if (Main.tileRope[(int)tile.type])
            {
                flag = createTile == 314 || createTile == 380 || TileID.Sets.Platforms[createTile];
                if (!flag)
                {
                    return false;
                }
            }
            if (!flag && Main.tileFrameImportant[createTile] && !TileID.Sets.Platforms[createTile])
            {
                return false;
            }
            if ((int)Main.tile[Player.tileTargetX, Player.tileTargetY].type == createTile)
            {
                return false;
            }
            if (Main.tile[Player.tileTargetX, Player.tileTargetY].type == 230 && Main.getGoodWorld)
            {
                return false;
            }
            if (!TileID.Sets.IgnoresTileReplacementDropCheckWhenBeingPlaced[createTile])
            {
                int num;
                int num2;
                int num3;
                int num4;
                bool flag2;
                WorldGen.KillTile_GetItemDrops(Player.tileTargetX, Player.tileTargetY, tile, out num, out num2, out num3, out num4, out flag2, false);
                if (num == this.HeldItem.type)
                {
                    return false;
                }
            }
            return WorldGen.WouldTileReplacementWork((int)((ushort)createTile), Player.tileTargetX, Player.tileTargetY);
        }
References Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicDresser, Terraria.ID.TileID.Sets.Campfires, Terraria.ID.TileID.Sets.DoesntGetReplacedWithTileReplacement, Terraria.ID.TileID.Sets.DoesntPlaceWithTileReplacement, Terraria.Main.getGoodWorld, Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.ID.TileID.Sets.IgnoresTileReplacementDropCheckWhenBeingPlaced, Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.ID.TileID.Sets.Platforms, Terraria.ID.ItemID.Sets.SortingPriorityRopes, Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileFrameImportant, Terraria.Main.tileMoss, Terraria.Main.tileRope, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.ID.TileID.Sets.Torches, Terraria.Tile.type, Terraria.ObjectData.TileObjectData.WaterPlacement, and Terraria.WorldGen.WouldTileReplacementWork().