Terraria Decompiled: Terraria.Player.ItemCheck_CatchCritters
ItemCheck_CatchCritters()
void Terraria.Player.ItemCheck_CatchCritters (Item sItem, Rectangle itemRectangle) inline private
Definition at line 43924 of file Player.cs.
        {
            bool flag = sItem.type == 3183 || sItem.type == 4821;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].catchItem > 0)
                {
                    Rectangle rectangle = new Rectangle((int)Main.npc[i].position.X, (int)Main.npc[i].position.Y, Main.npc[i].width, Main.npc[i].height);
                    if (itemRectangle.Intersects(rectangle))
                    {
                        if (!flag && ItemID.Sets.IsLavaBait[(int)Main.npc[i].catchItem])
{
                            if (Main.myPlayer == this.whoAmI && this.Hurt(PlayerDeathReason.ByNPC(i), 1, (Main.npc[i].Center.X < base.Center.X) ? 1 : (-1), false, false, false, ImmunityCooldownID.WrongBugNet, true) > 0.0 && !this.dead)
{
                                this.AddBuff(24, 300, false);
                            }
                        }
                        else if (Main.npc[i].type == 585 || Main.npc[i].type == 583 || Main.npc[i].type == 584)
{
                            if (Main.npc[i].ai[2] <= 1f)
{
                                NPC.CatchNPC(i, this.whoAmI);
                            }
                        }
                        else
{
                            NPC.CatchNPC(i, this.whoAmI);
                        }
                    }
                }
            }
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.DataStructures.PlayerDeathReason.ByNPC(), Terraria.NPC.catchItem, Terraria.NPC.CatchNPC(), Terraria.Entity.Center, Terraria.Entity.height, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.ID.ItemID.Sets.IsLavaBait, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Entity.position, Terraria.NPC.type, Terraria.Entity.width, Terraria.ID.ImmunityCooldownID.WrongBugNet, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.