Terraria Decompiled: Terraria.Player.TryLandingOnDetonator
TryLandingOnDetonator()
void Terraria.Player.TryLandingOnDetonator () inline private
Definition at line 33577 of file Player.cs.
        {
            if (this.whoAmI != Main.myPlayer)
            {
                return;
            }
            if (this.velocity.Y >= 3f)
            {
                Point point = (base.Bottom + new Vector2(0f, 0.01f)).ToTileCoordinates();
                Tile tileSafely = Framing.GetTileSafely(point.X, point.Y);
                if (tileSafely.active() && tileSafely.type == 411 && tileSafely.frameY == 0 && tileSafely.frameX < 36)
                {
                    Wiring.HitSwitch(point.X, point.Y);
                    NetMessage.SendData(59, -1, -1, null, point.X, (float)point.Y, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.Tile.active(), Terraria.Framing.GetTileSafely(), Terraria.Wiring.HitSwitch(), Terraria.Main.myPlayer, Terraria.NetMessage.SendData(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.