Terraria Decompiled: Terraria.Player.PetAnimal
PetAnimal()
void Terraria.Player.PetAnimal (PlayerPettingInfo info) inline
Definition at line 32058 of file Player.cs.
        {
            Entity entity;
            if (!info.TryGetTarget(out entity))
            {
                return;
            }
            Vector2 vector = base.Bottom;
            if (entity != null)
            {
                vector = (entity.Bottom + info.offsetFromPet).Floor();
                Vector2 vector2 = vector - base.Bottom;
                if (!this.CanSnapToPosition(vector2))
                {
                    return;
                }
                if (!WorldGen.SolidTileAllowBottomSlope((int)vector.X / 16, (int)vector.Y / 16))
                {
                    return;
                }
            }
            if (this.petting.isPetting && base.Bottom == vector)
            {
                this.StopPettingAnimal();
                return;
            }
            this.StopVanityActions(true);
            this.RemoveAllGrapplingHooks();
            if (!info.mount && this.mount.Active)
            {
                this.mount.TryDismount(this);
            }
            base.Bottom = vector;
            int num = Math.Sign(-info.offsetFromPet.X);
            if (num == 0)
            {
                num = this.direction;
            }
            this.ChangeDir(num);
            this.velocity = Vector2.Zero;
            this.gravDir = 1f;
            this.petting = info;
            this.petting.isPetting = true;
            if (this.whoAmI == Main.myPlayer)
            {
                AchievementsHelper.HandleSpecialEvent(this, 21);
            }
        }
References Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), System.info, Terraria.Main.myPlayer, System.Math.Sign(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.TryPetting().