Terraria Decompiled: Terraria.Player.ApplyItemPositionOffsetFromMount
ApplyItemPositionOffsetFromMount()
void Terraria.Player.ApplyItemPositionOffsetFromMount (ref Vector2 pos) inline
Definition at line 50759 of file Player.cs.
        {
            if (!this.mount.Active)
            {
                return;
            }
            int num = this.bodyFrame.Y / this.bodyFrame.Height;
            Vector2 vector = Vector2.Zero;
            Item heldItem = this.HeldItem;
            bool flag = this.itemAnimation > 0;
            bool flag2 = !flag && heldItem.holdStyle > 0;
            if (!flag && !flag2)
            {
                return;
            }
            bool flag3 = heldItem.useStyle == 5;
            int num2 = this.heldProj;
            bool flag4 = heldItem.useStyle == 2;
            bool flag5 = heldItem.useStyle == 9;
            bool flag6 = heldItem.fishingPole != 0;
            bool flag7 = heldItem.useStyle == 14;
            bool flag8 = heldItem.useStyle == 8;
            bool flag9 = heldItem.type > 0 && ItemID.Sets.Yoyo[heldItem.type];
            bool flag10 = heldItem.useStyle == 11;
            bool flag11 = heldItem.type == 3542;
            bool flag12 = heldItem.type > 0 && ItemID.Sets.IsAKite[heldItem.type];
            bool flag13 = heldItem.holdStyle == 1;
            bool flag14 = heldItem.holdStyle == 2;
            bool flag15 = heldItem.holdStyle == 5;
            if (this.mount.Type == 54)
            {
                if (flag4)
                {
                    if (flag)
                    {
                        vector += new Vector2(7f, -4f) * this.Directions;
                    }
                    else
                    {
                        vector += new Vector2(3f, 2f) * this.Directions;
                    }
                }
                else if (flag6)
                {
                    vector += new Vector2(-2f, 0f) * this.Directions;
                }
                else if (flag5)
                {
                    if (flag)
                    {
                        vector += new Vector2(14f, -10f) * this.Directions;
                    }
                    else
                    {
                        vector += new Vector2(3f, 2f) * this.Directions;
                    }
                }
                else if (flag10)
                {
                    if (flag)
                    {
                        vector += new Vector2(4f, 0f) * this.Directions;
                    }
                    else
                    {
                        vector += new Vector2(1f, 0f) * this.Directions;
                    }
                }
                else if (flag8)
                {
                    vector += new Vector2(6f, 0f) * this.Directions;
                }
                else if (flag7)
                {
                    if (flag)
                    {
                        vector += new Vector2(-6f, 6f) * this.Directions;
                    }
                    else
                    {
                        vector += new Vector2(-10f, 10f) * this.Directions;
                    }
                }
                else if (flag12)
                {
                    vector += new Vector2(4f, -4f) * this.Directions;
                }
                else if (flag15)
                {
                    vector += new Vector2(6f, 0f) * this.Directions;
                }
                else if (flag13 && !flag)
                {
                    vector += new Vector2(1f, 4f) * this.Directions;
                }
                else if (flag14)
                {
                    if (flag && heldItem.type == 186)
                    {
                        vector += new Vector2(-4f, 0f).RotatedBy((double)(pos - base.Center).ToRotation(), Vector2.Zero);
                    }
                    else
                    {
                        vector += new Vector2(6f, 0f) * this.Directions;
                    }
                }
                else if (flag9)
                {
                    switch (num)
                    {
                    case 2:
                        vector += new Vector2(10f, -10f) * this.Directions;
                        break;
                    case 3:
                        vector += new Vector2(8f, 0f) * this.Directions;
                        break;
                    case 4:
                        vector += new Vector2(2f, 2f) * this.Directions;
                        break;
                    }
                }
                else if (flag11)
                {
                    switch (num)
                    {
                    case 2:
                        vector += new Vector2(-10f, 0f) * this.Directions;
                        break;
                    case 3:
                        vector += new Vector2(10f, 0f) * this.Directions;
                        break;
                    case 4:
                        vector += new Vector2(10f, 0f) * this.Directions;
                        break;
                    }
                }
                else if (flag3)
                {
                    vector += new Vector2(4f, 0f) * this.Directions;
                }
                else
                {
                    switch (num)
                    {
                    case 1:
                        vector += new Vector2(1f, -1f) * this.Directions;
                        break;
                    case 2:
                        vector += new Vector2(4f, 2f) * this.Directions;
                        break;
                    case 3:
                        vector += new Vector2(2f, 0f) * this.Directions;
                        break;
                    }
                }
            }
            pos += vector;
        }
References Terraria.ID.ItemID.Sets.IsAKite, Terraria.Item.type, Terraria.ID.ItemID.Sets.Yoyo, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.DataStructures.PlayerDrawSet.AdjustmentsForVelociraptorMount(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProjDirect(), and Terraria.Main.GetPlayerArmPosition().