Terraria Decompiled: Terraria.Player.ItemCheck_UseTorchGodsFavor
ItemCheck_UseTorchGodsFavor()
void Terraria.Player.ItemCheck_UseTorchGodsFavor (Item sItem) inline private
Definition at line 44493 of file Player.cs.
        {
            if (sItem.type == 5043 && this.itemAnimation > 0 && !this.unlockedBiomeTorches && this.ItemTimeIsZero)
            {
                this.ApplyItemTime(sItem);
                this.unlockedBiomeTorches = true;
                this.UsingBiomeTorches = true;
                AchievementsHelper.HandleSpecialEvent(this, 24);
                if (Main.netMode == 0)
                {
                    NPC npc = new NPC();
                    npc.SetDefaults(664, default(NPCSpawnParams));
                    Main.BestiaryTracker.Kills.RegisterKill(npc);
                }
                NetMessage.SendData(4, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(51, -1, -1, null, this.whoAmI, 5f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Main.BestiaryTracker, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Main.netMode, Terraria.Enums.NPC, Terraria.NetMessage.SendData(), Terraria.NPC.SetDefaults(), and Terraria.Item.type.