Terraria Decompiled: Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids
PlaceThing_Tiles_PlaceIt_UnslopeForSolids()
void Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids () inline private
Definition at line 39425 of file Player.cs.
        {
            if (this.inventory[this.selectedItem].createTile < 0)
            {
                return;
            }
            if (Main.tileSolid[this.inventory[this.selectedItem].createTile] && !TileID.Sets.Platforms[this.inventory[this.selectedItem].createTile])
            {
                int num = Player.tileTargetX;
                int num2 = Player.tileTargetY + 1;
                if (Main.tile[num, num2] != null && !TileID.Sets.Platforms[(int)Main.tile[num, num2].type] && (Main.tile[num, num2].topSlope() || Main.tile[num, num2].halfBrick()))
                {
                    WorldGen.SlopeTile(num, num2, 0, false, true);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 14, (float)num, (float)num2, 0f, 0, 0, 0);
                    }
                }
                num = Player.tileTargetX;
                num2 = Player.tileTargetY - 1;
                if (Main.tile[num, num2] != null && !TileID.Sets.Platforms[(int)Main.tile[num, num2].type] && Main.tile[num, num2].bottomSlope())
                {
                    WorldGen.SlopeTile(num, num2, 0, false, true);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 14, (float)num, (float)num2, 0f, 0, 0, 0);
                    }
                }
            }
        }
References Terraria.Tile.bottomSlope(), Terraria.Tile.halfBrick(), Terraria.Main.netMode, Terraria.ID.TileID.Sets.Platforms, Terraria.NetMessage.SendData(), Terraria.WorldGen.SlopeTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Player.tileTargetX, Terraria.Tile.topSlope(), and Terraria.Tile.type.