Terraria Decompiled: Terraria.Player.UpdateArmorSetsOld
UpdateArmorSetsOld()
void Terraria.Player.UpdateArmorSetsOld (int i) inline
Definition at line 13909 of file Player.cs.
        {
            this.setBonus = "";
            if (this.body == 67 && this.legs == 56 && this.head >= 103 && this.head <= 105)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Shroomite");
                this.shroomiteStealth = true;
            }
            if ((this.head == 52 && this.body == 32 && this.legs == 31) || (this.head == 53 && this.body == 33 && this.legs == 32) || (this.head == 54 && this.body == 34 && this.legs == 33) || (this.head == 55 && this.body == 35 && this.legs == 34) || (this.head == 71 && this.body == 47 && this.legs == 43) || (this.head == 166 && this.body == 173 && this.legs == 108) || (this.head == 167 && this.body == 174 && this.legs == 109))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Wood");
                this.statDefense++;
            }
            if (this.head == 278 && this.body == 246 && this.legs == 234)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.AshWood");
                this.ashWoodBonus = true;
            }
            if ((this.head == 1 && this.body == 1 && this.legs == 1) || ((this.head == 72 || this.head == 2) && this.body == 2 && this.legs == 2) || (this.head == 47 && this.body == 28 && this.legs == 27))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.MetalTier1");
                this.statDefense += 2;
            }
            if ((this.head == 3 && this.body == 3 && this.legs == 3) || ((this.head == 73 || this.head == 4) && this.body == 4 && this.legs == 4) || (this.head == 48 && this.body == 29 && this.legs == 28) || (this.head == 49 && this.body == 30 && this.legs == 29))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.MetalTier2");
                this.statDefense += 3;
            }
            if (this.head == 50 && this.body == 31 && this.legs == 30)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Platinum");
                this.statDefense += 4;
            }
            if (this.head == 112 && this.body == 75 && this.legs == 64)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Pumpkin");
                this.meleeDamage += 0.1f;
                this.magicDamage += 0.1f;
                this.rangedDamage += 0.1f;
                this.minionDamage += 0.1f;
            }
            if (this.head == 180 && this.body == 182 && this.legs == 122)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Gladiator");
                this.noKnockback = true;
            }
            if (this.head == 22 && this.body == 14 && this.legs == 14)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Ninja");
                this.moveSpeed += 0.2f;
            }
            if (this.head == 188 && this.body == 189 && this.legs == 129)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Fossil");
                this.ammoCost80 = true;
            }
            if ((this.head == 75 || this.head == 7) && this.body == 7 && this.legs == 7)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Bone");
                this.rangedCrit += 10;
            }
            if (this.head == 157 && this.body == 105 && this.legs == 98)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.BeetleDamage");
                this.ApplySetBonus_BeetleDamage();
            }
            else if (this.head == 157 && this.body == 106 && this.legs == 98)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.BeetleDefense");
                this.ApplySetBonus_BeetleDefense();
            }
            this.UpdateArmorSets_Always_Beetle();
            if (this.head == 14 && ((this.body >= 58 && this.body <= 63) || this.body == 167 || this.body == 213))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Wizard");
                this.magicCrit += 10;
            }
            if (this.head == 159 && ((this.body >= 58 && this.body <= 63) || this.body == 167 || this.body == 213))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.MagicHat");
                this.statManaMax2 += 60;
            }
            if ((this.head == 5 || this.head == 74) && (this.body == 5 || this.body == 48) && (this.legs == 5 || this.legs == 44))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.ShadowScale");
                this.shadowArmor = true;
            }
            if (this.head == 57 && this.body == 37 && this.legs == 35)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Crimson");
                this.crimsonRegen = true;
            }
            if (this.head == 101 && this.body == 66 && this.legs == 55)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.SpectreHealing");
                this.ghostHeal = true;
                this.magicDamage -= 0.4f;
            }
            if (this.head == 156 && this.body == 66 && this.legs == 55)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.SpectreDamage");
                this.ghostHurt = true;
            }
            if (this.head == 6 && this.body == 6 && this.legs == 6)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Meteor");
                this.spaceGun = true;
            }
            if (this.head == 46 && this.body == 27 && this.legs == 26)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Frost");
                this.frostBurn = true;
                this.meleeDamage += 0.1f;
                this.rangedDamage += 0.1f;
            }
            if ((this.head == 76 || this.head == 8) && (this.body == 49 || this.body == 8) && (this.legs == 45 || this.legs == 8))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Jungle");
                this.manaCost -= 0.16f;
            }
            if (this.head == 9 && this.body == 9 && this.legs == 9)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Molten");
                this.meleeDamage += 0.1f;
                this.fireWalk = true;
                if (!this.vampireBurningInSunlight)
                {
                    this.buffImmune[24] = true;
                }
            }
            if ((this.head == 58 || this.head == 77) && (this.body == 38 || this.body == 50) && (this.legs == 36 || this.legs == 46))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Snow");
                this.buffImmune[46] = true;
                this.buffImmune[47] = true;
            }
            if ((this.head == 11 || this.head == 285 || this.head == 216) && (this.body == 20 || this.body == 252) && (this.legs == 19 || this.legs == 240))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Mining");
                this.pickSpeed -= 0.1f;
            }
            if (this.head == 78 && this.body == 51 && this.legs == 47)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.ChlorophyteMelee");
                this.AddBuff(60, 5, false);
                this.endurance += 0.05f;
            }
            else if (this.head == 283 && this.body == 51 && this.legs == 47)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.ChlorophyteSummon");
                this.AddBuff(60, 5, false);
                this.maxMinions += 2;
            }
            else if ((this.head == 80 || this.head == 79) && this.body == 51 && this.legs == 47)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Chlorophyte");
                this.AddBuff(60, 5, false);
                this.setChlorophyte = true;
            }
            this.UpdateArmorSets_Always_Chlorophyte();
            if ((this.head == 161 || this.head == 286) && (this.body == 169 || this.body == 253) && (this.legs == 104 || this.legs == 241))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Angler");
                this.anglerSetSpawnReduction = true;
            }
            if (this.head == 70 && this.body == 46 && this.legs == 42)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Cactus");
                this.cactusThorns = true;
            }
            if (this.head == 99 && this.body == 65 && this.legs == 54)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Turtle");
                this.endurance += 0.15f;
                this.thorns = 1f;
                this.turtleThorns = true;
            }
            if (this.body == 17 && this.legs == 16)
            {
                if (this.head == 29)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.CobaltCaster");
                    this.manaCost -= 0.14f;
                }
                else if (this.head == 30)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.CobaltMelee");
                    this.meleeSpeed += 0.15f;
                }
                else if (this.head == 31)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.CobaltRanged");
                    this.ammoCost80 = true;
                }
            }
            if (this.body == 18 && this.legs == 17)
            {
                if (this.head == 32)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.MythrilCaster");
                    this.manaCost -= 0.17f;
                }
                else if (this.head == 33)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.MythrilMelee");
                    this.meleeCrit += 10;
                }
                else if (this.head == 34)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.MythrilRanged");
                    this.ammoCost80 = true;
                }
            }
            if (this.body == 19 && this.legs == 18)
            {
                if (this.head == 35)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.AdamantiteCaster");
                    this.manaCost -= 0.19f;
                }
                else if (this.head == 36)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.AdamantiteMelee");
                    this.meleeSpeed += 0.2f;
                    this.moveSpeed += 0.2f;
                }
                else if (this.head == 37)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.AdamantiteRanged");
                    this.ammoCost75 = true;
                }
            }
            if (this.body == 54 && this.legs == 49 && (this.head == 83 || this.head == 84 || this.head == 85))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Palladium");
                this.onHitRegen = true;
            }
            if (this.body == 55 && this.legs == 50 && (this.head == 86 || this.head == 87 || this.head == 88))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Orichalcum");
                this.onHitPetal = true;
            }
            if (this.body == 56 && this.legs == 51)
            {
                bool flag = false;
                if (this.head == 91)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.Titanium");
                    flag = true;
                }
                else if (this.head == 89)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.Titanium");
                    flag = true;
                }
                else if (this.head == 90)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.Titanium");
                    flag = true;
                }
                if (flag)
                {
                    this.onHitTitaniumStorm = true;
                }
            }
            if ((this.body == 24 || this.body == 229) && (this.legs == 23 || this.legs == 212) && (this.head == 42 || this.head == 41 || this.head == 43 || this.head == 254 || this.head == 257 || this.head == 256 || this.head == 255 || this.head == 258))
            {
                if (this.head == 254 || this.head == 258)
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.HallowedSummoner");
                    this.maxMinions += 2;
                }
                else
                {
                    this.setBonus = Language.GetTextValue("ArmorSetBonus.Hallowed");
                }
                this.onHitDodge = true;
            }
            if (this.head == 261 && this.body == 230 && this.legs == 213)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.CrystalNinja");
                this.rangedDamage += 0.1f;
                this.meleeDamage += 0.1f;
                this.magicDamage += 0.1f;
                this.minionDamage += 0.1f;
                this.rangedCrit += 10;
                this.meleeCrit += 10;
                this.magicCrit += 10;
                this.dashType = 5;
            }
            if (this.head == 82 && this.body == 53 && this.legs == 48)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Tiki");
                this.maxMinions++;
                this.whipRangeMultiplier += 0.2f;
            }
            if (this.head == 134 && this.body == 95 && this.legs == 79)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Spooky");
                this.minionDamage += 0.25f;
            }
            if (this.head == 160 && this.body == 168 && this.legs == 103)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Bee");
                this.minionDamage += 0.1f;
                if (this.itemAnimation > 0 && this.inventory[this.selectedItem].type == 1121)
                {
                    AchievementsHelper.HandleSpecialEvent(this, 3);
                }
            }
            if (this.head == 162 && this.body == 170 && this.legs == 105)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Spider");
                this.minionDamage += 0.12f;
            }
            if (this.head == 171 && this.body == 177 && this.legs == 112)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Solar");
                this.ApplySetBonus_Solar();
            }
            this.UpdateArmorSets_Always_Solar();
            if (this.head == 169 && this.body == 175 && this.legs == 110)
            {
                this.setVortex = true;
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Vortex", Language.GetTextValue(Main.ReversedUpDownArmorSetBonuses ? "Key.UP" : "Key.DOWN"));
            }
            this.UpdateArmorSets_Always_Vortex();
            if (this.head == 170 && this.body == 176 && this.legs == 111)
            {
                if (this.nebulaCD > 0)
                {
                    this.nebulaCD--;
                }
                this.setNebula = true;
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Nebula");
            }
            if (this.head == 189 && this.body == 190 && this.legs == 130)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Stardust", Language.GetTextValue(Main.ReversedUpDownArmorSetBonuses ? "Key.UP" : "Key.DOWN"));
                this.ApplySetBonus_Stardust();
            }
            this.UpdateArmorSets_Always_Stardust();
            if (this.head == 200 && this.body == 198 && this.legs == 142)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.Forbidden", Language.GetTextValue(Main.ReversedUpDownArmorSetBonuses ? "Key.UP" : "Key.DOWN"));
                this.setForbidden = true;
                this.UpdateForbiddenSetLock();
                Lighting.AddLight(base.Center, 0.8f, 0.7f, 0.2f);
            }
            if (this.head == 204 && this.body == 201 && this.legs == 145)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.SquireTier2");
                this.setSquireT2 = true;
                this.maxTurrets++;
            }
            if (this.head == 203 && this.body == 200 && this.legs == 144)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.ApprenticeTier2");
                this.setApprenticeT2 = true;
                this.maxTurrets++;
            }
            if (this.head == 205 && this.body == 202 && (this.legs == 147 || this.legs == 146))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.HuntressTier2");
                this.setHuntressT2 = true;
                this.maxTurrets++;
            }
            if (this.head == 206 && this.body == 203 && this.legs == 148)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.MonkTier2");
                this.setMonkT2 = true;
                this.maxTurrets++;
            }
            if (this.head == 210 && this.body == 204 && this.legs == 152)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.SquireTier3");
                this.setSquireT3 = true;
                this.setSquireT2 = true;
                this.maxTurrets++;
            }
            if (this.head == 211 && this.body == 205 && this.legs == 153)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.ApprenticeTier3");
                this.setApprenticeT3 = true;
                this.setApprenticeT2 = true;
                this.maxTurrets++;
            }
            if (this.head == 212 && this.body == 206 && (this.legs == 154 || this.legs == 155))
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.HuntressTier3");
                this.setHuntressT3 = true;
                this.setHuntressT2 = true;
                this.maxTurrets++;
            }
            if (this.head == 213 && this.body == 207 && this.legs == 156)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.MonkTier3");
                this.setMonkT3 = true;
                this.setMonkT2 = true;
                this.maxTurrets++;
            }
            if (this.head == 185 && this.body == 187 && this.legs == 127)
            {
                this.setBonus = Language.GetTextValue("ArmorSetBonus.ObsidianOutlaw");
                this.minionDamage += 0.15f;
                this.whipRangeMultiplier += 0.3f;
                float num = 1.15f;
                float num2 = 1f / num;
                this.whipUseTimeMultiplier *= num2;
            }
            this.ApplyArmorSoundAndDustChanges();
        }
References Terraria.Lighting.AddLight(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), and Terraria.Main.ReversedUpDownArmorSetBonuses.