Terraria Decompiled: Terraria.Player.ItemCheck_ManageRightClickFeatures
ItemCheck_ManageRightClickFeatures()
void Terraria.Player.ItemCheck_ManageRightClickFeatures () inline
Definition at line 30141 of file Player.cs.
        {
            bool flag = this.selectedItem != 58 && this.controlUseTile && Main.myPlayer == this.whoAmI && !this.tileInteractionHappened && this.releaseUseItem && !this.controlUseItem && !this.mouseInterface && !CaptureManager.Instance.Active && (!Main.mouseRightRelease || !Main.HoveringAnInteractable) && !Main.LocalPlayerHasPendingInventoryActions();
            bool flag2 = flag;
            if (!ItemID.Sets.ItemsThatAllowRepeatedRightClick[this.inventory[this.selectedItem].type] && !Main.mouseRightRelease)
            {
                flag2 = false;
            }
            if (flag2 && this.altFunctionUse == 0 && this.itemTime == 0 && this.itemAnimation == 0)
            {
                int num = -1;
                int num2 = 7;
                int type = this.inventory[this.selectedItem].type;
                if (type <= 5309)
                {
                    if (type <= 4131)
                    {
                        if (type != 2611)
{
                            if (type == 4131)
{
                                num = 5325;
                            }
                        }
                        else
{
                            num = 5526;
                        }
                    }
                    else if (type != 4346)
                    {
                        if (type != 4767)
{
                            if (type == 5309)
{
                                num = 5454;
                            }
                        }
                        else
{
                            num = 5453;
                        }
                    }
                    else
                    {
                        num = 5391;
                        num2 = 22;
                    }
                }
                else if (type <= 5391)
                {
                    switch (type)
                    {
                    case 5323:
                        num = 5455;
                        break;
                    case 5324:
                        num = 5329;
                        num2 = 22;
                        break;
                    case 5325:
                        num = 4131;
                        break;
                    case 5326:
                    case 5327:
                    case 5328:
                        break;
                    case 5329:
                        num = 5330;
                        num2 = 22;
                        break;
                    case 5330:
                        num = 5324;
                        num2 = 22;
                        break;
                    default:
                        switch (type)
{
                        case 5358:
                            num = 5360;
                            num2 = 22;
                            break;
                        case 5359:
                            num = 5358;
                            num2 = 22;
                            break;
                        case 5360:
                            num = 5361;
                            num2 = 22;
                            break;
                        case 5361:
                            num = 5359;
                            num2 = 22;
                            break;
                        default:
                            if (type == 5391)
{
                                num = 4346;
                                num2 = 22;
                            }
                            break;
                        }
                        break;
                    }
                }
                else if (type != 5437)
                {
                    switch (type)
                    {
                    case 5453:
                        num = 4767;
                        break;
                    case 5454:
                        num = 5309;
                        break;
                    case 5455:
                        num = 5323;
                        break;
                    default:
                        if (type == 5526)
{
                            num = 2611;
                        }
                        break;
                    }
                }
                else
                {
                    num = 5358;
                    num2 = 22;
                }
                if (num != -1)
                {
                    this.releaseUseTile = false;
                    Main.mouseRightRelease = false;
                    SoundEngine.PlaySound(num2, -1, -1, 1, 1f, 0f);
                    this.inventory[this.selectedItem].ChangeItemType(num);
                }
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].type == 3384)
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].type == 3858)
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].type == 4673)
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].type == 5667)
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].type == 3852 && this.itemAnimation == 0)
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].shoot > 0 && ProjectileID.Sets.TurretFeature[this.inventory[this.selectedItem].shoot])
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].shoot > 0 && ProjectileID.Sets.MinionTargetingFeature[this.inventory[this.selectedItem].shoot])
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].shoot > 0 && ItemID.Sets.IsAKite[this.inventory[this.selectedItem].type] && (this.inventory[this.selectedItem].holdStyle == 1 || ItemID.Sets.PlaceTileOnAltUse[this.inventory[this.selectedItem].type]))
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (flag2 && this.altFunctionUse == 0 && this.inventory[this.selectedItem].makeNPC > 0 && this.itemAnimation == 0 && ItemID.Sets.PlaceTileOnAltUse[this.inventory[this.selectedItem].type])
            {
                this.altFunctionUse = 1;
                this.controlUseItem = true;
            }
            if (!this.controlUseItem && this.altFunctionUse == 1)
            {
                this.altFunctionUse = 0;
            }
            if (this.TryingToUseItem() && this.mount.Active && Mount.DismountsOnItemUse(this.mount.Type) && this.HeldItem.mountType != this.mount.Type)
            {
                this.mount.TryEarlyDismount(this);
                if (this.mount.Active)
                {
                    this.controlUseItem = false;
                }
            }
            this.ItemCheck_ManageRightClickFeatures_ShieldRaise(flag);
        }
References Terraria.Mount.DismountsOnItemUse(), Terraria.Main.HoveringAnInteractable, Terraria.ID.ItemID.Sets.IsAKite, Terraria.ID.ItemID.Sets.ItemsThatAllowRepeatedRightClick, Terraria.Main.LocalPlayerHasPendingInventoryActions(), Terraria.ID.ProjectileID.Sets.MinionTargetingFeature, Terraria.Main.mouseRightRelease, Terraria.ID.ItemID.Sets.PlaceTileOnAltUse, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.ID.ProjectileID.Sets.TurretFeature.