Terraria Decompiled: Terraria.Player.QuickMount
QuickMount()
void Terraria.Player.QuickMount () inline
Definition at line 3270 of file Player.cs.
        {
            if (this.mount.Active)
            {
                if (this.mount.TryDismountWithResult(this) == Mount.DismountCheckResult.FailedNoSpace)
                {
                    this.FailedNoSpaceLocation = this.position.ToTileCoordinates();
                    this.FailedNoSpaceCount++;
                    if (this.FailedNoSpaceCount < 3)
                    {
                        SoundEngine.PlaySound(0, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.mount.DoFailedDismountDust(this, this.FailedNoSpaceCount * 20);
                        return;
                    }
                    this.mount.Dismount(this, true);
                    this.FailedNoSpaceCount = 0;
                    if (Main.netMode == 0)
                    {
                        this.PlayerNoSpaceTeleport();
                        return;
                    }
                    if (Main.netMode == 1 && this.whoAmI == Main.myPlayer)
                    {
                        NetMessage.SendData(73, -1, -1, null, 4, 0f, 0f, 0f, 0, 0, 0);
                    }
                }
                return;
            }
            if (this.frozen || this.tongued || this.webbed || this.stoned || this.gravDir == -1f || this.dead)
            {
                return;
            }
            if (this.noItems)
            {
                return;
            }
            Item item = this.QuickMount_GetItemToUse();
            if (item != null && item.mountType != -1 && this.mount.CanMount(item.mountType, this) && this.ItemCheck_TryStartUse(item, false))
            {
                bool flag = !this.QuickMinecartSnap();
                if (Mount.DismountsOnItemUse(item.mountType) && this.TryingToUseItem())
                {
                    flag = false;
                }
                if (flag)
                {
                    this.mount.SetMount(item.mountType, this);
                    if (item.UseSound != null)
                    {
                        SoundEngine.PlaySound(item.UseSound, base.Center, 0f, 1f);
                        return;
                    }
                }
            }
            else
            {
                this.QuickMinecart();
            }
        }
References Terraria.Mount.Active, Terraria.Player.dead, Terraria.Mount.Dismount(), Terraria.Mount.DismountsOnItemUse(), Terraria.Mount.DoFailedDismountDust(), Terraria.Player.FailedNoSpaceCount, Terraria.Player.frozen, Terraria.Player.gravDir, System.item, Terraria.Player.mount, Terraria.Item.mountType, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Player.noItems, Terraria.Player.PlayerNoSpaceTeleport(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Player.QuickMinecart(), Terraria.Player.QuickMinecartSnap(), Terraria.Player.QuickMount_GetItemToUse(), Terraria.NetMessage.SendData(), Terraria.Mount.SetMount(), Terraria.Player.stoned, Terraria.Player.tongued, Terraria.Mount.TryDismountWithResult(), Terraria.Player.webbed, and Microsoft.Xna.Framework.Vector2.X.