Terraria Decompiled: Terraria.Player.QuickBuff_ShouldUseItem
QuickBuff_ShouldUseItem()
bool Terraria.Player.QuickBuff_ShouldUseItem (Item item, out int btype) inline private
Definition at line 3081 of file Player.cs.
        {
            btype = 0;
            if (item.stack <= 0 || item.type <= 0 || item.buffType <= 0 || item.summon)
            {
                return false;
            }
            if (!this.ItemCheck_TryStartUse(item, false))
            {
                return false;
            }
            btype = item.buffType;
            bool flag = this.QuickBuff_ShouldBotherUsingThisBuff(btype);
            if (item.mana > 0 && flag)
            {
                if (this.statMana >= (int)((float)item.mana * this.manaCost))
                {
                    this.manaRegenDelay = (float)((int)this.maxRegenDelay);
                    this.statMana -= (int)((float)item.mana * this.manaCost);
                }
                else
                {
                    flag = false;
                }
            }
            if (this.whoAmI == Main.myPlayer && item.type == 603 && !Main.runningCollectorsEdition)
            {
                flag = false;
            }
            if (btype == 27)
            {
                btype = Main.rand.Next(3);
                if (btype == 0)
                {
                    btype = 27;
                }
                if (btype == 1)
                {
                    btype = 101;
                }
                if (btype == 2)
                {
                    btype = 102;
                }
            }
            return flag;
        }
References int, System.item, Terraria.Player.ItemCheck_TryStartUse(), Terraria.Item.mana, Terraria.Player.manaCost, Terraria.Player.maxRegenDelay, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.QuickBuff_ShouldBotherUsingThisBuff(), Terraria.Main.rand, Terraria.Main.runningCollectorsEdition, Terraria.Player.statMana, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.QuickBuff().