Terraria Decompiled: Terraria.Player.RollerSkateMovement
RollerSkateMovement()
void Terraria.Player.RollerSkateMovement () inline private
Definition at line 26894 of file Player.cs.
        {
            bool flag = this.grappling[0] >= 0;
            if (this.controlRight.ToInt() - this.controlLeft.ToInt() == 0 && !flag)
            {
                float num = 0.3f;
                float num2 = 1.5f;
                float num3 = 6.5f;
                int num4 = 10;
                if (this.HeldItem.createTile >= 0 || this.HeldItem.tileWand > 0)
                {
                    num4 = this.HeldItem.useTime;
                }
                int num5 = (int)((float)num4 * this.tileSpeed);
                float num6 = 16f;
                float num7 = Math.Max(num2, num6 / (float)num5);
                if (Math.Abs(this.velocity.X) < num2)
                {
                    this.velocity.X = MathHelper.Lerp(this.velocity.X, 0f, num);
                    if (Math.Abs(this.velocity.X) < 0.03f)
                    {
                        this.velocity.X = 0f;
                    }
                }
                else if (Math.Abs(this.velocity.X) < num3)
                {
                    float num8 = (float)Math.Sign(this.velocity.X) * num7;
                    this.velocity.X = MathHelper.Lerp(this.velocity.X, num8, num);
                }
            }
            if (this.powerrun)
            {
                this.maxRunSpeed *= 2.25f;
                this.runAcceleration *= 1f;
                this.runSlowdown *= 1.6f;
            }
            float num9 = Math.Max(this.maxRunSpeed, this.accRunSpeed);
            this.runSlowdown = Utils.Clamp<float>(Math.Abs(this.velocity.X) - num9, 0f, this.runSlowdown);
            if (this.velocity.Y == 0f && !this.onTrack)
            {
                this.fullRotation = 0f;
            }
        }
References System.Math.Abs(), Terraria.Utils.Clamp(), int, Microsoft.Xna.Framework.MathHelper.Lerp(), System.Math.Max(), and System.Math.Sign().