Terraria Decompiled: Terraria.Player.AdjustRespawnTimerForWorldJoining
AdjustRespawnTimerForWorldJoining()
static void Terraria.Player.AdjustRespawnTimerForWorldJoining (Player newPlayer) inline static private
Definition at line 55101 of file Player.cs.
        {
            if (Main.myPlayer != newPlayer.whoAmI)
            {
                return;
            }
            if (!newPlayer.dead)
            {
                return;
            }
            if (newPlayer.lastTimePlayerWasSaved == 0L)
            {
                return;
            }
            long num = DateTime.UtcNow.ToBinary() - newPlayer.lastTimePlayerWasSaved;
            TimeSpan timeSpan = new TimeSpan(num);
            int num2 = Utils.Clamp<int>((int)(Utils.Clamp<double>(timeSpan.TotalSeconds, 0.0, 1000.0) * 60.0), 0, newPlayer.respawnTimer);
            newPlayer.respawnTimer -= num2;
            if (newPlayer.respawnTimer == 0)
            {
                newPlayer.dead = false;
            }
        }
References Terraria.Utils.Clamp(), Terraria.Player.dead, int, System.L, Terraria.Player.lastTimePlayerWasSaved, Terraria.Main.myPlayer, Terraria.Player.respawnTimer, System.DateTime.ToBinary(), System.TimeSpan.TotalSeconds, System.DateTime.UtcNow, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Spawn().