Terraria Decompiled: Terraria.Player.SerializedClone
SerializedClone()
Player Terraria.Player.SerializedClone () inline
Definition at line 54462 of file Player.cs.
        {
            Player player = new Player();
            Player._visualCloneStream.Seek(0L, SeekOrigin.Begin);
            Player.Serialize(Player._visualCloneDummyData, this, Player._visualCloneWriter);
            Player._visualCloneStream.Seek(0L, SeekOrigin.Begin);
            bool flag;
            Player.Deserialize(Player._visualCloneDummyData, player, Player._visualCloneReader, 319, out flag);
            return player;
        }
References Terraria.Player._visualCloneDummyData, Terraria.Player._visualCloneReader, Terraria.Player._visualCloneStream, Terraria.Player._visualCloneWriter, Terraria.Player.Deserialize(), System.L, Terraria.Enums.Player, System.IO.MemoryStream.Seek(), and Terraria.Player.Serialize().
Referenced by Terraria.GameContent.UI.Elements.UICharacter.UICharacter().