Terraria Decompiled: Terraria.Player.ItemCheck_UseMiningTools
ItemCheck_UseMiningTools()
void Terraria.Player.ItemCheck_UseMiningTools (Item sItem) inline private
Definition at line 44856 of file Player.cs.
        {
            Player.SpecialToolUsageSettings specialToolUsageSettings = default(Player.SpecialToolUsageSettings);
            if (sItem.type == 4711)
            {
                specialToolUsageSettings = new Player.SpecialToolUsageSettings
                {
                    IsAValidTool = true,
                    UsageAction = new Player.SpecialToolUsageSettings.UseToolAction(this.UseShovel)
                };
            }
            if (sItem.pick <= 0 && sItem.axe <= 0 && sItem.hammer <= 0 && !specialToolUsageSettings.IsAValidTool)
            {
                return;
            }
            bool flag = this.IsTargetTileInItemRange(sItem);
            if (this.noBuilding)
            {
                flag = false;
            }
            if (flag && specialToolUsageSettings.UsageCondition != null)
            {
                flag = specialToolUsageSettings.UsageCondition(this, sItem, Player.tileTargetX, Player.tileTargetY);
            }
            if (this.toolTime == 0 && this.itemAnimation > 0 && this.controlUseItem)
            {
                Tile tile = Main.tile[Player.tileTargetX, Player.tileTargetY];
                if (!tile.active() || !this.IsAHammerTarget(tile))
                {
                    this.poundRelease = false;
                }
            }
            if (!flag)
            {
                return;
            }
            if (!Main.GamepadDisableCursorItemIcon)
            {
                this.cursorItemIconEnabled = true;
                Main.ItemIconCacheUpdate(sItem.type);
            }
            bool flag2 = false;
            if (this.toolTime == 0 && this.itemAnimation > 0 && this.controlUseItem)
            {
                if (specialToolUsageSettings.UsageAction != null)
                {
                    specialToolUsageSettings.UsageAction(this, sItem, Player.tileTargetX, Player.tileTargetY);
                    return;
                }
                this.ItemCheck_UseMiningTools_ActuallyUseMiningTool(sItem, out flag2, Player.tileTargetX, Player.tileTargetY);
            }
            if (this.releaseUseItem)
            {
                this.poundRelease = true;
            }
            if (this.toolTime == 0 && this.itemAnimation > 0 && this.controlUseItem && flag2)
            {
                int num;
                int num2;
                Player.ItemCheck_UseMiningTools_TryFindingWallToHammer(out num, out num2);
                this.ItemCheck_UseMiningTools_TryHittingWall(sItem, num, num2);
            }
        }
References Terraria.Tile.active(), Terraria.Item.axe, Terraria.Main.GamepadDisableCursorItemIcon, Terraria.Item.hammer, Terraria.Player.SpecialToolUsageSettings.IsAValidTool, Terraria.Player.ItemCheck_UseMiningTools_TryFindingWallToHammer(), Terraria.Main.ItemIconCacheUpdate(), Terraria.Item.pick, Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Item.type, Terraria.Player.SpecialToolUsageSettings.UsageAction, Terraria.Player.SpecialToolUsageSettings.UsageCondition, and Terraria.Player.SpecialToolUsageSettings.UseToolAction().