Terraria Decompiled: Terraria.Player.JumpMovement
JumpMovement()
void Terraria.Player.JumpMovement () inline
Definition at line 18852 of file Player.cs.
        {
            if (this.mount.Active && this.mount.IsConsideredASlimeMount && this.wetSlime == 0 && this.velocity.Y > 0f)
            {
                Rectangle rect = this.getRect();
                rect.Offset(0, this.height - 1);
                rect.Height = 2;
                rect.Inflate(12, 6);
                for (int i = 0; i < Main.maxNPCs; i++)
                {
                    NPC npc = Main.npc[i];
                    if (npc.active && !npc.dontTakeDamage && !npc.friendly && npc.immune[this.whoAmI] == 0 && this.CanNPCBeHitByPlayerOrPlayerProjectile(npc, null))
                    {
                        Rectangle rect2 = npc.getRect();
                        if (rect.Intersects(rect2) && (npc.noTileCollide || Collision.CanHit(this.position, this.width, this.height, npc.position, npc.width, npc.height)))
{
                            float num = 40f * this.minionDamage;
                            float num2 = 5f;
                            int num3 = this.direction;
                            if (this.velocity.X < 0f)
{
                                num3 = -1;
                            }
                            if (this.velocity.X > 0f)
{
                                num3 = 1;
                            }
                            if (this.whoAmI == Main.myPlayer)
{
                                this.ApplyDamageToNPC(npc, (int)num, num2, num3, false);
                            }
                            npc.immune[this.whoAmI] = 10;
                            this.velocity.Y = -10f;
                            this.GiveImmuneTimeForCollisionAttack(6);
                            break;
                        }
                    }
                }
            }
            if (this.isPerformingJump_DownDash && this.velocity.Y > 0f)
            {
                Rectangle rect3 = this.getRect();
                rect3.Offset(0, this.height - 1);
                rect3.Height = 2;
                rect3.Inflate(12, 6);
                for (int j = 0; j < Main.maxNPCs; j++)
                {
                    NPC npc2 = Main.npc[j];
                    if (npc2.active && !npc2.dontTakeDamage && !npc2.friendly && npc2.immune[this.whoAmI] == 0 && this.CanNPCBeHitByPlayerOrPlayerProjectile(npc2, null))
                    {
                        Rectangle rect4 = npc2.getRect();
                        if (rect3.Intersects(rect4) && (npc2.noTileCollide || Collision.CanHit(this.position, this.width, this.height, npc2.position, npc2.width, npc2.height)))
{
                            float num4 = 40f * this.minionDamage;
                            float num5 = 5f;
                            int num6 = this.direction;
                            if (this.velocity.X < 0f)
{
                                num6 = -1;
                            }
                            if (this.velocity.X > 0f)
{
                                num6 = 1;
                            }
                            if (this.whoAmI == Main.myPlayer)
{
                                this.ApplyDamageToNPC(npc2, (int)num4, num5, num6, false);
                            }
                            npc2.immune[this.whoAmI] = 10;
                            this.GiveImmuneTimeForCollisionAttack(6);
                            break;
                        }
                    }
                }
            }
            if (this.mount.Active && this.mount.Type == 17 && this.velocity.Y > 0f)
            {
                Rectangle rect5 = this.getRect();
                rect5.Offset(0, this.height - 1);
                rect5.Height = 2;
                rect5.Inflate(12, 6);
                for (int k = 0; k < Main.maxNPCs; k++)
                {
                    NPC npc3 = Main.npc[k];
                    if (npc3.active && !npc3.dontTakeDamage && !npc3.friendly && npc3.immune[this.whoAmI] == 0 && this.CanNPCBeHitByPlayerOrPlayerProjectile(npc3, null))
                    {
                        Rectangle rect6 = npc3.getRect();
                        if (rect5.Intersects(rect6) && (npc3.noTileCollide || Collision.CanHit(this.position, this.width, this.height, npc3.position, npc3.width, npc3.height)))
{
                            float num7 = 40f;
                            float num8 = 5f;
                            int num9 = this.direction;
                            if (this.velocity.X < 0f)
{
                                num9 = -1;
                            }
                            if (this.velocity.X > 0f)
{
                                num9 = 1;
                            }
                            if (this.whoAmI == Main.myPlayer)
{
                                this.ApplyDamageToNPC(npc3, (int)num7, num8, num9, false);
                            }
                            npc3.immune[this.whoAmI] = 12;
                            this.GiveImmuneTimeForCollisionAttack(12);
                            break;
                        }
                    }
                }
            }
            if (this.controlJump)
            {
                if (this.sliding)
                {
                    this.autoJump = false;
                }
                bool flag = false;
                bool flag2 = this.wet && this.accFlipper;
                bool flag3 = !this.mount.Active || !this.mount.Cart;
                if (this.mount.Active && this.mount.IsConsideredASlimeMount && this.wetSlime > 0)
                {
                    this.wetSlime = 0;
                    flag = true;
                }
                if (this.mount.Active && this.mount.Type == 43 && this.releaseJump && this.velocity.Y != 0f)
                {
                    this.isPerformingPogostickTricks = true;
                }
                if (this.jump > 0)
                {
                    if (this.velocity.Y == 0f)
                    {
                        this.jump = 0;
                    }
                    else
                    {
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        if (this.merman && (!this.mount.Active || !this.mount.Cart))
{
                            if (this.swimTime <= 10)
{
                                this.swimTime = 30;
                            }
                        }
                        else
{
                            this.jump--;
                        }
                    }
                }
                else if ((this.sliding || this.velocity.Y == 0f || flag || this.canJumpAgain_Cloud || this.canJumpAgain_Sandstorm || this.canJumpAgain_Blizzard || this.canJumpAgain_Fart || this.canJumpAgain_Sail || this.canJumpAgain_Unicorn || this.canJumpAgain_Santank || this.canJumpAgain_WallOfFleshGoat || this.canJumpAgain_Basilisk || (flag2 && flag3) || (this.hasDeadCellsDownDash && this.controlDown && this.velocity.Y != 0f && !this.isPerformingJump_DownDash && !this.mount.Active)) && (this.releaseJump || (this.autoJump && (this.velocity.Y == 0f || this.sliding))))
                {
                    if (this.mount.Active && MountID.Sets.Cart[this.mount.Type])
                    {
                        this.position.Y = this.position.Y - 0.001f;
                    }
                    if (this.sliding || this.velocity.Y == 0f)
                    {
                        this.justJumped = true;
                    }
                    bool flag4 = false;
                    if (this.wet && this.accFlipper)
                    {
                        if (this.swimTime == 0)
{
                            this.swimTime = 30;
                        }
                        flag4 = true;
                    }
                    bool flag5 = false;
                    bool flag6 = false;
                    bool flag7 = false;
                    bool flag8 = false;
                    bool flag9 = false;
                    bool flag10 = false;
                    bool flag11 = false;
                    bool flag12 = false;
                    bool flag13 = false;
                    if (!flag2 && !flag)
                    {
                        if (this.canJumpAgain_Basilisk)
{
                            flag12 = true;
                            this.canJumpAgain_Basilisk = false;
                        }
                        else if (this.canJumpAgain_WallOfFleshGoat)
{
                            flag11 = true;
                            this.canJumpAgain_WallOfFleshGoat = false;
                        }
                        else if (this.canJumpAgain_Santank)
{
                            flag10 = true;
                            this.canJumpAgain_Santank = false;
                        }
                        else if (this.canJumpAgain_Unicorn)
{
                            flag9 = true;
                            this.canJumpAgain_Unicorn = false;
                        }
                        else if (this.hasDeadCellsDownDash && this.controlDown && !this.isPerformingJump_DownDash && this.velocity.Y != 0f && !this.mount.Active)
{
                            flag13 = true;
                        }
                        else if (this.canJumpAgain_Sandstorm)
{
                            flag5 = true;
                            this.canJumpAgain_Sandstorm = false;
                        }
                        else if (this.canJumpAgain_Blizzard)
{
                            flag6 = true;
                            this.canJumpAgain_Blizzard = false;
                        }
                        else if (this.canJumpAgain_Fart)
{
                            this.canJumpAgain_Fart = false;
                            flag7 = true;
                        }
                        else if (this.canJumpAgain_Sail)
{
                            this.canJumpAgain_Sail = false;
                            flag8 = true;
                        }
                        else
{
                            this.canJumpAgain_Cloud = false;
                        }
                    }
                    this.canRocket = false;
                    this.rocketRelease = false;
                    if (!this.onTrack)
                    {
                        this.fullRotation = 0f;
                    }
                    if (this.velocity.Y == 0f || this.sliding || (this.autoJump && this.justJumped))
                    {
                        this.RefreshDoubleJumps();
                    }
                    this.isPerformingJump_DownDash = flag13;
                    if (this.velocity.Y == 0f || flag4 || this.sliding || flag)
                    {
                        if (this.mount.Active && this.mount.Type == 43)
{
                            SoundEngine.PlaySound(SoundID.Item168, base.Center, 0f, 1f);
                        }
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = Player.jumpHeight;
                        if (this.portableStoolInfo.IsInUse)
{
                            this.portableStoolInfo.IsInUse = false;
                            this.position.Y = this.position.Y - (float)this.portableStoolInfo.HeightBoost;
                            if (Main.myPlayer == this.whoAmI)
{
                                Main.cameraY += (float)this.portableStoolInfo.HeightBoost;
                            }
                        }
                        if (this.sliding)
{
                            this.velocity.X = (float)(3 * -(float)this.slideDir);
                        }
                    }
                    else if (flag13)
                    {
                        this.velocity.Y = 16f * this.gravDir;
                    }
                    else if (flag5)
                    {
                        this.isPerformingJump_Sandstorm = true;
                        int height = this.height;
                        float num10 = this.gravDir;
                        SoundEngine.PlaySound(16, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = Player.jumpHeight * 3;
                    }
                    else if (flag6)
                    {
                        this.isPerformingJump_Blizzard = true;
                        int height2 = this.height;
                        float num11 = this.gravDir;
                        SoundEngine.PlaySound(16, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = (int)((double)Player.jumpHeight * 1.5);
                    }
                    else if (flag8)
                    {
                        this.isPerformingJump_Sail = true;
                        int num12 = this.height;
                        if (this.gravDir == -1f)
{
                            num12 = 0;
                        }
                        SoundEngine.PlaySound(16, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = (int)((double)Player.jumpHeight * 1.25);
                        for (int l = 0; l < 30; l++)
{
                            int num13 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)num12), this.width, 12, 253, this.velocity.X * 0.3f, this.velocity.Y * 0.3f, 100, default(Color), 1.5f);
                            if (l % 2 == 0)
{
                                Dust dust = Main.dust[num13];
                                dust.velocity.X = dust.velocity.X + (float)Main.rand.Next(30, 71) * 0.1f;
                            }
                            else
{
                                Dust dust2 = Main.dust[num13];
                                dust2.velocity.X = dust2.velocity.X - (float)Main.rand.Next(30, 71) * 0.1f;
                            }
                            Dust dust3 = Main.dust[num13];
                            dust3.velocity.Y = dust3.velocity.Y + (float)Main.rand.Next(-10, 31) * 0.1f;
                            Main.dust[num13].noGravity = true;
                            Main.dust[num13].scale += (float)Main.rand.Next(-10, 41) * 0.01f;
                            Main.dust[num13].velocity *= Main.dust[num13].scale * 0.7f;
                            Vector2 vector = new Vector2((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                            vector.Normalize();
                            vector *= (float)Main.rand.Next(81) * 0.1f;
                        }
                    }
                    else if (flag7)
                    {
                        this.isPerformingJump_Fart = true;
                        int num14 = this.height;
                        if (this.gravDir == -1f)
{
                            num14 = 0;
                        }
                        SoundEngine.PlaySound(SoundID.Item16, this.position, 0f, 1f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = Player.jumpHeight * 2;
                        for (int m = 0; m < 10; m++)
{
                            int num15 = Dust.NewDust(new Vector2(this.position.X - 34f, this.position.Y + (float)num14 - 16f), 102, 32, 188, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 100, default(Color), 1.5f);
                            Main.dust[num15].velocity.X = Main.dust[num15].velocity.X * 0.5f - this.velocity.X * 0.1f;
                            Main.dust[num15].velocity.Y = Main.dust[num15].velocity.Y * 0.5f - this.velocity.Y * 0.3f;
                        }
                        int num16 = Gore.NewGore(new Vector2(this.position.X + (float)(this.width / 2) - 16f, this.position.Y + (float)num14 - 16f), new Vector2(-this.velocity.X, -this.velocity.Y), Main.rand.Next(435, 438), 1f);
                        Main.gore[num16].velocity.X = Main.gore[num16].velocity.X * 0.1f - this.velocity.X * 0.1f;
                        Main.gore[num16].velocity.Y = Main.gore[num16].velocity.Y * 0.1f - this.velocity.Y * 0.05f;
                        num16 = Gore.NewGore(new Vector2(this.position.X - 36f, this.position.Y + (float)num14 - 16f), new Vector2(-this.velocity.X, -this.velocity.Y), Main.rand.Next(435, 438), 1f);
                        Main.gore[num16].velocity.X = Main.gore[num16].velocity.X * 0.1f - this.velocity.X * 0.1f;
                        Main.gore[num16].velocity.Y = Main.gore[num16].velocity.Y * 0.1f - this.velocity.Y * 0.05f;
                        num16 = Gore.NewGore(new Vector2(this.position.X + (float)this.width + 4f, this.position.Y + (float)num14 - 16f), new Vector2(-this.velocity.X, -this.velocity.Y), Main.rand.Next(435, 438), 1f);
                        Main.gore[num16].velocity.X = Main.gore[num16].velocity.X * 0.1f - this.velocity.X * 0.1f;
                        Main.gore[num16].velocity.Y = Main.gore[num16].velocity.Y * 0.1f - this.velocity.Y * 0.05f;
                    }
                    else if (flag9)
                    {
                        this.isPerformingJump_Unicorn = true;
                        int height3 = this.height;
                        float num17 = this.gravDir;
                        SoundEngine.PlaySound(16, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = Player.jumpHeight * 2;
                        Vector2 center = base.Center;
                        Vector2 vector2 = new Vector2(50f, 20f);
                        float num18 = 6.2831855f * Main.rand.NextFloat();
                        for (int n = 0; n < 5; n++)
{
                            for (float num19 = 0f; num19 < 14f; num19 += 1f)
{
                                Dust dust4 = Main.dust[Dust.NewDust(center, 0, 0, Utils.SelectRandom<int>(Main.rand, new int[] { 176, 177, 179 }), 0f, 0f, 0, default(Color), 1f)];
                                Vector2 vector3 = Vector2.UnitY.RotatedBy((double)(num19 * 6.2831855f / 14f + num18), default(Vector2));
                                vector3 *= 0.2f * (float)n;
                                dust4.position = center + vector3 * vector2;
                                dust4.velocity = vector3 + new Vector2(0f, this.gravDir * 4f);
                                dust4.noGravity = true;
                                dust4.scale = 1f + Main.rand.NextFloat() * 0.8f;
                                dust4.fadeIn = Main.rand.NextFloat() * 2f;
                                dust4.shader = GameShaders.Armor.GetSecondaryShader(this.cMount, this);
                            }
                        }
                    }
                    else if (flag11)
                    {
                        this.isPerformingJump_WallOfFleshGoat = true;
                        int height4 = this.height;
                        float num20 = this.gravDir;
                        SoundEngine.PlaySound(16, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = Player.jumpHeight * 2;
                        Vector2 center2 = base.Center;
                        Vector2 vector4 = new Vector2(50f, 20f);
                        float num21 = 6.2831855f * Main.rand.NextFloat();
                        for (int num22 = 0; num22 < 5; num22++)
{
                            for (float num23 = 0f; num23 < 14f; num23 += 1f)
{
                                Dust dust5 = Main.dust[Dust.NewDust(center2, 0, 0, 6, 0f, 0f, 0, default(Color), 1f)];
                                Vector2 vector5 = Vector2.UnitY.RotatedBy((double)(num23 * 6.2831855f / 14f + num21), default(Vector2));
                                vector5 *= 0.2f * (float)num22;
                                dust5.position = center2 + vector5 * vector4;
                                dust5.velocity = vector5 + new Vector2(0f, this.gravDir * 4f);
                                dust5.noGravity = true;
                                dust5.scale = 1f + Main.rand.NextFloat() * 0.8f;
                                dust5.fadeIn = Main.rand.NextFloat() * 2f;
                                dust5.shader = GameShaders.Armor.GetSecondaryShader(this.cMount, this);
                            }
                        }
                    }
                    else if (flag12)
                    {
                        this.isPerformingJump_Basilisk = true;
                        int height5 = this.height;
                        float num24 = this.gravDir;
                        SoundEngine.PlaySound(16, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = (int)((double)Player.jumpHeight * 0.75);
                        Vector2 center3 = base.Center;
                        Vector2 vector6 = new Vector2(50f, 20f);
                        float num25 = 6.2831855f * Main.rand.NextFloat();
                        for (int num26 = 0; num26 < 5; num26++)
{
                            for (float num27 = 0f; num27 < 14f; num27 += 1f)
{
                                Dust dust6 = Main.dust[Dust.NewDust(center3, 0, 0, 31, 0f, 0f, 0, default(Color), 1f)];
                                Vector2 vector7 = Vector2.UnitY.RotatedBy((double)(num27 * 6.2831855f / 14f + num25), default(Vector2));
                                vector7 *= 0.2f * (float)num26;
                                dust6.position = center3 + vector7 * vector6;
                                dust6.velocity = vector7 + new Vector2(0f, this.gravDir * 4f);
                                dust6.noGravity = true;
                                dust6.scale = 1f + Main.rand.NextFloat() * 0.8f;
                                dust6.fadeIn = Main.rand.NextFloat() * 2f;
                                dust6.shader = GameShaders.Armor.GetSecondaryShader(this.cMount, this);
                            }
                        }
                    }
                    else if (flag10)
                    {
                        this.isPerformingJump_Santank = true;
                        int num28 = this.height;
                        if (this.gravDir == -1f)
{
                            num28 = 0;
                        }
                        SoundEngine.PlaySound(16, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = Player.jumpHeight * 2;
                        for (int num29 = 0; num29 < 15; num29++)
{
                            int num30 = Dust.NewDust(new Vector2(this.position.X - 34f, this.position.Y + (float)num28 - 16f), 102, 32, 4, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 100, new Color(250, 230, 230, 150), 1.5f);
                            Main.dust[num30].velocity.X = Main.dust[num30].velocity.X * 0.5f - this.velocity.X * 0.1f;
                            Main.dust[num30].velocity.Y = Main.dust[num30].velocity.Y * 0.5f - this.velocity.Y * 0.3f;
                            Main.dust[num30].noGravity = true;
                            num30 = Dust.NewDust(new Vector2(this.position.X - 34f, this.position.Y + (float)num28 - 16f), 102, 32, 6, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 20, default(Color), 1.5f);
                            Dust dust7 = Main.dust[num30];
                            dust7.velocity.Y = dust7.velocity.Y - 1f;
                            if (num29 % 2 == 0)
{
                                Main.dust[num30].fadeIn = Main.rand.NextFloat() * 2f;
                            }
                        }
                        float num31 = base.Bottom.Y - 22f;
                        for (int num32 = 0; num32 < 3; num32++)
{
                            Vector2 center4 = base.Center;
                            switch (num32)
{
                            case 0:
                                center4 = new Vector2(base.Center.X - 16f, num31);
                                break;
                            case 1:
                                center4 = new Vector2(this.position.X - 36f, num31);
                                break;
                            case 2:
                                center4 = new Vector2(base.Right.X + 4f, num31);
                                break;
                            }
                            int num33 = Gore.NewGore(center4, new Vector2(-this.velocity.X, -this.velocity.Y), Main.rand.Next(61, 63), 1f);
                            Main.gore[num33].velocity *= 0.1f;
                            Gore gore = Main.gore[num33];
                            gore.velocity.X = gore.velocity.X - this.velocity.X * 0.1f;
                            Gore gore2 = Main.gore[num33];
                            gore2.velocity.Y = gore2.velocity.Y - this.velocity.Y * 0.05f;
                            Main.gore[num33].velocity += Main.rand.NextVector2Circular(1f, 1f) * 0.5f;
                        }
                    }
                    else
                    {
                        this.isPerformingJump_Cloud = true;
                        int num34 = this.height;
                        if (this.gravDir == -1f)
{
                            num34 = 0;
                        }
                        SoundEngine.PlaySound(16, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        this.velocity.Y = -Player.jumpSpeed * this.gravDir;
                        this.jump = (int)((double)Player.jumpHeight * 0.75);
                        for (int num35 = 0; num35 < 10; num35++)
{
                            int num36 = Dust.NewDust(new Vector2(this.position.X - 34f, this.position.Y + (float)num34 - 16f), 102, 32, 16, -this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 100, default(Color), 1.5f);
                            Main.dust[num36].velocity.X = Main.dust[num36].velocity.X * 0.5f - this.velocity.X * 0.1f;
                            Main.dust[num36].velocity.Y = Main.dust[num36].velocity.Y * 0.5f - this.velocity.Y * 0.3f;
                        }
                        int num37 = Gore.NewGore(new Vector2(this.position.X + (float)(this.width / 2) - 16f, this.position.Y + (float)num34 - 16f), new Vector2(-this.velocity.X, -this.velocity.Y), Main.rand.Next(11, 14), 1f);
                        Main.gore[num37].velocity.X = Main.gore[num37].velocity.X * 0.1f - this.velocity.X * 0.1f;
                        Main.gore[num37].velocity.Y = Main.gore[num37].velocity.Y * 0.1f - this.velocity.Y * 0.05f;
                        num37 = Gore.NewGore(new Vector2(this.position.X - 36f, this.position.Y + (float)num34 - 16f), new Vector2(-this.velocity.X, -this.velocity.Y), Main.rand.Next(11, 14), 1f);
                        Main.gore[num37].velocity.X = Main.gore[num37].velocity.X * 0.1f - this.velocity.X * 0.1f;
                        Main.gore[num37].velocity.Y = Main.gore[num37].velocity.Y * 0.1f - this.velocity.Y * 0.05f;
                        num37 = Gore.NewGore(new Vector2(this.position.X + (float)this.width + 4f, this.position.Y + (float)num34 - 16f), new Vector2(-this.velocity.X, -this.velocity.Y), Main.rand.Next(11, 14), 1f);
                        Main.gore[num37].velocity.X = Main.gore[num37].velocity.X * 0.1f - this.velocity.X * 0.1f;
                        Main.gore[num37].velocity.Y = Main.gore[num37].velocity.Y * 0.1f - this.velocity.Y * 0.05f;
                    }
                }
                this.releaseJump = false;
                return;
            }
            this.jump = 0;
            this.releaseJump = true;
            this.rocketRelease = true;
        }
References Terraria.NPC.active, Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Collision.CanHit(), Terraria.ID.MountID.Sets.Cart, Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.NPC.friendly, Terraria.NPC.getRect(), Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Main.gore, Terraria.Entity.height, Terraria.NPC.immune, Microsoft.Xna.Framework.Rectangle.Inflate(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.ID.SoundID.Item16, Terraria.ID.SoundID.Item168, Terraria.Player.jumpHeight, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.NPC.noTileCollide, Terraria.Main.npc, Microsoft.Xna.Framework.Rectangle.Offset(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Dust.velocity, Terraria.Gore.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.