Terraria Decompiled: Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins
ItemCheck_TryPlacingWearablesOnMannequins()
void Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins (Item sItem) inline private
Definition at line 51976 of file Player.cs.
        {
            if (this.controlUseItem && this.releaseUseItem && (sItem.headSlot > 0 || sItem.bodySlot > 0 || sItem.legSlot > 0))
            {
                if (sItem.useStyle == 0)
                {
                    this.releaseUseItem = false;
                }
                if (this.IsInTileInteractionRange(Player.tileTargetX, Player.tileTargetY, TileReachCheckSettings.Simple, sItem.tileBoost))
                {
                    int num = Player.tileTargetX;
                    int num2 = Player.tileTargetY;
                    if (Main.tile[num, num2].active() && (Main.tile[num, num2].type == 128 || Main.tile[num, num2].type == 269))
                    {
                        int num3 = (int)Main.tile[num, num2].frameY;
                        int i = 0;
                        if (sItem.bodySlot >= 0)
{
                            i = 1;
                        }
                        if (sItem.legSlot >= 0)
{
                            i = 2;
                        }
                        num3 /= 18;
                        while (i > num3)
{
                            num2++;
                            num3 = (int)Main.tile[num, num2].frameY;
                            num3 /= 18;
                        }
                        while (i < num3)
{
                            num2--;
                            num3 = (int)Main.tile[num, num2].frameY;
                            num3 /= 18;
                        }
                        int j;
                        for (j = (int)Main.tile[num, num2].frameX; j >= 100; j -= 100)
{
                        }
                        if (j >= 36)
{
                            j -= 36;
                        }
                        num -= j / 18;
                        int k = (int)Main.tile[num, num2].frameX;
                        WorldGen.KillTile(num, num2, true, false, false);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)num, (float)num2, 1f, 0, 0, 0);
                        }
                        while (k >= 100)
{
                            k -= 100;
                        }
                        if (num3 == 0 && sItem.headSlot >= 0)
{
                            Main.blockMouse = true;
                            Main.tile[num, num2].frameX = (short)(k + sItem.headSlot * 100);
                            if (Main.netMode == 1)
{
                                NetMessage.SendTileSquare(-1, num, num2, TileChangeType.None);
                            }
                            sItem.stack--;
                            if (sItem.stack <= 0)
{
                                sItem.SetDefaults(0, null);
                                Main.mouseItem.SetDefaults(0, null);
                            }
                            if (this.selectedItem == 58)
{
                                Main.mouseItem = sItem.Clone();
                            }
                            this.releaseUseItem = false;
                            this.mouseInterface = true;
                            return;
                        }
                        if (num3 == 1 && sItem.bodySlot >= 0)
{
                            Main.blockMouse = true;
                            Main.tile[num, num2].frameX = (short)(k + sItem.bodySlot * 100);
                            if (Main.netMode == 1)
{
                                NetMessage.SendTileSquare(-1, num, num2, TileChangeType.None);
                            }
                            sItem.stack--;
                            if (sItem.stack <= 0)
{
                                sItem.SetDefaults(0, null);
                                Main.mouseItem.SetDefaults(0, null);
                            }
                            if (this.selectedItem == 58)
{
                                Main.mouseItem = sItem.Clone();
                            }
                            this.releaseUseItem = false;
                            this.mouseInterface = true;
                            return;
                        }
                        if (num3 == 2 && sItem.legSlot >= 0 && !ArmorIDs.Legs.Sets.MannequinIncompatible.Contains(sItem.legSlot))
{
                            Main.blockMouse = true;
                            Main.tile[num, num2].frameX = (short)(k + sItem.legSlot * 100);
                            if (Main.netMode == 1)
{
                                NetMessage.SendTileSquare(-1, num, num2, TileChangeType.None);
                            }
                            sItem.stack--;
                            if (sItem.stack <= 0)
{
                                sItem.SetDefaults(0, null);
                                Main.mouseItem.SetDefaults(0, null);
                            }
                            if (this.selectedItem == 58)
{
                                Main.mouseItem = sItem.Clone();
                            }
                            this.releaseUseItem = false;
                            this.mouseInterface = true;
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Item.bodySlot, Terraria.Item.Clone(), System.Collections.Generic.List< T >.Contains(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Item.headSlot, int, Terraria.WorldGen.KillTile(), Terraria.Item.legSlot, Terraria.ID.ArmorIDs.Legs.Sets.MannequinIncompatible, Terraria.Main.mouseItem, Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Item.SetDefaults(), Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.Item.stack, Terraria.Main.tile, Terraria.Item.tileBoost, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Tile.type, and Terraria.Item.useStyle.