Terraria Decompiled: Terraria.Player.PlaceThing_PaintScrapper_TryScrapping
PlaceThing_PaintScrapper_TryScrapping()
void Terraria.Player.PlaceThing_PaintScrapper_TryScrapping (int x, int y) inline private
Definition at line 40908 of file Player.cs.
        {
            Tile tile = Main.tile[x, y];
            if (!(false | (tile.wall > 0 && (tile.wallColor() > 0 || tile.invisibleWall() || tile.fullbrightWall())) | (tile.active() && (tile.color() > 0 || tile.invisibleBlock() || tile.fullbrightBlock()))))
            {
                return;
            }
            this.cursorItemIconEnabled = true;
            if (!this.ItemTimeIsZero || this.itemAnimation <= 0 || !this.controlUseItem)
            {
                return;
            }
            if (WorldGen.paintTile(x, y, 0, true, true) || WorldGen.paintCoatTile(x, y, 0, true, true))
            {
                this.ApplyItemTime(this.inventory[this.selectedItem], this.tileSpeed);
                return;
            }
            if (WorldGen.paintWall(x, y, 0, true, true) || WorldGen.paintCoatWall(x, y, 0, true, true))
            {
                this.ApplyItemTime(this.inventory[this.selectedItem], this.wallSpeed);
                return;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.WorldGen.paintCoatTile(), Terraria.WorldGen.paintCoatWall(), Terraria.WorldGen.paintTile(), Terraria.WorldGen.paintWall(), Terraria.Main.tile, Terraria.Tile.wall, and Terraria.Tile.wallColor().