Terraria Decompiled: Terraria.Player.ProcessHitAgainstNPC
ProcessHitAgainstNPC()
void Terraria.Player.ProcessHitAgainstNPC (Item sItem, Rectangle itemRectangle, int originalDamage, float knockBack, int npcIndex) inline private
Definition at line 43431 of file Player.cs.
        {
            NPC npc = Main.npc[npcIndex];
            if (npc.dontTakeDamage || !this.CanNPCBeHitByPlayerOrPlayerProjectile(npc, null))
            {
                if (NPCID.Sets.ZappingJellyfish[npc.type] && itemRectangle.Intersects(npc.Hitbox) && (npc.noTileCollide || this.CanHit(npc)))
                {
                    this.TakeDamageFromJellyfish(npcIndex);
                }
                return;
            }
            if (npc.friendly && (npc.type != 22 || !this.killGuide) && (npc.type != 54 || !this.killClothier) && (!npc.isLikeATownNPC || (sItem.type != 5129 && sItem.type != 3351)))
            {
                return;
            }
            Rectangle rectangle = new Rectangle((int)npc.position.X, (int)npc.position.Y, npc.width, npc.height);
            bool flag = itemRectangle.Intersects(rectangle);
            int type = sItem.type;
            if (type == 121)
            {
                Vector2 vector;
                Vector2 vector2;
                this.GetPointOnSwungItemPath(70f, 70f, 0f, this.GetAdjustedItemScale(sItem), out vector, out vector2);
                Vector2 vector3;
                this.GetPointOnSwungItemPath(70f, 70f, 0.9f, this.GetAdjustedItemScale(sItem), out vector3, out vector2);
                bool flag2 = Utils.LineRectangleDistance(rectangle, vector, vector3) <= 16f;
                if (this._spawnVolcanoExplosion)
                {
                    flag = flag2;
                }
                else
                {
                    flag = flag || flag2;
                }
            }
            if (!flag)
            {
                return;
            }
            if (npc.noTileCollide || this.CanHit(npc))
            {
                int num = this.ApplyRapidAttackBonus(originalDamage, sItem.type, !npc.immortal);
                if (npc.isLikeATownNPC && sItem.type == 3351)
                {
                    num = 1;
                }
                bool flag3 = false;
                int weaponCrit = this.GetWeaponCrit(sItem);
                if (Main.rand.Next(1, 101) <= weaponCrit)
                {
                    flag3 = true;
                }
                ItemID.BannerEffect bannerEffect;
                if (this.GetBannerBuffEffect(npc, out bannerEffect))
                {
                    num = (int)((float)num * bannerEffect.DamageDealt.Sample(Main.Difficulty));
                }
                if (this.parryDamageBuff && sItem.melee)
                {
                    num *= 5;
                    this.parryDamageBuff = false;
                    this.ClearBuff(198);
                }
                if (sItem.type == 426 && (float)npc.life >= (float)npc.lifeMax * 0.9f)
                {
                    num = (int)((float)num * 2.5f);
                }
                if (sItem.type == 5096)
                {
                    int num2 = 0;
                    if (this.FindBuffIndex(26) != -1)
                    {
                        num2 = 1;
                    }
                    if (this.FindBuffIndex(206) != -1)
                    {
                        num2 = 2;
                    }
                    if (this.FindBuffIndex(207) != -1)
                    {
                        num2 = 3;
                    }
                    float num3 = 1f + 0.05f * (float)num2;
                    num = (int)((float)num * num3);
                }
                if (sItem.type == 671)
                {
                    num = npc.KeyBrandStrike(this.whoAmI, num, itemRectangle.Center.ToVector2());
                }
                int num4 = Main.DamageVar((float)num, this.luck);
                float num5 = 0f;
                if (sItem.type == 5129 && npc.isLikeATownNPC)
                {
                    num5 = 1f;
                    if (npc.type == 18)
                    {
                        num4 *= 2;
                    }
                }
                if (sItem.type == 3258)
                {
                    ParticleOrchestraSettings particleOrchestraSettings = new ParticleOrchestraSettings
                    {
                        PositionInWorld = npc.Center
                    };
                    ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.SlapHand, particleOrchestraSettings, new int?(this.whoAmI));
                }
                if (sItem.type == 5382)
                {
                    ParticleOrchestraSettings particleOrchestraSettings2 = new ParticleOrchestraSettings
                    {
                        PositionInWorld = npc.Center
                    };
                    ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.WaffleIron, particleOrchestraSettings2, new int?(this.whoAmI));
                }
                if (sItem.type == 3351 && npc.type != 488 && npc.lifeMax > 5)
                {
                    int num6 = Item.NewItem(this.GetItemSource_Misc(ItemSourceID.LuckyCoin), (int)npc.Left.X + Main.rand.Next(npc.width), (int)npc.Top.Y + Main.rand.Next(npc.height), 1, 1, 71, 1 + this.RollBadLuck(25), false, 0, false);
                    WorldItem worldItem = Main.item[num6];
                    if (Main.netMode == 0)
                    {
                        worldItem.noGrabDelay = 100;
                    }
                    worldItem.timeLeftInWhichTheItemCannotBeTakenByEnemies = 100;
                    worldItem.velocity.Y = -2f - Main.rand.NextFloat() * 2f;
                    worldItem.velocity.X = (2f + Main.rand.NextFloat() * 2f) * (float)this.direction;
                    worldItem.favorited = false;
                    worldItem.newAndShiny = false;
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(148, -1, -1, null, num6, 0f, 0f, 0f, 0, 0, 0);
                    }
                    ParticleOrchestraSettings particleOrchestraSettings3 = new ParticleOrchestraSettings
                    {
                        PositionInWorld = npc.Center
                    };
                    ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.ClassyCane, particleOrchestraSettings3, new int?(this.whoAmI));
                }
                if (sItem.type == 5129)
                {
                    ParticleOrchestraSettings particleOrchestraSettings4 = new ParticleOrchestraSettings
                    {
                        PositionInWorld = npc.Center
                    };
                    ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.FlyMeal, particleOrchestraSettings4, new int?(this.whoAmI));
                    if (npc.townNPC)
                    {
                        AchievementsHelper.NotifyProgressionEvent(42);
                    }
                }
                if (sItem.type == 1166 || sItem.type == 1320)
                {
                    Vector2 vector4 = new Vector2((float)(itemRectangle.Left + Main.rand.Next(itemRectangle.Width)), (float)(itemRectangle.Top + Main.rand.Next(itemRectangle.Height / 2)));
                    Vector2 vector5 = new Vector2((float)this.direction * (1f + Main.rand.NextFloat() * 5f), -1f - Main.rand.NextFloat() * 3f);
                    int num7 = (int)((double)originalDamage * 0.75);
                    Projectile.NewProjectile(this.GetProjectileSource_Item(sItem), vector4, vector5, 21, num7, knockBack, Main.myPlayer, 0f, 0f, 0f, null);
                }
                this.StatusToNPC(sItem.type, npcIndex);
                if (npc.life > 5)
                {
                    this.OnHit(npc.Center.X, npc.Center.Y, npc);
                }
                num4 += npc.checkArmorPenetration(this.GetArmorPenetration(sItem.melee), num5);
                NPCKillAttempt npckillAttempt = new NPCKillAttempt(npc);
                int num8 = (int)npc.StrikeNPC(num4, knockBack, this.direction, flag3, false, false, this.whoAmI);
                this.ApplyNPCOnHitEffects(sItem, itemRectangle, num, knockBack, npcIndex, num4, num8);
                int num9 = BannerSystem.NPCtoBanner(npc.BannerID());
                if (num9 >= 0)
                {
                    this.lastCreatureHit = num9;
                }
                if (Main.netMode != 0)
                {
                    if (flag3)
                    {
                        NetMessage.SendData(28, -1, -1, null, npcIndex, (float)num4, knockBack, (float)this.direction, 1, 0, 0);
                    }
                    else
                    {
                        NetMessage.SendData(28, -1, -1, null, npcIndex, (float)num4, knockBack, (float)this.direction, 0, 0, 0);
                    }
                }
                if (this.accDreamCatcher)
                {
                    this.addDPS(num8);
                }
                this.SetMeleeHitCooldown(npcIndex, this.itemAnimation);
                if (npckillAttempt.DidNPCDie())
                {
                    this.OnKillNPC(ref npckillAttempt, sItem);
                }
                this.ApplyAttackCooldown();
            }
        }
References Terraria.NPC.BannerID(), Microsoft.Xna.Framework.Rectangle.Center, Terraria.Entity.Center, Terraria.NPC.checkArmorPenetration(), Terraria.ID.ItemID.BannerEffect.DamageDealt, Terraria.Main.DamageVar(), Terraria.DataStructures.NPCKillAttempt.DidNPCDie(), Terraria.Main.Difficulty, Terraria.NPC.dontTakeDamage, Terraria.NPC.friendly, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.NPC.immortal, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.NPC.isLikeATownNPC, Terraria.Main.item, Terraria.NPC.KeyBrandStrike(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Entity.Left, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Utils.LineRectangleDistance(), Terraria.ID.ItemSourceID.LuckyCoin, Terraria.Item.melee, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.GameContent.BannerSystem.NPCtoBanner(), Terraria.Entity.position, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.NetMessage.SendData(), Terraria.NPC.StrikeNPC(), Microsoft.Xna.Framework.Rectangle.Top, Terraria.Entity.Top, Terraria.NPC.townNPC, Terraria.Item.type, Terraria.NPC.type, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.ID.NPCID.Sets.ZappingJellyfish.