Terraria Decompiled: Terraria.Player.SmartSelectLookup
SmartSelectLookup()
bool Terraria.Player.SmartSelectLookup (out int selectedSlot) inline
Definition at line 15724 of file Player.cs.
        {
            if (!this.controlTorch)
            {
                selectedSlot = -1;
                this._lastSmartCursorToolStrategy = -1;
                return false;
            }
            int num;
            int num2;
            PlayerInput.smartSelectPointer.SmartSelectLookup_GetTargetTile(this, out num, out num2);
            int num3;
            bool flag;
            this.SmartSelect_GetToolStrategy(num, num2, out num3, out flag);
            if (PlayerInput.UsingGamepad && this._lastSmartCursorToolStrategy != -1)
            {
                num3 = this._lastSmartCursorToolStrategy;
            }
            if (num3 == 0 || num3 == 4)
            {
                float num4 = Math.Abs((float)Main.mouseX + Main.screenPosition.X - (this.position.X + (float)(this.width / 2)));
                float num5 = Math.Abs((float)Main.mouseY + Main.screenPosition.Y - (this.position.Y + (float)(this.height / 2))) * 1.3f;
                if ((float)Math.Sqrt((double)(num4 * num4 + num5 * num5)) > 200f)
                {
                    num3 = 5;
                }
            }
            this._lastSmartCursorToolStrategy = num3;
            selectedSlot = this.SmartSelect_PickToolForStrategy(num, num2, num3, flag);
            return true;
        }
References System.Math.Abs(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.screenPosition, Terraria.GameInput.SmartSelectGamepadPointer.SmartSelectLookup_GetTargetTile(), Terraria.GameInput.PlayerInput.smartSelectPointer, System.Math.Sqrt(), Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.