Terraria Decompiled: Terraria.Player.LimitPointToPlayerReachableArea
LimitPointToPlayerReachableArea()
void Terraria.Player.LimitPointToPlayerReachableArea (ref Vector2 pointPosition) inline
Definition at line 44726 of file Player.cs.
        {
            Rectangle rectangle = Utils.CenteredRectangle(base.Center, Main.MaxWorldViewSize.ToVector2());
            rectangle = WorldUtils.ClampToWorldBorders(rectangle);
            Vector2 vector = rectangle.Center.ToVector2();
            Vector2 vector2 = pointPosition - vector;
            float num = Math.Abs(vector2.X);
            float num2 = Math.Abs(vector2.Y);
            float num3 = 1f;
            float num4 = (float)rectangle.Width / 2f;
            if (num > num4)
            {
                float num5 = num4 / num;
                if (num3 > num5)
                {
                    num3 = num5;
                }
            }
            float num6 = (float)rectangle.Height / 2f;
            if (num2 > num6)
            {
                float num7 = num6 / num2;
                if (num3 > num7)
                {
                    num3 = num7;
                }
            }
            Vector2 vector3 = vector2 * num3;
            pointPosition = vector + vector3;
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Rectangle.Center, Terraria.Utils.CenteredRectangle(), Terraria.WorldBuilding.WorldUtils.ClampToWorldBorders(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.MaxWorldViewSize, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI_009_MagicMissiles(), and Terraria.Projectile.AI_009_MagicMissiles_Old().