Terraria Decompiled: Terraria.Player.UpdateSunScorch
UpdateSunScorch()
void Terraria.Player.UpdateSunScorch () inline private
Definition at line 27013 of file Player.cs.
        {
            if (this.whoAmI != Main.myPlayer)
            {
                return;
            }
            this.VampireSeedSunlightExposure();
            int num = this.sunScorchCounter;
            this.UpdateSunScorchValues();
            if (this.vampireBurningInSunlight && this.sunScorchCounter >= 120)
            {
                if (num < 120)
                {
                    int num2 = this.head;
                    int num3 = this.body;
                    int num4 = this.legs;
                    this.PlayerFrame();
                    if (this.head == 124 && this.body == 85 && this.legs == 72)
                    {
                        AchievementsHelper.NotifyProgressionEvent(33);
                    }
                    this.head = num2;
                    this.body = num3;
                    this.legs = num4;
                }
                Array.Clear(this.buffImmune, 0, BuffID.Count);
                if (!this.onFire)
                {
                    ParticleOrchestraSettings particleOrchestraSettings = new ParticleOrchestraSettings
                    {
                        PositionInWorld = base.Center
                    };
                    ParticleOrchestrator.RequestParticleSpawn(false, ParticleOrchestraType.VampireOnFire, particleOrchestraSettings, new int?(this.whoAmI));
                }
                this.AddBuff(24, 3, false);
                this.AddBuff(23, 3, false);
                this.AddBuff(32, 3, false);
                if (this.mount.Active)
                {
                    this.mount.TryDismount(this);
                }
                this.wingsLogic = 0;
                this.rocketBoots = 0;
            }
        }
References System.Array.Clear(), Terraria.ID.BuffID.Count, Terraria.Main.myPlayer, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), and Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn().