Terraria Decompiled: Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate
PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate()
void Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate (Vector3 tileDataCaches[,], int tileToCreate) inline private
Definition at line 39498 of file Player.cs.
        {
            if (this.autoPaint || this.autoActuator)
            {
                Tile tile = Main.tile[Player.tileTargetX, Player.tileTargetY];
                int num = 0;
                int num2 = 0;
                int num3 = 11;
                int num4 = 11;
                bool flag = TileID.Sets.Platforms[(int)tile.type];
                bool flag2 = (TileID.Sets.BasicChest[(int)tile.type] && TileID.Sets.BasicChest[tileToCreate]) || (TileID.Sets.BasicChestFake[(int)tile.type] && TileID.Sets.BasicChestFake[tileToCreate]) || (TileID.Sets.BasicDresser[(int)tile.type] && TileID.Sets.BasicDresser[tileToCreate]) || (TileID.Sets.Campfires[(int)tile.type] && TileID.Sets.Campfires[tileToCreate]) || (TileID.Sets.Torches[(int)tile.type] && TileID.Sets.Torches[tileToCreate]);
                bool flag3 = flag2 || (TileID.Sets.Platforms[(int)tile.type] && TileID.Sets.Platforms[tileToCreate]);
                if (!Main.tileFrameImportant[(int)tile.type] || flag)
                {
                    num2 = (num = 5);
                    num4 = (num3 = 6);
                }
                for (int i = num; i < num3; i++)
                {
                    for (int j = num2; j < num4; j++)
                    {
                        int num5 = Player.tileTargetX - 5 + i;
                        int num6 = Player.tileTargetY - 5 + j;
                        Tile tile2 = Main.tile[num5, num6];
                        if (tile2.active() && (int)tile2.type == tileToCreate)
{
                            Vector3 vector = tileDataCaches[i, j];
                            int num7 = (int)vector.X;
                            int num8 = (int)vector.Y;
                            int num9 = (int)vector.Z;
                            if ((flag3 || (int)tile2.type != num7) && (!flag2 || (int)tile2.type != num7 || (int)tile2.frameX != num8 || (int)tile2.frameY != num9))
{
                                if (this.autoPaint && this.builderAccStatus[3] == 0)
{
                                    this.TryPainting(num5, num6, false, false);
                                }
                                if (this.autoActuator && this.builderAccStatus[2] == 0)
{
                                    bool flag4 = Main.tile[num5, num6].active() && Main.tileSolid[(int)Main.tile[num5, num6].type] && !TileID.Sets.NotReallySolid[(int)Main.tile[num5, num6].type];
                                    ushort type = Main.tile[num5, num6].type;
                                    if (type <= 379)
{
                                        if (type == 314 || type == 379)
{
                                            goto IL_0274;
                                        }
                                    }
                                    else if (type - 386 <= 3 || type == 476)
{
                                        goto IL_0274;
                                    }
                                    IL_0277:
                                    if (!flag4)
{
                                        goto IL_02E8;
                                    }
                                    int num10 = this.FindItem(849);
                                    if (num10 <= -1 || !WorldGen.PlaceActuator(num5, num6))
{
                                        goto IL_02E8;
                                    }
                                    NetMessage.SendData(17, -1, -1, null, 8, (float)num5, (float)num6, 0f, 0, 0, 0);
                                    this.inventory[num10].stack--;
                                    if (this.inventory[num10].stack <= 0)
{
                                        this.inventory[num10].SetDefaults(0, null);
                                        goto IL_02E8;
                                    }
                                    goto IL_02E8;
                                    IL_0274:
                                    flag4 = false;
                                    goto IL_0277;
                                }
                            }
                        }
                        IL_02E8:;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicChestFake, Terraria.ID.TileID.Sets.BasicDresser, Terraria.ID.TileID.Sets.Campfires, Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.ID.TileID.Sets.NotReallySolid, Terraria.WorldGen.PlaceActuator(), Terraria.ID.TileID.Sets.Platforms, Terraria.NetMessage.SendData(), System.stack, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.ID.TileID.Sets.Torches, Terraria.Tile.type, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.