Terraria Decompiled: Terraria.Player.OnHit
OnHit()
void Terraria.Player.OnHit (float x, float y, Entity victim) inline
Definition at line 4143 of file Player.cs.
        {
            if (Main.myPlayer != this.whoAmI)
            {
                return;
            }
            bool flag = victim is NPC && (((NPC)victim).type == 488 || ((NPC)victim).SpawnedFromStatue);
            if (this.titaniumStormCooldown > 0)
            {
                flag = true;
            }
            if (victim is NPC)
            {
                Main.BigBossProgressBar.TryTracking(victim.whoAmI);
            }
            if (this.onHitTitaniumStorm && !flag)
            {
                this.titaniumStormCooldown = 10;
                this.AddBuff(306, 600, false);
                if (this.ownedProjectileCounts[908] < 7)
                {
                    this.ownedProjectileCounts[908]++;
                    Projectile.NewProjectile(this.GetProjectileSource_OnHit(victim, 4), base.Center, Vector2.Zero, 908, 50, 15f, this.whoAmI, 0f, 0f, 0f, null);
                }
            }
            if (this.onHitDodge && this.shadowDodgeTimer == 0)
            {
                this.AddBuff(59, 1800, false);
            }
            if (this.onHitRegen)
            {
                this.AddBuff(58, 300, false);
            }
            if (this.stardustMinion && victim is NPC)
            {
                for (int i = 0; i < 1000; i++)
                {
                    Projectile projectile = Main.projectile[i];
                    if (projectile.active && projectile.owner == this.whoAmI && projectile.type == 613 && projectile.localAI[1] <= 0f && Main.rand.Next(2) == 0)
                    {
                        Vector2 vector = new Vector2(x, y) - projectile.Center;
                        if (vector.Length() > 0f)
{
                            vector.Normalize();
                        }
                        vector *= 20f;
                        Projectile.NewProjectile(Projectile.InheritSource(projectile), projectile.Center.X, projectile.Center.Y, vector.X, vector.Y, 614, projectile.damage / 3, 0f, projectile.owner, 0f, (float)victim.whoAmI, 0f, null);
                        projectile.localAI[1] = (float)(30 + Main.rand.Next(4) * 10);
                    }
                }
            }
            if (this.onHitPetal && this.petalTimer == 0)
            {
                this.petalTimer = 20;
                float num = this.position.X + (float)(this.width / 2);
                int direction = this.direction;
                float num2 = Main.screenPosition.X;
                if (direction < 0)
                {
                    num2 += (float)Main.screenWidth;
                }
                float num3 = Main.screenPosition.Y;
                num3 += (float)Main.rand.Next(Main.screenHeight);
                Vector2 vector2 = new Vector2(num2, num3);
                float num4 = x - vector2.X;
                float num5 = y - vector2.Y;
                num4 += (float)Main.rand.Next(-50, 51) * 0.1f;
                num5 += (float)Main.rand.Next(-50, 51) * 0.1f;
                float num6 = (float)24;
                float num7 = (float)Math.Sqrt((double)(num4 * num4 + num5 * num5));
                num7 = num6 / num7;
                num4 *= num7;
                num5 *= num7;
                Projectile.NewProjectile(this.GetProjectileSource_OnHit(victim, 5), num2, num3, num4, num5, 221, 36, 0f, this.whoAmI, 0f, 0f, 0f, null);
            }
            if (this.crystalLeaf && this.petalTimer == 0)
            {
                for (int j = 0; j < 1000; j++)
                {
                    if (Main.projectile[j].owner == this.whoAmI && Main.projectile[j].type == 226)
                    {
                        this.petalTimer = 50;
                        float num8 = 12f;
                        Vector2 vector3 = new Vector2(Main.projectile[j].position.X + (float)this.width * 0.5f, Main.projectile[j].position.Y + (float)this.height * 0.5f);
                        float num9 = x - vector3.X;
                        float num10 = y - vector3.Y;
                        float num11 = (float)Math.Sqrt((double)(num9 * num9 + num10 * num10));
                        int num12 = 180;
                        float num13 = num8 * (float)num12;
                        if (num11 < num13)
{
                            num11 = num8 / num11;
                            num9 *= num11;
                            num10 *= num11;
                            Utils.ChaseResults chaseResults = Utils.GetChaseResults(Main.projectile[j].Center, num8 * (float)num12, victim.Center, victim.velocity);
                            if (chaseResults.InterceptionHappens && chaseResults.InterceptionTime <= 180f)
{
                                Vector2 vector4 = chaseResults.ChaserVelocity / (float)num12;
                                num9 = vector4.X;
                                num10 = vector4.Y;
                            }
                            Projectile.NewProjectile(this.GetProjectileSource_SetBonus(6), Main.projectile[j].Center.X - 4f, Main.projectile[j].Center.Y, num9, num10, 227, Player.crystalLeafDamage, (float)Player.crystalLeafKB, this.whoAmI, 0f, 0f, 0f, null);
                            return;
                        }
                    }
                }
            }
        }
References Terraria.Projectile.active, Terraria.Player.AddBuff(), Terraria.Main.BigBossProgressBar, Terraria.Entity.Center, Terraria.Player.crystalLeaf, Terraria.Player.crystalLeafDamage, Terraria.Player.crystalLeafKB, Terraria.Projectile.damage, Terraria.Entity.direction, Terraria.Utils.GetChaseResults(), Terraria.Player.GetProjectileSource_OnHit(), Terraria.Player.GetProjectileSource_SetBonus(), Terraria.Projectile.InheritSource(), Terraria.Utils.ChaseResults.InterceptionHappens, Terraria.Utils.ChaseResults.InterceptionTime, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Projectile.localAI, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Enums.NPC, Terraria.Player.onHitDodge, Terraria.Player.onHitPetal, Terraria.Player.onHitRegen, Terraria.Player.onHitTitaniumStorm, Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.Player.petalTimer, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Player.shadowDodgeTimer, System.Math.Sqrt(), Terraria.Player.stardustMinion, Terraria.Player.titaniumStormCooldown, Terraria.Projectile.type, Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Projectile.TryDoingOnHitEffects().