Terraria Decompiled: Terraria.Player.ItemCheck
ItemCheck()
void Terraria.Player.ItemCheck () inline
Definition at line 41678 of file Player.cs.
        {
            this.pendingItemReuse = false;
            if (this.CCed)
            {
                this.channel = false;
                this.itemAnimation = (this.itemAnimationMax = 0);
                return;
            }
            float heightOffsetHitboxCenter = this.HeightOffsetHitboxCenter;
            Item item = this.inventory[this.selectedItem];
            Player.ItemCheckContext itemCheckContext = default(Player.ItemCheckContext);
            bool flag = false;
            if (Main.myPlayer == this.whoAmI)
            {
                if (PlayerInput.ShouldFastUseItem)
                {
                    this.controlUseItem = true;
                    flag = true;
                }
                if (!this.cursorItemIconEnabled && item.stack > 0 && item.fishingPole > 0)
                {
                    int num;
                    int num2;
                    this.Fishing_GetBait(out num, out num2);
                    if (num2 > 0)
                    {
                        this.cursorItemIconEnabled = true;
                        this.cursorItemIconID = num2;
                        this.cursorItemIconPush = 6;
                    }
                }
                if (!this.cursorItemIconEnabled && item.stack > 0 && (item.type == 779 || item.type == 5134))
                {
                    for (int i = 54; i < 58; i++)
                    {
                        if (this.inventory[i].ammo == item.useAmmo && this.inventory[i].stack > 0)
{
                            this.cursorItemIconEnabled = true;
                            this.cursorItemIconID = this.inventory[i].type;
                            this.cursorItemIconPush = 10;
                            break;
                        }
                    }
                    if (!this.cursorItemIconEnabled)
                    {
                        for (int j = 0; j < 54; j++)
{
                            if (this.inventory[j].ammo == item.useAmmo && this.inventory[j].stack > 0)
{
                                this.cursorItemIconEnabled = true;
                                this.cursorItemIconID = this.inventory[j].type;
                                this.cursorItemIconPush = 10;
                                break;
                            }
                        }
                    }
                }
            }
            this.ItemCheck_HandleMount();
            int weaponDamage = this.GetWeaponDamage(item);
            this.ItemCheck_AutoReuseLogic(item);
            this.ItemCheck_HackHoldStyles(item);
            if (this.itemAnimation < 0)
            {
                this.itemAnimation = 0;
            }
            if (this.itemTime < 0)
            {
                this.itemTime = 0;
            }
            if (this.itemAnimation == 0)
            {
                this.itemAnimationMax = 0;
            }
            if (this.itemAnimation == 0 && this.reuseDelay > 0)
            {
                this.ApplyReuseDelay();
            }
            this.UpdatePlacementPreview(item);
            if (this.itemAnimation == 0 && this.altFunctionUse == 2)
            {
                this.altFunctionUse = 0;
            }
            if (item.type == 2269)
            {
                if (this.itemAnimation > 0 && !this.controlUseItem)
                {
                    this.itemAnimation--;
                    this.itemTime--;
                    if (this.itemAnimation <= 0)
                    {
                        this.itemAnimation = 0;
                    }
                    if (this.itemTime < 0)
                    {
                        this.itemTime = 0;
                    }
                    this.revolverCritChanceBonus++;
                }
                else if (Main.rand.Next(3) == 0)
                {
                    this.revolverCritChanceBonus -= 2;
                }
                float num3;
                float num4;
                float num5;
                float num6;
                float num7;
                float num8;
                int num9;
                int num10;
                int num11;
                float num12;
                item.TryGetPrefixStatMultipliersForItem((int)item.prefix, out num3, out num4, out num5, out num6, out num7, out num8, out num9, out num10, out num11, out num12);
                this.revolverCritChanceBonus = Utils.Clamp<int>(item.crit + this.revolverCritChanceBonus, num9, 20 + num9) - item.crit;
            }
            else if (Main.rand.Next(3) == 0)
            {
                this.revolverCritChanceBonus -= 2;
            }
            if (this.controlUseItem && this.releaseUseItem && this.itemAnimation == 0 && item.useStyle != 0 && !this.selectedItemState.HasBufferedChange)
            {
                if (this.altFunctionUse == 1)
                {
                    this.altFunctionUse = 2;
                }
                if (item.shoot == 0)
                {
                    this.itemRotation = 0f;
                }
                bool flag2 = this.ItemCheck_TryStartUse(item, false);
                if (this.whoAmI == Main.myPlayer)
                {
                    if (flag2 != this.lastItemUseAttemptSuccess)
                    {
                        this.lastItemUseAttemptSuccess = flag2;
                        NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                    }
                }
                else
                {
                    flag2 &= this.lastItemUseAttemptSuccess;
                }
                if (item.potion && flag2)
                {
                    this.ApplyPotionDelay(item);
                }
                if (item.mana > 0 && flag2 && this.whoAmI == Main.myPlayer && item.buffType != 0 && item.buffTime != 0)
                {
                    this.AddBuff(item.buffType, item.buffTime, false);
                }
                if (item.shoot <= 0 || !ProjectileID.Sets.MinionTargetingFeature[item.shoot] || this.altFunctionUse != 2)
                {
                    this.ItemCheck_ApplyPetBuffs(item);
                }
                if (this.whoAmI == Main.myPlayer && this.gravDir == 1f && item.mountType != -1 && flag2)
                {
                    this.mount.SetMount(item.mountType, this);
                }
                bool flag3 = item.shoot > 0 && ProjectileID.Sets.MinionTargetingFeature[item.shoot] && this.altFunctionUse == 2;
                bool flag4 = false;
                if (!flag3 && flag2 && this.whoAmI == Main.myPlayer && item.shoot == 1094 && this.TryUsingFoxsparksAbility())
                {
                    flag4 = true;
                }
                if (!flag4 && !flag3 && flag2 && this.whoAmI == Main.myPlayer && item.shoot >= 0 && item.shoot < (int)ProjectileID.Count && (ProjectileID.Sets.LightPet[item.shoot] || Main.projPet[item.shoot]))
                {
                    this.FreeUpPetsAndMinions(item);
                }
                if (!flag4 && flag2)
                {
                    this.ItemCheck_StartActualUse(item);
                }
            }
            bool flag5 = this.controlUseItem;
            if (this.mount.Active && this.mount.Type == 8)
            {
                flag5 = this.controlUseItem || this.controlUseTile;
            }
            if (ItemID.Sets.IsAKite[item.type])
            {
                flag5 = this.controlUseTile;
            }
            if (this.whoAmI == Main.myPlayer && Main.LocalPlayerHasPendingInventoryActions())
            {
                flag5 = false;
            }
            if (this.selectedItemState.HasBufferedChange)
            {
                flag5 = false;
            }
            if (!flag5)
            {
                this.channel = false;
            }
            if (this.itemAnimation > 0)
            {
                if (item.mana > 0)
                {
                    this.ItemCheck_ApplyManaRegenDelay(item);
                }
                this.itemAnimation--;
                if (this.itemAnimation == 0 && this.whoAmI == Main.myPlayer)
                {
                    PlayerInput.TryEndingFastUse();
                }
                if (this.itemAnimation == 0 && this.reuseDelay == 0 && this.controlUseItem && this.releaseUseItem)
                {
                    this.pendingItemReuse = true;
                }
            }
            if (this.itemAnimation == 0 && item.IsAir && item.type != 0)
            {
                item.TurnToAir(false);
                this.pendingItemReuse = false;
            }
            this.releaseUseItem = !this.controlUseItem;
            if (this.itemTime > 0)
            {
                this.itemTime--;
                if (this.ItemTimeIsZero && this.whoAmI == Main.myPlayer && !this.JustDroppedAnItem && this.IsAllowedToHoldItems)
                {
                    int type = item.type;
                    if (type == 65 || type == 724 || type == 989 || type == 1226)
                    {
                        this.EmitMaxManaEffect();
                    }
                }
            }
            Rectangle rectangle = this.AnimatePlayerAndGetItemFrame(heightOffsetHitboxCenter, item);
            if (!this.JustDroppedAnItem && this.IsAllowedToHoldItems)
            {
                this.ItemCheck_EmitHeldItemLight(item);
                this.ItemCheck_EmitFoodParticles(item);
                this.ItemCheck_EmitDrinkParticles(item);
                if (this.whoAmI == Main.myPlayer)
                {
                    this.ItemCheck_OwnerOnlyCode(ref itemCheckContext, item, weaponDamage, rectangle);
                }
                if (this.ItemTimeIsZero && this.itemAnimation > 0)
                {
                    if (item.hairDye >= 0)
                    {
                        this.ApplyItemTime(item);
                        if (this.whoAmI == Main.myPlayer)
{
                            this.hairDye = (byte)item.hairDye;
                            NetMessage.SendData(4, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                    if (item.healLife > 0 || item.healMana > 0)
                    {
                        this.ApplyLifeAndOrMana(item);
                        this.ApplyItemTime(item);
                        if (Main.myPlayer == this.whoAmI && item.type == 126 && this.breath == 0)
{
                            AchievementsHelper.HandleSpecialEvent(this, 25);
                        }
                    }
                    if (item.buffType > 0)
                    {
                        if (this.whoAmI == Main.myPlayer && item.buffType != 90 && item.buffType != 27)
{
                            this.AddBuff(item.buffType, item.buffTime, false);
                        }
                        this.ApplyItemTime(item);
                    }
                    if (item.type == 678)
                    {
                        if (Main.getGoodWorld)
{
                            this.ApplyItemTime(item);
                            if (this.whoAmI == Main.myPlayer)
{
                                for (int k = 0; k < 3; k++)
{
                                    int num13 = 0;
                                    int num14 = 108000;
                                    switch (Main.rand.Next(18))
{
                                    case 0:
                                        num13 = 16;
                                        break;
                                    case 1:
                                        num13 = 111;
                                        break;
                                    case 2:
                                        num13 = 114;
                                        break;
                                    case 3:
                                        num13 = 8;
                                        break;
                                    case 4:
                                        num13 = 105;
                                        break;
                                    case 5:
                                        num13 = 17;
                                        break;
                                    case 6:
                                        num13 = 116;
                                        break;
                                    case 7:
                                        num13 = 5;
                                        break;
                                    case 8:
                                        num13 = 113;
                                        break;
                                    case 9:
                                        num13 = 7;
                                        break;
                                    case 10:
                                        num13 = 6;
                                        break;
                                    case 11:
                                        num13 = 104;
                                        break;
                                    case 12:
                                        num13 = 115;
                                        break;
                                    case 13:
                                        num13 = 2;
                                        break;
                                    case 14:
                                        num13 = 9;
                                        break;
                                    case 15:
                                        num13 = 3;
                                        break;
                                    case 16:
                                        num13 = 117;
                                        break;
                                    case 17:
                                        num13 = 1;
                                        break;
                                    }
                                    this.AddBuff(num13, num14, false);
                                }
                            }
                        }
                        else
{
                            this.ApplyItemTime(item);
                            if (this.whoAmI == Main.myPlayer)
{
                                this.AddBuff(20, 216000, false);
                                this.AddBuff(22, 216000, false);
                                this.AddBuff(23, 216000, false);
                                this.AddBuff(24, 216000, false);
                                this.AddBuff(30, 216000, false);
                                this.AddBuff(31, 216000, false);
                                this.AddBuff(32, 216000, false);
                                this.AddBuff(33, 216000, false);
                                this.AddBuff(35, 216000, false);
                                this.AddBuff(36, 216000, false);
                                this.AddBuff(68, 216000, false);
                            }
                        }
                    }
                }
                if ((item.type == 50 || item.type == 3124 || item.type == 3199 || item.type == 5358) && this.itemAnimation > 0)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        Dust.NewDust(this.position, this.width, this.height, 15, 0f, 0f, 150, default(Color), 1.1f);
                    }
                    if (this.ItemTimeIsZero)
                    {
                        this.ApplyItemTime(item);
                    }
                    else if (this.itemTime == item.useTime / 2)
                    {
                        for (int l = 0; l < 70; l++)
{
                            Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X * 0.5f, this.velocity.Y * 0.5f, 150, default(Color), 1.5f);
                        }
                        this.RemoveAllGrapplingHooks();
                        this.Spawn(PlayerSpawnContext.RecallFromItem);
                        for (int m = 0; m < 70; m++)
{
                            Dust.NewDust(this.position, this.width, this.height, 15, 0f, 0f, 150, default(Color), 1.5f);
                        }
                    }
                }
                if ((item.type == 4263 || item.type == 5360) && this.itemAnimation > 0)
                {
                    Vector2 vector = Vector2.UnitY.RotatedBy((double)((float)this.itemAnimation * 6.2831855f / 30f), default(Vector2)) * new Vector2(15f, 0f);
                    for (int n = 0; n < 2; n++)
                    {
                        if (Main.rand.Next(3) == 0)
{
                            Dust dust = Dust.NewDustPerfect(base.Bottom + vector, Dust.dustWater(), null, 0, default(Color), 1f);
                            dust.velocity.Y = dust.velocity.Y * 0f;
                            dust.velocity.Y = dust.velocity.Y - 4.5f;
                            dust.velocity.X = dust.velocity.X * 1.5f;
                            dust.scale = 0.8f;
                            dust.alpha = 130;
                            dust.noGravity = true;
                            dust.fadeIn = 1.1f;
                        }
                    }
                    if (this.ItemTimeIsZero)
                    {
                        this.ApplyItemTime(item);
                    }
                    else if (this.itemTime == item.useTime / 2)
                    {
                        if (Main.netMode == 0)
{
                            this.MagicConch();
                        }
                        else if (Main.netMode == 1 && this.whoAmI == Main.myPlayer)
{
                            NetMessage.SendData(73, -1, -1, null, 1, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                }
                if ((item.type == 4819 || item.type == 5361) && this.itemAnimation > 0)
                {
                    Vector2 vector2 = Vector2.UnitY.RotatedBy((double)((float)this.itemAnimation * 6.2831855f / 30f), default(Vector2)) * new Vector2(15f, 0f);
                    for (int num15 = 0; num15 < 2; num15++)
                    {
                        if (Main.rand.Next(3) == 0)
{
                            Dust dust2 = Dust.NewDustPerfect(base.Bottom + vector2, 35, null, 0, default(Color), 1f);
                            dust2.velocity.Y = dust2.velocity.Y * 0f;
                            dust2.velocity.Y = dust2.velocity.Y - 4.5f;
                            dust2.velocity.X = dust2.velocity.X * 1.5f;
                            dust2.scale = 0.8f;
                            dust2.alpha = 130;
                            dust2.noGravity = true;
                            dust2.fadeIn = 1.1f;
                        }
                    }
                    if (this.ItemTimeIsZero)
                    {
                        this.ApplyItemTime(item);
                    }
                    else if (this.itemTime == item.useTime / 2)
                    {
                        if (Main.netMode == 0)
{
                            this.DemonConch();
                        }
                        else if (Main.netMode == 1 && this.whoAmI == Main.myPlayer)
{
                            NetMessage.SendData(73, -1, -1, null, 2, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                }
                if (item.type == 5359 && this.itemAnimation > 0)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        int num16 = Main.rand.Next(4);
                        Color color = Color.Green;
                        switch (num16)
{
                        case 0:
                        case 1:
                            color = new Color(100, 255, 100);
                            break;
                        case 2:
                            color = Color.Yellow;
                            break;
                        case 3:
                            color = Color.White;
                            break;
                        }
                        Dust dust3 = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(base.Hitbox), 267, null, 0, default(Color), 1f);
                        dust3.noGravity = true;
                        dust3.color = color;
                        dust3.velocity *= 2f;
                        dust3.scale = 0.8f + Main.rand.NextFloat() * 0.6f;
                    }
                    if (this.ItemTimeIsZero)
                    {
                        this.ApplyItemTime(item);
                    }
                    else if (this.itemTime == item.useTime / 2)
                    {
                        if (Main.netMode == 0)
{
                            this.Shellphone_Spawn();
                        }
                        else if (Main.netMode == 1 && this.whoAmI == Main.myPlayer)
{
                            NetMessage.SendData(73, -1, -1, null, 3, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                }
                if (item.type == 2350 && this.itemAnimation > 0)
                {
                    if (this.ItemTimeIsZero)
                    {
                        this.ApplyItemTime(item);
                        SoundEngine.PlaySound(SoundID.Item3, this.position, 0f, 1f);
                        for (int num17 = 0; num17 < 10; num17++)
{
                            Main.dust[Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                        }
                    }
                    else if (this.itemTime == 20)
                    {
                        SoundEngine.PlaySound(this.HeldItem.UseSound, this.position, 0f, 1f);
                        for (int num18 = 0; num18 < 70; num18++)
{
                            Main.dust[Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                        }
                        this.RemoveAllGrapplingHooks();
                        bool flag6 = this.immune;
                        int num19 = this.immuneTime;
                        this.Spawn(PlayerSpawnContext.RecallFromItem);
                        this.immune = flag6;
                        this.immuneTime = num19;
                        for (int num20 = 0; num20 < 70; num20++)
{
                            Main.dust[Dust.NewDust(this.position, this.width, this.height, 15, 0f, 0f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                        }
                        if (item.stack > 0)
{
                            item.stack--;
                        }
                    }
                }
                if (item.type == 4870 && this.itemAnimation > 0)
                {
                    if (this.ItemTimeIsZero)
                    {
                        this.ApplyItemTime(item);
                        SoundEngine.PlaySound(SoundID.Item3, this.position, 0f, 1f);
                        for (int num21 = 0; num21 < 10; num21++)
{
                            Main.dust[Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                        }
                    }
                    else if (this.itemTime == 20)
                    {
                        SoundEngine.PlaySound(this.HeldItem.UseSound, this.position, 0f, 1f);
                        for (int num22 = 0; num22 < 70; num22++)
{
                            Main.dust[Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                        }
                        if (this.whoAmI == Main.myPlayer)
{
                            this.DoPotionOfReturnTeleportationAndSetTheComebackPoint();
                        }
                        for (int num23 = 0; num23 < 70; num23++)
{
                            Main.dust[Dust.NewDust(this.position, this.width, this.height, 15, 0f, 0f, 150, Color.Cyan, 1.2f)].velocity *= 0.5f;
                        }
                        if (item.stack > 0)
{
                            item.stack--;
                        }
                    }
                }
                if (item.type == 2351 && this.itemAnimation > 0)
                {
                    if (this.ItemTimeIsZero)
                    {
                        this.ApplyItemTime(item);
                    }
                    else if (this.itemTime == 2)
                    {
                        if (Main.netMode == 0)
{
                            this.TeleportationPotion();
                        }
                        else if (Main.netMode == 1 && this.whoAmI == Main.myPlayer)
{
                            NetMessage.SendData(73, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                        }
                        if (item.stack > 0)
{
                            item.stack--;
                        }
                    }
                }
                if (item.type == 2756 && this.itemAnimation > 0)
                {
                    if (this.ItemTimeIsZero)
                    {
                        this.ApplyItemTime(item);
                    }
                    else if (this.itemTime == 2)
                    {
                        if (this.whoAmI == Main.myPlayer)
{
                            this.Male = !this.Male;
                            int num24 = this.voiceVariant;
                            if (num24 != 1)
{
                                if (num24 == 2)
{
                                    this.voiceVariant = 1;
                                }
                            }
                            else
{
                                this.voiceVariant = 2;
                            }
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(4, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                            }
                        }
                        if (item.stack > 0)
{
                            item.stack--;
                        }
                    }
                    else
                    {
                        float num25 = (float)item.useTime;
                        num25 = (num25 - (float)this.itemTime) / num25;
                        float num26 = 15f;
                        float num27 = 44f;
                        float num28 = 9.424778f;
                        Vector2 vector3 = new Vector2(num26, 0f).RotatedBy((double)(num28 * num25), default(Vector2));
                        vector3.X *= (float)this.direction;
                        for (int num29 = 0; num29 < 2; num29++)
{
                            int num30 = 221;
                            if (num29 == 1)
{
                                vector3.X *= -1f;
                                num30 = 219;
                            }
                            Vector2 vector4 = new Vector2(vector3.X, num27 * (1f - num25) - num27 + (float)(this.height / 2));
                            vector4 += base.Center;
                            int num31 = Dust.NewDust(vector4, 0, 0, num30, 0f, 0f, 100, default(Color), 1f);
                            Main.dust[num31].position = vector4;
                            Main.dust[num31].noGravity = true;
                            Main.dust[num31].velocity = Vector2.Zero;
                            Main.dust[num31].scale = 1.3f;
                            Main.dust[num31].customData = this;
                        }
                    }
                }
                if (this.whoAmI == Main.myPlayer)
                {
                    if ((this.itemTimeMax != 0 && this.itemTime == this.itemTimeMax) | (!item.IsAir && item.IsNotTheSameAs(this.lastVisualizedSelectedItem)))
                    {
                        this.lastVisualizedSelectedItem = item.Clone();
                    }
                }
                else
                {
                    this.lastVisualizedSelectedItem = item.Clone();
                }
                if (this.whoAmI == Main.myPlayer)
                {
                    if (!this.dontConsumeWand && this.itemTimeMax != 0 && this.itemTime == this.itemTimeMax && item.tileWand > 0)
                    {
                        int tileWand = item.tileWand;
                        int num32 = 0;
                        while (num32 < 58)
{
                            if (tileWand == this.inventory[num32].type && this.inventory[num32].stack > 0)
{
                                this.inventory[num32].stack--;
                                if (this.inventory[num32].stack <= 0)
{
                                    this.inventory[num32] = new Item();
                                    break;
                                }
                                break;
                            }
                            else
{
                                num32++;
                            }
                        }
                    }
                    if (this.itemTimeMax != 0 && this.itemTime == this.itemTimeMax && item.consumable && !itemCheckContext.SkipItemConsumption)
                    {
                        bool flag7 = true;
                        if (item.ranged)
{
                            if (this.huntressAmmoCost90 && Main.rand.Next(10) == 0)
{
                                flag7 = false;
                            }
                            if (this.chloroAmmoCost80 && Main.rand.Next(5) == 0)
{
                                flag7 = false;
                            }
                            if (this.ammoCost80 && Main.rand.Next(5) == 0)
{
                                flag7 = false;
                            }
                            if (this.ammoCost75 && Main.rand.Next(4) == 0)
{
                                flag7 = false;
                            }
                        }
                        if (item.IsACoin)
{
                            flag7 = true;
                        }
                        if (!this.CanConsumeConsumableItem(item))
{
                            flag7 = false;
                        }
                        bool? flag8 = ItemID.Sets.ForceConsumption[item.type];
                        if (flag8 != null)
{
                            flag7 = flag8.Value;
                        }
                        if (flag7)
{
                            if (item.stack > 0)
{
                                item.stack--;
                            }
                            if (item.stack <= 0)
{
                                this.itemTime = this.itemAnimation;
                            }
                        }
                    }
                    if (this.selectedItem == 58 && this.itemAnimation > 0)
                    {
                        Main.mouseItem = this.inventory[this.selectedItem].Clone();
                    }
                }
            }
            else if (this.whoAmI == Main.myPlayer && !this.JustDroppedAnItem && this.mount.DismountOnItemUse)
            {
                this.ItemCheck_OwnerOnlyCode(ref itemCheckContext, item, weaponDamage, rectangle);
            }
            if (this.itemAnimation == 0)
            {
                this.JustDroppedAnItem = false;
            }
            if (this.whoAmI == Main.myPlayer && flag)
            {
                PlayerInput.TryEndingFastUse();
            }
        }
References Terraria.Utils.Clamp(), Terraria.ID.ProjectileID.Count, Terraria.Dust.customData, Microsoft.Xna.Framework.Color.Cyan, Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.ID.ItemID.Sets.ForceConsumption, Terraria.Main.getGoodWorld, Microsoft.Xna.Framework.Color.Green, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.ID.ItemID.Sets.IsAKite, System.item, Terraria.ID.SoundID.Item3, Terraria.ID.ProjectileID.Sets.LightPet, Terraria.Main.LocalPlayerHasPendingInventoryActions(), Terraria.ID.ProjectileID.Sets.MinionTargetingFeature, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.Main.projPet, Terraria.Main.rand, Terraria.Dust.scale, Terraria.NetMessage.SendData(), Terraria.GameInput.PlayerInput.ShouldFastUseItem, Terraria.Player.ItemCheckContext.SkipItemConsumption, System.stack, Terraria.GameInput.PlayerInput.TryEndingFastUse(), Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Dust.velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Color.Yellow, and Microsoft.Xna.Framework.Vector2.Zero.