Terraria Decompiled: Terraria.Player.ItemCheck_EmitUseVisuals
ItemCheck_EmitUseVisuals()
void Terraria.Player.ItemCheck_EmitUseVisuals (Item sItem, Rectangle itemRectangle) inline private
Definition at line 43971 of file Player.cs.
        {
            if (sItem.type == 989 && Main.rand.Next(5) == 0)
            {
                int num = Main.rand.Next(3);
                if (num == 0)
                {
                    num = 15;
                }
                else if (num == 1)
                {
                    num = 57;
                }
                else
                {
                    num = 58;
                }
                int num2 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, num, (float)(this.direction * 2), 0f, 150, default(Color), 1.3f);
                Main.dust[num2].velocity *= 0.2f;
            }
            if (sItem.type == 2880 && Main.rand.Next(2) == 0)
            {
                int num3 = Utils.SelectRandom<int>(Main.rand, new int[] { 226, 229 });
                int num4 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, num3, (float)(this.direction * 2), 0f, 150, default(Color), 1f);
                Main.dust[num4].velocity *= 0.2f;
                Main.dust[num4].noGravity = true;
            }
            if ((sItem.type == 44 || sItem.type == 45 || sItem.type == 103 || sItem.type == 104) && Main.rand.Next(15) == 0)
            {
                Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, (float)(this.direction * 2), 0f, 150, default(Color), 1.3f);
            }
            if (sItem.type == 46 && Main.rand.Next(15) == 0)
            {
                Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, (float)(this.direction * 2), 0f, 150, default(Color), 1.3f);
            }
            if (sItem.type == 273 || sItem.type == 675)
            {
                if (Main.rand.Next(5) == 0)
                {
                    Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, (float)(this.direction * 2), 0f, 150, default(Color), 1.4f);
                }
                int num5 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 27, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 1.2f);
                Main.dust[num5].noGravity = true;
                Dust dust = Main.dust[num5];
                dust.velocity.X = dust.velocity.X / 2f;
                Dust dust2 = Main.dust[num5];
                dust2.velocity.Y = dust2.velocity.Y / 2f;
            }
            if (sItem.type == 723 && Main.rand.Next(2) == 0)
            {
                int num6 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 64, 0f, 0f, 150, default(Color), 1.2f);
                Main.dust[num6].noGravity = true;
            }
            if (sItem.type == 65)
            {
                if (Main.rand.Next(5) == 0)
                {
                    Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 58, 0f, 0f, 150, default(Color), 1.2f);
                }
                if (Main.rand.Next(10) == 0)
                {
                    Gore.NewGore(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), default(Vector2), Main.rand.Next(16, 18), 1f);
                }
            }
            if (sItem.type == 3065)
            {
                int num7 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 58, 0f, 0f, 150, default(Color), 1.2f);
                Main.dust[num7].velocity *= 0.5f;
                if (Main.rand.Next(8) == 0)
                {
                    int num8 = Gore.NewGore(new Vector2((float)itemRectangle.Center.X, (float)itemRectangle.Center.Y), default(Vector2), 16, 1f);
                    Main.gore[num8].velocity *= 0.5f;
                    Main.gore[num8].velocity += new Vector2((float)this.direction, 0f);
                }
            }
            if (sItem.type == 190)
            {
                int num9 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 40, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 0, default(Color), 1.2f);
                Main.dust[num9].noGravity = true;
            }
            else if (sItem.type == 213 || sItem.type == 5295)
            {
                int num10 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 3, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 0, default(Color), 1.2f);
                Main.dust[num10].noGravity = true;
            }
            if (sItem.type == 121)
            {
                for (int i = 0; i < 2; i++)
                {
                    Vector2 vector;
                    Vector2 vector2;
                    this.GetPointOnSwungItemPath(70f, 70f, 0.2f + 0.8f * Main.rand.NextFloat(), this.GetAdjustedItemScale(sItem), out vector, out vector2);
                    Vector2 vector3 = vector2.RotatedBy((double)(1.5707964f * (float)this.direction * this.gravDir), default(Vector2));
                    Dust.NewDustPerfect(vector, 6, new Vector2?(vector3 * 4f), 100, default(Color), 2.5f).noGravity = true;
                }
            }
            if (sItem.type == 122 || sItem.type == 217)
            {
                int num11 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 1.9f);
                Main.dust[num11].noGravity = true;
            }
            if (sItem.type == 155)
            {
                int num12 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 172, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 0.9f);
                Main.dust[num12].noGravity = true;
                Main.dust[num12].velocity *= 0.1f;
            }
            if (sItem.type == 676 && Main.rand.Next(3) == 0)
            {
                int num13 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 67, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 90, default(Color), 1.5f);
                Main.dust[num13].noGravity = true;
                Main.dust[num13].velocity *= 0.2f;
            }
            if (sItem.type == 3063)
            {
                int num14 = Dust.NewDust(itemRectangle.TopLeft(), itemRectangle.Width, itemRectangle.Height, 66, 0f, 0f, 150, Color.Transparent, 0.85f);
                Main.dust[num14].color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f, byte.MaxValue);
                Main.dust[num14].noGravity = true;
                Main.dust[num14].velocity /= 2f;
            }
            if (sItem.type == 3823)
            {
                Dust dust3 = Dust.NewDustDirect(itemRectangle.TopLeft(), itemRectangle.Width, itemRectangle.Height, 6, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, Color.Transparent, 0.7f);
                dust3.noGravity = true;
                dust3.velocity *= 2f;
                dust3.fadeIn = 0.9f;
            }
            if (sItem.type == 724 && Main.rand.Next(5) == 0)
            {
                int num15 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 67, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 90, default(Color), 1.5f);
                Main.dust[num15].noGravity = true;
                Main.dust[num15].velocity *= 0.2f;
            }
            if (sItem.type >= 795 && sItem.type <= 802)
            {
                for (int j = 0; j < 2; j++)
                {
                    Vector2 vector4;
                    Vector2 vector5;
                    this.GetPointOnSwungItemPath(60f, 60f, 0.2f + 0.8f * Main.rand.NextFloat(), this.GetAdjustedItemScale(sItem), out vector4, out vector5);
                    Vector2 vector6 = vector5.RotatedBy((double)(1.5707964f * (float)this.direction * this.gravDir), default(Vector2));
                    Dust.NewDustPerfect(vector4, 5, new Vector2?(vector6 * 2f), 100, default(Color), 0.7f + Main.rand.NextFloat() * 0.6f);
                    if (Main.rand.Next(20) == 0)
                    {
                        int num16 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 115, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 140, default(Color), 0.7f);
                        Main.dust[num16].position = vector4;
                        Main.dust[num16].fadeIn = 1.2f;
                        Main.dust[num16].noGravity = true;
                        Main.dust[num16].velocity *= 0.25f;
                        Main.dust[num16].velocity += vector6 * 5f;
                    }
                }
            }
            if (sItem.type == 367)
            {
                if (Main.rand.Next(3) == 0)
                {
                    int num17 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 57, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 1.1f);
                    Main.dust[num17].noGravity = true;
                    Dust dust4 = Main.dust[num17];
                    dust4.velocity.X = dust4.velocity.X / 2f;
                    Dust dust5 = Main.dust[num17];
                    dust5.velocity.Y = dust5.velocity.Y / 2f;
                    Dust dust6 = Main.dust[num17];
                    dust6.velocity.X = dust6.velocity.X + (float)(this.direction * 2);
                }
                if (Main.rand.Next(4) == 0)
                {
                    int num17 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 43, 0f, 0f, 254, default(Color), 0.3f);
                    Main.dust[num17].velocity *= 0f;
                }
            }
            else if (sItem.type != 368)
            {
                int type = sItem.type;
            }
            if (!sItem.noUseGraphic && (sItem.type == 5670 || sItem.type == 5671 || sItem.type == 5535 || sItem.type == 5536 || sItem.type == 4258 || sItem.type == 4259 || (sItem.type >= 198 && sItem.type <= 203) || (sItem.type >= 3764 && sItem.type <= 3769)))
            {
                Color color = Item.GetPhaseColor(sItem.shoot, false) * 0.5f;
                float num18 = (float)color.R / 255f;
                float num19 = (float)color.G / 255f;
                float num20 = (float)color.B / 255f;
                Lighting.AddLight((int)((this.itemLocation.X + 6f + this.velocity.X) / 16f), (int)((this.itemLocation.Y - 14f) / 16f), num18, num19, num20);
            }
            if (this.frostBurn && sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && Main.rand.Next(2) == 0)
            {
                int num21 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 135, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 2.5f);
                Main.dust[num21].noGravity = true;
                Main.dust[num21].velocity *= 0.7f;
                Dust dust7 = Main.dust[num21];
                dust7.velocity.Y = dust7.velocity.Y - 0.5f;
            }
            if (sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && this.meleeEnchant > 0)
            {
                if (this.meleeEnchant == 1)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        int num22 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 171, 0f, 0f, 100, default(Color), 1f);
                        Main.dust[num22].noGravity = true;
                        Main.dust[num22].fadeIn = 1.5f;
                        Main.dust[num22].velocity *= 0.25f;
                    }
                }
                else if (this.meleeEnchant == 2)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        int num23 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 75, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 2.5f);
                        Main.dust[num23].noGravity = true;
                        Main.dust[num23].velocity *= 0.7f;
                        Dust dust8 = Main.dust[num23];
                        dust8.velocity.Y = dust8.velocity.Y - 0.5f;
                    }
                }
                else if (this.meleeEnchant == 3)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        int num24 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 2.5f);
                        Main.dust[num24].noGravity = true;
                        Main.dust[num24].velocity *= 0.7f;
                        Dust dust9 = Main.dust[num24];
                        dust9.velocity.Y = dust9.velocity.Y - 0.5f;
                    }
                }
                else if (this.meleeEnchant == 4)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        int num25 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 57, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 1.1f);
                        Main.dust[num25].noGravity = true;
                        Dust dust10 = Main.dust[num25];
                        dust10.velocity.X = dust10.velocity.X / 2f;
                        Dust dust11 = Main.dust[num25];
                        dust11.velocity.Y = dust11.velocity.Y / 2f;
                    }
                }
                else if (this.meleeEnchant == 5)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        int num26 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 169, 0f, 0f, 100, default(Color), 1f);
                        Dust dust12 = Main.dust[num26];
                        dust12.velocity.X = dust12.velocity.X + (float)this.direction;
                        Dust dust13 = Main.dust[num26];
                        dust13.velocity.Y = dust13.velocity.Y + 0.2f;
                        Main.dust[num26].noGravity = true;
                    }
                }
                else if (this.meleeEnchant == 6)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        int num27 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 135, 0f, 0f, 100, default(Color), 1f);
                        Dust dust14 = Main.dust[num27];
                        dust14.velocity.X = dust14.velocity.X + (float)this.direction;
                        Dust dust15 = Main.dust[num27];
                        dust15.velocity.Y = dust15.velocity.Y + 0.2f;
                        Main.dust[num27].noGravity = true;
                    }
                }
                else if (this.meleeEnchant == 7)
                {
                    if (Main.rand.Next(20) == 0)
                    {
                        int num28 = Main.rand.Next(139, 143);
                        int num29 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, num28, this.velocity.X, this.velocity.Y, 0, default(Color), 1.2f);
                        Dust dust16 = Main.dust[num29];
                        dust16.velocity.X = dust16.velocity.X * (1f + (float)Main.rand.Next(-50, 51) * 0.01f);
                        Dust dust17 = Main.dust[num29];
                        dust17.velocity.Y = dust17.velocity.Y * (1f + (float)Main.rand.Next(-50, 51) * 0.01f);
                        Dust dust18 = Main.dust[num29];
                        dust18.velocity.X = dust18.velocity.X + (float)Main.rand.Next(-50, 51) * 0.05f;
                        Dust dust19 = Main.dust[num29];
                        dust19.velocity.Y = dust19.velocity.Y + (float)Main.rand.Next(-50, 51) * 0.05f;
                        Main.dust[num29].scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
                    }
                    if (Main.rand.Next(40) == 0)
                    {
                        int num30 = Main.rand.Next(276, 283);
                        int num31 = Gore.NewGore(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), this.velocity, num30, 1f);
                        Gore gore = Main.gore[num31];
                        gore.velocity.X = gore.velocity.X * (1f + (float)Main.rand.Next(-50, 51) * 0.01f);
                        Gore gore2 = Main.gore[num31];
                        gore2.velocity.Y = gore2.velocity.Y * (1f + (float)Main.rand.Next(-50, 51) * 0.01f);
                        Main.gore[num31].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                        Gore gore3 = Main.gore[num31];
                        gore3.velocity.X = gore3.velocity.X + (float)Main.rand.Next(-50, 51) * 0.05f;
                        Gore gore4 = Main.gore[num31];
                        gore4.velocity.Y = gore4.velocity.Y + (float)Main.rand.Next(-50, 51) * 0.05f;
                    }
                }
                else if (this.meleeEnchant == 8 && Main.rand.Next(4) == 0)
                {
                    int num32 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 46, 0f, 0f, 100, default(Color), 1f);
                    Main.dust[num32].noGravity = true;
                    Main.dust[num32].fadeIn = 1.5f;
                    Main.dust[num32].velocity *= 0.25f;
                }
            }
            if (this.magmaStone && sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && Main.rand.Next(3) != 0)
            {
                int num33 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 2.5f);
                Main.dust[num33].noGravity = true;
                Dust dust20 = Main.dust[num33];
                dust20.velocity.X = dust20.velocity.X * 2f;
                Dust dust21 = Main.dust[num33];
                dust21.velocity.Y = dust21.velocity.Y * 2f;
            }
            if (sItem.type == 1304 && Main.rand.Next(60) == 0 && ChildSafety.Disabled)
            {
                Gore.NewGore(new Vector2((float)(itemRectangle.Left + itemRectangle.Width / 2), (float)(itemRectangle.Top + itemRectangle.Height / 2)), new Vector2((float)this.direction * (2f + Main.rand.NextFloat() * 3f), -2f - Main.rand.NextFloat() * 3f), Main.rand.Next(3, 6), 1f);
            }
            if (this.mount.Active && (this.mount.Type == 62 || this.mount.Type == 63) && sItem.melee && !sItem.noMelee && !sItem.noUseGraphic)
            {
                Vector3 vector7 = ((this.mount.Type == 63) ? new Vector3(0.6f, 0.3f, 0.1f) : new Vector3(0.5f, 0.1f, 0.6f));
                Lighting.AddLight(itemRectangle.Center.ToVector2(), vector7 * 0.5f);
                if (Main.rand.Next(3) != 0)
                {
                    int num34 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 306, this.velocity.X * 0.2f + (float)(this.direction * 3), this.velocity.Y * 0.2f, 100, default(Color), 1.25f);
                    Main.dust[num34].noGravity = true;
                    Dust dust22 = Main.dust[num34];
                    dust22.velocity.X = dust22.velocity.X * 0.2f;
                    Dust dust23 = Main.dust[num34];
                    dust23.velocity.Y = dust23.velocity.Y * 0.2f;
                    float num35 = Main.rand.NextFloat();
                    Main.dust[num34].color = Color.Lerp(new Color(0.9f, 0.7f, 1f), Color.White, num35 * num35 * num35);
                    if (this.mount.Type == 63)
                    {
                        Main.dust[num34].color = Color.Lerp(new Color(1f, 0.7f, 0.5f), Color.White, num35 * num35 * num35);
                    }
                }
            }
        }
References Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Rectangle.Center, Terraria.Dust.color, Terraria.GameContent.ChildSafety.Disabled, Terraria.Main.dust, Terraria.Dust.fadeIn, Microsoft.Xna.Framework.Color.G, Terraria.Item.GetPhaseColor(), Terraria.Main.gore, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Item.melee, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Item.noMelee, Terraria.Item.noUseGraphic, Terraria.Dust.position, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Gore.scale, Terraria.Item.shoot, Microsoft.Xna.Framework.Color.Transparent, Terraria.Item.type, Terraria.Dust.velocity, Terraria.Gore.velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Rectangle.Y.