Terraria Decompiled: Terraria.Player.ItemCheck_ApplyUseStyle
ItemCheck_ApplyUseStyle()
void Terraria.Player.ItemCheck_ApplyUseStyle (float mountOffset, Item sItem, Rectangle heldItemFrame) inline
Definition at line 50022 of file Player.cs.
        {
            if (Main.dedServ)
            {
                return;
            }
            bool flag = this.isDisplayDollOrInanimate;
            if (sItem.useStyle == 1)
            {
                if (sItem.type > -1 && Item.claw[sItem.type])
                {
                    if ((double)this.itemAnimation < (double)this.itemAnimationMax * 0.333)
                    {
                        float num = 10f;
                        this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num) * (float)this.direction;
                        this.itemLocation.Y = this.position.Y + 26f + mountOffset;
                    }
                    else if ((double)this.itemAnimation < (double)this.itemAnimationMax * 0.666)
                    {
                        float num2 = 8f;
                        this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num2) * (float)this.direction;
                        num2 = 24f;
                        this.itemLocation.Y = this.position.Y + num2 + mountOffset;
                    }
                    else
                    {
                        float num3 = 6f;
                        this.itemLocation.X = this.position.X + (float)this.width * 0.5f - ((float)heldItemFrame.Width * 0.5f - num3) * (float)this.direction;
                        num3 = 20f;
                        this.itemLocation.Y = this.position.Y + num3 + mountOffset;
                    }
                    this.itemRotation = ((float)this.itemAnimation / (float)this.itemAnimationMax - 0.5f) * (float)(-(float)this.direction) * 3.5f - (float)this.direction * 0.3f;
                }
                else
                {
                    Vector2 zero = Vector2.Zero;
                    if ((double)this.itemAnimation < (double)this.itemAnimationMax * 0.333)
                    {
                        float num4 = 10f;
                        if (heldItemFrame.Width > 32)
{
                            num4 = 14f;
                        }
                        if (heldItemFrame.Width >= 52)
{
                            num4 = 24f;
                        }
                        if (heldItemFrame.Width >= 64)
{
                            num4 = 28f;
                        }
                        if (heldItemFrame.Width >= 92)
{
                            num4 = 38f;
                        }
                        if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
{
                            num4 += 8f;
                        }
                        if (sItem.type == 671)
{
                            num4 += 12f;
                        }
                        this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num4) * (float)this.direction;
                        this.itemLocation.Y = this.position.Y + 24f + mountOffset;
                        zero = new Vector2(-4f, 1f);
                    }
                    else if ((double)this.itemAnimation < (double)this.itemAnimationMax * 0.666)
                    {
                        float num5 = 10f;
                        if (heldItemFrame.Width > 32)
{
                            num5 = 18f;
                        }
                        if (heldItemFrame.Width >= 52)
{
                            num5 = 24f;
                        }
                        if (heldItemFrame.Width >= 64)
{
                            num5 = 28f;
                        }
                        if (heldItemFrame.Width >= 92)
{
                            num5 = 38f;
                        }
                        if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
{
                            num5 += 4f;
                        }
                        if (sItem.type == 671)
{
                            num5 += 6f;
                        }
                        this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num5) * (float)this.direction;
                        num5 = 10f;
                        if (heldItemFrame.Height > 32)
{
                            num5 = 8f;
                        }
                        if (heldItemFrame.Height > 52)
{
                            num5 = 12f;
                        }
                        if (heldItemFrame.Height > 64)
{
                            num5 = 14f;
                        }
                        if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
{
                            num5 += 4f;
                        }
                        if (sItem.type == 671)
{
                            num5 += 10f;
                        }
                        this.itemLocation.Y = this.position.Y + num5 + mountOffset;
                        zero = new Vector2(-6f, -4f);
                    }
                    else
                    {
                        float num6 = 6f;
                        if (heldItemFrame.Width > 32)
{
                            num6 = 14f;
                        }
                        if (heldItemFrame.Width >= 48)
{
                            num6 = 18f;
                        }
                        if (heldItemFrame.Width >= 52)
{
                            num6 = 24f;
                        }
                        if (heldItemFrame.Width >= 64)
{
                            num6 = 28f;
                        }
                        if (heldItemFrame.Width >= 92)
{
                            num6 = 38f;
                        }
                        if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
{
                            num6 += 4f;
                        }
                        if (sItem.type == 671)
{
                            num6 += 8f;
                        }
                        this.itemLocation.X = this.position.X + (float)this.width * 0.5f - ((float)heldItemFrame.Width * 0.5f - num6) * (float)this.direction;
                        num6 = 10f;
                        if (heldItemFrame.Height > 32)
{
                            num6 = 10f;
                        }
                        if (heldItemFrame.Height > 52)
{
                            num6 = 12f;
                        }
                        if (heldItemFrame.Height > 64)
{
                            num6 = 14f;
                        }
                        if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
{
                            num6 += 4f;
                        }
                        if (sItem.type == 671)
{
                            num6 += 8f;
                        }
                        this.itemLocation.Y = this.position.Y + num6 + mountOffset;
                        zero = new Vector2(4f, -2f);
                    }
                    if (sItem.type > -1 && ItemID.Sets.UsesBetterMeleeItemLocation[sItem.type])
                    {
                        this.itemLocation += zero * this.Directions;
                    }
                    this.itemRotation = ((float)this.itemAnimation / (float)this.itemAnimationMax - 0.5f) * (float)(-(float)this.direction) * 3.5f - (float)this.direction * 0.3f;
                }
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                    return;
                }
            }
            else if (sItem.useStyle == 7)
            {
                this.itemRotation = (float)this.itemAnimation / (float)this.itemAnimationMax * (float)this.direction * 2f + -1.4f * (float)this.direction;
                if ((double)this.itemAnimation < (double)this.itemAnimationMax * 0.5)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - this.itemRotation * 12f * (float)this.direction) * (float)this.direction;
                    this.itemLocation.Y = this.position.Y + 38f + this.itemRotation * (float)this.direction * 4f + mountOffset;
                }
                else
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - this.itemRotation * 16f * (float)this.direction) * (float)this.direction;
                    this.itemLocation.Y = this.position.Y + 38f + this.itemRotation * (float)this.direction + mountOffset;
                }
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                    return;
                }
            }
            else if (sItem.useStyle == 9)
            {
                float num7 = (float)this.itemAnimation / (float)this.itemAnimationMax;
                float num8 = 1f - num7;
                num8 = Utils.GetLerpValue(0f, 0.7f, num8, true);
                this.itemRotation = num8 * (float)(-(float)this.direction) * 2f + 0.7f * (float)this.direction;
                this.itemLocation = this.MountedCenter + new Vector2((float)(this.direction * 10) * ((float)this.itemAnimation / (float)this.itemAnimationMax), 0f);
                float num9 = 8f;
                float num10 = 7f;
                float num11 = 1.2566371f;
                float num12 = -num11 * 0.5f + (1f - num8) * num11;
                num12 += 0.31415927f;
                Vector2 vector = base.Center + new Vector2((float)this.direction * num9, 0f) + num12.ToRotationVector2() * num10 * new Vector2((float)this.direction, 1f);
                this.itemLocation = vector;
                float num13 = num12 - 1.5707964f;
                if (this.direction == -1)
                {
                    num13 = -num13;
                }
                this.SetCompositeArmFront(true, Player.CompositeArmStretchAmount.Full, num13);
                this.itemLocation = this.GetFrontHandPosition(Player.CompositeArmStretchAmount.Full, num13);
                this.itemLocation -= this.MountedCenter;
                this.itemLocation *= MathHelper.Lerp(1.5f, 1.2f, num8);
                this.itemLocation += this.MountedCenter;
                this.itemLocation.X = this.itemLocation.X + (float)this.direction * MathHelper.Lerp(8f, 2f, num8);
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                    return;
                }
            }
            else if (sItem.useStyle == 6)
            {
                float num14 = 1f - (float)this.itemAnimation / (float)this.itemAnimationMax;
                num14 *= 6f;
                if (num14 > 1f)
                {
                    num14 = 1f;
                }
                this.itemRotation = (1f - num14) * (float)this.direction * 2f - 1.4f * (float)this.direction;
                if (num14 >= 0.5f)
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - this.itemRotation * 12f * (float)this.direction) * (float)this.direction;
                    this.itemLocation.Y = this.position.Y + 38f + this.itemRotation * (float)this.direction * 4f + mountOffset;
                }
                else
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - this.itemRotation * 16f * (float)this.direction) * (float)this.direction;
                    this.itemLocation.Y = this.position.Y + 38f + this.itemRotation * (float)this.direction + mountOffset;
                }
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                    return;
                }
            }
            else if (sItem.useStyle == 2)
            {
                this.itemLocation = this.MountedCenter + new Vector2((float)(10 * this.direction), -10f).RotatedBy((double)(this.itemRotation + 0.7853982f * (float)this.direction), default(Vector2));
                float num15 = 1f - (float)this.itemAnimation / (float)this.itemAnimationMax;
                Player.CompositeArmStretchAmount compositeArmStretchAmount = Player.CompositeArmStretchAmount.Full;
                if (num15 > 0.25f && num15 <= 0.5f)
                {
                    compositeArmStretchAmount = Player.CompositeArmStretchAmount.ThreeQuarters;
                }
                if (num15 > 0.5f && num15 <= 0.75f)
                {
                    compositeArmStretchAmount = Player.CompositeArmStretchAmount.Quarter;
                }
                if (num15 > 0.75f && num15 <= 1f)
                {
                    compositeArmStretchAmount = Player.CompositeArmStretchAmount.None;
                }
                this.SetCompositeArmFront(true, compositeArmStretchAmount, -1.5707964f * (float)this.direction);
                this.SetCompositeArmBack(true, compositeArmStretchAmount, -1.5707964f * (float)this.direction);
                int num16 = 8;
                switch (compositeArmStretchAmount)
                {
                case Player.CompositeArmStretchAmount.Full:
                    num16 = 8;
                    break;
                case Player.CompositeArmStretchAmount.None:
                    num16 = 2;
                    break;
                case Player.CompositeArmStretchAmount.Quarter:
                    num16 = 4;
                    break;
                case Player.CompositeArmStretchAmount.ThreeQuarters:
                    num16 = 6;
                    break;
                }
                this.itemLocation = this.MountedCenter + new Vector2((float)((num16 + 10 - heldItemFrame.Width / 2) * this.direction), (float)(heldItemFrame.Height / 2 - 4));
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                    return;
                }
            }
            else if (sItem.useStyle == 11)
            {
                float num17 = 1f - (float)this.itemAnimation / (float)this.itemAnimationMax;
                num17 *= 2f;
                Player.CompositeArmStretchAmount compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.Full;
                if (num17 > 0.25f && num17 <= 0.5f)
                {
                    compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.ThreeQuarters;
                }
                if (num17 > 0.5f && num17 <= 0.75f)
                {
                    compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.Quarter;
                }
                if (num17 > 0.75f && num17 <= 1.25f)
                {
                    compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.None;
                }
                if (num17 > 1.25f && num17 <= 1.5f)
                {
                    compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.Quarter;
                }
                if (num17 > 1.5f && num17 <= 1.75f)
                {
                    compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.ThreeQuarters;
                }
                if (num17 > 1.75f && num17 <= 2f)
                {
                    compositeArmStretchAmount2 = Player.CompositeArmStretchAmount.Full;
                }
                this.SetCompositeArmFront(true, compositeArmStretchAmount2, -0.7853982f * (float)this.direction);
                this.SetCompositeArmBack(true, Player.CompositeArmStretchAmount.Full, -0.19634955f);
                int num18 = 8;
                switch (compositeArmStretchAmount2)
                {
                case Player.CompositeArmStretchAmount.Full:
                    num18 = 8;
                    break;
                case Player.CompositeArmStretchAmount.None:
                    num18 = 2;
                    break;
                case Player.CompositeArmStretchAmount.Quarter:
                    num18 = 4;
                    break;
                case Player.CompositeArmStretchAmount.ThreeQuarters:
                    num18 = 6;
                    break;
                }
                this.itemLocation = this.MountedCenter + new Vector2((float)((num18 + 22 - heldItemFrame.Width / 2) * this.direction), (float)(heldItemFrame.Height / 2 - 8));
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                    return;
                }
            }
            else if (sItem.useStyle == 3)
            {
                if ((double)this.itemAnimation > (double)this.itemAnimationMax * 0.666)
                {
                    this.itemLocation.X = -1000f;
                    this.itemLocation.Y = -1000f;
                    this.itemRotation = -1.3f * (float)this.direction;
                }
                else
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 4f) * (float)this.direction;
                    this.itemLocation.Y = this.position.Y + 24f + mountOffset;
                    float num19 = (float)this.itemAnimation / (float)this.itemAnimationMax * (float)heldItemFrame.Width * (float)this.direction * this.GetAdjustedItemScale(sItem) * 1.2f - (float)(10 * this.direction);
                    if (num19 > -4f && this.direction == -1)
                    {
                        num19 = -8f;
                    }
                    if (num19 < 4f && this.direction == 1)
                    {
                        num19 = 8f;
                    }
                    this.itemLocation.X = this.itemLocation.X - num19;
                    this.itemRotation = 0.8f * (float)this.direction;
                    if (sItem.type == 946 || sItem.type == 4707)
                    {
                        this.itemLocation.X = this.itemLocation.X - (float)(6 * this.direction);
                    }
                }
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                    return;
                }
            }
            else if (sItem.useStyle == 4)
            {
                int num20 = 0;
                int num21 = 0;
                if (sItem.type == 3601)
                {
                    num20 = 10;
                }
                if (sItem.type == 5114)
                {
                    num20 = 10;
                    num21 = -2;
                }
                if (sItem.type == 5120)
                {
                    num20 = 10;
                }
                this.itemRotation = 0f;
                this.itemLocation.X = this.position.X + (float)this.width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - this.itemRotation * 14f * (float)this.direction - 4f - (float)num20) * (float)this.direction;
                this.itemLocation.Y = this.position.Y + (float)heldItemFrame.Height * 0.5f + 4f + mountOffset + (float)num21;
                if (this.gravDir == -1f)
                {
                    this.itemRotation = -this.itemRotation;
                    this.itemLocation.Y = this.position.Y + (float)this.height + (this.position.Y - this.itemLocation.Y);
                    return;
                }
            }
            else if (sItem.useStyle == 5)
            {
                if (sItem.type == 3779)
                {
                    this.itemRotation = 0f;
                    this.itemLocation.X = base.Center.X + (float)(6 * this.direction);
                    this.itemLocation.Y = this.MountedCenter.Y + 6f;
                }
                else if (sItem.type == 4262)
                {
                    this.itemRotation = 0f;
                    this.itemLocation.X = base.Center.X + (float)(this.direction * -6);
                    this.itemLocation.Y = this.MountedCenter.Y - 6f;
                    bool flag2 = true;
                    if (this.mount.Active && this.mount.Type >= 0 && MountID.Sets.DontHoldItems[this.mount.Type])
                    {
                        flag2 = false;
                    }
                    if (flag2 && Main.rand.Next(20) == 0)
                    {
                        int num22 = Main.rand.Next(570, 573);
                        Vector2 vector2 = new Vector2(base.Center.X + (float)(this.direction * 30) - 6f, this.itemLocation.Y - 30f);
                        Vector2 vector3 = new Vector2(Main.WindForVisuals * 2f + (float)this.direction * 0.3f, -0.5f);
                        vector3.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                        vector3.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                        if (num22 == 572)
{
                            vector2.X -= 8f;
                        }
                        if (num22 == 571)
{
                            vector2.X -= 4f;
                        }
                        Gore.NewGore(vector2, vector3, num22, 0.8f);
                    }
                }
                else if (Item.staff[sItem.type])
                {
                    float num23 = 6f;
                    if (sItem.type == 3476)
                    {
                        num23 = 14f;
                    }
                    this.itemLocation = this.MountedCenter;
                    this.itemLocation += (this.itemRotation.ToRotationVector2() * num23 * (float)this.direction).Floor();
                }
                else
                {
                    this.itemLocation.X = this.position.X + (float)this.width * 0.5f - (float)(this.direction * 2);
                    this.itemLocation.Y = this.MountedCenter.Y - (float)heldItemFrame.Height * 0.5f;
                }
                if (sItem.type == 5065)
                {
                    float num24 = this.itemRotation;
                    Vector2 vector4 = this.itemLocation + this.itemRotation.ToRotationVector2() * 38f * (float)this.direction;
                    Vector2 vector5 = this.itemRotation.ToRotationVector2() * 5f * (float)this.direction;
                    if (this.itemAnimation % 2 == 0)
                    {
                        Color color = Main.hslToRgb(0.92f, 1f, 0.5f, byte.MaxValue);
                        int num25 = Dust.NewDust(vector4, 0, 0, 267, 0f, 0f, 0, color, 1f);
                        Main.dust[num25].position = vector4 - this.velocity + Main.rand.NextVector2Circular(10f, 10f);
                        Main.dust[num25].noGravity = true;
                        Main.dust[num25].scale = 0.3f;
                        Main.dust[num25].fadeIn = Main.rand.NextFloat() * 1.2f;
                        Main.dust[num25].velocity = Main.rand.NextVector2Circular(1f, 1f) + this.velocity;
                        if (num25 != 6000)
{
                            Dust dust = Dust.CloneDust(num25);
                            dust.scale /= 2f;
                            dust.fadeIn *= 0.85f;
                            dust.color = new Color(255, 255, 255, 255);
                        }
                    }
                    if (this.itemAnimation % 4 == 0)
                    {
                        ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
{
                            PositionInWorld = vector4,
                            MovementVector = vector5 * 0.1f + Main.rand.NextVector2Circular(2f, 2f) + this.velocity
                        }, new int?(this.whoAmI));
                        return;
                    }
                }
            }
            else
            {
                if (sItem.useStyle == 13)
                {
                    int useAnimation = this.itemAnimationMax;
                    if (this.itemTimeMax != 0)
                    {
                        useAnimation = this.itemTimeMax;
                    }
                    if (useAnimation == 0)
                    {
                        useAnimation = sItem.useAnimation;
                    }
                    float num26 = 1f - (float)(this.itemAnimation % useAnimation) / (float)useAnimation;
                    Player.CompositeArmStretchAmount compositeArmStretchAmount3 = Player.CompositeArmStretchAmount.Quarter;
                    if (num26 > 0.33f && num26 <= 0.66f)
                    {
                        compositeArmStretchAmount3 = Player.CompositeArmStretchAmount.ThreeQuarters;
                    }
                    if (num26 > 0.66f && num26 <= 1f)
                    {
                        compositeArmStretchAmount3 = Player.CompositeArmStretchAmount.Full;
                    }
                    float num27 = this.itemRotation * this.Directions.Y - 1.5707964f * (float)this.direction;
                    this.SetCompositeArmFront(true, compositeArmStretchAmount3, num27);
                    return;
                }
                if (sItem.useStyle == 8)
                {
                    if (this.itemAnimation >= sItem.useAnimation - 1 && this.itemAnimation <= sItem.useAnimation)
                    {
                        float num28 = new Vector2((float)(10 * this.direction), 10f).ToRotation() + 0.7853982f;
                        this.itemRotation = num28;
                        if (this.direction == -1)
{
                            this.itemRotation += 1.5707964f;
                        }
                        float num29 = (float)this.itemAnimation / (float)this.itemAnimationMax;
                        Player.CompositeArmStretchAmount compositeArmStretchAmount4 = Player.CompositeArmStretchAmount.Full;
                        Player.CompositeArmStretchAmount compositeArmStretchAmount5 = Player.CompositeArmStretchAmount.ThreeQuarters;
                        float num30 = -0.31415927f;
                        if (this.direction == -1)
{
                            num30 *= -1f;
                        }
                        float num31 = this.itemRotation - 0.7853982f + 3.1415927f;
                        if (this.direction == 1)
{
                            num31 += 1.5707964f;
                        }
                        float num32 = num31 + num30;
                        float num33 = num31 - num30;
                        Vector2 vector6 = (num31 + 1.5707964f).ToRotationVector2() * -2f;
                        this.itemLocation = (this.MountedCenter + vector6).Floor();
                        this.SetCompositeArmFront(true, compositeArmStretchAmount4, num32);
                        this.SetCompositeArmBack(true, compositeArmStretchAmount5, num33);
                    }
                    else if (this.itemAnimation > sItem.useAnimation)
                    {
                        float num34 = -Utils.GetLerpValue((float)this.itemAnimationMax, (float)(this.itemAnimationMax * 5), (float)this.itemAnimation, true);
                        Player.CompositeArmStretchAmount compositeArmStretchAmount6 = Player.CompositeArmStretchAmount.Full;
                        Player.CompositeArmStretchAmount compositeArmStretchAmount7 = Player.CompositeArmStretchAmount.ThreeQuarters;
                        float num35 = -0.31415927f;
                        num35 *= -num34;
                        this.itemRotation = 1.5707964f * (float)(-(float)this.direction) + 3.1415927f + 3.1415927f * num34 * (float)(-(float)this.direction);
                        float num36 = -0.62831855f * (float)this.direction;
                        if (this.direction < 1)
{
                            num35 *= -1f;
                        }
                        float num37 = num36 + num35;
                        float num38 = num36 - num35;
                        Vector2 vector7 = new Vector2((float)(10 * this.direction), num34 * -6f);
                        this.itemLocation = (this.MountedCenter + vector7).Floor();
                        this.SetCompositeArmFront(true, compositeArmStretchAmount6, num37);
                        this.SetCompositeArmBack(true, compositeArmStretchAmount7, num38);
                    }
                    else
                    {
                        float num39 = 1f - (float)this.itemAnimation / (float)this.itemAnimationMax;
                        Player.CompositeArmStretchAmount compositeArmStretchAmount8 = Player.CompositeArmStretchAmount.Full;
                        Player.CompositeArmStretchAmount compositeArmStretchAmount9 = Player.CompositeArmStretchAmount.ThreeQuarters;
                        if (num39 > 0.6f)
{
                            compositeArmStretchAmount9 = Player.CompositeArmStretchAmount.Quarter;
                        }
                        float num40 = -0.31415927f;
                        if (this.direction == -1)
{
                            num40 *= -1f;
                        }
                        num40 *= 1f - num39 * 2.2f;
                        this.itemRotation = (num39 * 3.1415927f * 1.6f + -1.5707964f) * (float)(-(float)this.direction) + 3.1415927f;
                        float num41 = (num39 * 3.1415927f * 0.6f + 1.2566371f) * (float)(-(float)this.direction) + 3.1415927f - 0.7853982f + 3.1415927f;
                        if (this.direction == 1)
{
                            num41 += 1.5707964f;
                        }
                        float num42 = num41 + num40;
                        float num43 = num41 - num40;
                        Vector2 vector8 = (num41 + 1.5707964f).ToRotationVector2() * (-5f * (1f - num39));
                        this.itemLocation = (this.MountedCenter + vector8).Floor();
                        this.SetCompositeArmFront(true, compositeArmStretchAmount8, num42);
                        this.SetCompositeArmBack(true, compositeArmStretchAmount9, num43);
                    }
                    this.FlipItemLocationAndRotationForGravity();
                    return;
                }
                if (sItem.useStyle == 12)
                {
                    this.itemRotation = 0f;
                    this.itemLocation.X = this.MountedCenter.X - (float)(8 * this.direction);
                    this.itemLocation.Y = this.position.Y + 40f + mountOffset;
                    Vector2 vector9 = Main.OffsetsPlayerHeadgear[this.bodyFrame.Y / 56];
                    this.itemLocation += vector9;
                    float num44 = (float)this.itemAnimationMax;
                    if (num44 == 0f)
                    {
                        num44 = (float)sItem.useAnimation;
                    }
                    float num45 = 1f - (float)this.itemAnimation / num44;
                    num45 *= 2f;
                    float num46 = (float)Math.Cos((double)(num45 * 3.1415927f)) * 0.2f;
                    Player.CompositeArmStretchAmount compositeArmStretchAmount10 = Player.CompositeArmStretchAmount.Full;
                    if (num45 > 0.25f && num45 <= 0.5f)
                    {
                        compositeArmStretchAmount10 = Player.CompositeArmStretchAmount.ThreeQuarters;
                    }
                    if (num45 > 0.5f && num45 <= 0.75f)
                    {
                        compositeArmStretchAmount10 = Player.CompositeArmStretchAmount.Quarter;
                    }
                    if (num45 > 0.75f && num45 <= 1.25f)
                    {
                        compositeArmStretchAmount10 = Player.CompositeArmStretchAmount.None;
                    }
                    if (num45 > 1.25f && num45 <= 1.5f)
                    {
                        compositeArmStretchAmount10 = Player.CompositeArmStretchAmount.Quarter;
                    }
                    if (num45 > 1.5f && num45 <= 1.75f)
                    {
                        compositeArmStretchAmount10 = Player.CompositeArmStretchAmount.ThreeQuarters;
                    }
                    if (num45 > 1.75f && num45 <= 2f)
                    {
                        compositeArmStretchAmount10 = Player.CompositeArmStretchAmount.Full;
                    }
                    this.SetCompositeArmFront(true, compositeArmStretchAmount10, (-0.7853982f + num46) * (float)this.direction);
                    Player.CompositeArmStretchAmount compositeArmStretchAmount11 = Player.CompositeArmStretchAmount.Quarter;
                    this.SetCompositeArmBack(true, compositeArmStretchAmount11, (-0.7853982f - num46 * 0.5f) * (float)this.direction);
                    this.FlipItemLocationAndRotationForGravity();
                    if (sItem.type == 4715 && compositeArmStretchAmount10 == Player.CompositeArmStretchAmount.ThreeQuarters)
                    {
                        Vector2 vector10 = this.itemLocation + new Vector2((float)heldItemFrame.Width, (float)(-(float)heldItemFrame.Height)) * new Vector2((float)this.direction, this.gravDir) * 0.3f;
                        Dust dust2 = Dust.NewDustPerfect(vector10, 228, new Vector2?(Main.rand.NextVector2CircularEdge(1f, 1f)), 0, default(Color), 1f);
                        dust2.noGravity = true;
                        dust2.noLight = true;
                        dust2.velocity *= 2f;
                        float num47 = 0.5f;
                        for (float num48 = 0f; num48 < 1f; num48 += 0.5f)
{
                            if (Main.rand.Next(3) == 0)
{
                                Dust dust3 = Dust.NewDustPerfect(vector10, 278, new Vector2?(Vector2.UnitY.RotatedBy((double)(num48 * 6.2831855f + Main.rand.NextFloat() * num47 - num47 * 0.5f + 1.5707964f), default(Vector2)) * (2f + Main.rand.NextFloat() * 1f)), 150, Color.Lerp(Color.White, Color.HotPink, Main.rand.NextFloat() * 0.5f + 0.5f), 0.45f);
                                dust3.noGravity = true;
                                dust3.velocity *= 0.5f;
                                dust3.customData = this;
                                dust3.position += dust3.velocity * 6f;
                            }
                        }
                        for (float num49 = 0f; num49 < 1f; num49 += 0.5f)
{
                            if (Main.rand.Next(3) == 0)
{
                                Dust dust4 = Dust.NewDustPerfect(vector10, 278, new Vector2?(Vector2.UnitY.RotatedBy((double)(num49 * 6.2831855f + Main.rand.NextFloat() * num47 - num47 * 0.5f + 1.5707964f), default(Vector2)) * (0.5f + Main.rand.NextFloat() * 1f)), 150, Color.Lerp(Color.White, Color.Gold, Main.rand.NextFloat() * 0.5f + 0.5f), 0.45f);
                                dust4.noGravity = true;
                                dust4.velocity *= 0.5f;
                                dust4.customData = this;
                                dust4.position += dust4.velocity * 6f;
                            }
                        }
                        return;
                    }
                }
                else if (sItem.useStyle == 14)
                {
                    if (Main.dedServ)
                    {
                        return;
                    }
                    this.itemRotation = 0f;
                    this.itemLocation.X = base.Center.X + (float)(6 * this.direction);
                    this.itemLocation.Y = this.position.Y + 40f + mountOffset - 8f;
                    Vector2 vector11 = Main.OffsetsPlayerHeadgear[this.bodyFrame.Y / 56];
                    this.itemLocation += vector11;
                    Player.CompositeArmStretchAmount compositeArmStretchAmount12 = Player.CompositeArmStretchAmount.Full;
                    this.SetCompositeArmBack(true, compositeArmStretchAmount12, -2.3561945f * (float)this.direction);
                    this.FlipItemLocationAndRotationForGravity();
                    return;
                }
                else
                {
                    if (sItem.useStyle == 15)
                    {
                        this.itemRotation = 0f;
                        this.itemLocation.X = base.Center.X + (float)(6 * this.direction);
                        this.itemLocation.Y = this.position.Y + 30f + mountOffset - 2f;
                        Vector2 vector12 = Main.OffsetsPlayerHeadgear[this.bodyFrame.Y / 56];
                        this.itemLocation += vector12;
                        this.SetCompositeArmBack(true, Player.CompositeArmStretchAmount.ThreeQuarters, -1.2566371f * (float)this.direction);
                        this.SetCompositeArmFront(true, Player.CompositeArmStretchAmount.Full, -1.2566371f * (float)this.direction);
                        this.FlipItemLocationAndRotationForGravity();
                        return;
                    }
                    if (sItem.useStyle == 16)
                    {
                        bool flag3 = this.pulley;
                        this.pulley = false;
                        this.ItemCheck_ApplyHoldStyle(mountOffset, sItem, heldItemFrame);
                        this.pulley = flag3;
                    }
                }
            }
        }
References Terraria.Item.claw, Terraria.Dust.CloneDust(), System.Math.Cos(), Terraria.Main.dedServ, Terraria.ID.MountID.Sets.DontHoldItems, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Color.Gold, Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Color.HotPink, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.OffsetsPlayerHeadgear, Terraria.Dust.position, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Dust.scale, Terraria.Item.staff, Terraria.Item.type, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Item.useAnimation, Terraria.ID.ItemID.Sets.UsesBetterMeleeItemLocation, Terraria.Item.useStyle, Terraria.Dust.velocity, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Main.WindForVisuals, and Microsoft.Xna.Framework.Vector2.Zero.