Terraria Decompiled: Terraria.Player.ItemCheck_UseCombatBook
ItemCheck_UseCombatBook()
void Terraria.Player.ItemCheck_UseCombatBook (Item sItem) inline private
Definition at line 44593 of file Player.cs.
        {
            if (!NPC.combatBookWasUsed && sItem.type == 4382 && this.itemAnimation > 0 && this.ItemTimeIsZero)
            {
                this.ApplyItemTime(sItem);
                if (Main.netMode == 0)
                {
                    NPC.combatBookWasUsed = true;
                    Main.NewText(Language.GetTextValue("Misc.CombatBookUsed"), ChatColors.World);
                }
                else
                {
                    NetMessage.SendData(61, -1, -1, null, this.whoAmI, -11f, 0f, 0f, 0, 0, 0);
                }
            }
            if (!NPC.combatBookVolumeTwoWasUsed && sItem.type == 5336 && this.itemAnimation > 0 && this.ItemTimeIsZero)
            {
                this.ApplyItemTime(sItem);
                if (Main.netMode == 0)
                {
                    NPC.combatBookVolumeTwoWasUsed = true;
                    Main.NewText(Language.GetTextValue("Misc.CombatBookVolumeTwoUsed"), ChatColors.World);
                    return;
                }
                NetMessage.SendData(61, -1, -1, null, this.whoAmI, -17f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.NPC.combatBookVolumeTwoWasUsed, Terraria.NPC.combatBookWasUsed, Terraria.Localization.Language.GetTextValue(), Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.NetMessage.SendData(), Terraria.Item.type, and Terraria.Chat.ChatColors.World.