Terraria Decompiled: Terraria.Player.GetOrDropItem
GetOrDropItem()
void Terraria.Player.GetOrDropItem (Item item, GetItemSettings settings) inline
Definition at line 4443 of file Player.cs.
        {
            Item item2 = this.GetItem(item, settings);
            if (item2.IsAir)
            {
                return;
            }
            int num = Item.NewItem(this.GetItemSource_InventoryOverflow(), (int)this.position.X, (int)this.position.Y, this.width, this.height, item2.type, item2.stack, false, (int)item2.prefix, true);
            Main.item[num].newAndShiny = item.newAndShiny;
            settings.HandlePostAction(Main.item[num].inner);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, num, 1f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Player.GetItem(), Terraria.Player.GetItemSource_InventoryOverflow(), Terraria.GetItemSettings.HandlePostAction(), Terraria.WorldItem.inner, Terraria.Item.IsAir, System.item, Terraria.Main.item, Terraria.Main.netMode, Terraria.WorldItem.newAndShiny, Terraria.Item.NewItem(), Terraria.Entity.position, Terraria.Item.prefix, Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.Item.type, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.Main.CraftItem_GrantItem(), Terraria.Player.dropItemCheck(), Terraria.Player.QuickSpawnItem(), Terraria.GameContent.CraftingRequests.Refund(), and Terraria.GameContent.Creative.CreativeUI.ToggleMenu().