Terraria Decompiled: Terraria.Player.LoadPlayer
LoadPlayer()
static PlayerFileData Terraria.Player.LoadPlayer (string playerPath, bool cloudSave) inline static
Definition at line 54391 of file Player.cs.
        {
            PlayerFileData playerFileData = new PlayerFileData(playerPath, cloudSave);
            if (cloudSave && SocialAPI.Cloud == null)
            {
                return playerFileData;
            }
            if (Main.rand == null)
            {
                Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
            }
            Player player = new Player();
            bool flag = false;
            try
            {
                RijndaelManaged rijndaelManaged = new RijndaelManaged();
                rijndaelManaged.Padding = PaddingMode.None;
                using (MemoryStream memoryStream = new MemoryStream(FileUtilities.ReadAllBytes(playerPath, cloudSave)))
                {
                    using (CryptoStream cryptoStream = new CryptoStream(memoryStream, rijndaelManaged.CreateDecryptor(Player.ENCRYPTION_KEY, Player.ENCRYPTION_KEY), CryptoStreamMode.Read))
                    {
                        using (BinaryReader binaryReader = new BinaryReader(cryptoStream))
{
                            int num = binaryReader.ReadInt32();
                            if (num >= 135)
{
                                playerFileData.Metadata = FileMetadata.Read(binaryReader, FileType.Player);
                            }
                            else
{
                                playerFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.Player);
                            }
                            if (num > 319)
{
                                player.loadStatus = StatusID.LaterVersion;
                                player.name = binaryReader.ReadString();
                                playerFileData.Player = player;
                                return playerFileData;
                            }
                            Player.Deserialize(playerFileData, player, binaryReader, num, out flag);
                            if (player.lastTimePlayerWasSaved == 0L && !cloudSave)
{
                                player.lastTimePlayerWasSaved = File.GetLastWriteTimeUtc(playerPath).ToBinary();
                            }
                        }
                    }
                }
                player.PlayerFrame();
                player.loadStatus = StatusID.Ok;
                playerFileData.Player = player;
                return playerFileData;
            }
            catch
            {
            }
            Player player2 = new Player();
            player2.loadStatus = StatusID.UnknownError;
            if (flag && player.name.Length <= Player.nameLen)
            {
                player2.name = player.name;
            }
            else
            {
                string[] array = playerPath.Replace('/', Path.DirectorySeparatorChar).Split(new char[] { Path.DirectorySeparatorChar });
                player2.name = array[array.Length - 1].Split(new char[] { '.' })[0];
            }
            playerFileData.Player = player2;
            return playerFileData;
        }
References System.array, Terraria.Social.SocialAPI.Cloud, System.Security.Cryptography.RijndaelManaged.CreateDecryptor(), Terraria.Player.Deserialize(), System.IO.Path.DirectorySeparatorChar, Terraria.Player.ENCRYPTION_KEY, Terraria.IO.FileMetadata.FromCurrentSettings(), System.IO.File.GetLastWriteTimeUtc(), System.L, Terraria.Player.lastTimePlayerWasSaved, Terraria.ID.StatusID.LaterVersion, Terraria.Player.name, Terraria.Player.nameLen, System.DateTime.Now, Terraria.ID.StatusID.Ok, Terraria.Enums.Player, Terraria.Player.PlayerFrame(), Terraria.Main.rand, Terraria.IO.FileMetadata.Read(), Terraria.Utilities.FileUtilities.ReadAllBytes(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), System.DateTime.Ticks, System.DateTime.ToBinary(), and Terraria.ID.StatusID.UnknownError.
Referenced by Terraria.Player.GetFileData().