Terraria Decompiled: Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool
ItemCheck_UseMiningTools_ActuallyUseMiningTool()
void Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool (Item sItem, out bool canHitWalls, int x, int y) inline private
Definition at line 44921 of file Player.cs.
        {
            int num = 0;
            canHitWalls = true;
            Tile tile = Main.tile[x, y];
            if (tile.active())
            {
                if ((sItem.pick > 0 && !Main.tileAxe[(int)tile.type] && !Main.tileHammer[(int)tile.type]) || (sItem.axe > 0 && Main.tileAxe[(int)tile.type]) || (sItem.hammer > 0 && Main.tileHammer[(int)tile.type]))
                {
                    canHitWalls = false;
                }
                int num2 = this.hitTile.HitObject(x, y, 1);
                if (Main.tileNoFail[(int)tile.type])
                {
                    num = 100;
                }
                if (Main.tileHammer[(int)tile.type])
                {
                    canHitWalls = false;
                    if (sItem.hammer > 0)
                    {
                        num += sItem.hammer;
                        if (!WorldGen.CanKillTile(x, y))
{
                            num = 0;
                        }
                        if (tile.type == 26 && (sItem.hammer < 80 || !Main.hardMode))
{
                            num = 0;
                            this.Hurt(PlayerDeathReason.ByOther(4), this.statLife / 2, -this.direction, false, false, false, -1, true);
                        }
                        AchievementsHelper.CurrentlyMining = true;
                        if (this.hitTile.AddDamage(num2, num, true) >= 100)
{
                            this.ClearMiningCacheAt(x, y, 1);
                            WorldGen.KillTile(x, y, false, false, false);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                            }
                        }
                        else
{
                            WorldGen.KillTile(x, y, true, false, false);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 1f, 0, 0, 0);
                            }
                        }
                        if (num != 0)
{
                            this.hitTile.Prune();
                        }
                        this.ApplyItemTime(sItem);
                        AchievementsHelper.CurrentlyMining = false;
                    }
                }
                else if (Main.tileAxe[(int)tile.type])
                {
                    if (tile.type == 80)
                    {
                        num += (int)((float)(sItem.axe * 3) * 1.2f);
                    }
                    else
                    {
                        num += (int)((float)sItem.axe * 1.2f);
                    }
                    if (Main.getGoodWorld)
                    {
                        num = (int)((double)num * 1.3);
                    }
                    if (sItem.axe > 0)
                    {
                        this.IntentionGuesser.Track(this, x, y, GuessedPlayerIntention.HarvestTrees);
                        AchievementsHelper.CurrentlyMining = true;
                        if (!WorldGen.CanKillTile(x, y))
{
                            num = 0;
                        }
                        if (Main.dontStarveWorld && Main.myPlayer == this.whoAmI && num > 0 && tile.type == 80)
{
                            this.Hurt(PlayerDeathReason.ByOther(3), Main.DamageVar(6f, -this.luck), 0, false, false, false, ImmunityCooldownID.TileContactDamage, true);
                        }
                        if (this.hitTile.AddDamage(num2, num, true) >= 100)
{
                            if (this.whoAmI == Main.myPlayer && sItem.type == 5095 && (TileID.Sets.IsATreeTrunk[(int)tile.type] || tile.type == 323 || tile.type == 80))
{
                                LucyAxeMessage.MessageSource messageSource = LucyAxeMessage.MessageSource.ChoppedTree;
                                if (TileID.Sets.CountsAsGemTree[(int)tile.type])
{
                                    messageSource = LucyAxeMessage.MessageSource.ChoppedGemTree;
                                }
                                if (tile.type == 80)
{
                                    messageSource = LucyAxeMessage.MessageSource.ChoppedCactus;
                                    LucyAxeMessage.TryCreatingMessageWithCooldown(messageSource, base.Top, new Vector2((float)(this.direction * 7), -7f), 420);
                                }
                                else
{
                                    LucyAxeMessage.Create(messageSource, base.Top, new Vector2((float)(this.direction * 7), -7f));
                                }
                            }
                            this.ClearMiningCacheAt(x, y, 1);
                            bool flag = this.IsBottomOfTreeTrunkNoRoots(x, y);
                            WorldGen.KillTile(x, y, false, false, false);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                            }
                            if (sItem.type == 5295 && flag)
{
                                this.TryReplantingTree();
                            }
                            this.IntentionGuesser.AllowTracking(60);
                        }
                        else
{
                            WorldGen.KillTile(x, y, true, false, false);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 1f, 0, 0, 0);
                            }
                        }
                        if (num != 0)
{
                            this.hitTile.Prune();
                        }
                        this.ApplyItemTime(sItem);
                        AchievementsHelper.CurrentlyMining = false;
                    }
                }
                else if (sItem.pick > 0)
                {
                    this.IntentionGuesser.Track(this, x, y, GuessedPlayerIntention.HarvestTreasure);
                    this.PickTile(x, y, sItem.pick);
                }
                if (sItem.pick > 0)
                {
                    this.itemTime = (int)((float)sItem.useTime * this.pickSpeed);
                }
                this.ItemCheck_UseMiningTools_TryPoundingTile(sItem, num2, ref canHitWalls, x, y);
            }
        }
References Terraria.Tile.active(), Terraria.Item.axe, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.WorldGen.CanKillTile(), Terraria.ID.TileID.Sets.CountsAsGemTree, Terraria.GameContent.LucyAxeMessage.Create(), Terraria.Main.DamageVar(), Terraria.Main.dontStarveWorld, Terraria.Main.getGoodWorld, Terraria.Item.hammer, Terraria.Main.hardMode, int, Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.WorldGen.KillTile(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.pick, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Main.tileAxe, Terraria.ID.ImmunityCooldownID.TileContactDamage, Terraria.Main.tileHammer, Terraria.Main.tileNoFail, Terraria.GameContent.LucyAxeMessage.TryCreatingMessageWithCooldown(), Terraria.Item.type, and Terraria.Tile.type.