Terraria Decompiled: Terraria.Player.FindPulley
FindPulley()
void Terraria.Player.FindPulley () inline
Definition at line 17883 of file Player.cs.
        {
            if (this.portableStoolInfo.IsInUse)
            {
                return;
            }
            if (this.controlUp || this.controlDown)
            {
                int num = (int)(this.position.X + (float)(this.width / 2)) / 16;
                int num2 = (int)(this.position.Y - 8f) / 16;
                if (WorldGen.IsRope(num, num2, 5))
                {
                    float num3 = this.position.Y;
                    if (Main.tile[num, num2 - 1] == null)
                    {
                        Main.tile[num, num2 - 1] = new Tile();
                    }
                    if (Main.tile[num, num2 + 1] == null)
                    {
                        Main.tile[num, num2 + 1] = new Tile();
                    }
                    if ((!Main.tile[num, num2 - 1].active() || !Main.tileRope[(int)Main.tile[num, num2 - 1].type]) && (!Main.tile[num, num2 + 1].active() || !Main.tileRope[(int)Main.tile[num, num2 + 1].type]))
                    {
                        num3 = (float)(num2 * 16 + 22);
                    }
                    float num4 = (float)(num * 16 + 8 - this.width / 2 + 6 * this.direction);
                    int num5 = num * 16 + 8 - this.width / 2 + 6;
                    int num6 = num * 16 + 8 - this.width / 2;
                    int num7 = num * 16 + 8 - this.width / 2 + -6;
                    int num8 = 1;
                    float num9 = Math.Abs(this.position.X - (float)num5);
                    if (Math.Abs(this.position.X - (float)num6) < num9)
                    {
                        num8 = 2;
                        num9 = Math.Abs(this.position.X - (float)num6);
                    }
                    if (Math.Abs(this.position.X - (float)num7) < num9)
                    {
                        num8 = 3;
                        num9 = Math.Abs(this.position.X - (float)num7);
                    }
                    if (num8 == 1)
                    {
                        num4 = (float)num5;
                        this.pulleyDir = 2;
                        this.direction = 1;
                    }
                    if (num8 == 2)
                    {
                        num4 = (float)num6;
                        this.pulleyDir = 1;
                    }
                    if (num8 == 3)
                    {
                        num4 = (float)num7;
                        this.pulleyDir = 2;
                        this.direction = -1;
                    }
                    if (!Collision.SolidCollision(new Vector2(num4, this.position.Y), this.width, this.height))
                    {
                        if (this.whoAmI == Main.myPlayer)
{
                            Main.cameraX = Main.cameraX + this.position.X - num4;
                        }
                        this.pulley = true;
                        this.position.X = num4;
                        this.gfxOffY = this.position.Y - num3;
                        this.stepSpeed = 2.5f;
                        this.position.Y = num3;
                        this.velocity.X = 0f;
                        return;
                    }
                    num4 = (float)num5;
                    this.pulleyDir = 2;
                    this.direction = 1;
                    if (!Collision.SolidCollision(new Vector2(num4, this.position.Y), this.width, this.height))
                    {
                        if (this.whoAmI == Main.myPlayer)
{
                            Main.cameraX = Main.cameraX + this.position.X - num4;
                        }
                        this.pulley = true;
                        this.position.X = num4;
                        this.gfxOffY = this.position.Y - num3;
                        this.stepSpeed = 2.5f;
                        this.position.Y = num3;
                        this.velocity.X = 0f;
                        return;
                    }
                    num4 = (float)num7;
                    this.pulleyDir = 2;
                    this.direction = -1;
                    if (!Collision.SolidCollision(new Vector2(num4, this.position.Y), this.width, this.height))
                    {
                        if (this.whoAmI == Main.myPlayer)
{
                            Main.cameraX = Main.cameraX + this.position.X - num4;
                        }
                        this.pulley = true;
                        this.position.X = num4;
                        this.gfxOffY = this.position.Y - num3;
                        this.stepSpeed = 2.5f;
                        this.position.Y = num3;
                        this.velocity.X = 0f;
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), int, Terraria.WorldGen.IsRope(), Terraria.Main.myPlayer, Terraria.Collision.SolidCollision(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileRope, and Terraria.Tile.type.