Terraria Decompiled: Terraria.Player.DropItemFromExtractinator
DropItemFromExtractinator()
void Terraria.Player.DropItemFromExtractinator (int itemType, int stack) inline private
Definition at line 41132 of file Player.cs.
        {
            Vector2 vector = Main.ReverseGravitySupport(Main.MouseScreen, 0f) + Main.screenPosition;
            if (Main.SmartCursorIsUsed || PlayerInput.UsingGamepad)
            {
                vector = base.Center;
            }
            int num = Item.NewItem(this.GetItemSource_TileInteraction(Player.tileTargetX, Player.tileTargetY), (int)vector.X, (int)vector.Y, 1, 1, itemType, stack, false, -1, false);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, num, 1f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Main.MouseScreen, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, Terraria.NetMessage.SendData(), Terraria.Main.SmartCursorIsUsed, System.stack, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.