Terraria Decompiled: Terraria.Player.ItemCheck_Shoot
ItemCheck_Shoot()
void Terraria.Player.ItemCheck_Shoot (int i, Item sItem, int weaponDamage, bool withAudioVisualFeedback = true) inline private
Definition at line 46418 of file Player.cs.
        {
            int num = sItem.shoot;
            float num2 = sItem.shootSpeed;
            int damage = sItem.damage;
            if (sItem.melee && !ProjectileID.Sets.NoMeleeSpeedVelocityScaling[num])
            {
                num2 /= this.meleeSpeed;
            }
            bool flag = false;
            int num3 = weaponDamage;
            float num4 = sItem.knockBack;
            int num5 = 0;
            if (sItem.useAmmo > 0)
            {
                this.PickAmmo(sItem, ref num, ref num2, ref flag, ref num3, ref num4, out num5, ItemID.Sets.gunProj[sItem.type]);
            }
            else
            {
                flag = true;
            }
            if (ItemID.Sets.gunProj[sItem.type])
            {
                num4 = sItem.knockBack;
                num3 = weaponDamage;
                num2 = sItem.shootSpeed;
            }
            if (ProjectileID.Sets.IsAPhaseblade[sItem.shoot] && sItem.type != 671)
            {
                num4 *= 1.25f;
                switch (sItem.shoot)
                {
                case 1065:
                case 1066:
                case 1067:
                case 1068:
                case 1069:
                case 1070:
                case 1072:
                case 1076:
                    num3 = (int)((double)num3 * 1.5);
                    break;
                default:
                    num3 = (int)((double)num3 * 1.25);
                    break;
                }
            }
            if (sItem.IsACoin)
            {
                flag = false;
            }
            if (sItem.type == 1254 && num == 14)
            {
                num = 242;
            }
            if (sItem.type == 1255 && num == 14)
            {
                num = 242;
            }
            if (sItem.type == 1265 && num == 14)
            {
                num = 242;
            }
            if (sItem.type == 3542)
            {
                if (Main.rand.Next(100) < 20)
                {
                    num++;
                    num3 *= 3;
                }
                else
                {
                    num2 -= 1f;
                }
            }
            if (sItem.type == 1928)
            {
                num3 = (int)((float)num3 * 1f);
            }
            if (sItem.type == 3063)
            {
                num3 = (int)((float)num3 * 1.25f);
            }
            if (sItem.type == 1306)
            {
                num3 = (int)((double)num3 * 0.67);
            }
            if (sItem.type == 1227)
            {
                num3 = (int)((double)num3 * 0.7);
            }
            if (flag)
            {
                num4 = this.GetWeaponKnockback(sItem, num4);
                IEntitySource projectileSource_Item_WithPotentialAmmo = this.GetProjectileSource_Item_WithPotentialAmmo(sItem, num5);
                if (num == 228)
                {
                    num4 = 0f;
                }
                if (num == 1 && sItem.type == 120)
                {
                    num = 2;
                }
                if (sItem.type == 682)
                {
                    num = 117;
                }
                if (sItem.type == 725)
                {
                    num = 120;
                }
                if (sItem.type == 2796)
                {
                    num = 442;
                }
                if (sItem.type == 2223)
                {
                    num = 357;
                }
                if (sItem.type == 5117)
                {
                    num = 968;
                }
                if (sItem.fishingPole > 0 && this.overrideFishingBobber > -1)
                {
                    num = this.overrideFishingBobber;
                }
                if (withAudioVisualFeedback)
                {
                    this.ApplyItemTime(sItem);
                }
                Vector2 mountedCenter = this.MountedCenter;
                Vector2 vector = this.RotatedRelativePoint(mountedCenter, false, true);
                bool flag2 = true;
                int num6 = sItem.type;
                if (num6 == 723 || num6 == 3611)
                {
                    flag2 = false;
                }
                Vector2 vector2 = Vector2.UnitX.RotatedBy((double)this.fullRotation, default(Vector2));
                Vector2 vector3 = Main.MouseWorld - vector;
                Vector2 vector4 = this.itemRotation.ToRotationVector2() * (float)this.direction;
                if (sItem.type == 3852 && !this.ItemAnimationJustStarted)
                {
                    vector3 = (vector4.ToRotation() + this.fullRotation).ToRotationVector2();
                }
                if (vector3 != Vector2.Zero)
                {
                    vector3.Normalize();
                }
                float num7 = Vector2.Dot(vector2, vector3);
                if (flag2)
                {
                    if (num7 > 0f)
                    {
                        this.ChangeDir(1);
                    }
                    else
                    {
                        this.ChangeDir(-1);
                    }
                }
                if (sItem.type == 3094 || sItem.type == 3378 || sItem.type == 3543)
                {
                    vector.Y = this.position.Y + (float)(this.height / 3);
                }
                if (sItem.type == 5117)
                {
                    vector.Y = this.position.Y + (float)(this.height / 3);
                }
                if (sItem.type == 517)
                {
                    vector.X += (float)Main.rand.Next(-3, 4) * 3.5f;
                    vector.Y += (float)Main.rand.Next(-3, 4) * 3.5f;
                }
                if (sItem.type == 2611 || sItem.type == 5526)
                {
                    Vector2 vector5 = vector3;
                    if (vector5 != Vector2.Zero)
                    {
                        vector5.Normalize();
                    }
                    vector += vector5;
                }
                if (sItem.type == 3827)
                {
                    vector += vector3.SafeNormalize(Vector2.Zero).RotatedBy((double)((float)this.direction * -1.5707964f), default(Vector2)) * 24f;
                }
                if (num == 9)
                {
                    float num8 = (float)Main.mouseX + Main.screenPosition.X;
                    int num9 = -1;
                    if (num8 < base.Left.X)
                    {
                        num9 = 1;
                    }
                    else if (num8 <= base.Right.X && Main.rand.Next(2) == 0)
                    {
                        num9 = 1;
                    }
                    vector = new Vector2(this.position.X + (float)this.width * 0.5f + (float)(Main.rand.Next(201) * num9) + ((float)Main.mouseX + Main.screenPosition.X - this.position.X), this.MountedCenter.Y - 600f);
                    num4 = 0f;
                    num3 = (int)((float)num3 * 1.5f);
                }
                if (sItem.type == 986 || sItem.type == 281)
                {
                    vector.X += (float)(6 * this.direction);
                    vector.Y -= 6f * this.gravDir;
                }
                if (sItem.type == 3007)
                {
                    vector.X -= (float)(4 * this.direction);
                    vector.Y -= 2f * this.gravDir;
                }
                float num10 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                float num11 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
                if (sItem.type == 3852 && !this.ItemAnimationJustStarted)
                {
                    Vector2 vector6 = vector3;
                    num10 = vector6.X;
                    num11 = vector6.Y;
                }
                if (this.gravDir == -1f)
                {
                    num11 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector.Y;
                }
                float num12 = (float)Math.Sqrt((double)(num10 * num10 + num11 * num11));
                float num13 = num12;
                if ((float.IsNaN(num10) && float.IsNaN(num11)) || (num10 == 0f && num11 == 0f))
                {
                    num10 = (float)this.direction;
                    num11 = 0f;
                    num12 = num2;
                }
                else
                {
                    num12 = num2 / num12;
                }
                if (sItem.type == 1929 || sItem.type == 2270)
                {
                    num10 += (float)Main.rand.Next(-50, 51) * 0.03f / num12;
                    num11 += (float)Main.rand.Next(-50, 51) * 0.03f / num12;
                }
                num10 *= num12;
                num11 *= num12;
                if (num == 250)
                {
                    for (int j = 0; j < 1000; j++)
                    {
                        if (Main.projectile[j].active && Main.projectile[j].owner == this.whoAmI && (Main.projectile[j].type == 250 || Main.projectile[j].type == 251))
{
                            Main.projectile[j].Kill();
                        }
                    }
                }
                if (num == 12 && Collision.CanHitLine(base.Center, 0, 0, vector + new Vector2(num10, num11) * 4f, 0, 0))
                {
                    vector += new Vector2(num10, num11) * 3f;
                }
                if (num == 728 && !Collision.CanHitLine(base.Center, 0, 0, vector + new Vector2(num10, num11) * 2f, 0, 0))
                {
                    Vector2 vector7 = new Vector2(num10, num11) * 0.25f;
                    vector = base.Center - vector7;
                }
                if (num == 85)
                {
                    vector += new Vector2(0f, -6f * (float)this.direction * this.Directions.Y).RotatedBy((double)vector3.ToRotation(), default(Vector2));
                    if (Collision.CanHitLine(vector, 0, 0, vector + new Vector2(num10, num11) * 5f, 0, 0))
                    {
                        vector += new Vector2(num10, num11) * 4f;
                    }
                }
                if (num == 802 || num == 842)
                {
                    Vector2 vector8 = new Vector2(num10, num11);
                    float num14 = 0.7853982f;
                    Vector2 vector9 = vector8.SafeNormalize(Vector2.Zero).RotatedBy((double)(num14 * (Main.rand.NextFloat() - 0.5f)), default(Vector2)) * (vector8.Length() - Main.rand.NextFloatDirection() * 0.7f);
                    num10 = vector9.X;
                    num11 = vector9.Y;
                }
                if (sItem.useStyle == 5)
                {
                    if (sItem.type == 3029)
                    {
                        Vector2 vector10 = new Vector2(num10, num11);
                        vector10.X = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                        vector10.Y = (float)Main.mouseY + Main.screenPosition.Y - vector.Y - 1000f;
                        this.itemRotation = (float)Math.Atan2((double)(vector10.Y * (float)this.direction), (double)(vector10.X * (float)this.direction));
                    }
                    else if (sItem.type == 4381)
                    {
                        Vector2 vector11 = new Vector2(num10, num11);
                        vector11.X = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                        vector11.Y = (float)Main.mouseY + Main.screenPosition.Y - vector.Y - 1000f;
                        this.itemRotation = (float)Math.Atan2((double)(vector11.Y * (float)this.direction), (double)(vector11.X * (float)this.direction));
                    }
                    else if (sItem.type == 3779)
                    {
                        this.itemRotation = 0f;
                    }
                    else
                    {
                        this.itemRotation = (float)Math.Atan2((double)(num11 * (float)this.direction), (double)(num10 * (float)this.direction)) - this.fullRotation;
                    }
                    NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                    NetMessage.SendData(41, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                }
                if (sItem.useStyle == 13)
                {
                    this.itemRotation = (float)Math.Atan2((double)(num11 * (float)this.direction), (double)(num10 * (float)this.direction)) - this.fullRotation;
                    NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                    NetMessage.SendData(41, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                }
                if (num == 17)
                {
                    vector.X = (float)Main.mouseX + Main.screenPosition.X;
                    vector.Y = (float)Main.mouseY + Main.screenPosition.Y;
                    if (this.gravDir == -1f)
                    {
                        vector.Y = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY;
                    }
                    this.LimitPointToPlayerReachableArea(ref vector);
                }
                if (num == 76)
                {
                    num += Main.rand.Next(3);
                    float smallerScaledAxis = Main.Camera.SmallerScaledAxis;
                    num13 /= smallerScaledAxis / 2f;
                    if (num13 > 1f)
                    {
                        num13 = 1f;
                    }
                    float num15 = num10 + (float)Main.rand.Next(-40, 41) * 0.01f;
                    float num16 = num11 + (float)Main.rand.Next(-40, 41) * 0.01f;
                    num13 *= 1.75f;
                    num15 *= num13 + 0.1f;
                    num16 *= num13 + 0.1f;
                    int num17 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num15, num16, num, num3, num4, i, 0f, 1f, 0f, null);
                    num13 = num13 * 2f - 1f;
                    if (num13 < -1f)
                    {
                        num13 = -1f;
                    }
                    if (num13 > 1f)
                    {
                        num13 = 1f;
                    }
                    Main.projectile[num17].ai[0] = num13;
                    NetMessage.SendData(27, -1, -1, null, num17, 0f, 0f, 0f, 0, 0, 0);
                    return;
                }
                if (sItem.type == 3029)
                {
                    int num18 = 3;
                    if (num == 91 || num == 4 || num == 5 || num == 41)
                    {
                        if (Main.rand.Next(3) == 0)
{
                            num18--;
                        }
                    }
                    else if (Main.rand.Next(3) == 0)
                    {
                        num18++;
                    }
                    for (int k = 0; k < num18; k++)
                    {
                        vector = new Vector2(this.position.X + (float)this.width * 0.5f + (float)(Main.rand.Next(201) * -(float)this.direction) + ((float)Main.mouseX + Main.screenPosition.X - this.position.X), this.MountedCenter.Y - 600f);
                        vector.X = (vector.X * 10f + base.Center.X) / 11f + (float)Main.rand.Next(-100, 101);
                        vector.Y -= (float)(150 * k);
                        num10 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                        num11 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
                        if (num11 < 0f)
{
                            num11 *= -1f;
                        }
                        if (num11 < 20f)
{
                            num11 = 20f;
                        }
                        num12 = (float)Math.Sqrt((double)(num10 * num10 + num11 * num11));
                        num12 = num2 / num12;
                        num10 *= num12;
                        num11 *= num12;
                        float num19 = num10 + (float)Main.rand.Next(-40, 41) * 0.03f;
                        float num20 = num11 + (float)Main.rand.Next(-40, 41) * 0.03f;
                        num19 *= (float)Main.rand.Next(75, 150) * 0.01f;
                        vector.X += (float)Main.rand.Next(-50, 51);
                        int num21 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num19, num20, num, num3, num4, i, 0f, 0f, 0f, null);
                        Main.projectile[num21].noDropItem = true;
                    }
                    return;
                }
                if (sItem.type == 4381)
                {
                    int num22 = Main.rand.Next(1, 3);
                    if (Main.rand.Next(3) == 0)
                    {
                        num22++;
                    }
                    for (int l = 0; l < num22; l++)
                    {
                        vector = new Vector2(this.position.X + (float)this.width * 0.5f + (float)(Main.rand.Next(61) * -(float)this.direction) + ((float)Main.mouseX + Main.screenPosition.X - this.position.X), this.MountedCenter.Y - 600f);
                        vector.X = (vector.X * 10f + base.Center.X) / 11f + (float)Main.rand.Next(-30, 31);
                        vector.Y -= 150f * Main.rand.NextFloat();
                        num10 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                        num11 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
                        if (num11 < 0f)
{
                            num11 *= -1f;
                        }
                        if (num11 < 20f)
{
                            num11 = 20f;
                        }
                        num12 = (float)Math.Sqrt((double)(num10 * num10 + num11 * num11));
                        num12 = num2 / num12;
                        num10 *= num12;
                        num11 *= num12;
                        float num23 = num10 + (float)Main.rand.Next(-20, 21) * 0.03f;
                        float num24 = num11 + (float)Main.rand.Next(-40, 41) * 0.03f;
                        num23 *= (float)Main.rand.Next(55, 80) * 0.01f;
                        vector.X += (float)Main.rand.Next(-50, 51);
                        int num25 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num23, num24, num, num3, num4, i, 0f, 0f, 0f, null);
                        Main.projectile[num25].noDropItem = true;
                    }
                    return;
                }
                if (sItem.type == 98 || sItem.type == 533)
                {
                    float num26 = num10 + (float)Main.rand.Next(-40, 41) * 0.01f;
                    float num27 = num11 + (float)Main.rand.Next(-40, 41) * 0.01f;
                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num26, num27, num, num3, num4, i, 0f, 0f, 0f, null);
                    return;
                }
                if (sItem.type == 1319)
                {
                    float num28 = num10 + (float)Main.rand.Next(-40, 41) * 0.02f;
                    float num29 = num11 + (float)Main.rand.Next(-40, 41) * 0.02f;
                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num28, num29, num, num3, num4, i, 0f, 0f, 0f, null);
                    return;
                }
                if (sItem.type == 3107)
                {
                    float num30 = num10 + (float)Main.rand.Next(-40, 41) * 0.02f;
                    float num31 = num11 + (float)Main.rand.Next(-40, 41) * 0.02f;
                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num30, num31, num, num3, num4, i, 0f, 0f, 0f, null);
                    return;
                }
                if (ProjectileID.Sets.IsAGolfBall[num])
                {
                    Vector2 vector12 = new Vector2((float)Main.mouseX + Main.screenPosition.X, (float)Main.mouseY + Main.screenPosition.Y);
                    Vector2 vector13 = vector12 - base.Center;
                    bool flag3 = false;
                    if (vector13.Length() < 100f)
                    {
                        flag3 = this.TryPlacingAGolfBallNearANearbyTee(vector12);
                    }
                    if (!flag3)
                    {
                        if (vector13.Length() > 100f || !Collision.CanHit(base.Center, 1, 1, vector12, 1, 1))
{
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 0f, 0f, null);
                            return;
                        }
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector12.X, vector12.Y, 0f, 0f, num, num3, num4, i, 0f, 0f, 0f, null);
                        return;
                    }
                }
                else
                {
                    if (sItem.type == 3053)
                    {
                        bool flag4 = false;
                        if (this.itemAnimation <= sItem.useTime + 1)
{
                            flag4 = true;
                        }
                        Vector2 vector14 = new Vector2(num10, num11);
                        vector14.Normalize();
                        vector14 *= 4f;
                        if (!flag4)
{
                            Vector2 vector15 = new Vector2((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                            vector15.Normalize();
                            vector14 += vector15;
                        }
                        vector14.Normalize();
                        vector14 *= sItem.shootSpeed;
                        float num32 = (float)Main.rand.Next(10, 80) * 0.001f;
                        if (Main.rand.Next(2) == 0)
{
                            num32 *= -1f;
                        }
                        float num33 = (float)Main.rand.Next(10, 80) * 0.001f;
                        if (Main.rand.Next(2) == 0)
{
                            num33 *= -1f;
                        }
                        if (flag4)
{
                            num32 = (num33 = 0f);
                        }
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector14.X, vector14.Y, num, num3, num4, i, num33, num32, 0f, null);
                        return;
                    }
                    if (sItem.type == 3019)
                    {
                        Vector2 vector16 = new Vector2(num10, num11);
                        vector16 = vector16.RotatedByRandom(0.39269909262657166);
                        Vector2 vector17 = new Vector2(num10, num11);
                        vector17 = vector17.RotatedByRandom(0.19634954631328583);
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector17.X, vector17.Y, num, num3, num4, i, vector16.X, vector16.Y, 0f, null);
                        return;
                    }
                    if (sItem.type == 2797)
                    {
                        Vector2 vector18 = Vector2.Normalize(new Vector2(num10, num11)) * 40f * sItem.scale;
                        if (Collision.CanHit(vector, 0, 0, vector + vector18, 0, 0))
{
                            vector += vector18;
                        }
                        float num34 = new Vector2(num10, num11).ToRotation();
                        float num35 = 2.0943952f;
                        int num36 = Main.rand.Next(4, 5);
                        if (Main.rand.Next(4) == 0)
{
                            num36++;
                        }
                        for (int m = 0; m < num36; m++)
{
                            float num37 = (float)Main.rand.NextDouble() * 0.2f + 0.05f;
                            Vector2 vector19 = new Vector2(num10, num11).RotatedBy((double)(num35 * (float)Main.rand.NextDouble() - num35 / 2f), default(Vector2)) * num37;
                            int num38 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector19.X, vector19.Y, 444, num3, num4, i, num34, 0f, 0f, null);
                            Main.projectile[num38].localAI[0] = (float)num;
                            Main.projectile[num38].localAI[1] = num2;
                        }
                        return;
                    }
                    if (sItem.type == 2270)
                    {
                        float num39 = num10 + (float)Main.rand.Next(-40, 41) * 0.05f;
                        float num40 = num11 + (float)Main.rand.Next(-40, 41) * 0.05f;
                        if (Main.rand.Next(3) == 0)
{
                            num39 *= 1f + (float)Main.rand.Next(-30, 31) * 0.02f;
                            num40 *= 1f + (float)Main.rand.Next(-30, 31) * 0.02f;
                        }
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num39, num40, num, num3, num4, i, 0f, 0f, 0f, null);
                        return;
                    }
                    if (sItem.type == 5117)
                    {
                        float num41 = num10 + (float)Main.rand.Next(-15, 16) * 0.075f;
                        float num42 = num11 + (float)Main.rand.Next(-15, 16) * 0.075f;
                        int num43 = Main.rand.Next(Main.projFrames[sItem.shoot]);
                        int num44 = num3;
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num41, num42, num, num44, num4, i, 0f, (float)num43, 0f, null);
                        return;
                    }
                    if (sItem.type == 1930)
                    {
                        int num45 = 2 + Main.rand.Next(3);
                        for (int n = 0; n < num45; n++)
{
                            float num46 = num10;
                            float num47 = num11;
                            float num48 = 0.025f * (float)n;
                            num46 += (float)Main.rand.Next(-35, 36) * num48;
                            num47 += (float)Main.rand.Next(-35, 36) * num48;
                            num12 = (float)Math.Sqrt((double)(num46 * num46 + num47 * num47));
                            num12 = num2 / num12;
                            num46 *= num12;
                            num47 *= num12;
                            float num49 = vector.X + num10 * (float)(num45 - n) * 1.75f;
                            float num50 = vector.Y + num11 * (float)(num45 - n) * 1.75f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, num49, num50, num46, num47, num, num3, num4, i, (float)Main.rand.Next(0, 10 * (n + 1)), 0f, 0f, null);
                        }
                        return;
                    }
                    if (sItem.type == 1931)
                    {
                        int num51 = 2;
                        for (int num52 = 0; num52 < num51; num52++)
{
                            vector = new Vector2(this.position.X + (float)this.width * 0.5f + (float)(Main.rand.Next(201) * -(float)this.direction) + ((float)Main.mouseX + Main.screenPosition.X - this.position.X), this.MountedCenter.Y - 600f);
                            vector.X = (vector.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                            vector.Y -= (float)(100 * num52);
                            num10 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                            num11 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
                            if (this.gravDir == -1f)
{
                                num11 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector.Y;
                            }
                            if (num11 < 0f)
{
                                num11 *= -1f;
                            }
                            if (num11 < 20f)
{
                                num11 = 20f;
                            }
                            num12 = (float)Math.Sqrt((double)(num10 * num10 + num11 * num11));
                            num12 = num2 / num12;
                            num10 *= num12;
                            num11 *= num12;
                            float num53 = num10 + (float)Main.rand.Next(-40, 41) * 0.02f;
                            float num54 = num11 + (float)Main.rand.Next(-40, 41) * 0.02f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num53, num54, num, num3, num4, i, 0f, (float)Main.rand.Next(5), 0f, null);
                        }
                        return;
                    }
                    if (sItem.type == 2750)
                    {
                        int num55 = 1;
                        for (int num56 = 0; num56 < num55; num56++)
{
                            vector = new Vector2(this.position.X + (float)this.width * 0.5f + (float)(Main.rand.Next(201) * -(float)this.direction) + ((float)Main.mouseX + Main.screenPosition.X - this.position.X), this.MountedCenter.Y - 600f);
                            vector.X = (vector.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                            vector.Y -= (float)(100 * num56);
                            num10 = (float)Main.mouseX + Main.screenPosition.X - vector.X + (float)Main.rand.Next(-40, 41) * 0.03f;
                            num11 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
                            if (this.gravDir == -1f)
{
                                num11 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector.Y;
                            }
                            if (num11 < 0f)
{
                                num11 *= -1f;
                            }
                            if (num11 < 20f)
{
                                num11 = 20f;
                            }
                            num12 = (float)Math.Sqrt((double)(num10 * num10 + num11 * num11));
                            num12 = num2 / num12;
                            num10 *= num12;
                            num11 *= num12;
                            float num57 = num10;
                            float num58 = num11 + (float)Main.rand.Next(-40, 41) * 0.02f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num57 * 0.75f, num58 * 0.75f, num + Main.rand.Next(3), num3, num4, i, 0f, 0.5f + (float)Main.rand.NextDouble() * 0.3f, 0f, null);
                        }
                        return;
                    }
                    if (sItem.type == 3570)
                    {
                        int num59 = 3;
                        for (int num60 = 0; num60 < num59; num60++)
{
                            vector = new Vector2(this.position.X + (float)this.width * 0.5f + (float)(Main.rand.Next(201) * -(float)this.direction) + ((float)Main.mouseX + Main.screenPosition.X - this.position.X), this.MountedCenter.Y - 600f);
                            vector.X = (vector.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                            vector.Y -= (float)(100 * num60);
                            num10 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                            num11 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
                            float num61 = num11 + vector.Y;
                            if (num11 < 0f)
{
                                num11 *= -1f;
                            }
                            if (num11 < 20f)
{
                                num11 = 20f;
                            }
                            num12 = (float)Math.Sqrt((double)(num10 * num10 + num11 * num11));
                            num12 = num2 / num12;
                            num10 *= num12;
                            num11 *= num12;
                            Vector2 vector20 = new Vector2(num10, num11) / 2f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector20.X, vector20.Y, num, num3, num4, i, 0f, num61, 0f, null);
                        }
                        return;
                    }
                    if (sItem.type == 5065)
                    {
                        Vector2 farthestSpawnPositionOnLine = this.GetFarthestSpawnPositionOnLine(vector, num10, num11);
                        Vector2 zero = Vector2.Zero;
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, farthestSpawnPositionOnLine, zero, num, num3, num4, i, 0f, 0f, 0f, null);
                        return;
                    }
                    if (sItem.type == 3065)
                    {
                        Vector2 vector21 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY);
                        float num62 = vector21.Y;
                        if (num62 > base.Center.Y - 200f)
{
                            num62 = base.Center.Y - 200f;
                        }
                        for (int num63 = 0; num63 < 3; num63++)
{
                            vector = base.Center + new Vector2((float)(-(float)Main.rand.Next(0, 401) * this.direction), -600f);
                            vector.Y -= (float)(100 * num63);
                            Vector2 vector22 = vector21 - vector;
                            if (vector22.Y < 0f)
{
                                vector22.Y *= -1f;
                            }
                            if (vector22.Y < 20f)
{
                                vector22.Y = 20f;
                            }
                            vector22.Normalize();
                            vector22 *= num2;
                            num10 = vector22.X;
                            num11 = vector22.Y;
                            float num64 = num10;
                            float num65 = num11 + (float)Main.rand.Next(-40, 41) * 0.02f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num64, num65, num, num3, num4, i, 0f, num62, 0f, null);
                        }
                        return;
                    }
                    if (sItem.type == 2624)
                    {
                        float num66 = 0.31415927f;
                        int num67 = 5;
                        Vector2 vector23 = new Vector2(num10, num11);
                        vector23.Normalize();
                        vector23 *= 40f;
                        bool flag5 = Collision.CanHit(vector, 0, 0, vector + vector23, 0, 0);
                        for (int num68 = 0; num68 < num67; num68++)
{
                            float num69 = (float)num68 - ((float)num67 - 1f) / 2f;
                            Vector2 vector24 = vector23.RotatedBy((double)(num66 * num69), default(Vector2));
                            if (!flag5)
{
                                vector24 -= vector23;
                            }
                            Vector2 vector25 = vector + vector24;
                            Vector2 vector26 = (vector25 - base.Center).SafeNormalize(Vector2.Zero);
                            if (!Collision.CanHitLine(this.MountedCenter, 4, 4, vector25 - new Vector2(num10, num11), 0, 0))
{
                                vector25 -= vector26 * 15f;
                            }
                            int num70 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector25.X, vector25.Y, num10, num11, num, num3, num4, i, 0f, 0f, 0f, null);
                            Main.projectile[num70].noDropItem = true;
                        }
                        return;
                    }
                    if (sItem.type == 1929)
                    {
                        float num71 = num10 + (float)Main.rand.Next(-40, 41) * 0.03f;
                        float num72 = num11 + (float)Main.rand.Next(-40, 41) * 0.03f;
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num71, num72, num, num3, num4, i, 0f, 0f, 0f, null);
                        return;
                    }
                    if (sItem.type == 1553)
                    {
                        float num73 = num10 + (float)Main.rand.Next(-40, 41) * 0.005f;
                        float num74 = num11 + (float)Main.rand.Next(-40, 41) * 0.005f;
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num73, num74, num, num3, num4, i, 0f, 0f, 0f, null);
                        return;
                    }
                    if (sItem.type == 518)
                    {
                        float num75 = num10;
                        float num76 = num11;
                        num75 += (float)Main.rand.Next(-40, 41) * 0.04f;
                        num76 += (float)Main.rand.Next(-40, 41) * 0.04f;
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num75, num76, num, num3, num4, i, 0f, 0f, 0f, null);
                        return;
                    }
                    if (sItem.type == 1265)
                    {
                        float num77 = num10;
                        float num78 = num11;
                        num77 += (float)Main.rand.Next(-30, 31) * 0.03f;
                        num78 += (float)Main.rand.Next(-30, 31) * 0.03f;
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num77, num78, num, num3, num4, i, 0f, 0f, 0f, null);
                        return;
                    }
                    if (sItem.type == 4262)
                    {
                        float num79 = 2.6666667f;
                        Vector2 bottom = base.Bottom;
                        int num80 = (int)base.Bottom.X / 16;
                        float num81 = Math.Abs((float)Main.mouseX + Main.screenPosition.X - this.position.X) / 16f;
                        if (this.direction < 0)
{
                            num81 += 1f;
                        }
                        int num82 = (int)num81;
                        if (num82 > 15)
{
                            num82 = 15;
                        }
                        Point point = base.Center.ToTileCoordinates();
                        int num83 = 31;
                        for (int num84 = num82; num84 >= 0; num84--)
{
                            Point point2;
                            if (Collision.CanHitLine(base.Center, 1, 1, base.Center + new Vector2((float)(16 * num84 * this.direction), 0f), 1, 1) && WorldUtils.Find(new Point(point.X + this.direction * num84, point.Y), Searches.Chain(new Searches.Down(num83), new GenCondition[]
{
                                new Conditions.MysticSnake()
                            }), out point2))
{
                                int num85 = point2.Y;
                                while (Main.tile[point2.X, num85 - 1].active())
{
                                    num85--;
                                    if (Main.tile[point2.X, num85 - 1] == null || num85 < 10 || point2.Y - num85 > 7)
{
                                        num85 = -1;
                                        break;
                                    }
                                }
                                if (num85 >= 10)
{
                                    point2.Y = num85;
                                    for (int num86 = 0; num86 < 1000; num86++)
{
                                        Projectile projectile = Main.projectile[num86];
                                        if (projectile.active && projectile.owner == this.whoAmI && projectile.type == num)
{
                                            if (projectile.ai[1] == 2f)
{
                                                projectile.timeLeft = 4;
                                            }
                                            else
{
                                                projectile.Kill();
                                            }
                                        }
                                    }
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, (float)(point2.X * 16 + 8), (float)(point2.Y * 16 + 8 - 16), 0f, -num79, num, num3, num4, i, (float)(point2.Y * 16 + 8 - 16), 0f, 0f, null);
                                    return;
                                }
                            }
                        }
                        return;
                    }
                    if (sItem.type == 4952)
                    {
                        Vector2 vector27 = Main.rand.NextVector2Circular(1f, 1f) + Main.rand.NextVector2CircularEdge(3f, 3f);
                        if (vector27.Y > 0f)
{
                            vector27.Y *= -1f;
                        }
                        float num87 = (float)this.itemAnimation / (float)this.itemAnimationMax * 0.66f + this.miscCounterNormalized;
                        vector = this.MountedCenter + new Vector2((float)(this.direction * 15), this.gravDir * 3f);
                        this.ApplyItemPositionOffsetFromMount(ref vector);
                        Point point3 = vector.ToTileCoordinates();
                        Tile tile = Main.tile[point3.X, point3.Y];
                        if (tile != null && tile.nactive() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type] && !TileID.Sets.Platforms[(int)tile.type])
{
                            vector = this.MountedCenter;
                        }
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector27.X, vector27.Y, num, num3, num4, i, -1f, num87 % 1f, 0f, null);
                        return;
                    }
                    if (sItem.type == 4953)
                    {
                        float num88 = 0.31415927f;
                        int num89 = 5;
                        Vector2 vector28 = new Vector2(num10, num11);
                        vector28.Normalize();
                        vector28 *= 40f;
                        bool flag6 = Collision.CanHit(vector, 0, 0, vector + vector28, 0, 0);
                        int num90 = (this.itemAnimationMax - this.itemAnimation) / 2;
                        int num91 = num90;
                        if (this.direction == 1)
{
                            num91 = 4 - num90;
                        }
                        float num92 = (float)num91 - ((float)num89 - 1f) / 2f;
                        Vector2 vector29 = vector28.RotatedBy((double)(num88 * num92), default(Vector2));
                        if (!flag6)
{
                            vector29 -= vector28;
                        }
                        Vector2 mouseWorld = Main.MouseWorld;
                        Vector2 vector30 = vector + vector29;
                        Vector2 vector31 = (vector30 - base.Center).SafeNormalize(Vector2.Zero);
                        if (!Collision.CanHitLine(this.MountedCenter, 4, 4, vector30 - new Vector2(num10, num11), 0, 0))
{
                            vector30 -= vector31 * 15f;
                        }
                        Vector2 vector32 = vector30.DirectionTo(mouseWorld).SafeNormalize(-Vector2.UnitY);
                        Vector2 vector33 = base.Center.DirectionTo(base.Center + new Vector2(num10, num11)).SafeNormalize(-Vector2.UnitY);
                        float lerpValue = Utils.GetLerpValue(100f, 40f, mouseWorld.Distance(base.Center), true);
                        if (lerpValue > 0f)
{
                            vector32 = Vector2.Lerp(vector32, vector33, lerpValue).SafeNormalize(new Vector2(num10, num11).SafeNormalize(-Vector2.UnitY));
                        }
                        Vector2 vector34 = vector32 * num2;
                        if (num90 == 2)
{
                            num = 932;
                            num3 *= 2;
                        }
                        if (num == 932)
{
                            float num93 = this.miscCounterNormalized * 12f % 1f;
                            vector34 = vector34.SafeNormalize(Vector2.Zero) * (num2 * 2f);
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector30, vector34, num, num3, num4, i, 0f, num93, 0f, null);
                            return;
                        }
                        int num94 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector30, vector34, num, num3, num4, i, 0f, 0f, 0f, null);
                        Main.projectile[num94].noDropItem = true;
                        return;
                    }
                    else
                    {
                        if (sItem.type == 534)
{
                            int num95 = Main.rand.Next(4, 6);
                            for (int num96 = 0; num96 < num95; num96++)
{
                                float num97 = num10;
                                float num98 = num11;
                                num97 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                num98 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num97, num98, num, num3, num4, i, 0f, 0f, 0f, null);
                            }
                            return;
                        }
                        if (sItem.type == 4703)
{
                            float num99 = 1.5707964f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 0f, 0f, null);
                            for (int num100 = 0; num100 < 7; num100++)
{
                                Vector2 vector35 = new Vector2(num10, num11);
                                float num101 = vector35.Length();
                                vector35 += vector35.SafeNormalize(Vector2.Zero).RotatedBy((double)(num99 * Main.rand.NextFloat()), default(Vector2)) * Main.rand.NextFloatDirection() * 5f;
                                vector35 = vector35.SafeNormalize(Vector2.Zero) * num101;
                                float num102 = vector35.X;
                                float num103 = vector35.Y;
                                num102 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                num103 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num102, num103, num, num3, num4, i, 0f, 0f, 0f, null);
                            }
                            return;
                        }
                        if (sItem.type == 4270)
{
                            Vector2 mouseWorld2 = Main.MouseWorld;
                            this.LimitPointToPlayerReachableArea(ref mouseWorld2);
                            Vector2 vector36 = mouseWorld2 + Main.rand.NextVector2Circular(8f, 8f);
                            Vector2 vector37 = this.FindSharpTearsSpot(vector36).ToWorldCoordinates((float)Main.rand.Next(17), (float)Main.rand.Next(17));
                            Vector2 vector38 = (vector36 - vector37).SafeNormalize(-Vector2.UnitY) * 16f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector37.X, vector37.Y, vector38.X, vector38.Y, num, num3, num4, i, 0f, Main.rand.NextFloat() * 0.5f + 0.6f, 0f, null);
                            return;
                        }
                        if (sItem.type == 4715)
{
                            Vector2 vector39 = Main.MouseWorld;
                            List<NPC> list;
                            bool sparkleGuitarTarget = this.GetSparkleGuitarTarget(out list);
                            if (sparkleGuitarTarget)
{
                                NPC npc = list[Main.rand.Next(list.Count)];
                                vector39 = npc.Center + npc.velocity * 20f;
                            }
                            Vector2 vector40 = vector39 - base.Center;
                            if (!sparkleGuitarTarget)
{
                                vector39 += Main.rand.NextVector2Circular(24f, 24f);
                                if (vector40.Length() > 700f)
{
                                    vector40 *= 700f / vector40.Length();
                                    vector39 = base.Center + vector40;
                                }
                            }
                            Vector2 vector41 = Main.rand.NextVector2CircularEdge(1f, 1f);
                            if (vector41.Y > 0f)
{
                                vector41 *= -1f;
                            }
                            if (Math.Abs(vector41.Y) < 0.5f)
{
                                vector41.Y = -Main.rand.NextFloat() * 0.5f - 0.5f;
                            }
                            vector41 *= vector40.Length() * 2f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector41.X, vector41.Y, num, num3, num4, i, vector39.X, vector39.Y, 0f, null);
                            return;
                        }
                        if (sItem.type == 4722)
{
                            Vector2 vector42 = Main.MouseWorld;
                            List<NPC> list2;
                            bool sparkleGuitarTarget2 = this.GetSparkleGuitarTarget(out list2);
                            if (sparkleGuitarTarget2)
{
                                NPC npc2 = list2[Main.rand.Next(list2.Count)];
                                vector42 = npc2.Center + npc2.velocity * 20f;
                            }
                            Vector2 vector43 = vector42 - base.Center;
                            Vector2 vector44 = Main.rand.NextVector2CircularEdge(1f, 1f);
                            float num104 = 1f;
                            int num105 = 1;
                            for (int num106 = 0; num106 < num105; num106++)
{
                                if (!sparkleGuitarTarget2)
{
                                    vector42 += Main.rand.NextVector2Circular(24f, 24f);
                                    if (vector43.Length() > 700f)
{
                                        vector43 *= 700f / vector43.Length();
                                        vector42 = base.Center + vector43;
                                    }
                                    float num107 = Utils.GetLerpValue(0f, 6f, this.velocity.Length(), true) * 0.8f;
                                    vector44 *= 1f - num107;
                                    vector44 += this.velocity * num107;
                                    vector44 = vector44.SafeNormalize(Vector2.UnitX);
                                }
                                float num108 = 60f;
                                float num109 = Main.rand.NextFloatDirection() * 3.1415927f * (1f / num108) * 0.5f * num104;
                                float num110 = num108 / 2f;
                                float num111 = 12f + Main.rand.NextFloat() * 2f;
                                Vector2 vector45 = vector44 * num111;
                                Vector2 vector46 = new Vector2(0f, 0f);
                                Vector2 vector47 = vector45;
                                int num112 = 0;
                                while ((float)num112 < num110)
{
                                    vector46 += vector47;
                                    vector47 = vector47.RotatedBy((double)num109, default(Vector2));
                                    num112++;
                                }
                                Vector2 vector48 = -vector46;
                                Vector2 vector49 = vector42 + vector48;
                                float lerpValue2 = Utils.GetLerpValue((float)this.itemAnimationMax, 0f, (float)this.itemAnimation, true);
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector49, vector45, num, num3, num4, i, num109, lerpValue2, 0f, null);
                            }
                            return;
                        }
                        if (sItem.type == 4607)
{
                            this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                            return;
                        }
                        if (sItem.type == 5069)
{
                            this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                            return;
                        }
                        if (sItem.type == 5114)
{
                            this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                            return;
                        }
                        if (sItem.type == 5456)
{
                            this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                            return;
                        }
                        if (sItem.type == 2188)
{
                            int num113 = 4;
                            if (Main.rand.Next(3) == 0)
{
                                num113++;
                            }
                            if (Main.rand.Next(4) == 0)
{
                                num113++;
                            }
                            if (Main.rand.Next(5) == 0)
{
                                num113++;
                            }
                            for (int num114 = 0; num114 < num113; num114++)
{
                                float num115 = num10;
                                float num116 = num11;
                                float num117 = 0.05f * (float)num114;
                                num115 += (float)Main.rand.Next(-35, 36) * num117;
                                num116 += (float)Main.rand.Next(-35, 36) * num117;
                                num12 = (float)Math.Sqrt((double)(num115 * num115 + num116 * num116));
                                num12 = num2 / num12;
                                num115 *= num12;
                                num116 *= num12;
                                float x = vector.X;
                                float y = vector.Y;
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x, y, num115, num116, num, num3, num4, i, 0f, 0f, 0f, null);
                            }
                            return;
                        }
                        if (sItem.type == 1308)
{
                            int num118 = 3;
                            if (Main.rand.Next(3) == 0)
{
                                num118++;
                            }
                            for (int num119 = 0; num119 < num118; num119++)
{
                                float num120 = num10;
                                float num121 = num11;
                                float num122 = 0.05f * (float)num119;
                                num120 += (float)Main.rand.Next(-35, 36) * num122;
                                num121 += (float)Main.rand.Next(-35, 36) * num122;
                                num12 = (float)Math.Sqrt((double)(num120 * num120 + num121 * num121));
                                num12 = num2 / num12;
                                num120 *= num12;
                                num121 *= num12;
                                float x2 = vector.X;
                                float y2 = vector.Y;
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x2, y2, num120, num121, num, num3, num4, i, 0f, 0f, 0f, null);
                            }
                            return;
                        }
                        if (sItem.type == 1258)
{
                            float num123 = num10;
                            float num124 = num11;
                            num123 += (float)Main.rand.Next(-40, 41) * 0.01f;
                            num124 += (float)Main.rand.Next(-40, 41) * 0.01f;
                            vector.X += (float)Main.rand.Next(-40, 41) * 0.05f;
                            vector.Y += (float)Main.rand.Next(-45, 36) * 0.05f;
                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num123, num124, num, num3, num4, i, 0f, 0f, 0f, null);
                            return;
                        }
                        if (sItem.type == 964)
{
                            int num125 = Main.rand.Next(3, 5);
                            for (int num126 = 0; num126 < num125; num126++)
{
                                float num127 = num10;
                                float num128 = num11;
                                num127 += (float)Main.rand.Next(-35, 36) * 0.04f;
                                num128 += (float)Main.rand.Next(-35, 36) * 0.04f;
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num127, num128, num, num3, num4, i, 0f, 0f, 0f, null);
                            }
                            return;
                        }
                        if (sItem.type == 1569)
{
                            int num129 = 4;
                            if (Main.rand.Next(2) == 0)
{
                                num129++;
                            }
                            if (Main.rand.Next(4) == 0)
{
                                num129++;
                            }
                            if (Main.rand.Next(8) == 0)
{
                                num129++;
                            }
                            if (Main.rand.Next(16) == 0)
{
                                num129++;
                            }
                            for (int num130 = 0; num130 < num129; num130++)
{
                                float num131 = num10;
                                float num132 = num11;
                                float num133 = 0.05f * (float)num130;
                                num131 += (float)Main.rand.Next(-35, 36) * num133;
                                num132 += (float)Main.rand.Next(-35, 36) * num133;
                                num12 = (float)Math.Sqrt((double)(num131 * num131 + num132 * num132));
                                num12 = num2 / num12;
                                num131 *= num12;
                                num132 *= num12;
                                float x3 = vector.X;
                                float y3 = vector.Y;
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x3, y3, num131, num132, num, num3, num4, i, 0f, 0f, 0f, null);
                            }
                            return;
                        }
                        if (sItem.type == 1572 || sItem.type == 2366 || sItem.type == 3571 || sItem.type == 3569 || sItem.type == 5119 || sItem.type == 5463)
{
                            float num134;
                            float num135;
                            this.PickSentryLandingSpot(sItem, out num134, out num135);
                            float num136 = 0f;
                            float num137 = 15f;
                            int num138 = 0;
                            num6 = sItem.type;
                            if (num6 != 1572)
{
                                if (num6 != 5119)
{
                                    if (num6 == 5463)
{
                                        num135 = (float)Main.mouseY + Main.screenPosition.Y;
                                        num137 = 0f;
                                    }
                                }
                                else
{
                                    num138 = 90;
                                }
                            }
                            else
{
                                num138 = 60;
                            }
                            int num139 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, num134, num135, num136, num137, num, num3, num4, i, (float)num138, 0f, 0f, null);
                            Main.projectile[num139].originalDamage = damage;
                            this.UpdateMaxTurrets();
                            return;
                        }
                        if (sItem.type == 5667)
{
                            bool flag7 = this.altFunctionUse == 2;
                            bool flag8 = !flag7;
                            if (this.ownedProjectileCounts[1098] > 0)
{
                                for (int num140 = 0; num140 < 1000; num140++)
{
                                    Projectile projectile2 = Main.projectile[num140];
                                    if (projectile2.active && projectile2.owner == this.whoAmI && projectile2.type == 1098)
{
                                        if (flag7)
{
                                            projectile2.Kill();
                                        }
                                        else
{
                                            flag8 = false;
                                            projectile2.netUpdate2 = true;
                                            projectile2.ai[1] = 0f;
                                            this.StopPettingAnimal();
                                            if (projectile2.Distance(base.Center) >= 1200f)
{
                                                projectile2.Kill();
                                            }
                                            else if (projectile2.ai[0] == 0f || projectile2.ai[0] == 4f || projectile2.ai[0] == 5f)
{
                                                Vector2 vector50 = Main.ReverseGravitySupport(Main.MouseScreen, 0f) + Main.screenPosition - projectile2.Center;
                                                if (Math.Abs(vector50.Y) >= Math.Abs(vector50.X))
{
                                                    projectile2.ai[0] = 1f;
                                                }
                                                else
{
                                                    projectile2.ai[0] = (float)((vector50.X >= 0f) ? 2 : 3);
                                                }
                                            }
                                            else
{
                                                int num141 = 6;
                                                if (projectile2.ai[0] == 2f)
{
                                                    projectile2.velocity.X = (float)(-(float)num141);
                                                }
                                                else if (projectile2.ai[0] == 3f)
{
                                                    projectile2.velocity.X = (float)num141;
                                                }
                                                projectile2.ai[0] = 4f;
                                            }
                                        }
                                    }
                                }
                            }
                            if (flag8)
{
                                this.SpawnDigtoiseOnCursor(i, num, projectileSource_Item_WithPotentialAmmo);
                                return;
                            }
                        }
                        else
{
                            if (sItem.type == 1244 || sItem.type == 1256)
{
                                int num142 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 0f, 0f, null);
                                Main.projectile[num142].ai[0] = (float)Main.mouseX + Main.screenPosition.X;
                                Main.projectile[num142].ai[1] = (float)Main.mouseY + Main.screenPosition.Y;
                                return;
                            }
                            if (sItem.type == 1229)
{
                                int num143 = 2;
                                if (Main.rand.Next(3) == 0)
{
                                    num143++;
                                }
                                for (int num144 = 0; num144 < num143; num144++)
{
                                    float num145 = num10;
                                    float num146 = num11;
                                    if (num144 > 0)
{
                                        num145 += (float)Main.rand.Next(-35, 36) * 0.04f;
                                        num146 += (float)Main.rand.Next(-35, 36) * 0.04f;
                                    }
                                    if (num144 > 1)
{
                                        num145 += (float)Main.rand.Next(-35, 36) * 0.04f;
                                        num146 += (float)Main.rand.Next(-35, 36) * 0.04f;
                                    }
                                    if (num144 > 2)
{
                                        num145 += (float)Main.rand.Next(-35, 36) * 0.04f;
                                        num146 += (float)Main.rand.Next(-35, 36) * 0.04f;
                                    }
                                    int num147 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num145, num146, num, num3, num4, i, 0f, 0f, 0f, null);
                                    Main.projectile[num147].noDropItem = true;
                                }
                                return;
                            }
                            if (sItem.type == 1121)
{
                                int num148 = Main.rand.Next(1, 4);
                                if (Main.rand.Next(6) == 0)
{
                                    num148++;
                                }
                                if (Main.rand.Next(6) == 0)
{
                                    num148++;
                                }
                                if (this.strongBees && Main.rand.Next(3) == 0)
{
                                    num148++;
                                }
                                for (int num149 = 0; num149 < num148; num149++)
{
                                    float num150 = num10;
                                    float num151 = num11;
                                    num150 += (float)Main.rand.Next(-35, 36) * 0.02f;
                                    num151 += (float)Main.rand.Next(-35, 36) * 0.02f;
                                    int num152 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num150, num151, this.beeType(), this.beeDamage(num3), this.beeKB(num4), i, 0f, 0f, 0f, null);
                                    Main.projectile[num152].magic = true;
                                }
                                return;
                            }
                            if (sItem.type == 1155)
{
                                int num153 = Main.rand.Next(2, 5);
                                for (int num154 = 0; num154 < num153; num154++)
{
                                    float num155 = num10;
                                    float num156 = num11;
                                    num155 += (float)Main.rand.Next(-35, 36) * 0.02f;
                                    num156 += (float)Main.rand.Next(-35, 36) * 0.02f;
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num155, num156, num, num3, num4, i, 0f, 0f, 0f, null);
                                }
                                return;
                            }
                            if (sItem.type == 1801)
{
                                int num157 = Main.rand.Next(2, 4);
                                for (int num158 = 0; num158 < num157; num158++)
{
                                    float num159 = num10;
                                    float num160 = num11;
                                    num159 += (float)Main.rand.Next(-35, 36) * 0.05f;
                                    num160 += (float)Main.rand.Next(-35, 36) * 0.05f;
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num159, num160, num, num3, num4, i, 0f, 0f, 0f, null);
                                }
                                return;
                            }
                            if (sItem.type == 679)
{
                                for (int num161 = 0; num161 < 6; num161++)
{
                                    float num162 = num10;
                                    float num163 = num11;
                                    num162 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                    num163 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num162, num163, num, num3, num4, i, 0f, 0f, 0f, null);
                                }
                                return;
                            }
                            if (sItem.type == 1156)
{
                                int num164 = 0;
                                for (int num165 = 0; num165 < 1000; num165++)
{
                                    if (Main.projectile[num165].active && Main.projectile[num165].owner == this.whoAmI && Main.projectile[num165].type == this.HeldItem.shoot)
{
                                        num164++;
                                    }
                                }
                                for (int num166 = 0; num166 < 3 - num164; num166++)
{
                                    float num167 = num10;
                                    float num168 = num11;
                                    num167 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                    num168 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num167, num168, num, num3, num4, i, 0f, 0f, 0f, null);
                                }
                                return;
                            }
                            if (sItem.type == 4682)
{
                                for (int num169 = 0; num169 < 3; num169++)
{
                                    float num170 = num10;
                                    float num171 = num11;
                                    num170 += (float)Main.rand.Next(-20, 21) * 0.1f;
                                    num171 += (float)Main.rand.Next(-20, 21) * 0.1f;
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num170, num171, num, num3, num4, i, 0f, 0f, 0f, null);
                                }
                                return;
                            }
                            if (sItem.type == 2623)
{
                                for (int num172 = 0; num172 < 3; num172++)
{
                                    float num173 = num10;
                                    float num174 = num11;
                                    num173 += (float)Main.rand.Next(-40, 41) * 0.1f;
                                    num174 += (float)Main.rand.Next(-40, 41) * 0.1f;
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num173, num174, num, num3, num4, i, 0f, 0f, 0f, null);
                                }
                                return;
                            }
                            if (sItem.type == 3210)
{
                                Vector2 vector51 = new Vector2(num10, num11);
                                vector51.X += (float)Main.rand.Next(-30, 31) * 0.04f;
                                vector51.Y += (float)Main.rand.Next(-30, 31) * 0.03f;
                                vector51.Normalize();
                                vector51 *= (float)Main.rand.Next(70, 91) * 0.1f;
                                vector51.X += (float)Main.rand.Next(-30, 31) * 0.04f;
                                vector51.Y += (float)Main.rand.Next(-30, 31) * 0.03f;
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector51.X, vector51.Y, num, num3, num4, i, (float)Main.rand.Next(20), 0f, 0f, null);
                                return;
                            }
                            if (sItem.type == 434)
{
                                float num175 = num10;
                                float num176 = num11;
                                if (this.itemAnimation < 5)
{
                                    num175 += (float)Main.rand.Next(-40, 41) * 0.01f;
                                    num176 += (float)Main.rand.Next(-40, 41) * 0.01f;
                                    num175 *= 1.1f;
                                    num176 *= 1.1f;
                                }
                                else if (this.itemAnimation < 10)
{
                                    num175 += (float)Main.rand.Next(-20, 21) * 0.01f;
                                    num176 += (float)Main.rand.Next(-20, 21) * 0.01f;
                                    num175 *= 1.05f;
                                    num176 *= 1.05f;
                                }
                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num175, num176, num, num3, num4, i, 0f, 0f, 0f, null);
                                return;
                            }
                            if (sItem.type == 1157)
{
                                num = Main.rand.Next(191, 195);
                                int num177 = this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                                Main.projectile[num177].localAI[0] = 30f;
                                return;
                            }
                            if (sItem.type == 5663)
{
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                                return;
                            }
                            if (sItem.type == 5664)
{
                                int num178 = this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                                Main.projectile[num178].localAI[0] = 30f;
                                return;
                            }
                            if (sItem.type == 1802)
{
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                                return;
                            }
                            if (sItem.type == 2364 || sItem.type == 2365)
{
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                                return;
                            }
                            if (sItem.type == 2535)
{
                                num10 = 0f;
                                num11 = 0f;
                                Vector2 vector52 = new Vector2(num10, num11);
                                vector52 = vector52.RotatedBy(1.5707963705062866, default(Vector2));
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, vector52, vector52);
                                vector52 = vector52.RotatedBy(-3.1415927410125732, default(Vector2));
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num + 1, damage, num4, vector52, vector52);
                                return;
                            }
                            if (sItem.type == 2551)
{
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num + this.nextCycledSpiderMinionType, damage, num4, default(Vector2), default(Vector2));
                                this.nextCycledSpiderMinionType++;
                                this.nextCycledSpiderMinionType %= 3;
                                return;
                            }
                            if (sItem.type == 2584)
{
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num + Main.rand.Next(3), damage, num4, default(Vector2), default(Vector2));
                                return;
                            }
                            if (sItem.type == 2621)
{
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                                return;
                            }
                            if (sItem.type == 2749 || sItem.type == 3249 || sItem.type == 3474 || sItem.type == 4273 || sItem.type == 4281)
{
                                this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                                return;
                            }
                            if (sItem.type == 3531)
{
                                int num179 = -1;
                                int num180 = -1;
                                for (int num181 = 0; num181 < 1000; num181++)
{
                                    if (Main.projectile[num181].active && Main.projectile[num181].owner == Main.myPlayer)
{
                                        if (num179 == -1 && Main.projectile[num181].type == 625)
{
                                            num179 = num181;
                                        }
                                        if (num180 == -1 && Main.projectile[num181].type == 628)
{
                                            num180 = num181;
                                        }
                                        if (num179 != -1 && num180 != -1)
{
                                            break;
                                        }
                                    }
                                }
                                if (num179 == -1 && num180 == -1)
{
                                    num10 = 0f;
                                    num11 = 0f;
                                    vector.X = (float)Main.mouseX + Main.screenPosition.X;
                                    vector.Y = (float)Main.mouseY + Main.screenPosition.Y;
                                    int num182 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 0f, 0f, null);
                                    int num183 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num + 1, num3, num4, i, (float)num182, 0f, 0f, null);
                                    int num184 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num + 2, num3, num4, i, (float)num183, 0f, 0f, null);
                                    int num185 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num + 3, num3, num4, i, (float)num184, 0f, 0f, null);
                                    Main.projectile[num183].localAI[1] = (float)num184;
                                    Main.projectile[num184].localAI[1] = (float)num185;
                                    Main.projectile[num182].originalDamage = damage;
                                    Main.projectile[num183].originalDamage = damage;
                                    Main.projectile[num184].originalDamage = damage;
                                    Main.projectile[num185].originalDamage = damage;
                                    return;
                                }
                                if (num179 != -1 && num180 != -1)
{
                                    int num186 = (int)Main.projectile[num180].ai[0];
                                    int num187 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num + 1, num3, num4, i, (float)num186, 0f, 0f, null);
                                    int num188 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num + 2, num3, num4, i, (float)num187, 0f, 0f, null);
                                    Main.projectile[num187].localAI[1] = (float)num188;
                                    Main.projectile[num187].netUpdate = true;
                                    Main.projectile[num187].ai[1] = 1f;
                                    Main.projectile[num188].localAI[1] = (float)num180;
                                    Main.projectile[num188].netUpdate = true;
                                    Main.projectile[num188].ai[1] = 1f;
                                    Main.projectile[num180].ai[0] = (float)num188;
                                    Main.projectile[num180].netUpdate = true;
                                    Main.projectile[num180].ai[1] = 1f;
                                    Main.projectile[num187].originalDamage = damage;
                                    Main.projectile[num188].originalDamage = damage;
                                    Main.projectile[num180].originalDamage = damage;
                                    return;
                                }
                            }
                            else
{
                                if (sItem.type == 1309 || sItem.type == 4758 || sItem.type == 4269 || sItem.type == 5005)
{
                                    this.SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, num, damage, num4, default(Vector2), default(Vector2));
                                    return;
                                }
                                if (sItem.shoot > 0 && (Main.projPet[sItem.shoot] || sItem.shoot == 72 || sItem.shoot == 18 || sItem.shoot == 500 || sItem.shoot == 650) && !sItem.summon)
{
                                    for (int num189 = 0; num189 < 1000; num189++)
{
                                        Projectile projectile3 = Main.projectile[num189];
                                        if (projectile3.active && projectile3.owner == this.whoAmI)
{
                                            if (sItem.shoot == 72 && (projectile3.type == 72 || projectile3.type == 86 || projectile3.type == 87))
{
                                                projectile3.Kill();
                                            }
                                            else if (sItem.type == 5131 && (projectile3.type == 881 || projectile3.type == 934))
{
                                                projectile3.Kill();
                                            }
                                            else if (sItem.shoot == projectile3.type)
{
                                                projectile3.Kill();
                                            }
                                        }
                                    }
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, 0, 0f, i, 0f, 0f, 0f, null);
                                    return;
                                }
                                if (sItem.type == 3006)
{
                                    vector = this.GetFarthestSpawnPositionOnLine(vector, num10, num11);
                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, 0f, 0f, num, num3, num4, i, 0f, 0f, 0f, null);
                                    return;
                                }
                                if (sItem.type == 3014)
{
                                    Vector2 vector53;
                                    vector53.X = Main.MouseWorld.X;
                                    vector53.Y = Main.MouseWorld.Y;
                                    this.LimitPointToPlayerReachableArea(ref vector53);
                                    while (Collision.CanHitLine(this.position, this.width, this.height, vector, 1, 1))
{
                                        vector.X += num10;
                                        vector.Y += num11;
                                        if ((vector - vector53).Length() < 20f + Math.Abs(num10) + Math.Abs(num11))
{
                                            vector = vector53;
                                            break;
                                        }
                                    }
                                    bool flag9 = false;
                                    int num190 = (int)vector.Y / 16;
                                    int num191 = (int)vector.X / 16;
                                    int num192 = num190;
                                    while (num190 < Main.maxTilesY - 10 && num190 - num192 < 30 && !WorldGen.SolidTile(num191, num190, false))
{
                                        ushort type = Main.tile[num191, num190].type;
                                        if (TileID.Sets.Platforms[(int)type] || type == 380)
{
                                            break;
                                        }
                                        num190++;
                                    }
                                    if (!WorldGen.SolidTile(num191, num190, false) && !TileID.Sets.Platforms[(int)Main.tile[num191, num190].type] && Main.tile[num191, num190].type != 380)
{
                                        flag9 = true;
                                    }
                                    float num193 = (float)(num190 * 16);
                                    num190 = num192;
                                    while (num190 > 10 && num192 - num190 < 30 && !WorldGen.SolidTile(num191, num190, false))
{
                                        num190--;
                                    }
                                    float num194 = (float)(num190 * 16 + 16);
                                    float num195 = num193 - num194;
                                    int num196 = 15;
                                    if (num195 > (float)(16 * num196))
{
                                        num195 = (float)(16 * num196);
                                    }
                                    num194 = num193 - num195;
                                    vector.X = (float)((int)(vector.X / 16f) * 16);
                                    if (!flag9)
{
                                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, 0f, 0f, num, num3, num4, i, num194, num195, 0f, null);
                                        return;
                                    }
                                }
                                else
{
                                    if (sItem.type == 3384)
{
                                        int num197 = ((this.altFunctionUse == 2) ? 1 : 0);
                                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, (float)num197, 0f, null);
                                        return;
                                    }
                                    if (sItem.type == 3473)
{
                                        float num198 = (Main.rand.NextFloat() - 0.5f) * 0.7853982f;
                                        Vector2 vector54 = new Vector2(num10, num11);
                                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector54.X, vector54.Y, num, num3, num4, i, 0f, num198, 0f, null);
                                        return;
                                    }
                                    if (sItem.type == 5688 || sItem.type == 4672 || sItem.type == 5473 || sItem.type == 5474 || sItem.type == 5475 || sItem.type == 5476 || sItem.type == 5477 || sItem.type == 5478 || sItem.type == 5479 || sItem.type == 5480 || sItem.type == 5074 || sItem.type == 4911 || sItem.type == 4912 || sItem.type == 4913 || sItem.type == 4914 || sItem.type == 4678 || sItem.type == 4679 || sItem.type == 4680)
{
                                        float num199 = 0.6f;
                                        float num200 = 0.4f;
                                        float num201 = num199 + num200 * Main.rand.NextFloat();
                                        if (sItem.type != 4680 && Main.rand.Next(3) == 0)
{
                                            num201 *= -2.5f;
                                        }
                                        float num202 = 1f;
                                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, num201 * num202, 0f, null);
                                        return;
                                    }
                                    if (sItem.type == 4956 || sItem.type == 5669)
{
                                        int num203 = (this.itemAnimationMax - this.itemAnimation) / this.itemTime;
                                        Vector2 vector55 = new Vector2(num10, num11);
                                        int num204 = 4956;
                                        if (sItem.type == 4956)
{
                                            num204 = FinalFractalHelper.GetRandomProfileIndex();
                                            if (num203 == 0)
{
                                                num204 = 4956;
                                            }
                                        }
                                        if (sItem.type == 5669)
{
                                            num204 = 3507;
                                        }
                                        Vector2 mouseWorld3 = Main.MouseWorld;
                                        this.LimitPointToPlayerReachableArea(ref mouseWorld3);
                                        Vector2 vector56 = mouseWorld3 - this.MountedCenter;
                                        if (num203 == 1 || num203 == 2)
{
                                            int num205;
                                            bool zenithTarget = this.GetZenithTarget(mouseWorld3, 400f, out num205);
                                            if (zenithTarget)
{
                                                vector56 = Main.npc[num205].Center - this.MountedCenter;
                                            }
                                            bool flag10 = num203 == 2;
                                            if (num203 == 1 && !zenithTarget)
{
                                                flag10 = true;
                                            }
                                            if (flag10)
{
                                                vector56 += Main.rand.NextVector2Circular(150f, 150f);
                                            }
                                        }
                                        vector55 = vector56 / 2f;
                                        float num206 = (float)Main.rand.Next(-100, 101);
                                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, vector55, num, num3, num4, i, num206, (float)num204, 0f, null);
                                        return;
                                    }
                                    if (sItem.type == 3836)
{
                                        float num207 = Main.rand.NextFloat() * num2 * 0.75f * (float)this.direction;
                                        Vector2 vector57 = new Vector2(num10, num11);
                                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, vector57, num, num3, num4, i, num207, 0f, 0f, null);
                                        return;
                                    }
                                    if (sItem.type == 3858)
{
                                        bool flag11 = this.altFunctionUse == 2;
                                        Vector2 vector58 = new Vector2(num10, num11);
                                        if (flag11)
{
                                            vector58 *= 1.5f;
                                            float num208 = (0.3f + 0.7f * Main.rand.NextFloat()) * num2 * 1.75f * (float)this.direction;
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, vector58, 708, (int)((float)num3 * 0.5f), num4 + 4f, i, num208, 0f, 0f, null);
                                            return;
                                        }
                                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, vector58, num, num3, num4, i, 0f, 0f, 0f, null);
                                        return;
                                    }
                                    else
{
                                        if (sItem.type == 3859)
{
                                            Vector2 vector59 = new Vector2(num10, num11);
                                            num = 710;
                                            vector59 *= 0.8f;
                                            Vector2 vector60 = vector59.SafeNormalize(-Vector2.UnitY);
                                            float num209 = 0.017453292f * (float)(-(float)this.direction);
                                            for (float num210 = -2.5f; num210 < 3f; num210 += 1f)
{
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, (vector59 + vector60 * num210 * 0.5f).RotatedBy((double)(num210 * num209), default(Vector2)), num, num3, num4, i, 0f, 0f, 0f, null);
                                            }
                                            return;
                                        }
                                        if (sItem.type == 3870)
{
                                            Vector2 vector61 = Vector2.Normalize(new Vector2(num10, num11)) * 40f * sItem.scale;
                                            if (Collision.CanHit(vector, 0, 0, vector + vector61, 0, 0))
{
                                                vector += vector61;
                                            }
                                            Vector2 vector62 = new Vector2(num10, num11);
                                            vector62 *= 0.8f;
                                            Vector2 vector63 = vector62.SafeNormalize(-Vector2.UnitY);
                                            float num211 = 0.017453292f * (float)(-(float)this.direction);
                                            for (int num212 = 0; num212 <= 2; num212++)
{
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, (vector62 + vector63 * (float)num212 * 1f).RotatedBy((double)((float)num212 * num211), default(Vector2)), num, num3, num4, i, 0f, 0f, 0f, null);
                                            }
                                            return;
                                        }
                                        if (sItem.type == 3542)
{
                                            float num213 = (Main.rand.NextFloat() - 0.5f) * 0.7853982f * 0.7f;
                                            int num214 = 0;
                                            while (num214 < 10 && !Collision.CanHit(vector, 0, 0, vector + new Vector2(num10, num11).RotatedBy((double)num213, default(Vector2)) * 100f, 0, 0))
{
                                                num213 = (Main.rand.NextFloat() - 0.5f) * 0.7853982f * 0.7f;
                                                num214++;
                                            }
                                            Vector2 vector64 = new Vector2(num10, num11).RotatedBy((double)num213, default(Vector2)) * (0.95f + Main.rand.NextFloat() * 0.3f);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector64.X, vector64.Y, num, num3, num4, i, 0f, 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 3779)
{
                                            float num215 = Main.rand.NextFloat() * 6.2831855f;
                                            int num216 = 0;
                                            while (num216 < 10 && !Collision.CanHit(vector, 0, 0, vector + new Vector2(num10, num11).RotatedBy((double)num215, default(Vector2)) * 100f, 0, 0))
{
                                                num215 = Main.rand.NextFloat() * 6.2831855f;
                                                num216++;
                                            }
                                            Vector2 vector65 = new Vector2(num10, num11).RotatedBy((double)num215, default(Vector2)) * (0.95f + Main.rand.NextFloat() * 0.3f);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector + vector65 * 30f, Vector2.Zero, num, num3, num4, i, -2f, 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 3787)
{
                                            float num217 = Main.rand.NextFloat() * 6.2831855f;
                                            float num218 = 20f;
                                            float num219 = 60f;
                                            Vector2 vector66 = vector + num217.ToRotationVector2() * MathHelper.Lerp(num218, num219, Main.rand.NextFloat());
                                            for (int num220 = 0; num220 < 50; num220++)
{
                                                vector66 = vector + num217.ToRotationVector2() * MathHelper.Lerp(num218, num219, Main.rand.NextFloat());
                                                if (Collision.CanHit(vector, 0, 0, vector66 + (vector66 - vector).SafeNormalize(Vector2.UnitX) * 8f, 0, 0))
{
                                                    break;
                                                }
                                                num217 = Main.rand.NextFloat() * 6.2831855f;
                                            }
                                            Vector2 vector67 = Main.MouseWorld - vector66;
                                            Vector2 vector68 = new Vector2(num10, num11).SafeNormalize(Vector2.UnitY) * num2;
                                            vector67 = vector67.SafeNormalize(vector68) * num2;
                                            vector67 = Vector2.Lerp(vector67, vector68, 0.25f);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector66, vector67, num, num3, num4, i, 0f, 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 3788)
{
                                            Vector2 vector69 = new Vector2(num10, num11);
                                            float num221 = 0.7853982f;
                                            for (int num222 = 0; num222 < 2; num222++)
{
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, vector69 + vector69.SafeNormalize(Vector2.Zero).RotatedBy((double)(num221 * (Main.rand.NextFloat() * 0.5f + 0.5f)), default(Vector2)) * Main.rand.NextFloatDirection() * 2f, num, num3, num4, i, 0f, 0f, 0f, null);
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, vector69 + vector69.SafeNormalize(Vector2.Zero).RotatedBy((double)(-(double)num221 * (Main.rand.NextFloat() * 0.5f + 0.5f)), default(Vector2)) * Main.rand.NextFloatDirection() * 2f, num, num3, num4, i, 0f, 0f, 0f, null);
                                            }
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, vector69.SafeNormalize(Vector2.UnitX * (float)this.direction) * (num2 * 1.3f), 661, num3 * 2, num4, i, 0f, 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 4463 || sItem.type == 486)
{
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, new Vector2(num10, num11), num, num3, num4, i, 0f, 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 46)
{
                                            Vector2 vector70 = new Vector2((float)this.direction, this.gravDir * 4f).SafeNormalize(Vector2.UnitY).RotatedBy((double)(6.2831855f * Main.rand.NextFloatDirection() * 0.05f), default(Vector2));
                                            Vector2 vector71 = this.MountedCenter + new Vector2(70f, -40f) * this.Directions + vector70 * -10f;
                                            int num223;
                                            if (this.GetZenithTarget(vector71, 50f, out num223))
{
                                                NPC npc3 = Main.npc[num223];
                                                vector71 = npc3.Center + Main.rand.NextVector2Circular((float)(npc3.width / 2), (float)(npc3.height / 2));
                                            }
                                            else
{
                                                vector71 += Main.rand.NextVector2Circular(20f, 20f);
                                            }
                                            float num224 = 1f;
                                            if (Main.rand.Next(100) < this.meleeCrit)
{
                                                num224 = 2f;
                                                num3 *= 2;
                                            }
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector71, vector70 * 0.001f, num, (int)((double)num3 * 0.5), num4, i, num224, 0f, 0f, null);
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 273)
{
                                            float adjustedItemScale = this.GetAdjustedItemScale(sItem);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2((float)this.direction, 0f), num, num3, num4, i, (float)this.direction * this.gravDir, (float)this.itemAnimationMax, adjustedItemScale, null);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2(num10, num11), num, num3, num4, i, (float)this.direction * this.gravDir * 0.1f, 30f, adjustedItemScale, null);
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 5462)
{
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 0f, 0f, null);
                                            this.itemAnimation = sItem.useAnimation - 10;
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 368)
{
                                            float adjustedItemScale2 = this.GetAdjustedItemScale(sItem);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2((float)this.direction, 0f), num, num3, num4, i, (float)this.direction * this.gravDir, (float)this.itemAnimationMax, adjustedItemScale2, null);
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 1826)
{
                                            float adjustedItemScale3 = this.GetAdjustedItemScale(sItem);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2((float)this.direction, 0f), num, num3, num4, i, (float)this.direction * this.gravDir, (float)this.itemAnimationMax, adjustedItemScale3, null);
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 675)
{
                                            float adjustedItemScale4 = this.GetAdjustedItemScale(sItem);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2((float)this.direction, 0f), 972, num3, num4, i, (float)this.direction * this.gravDir, (float)this.itemAnimationMax, adjustedItemScale4, null);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2(num10, num11), num, num3 / 2, num4, i, (float)this.direction * this.gravDir, 32f, adjustedItemScale4, null);
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 674)
{
                                            float adjustedItemScale5 = this.GetAdjustedItemScale(sItem);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2((float)this.direction, 0f), num, num3, num4, i, (float)this.direction * this.gravDir, (float)this.itemAnimationMax, adjustedItemScale5, null);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2((float)this.direction, 0f), 982, 0, num4, i, (float)this.direction * this.gravDir, (float)this.itemAnimationMax, adjustedItemScale5, null);
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 757)
{
                                            float adjustedItemScale6 = this.GetAdjustedItemScale(sItem);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2((float)this.direction, 0f), 984, num3, num4, i, (float)this.direction * this.gravDir, (float)this.itemAnimationMax, adjustedItemScale6, null);
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, this.MountedCenter, new Vector2(num10, num11) * 5f, num, num3, num4, i, (float)this.direction * this.gravDir, 18f, adjustedItemScale6, null);
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 190)
{
                                            Vector2 vector72 = this.MountedCenter + new Vector2(70f, -40f) * this.Directions;
                                            int num225;
                                            bool zenithTarget2 = this.GetZenithTarget(vector72, 150f, out num225);
                                            if (zenithTarget2)
{
                                                NPC npc4 = Main.npc[num225];
                                                vector72 = Main.rand.NextVector2FromRectangle(npc4.Hitbox);
                                            }
                                            else
{
                                                vector72 += Main.rand.NextVector2Circular(20f, 20f);
                                            }
                                            Vector2 vector73 = base.Center + new Vector2(Main.rand.NextFloatDirection() * (float)this.width / 2f, (float)(this.height / 2)) * this.Directions;
                                            Vector2 vector74 = vector72 - vector73;
                                            float num226 = (3.1415927f + 6.2831855f * Main.rand.NextFloat() * 1.5f) * ((float)(-(float)this.direction) * this.gravDir);
                                            int num227 = 60;
                                            float num228 = num226 / (float)num227;
                                            float num229 = 16f;
                                            float num230 = vector74.Length();
                                            if (Math.Abs(num228) >= 0.17f)
{
                                                num228 *= 0.7f;
                                            }
                                            int direction = this.direction;
                                            float num231 = this.gravDir;
                                            Vector2 vector75 = Vector2.UnitX * num229;
                                            Vector2 vector76 = vector75;
                                            int num232 = 0;
                                            while (vector76.Length() < num230 && num232 < num227)
{
                                                num232++;
                                                vector76 += vector75;
                                                vector75 = vector75.RotatedBy((double)num228, default(Vector2));
                                            }
                                            float num233 = vector76.ToRotation();
                                            Vector2 vector77 = vector74.SafeNormalize(Vector2.UnitY).RotatedBy((double)(-(double)num233 - num228), default(Vector2)) * num229;
                                            if (num232 == num227)
{
                                                vector77 = new Vector2((float)this.direction, 0f) * num229;
                                            }
                                            if (!zenithTarget2)
{
                                                vector73.Y -= this.gravDir * 24f;
                                                vector77 = vector77.RotatedBy((double)((float)this.direction * this.gravDir * 6.2831855f * 0.14f), default(Vector2));
                                            }
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector73, vector77, num, (int)((double)num3 * 0.25), num4, i, num228, (float)num232, 0f, null);
                                            NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            return;
                                        }
                                        if (sItem.type == 3475)
{
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, 615, num3, num4, i, (float)(5 * Main.rand.Next(0, 20)), 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 3930)
{
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, 714, num3, num4, i, (float)(5 * Main.rand.Next(0, 20)), 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 3540)
{
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, 630, num3, num4, i, 0f, 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 5451 || sItem.type == 5738)
{
                                            for (int num234 = 0; num234 < 1000; num234++)
{
                                                Projectile projectile4 = Main.projectile[num234];
                                                if (projectile4.type == num && projectile4.owner == this.whoAmI)
{
                                                    projectile4.Kill();
                                                }
                                            }
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 3854)
{
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, 705, num3, num4, i, 0f, 0f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 3546)
{
                                            for (int num235 = 0; num235 < 2; num235++)
{
                                                float num236 = num10;
                                                float num237 = num11;
                                                num236 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                                num237 += (float)Main.rand.Next(-40, 41) * 0.05f;
                                                Vector2 vector78 = vector + Vector2.Normalize(new Vector2(num236, num237).RotatedBy((double)(-1.5707964f * (float)this.direction), default(Vector2))) * 6f;
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector78.X, vector78.Y, num236, num237, 167 + Main.rand.Next(4), num3, num4, i, 0f, 1f, 0f, null);
                                            }
                                            return;
                                        }
                                        if (sItem.type == 3350)
{
                                            float num238 = num10;
                                            float num239 = num11;
                                            num238 += (float)Main.rand.Next(-1, 2) * 0.5f;
                                            num239 += (float)Main.rand.Next(-1, 2) * 0.5f;
                                            if (Collision.CanHitLine(base.Center, 0, 0, vector + new Vector2(num238, num239) * 2f, 0, 0))
{
                                                vector += new Vector2(num238, num239);
                                            }
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y - this.gravDir * 4f, num238, num239, num, num3, num4, i, 0f, (float)Main.rand.Next(12) / 6f, 0f, null);
                                            return;
                                        }
                                        if (sItem.type == 3852)
{
                                            if (this.altFunctionUse == 2)
{
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, base.Bottom.Y - 100f, (float)this.direction * num2, 0f, 704, (int)((float)num3 * 1.75f), num4, i, 0f, 0f, 0f, null);
                                                return;
                                            }
                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 0f, 0f, null);
                                            return;
                                        }
                                        else
{
                                            if (sItem.type == 3818 || sItem.type == 3819 || sItem.type == 3820 || sItem.type == 3824 || sItem.type == 3825 || sItem.type == 3826 || sItem.type == 3829 || sItem.type == 3830 || sItem.type == 3831 || sItem.type == 3832 || sItem.type == 3833 || sItem.type == 3834)
{
                                                this.PayDD2CrystalsBeforeUse(sItem);
                                                int num240;
                                                int num241;
                                                int num242;
                                                this.FindSentryRestingSpot(sItem.shoot, out num240, out num241, out num242);
                                                int num243 = 0;
                                                int num244 = 0;
                                                int num245 = 0;
                                                switch (sItem.type)
{
                                                case 3818:
                                                    num243 = 1;
                                                    num244 = 80;
                                                    break;
                                                case 3819:
                                                    num243 = 1;
                                                    num244 = 70;
                                                    break;
                                                case 3820:
                                                    num243 = 1;
                                                    num244 = 60;
                                                    break;
                                                case 3824:
                                                case 3825:
                                                case 3826:
                                                    num243 = 1;
                                                    num244 = Projectile.GetBallistraShotDelay(this);
                                                    break;
                                                case 3832:
                                                case 3833:
                                                case 3834:
                                                    num245 = Projectile.GetExplosiveTrapCooldown(this);
                                                    break;
                                                }
                                                int num246 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, (float)num240, (float)(num241 - num242), 0f, 0f, num, num3, num4, i, (float)num243, (float)num244, 0f, null);
                                                Main.projectile[num246].originalDamage = damage;
                                                Main.projectile[num246].localAI[0] = (float)num245;
                                                this.UpdateMaxTurrets();
                                                return;
                                            }
                                            if (sItem.type == 65)
{
                                                Vector2 vector79 = new Vector2(num10, num11);
                                                new Vector2(100f, 0f);
                                                Vector2 mouseWorld4 = Main.MouseWorld;
                                                Vector2 vector80 = mouseWorld4;
                                                Vector2 vector81 = (vector - mouseWorld4).SafeNormalize(new Vector2(0f, -1f));
                                                while (vector80.Y > vector.Y && WorldGen.SolidTile(vector80.ToTileCoordinates()))
{
                                                    vector80 += vector81 * 16f;
                                                }
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector, vector79, num, num3, num4, i, 0f, vector80.Y, 0f, null);
                                                return;
                                            }
                                            if (sItem.type == 4923)
{
                                                float adjustedItemScale7 = this.GetAdjustedItemScale(sItem);
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, adjustedItemScale7, 0f, null);
                                                return;
                                            }
                                            if (sItem.type == 1910)
{
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 1f, 0f, 0f, null);
                                                return;
                                            }
                                            if (sItem.type == 5134)
{
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 1f, 0f, null);
                                                return;
                                            }
                                            if (sItem.type == 5495)
{
                                                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, 0f, 1f, 0f, null);
                                                return;
                                            }
                                            if (sItem.type == 5461)
{
                                                if (this.killingCardFireType == 3)
{
                                                    bool flag12 = true;
                                                    for (int num247 = 0; num247 < 1000; num247++)
{
                                                        Projectile projectile5 = Main.projectile[num247];
                                                        if (projectile5.type == num && projectile5.owner == this.whoAmI && projectile5.ai[0] != 2f)
{
                                                            flag12 = false;
                                                            break;
                                                        }
                                                    }
                                                    if (flag12)
{
                                                        this.killingCardFireType = 0;
                                                    }
                                                }
                                                switch (this.killingCardFireType)
{
                                                default:
{
                                                    float num248 = 1f;
                                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, (int)((float)num3 * num248), num4, i, 0f, 0f, (float)(Main.rand.Next(2) * 2 - 1) * 0.4f, null);
                                                    break;
                                                }
                                                case 1:
{
                                                    float num248 = 1f;
                                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, (int)((float)num3 * num248), num4, i, 0f, 0f, (float)(Main.rand.Next(2) * 2 - 1) * 0.4f, null);
                                                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10 * -1f, num11 * -1f, num, (int)((float)num3 * num248), num4, i, 0f, 0f, (float)(Main.rand.Next(2) * 2 - 1) * 0.4f, null);
                                                    break;
                                                }
                                                case 2:
{
                                                    float num248 = 1f;
                                                    float num249 = 0.7853982f;
                                                    float num250 = 6f;
                                                    float num251 = num250 - 1f;
                                                    float num252 = num249 / num251;
                                                    int num253 = -1;
                                                    int num254 = 0;
                                                    while ((float)num254 < num250)
{
                                                        Vector2 vector82 = new Vector2(num10, num11).RotatedBy((double)(num252 * (-(double)num251 * 0.5f + (float)num254)), default(Vector2));
                                                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, vector82.X, vector82.Y, num, (int)((float)num3 * num248), num4, i, 0f, 0f, (float)num253 * 0.4f, null);
                                                        if (Main.rand.Next(2) == 0)
{
                                                            num253 *= -1;
                                                        }
                                                        num254++;
                                                    }
                                                    break;
                                                }
                                                case 3:
{
                                                    for (int num255 = 0; num255 < 1000; num255++)
{
                                                        Projectile projectile6 = Main.projectile[num255];
                                                        if (projectile6.type == num && projectile6.owner == this.whoAmI)
{
                                                            projectile6.velocity = Vector2.Zero;
                                                            projectile6.ai[0] = 2f;
                                                            projectile6.netUpdate = true;
                                                            projectile6.ResetLocalNPCHitImmunity();
                                                            projectile6.Damage();
                                                        }
                                                    }
                                                    break;
                                                }
                                                }
                                                this.killingCardFireType++;
                                                if (this.killingCardFireType < 0 || this.killingCardFireType > 3)
{
                                                    this.killingCardFireType = 0;
                                                    return;
                                                }
                                            }
                                            else
{
                                                float num256 = 0f;
                                                float num257 = 0f;
                                                float num258 = 0f;
                                                if (num == 88)
{
                                                    num256 = (float)Main.rand.Next(3, 6);
                                                }
                                                if (num == 80)
{
                                                    num256 = (float)Player.tileTargetX;
                                                    num257 = (float)Player.tileTargetY;
                                                }
                                                if (num == 442)
{
                                                    num256 = (float)Player.tileTargetX;
                                                    num257 = (float)Player.tileTargetY;
                                                }
                                                if (num == 826)
{
                                                    num257 = (float)Main.rand.Next(3);
                                                }
                                                if (sItem.type == 949)
{
                                                    num257 = 1f;
                                                }
                                                if (sItem.type == 3772 || sItem.type == 3352)
{
                                                    num256 = (float)Main.rand.Next(-5, 1);
                                                }
                                                if (sItem.type == 2880)
{
                                                    num256 = -1f;
                                                }
                                                if (num == 22)
{
                                                    num258 = (float)Main.rand.Next(0, 20000);
                                                }
                                                if (num == 26 || num == 35)
{
                                                    for (int num259 = 0; num259 < 50; num259++)
{
                                                        Item item = this.inventory[num259];
                                                        if (!item.IsAir && item.shoot != num && (item.shoot == 26 || item.shoot == 35))
{
                                                            num258 = 1f;
                                                            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, -num10, -num11, item.shoot, this.GetWeaponDamage(item), this.GetWeaponKnockback(item, item.knockBack), i, num256, num257, num258, null);
                                                            break;
                                                        }
                                                    }
                                                }
                                                int num260 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector.X, vector.Y, num10, num11, num, num3, num4, i, num256, num257, num258, null);
                                                if (sItem.type == 726)
{
                                                    Main.projectile[num260].magic = true;
                                                }
                                                if (sItem.type == 724 || sItem.type == 676)
{
                                                    Main.projectile[num260].melee = true;
                                                }
                                                if (sItem.type == 760)
{
                                                    this.DestroyOldestProximityMinesOverMinesCap(20);
                                                }
                                                if (Main.projectile[num260].aiStyle == 99)
{
                                                    AchievementsHelper.HandleSpecialEvent(this, 7);
                                                }
                                                if (Main.projectile[num260].aiStyle == 160 && Main.IsItAHappyWindyDay)
{
                                                    AchievementsHelper.HandleSpecialEvent(this, 17);
                                                }
                                                if (ItemID.Sets.ShootsOnUseRelease[sItem.type])
{
                                                    this.SetItemTime(this.itemAnimation);
                                                    this.itemAnimation = 0;
                                                }
                                                NetMessage.SendData(13, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Projectile.active, Terraria.Tile.active(), Terraria.Projectile.ai, Terraria.Projectile.aiStyle, System.Math.Atan2(), Terraria.Main.Camera, Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.WorldBuilding.Searches.Chain(), System.Collections.Generic.List< T >.Count, Terraria.Item.damage, Terraria.Projectile.Damage(), Terraria.Entity.Distance(), Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Vector2.Dot(), Terraria.WorldBuilding.WorldUtils.Find(), Terraria.Item.fishingPole, Terraria.Projectile.GetBallistraShotDelay(), Terraria.Projectile.GetExplosiveTrapCooldown(), Terraria.Utils.GetLerpValue(), Terraria.Graphics.FinalFractalHelper.GetRandomProfileIndex(), Terraria.ID.ItemID.Sets.gunProj, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Entity.height, Terraria.Entity.Hitbox, int, Terraria.Item.IsACoin, Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.ID.ProjectileID.Sets.IsAPhaseblade, Terraria.Main.IsItAHappyWindyDay, System.item, Terraria.Projectile.Kill(), Terraria.Item.knockBack, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), System.list, Terraria.Projectile.localAI, Terraria.Projectile.magic, Terraria.Main.maxTilesY, Terraria.Item.melee, Terraria.Projectile.melee, Terraria.Main.MouseScreen, Terraria.Main.MouseWorld, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Tile.nactive(), Terraria.Projectile.netUpdate, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Projectile.noDropItem, Terraria.ID.ProjectileID.Sets.NoMeleeSpeedVelocityScaling, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.Projectile.originalDamage, Terraria.Projectile.owner, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.projectile, Terraria.Main.projFrames, Terraria.Main.projPet, Terraria.Main.rand, Terraria.Projectile.ResetLocalNPCHitImmunity(), Terraria.Main.ReverseGravitySupport(), Terraria.Item.scale, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.NetMessage.SendData(), Terraria.Item.shoot, Terraria.ID.ItemID.Sets.ShootsOnUseRelease, Terraria.Item.shootSpeed, Terraria.Graphics.Camera.SmallerScaledAxis, Terraria.WorldGen.SolidTile(), System.Math.Sqrt(), Terraria.Item.summon, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Item.type, Terraria.Projectile.type, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Item.useAmmo, Terraria.Item.useStyle, Terraria.Item.useTime, Terraria.Entity.width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.