Terraria Decompiled: Terraria.Player.FillAmmo
FillAmmo()
Item Terraria.Player.FillAmmo (Item newItem, GetItemSettings settings) inline
Definition at line 38102 of file Player.cs.
        {
            for (int i = 54; i < 58; i++)
            {
                if (this.inventory[i].type > 0 && this.inventory[i].stack < this.inventory[i].maxStack && Item.CanStack(newItem, this.inventory[i]))
                {
                    if (!settings.NoSound)
                    {
                        SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    }
                    if (newItem.stack + this.inventory[i].stack <= this.inventory[i].maxStack)
                    {
                        this.inventory[i].stack += newItem.stack;
                        Player.GetItemLogger.Add(this.inventory, i, 2, newItem.stack);
                        if (!settings.NoText)
{
                            PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, base.Center, newItem.stack, false, false);
                        }
                        if (!settings.NoCoinMerge)
{
                            this.DoCoins(i);
                        }
                        settings.HandlePostAction(this.inventory[i]);
                        return new Item();
                    }
                    int num = this.inventory[i].maxStack - this.inventory[i].stack;
                    newItem.stack -= num;
                    Player.GetItemLogger.Add(this.inventory, i, 2, num);
                    if (!settings.NoText)
                    {
                        PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, base.Center, this.inventory[i].maxStack - this.inventory[i].stack, false, false);
                    }
                    this.inventory[i].stack = this.inventory[i].maxStack;
                    if (!settings.NoCoinMerge)
                    {
                        this.DoCoins(i);
                    }
                    settings.HandlePostAction(this.inventory[i]);
                }
            }
            if (newItem.CanFillEmptyAmmoSlot())
            {
                for (int j = 54; j < 58; j++)
                {
                    if (this.inventory[j].type == 0)
                    {
                        this.inventory[j] = newItem;
                        Player.GetItemLogger.Add(this.inventory, j, 2, newItem.stack);
                        if (!settings.NoText)
{
                            PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, base.Center, newItem.stack, false, false);
                        }
                        if (!settings.NoCoinMerge)
{
                            this.DoCoins(j);
                        }
                        SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                        settings.HandlePostAction(this.inventory[j]);
                        return new Item();
                    }
                }
            }
            return newItem;
        }
References Terraria.DataStructures.PlayerGetItemLogger.Add(), Terraria.Item.CanFillEmptyAmmoSlot(), Terraria.Item.CanStack(), Terraria.Player.GetItemLogger, Terraria.GetItemSettings.HandlePostAction(), Terraria.Item.maxStack, Terraria.PopupText.NewText(), Terraria.GetItemSettings.NoCoinMerge, Terraria.GetItemSettings.NoSound, Terraria.GetItemSettings.NoText, Terraria.Audio.SoundEngine.PlaySound(), System.stack, and Terraria.Item.stack.