Terraria Decompiled: Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile
ItemCheck_UseMiningTools_TryPoundingTile()
void Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile (Item sItem, int tileHitId, ref bool hitWall, int x, int y) inline private
Definition at line 45255 of file Player.cs.
        {
            if (!this.poundRelease)
            {
                return;
            }
            Tile tile = Main.tile[x, y];
            if (sItem.hammer <= 0 || !tile.active())
            {
                this.poundRelease = false;
                return;
            }
            if (!this.IsTilePoundable(tile))
            {
                this.poundRelease = false;
                return;
            }
            hitWall = false;
            this.ApplyItemTime(sItem);
            int num = 100;
            if (WorldGen.IsLockedDoor(x, y - 1) || WorldGen.IsLockedDoor(x, y + 1))
            {
                num = 0;
            }
            if (this.hitTile.AddDamage(tileHitId, num, true) < 100)
            {
                WorldGen.KillTile(x, y, true, true, false);
                SoundEngine.PlaySound(0, x * 16, y * 16, 1, 1f, 0f);
                return;
            }
            this.ClearMiningCacheAt(x, y, 1);
            if (!this.poundRelease)
            {
                return;
            }
            if (Main.tile[x, y].type == 470)
            {
                TEDisplayDoll.TryChangePose(x, y);
            }
            else if (TileID.Sets.Platforms[(int)Main.tile[x, y].type])
            {
                if (tile.halfBrick())
                {
                    WorldGen.PoundTile(x, y);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 7, (float)x, (float)y, 1f, 0, 0, 0);
                    }
                }
                else
                {
                    int num2 = 1;
                    int num3 = 2;
                    if (TileID.Sets.Platforms[(int)Main.tile[x + 1, y - 1].type] || TileID.Sets.Platforms[(int)Main.tile[x - 1, y + 1].type] || (WorldGen.SolidTile(x + 1, y, false) && !WorldGen.SolidTile(x - 1, y, false)))
                    {
                        num2 = 2;
                        num3 = 1;
                    }
                    if (Main.tile[x, y].slope() == 0)
                    {
                        WorldGen.SlopeTile(x, y, num2, false, true);
                        int num4 = (int)Main.tile[x, y].slope();
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 14, (float)x, (float)y, (float)num4, 0, 0, 0);
                        }
                    }
                    else if ((int)Main.tile[x, y].slope() == num2)
                    {
                        WorldGen.SlopeTile(x, y, num3, false, true);
                        int num5 = (int)Main.tile[x, y].slope();
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 14, (float)x, (float)y, (float)num5, 0, 0, 0);
                        }
                    }
                    else if (WorldGen.CanPoundTile(x, y))
                    {
                        Main.tile[x, y].slope(0);
                        WorldGen.PoundTile(x, y);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 23, (float)x, (float)y, 0f, 0, 0, 0);
                        }
                    }
                }
            }
            else if (Main.tile[x, y].type == 314)
            {
                if (Minecart.FrameTrack(x, y, true, false) && Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 15, (float)x, (float)y, 1f, 0, 0, 0);
                }
            }
            else if (Main.tile[x, y].type == 137)
            {
                int num6 = 0;
                switch (Main.tile[x, y].frameY / 18)
                {
                case 0:
                case 1:
                case 2:
                case 5:
                    switch (Main.tile[x, y].frameX / 18)
                    {
                    case 0:
                        num6 = 2;
                        break;
                    case 1:
                        num6 = 3;
                        break;
                    case 2:
                        num6 = 4;
                        break;
                    case 3:
                        num6 = 5;
                        break;
                    case 4:
                        num6 = 1;
                        break;
                    case 5:
                        num6 = 0;
                        break;
                    }
                    break;
                case 3:
                case 4:
                    switch (Main.tile[x, y].frameX / 18)
                    {
                    case 0:
                    case 1:
                        num6 = 3;
                        break;
                    case 2:
                        num6 = 4;
                        break;
                    case 3:
                        num6 = 2;
                        break;
                    case 4:
                        num6 = 0;
                        break;
                    }
                    break;
                }
                Main.tile[x, y].frameX = (short)(num6 * 18);
                if (Main.netMode == 1)
                {
                    NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                }
            }
            else if (Main.tile[x, y].type == 424)
            {
                if (Main.tile[x, y].frameX == 0)
                {
                    Main.tile[x, y].frameX = 18;
                }
                else if (Main.tile[x, y].frameX == 18)
                {
                    Main.tile[x, y].frameX = 36;
                }
                else
                {
                    Main.tile[x, y].frameX = 0;
                }
                if (Main.netMode == 1)
                {
                    NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                }
            }
            else if (Main.tile[x, y].type == 442)
            {
                Tile tile2 = Main.tile[x, y - 1];
                Tile tile3 = Main.tile[x, y + 1];
                Tile tile4 = Main.tile[x - 1, y];
                Tile tile5 = Main.tile[x + 1, y];
                Tile tile6 = Main.tile[x - 1, y + 1];
                Tile tile7 = Main.tile[x + 1, y + 1];
                Tile tile8 = Main.tile[x - 1, y - 1];
                Tile tile9 = Main.tile[x + 1, y - 1];
                int num7 = -1;
                int num8 = -1;
                int num9 = -1;
                int num10 = -1;
                int num11 = -1;
                int num12 = -1;
                int num13 = -1;
                int num14 = -1;
                if (tile2 != null && tile2.nactive() && !tile2.bottomSlope())
                {
                    num8 = (int)tile2.type;
                }
                if (tile3 != null && tile3.nactive() && !tile3.halfBrick() && !tile3.topSlope())
                {
                    num7 = (int)tile3.type;
                }
                if (tile4 != null && tile4.nactive() && (tile4.slope() == 0 || tile4.slope() % 2 != 1))
                {
                    num9 = (int)tile4.type;
                }
                if (tile5 != null && tile5.nactive() && (tile5.slope() == 0 || tile5.slope() % 2 != 0))
                {
                    num10 = (int)tile5.type;
                }
                if (tile6 != null && tile6.nactive())
                {
                    num11 = (int)tile6.type;
                }
                if (tile7 != null && tile7.nactive())
                {
                    num12 = (int)tile7.type;
                }
                if (tile8 != null && tile8.nactive())
                {
                    num13 = (int)tile8.type;
                }
                if (tile9 != null && tile9.nactive())
                {
                    num14 = (int)tile9.type;
                }
                bool flag = false;
                bool flag2 = false;
                bool flag3 = false;
                bool flag4 = false;
                if (num7 >= 0 && Main.tileSolid[num7] && (!Main.tileNoAttach[num7] || TileID.Sets.Platforms[num7]) && (tile3.bottomSlope() || tile3.slope() == 0) && !tile3.halfBrick())
                {
                    flag4 = true;
                }
                if (num8 >= 0 && Main.tileSolid[num8] && (!Main.tileNoAttach[num8] || (TileID.Sets.Platforms[num8] && tile2.halfBrick())) && (tile2.topSlope() || tile2.slope() == 0 || tile2.halfBrick()))
                {
                    flag = true;
                }
                if ((num9 >= 0 && Main.tileSolid[num9] && !Main.tileNoAttach[num9] && (tile4.leftSlope() || tile4.slope() == 0) && !tile4.halfBrick()) || (num9 >= 0 && TileID.Sets.IsBeam[num9]) || (WorldGen.IsTreeType(num9) && WorldGen.IsTreeType(num13) && WorldGen.IsTreeType(num11)))
                {
                    flag2 = true;
                }
                if ((num10 >= 0 && Main.tileSolid[num10] && !Main.tileNoAttach[num10] && (tile5.rightSlope() || tile5.slope() == 0) && !tile5.halfBrick()) || (num10 >= 0 && TileID.Sets.IsBeam[num10]) || (WorldGen.IsTreeType(num10) && WorldGen.IsTreeType(num14) && WorldGen.IsTreeType(num12)))
                {
                    flag3 = true;
                }
                int num15 = (int)(Main.tile[x, y].frameX / 22);
                short num16 = -2;
                switch (num15)
                {
                case 0:
                    if (flag2)
                    {
                        num16 = 2;
                    }
                    else if (flag)
                    {
                        num16 = 1;
                    }
                    else if (flag3)
                    {
                        num16 = 3;
                    }
                    else
                    {
                        num16 = -1;
                    }
                    break;
                case 1:
                    if (flag3)
                    {
                        num16 = 3;
                    }
                    else if (flag4)
                    {
                        num16 = 0;
                    }
                    else if (flag2)
                    {
                        num16 = 2;
                    }
                    else
                    {
                        num16 = -1;
                    }
                    break;
                case 2:
                    if (flag)
                    {
                        num16 = 1;
                    }
                    else if (flag3)
                    {
                        num16 = 3;
                    }
                    else if (flag4)
                    {
                        num16 = 0;
                    }
                    else
                    {
                        num16 = -1;
                    }
                    break;
                case 3:
                    if (flag4)
                    {
                        num16 = 0;
                    }
                    else if (flag2)
                    {
                        num16 = 2;
                    }
                    else if (flag)
                    {
                        num16 = 1;
                    }
                    else
                    {
                        num16 = -1;
                    }
                    break;
                }
                if (num16 != -1)
                {
                    if (num16 == -2)
                    {
                        num16 = 0;
                    }
                    Main.tile[x, y].frameX = 22 * num16;
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                    }
                }
            }
            else if ((Main.tile[x, y].halfBrick() || Main.tile[x, y].slope() != 0) && !Main.tileSolidTop[(int)Main.tile[x, y].type])
            {
                int num17 = 1;
                int num18 = 1;
                int num19 = 2;
                if ((WorldGen.SolidTile(x + 1, y, false) || Main.tile[x + 1, y].slope() == 1 || Main.tile[x + 1, y].slope() == 3) && !WorldGen.SolidTile(x - 1, y, false))
                {
                    num18 = 2;
                    num19 = 1;
                }
                if (WorldGen.SolidTile(x, y - 1, false) && !WorldGen.SolidTile(x, y + 1, false))
                {
                    num17 = -1;
                }
                if (num17 == 1)
                {
                    if (Main.tile[x, y].slope() == 0)
                    {
                        WorldGen.SlopeTile(x, y, num18, false, true);
                    }
                    else if ((int)Main.tile[x, y].slope() == num18)
                    {
                        WorldGen.SlopeTile(x, y, num19, false, true);
                    }
                    else if ((int)Main.tile[x, y].slope() == num19)
                    {
                        WorldGen.SlopeTile(x, y, num18 + 2, false, true);
                    }
                    else if ((int)Main.tile[x, y].slope() == num18 + 2)
                    {
                        WorldGen.SlopeTile(x, y, num19 + 2, false, true);
                    }
                    else
                    {
                        WorldGen.SlopeTile(x, y, 0, false, true);
                    }
                }
                else if (Main.tile[x, y].slope() == 0)
                {
                    WorldGen.SlopeTile(x, y, num18 + 2, false, true);
                }
                else if ((int)Main.tile[x, y].slope() == num18 + 2)
                {
                    WorldGen.SlopeTile(x, y, num19 + 2, false, true);
                }
                else if ((int)Main.tile[x, y].slope() == num19 + 2)
                {
                    WorldGen.SlopeTile(x, y, num18, false, true);
                }
                else if ((int)Main.tile[x, y].slope() == num18)
                {
                    WorldGen.SlopeTile(x, y, num19, false, true);
                }
                else
                {
                    WorldGen.SlopeTile(x, y, 0, false, true);
                }
                int num20 = (int)Main.tile[x, y].slope();
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 14, (float)x, (float)y, (float)num20, 0, 0, 0);
                }
            }
            else
            {
                WorldGen.PoundTile(x, y);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 7, (float)x, (float)y, 1f, 0, 0, 0);
                }
            }
            this.poundRelease = false;
        }
References Terraria.Tile.active(), Terraria.Tile.bottomSlope(), Terraria.WorldGen.CanPoundTile(), Terraria.Minecart.FrameTrack(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Item.hammer, int, Terraria.ID.TileID.Sets.IsBeam, Terraria.WorldGen.IsLockedDoor(), Terraria.WorldGen.IsTreeType(), Terraria.WorldGen.KillTile(), Terraria.Tile.leftSlope(), Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.ID.TileID.Sets.Platforms, Terraria.Audio.SoundEngine.PlaySound(), Terraria.WorldGen.PoundTile(), Terraria.Tile.rightSlope(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.topSlope(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryChangePose(), and Terraria.Tile.type.