Terraria Decompiled: Terraria.Player.CheckSpawn_Internal
CheckSpawn_Internal()
static bool Terraria.Player.CheckSpawn_Internal (int x, int y) inline static private
Definition at line 53866 of file Player.cs.
        {
            if (x < 10 || x > Main.maxTilesX - 10 || y < 10 || y > Main.maxTilesX - 10)
            {
                return false;
            }
            if (Main.tile[x, y - 1] == null)
            {
                return false;
            }
            if (!Main.tile[x, y - 1].active() || Main.tile[x, y - 1].type != 79)
            {
                return false;
            }
            for (int i = x - 1; i <= x + 1; i++)
            {
                for (int j = y - 3; j < y; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        return false;
                    }
                    if (Main.tile[i, j].nactive() && Main.tileSolid[(int)Main.tile[i, j].type] && !Main.tileSolidTop[(int)Main.tile[i, j].type])
                    {
                        Main.NewText(Language.GetTextValue("Game.BedObstructed"), ChatColors.ServerMessage);
                        return false;
                    }
                }
            }
            if (!WorldGen.StartRoomCheck(x, y - 1, null))
            {
                string text;
                switch (WorldGen.roomCheckFailureReason)
                {
                case TownNPCRoomCheckFailureReason.TooCloseToWorldEdge:
                    text = "Game.BedTooCloseToWorldEdge";
                    goto IL_0152;
                case TownNPCRoomCheckFailureReason.RoomIsTooBig:
                    text = "Game.BedRoomIsTooBig";
                    goto IL_0152;
                case TownNPCRoomCheckFailureReason.RoomIsTooSmall:
                    text = "Game.BedRoomIsTooSmall";
                    goto IL_0152;
                case TownNPCRoomCheckFailureReason.HoleInWallIsTooBig:
                    text = "Game.BedRoomHasHolesInWall";
                    goto IL_0152;
                case TownNPCRoomCheckFailureReason.TooManyUnsafeWalls:
                    text = "Game.BedRoomHasUnsafeWalls";
                    goto IL_0152;
                }
                text = "Game.BedRoomIsNotValid";
                IL_0152:
                if (!string.IsNullOrEmpty(text))
                {
                    Main.NewText(Language.GetTextValue(text), ChatColors.ServerMessage);
                }
                return false;
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.maxTilesX, Terraria.Tile.nactive(), Terraria.Main.NewText(), Terraria.WorldGen.roomCheckFailureReason, Terraria.Chat.ChatColors.ServerMessage, Terraria.WorldGen.StartRoomCheck(), System.text, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.Player.CheckSpawn().