Terraria Decompiled: Terraria.Player.ApplyCoating
ApplyCoating()
void Terraria.Player.ApplyCoating (int x, int y, bool paintingAWall, bool applyItemAnimation, Item targetItem) inline private
Definition at line 41007 of file Player.cs.
        {
            byte paintCoating = targetItem.paintCoating;
            if (paintingAWall)
            {
                if (WorldGen.paintCoatWall(x, y, paintCoating, true, true))
                {
                    targetItem.stack--;
                    if (targetItem.stack <= 0)
                    {
                        targetItem.SetDefaults(0, null);
                    }
                    if (applyItemAnimation)
                    {
                        this.ApplyItemTime(this.inventory[this.selectedItem], this.wallSpeed);
                        return;
                    }
                }
            }
            else if (WorldGen.paintCoatTile(x, y, paintCoating, true, true))
            {
                targetItem.stack--;
                if (targetItem.stack <= 0)
                {
                    targetItem.SetDefaults(0, null);
                }
                if (applyItemAnimation)
                {
                    this.ApplyItemTime(this.inventory[this.selectedItem], this.tileSpeed);
                }
            }
        }
References Terraria.Item.paintCoating, Terraria.WorldGen.paintCoatTile(), Terraria.WorldGen.paintCoatWall(), Terraria.Item.SetDefaults(), and Terraria.Item.stack.