Terraria Decompiled: Terraria.Player.ItemCheck_CheckCanUse_Inner
ItemCheck_CheckCanUse_Inner()
bool Terraria.Player.ItemCheck_CheckCanUse_Inner (Item sItem, bool ignoreCursed = false) inline private
Definition at line 51334 of file Player.cs.
        {
            if (this.whoAmI == Main.myPlayer && Main.LocalPlayerHasPendingInventoryActions())
            {
                return false;
            }
            int whoAmI = this.whoAmI;
            bool flag = true;
            int num;
            int num2;
            this.GetTargetTileWithReverseGravity(out num, out num2);
            if (sItem.type == 3335 && (this.extraAccessory || !Main.expertMode))
            {
                flag = false;
            }
            if (this.pulley && sItem.fishingPole > 0)
            {
                flag = false;
            }
            if (this.pulley && ItemID.Sets.IsAKite[sItem.type])
            {
                flag = false;
            }
            if (sItem.type == 3611 && (WiresUI.Settings.ToolMode & (WiresUI.Settings.MultiToolMode.Red | WiresUI.Settings.MultiToolMode.Green | WiresUI.Settings.MultiToolMode.Blue | WiresUI.Settings.MultiToolMode.Yellow | WiresUI.Settings.MultiToolMode.Actuator)) == (WiresUI.Settings.MultiToolMode)0)
            {
                flag = false;
            }
            if (sItem.type == 5451 && this.ownedProjectileCounts[1020] > 0)
            {
                flag = false;
            }
            if (sItem.type == 5738 && this.ownedProjectileCounts[1105] > 0)
            {
                flag = false;
            }
            if ((sItem.type == 3611 || sItem.type == 3625) && this.wireOperationsCooldown > 0)
            {
                flag = false;
            }
            if (!this.CheckDD2CrystalPaymentLock(sItem))
            {
                flag = false;
            }
            if (sItem.shoot > -1 && ProjectileID.Sets.IsADD2Turret[sItem.shoot] && !this.downedDD2EventAnyDifficulty && !DD2Event.Ongoing)
            {
                flag = false;
            }
            if (sItem.shoot > -1 && ProjectileID.Sets.IsADD2Turret[sItem.shoot] && DD2Event.Ongoing && whoAmI == Main.myPlayer)
            {
                int num3;
                int num4;
                int num5;
                this.FindSentryRestingSpot(sItem.shoot, out num3, out num4, out num5);
                if (Player.WouldSpotOverlapWithSentry(num3, num4, sItem.shoot == 688 || sItem.shoot == 689 || sItem.shoot == 690))
                {
                    flag = false;
                }
            }
            if (sItem.shoot > -1 && ProjectileID.Sets.IsADD2Turret[sItem.shoot] && whoAmI == Main.myPlayer)
            {
                int num6;
                int num7;
                int num8;
                this.FindSentryRestingSpot(sItem.shoot, out num6, out num7, out num8);
                num6 /= 16;
                num7 /= 16;
                num7--;
                if (sItem.shoot == 688 || sItem.shoot == 689 || sItem.shoot == 690)
                {
                    if (Collision.SolidTiles(num6, num6, num7 - 2, num7))
                    {
                        flag = false;
                    }
                }
                else if (WorldGen.SolidTile(num6, num7, false))
                {
                    flag = false;
                }
            }
            if (this.wet && !this.lavaWet && (sItem.shoot == 85 || sItem.shoot == 15 || sItem.shoot == 34))
            {
                flag = false;
            }
            if (sItem.makeNPC > 0 && !NPC.CanReleaseNPCs(this.whoAmI))
            {
                flag = false;
            }
            if (this.whoAmI == Main.myPlayer && sItem.type == 603 && !Main.runningCollectorsEdition)
            {
                flag = false;
            }
            if (sItem.type == 1071 || sItem.type == 1072 || sItem.type == 1543 || sItem.type == 1544)
            {
                bool flag2 = false;
                for (int i = 0; i < 58; i++)
                {
                    if (this.inventory[i].PaintOrCoating)
                    {
                        flag2 = true;
                        break;
                    }
                }
                if (!flag2)
                {
                    flag = false;
                }
            }
            bool flag3 = ignoreCursed;
            if (this.mount.Active && this.mount.DismountOnItemUse && this.mount.CanDismount(this) && this.noItems && !this.cursed)
            {
                flag3 = true;
            }
            if (this.noItems && !flag3)
            {
                flag = false;
            }
            if (sItem.tileWand > 0)
            {
                int tileWand = sItem.tileWand;
                flag = false;
                for (int j = 0; j < 58; j++)
                {
                    if (tileWand == this.inventory[j].type && this.inventory[j].stack > 0)
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (sItem.shoot == 6 || sItem.shoot == 19 || sItem.shoot == 33 || sItem.shoot == 52 || sItem.shoot == 113 || sItem.shoot == 320 || sItem.shoot == 333 || sItem.shoot == 383 || sItem.shoot == 491 || sItem.shoot == 867 || sItem.shoot == 1052 || sItem.shoot == 902 || sItem.shoot == 866 || ProjectileID.Sets.IsAPhaseblade[sItem.shoot] || sItem.shoot == 301)
            {
                for (int k = 0; k < 1000; k++)
                {
                    if (Main.projectile[k].active && Main.projectile[k].owner == this.whoAmI && Main.projectile[k].type == sItem.shoot)
                    {
                        flag = false;
                    }
                }
            }
            if (sItem.shoot == 106)
            {
                int num9 = 0;
                for (int l = 0; l < 1000; l++)
                {
                    if (Main.projectile[l].active && Main.projectile[l].owner == this.whoAmI && Main.projectile[l].type == sItem.shoot)
                    {
                        num9++;
                    }
                }
                if (num9 >= 6)
                {
                    flag = false;
                }
            }
            if (sItem.shoot == 272)
            {
                int num10 = 0;
                for (int m = 0; m < 1000; m++)
                {
                    if (Main.projectile[m].active && Main.projectile[m].owner == this.whoAmI && Main.projectile[m].type == sItem.shoot)
                    {
                        num10++;
                    }
                }
                if (num10 >= 10)
                {
                    flag = false;
                }
            }
            if (sItem.shoot == 1000)
            {
                int num11 = 0;
                for (int n = 0; n < 1000; n++)
                {
                    if (Main.projectile[n].active && Main.projectile[n].owner == this.whoAmI && Main.projectile[n].type == sItem.shoot)
                    {
                        num11++;
                    }
                }
                if (num11 >= 3)
                {
                    flag = false;
                }
            }
            if (sItem.potion && this.potionDelay > 0)
            {
                flag = false;
            }
            if (sItem.mana > 0 && this.silence)
            {
                flag = false;
            }
            if (sItem.mana > 0 && flag)
            {
                flag = this.ItemCheck_CheckCanUse_CanPayMana(sItem, flag);
            }
            if (this.gravDir == -1f && GolfHelper.IsPlayerHoldingClub(this))
            {
                flag = false;
            }
            if (sItem.type == 43 && Main.IsItDay())
            {
                flag = false;
            }
            if (sItem.type == 544 && Main.IsItDay())
            {
                flag = false;
            }
            if (sItem.type == 556 && Main.IsItDay())
            {
                flag = false;
            }
            if (sItem.type == 557 && Main.IsItDay())
            {
                flag = false;
            }
            if (sItem.type == 70 && !this.ZoneCorrupt)
            {
                flag = false;
            }
            if (sItem.type == 1133 && !this.ZoneJungle)
            {
                flag = false;
            }
            if (sItem.type == 5120 && !this.ZoneSnow)
            {
                flag = false;
            }
            if (sItem.type == 1844 && (Main.dayTime || Main.pumpkinMoon || Main.snowMoon || DD2Event.Ongoing))
            {
                flag = false;
            }
            if (sItem.type == 1958 && (Main.dayTime || Main.pumpkinMoon || Main.snowMoon || DD2Event.Ongoing))
            {
                flag = false;
            }
            if (sItem.type == 2767 && (!Main.dayTime || Main.eclipse || !Main.hardMode))
            {
                flag = false;
            }
            if (sItem.type == 4271 && (Main.dayTime || Main.bloodMoon))
            {
                flag = false;
            }
            if (sItem.type == 3601 && (!NPC.downedGolemBoss || !Main.hardMode || NPC.AnyDanger(false, false) || NPC.AnyoneNearCultists()))
            {
                flag = false;
            }
            if (!this.SummonItemCheck(sItem))
            {
                flag = false;
            }
            if (sItem.chlorophyteExtractinatorConsumable && flag && whoAmI == Main.myPlayer)
            {
                Tile tile = Main.tile[num, num2];
                if (!tile.active() || (tile.type != 642 && tile.type != 219))
                {
                    flag = false;
                }
            }
            if (ItemID.Sets.HasAProjectileThatHasAUsabilityCheck[sItem.type])
            {
                flag = this.ItemCheck_CheckUsabilityOfProjectiles(flag);
            }
            if (ItemID.Sets.ShootsOnUseRelease[sItem.type])
            {
                flag &= this.itemTime == 0;
            }
            if (sItem.shoot == 17 && flag && whoAmI == Main.myPlayer)
            {
                if (!Player.ItemCheck_IsValidDirtRodTarget(Main.tile[num, num2]))
                {
                    flag = false;
                }
                if (!WorldGen.CanKillTile(num, num2))
                {
                    flag = false;
                }
            }
            if (flag && sItem.mountType != -1 && !this.mount.CanMount(sItem.mountType, this))
            {
                flag = false;
            }
            if (flag)
            {
                flag = this.HasAmmo(sItem, flag);
            }
            return flag;
        }
References Terraria.Projectile.active, Terraria.Tile.active(), Terraria.NPC.AnyDanger(), Terraria.NPC.AnyoneNearCultists(), Terraria.Main.bloodMoon, Terraria.WorldGen.CanKillTile(), Terraria.NPC.CanReleaseNPCs(), Terraria.Item.chlorophyteExtractinatorConsumable, Terraria.Main.dayTime, Terraria.NPC.downedGolemBoss, Terraria.Main.eclipse, Terraria.Main.expertMode, Terraria.Item.fishingPole, Terraria.Main.hardMode, Terraria.ID.ItemID.Sets.HasAProjectileThatHasAUsabilityCheck, Terraria.ID.ProjectileID.Sets.IsADD2Turret, Terraria.ID.ItemID.Sets.IsAKite, Terraria.ID.ProjectileID.Sets.IsAPhaseblade, Terraria.Main.IsItDay(), Terraria.GameContent.Golf.GolfHelper.IsPlayerHoldingClub(), Terraria.Player.ItemCheck_IsValidDirtRodTarget(), Terraria.Main.LocalPlayerHasPendingInventoryActions(), Terraria.Item.makeNPC, Terraria.Item.mana, Terraria.Item.mountType, Terraria.Main.myPlayer, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Projectile.owner, Terraria.Item.potion, Terraria.Main.projectile, Terraria.Main.pumpkinMoon, Terraria.Main.runningCollectorsEdition, Terraria.Item.shoot, Terraria.ID.ItemID.Sets.ShootsOnUseRelease, Terraria.Main.snowMoon, Terraria.WorldGen.SolidTile(), Terraria.Collision.SolidTiles(), System.stack, Terraria.Main.tile, Terraria.Item.tileWand, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.Item.type, Terraria.Projectile.type, Terraria.Tile.type, and Terraria.Player.WouldSpotOverlapWithSentry().