Terraria Decompiled: Terraria.Player.WallslideMovement
WallslideMovement()
void Terraria.Player.WallslideMovement () inline
Definition at line 20143 of file Player.cs.
        {
            this.sliding = false;
            if (this.slideDir != 0 && this.spikedBoots > 0 && !this.mount.Active && ((this.controlLeft && this.slideDir == -1) || (this.controlRight && this.slideDir == 1)))
            {
                bool flag = false;
                float num = this.position.X;
                if (this.slideDir == 1)
                {
                    num += (float)this.width;
                }
                num += (float)this.slideDir;
                float num2 = this.position.Y + (float)this.height + 1f;
                if (this.gravDir < 0f)
                {
                    num2 = this.position.Y - 1f;
                }
                num /= 16f;
                num2 /= 16f;
                if (WorldGen.SolidTile((int)num, (int)num2, false) && WorldGen.SolidTile((int)num, (int)num2 - 1, false))
                {
                    flag = true;
                }
                if (this.spikedBoots >= 2)
                {
                    if (flag && ((this.velocity.Y > 0f && this.gravDir == 1f) || (this.velocity.Y < this.gravity && this.gravDir == -1f)))
                    {
                        float num3 = this.gravity;
                        if (this.slowFall)
{
                            if (this.TryingToHoverUp)
{
                                num3 = this.gravity / 10f * this.gravDir;
                            }
                            else
{
                                num3 = this.gravity / 3f * this.gravDir;
                            }
                        }
                        this.fallStart = (int)(this.position.Y / 16f);
                        if ((this.controlDown && this.gravDir == 1f) || (this.controlUp && this.gravDir == -1f))
{
                            this.velocity.Y = 4f * this.gravDir;
                            int num4 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) + (float)((this.width / 2 - 4) * this.slideDir), this.position.Y + (float)(this.height / 2) + (float)(this.height / 2 - 4) * this.gravDir), 8, 8, 31, 0f, 0f, 0, default(Color), 1f);
                            if (this.slideDir < 0)
{
                                Dust dust = Main.dust[num4];
                                dust.position.X = dust.position.X - 10f;
                            }
                            if (this.gravDir < 0f)
{
                                Dust dust2 = Main.dust[num4];
                                dust2.position.Y = dust2.position.Y - 12f;
                            }
                            Main.dust[num4].velocity *= 0.1f;
                            Main.dust[num4].scale *= 1.2f;
                            Main.dust[num4].noGravity = true;
                            Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(this.cShoe, this);
                        }
                        else if (this.gravDir == -1f)
{
                            this.velocity.Y = (-num3 + 1E-05f) * this.gravDir;
                        }
                        else
{
                            this.velocity.Y = (-num3 + 1E-05f) * this.gravDir;
                        }
                        this.sliding = true;
                        return;
                    }
                }
                else if ((flag && (double)this.velocity.Y > 0.5 && this.gravDir == 1f) || ((double)this.velocity.Y < -0.5 && this.gravDir == -1f))
                {
                    this.fallStart = (int)(this.position.Y / 16f);
                    if (this.controlDown)
                    {
                        this.velocity.Y = 4f * this.gravDir;
                    }
                    else
                    {
                        this.velocity.Y = 0.5f * this.gravDir;
                    }
                    this.sliding = true;
                    int num5 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) + (float)((this.width / 2 - 4) * this.slideDir), this.position.Y + (float)(this.height / 2) + (float)(this.height / 2 - 4) * this.gravDir), 8, 8, 31, 0f, 0f, 0, default(Color), 1f);
                    if (this.slideDir < 0)
                    {
                        Dust dust3 = Main.dust[num5];
                        dust3.position.X = dust3.position.X - 10f;
                    }
                    if (this.gravDir < 0f)
                    {
                        Dust dust4 = Main.dust[num5];
                        dust4.position.Y = dust4.position.Y - 12f;
                    }
                    Main.dust[num5].velocity *= 0.1f;
                    Main.dust[num5].scale *= 1.2f;
                    Main.dust[num5].noGravity = true;
                    Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(this.cShoe, this);
                }
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.dust, System.E, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), int, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Dust.scale, Terraria.Dust.shader, Terraria.WorldGen.SolidTile(), and Terraria.Dust.velocity.