Terraria Decompiled: Terraria.Player.PickTile_DetermineDamage
PickTile_DetermineDamage()
void Terraria.Player.PickTile_DetermineDamage (int x, int y, int pickPower, Tile tileTarget, out int bufferIndex, out int damage) inline
Definition at line 53104 of file Player.cs.
        {
            bufferIndex = this.hitTile.HitObject(x, y, 1);
            damage = this.GetPickaxeDamage(x, y, pickPower, bufferIndex, tileTarget);
            if (!WorldGen.CanKillTile(x, y))
            {
                damage = 0;
            }
            if (Main.getGoodWorld)
            {
                damage *= 2;
            }
            if (this.DoesPickTargetTransformOnKill(this.hitTile, damage, x, y, pickPower, bufferIndex, tileTarget))
            {
                damage = 0;
            }
        }
References Terraria.WorldGen.CanKillTile(), and Terraria.Main.getGoodWorld.
Referenced by Terraria.Projectile.AI_067_FreakingPirates_HitIntention(), and Terraria.Projectile.AI_204_Digtoise().