Terraria Decompiled: Terraria.Player.GetHelmetDrawOffset
GetHelmetDrawOffset()
Vector2 Terraria.Player.GetHelmetDrawOffset (bool minimap = false) inline
Definition at line 1660 of file Player.cs.
        {
            Vector2 vector = Vector2.Zero;
            if (this.head == 270)
            {
                vector = new Vector2(-10f, 0f) * this.Directions;
                if (this.direction == -1)
                {
                    vector.X -= 2f;
                }
            }
            else if (this.head == 268)
            {
                vector = new Vector2(0f, -6f) * this.Directions;
            }
            else if (this.head == 222)
            {
                float num = 0f;
                if (this.hair == 15 || this.hair == 76 || this.hair == 108)
                {
                    num = 4f;
                }
                vector = new Vector2(0f, num) * this.Directions;
            }
            else if (this.head == 272)
            {
                if (this.hair == 15 || this.hair == 76 || this.hair == 108)
                {
                    vector = new Vector2(0f, 4f) * this.Directions;
                }
            }
            else if (this.head == 275)
            {
                vector = new Vector2(0f, -4f) * this.Directions;
            }
            vector += this.GetHelmetOffsetAddonFromFaceHead();
            if (!minimap)
            {
                vector += this.GetHelmetOffsetAddonFromMount();
            }
            return vector;
        }
References Terraria.Entity.direction, Terraria.Player.Directions, Terraria.Player.GetHelmetOffsetAddonFromFaceHead(), Terraria.Player.GetHelmetOffsetAddonFromMount(), Terraria.Player.hair, Terraria.Player.head, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.DataStructures.PlayerDrawHeadSet.BoringSetup(), and Terraria.DataStructures.PlayerDrawSet.BoringSetup().