Terraria Decompiled: Terraria.Player.ApplyTouchDamage
ApplyTouchDamage()
void Terraria.Player.ApplyTouchDamage (int tileId, int x, int y) inline private
Definition at line 27403 of file Player.cs.
        {
            bool flag = false;
            int num = TileID.Sets.TouchDamageImmediate[tileId];
            if (num > 0)
            {
                num = Main.DamageVar((float)num, -this.luck);
                if (this.Hurt(PlayerDeathReason.ByOther(3), num, 0, false, false, false, ImmunityCooldownID.TileContactDamage, true) == 0.0)
                {
                    flag = true;
                }
            }
            if (!flag)
            {
                if (TileID.Sets.TouchDamageHot[tileId])
                {
                    this.AddBuff(67, 20, false);
                }
                if (TileID.Sets.TouchDamageBleeding[tileId])
                {
                    this.AddBuff(30, Main.rand.Next(600, 1200), false);
                }
            }
            if (TileID.Sets.Suffocate[tileId])
            {
                if (this.suffocateDelay < 5)
                {
                    this.suffocateDelay += 1;
                }
                else
                {
                    this.AddBuff(68, 1, false);
                }
            }
            else
            {
                this.suffocateDelay = 0;
            }
            if (TileID.Sets.TouchDamageDestroyTile[tileId])
            {
                WorldGen.KillTile(x, y, false, false, false);
                if (Main.netMode == 1 && !Main.tile[x, y].active())
                {
                    NetMessage.SendData(17, -1, -1, null, 4, (float)x, (float)y, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.Tile.active(), Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Main.DamageVar(), Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.ID.TileID.Sets.Suffocate, Terraria.Main.tile, Terraria.ID.ImmunityCooldownID.TileContactDamage, Terraria.ID.TileID.Sets.TouchDamageBleeding, Terraria.ID.TileID.Sets.TouchDamageDestroyTile, Terraria.ID.TileID.Sets.TouchDamageHot, and Terraria.ID.TileID.Sets.TouchDamageImmediate.