Terraria Decompiled: Terraria.Player.PlaceThing_ItemInExtractinator
PlaceThing_ItemInExtractinator()
void Terraria.Player.PlaceThing_ItemInExtractinator (ref Player::ItemCheckContext context) inline private
Definition at line 40679 of file Player.cs.
        {
            Tile tile = Main.tile[Player.tileTargetX, Player.tileTargetY];
            Item item = this.inventory[this.selectedItem];
            if (!tile.active())
            {
                return;
            }
            if (!this.IsInTileInteractionRange(Player.tileTargetX, Player.tileTargetY, TileReachCheckSettings.Simple, item.tileBoost + this.blockRange))
            {
                return;
            }
            if (!this.ItemTimeIsZero || this.itemAnimation <= 0 || !this.controlUseItem)
            {
                return;
            }
            float num = 1f;
            if (tile.type == 642)
            {
                num *= 0.33f;
            }
            ItemTrader itemTrader = Player.TryGettingItemTraderFromBlock(tile);
            ItemTrader.TradeOption tradeOption;
            if (itemTrader != null && itemTrader.TryGetTradeOption(item, out tradeOption))
            {
                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                this.ApplyItemTime(item, num);
                context.SkipItemConsumption = true;
                item.stack -= tradeOption.TakingItemStack;
                if (item.stack <= 0)
                {
                    item.TurnToAir(false);
                }
                this.DropItemFromExtractinator(tradeOption.GivingItemType, tradeOption.GivingItemStack);
                return;
            }
            if (ItemID.Sets.ExtractinatorMode[item.type] >= 0 && (tile.type == 219 || tile.type == 642))
            {
                this.ApplyItemTime(item, num);
                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                int num2 = ItemID.Sets.ExtractinatorMode[item.type];
                this.ExtractinatorUse(num2, (int)tile.type);
            }
        }
References Terraria.Tile.active(), Terraria.ID.ItemID.Sets.ExtractinatorMode, Terraria.GameContent.ItemTrader.TradeOption.GivingItemStack, Terraria.GameContent.ItemTrader.TradeOption.GivingItemType, System.item, Terraria.Audio.SoundEngine.PlaySound(), Terraria.DataStructures.TileReachCheckSettings.Simple, Terraria.GameContent.ItemTrader.TradeOption.TakingItemStack, Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Player.TryGettingItemTraderFromBlock(), Terraria.GameContent.ItemTrader.TryGetTradeOption(), and Terraria.Tile.type.