Terraria Decompiled: Terraria.Player.AllowShimmerDodge
AllowShimmerDodge()
static bool Terraria.Player.AllowShimmerDodge (PlayerDeathReason damageSource, int cooldownCounter, bool dodgeable) inline static private
Definition at line 37626 of file Player.cs.
        {
            if (!dodgeable)
            {
                return false;
            }
            if (cooldownCounter == 1)
            {
                return false;
            }
            Entity entity = null;
            if (!damageSource.TryGetCausingEntity(out entity))
            {
                return true;
            }
            NPC npc = entity as NPC;
            if (npc != null && npc.active && (npc.boss || NPC.GetNPCInvasionGroup(npc.type) != 0 || NPCID.Sets.CanHitPastShimmer[npc.type]))
            {
                return false;
            }
            Projectile projectile = entity as Projectile;
            return projectile == null || !projectile.active || !ProjectileID.Sets.CanHitPastShimmer[projectile.type];
        }
References Terraria.NPC.active, Terraria.NPC.boss, Terraria.ID.NPCID.Sets.CanHitPastShimmer, Terraria.ID.ProjectileID.Sets.CanHitPastShimmer, Terraria.NPC.GetNPCInvasionGroup(), Terraria.Enums.NPC, Terraria.DataStructures.PlayerDeathReason.TryGetCausingEntity(), Terraria.NPC.type, and Terraria.Projectile.type.
Referenced by Terraria.Player.Hurt().