Terraria Decompiled: Terraria.Player.Ghost
Ghost()
void Terraria.Player.Ghost () inline
Definition at line 3947 of file Player.cs.
        {
            this.spectating = -1;
            this.immune = false;
            this.immuneAlpha = 0;
            this.ResetEffects();
            this.ResetVisibleAccessories();
            if (FocusHelper.AllowGameplayInputs && this.whoAmI == Main.myPlayer)
            {
                this.controlUp = false;
                this.controlLeft = false;
                this.controlDown = false;
                this.controlRight = false;
                this.controlJump = false;
                if (!Main.drawingPlayerChat && !Main.editSign && !Main.editChest && !Main.blockInput)
                {
                    PlayerInput.Triggers.Current.CopyInto(this);
                    this.TrySyncingInput();
                    this.TryOpeningInGameOptionsBasedOnInput();
                }
            }
            float num = 7f;
            float num2 = 0.2f;
            if (this.controlUp || this.controlJump)
            {
                if (this.velocity.Y > 0f)
                {
                    this.velocity.Y = this.velocity.Y * 0.9f;
                }
                this.velocity.Y = this.velocity.Y - num2;
                if (this.velocity.Y < -num)
                {
                    this.velocity.Y = -num;
                }
            }
            else if (this.controlDown)
            {
                if (this.velocity.Y < 0f)
                {
                    this.velocity.Y = this.velocity.Y * 0.9f;
                }
                this.velocity.Y = this.velocity.Y + num2;
                if (this.velocity.Y > num)
                {
                    this.velocity.Y = num;
                }
            }
            else if ((double)this.velocity.Y < -0.1 || (double)this.velocity.Y > 0.1)
            {
                this.velocity.Y = this.velocity.Y * 0.9f;
            }
            else
            {
                this.velocity.Y = 0f;
            }
            if (this.controlLeft && !this.controlRight)
            {
                if (this.velocity.X > 0f)
                {
                    this.velocity.X = this.velocity.X * 0.9f;
                }
                this.velocity.X = this.velocity.X - num2;
                if (this.velocity.X < -num)
                {
                    this.velocity.X = -num;
                }
            }
            else if (this.controlRight && !this.controlLeft)
            {
                if (this.velocity.X < 0f)
                {
                    this.velocity.X = this.velocity.X * 0.9f;
                }
                this.velocity.X = this.velocity.X + num2;
                if (this.velocity.X > num)
                {
                    this.velocity.X = num;
                }
            }
            else if (this.velocity.X < -num2 || this.velocity.X > num2)
            {
                this.velocity.X = this.velocity.X * 0.9f;
            }
            else
            {
                this.velocity.X = 0f;
            }
            this.position += this.velocity;
            this.ghostFrameCounter++;
            if (this.velocity.X < 0f)
            {
                this.direction = -1;
            }
            else if (this.velocity.X > 0f)
            {
                this.direction = 1;
            }
            if (this.ghostFrameCounter >= 8)
            {
                this.ghostFrameCounter = 0;
                this.ghostFrame++;
                if (this.ghostFrame >= 4)
                {
                    this.ghostFrame = 0;
                }
            }
            int num3 = 640;
            float num4 = Main.leftWorld + (float)num3;
            if (this.position.X < num4)
            {
                this.position.X = num4;
                this.velocity.X = 0f;
            }
            float num5 = Main.rightWorld - (float)num3 - (float)this.width;
            if (this.position.X > num5)
            {
                this.position.X = num5;
                this.velocity.X = 0f;
            }
            float num6 = Main.topWorld + (float)num3;
            if (this.position.Y < num6)
            {
                this.position.Y = num6;
                if (this.velocity.Y < -0.1f)
                {
                    this.velocity.Y = -0.1f;
                }
            }
            float num7 = Main.bottomWorld - (float)num3 - (float)this.height;
            if (this.position.Y > num7)
            {
                this.position.Y = num7;
                this.velocity.Y = 0f;
            }
            this.UpdateNetOffset(true, true);
        }
References Terraria.FocusHelper.AllowGameplayInputs, Terraria.Main.blockInput, Terraria.Player.controlDown, Terraria.Player.controlJump, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.controlUp, Terraria.GameInput.TriggersSet.CopyInto(), Terraria.GameInput.TriggersPack.Current, Terraria.Main.drawingPlayerChat, Terraria.Main.editChest, Terraria.Main.editSign, Terraria.Player.ghostFrame, Terraria.Player.ghostFrameCounter, Terraria.Entity.height, Terraria.Main.myPlayer, Terraria.Entity.position, Terraria.Player.ResetEffects(), Terraria.Player.ResetVisibleAccessories(), Terraria.GameInput.PlayerInput.Triggers, Terraria.Player.TryOpeningInGameOptionsBasedOnInput(), Terraria.Player.TrySyncingInput(), Terraria.Player.UpdateNetOffset(), Terraria.Entity.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.