Terraria Decompiled: Terraria.Player.ApplyDamageToNPC
ApplyDamageToNPC()
void Terraria.Player.ApplyDamageToNPC (NPC npc, int damage, float knockback, int direction, bool crit) inline
Definition at line 18733 of file Player.cs.
        {
            ItemID.BannerEffect bannerEffect;
            if (this.GetBannerBuffEffect(npc, out bannerEffect))
            {
                damage = (int)((float)damage * bannerEffect.DamageDealt.Sample(Main.Difficulty));
            }
            this.OnHit(npc.Center.X, npc.Center.Y, npc);
            damage += npc.checkArmorPenetration(this.GetArmorPenetration(false), 0f);
            NPCKillAttempt npckillAttempt = new NPCKillAttempt(npc);
            int num = (int)npc.StrikeNPC(damage, knockback, direction, crit, false, false, this.whoAmI);
            if (this.accDreamCatcher)
            {
                this.addDPS(num);
            }
            if (Main.netMode != 0)
            {
                NetMessage.SendData(28, -1, -1, null, npc.whoAmI, (float)damage, knockback, (float)direction, crit.ToInt(), 0, 0);
            }
            int num2 = BannerSystem.NPCtoBanner(npc.BannerID());
            if (num2 >= 0)
            {
                this.lastCreatureHit = num2;
            }
            if (npckillAttempt.DidNPCDie())
            {
                this.OnKillNPC(ref npckillAttempt, null);
            }
        }
References Terraria.NPC.BannerID(), Terraria.Entity.Center, Terraria.NPC.checkArmorPenetration(), Terraria.ID.ItemID.BannerEffect.DamageDealt, Terraria.DataStructures.NPCKillAttempt.DidNPCDie(), Terraria.Main.Difficulty, int, Terraria.Main.netMode, Terraria.GameContent.BannerSystem.NPCtoBanner(), Terraria.NetMessage.SendData(), Terraria.NPC.StrikeNPC(), Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.