Terraria Decompiled: Terraria.Player.HeroicisWingDust
HeroicisWingDust()
void Terraria.Player.HeroicisWingDust (bool noDustLight, bool justSwitched) inline private
Definition at line 29183 of file Player.cs.
        {
            if (Main.netMode == 2 || this.wingFrame == 0)
            {
                return;
            }
            float num = 0f;
            switch (this.wingFrame)
            {
            case 1:
                num = 0f;
                break;
            case 2:
                num = 0f;
                break;
            case 3:
                num = 0.5f;
                break;
            case 4:
                num = 1f;
                break;
            case 5:
                num = 1f;
                break;
            case 6:
                num = 0.5f;
                break;
            case 7:
                num = 0f;
                break;
            case 8:
                num = -0.5f;
                break;
            case 9:
                num = -1f;
                break;
            case 10:
                num = -0.5f;
                break;
            }
            Color color = new Color(255, 255, 255, 200);
            float num2 = 0.6f;
            float num3 = 0f;
            float num4 = 0.45f;
            float num5 = Main.rgbToHsl(Lighting.GetColor(this.MountedCenter.ToTileCoordinates())).Z;
            num5 = Utils.Remap(num5, 0.2f, 0.4f, 0f, 1f, true);
            if (justSwitched && this.wingFrame == 6 && this.controlJump)
            {
                for (int i = 0; i < 8; i++)
                {
                    if (num5 >= Main.rand.NextFloat())
                    {
                        Point point = new Point(10, 5);
                        Vector2 vector = ((i < 4) ? new Vector2((float)(-20 * this.direction), 15f * this.gravDir) : new Vector2((float)(-10 * this.direction), 15f * this.gravDir));
                        Dust dust = Dust.NewDustDirect(base.Center - point.ToVector2() / 2f + vector, point.X, point.Y, 264, 0f, 0f, 0, color, num2 * (1f + num4 * Main.rand.NextFloatDirection()));
                        float x = (dust.position - base.Center - vector).X;
                        dust.position.Y = dust.position.Y + x * 2f;
                        dust.noGravity = true;
                        dust.noLightEmittance = noDustLight;
                        dust.noLight = true;
                        dust.fadeIn = num3;
                        dust.velocity = new Vector2(x * 0.5f, 2f);
                        dust.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                        dust.customData = this;
                    }
                }
            }
            if (Main.rand.Next(6) == 0 && num5 >= Main.rand.NextFloat())
            {
                Point point2 = new Point(30, 40);
                Vector2 vector2 = new Vector2((float)(-30 * this.direction), 0f);
                Dust dust2 = Dust.NewDustDirect(base.Center - point2.ToVector2() / 2f + vector2, point2.X, point2.Y, 264, 0f, 0f, 0, color, num2 * (1f + num4 * Main.rand.NextFloatDirection()));
                dust2.noGravity = true;
                dust2.noLightEmittance = noDustLight;
                dust2.noLight = true;
                dust2.velocity *= 0.1f;
                dust2.fadeIn = num3;
                dust2.velocity.Y = dust2.velocity.Y + num * 1.5f;
                dust2.position.Y = dust2.position.Y + num * 2f;
                dust2.velocity += this.velocity * 0.3f * Main.rand.NextFloat();
                dust2.shader = GameShaders.Armor.GetSecondaryShader(this.cWings, this);
                dust2.customData = this;
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Lighting.GetColor(), Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Main.netMode, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Main.rgbToHsl(), Microsoft.Xna.Framework.Point.X, System.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector3.Z.