Terraria Decompiled: Terraria.Player.LoadPlayer_LastMinuteFixes
LoadPlayer_LastMinuteFixes()
static void Terraria.Player.LoadPlayer_LastMinuteFixes (Player newPlayer) inline static private
Definition at line 55178 of file Player.cs.
        {
            newPlayer.skinVariant = (int)MathHelper.Clamp((float)newPlayer.skinVariant, 0f, (float)(PlayerVariantID.Count - 1));
            newPlayer.voiceVariant = Utils.Clamp<int>(newPlayer.voiceVariant, 1, 4);
            for (int i = 3; i < 10; i++)
            {
                int type = newPlayer.armor[i].type;
                if (type == 908 || type == 5000)
                {
                    newPlayer.lavaMax += 420;
                }
                if (type == 906 || type == 4038 || type == 3999 || type == 4003)
                {
                    newPlayer.lavaMax += 420;
                }
                if (newPlayer.wingsLogic == 0 && newPlayer.armor[i].wingSlot >= 0)
                {
                    newPlayer.wingsLogic = (int)newPlayer.armor[i].wingSlot;
                }
                if (type == 158 || type == 396 || type == 1250 || type == 1251 || type == 1252)
                {
                    newPlayer.noFallDmg = true;
                }
                if (type == 860 || type == 535)
                {
                    newPlayer.pStone = true;
                }
                newPlayer.lavaTime = newPlayer.lavaMax;
            }
            newPlayer.FixLoadedData();
        }
References Terraria.Player.armor, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Utils.Clamp(), Terraria.ID.PlayerVariantID.Count, Terraria.Player.FixLoadedData(), int, Terraria.Player.lavaMax, Terraria.Player.skinVariant, Terraria.Item.type, Terraria.Player.voiceVariant, Terraria.Player.wingsLogic, and Terraria.Item.wingSlot.
Referenced by Terraria.Player.Deserialize().