Terraria Decompiled: Terraria.Player.PickWall
PickWall()
void Terraria.Player.PickWall (int x, int y, int damage) inline
Definition at line 45227 of file Player.cs.
        {
            int num = this.hitTile.HitObject(x, y, 2);
            if (this.hitTile.AddDamage(num, damage, true) >= 100)
            {
                this.hitTile.Clear(num);
                this.ClearMiningCacheAt(x, y, 2);
                WorldGen.KillWall(x, y, false);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 2, (float)x, (float)y, 0f, 0, 0, 0);
                }
            }
            else
            {
                WorldGen.KillWall(x, y, true);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 2, (float)x, (float)y, 1f, 0, 0, 0);
                }
            }
            if (damage != 0)
            {
                this.hitTile.Prune();
            }
        }
References Terraria.WorldGen.KillWall(), Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.Mount.UseDrill().