Terraria Decompiled: Terraria.Player.InTileEntityInteractionRange
InTileEntityInteractionRange()
bool Terraria.Player.InTileEntityInteractionRange (int interactX, int interactY, int tileSizeX, int tileSizeY, TileReachCheckSettings settings) inline
Definition at line 30658 of file Player.cs.
        {
            Rectangle rectangle = new Rectangle(interactX * 16, interactY * 16, 16 * tileSizeX, 16 * tileSizeY);
            rectangle.Inflate(-1, -1);
            Point point = rectangle.ClosestPointInRect(base.Center).ToTileCoordinates();
            interactX = point.X;
            interactY = point.Y;
            return this.IsInTileInteractionRange(interactX, interactY, settings, 0);
        }
References Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerUpdate(), and Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerUpdate().