Terraria Decompiled: Terraria.Player.GetItem_FillEmptyInventorySlot
GetItem_FillEmptyInventorySlot()
bool Terraria.Player.GetItem_FillEmptyInventorySlot (Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
Definition at line 38403 of file Player.cs.
        {
            if (this.inventory[i].type != 0)
            {
                return false;
            }
            if (!settings.NoSound)
            {
                SoundEngine.PlaySound(newItem.IsACoin ? 38 : 7, -1, -1, 1, 1f, 0f);
            }
            this.inventory[i] = returnItem;
            Player.GetItemLogger.Add(this.inventory, i, this.GetFittingItemSlotContext(i), returnItem.stack);
            if (!settings.NoText)
            {
                PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, base.Center, newItem.stack, false, settings.LongText);
            }
            if (!settings.NoCoinMerge)
            {
                this.DoCoins(i);
            }
            AchievementsHelper.NotifyItemPickup(this, returnItem);
            if (this.whoAmI == Main.myPlayer && newItem.type == 5095)
            {
                LucyAxeMessage.Create(LucyAxeMessage.MessageSource.PickedUp, base.Top, new Vector2(0f, -7f));
            }
            settings.HandlePostAction(this.inventory[i]);
            return true;
        }
References Terraria.DataStructures.PlayerGetItemLogger.Add(), Terraria.GameContent.LucyAxeMessage.Create(), Terraria.Player.GetItemLogger, Terraria.GetItemSettings.HandlePostAction(), Terraria.Item.IsACoin, Terraria.GetItemSettings.LongText, Terraria.Main.myPlayer, Terraria.PopupText.NewText(), Terraria.GetItemSettings.NoCoinMerge, Terraria.GetItemSettings.NoSound, Terraria.GetItemSettings.NoText, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Item.stack, and Terraria.Item.type.