Terraria Decompiled: Terraria.Player.ApplySetBonus_Solar
ApplySetBonus_Solar()
void Terraria.Player.ApplySetBonus_Solar () inline
Definition at line 14379 of file Player.cs.
        {
            this.endurance += 0.12f;
            this.setSolar = true;
            this.solarCounter++;
            int num = 180;
            if (this.solarCounter >= num)
            {
                if (this.solarShields > 0 && this.solarShields < 3)
                {
                    for (int i = 0; i < Player.maxBuffs; i++)
                    {
                        if (this.buffType[i] >= 170 && this.buffType[i] <= 171)
{
                            this.DelBuff(i);
                        }
                    }
                }
                if (this.solarShields < 3)
                {
                    this.AddBuff(170 + this.solarShields, 5, false);
                    for (int j = 0; j < 16; j++)
                    {
                        Dust dust = Main.dust[Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 100, default(Color), 1f)];
                        dust.noGravity = true;
                        dust.scale = 1.7f;
                        dust.fadeIn = 0.5f;
                        dust.velocity *= 5f;
                        dust.shader = GameShaders.Armor.GetSecondaryShader(this.ArmorSetDye(), this);
                    }
                    this.solarCounter = 0;
                }
                else
                {
                    this.solarCounter = num;
                }
            }
            for (int k = this.solarShields; k < 3; k++)
            {
                this.solarShieldPos[k] = Vector2.Zero;
            }
            for (int l = 0; l < this.solarShields; l++)
            {
                this.solarShieldPos[l] += this.solarShieldVel[l];
                Vector2 vector = ((float)this.miscCounter / 100f * 6.2831855f + (float)l * (6.2831855f / (float)this.solarShields)).ToRotationVector2() * 6f;
                vector.X = (float)(this.direction * 20);
                if (this.mount.Active)
                {
                    if (this.mount.Type == 52)
                    {
                        vector.X = (float)(this.direction * 50);
                    }
                    if (this.mount.Type == 54)
                    {
                        vector.X = (float)(this.direction * 54);
                    }
                    if (this.mount.Type == 56 || this.mount.Type == 61)
                    {
                        vector.X = (float)(this.direction * 40);
                    }
                }
                this.solarShieldVel[l] = (vector - this.solarShieldPos[l]) * 0.2f;
            }
            if (this.dashDelay >= 0)
            {
                this.solarDashing = false;
                this.solarDashConsumedFlare = false;
            }
            bool flag = this.solarDashing && this.dashDelay < 0;
            if (this.solarShields > 0 || flag)
            {
                this.dashType = 3;
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.dust, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Player.maxBuffs, Terraria.Dust.NewDust(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.DataStructures.ArmorSetBonuses.Benefits.Solar().