Terraria Decompiled: Terraria.Player.CopyVisuals
CopyVisuals()
void Terraria.Player.CopyVisuals (Player other) inline
Definition at line 53719 of file Player.cs.
        {
            this.skinVariant = other.skinVariant;
            this.direction = other.direction;
            this.selectedItemState = other.selectedItemState;
            this.extraAccessory = other.extraAccessory;
            this.skinColor = other.skinColor;
            this.eyeColor = other.eyeColor;
            this.hair = other.hair;
            this.hairColor = other.hairColor;
            this.shirtColor = other.shirtColor;
            this.underShirtColor = other.underShirtColor;
            this.pantsColor = other.pantsColor;
            this.shoeColor = other.shoeColor;
            this.position = other.position;
            this.velocity = other.velocity;
            this.statLife = other.statLife;
            this.statLifeMax = other.statLifeMax;
            this.statLifeMax2 = other.statLifeMax2;
            this.statMana = other.statMana;
            this.statManaMax = other.statManaMax;
            this.statManaMax2 = other.statManaMax2;
            this.hideMisc = other.hideMisc;
            for (int i = 0; i < 59; i++)
            {
                this.inventory[i] = other.inventory[i].Clone();
                if (i < this.armor.Length)
                {
                    this.armor[i] = other.armor[i].Clone();
                }
                if (i < this.dye.Length)
                {
                    this.dye[i] = other.dye[i].Clone();
                }
                if (i < this.miscEquips.Length)
                {
                    this.miscEquips[i] = other.miscEquips[i].Clone();
                }
                if (i < this.miscDyes.Length)
                {
                    this.miscDyes[i] = other.miscDyes[i].Clone();
                }
                if (i < this.hideVisibleAccessory.Length)
                {
                    this.hideVisibleAccessory[i] = other.hideVisibleAccessory[i];
                }
            }
        }
References Terraria.Player.armor, Terraria.Item.Clone(), Terraria.Entity.direction, Terraria.Player.dye, Terraria.Player.extraAccessory, Terraria.Player.eyeColor, Terraria.Player.hair, Terraria.Player.hairColor, Terraria.Player.hideMisc, Terraria.Player.hideVisibleAccessory, Terraria.Player.inventory, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.Player.pantsColor, Terraria.Entity.position, Terraria.Player.selectedItemState, Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, Terraria.Player.skinVariant, Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statLifeMax2, Terraria.Player.statMana, Terraria.Player.statManaMax, Terraria.Player.statManaMax2, Terraria.Player.underShirtColor, and Terraria.Entity.velocity.
Referenced by Terraria.Main.DrawSuperSpecialProjectiles(), and Terraria.GameContent.Animations.Segments.PlayerSegment.ResetPlayerAnimation().