Terraria Decompiled: Terraria.Player.ApplyWilsonBeard
ApplyWilsonBeard()
void Terraria.Player.ApplyWilsonBeard (Item currentItem) inline private
Definition at line 13566 of file Player.cs.
        {
            this.beardGrowthTimer++;
            if (this.beardGrowthTimer < 43200 || Main.rand.Next(540) != 0)
            {
                return;
            }
            this.beardGrowthTimer = 0;
            short num = 5105;
            if (currentItem.type == 5105)
            {
                num = 5106;
            }
            SoundEngine.PlaySound(SoundID.Item60, base.Center, 0f, 1f);
            currentItem.SetDefaults((int)num, null);
        }
References Terraria.ID.SoundID.Item60, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Item.SetDefaults(), and Terraria.Item.type.