Terraria Decompiled: Terraria.Player.TryReplantingTree
TryReplantingTree()
void Terraria.Player.TryReplantingTree () inline private
Definition at line 45084 of file Player.cs.
        {
            ushort num = 20;
            int num2 = 0;
            TileObject tileObject;
            if (!TileObject.CanPlace(Player.tileTargetX, Player.tileTargetY, (int)num, num2, this.direction, out tileObject, false, null))
            {
                return;
            }
            bool flag = TileObject.Place(tileObject);
            WorldGen.SquareTileFrame(Player.tileTargetX, Player.tileTargetY, true);
            if (!flag)
            {
                return;
            }
            TileObjectData.CallPostPlacementPlayerHook(Player.tileTargetX, Player.tileTargetY, (int)num, num2, this.direction, tileObject.alternate, tileObject);
            if (Main.netMode == 1)
            {
                NetMessage.SendObjectPlacement(-1, Player.tileTargetX, Player.tileTargetY, tileObject.type, tileObject.style, tileObject.alternate, tileObject.random, this.direction);
            }
        }
References Terraria.TileObject.alternate, Terraria.ObjectData.TileObjectData.CallPostPlacementPlayerHook(), Terraria.TileObject.CanPlace(), Terraria.Main.netMode, Terraria.TileObject.Place(), Terraria.TileObject.random, Terraria.NetMessage.SendObjectPlacement(), Terraria.WorldGen.SquareTileFrame(), Terraria.TileObject.style, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, and Terraria.TileObject.type.