Terraria Decompiled: Terraria.Player.ItemCheck_GetMeleeHitboxParticles
ItemCheck_GetMeleeHitboxParticles()
void Terraria.Player.ItemCheck_GetMeleeHitboxParticles (Item sItem, Rectangle heldItemFrame) inline private
Definition at line 44308 of file Player.cs.
        {
            if (sItem.type == 1450 && Main.rand.Next(3) == 0)
            {
                bool flag;
                Rectangle rectangle;
                this.ItemCheck_GetMeleeHitbox(sItem, heldItemFrame, out flag, out rectangle);
                int num = -1;
                float num2 = (float)(rectangle.X + Main.rand.Next(rectangle.Width));
                float num3 = (float)(rectangle.Y + Main.rand.Next(rectangle.Height));
                if (Main.rand.Next(500) == 0)
                {
                    num = Gore.NewGore(new Vector2(num2, num3), default(Vector2), 415, (float)Main.rand.Next(51, 101) * 0.01f);
                }
                else if (Main.rand.Next(250) == 0)
                {
                    num = Gore.NewGore(new Vector2(num2, num3), default(Vector2), 414, (float)Main.rand.Next(51, 101) * 0.01f);
                }
                else if (Main.rand.Next(80) == 0)
                {
                    num = Gore.NewGore(new Vector2(num2, num3), default(Vector2), 413, (float)Main.rand.Next(51, 101) * 0.01f);
                }
                else if (Main.rand.Next(10) == 0)
                {
                    num = Gore.NewGore(new Vector2(num2, num3), default(Vector2), 412, (float)Main.rand.Next(51, 101) * 0.01f);
                }
                else if (Main.rand.Next(3) == 0)
                {
                    num = Gore.NewGore(new Vector2(num2, num3), default(Vector2), 411, (float)Main.rand.Next(51, 101) * 0.01f);
                }
                if (num >= 0)
                {
                    Gore gore = Main.gore[num];
                    gore.velocity.X = gore.velocity.X + (float)(this.direction * 2);
                    Gore gore2 = Main.gore[num];
                    gore2.velocity.Y = gore2.velocity.Y * 0.3f;
                }
            }
            if (sItem.type == 3779)
            {
                Vector2 vector = this.itemLocation + new Vector2((float)(this.direction * 30), -8f);
                Vector2 vector2 = vector - this.position;
                for (float num4 = 0f; num4 < 1f; num4 += 0.2f)
                {
                    Vector2 vector3 = Vector2.Lerp(this.oldPosition + vector2 + new Vector2(0f, this.gfxOffY), vector, num4);
                    Dust dust = Main.dust[Dust.NewDust(vector - Vector2.One * 8f, 16, 16, 27, 0f, -2f, 0, default(Color), 1f)];
                    dust.noGravity = true;
                    dust.position = vector3;
                    dust.velocity = new Vector2(0f, -this.gravDir * 2f);
                    dust.scale = 1.2f;
                    dust.alpha = 200;
                }
            }
        }
References Terraria.Main.dust, Terraria.Main.gore, Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector2.One, Terraria.Main.rand, Terraria.Item.type, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.