Terraria Decompiled: Terraria.Player.FreeUpPetsAndMinions
FreeUpPetsAndMinions()
void Terraria.Player.FreeUpPetsAndMinions (Item sItem) inline private
Definition at line 51080 of file Player.cs.
        {
            if (sItem.shoot == 1093)
            {
                for (int i = 0; i < 1000; i++)
                {
                    if (Main.projectile[i].active && Main.projectile[i].owner == this.whoAmI && Main.projectile[i].minion && Main.projectile[i].type == sItem.shoot)
                    {
                        Main.projectile[i].Kill();
                    }
                }
            }
            if (ProjectileID.Sets.MinionSacrificable[sItem.shoot])
            {
                List<int> list = new List<int>();
                float num = 0f;
                for (int j = 0; j < 1000; j++)
                {
                    if (Main.projectile[j].active && Main.projectile[j].owner == this.whoAmI && Main.projectile[j].minion)
                    {
                        int k;
                        for (k = 0; k < list.Count; k++)
{
                            if (Main.projectile[list[k]].minionSlots > Main.projectile[j].minionSlots)
{
                                list.Insert(k, j);
                                break;
                            }
                        }
                        if (k == list.Count)
{
                            list.Add(j);
                        }
                        num += Main.projectile[j].minionSlots;
                    }
                }
                float num2 = (float)ItemID.Sets.StaffMinionSlotsRequired[sItem.type];
                float num3 = 0f;
                int num4 = 388;
                int num5 = -1;
                for (int l = 0; l < list.Count; l++)
                {
                    int type = Main.projectile[list[l]].type;
                    if (type == 626)
                    {
                        list.RemoveAt(l);
                        l--;
                    }
                    if (type == 627)
                    {
                        if (Main.projectile[(int)Main.projectile[list[l]].localAI[1]].type == 628)
{
                            num5 = list[l];
                        }
                        list.RemoveAt(l);
                        l--;
                    }
                }
                if (num5 != -1)
                {
                    list.Add(num5);
                    list.Add(Projectile.GetByUUID(Main.projectile[num5].owner, Main.projectile[num5].ai[0]));
                }
                int num6 = 0;
                while (num6 < list.Count && num - num3 > (float)this.maxMinions - num2)
                {
                    int type2 = Main.projectile[list[num6]].type;
                    if (type2 != num4 && type2 != 625 && type2 != 628 && type2 != 623)
                    {
                        if (type2 == 388 && num4 == 387)
{
                            num4 = 388;
                        }
                        if (type2 == 387 && num4 == 388)
{
                            num4 = 387;
                        }
                        num3 += Main.projectile[list[num6]].minionSlots;
                        if (type2 == 626 || type2 == 627)
{
                            Projectile projectile = Main.projectile[list[num6]];
                            int byUUID = Projectile.GetByUUID(projectile.owner, projectile.ai[0]);
                            if (Main.projectile.IndexInRange(byUUID))
{
                                Projectile projectile2 = Main.projectile[byUUID];
                                if (projectile2.type != 625)
{
                                    projectile2.localAI[1] = projectile.localAI[1];
                                }
                                projectile2 = Main.projectile[(int)projectile.localAI[1]];
                                projectile2.ai[0] = projectile.ai[0];
                                projectile2.ai[1] = 1f;
                                projectile2.netUpdate = true;
                            }
                        }
                        Main.projectile[list[num6]].Kill();
                    }
                    num6++;
                }
                list.Clear();
                if (num + num2 >= 9f)
                {
                    AchievementsHelper.HandleSpecialEvent(this, 6);
                    return;
                }
            }
            else
            {
                for (int m = 0; m < 1000; m++)
                {
                    Projectile projectile3 = Main.projectile[m];
                    if (projectile3.active && projectile3.owner == this.whoAmI)
                    {
                        if (projectile3.type == sItem.shoot)
{
                            projectile3.Kill();
                        }
                        if (sItem.shoot == 72 && (projectile3.type == 86 || projectile3.type == 87))
{
                            projectile3.Kill();
                        }
                        if (sItem.type == 5131 && (projectile3.type == 881 || projectile3.type == 934))
{
                            projectile3.Kill();
                        }
                    }
                }
            }
        }
References Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.Projectile.GetByUUID(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), int, Terraria.Projectile.Kill(), System.list, Terraria.Projectile.localAI, Terraria.Projectile.minion, Terraria.ID.ProjectileID.Sets.MinionSacrificable, Terraria.Projectile.minionSlots, Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.Item.shoot, Terraria.ID.ItemID.Sets.StaffMinionSlotsRequired, Terraria.Item.type, and Terraria.Projectile.type.