Terraria Decompiled: Terraria.Player.ItemCheck_UseWiringTools
ItemCheck_UseWiringTools()
void Terraria.Player.ItemCheck_UseWiringTools (Item sItem) inline private
Definition at line 46121 of file Player.cs.
        {
            if ((sItem.type == 509 || sItem.type == 510 || sItem.type == 849 || sItem.type == 850 || sItem.type == 851 || sItem.type == 3612 || sItem.type == 3620 || sItem.type == 3625) && this.IsInTileInteractionRange(Player.tileTargetX, Player.tileTargetY, TileReachCheckSettings.Simple, sItem.tileBoost + this.blockRange))
            {
                if (!Main.GamepadDisableCursorItemIcon)
                {
                    this.cursorItemIconEnabled = true;
                    Main.ItemIconCacheUpdate(sItem.type);
                }
                if (this.CanDoWireStuffHere(Player.tileTargetX, Player.tileTargetY) && this.itemAnimation > 0 && this.ItemTimeIsZero && this.controlUseItem)
                {
                    int num = Player.tileTargetX;
                    int num2 = Player.tileTargetY;
                    if (sItem.type == 509)
                    {
                        int num3 = -1;
                        for (int i = 0; i < 58; i++)
{
                            if (this.inventory[i].stack > 0 && this.inventory[i].type == 530)
{
                                num3 = i;
                                break;
                            }
                        }
                        if (num3 >= 0 && WorldGen.PlaceWire(num, num2))
{
                            this.inventory[num3].stack--;
                            if (this.inventory[num3].stack <= 0)
{
                                this.inventory[num3].SetDefaults(0, null);
                            }
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 5, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                    }
                    else if (sItem.type == 850)
                    {
                        int num4 = -1;
                        for (int j = 0; j < 58; j++)
{
                            if (this.inventory[j].stack > 0 && this.inventory[j].type == 530)
{
                                num4 = j;
                                break;
                            }
                        }
                        if (num4 >= 0 && WorldGen.PlaceWire2(num, num2))
{
                            this.inventory[num4].stack--;
                            if (this.inventory[num4].stack <= 0)
{
                                this.inventory[num4].SetDefaults(0, null);
                            }
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 10, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                    }
                    if (sItem.type == 851)
                    {
                        int num5 = -1;
                        for (int k = 0; k < 58; k++)
{
                            if (this.inventory[k].stack > 0 && this.inventory[k].type == 530)
{
                                num5 = k;
                                break;
                            }
                        }
                        if (num5 >= 0 && WorldGen.PlaceWire3(num, num2))
{
                            this.inventory[num5].stack--;
                            if (this.inventory[num5].stack <= 0)
{
                                this.inventory[num5].SetDefaults(0, null);
                            }
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 12, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                    }
                    if (sItem.type == 3612)
                    {
                        int num6 = -1;
                        for (int l = 0; l < 58; l++)
{
                            if (this.inventory[l].stack > 0 && this.inventory[l].type == 530)
{
                                num6 = l;
                                break;
                            }
                        }
                        if (num6 >= 0 && WorldGen.PlaceWire4(num, num2))
{
                            this.inventory[num6].stack--;
                            if (this.inventory[num6].stack <= 0)
{
                                this.inventory[num6].SetDefaults(0, null);
                            }
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 16, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                    }
                    else if (sItem.type == 510)
                    {
                        if (WorldGen.KillActuator(num, num2))
{
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 9, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                        else if (WorldGen.KillWire4(num, num2))
{
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 17, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                        else if (WorldGen.KillWire3(num, num2))
{
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 13, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                        else if (WorldGen.KillWire2(num, num2))
{
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 11, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                        else if (WorldGen.KillWire(num, num2))
{
                            this.ApplyItemTime(sItem);
                            NetMessage.SendData(17, -1, -1, null, 6, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                        }
                    }
                    else if (sItem.type == 849 && sItem.stack > 0 && WorldGen.PlaceActuator(num, num2))
                    {
                        this.ApplyItemTime(sItem);
                        NetMessage.SendData(17, -1, -1, null, 8, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                    }
                    if (sItem.type == 3620)
                    {
                        Tile tile = Main.tile[num, num2];
                        if (tile != null && tile.actuator())
{
                            bool flag = tile.inActive();
                            if ((!this.ActuationRodLock || this.ActuationRodLockSetting == tile.inActive()) && Wiring.Actuate(num, num2) && flag != tile.inActive())
{
                                this.ActuationRodLock = true;
                                this.ActuationRodLockSetting = !tile.inActive();
                                this.ApplyItemTime(sItem);
                                NetMessage.SendData(17, -1, -1, null, 19, (float)Player.tileTargetX, (float)Player.tileTargetY, 0f, 0, 0, 0);
                            }
                        }
                    }
                    if (sItem.type == 3625)
                    {
                        Point point = new Point(Player.tileTargetX, Player.tileTargetY);
                        this.ApplyItemTime(sItem);
                        WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
                        WiresUI.Settings.ToolMode &= ~WiresUI.Settings.MultiToolMode.Actuator;
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(109, -1, -1, null, point.X, (float)point.Y, (float)point.X, (float)point.Y, (int)WiresUI.Settings.ToolMode, 0, 0);
                        }
                        else
{
                            Wiring.MassWireOperation(point, point, this);
                        }
                        WiresUI.Settings.ToolMode = toolMode;
                    }
                }
            }
        }
References Terraria.Wiring.Actuate(), Terraria.Tile.actuator(), Terraria.Main.GamepadDisableCursorItemIcon, Terraria.Tile.inActive(), Terraria.Main.ItemIconCacheUpdate(), Terraria.WorldGen.KillActuator(), Terraria.WorldGen.KillWire(), Terraria.WorldGen.KillWire2(), Terraria.WorldGen.KillWire3(), Terraria.WorldGen.KillWire4(), Terraria.Wiring.MassWireOperation(), Terraria.Main.netMode, Terraria.WorldGen.PlaceActuator(), Terraria.WorldGen.PlaceWire(), Terraria.WorldGen.PlaceWire2(), Terraria.WorldGen.PlaceWire3(), Terraria.WorldGen.PlaceWire4(), Terraria.NetMessage.SendData(), Terraria.DataStructures.TileReachCheckSettings.Simple, System.stack, Terraria.Item.stack, Terraria.Main.tile, Terraria.Item.tileBoost, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.Item.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.