Terraria Decompiled: Terraria.Player.ToggleInv
ToggleInv()
void Terraria.Player.ToggleInv () inline
Definition at line 2215 of file Player.cs.
        {
            bool grappleAndInteractAreShared = PlayerInput.GrappleAndInteractAreShared;
            if (Main.mapFullscreen)
            {
                Main.mapFullscreen = false;
                this.releaseInventory = false;
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                if (PlayerInput.GrappleAndInteractAreShared)
                {
                    this.LockGamepadTileInteractions();
                }
            }
            else if (PlayerInput.InBuildingMode)
            {
                PlayerInput.ExitBuildingMode(false);
            }
            else if (Main.ingameOptionsWindow)
            {
                if (PlayerInput.UsingGamepadUI && UILinkPointNavigator.CurrentPage == 1002)
                {
                    UILinkPointNavigator.ChangePage(1001);
                }
                else
                {
                    IngameOptions.Close();
                }
            }
            else if (Main.inFancyUI)
            {
                IngameFancyUI.Close(false);
            }
            else if (CaptureManager.Instance.Active)
            {
                CaptureManager.Instance.Active = false;
            }
            else if (this.talkNPC >= 0)
            {
                this.SetTalkNPC(-1);
                Main.npcChatCornerItem = 0;
                Main.npcChatText = "";
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                if (PlayerInput.UsingGamepad)
                {
                    Main.npcChatRelease = false;
                }
                Main.playerInventory = false;
            }
            else if (this.sign >= 0)
            {
                this.CloseSign(false);
            }
            else if (Main.clothesWindow)
            {
                Main.CancelClothesWindow(false);
            }
            else if (NewCraftingUI.Visible)
            {
                NewCraftingUI.Close(false, false);
            }
            else if (!Main.playerInventory)
            {
                Player.OpenInventory(false);
            }
            else
            {
                Main.playerInventory = false;
                CraftingUI.ClearHacks();
                if (this.channel && Main.mouseItem != null && !Main.mouseItem.IsAir)
                {
                    this.channel = false;
                }
                this.tileEntityAnchor.Clear();
                if (!PlayerInput.UsingGamepad)
                {
                    Main.ResetInventoryState();
                }
                else
                {
                    PlayerInput.NavigatorUnCachePosition();
                    Main.GamepadCursorAlpha = 0f;
                    Player.BlockInteractionWithProjectiles = 3;
                    if (PlayerInput.GrappleAndInteractAreShared)
                    {
                        this.LockGamepadTileInteractions();
                    }
                }
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                if (ItemSlot.Options.HighlightNewItems)
                {
                    Item[] array = this.inventory;
                    for (int i = 0; i < array.Length; i++)
                    {
                        array[i].newAndShiny = false;
                    }
                }
                if (PlayerInput.UsingGamepad)
                {
                    Main.npcChatRelease = false;
                    this.tileInteractionHappened = true;
                    this.releaseInventory = false;
                    Main.mouseRight = true;
                }
            }
            if (grappleAndInteractAreShared)
            {
                this.GamepadEnableGrappleCooldown();
            }
        }
References Terraria.Graphics.Capture.CaptureManager.Active, System.array, Terraria.Main.CancelClothesWindow(), Terraria.UI.Gamepad.UILinkPointNavigator.ChangePage(), Terraria.Player.channel, Terraria.DataStructures.PlayerInteractionAnchor.Clear(), Terraria.UI.CraftingUI.ClearHacks(), Terraria.IngameOptions.Close(), Terraria.UI.IngameFancyUI.Close(), Terraria.GameContent.UI.NewCraftingUI.Close(), Terraria.Player.CloseSign(), Terraria.Main.clothesWindow, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPage, Terraria.GameInput.PlayerInput.ExitBuildingMode(), Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.GameInput.PlayerInput.GrappleAndInteractAreShared, Terraria.UI.ItemSlot.Options.HighlightNewItems, Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.Main.inFancyUI, Terraria.Main.ingameOptionsWindow, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Player.inventory, Terraria.Item.IsAir, Terraria.Player.LockGamepadTileInteractions(), Terraria.Main.mapFullscreen, Terraria.Main.mouseItem, Terraria.GameInput.PlayerInput.NavigatorUnCachePosition(), Terraria.Item.newAndShiny, Terraria.Player.OpenInventory(), Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.ResetInventoryState(), Terraria.Player.SetTalkNPC(), Terraria.Player.sign, Terraria.Player.talkNPC, Terraria.Player.tileEntityAnchor, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.GameInput.PlayerInput.UsingGamepadUI, and Terraria.GameContent.UI.NewCraftingUI.Visible.
Referenced by Terraria.Main.DoUpdate_WhilePaused().