Terraria Decompiled: Terraria.Player.WOFTongue
WOFTongue()
void Terraria.Player.WOFTongue () inline
Definition at line 20679 of file Player.cs.
        {
            if (Main.wofNPCIndex >= 0 && Main.npc[Main.wofNPCIndex].active)
            {
                float num = Main.npc[Main.wofNPCIndex].position.X + 40f;
                if (Main.npc[Main.wofNPCIndex].direction > 0)
                {
                    num -= 96f;
                }
                if (this.position.X + (float)this.width > num && this.position.X < num + 140f && this.gross)
                {
                    this.noKnockback = false;
                    int attackDamage_ScaledByDifficulty = Main.npc[Main.wofNPCIndex].GetAttackDamage_ScaledByDifficulty(50f);
                    this.Hurt(PlayerDeathReason.LegacyDefault(), attackDamage_ScaledByDifficulty, Main.npc[Main.wofNPCIndex].direction, false, false, false, -1, true);
                }
                if (!this.gross && this.position.Y > (float)((Main.maxTilesY - 250) * 16) && this.position.X > num - (float)Main.MaxWorldViewSize.X && this.position.X < num + (float)Main.MaxWorldViewSize.X)
                {
                    this.AddBuff(37, 10, false);
                    SoundEngine.PlaySound(4, (int)Main.npc[Main.wofNPCIndex].position.X, (int)Main.npc[Main.wofNPCIndex].position.Y, 10, 1f, 0f);
                }
                if (this.gross)
                {
                    if (this.position.Y < (float)(Main.UnderworldLayer * 16))
                    {
                        this.AddBuff(38, 10, false);
                    }
                    if (Main.npc[Main.wofNPCIndex].direction < 0)
                    {
                        if (this.position.X + (float)(this.width / 2) > Main.npc[Main.wofNPCIndex].position.X + (float)(Main.npc[Main.wofNPCIndex].width / 2) + 40f)
{
                            this.AddBuff(38, 10, false);
                        }
                    }
                    else if (this.position.X + (float)(this.width / 2) < Main.npc[Main.wofNPCIndex].position.X + (float)(Main.npc[Main.wofNPCIndex].width / 2) - 40f)
                    {
                        this.AddBuff(38, 10, false);
                    }
                }
                if (this.tongued)
                {
                    this.controlHook = false;
                    this.controlUseItem = false;
                    for (int i = 0; i < 1000; i++)
                    {
                        if (Main.projectile[i].active && Main.projectile[i].owner == Main.myPlayer && Main.projectile[i].aiStyle == 7)
{
                            Main.projectile[i].Kill();
                        }
                    }
                    Vector2 center = base.Center;
                    float num2 = Main.npc[Main.wofNPCIndex].position.X + (float)(Main.npc[Main.wofNPCIndex].width / 2) - center.X;
                    float num3 = Main.npc[Main.wofNPCIndex].position.Y + (float)(Main.npc[Main.wofNPCIndex].height / 2) - center.Y;
                    if ((float)Math.Sqrt((double)(num2 * num2 + num3 * num3)) > 3000f)
                    {
                        this.KillMe(PlayerDeathReason.ByOther(11), 1000.0, 0, false);
                        return;
                    }
                    if (Main.npc[Main.wofNPCIndex].position.X < 608f || Main.npc[Main.wofNPCIndex].position.X > (float)((Main.maxTilesX - 38) * 16))
                    {
                        this.KillMe(PlayerDeathReason.ByOther(12), 1000.0, 0, false);
                    }
                }
            }
        }
References Terraria.NPC.active, Terraria.Projectile.active, Terraria.Projectile.aiStyle, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Entity.direction, Terraria.NPC.GetAttackDamage_ScaledByDifficulty(), Terraria.Entity.height, Terraria.Projectile.Kill(), Terraria.DataStructures.PlayerDeathReason.LegacyDefault(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.MaxWorldViewSize, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, System.Math.Sqrt(), Terraria.Main.UnderworldLayer, Terraria.Entity.width, Terraria.Main.wofNPCIndex, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.