Terraria Decompiled: Terraria.Player.SetTalkNPC
SetTalkNPC()
void Terraria.Player.SetTalkNPC (int npcIndex) inline
Definition at line 1187 of file Player.cs.
        {
            this.talkNPC = npcIndex;
            if (Main.netMode != 1 && npcIndex >= 0 && npcIndex < Main.maxNPCs)
            {
                Main.BestiaryTracker.Chats.RegisterChatStartWith(Main.npc[npcIndex]);
            }
            if (this.talkNPC == -1)
            {
                this.currentShoppingSettings = ShoppingSettings.NotInShop;
            }
            else
            {
                this.currentShoppingSettings = Main.ShopHelper.GetShoppingSettings(this, Main.npc[this.talkNPC]);
            }
            if (this.currentShoppingSettings.PriceAdjustment <= 0.82f)
            {
                AchievementsHelper.HandleSpecialEvent(this, 20);
            }
            if (this.whoAmI == Main.myPlayer)
            {
                Main.npcChatPortrait = null;
                NPCID.Sets.NPCPortraitProvider npcportraitProvider;
                if (npcIndex >= 0 && npcIndex < Main.maxNPCs && NPCID.Sets.NPCPortraits.TryGetValue(Main.npc[npcIndex].type, out npcportraitProvider))
                {
                    Main.npcChatPortrait = npcportraitProvider;
                    Main.DoNPCPortraitHop();
                }
            }
        }
References Terraria.Main.BestiaryTracker, Terraria.Player.currentShoppingSettings, Terraria.Main.DoNPCPortraitHop(), Terraria.GameContent.ShopHelper.GetShoppingSettings(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.ShoppingSettings.NotInShop, Terraria.Main.npc, Terraria.ID.NPCID.Sets.NPCPortraits, Terraria.ShoppingSettings.PriceAdjustment, Terraria.Main.ShopHelper, Terraria.Player.talkNPC, Terraria.NPC.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.NPC.AI_000_TransformBoundNPC(), Terraria.Main.BuyHairWindow(), Terraria.Main.CancelHairWindow(), Terraria.UI.IngameUIWindows.CloseAll(), Terraria.Main.CloseNPCChatOrSign(), Terraria.Main.DrawBestiaryIcon(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.Main.DrawInventory(), Terraria.Main.HoverOverNPCs(), Terraria.GameContent.UI.NewCraftingUI.OpenCloseFilter(), Terraria.DataStructures.TileEntity.SetInteractionAnchor(), Terraria.Player.ToggleInv(), Terraria.Main.TryInteractingWithMoneyTrough(), and Terraria.Main.TryInteractingWithVoidLens().