Terraria Decompiled: Terraria.Player.IsItemSlotUnlockedAndUsable
IsItemSlotUnlockedAndUsable()
bool Terraria.Player.IsItemSlotUnlockedAndUsable (int slot) inline
Definition at line 10173 of file Player.cs.
        {
            if (slot <= 9)
            {
                if (slot == 8)
                {
                    goto IL_001C;
                }
                if (slot == 9)
                {
                    goto IL_0038;
                }
            }
            else
            {
                if (slot == 18)
                {
                    goto IL_001C;
                }
                if (slot == 19)
                {
                    goto IL_0038;
                }
            }
            return true;
            IL_001C:
            bool flag = this.extraAccessory;
            if (!Main.expertMode && !Main.gameMenu)
            {
                flag = false;
            }
            return flag;
            IL_0038:
            bool flag2 = true;
            if (!Main.masterMode && !Main.gameMenu)
            {
                flag2 = false;
            }
            return flag2;
        }
References Terraria.Main.expertMode, Terraria.Main.gameMenu, and Terraria.Main.masterMode.
Referenced by Terraria.UI.ItemSlot.ArmorSwap(), Terraria.Player.CanDemonHeartAccessoryBeShown(), Terraria.Player.CanMasterModeAccessoryBeShown(), Terraria.Main.DrawInventory(), Terraria.UI.ItemSlot.DyeSwap(), Terraria.UI.ItemSlot.GetDimSlotForMouseItem(), Terraria.GameContent.Achievements.AchievementsHelper.HandleOnEquip(), Terraria.GameContent.Achievements.AchievementsHelper.OnPlayerEnteredWorld(), and Terraria.UI.ItemSlot.ShouldHighlightSlotForMouseItem().