Terraria Decompiled: Terraria.Player.GetItemExpectedPrice
GetItemExpectedPrice()
void Terraria.Player.GetItemExpectedPrice (Item item, out long calcForSelling, out long calcForBuying) inline
Definition at line 34150 of file Player.cs.
        {
            if (item.shopSpecialCurrency != -1)
            {
                CustomCurrencyManager.GetPrices(item, out calcForSelling, out calcForBuying);
                return;
            }
            int storeValue = item.GetStoreValue();
            calcForSelling = (long)storeValue;
            calcForBuying = (long)storeValue;
            if (this.discountAvailable)
            {
                if (!item.buyOnce)
                {
                    calcForBuying = (long)((int)((float)calcForBuying * 0.8f));
                }
                if (item.isAShopItem)
                {
                    calcForSelling = calcForBuying;
                }
            }
            if (item.buyOnce)
            {
                calcForBuying = (long)((int)Math.Round((double)((float)calcForBuying / this.currentShoppingSettings.PriceAdjustment)));
                calcForSelling = (long)((int)Math.Round((double)((float)calcForSelling / this.currentShoppingSettings.PriceAdjustment)));
            }
            else
            {
                calcForBuying = (long)((int)Math.Round((double)((float)calcForBuying * this.currentShoppingSettings.PriceAdjustment)));
                calcForSelling = (long)((int)Math.Round((double)((float)calcForSelling / this.currentShoppingSettings.PriceAdjustment)));
            }
            if (item.buyOnce)
            {
                calcForBuying /= 5L;
                if (storeValue != 0 && calcForBuying < 1L)
                {
                    calcForBuying = 1L;
                }
            }
        }
References Terraria.GameContent.UI.CustomCurrencyManager.GetPrices(), System.item, System.L, long, and System.Math.Round().
Referenced by Terraria.UI.ItemSlot.HandleShopSlot(), and Terraria.Main.MouseText_DrawItemTooltip_AddShopLines().