Terraria Decompiled: Terraria.Player.GetAnglerReward_MainReward
GetAnglerReward_MainReward()
void Terraria.Player.GetAnglerReward_MainReward (IEntitySource source, int questsDone, float rarityReduction, int questItemType) inline private
Definition at line 55665 of file Player.cs.
        {
            Item item = new Item();
            item.type = 0;
            if (questsDone == 5)
            {
                item.SetDefaults(2428, null);
            }
            else if (questsDone == 10)
            {
                item.SetDefaults(2367, null);
            }
            else if (questsDone == 15)
            {
                item.SetDefaults(2368, null);
            }
            else if (questsDone == 20)
            {
                item.SetDefaults(2369, null);
            }
            else if (questsDone == 25)
            {
                item.SetDefaults(3031, null);
            }
            else if (questsDone == 30)
            {
                item.SetDefaults(2294, null);
            }
            else if (questItemType == 2451 && Main.hardMode)
            {
                item.SetDefaults((Main.rand.Next(2) == 0) ? 5303 : 5302, null);
            }
            else if (questItemType == 2451 && !Main.hardMode && Main.rand.Next(2) == 0)
            {
                item.SetDefaults((Main.rand.Next(2) == 0) ? 5303 : 5302, null);
            }
            else
            {
                List<int> list = new List<int> { 2373, 2374, 2375, 3120, 3037, 3096, 5139 };
                float num = 1f;
                for (int i = 0; i < 3; i++)
                {
                    num *= 1f - 1f / (float)((int)(40f * rarityReduction));
                }
                for (int j = 0; j < 3; j++)
                {
                    num *= 1f - 1f / (float)((int)(30f * rarityReduction));
                }
                num *= 1f - 1f / (float)((int)(25f * rarityReduction));
                float num2 = 1f - num;
                num2 *= 0.8f;
                bool flag;
                int num3;
                if (questsDone > 75 && Main.rand.Next((int)(250f * rarityReduction)) == 0)
                {
                    item.SetDefaults(2294, null);
                }
                else if (Main.hardMode && questsDone > 25 && Main.rand.Next((int)(100f * rarityReduction)) == 0)
                {
                    item.SetDefaults(2422, null);
                }
                else if (Main.hardMode && questsDone > 10 && Main.rand.Next((int)(70f * rarityReduction)) == 0)
                {
                    item.SetDefaults(2494, null);
                }
                else if (questsDone > 10 && Main.rand.Next((int)(70f * rarityReduction)) == 0)
                {
                    item.SetDefaults(3031, null);
                }
                else if (questsDone > 10 && Main.rand.Next((int)(70f * rarityReduction)) == 0)
                {
                    item.SetDefaults(3032, null);
                }
                else if (Main.rand.Next((int)(80f * rarityReduction)) == 0)
                {
                    item.SetDefaults(3183, null);
                }
                else if (Main.rand.Next((int)(60f * rarityReduction)) == 0)
                {
                    item.SetDefaults(2360, null);
                }
                else if (Main.rand.Next((int)(60f * rarityReduction)) == 0)
                {
                    item.SetDefaults(4067, null);
                }
                else if (Main.rand.Next((int)(80f * rarityReduction)) == 0)
                {
                    item.SetDefaults(2417, null);
                }
                else if (Main.rand.Next((int)(80f * rarityReduction)) == 0)
                {
                    item.SetDefaults(2498, null);
                }
                else if (this.DropAnglerAccByMissing(list, num2, out flag, out num3))
                {
                    item.SetDefaults(num3, null);
                }
                else if (!flag && Main.rand.NextDouble() < (double)num2)
                {
                    int num4 = Utils.SelectRandom<int>(Main.rand, list.ToArray());
                    item.SetDefaults(num4, null);
                }
                else
                {
                    int num5 = Main.rand.Next(3);
                    if (num5 == 0)
                    {
                        item.SetDefaults(2354, null);
                        item.stack = Main.rand.Next(2, 6);
                    }
                    else if (num5 == 1)
                    {
                        item.SetDefaults(2355, null);
                        item.stack = Main.rand.Next(2, 6);
                    }
                    else
                    {
                        item.SetDefaults(2356, null);
                        item.stack = Main.rand.Next(2, 6);
                    }
                }
            }
            this.QuickSpawnItem(source, item, GetItemSettings.GiftRecieved);
            if (item.type == 2417)
            {
                Item item2 = new Item();
                Item item3 = new Item();
                item2.SetDefaults(2418, null);
                this.QuickSpawnItem(source, item2, GetItemSettings.GiftRecieved);
                item3.SetDefaults(2419, null);
                this.QuickSpawnItem(source, item3, GetItemSettings.GiftRecieved);
                return;
            }
            if (item.type == 2498)
            {
                Item item4 = new Item();
                Item item5 = new Item();
                item4.SetDefaults(2499, null);
                this.QuickSpawnItem(source, item4, GetItemSettings.GiftRecieved);
                item5.SetDefaults(2500, null);
                this.QuickSpawnItem(source, item5, GetItemSettings.GiftRecieved);
            }
        }
References Terraria.GetItemSettings.GiftRecieved, Terraria.Main.hardMode, System.item, System.list, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Main.rand, Terraria.Item.SetDefaults(), and System.source.