Terraria Decompiled: Terraria.Player.UpdateNetOffset
UpdateNetOffset()
void Terraria.Player.UpdateNetOffset (bool fallThrough, bool ignorePlats) inline private
Definition at line 27114 of file Player.cs.
        {
            if (DebugOptions.FakeNetOffset != Vector2.Zero)
            {
                this.netOffset = DebugOptions.FakeNetOffset;
                return;
            }
            float num = 0.1f;
            float num2 = 2f;
            float num3 = this.netOffset.Length();
            if (num3 < num2)
            {
                this.netOffset = Vector2.Zero;
                return;
            }
            if (!this.ghost)
            {
                Vector2 vector = this.TileCollision(this.position + this.netOffset, this.velocity, fallThrough, ignorePlats);
                if (vector != this.velocity)
                {
                    Vector2 vector2 = this.velocity - vector;
                    float num4 = Vector2.Dot(vector2, this.netOffset);
                    if (num4 >= 1f)
                    {
                        float num5 = vector2.LengthSquared() * num3 / num4;
                        num2 = Math.Max(num2, num5 * 1.0001f);
                    }
                }
            }
            float num6 = Math.Max(num2, num3 * num);
            this.netOffset = this.netOffset.MoveTowards(Vector2.Zero, num6);
            if (this.netOffset != Vector2.Zero && DebugOptions.ShowNetOffsetDust)
            {
                Dust.QuickDust(this.position + this.netOffset, Color.Green).scale = 0.5f;
            }
        }
References Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Testing.DebugOptions.FakeNetOffset, Microsoft.Xna.Framework.Color.Green, Microsoft.Xna.Framework.Vector2.LengthSquared(), System.Math.Max(), Terraria.Dust.QuickDust(), Terraria.Dust.scale, Terraria.Testing.DebugOptions.ShowNetOffsetDust, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Player.Ghost().