Terraria Decompiled: Terraria.Player.AddBuff
AddBuff()
void Terraria.Player.AddBuff (int type, int time, bool fromNetPvP = false) inline
Definition at line 2537 of file Player.cs.
        {
            if (this.buffImmune[type])
            {
                return;
            }
            if (Main.netMode == 1 && Main.myPlayer != this.whoAmI)
            {
                if (Main.pvpBuff[type])
                {
                    NetMessage.SendData(55, -1, -1, null, this.whoAmI, (float)type, (float)time, 0f, 0, 0, 0);
                }
                return;
            }
            if (BuffID.Sets.IsFedState[type])
            {
                for (int i = 0; i < Player.maxBuffs; i++)
                {
                    if (BuffID.Sets.IsFedState[this.buffType[i]])
                    {
                        this.DelBuff(i);
                    }
                }
            }
            if (!fromNetPvP)
            {
                time = this.AddBuff_DetermineBuffTimeToAdd(type, time);
            }
            if (this.AddBuff_TryUpdatingExistingBuffTime(type, time))
            {
                return;
            }
            this.AddBuff_RemoveOldPetBuffsOfMatchingType(type);
            this.AddBuff_RemoveOldMeleeBuffsOfMatchingType(type);
            this.AddBuff_ActuallyTryToAddTheBuff(type, time);
        }
References Terraria.Player.AddBuff_ActuallyTryToAddTheBuff(), Terraria.Player.AddBuff_DetermineBuffTimeToAdd(), Terraria.Player.AddBuff_RemoveOldMeleeBuffsOfMatchingType(), Terraria.Player.AddBuff_RemoveOldPetBuffsOfMatchingType(), Terraria.Player.AddBuff_TryUpdatingExistingBuffTime(), Terraria.Player.buffImmune, Terraria.Player.DelBuff(), Terraria.ID.BuffID.Sets.IsFedState, Terraria.Player.maxBuffs, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.pvpBuff, Terraria.NetMessage.SendData(), and Terraria.Entity.whoAmI.
Referenced by Terraria.GameContent.Items.WhipTagEffect.AddTheBuff(), Terraria.NPC.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.NPC.AI_123_Deerclops(), Terraria.Projectile.ApplyBuffTo(), Terraria.Player.ApplyEquipFunctional(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Chlorophyte(), Terraria.DataStructures.ArmorSetBonuses.Benefits.ChlorophyteMelee(), Terraria.DataStructures.ArmorSetBonuses.Benefits.ChlorophyteSummon(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Player.OnHit(), Terraria.Player.QuickBuff(), Terraria.Player.QuickBuff_UseItemForBuff(), Terraria.Player.QuickHeal(), Terraria.Mount.SetMount(), Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty(), Terraria.Player.StatusToPlayerPvP(), Terraria.DataStructures.MinionSpawnFromInventoryItem.TryRespawn(), and Terraria.Player.UpdateBuffs().