Terraria Decompiled: Terraria.Player.BordersMovement
BordersMovement()
void Terraria.Player.BordersMovement () inline
Definition at line 22525 of file Player.cs.
        {
            if (DebugOptions.noLimits)
            {
                return;
            }
            int num = 640;
            float num2 = Main.leftWorld + (float)num;
            if (this.position.X < num2)
            {
                Main.cameraX = 0f;
                this.position.X = num2;
                this.velocity.X = 0f;
            }
            float num3 = Main.rightWorld - (float)num - (float)this.width;
            if (this.position.X > num3)
            {
                Main.cameraX = 0f;
                this.position.X = num3;
                this.velocity.X = 0f;
            }
            if (this.position.Y < Main.topWorld + (float)num)
            {
                Main.cameraY = 0f;
                if (Main.remixWorld || this.forcedGravity > 0)
                {
                    if (this.position.Y < Main.topWorld + (float)num - (float)this.height && !this.dead)
                    {
                        this.KillMe(PlayerDeathReason.ByOther(19), 10.0, 0, false);
                        if (this.whoAmI == Main.myPlayer)
{
                            AchievementsHelper.NotifyProgressionEvent(44);
                        }
                    }
                    int num4 = num / 2;
                    if (this.position.Y < Main.topWorld + (float)num4)
                    {
                        this.position.Y = Main.topWorld + (float)num4;
                        if (this.velocity.Y < 0f)
{
                            this.velocity.Y = 0f;
                        }
                        this.gravDir = 1f;
                    }
                }
                else
                {
                    this.position.Y = Main.topWorld + (float)num;
                    if (this.velocity.Y < 0.11f)
                    {
                        this.velocity.Y = 0.11f;
                    }
                    this.gravDir = 1f;
                }
                AchievementsHelper.HandleSpecialEvent(this, 11);
            }
            if (this.position.Y > Main.bottomWorld - (float)num)
            {
                if (!this.dead)
                {
                    this.KillMe(PlayerDeathReason.ByOther(21), 10.0, 0, false);
                }
                Main.cameraY = 0f;
                this.position.Y = Main.bottomWorld - (float)num;
                this.velocity.Y = 0f;
            }
            bool flag = false;
            if (this.creativeGodMode)
            {
                flag = true;
            }
            if (flag && this.position.Y > Main.bottomWorld - (float)num - (float)this.height)
            {
                Main.cameraY = 0f;
                this.position.Y = Main.bottomWorld - (float)num - (float)this.height;
                this.velocity.Y = 0f;
            }
            if (this.position.Y > Main.bottomWorld - (float)num - 118f - (float)this.height)
            {
                AchievementsHelper.HandleSpecialEvent(this, 10);
            }
        }
References Terraria.Main.bottomWorld, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Main.myPlayer, Terraria.Testing.DebugOptions.noLimits, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.remixWorld, and Terraria.Main.topWorld.