Terraria Decompiled: Terraria.Player.ItemCheck_UseBossSpawners
ItemCheck_UseBossSpawners()
void Terraria.Player.ItemCheck_UseBossSpawners (int onWhichPlayer, Item sItem) inline private
Definition at line 42866 of file Player.cs.
        {
            if (this.ItemTimeIsZero && this.itemAnimation > 0 && (sItem.type == 43 || sItem.type == 70 || sItem.type == 544 || sItem.type == 556 || sItem.type == 557 || sItem.type == 560 || sItem.type == 1133 || sItem.type == 1331 || sItem.type == 4988 || sItem.type == 5120 || sItem.type == 5334) && this.SummonItemCheck(sItem))
            {
                if (sItem.type == 560)
                {
                    this.ApplyItemTime(sItem);
                    SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                    if (Main.netMode != 1)
                    {
                        NPC.SpawnOnPlayer(onWhichPlayer, 50, 0f, 0f, 0f, 0f);
                        return;
                    }
                    NetMessage.SendData(61, -1, -1, null, this.whoAmI, 50f, 0f, 0f, 0, 0, 0);
                    return;
                }
                else if (sItem.type == 43)
                {
                    if (!Main.IsItDay())
                    {
                        this.ApplyItemTime(sItem);
                        SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                        if (Main.netMode != 1)
{
                            NPC.SpawnOnPlayer(onWhichPlayer, 4, 0f, 0f, 0f, 0f);
                        }
                        else
{
                            NetMessage.SendData(61, -1, -1, null, this.whoAmI, 4f, 0f, 0f, 0, 0, 0);
                        }
                        WorldGen.spawnEye = false;
                        return;
                    }
                }
                else if (sItem.type == 70)
                {
                    if (this.ZoneCorrupt)
                    {
                        this.ApplyItemTime(sItem);
                        SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                        if (Main.netMode != 1)
{
                            NPC.SpawnOnPlayer(onWhichPlayer, 13, 0f, 0f, 0f, 0f);
                            return;
                        }
                        NetMessage.SendData(61, -1, -1, null, this.whoAmI, 13f, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
                else if (sItem.type == 544)
                {
                    if (!Main.IsItDay() && sItem.Variant != ItemVariants.DisabledBossSummonVariant)
                    {
                        this.ApplyItemTime(sItem);
                        SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                        if (Main.netMode != 1)
{
                            NPC.SpawnOnPlayer(onWhichPlayer, 125, 0f, 0f, 0f, 0f);
                            NPC.SpawnOnPlayer(onWhichPlayer, 126, 0f, 0f, 0f, 0f);
                            return;
                        }
                        NetMessage.SendData(61, -1, -1, null, this.whoAmI, 125f, 0f, 0f, 0, 0, 0);
                        NetMessage.SendData(61, -1, -1, null, this.whoAmI, 126f, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
                else if (sItem.type == 556)
                {
                    if (!Main.IsItDay() && sItem.Variant != ItemVariants.DisabledBossSummonVariant)
                    {
                        this.ApplyItemTime(sItem);
                        SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                        if (Main.netMode != 1)
{
                            NPC.SpawnOnPlayer(onWhichPlayer, 134, 0f, 0f, 0f, 0f);
                            return;
                        }
                        NetMessage.SendData(61, -1, -1, null, this.whoAmI, 134f, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
                else if (sItem.type == 557)
                {
                    if (!Main.IsItDay() && sItem.Variant != ItemVariants.DisabledBossSummonVariant)
                    {
                        this.ApplyItemTime(sItem);
                        SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                        if (Main.netMode != 1)
{
                            NPC.SpawnOnPlayer(onWhichPlayer, 127, 0f, 0f, 0f, 0f);
                            return;
                        }
                        NetMessage.SendData(61, -1, -1, null, this.whoAmI, 127f, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
                else if (sItem.type == 5334)
                {
                    if (NPC.SpawnMechQueen(this.whoAmI))
                    {
                        this.ApplyItemTime(sItem);
                        SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                        return;
                    }
                }
                else if (sItem.type == 1133)
                {
                    this.ApplyItemTime(sItem);
                    SoundEngine.PlaySound(SoundID.Item173, (int)this.position.X, (int)this.position.Y, 0f, 1f);
                    if (Main.netMode != 1)
                    {
                        NPC.SpawnOnPlayer(onWhichPlayer, 222, 0f, 0f, 0f, 0f);
                        return;
                    }
                    NetMessage.SendData(61, -1, -1, null, this.whoAmI, 222f, 0f, 0f, 0, 0, 0);
                    return;
                }
                else if (sItem.type == 1331)
                {
                    if (this.ZoneCrimson)
                    {
                        this.ApplyItemTime(sItem);
                        SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                        if (Main.netMode != 1)
{
                            NPC.SpawnOnPlayer(onWhichPlayer, 266, 0f, 0f, 0f, 0f);
                            return;
                        }
                        NetMessage.SendData(61, -1, -1, null, this.whoAmI, 266f, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
                else if (sItem.type == 4988)
                {
                    if (this.ZoneHallow)
                    {
                        this.ApplyItemTime(sItem);
                        SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                        if (Main.netMode != 1)
{
                            NPC.SpawnOnPlayer(onWhichPlayer, 657, 0f, 0f, 0f, 0f);
                            return;
                        }
                        NetMessage.SendData(61, -1, -1, null, this.whoAmI, 657f, 0f, 0f, 0, 0, 0);
                        return;
                    }
                }
                else if (sItem.type == 5120 && this.ZoneSnow)
                {
                    this.ApplyItemTime(sItem);
                    SoundEngine.PlaySound(15, (int)this.position.X, (int)this.position.Y, 0, 1f, 0f);
                    if (Main.netMode != 1)
                    {
                        NPC.SpawnOnPlayer(onWhichPlayer, 668, 0f, 0f, 0f, 0f);
                        return;
                    }
                    NetMessage.SendData(61, -1, -1, null, this.whoAmI, 668f, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.GameContent.Items.ItemVariants.DisabledBossSummonVariant, Terraria.Main.IsItDay(), Terraria.ID.SoundID.Item173, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.NPC.SpawnMechQueen(), Terraria.NPC.SpawnOnPlayer(), Terraria.Item.type, and Terraria.Item.Variant.