Terraria Decompiled: Terraria.Player.ItemCheck_CutTiles
ItemCheck_CutTiles()
void Terraria.Player.ItemCheck_CutTiles (Item sItem, Rectangle itemRectangle, bool[] shouldIgnore, bool cutExtraTiles = false) inline private
Definition at line 43863 of file Player.cs.
        {
            if (sItem.type == 213 || sItem.type == 5295)
            {
                this.staffOfRegrowthBonus = true;
            }
            int num = itemRectangle.X / 16;
            int num2 = (itemRectangle.X + itemRectangle.Width) / 16 + 1;
            int num3 = itemRectangle.Y / 16;
            int num4 = (itemRectangle.Y + itemRectangle.Height) / 16 + 1;
            Utils.ClampWithinWorld(ref num, ref num3, ref num2, ref num4, false, 0, 0);
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    if (Main.tile[i, j] != null && (Main.tileCut[(int)Main.tile[i, j].type] || (cutExtraTiles && TileID.Sets.bonusCutTiles[(int)Main.tile[i, j].type])) && !shouldIgnore[(int)Main.tile[i, j].type] && WorldGen.CanCutTile(i, j, TileCuttingContext.AttackMelee))
                    {
                        if (sItem.type == 1786)
{
                            ushort type = Main.tile[i, j].type;
                            WorldGen.KillTile(i, j, false, false, false);
                            if (!Main.tile[i, j].active())
{
                                int num5 = 0;
                                if (type == 3 || type == 24 || type == 61 || type == 110 || type == 201 || type == 637 || type == 529)
{
                                    num5 = Main.rand.Next(1, 3);
                                }
                                else if (type == 73 || type == 74 || type == 113)
{
                                    num5 = Main.rand.Next(2, 5);
                                }
                                if (num5 > 0)
{
                                    int num6 = Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 1727, num5, false, 0, false);
                                    if (Main.netMode == 1)
{
                                        NetMessage.SendData(21, -1, -1, null, num6, 1f, 0f, 0f, 0, 0, 0);
                                    }
                                }
                            }
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                            }
                        }
                        else
{
                            WorldGen.KillTile(i, j, false, false, false);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                            }
                        }
                    }
                }
            }
            this.staffOfRegrowthBonus = false;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.bonusCutTiles, Terraria.WorldGen.CanCutTile(), Terraria.Utils.ClampWithinWorld(), Terraria.WorldGen.GetItemSource_FromTileBreak(), Microsoft.Xna.Framework.Rectangle.Height, int, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Item.type, Terraria.Tile.type, and Microsoft.Xna.Framework.Rectangle.Width.