Terraria Decompiled: Terraria.Player.TryInterruptingItemUsage
TryInterruptingItemUsage()
void Terraria.Player.TryInterruptingItemUsage () inline
Definition at line 22648 of file Player.cs.
        {
            bool flag = false;
            if (this.heldProj > -1 && Main.projectile[this.heldProj].IsInterruptible(this))
            {
                flag = true;
            }
            if (!flag)
            {
                return;
            }
            bool flag2 = false;
            if (PlayerInput.Triggers.Current.Hotbar1)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar2)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar3)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar4)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar5)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar6)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar7)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar8)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar9)
            {
                flag2 = true;
            }
            if (PlayerInput.Triggers.Current.Hotbar10)
            {
                flag2 = true;
            }
            bool flag3 = Main.hairWindow;
            if (flag3)
            {
                int num = Main.screenHeight / 2 + 60;
                flag3 = new Rectangle(Main.screenWidth / 2 - TextureAssets.HairStyleBack.Width() / 2, num, TextureAssets.HairStyleBack.Width(), TextureAssets.HairStyleBack.Height()).Contains(Main.MouseScreen.ToPoint());
            }
            if (!Main.mapFullscreen && !CaptureManager.Instance.Active && !flag3 && !Main.playerInventory)
            {
                int num2 = PlayerInput.Triggers.Current.HotbarPlus.ToInt() - PlayerInput.Triggers.Current.HotbarMinus.ToInt();
                if (PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired != -1)
                {
                    num2 = PlayerInput.Triggers.JustReleased.HotbarPlus.ToInt() - PlayerInput.Triggers.JustReleased.HotbarMinus.ToInt();
                }
                if (PlayerInput.Triggers.Current.HotbarScrollCD != 0)
                {
                    num2 = 0;
                }
                if (!Main.inFancyUI && !Main.ingameOptionsWindow)
                {
                    num2 += PlayerInput.ScrollWheelDelta / -120;
                }
                if (num2 != 0)
                {
                    num2 = Player.ClampHotbarOffset(num2);
                    int num3 = this.selectedItem + num2;
                    flag2 = true;
                }
            }
            if (flag2 && this.heldProj > -1)
            {
                Main.projectile[this.heldProj].Interrupt(this);
            }
        }
References Terraria.Graphics.Capture.CaptureManager.Active, Terraria.Player.ClampHotbarOffset(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameInput.TriggersPack.Current, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameContent.TextureAssets.HairStyleBack, Terraria.Main.hairWindow, Terraria.GameInput.TriggersSet.Hotbar1, Terraria.GameInput.TriggersSet.Hotbar10, Terraria.GameInput.TriggersSet.Hotbar2, Terraria.GameInput.TriggersSet.Hotbar3, Terraria.GameInput.TriggersSet.Hotbar4, Terraria.GameInput.TriggersSet.Hotbar5, Terraria.GameInput.TriggersSet.Hotbar6, Terraria.GameInput.TriggersSet.Hotbar7, Terraria.GameInput.TriggersSet.Hotbar8, Terraria.GameInput.TriggersSet.Hotbar9, Terraria.GameInput.TriggersSet.HotbarMinus, Terraria.GameInput.TriggersSet.HotbarPlus, Terraria.GameInput.PlayerInputProfile.HotbarRadialHoldTimeRequired, Terraria.GameInput.TriggersSet.HotbarScrollCD, Terraria.Main.inFancyUI, Terraria.Main.ingameOptionsWindow, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Projectile.Interrupt(), Terraria.Projectile.IsInterruptible(), Terraria.GameInput.TriggersPack.JustReleased, Terraria.Main.mapFullscreen, Terraria.Main.MouseScreen, Terraria.Main.playerInventory, Terraria.Main.projectile, Terraria.Main.screenWidth, and Terraria.GameInput.PlayerInput.Triggers.