Terraria Decompiled: Terraria.Player.MoonLeechRope
MoonLeechRope()
void Terraria.Player.MoonLeechRope () inline
Definition at line 20649 of file Player.cs.
        {
            int num = -1;
            for (int i = 0; i < 1000; i++)
            {
                if (Main.projectile[i].active && Main.projectile[i].type == 456 && Main.projectile[i].ai[1] == (float)this.whoAmI)
                {
                    num = i;
                    break;
                }
            }
            if (num == -1)
            {
                return;
            }
            if (Main.projectile[num].ai[0] < 0f)
            {
                return;
            }
            Projectile projectile = Main.projectile[num];
            Vector2 vector = new Vector2(0f, 216f);
            Vector2 vector2 = Main.npc[(int)Math.Abs(projectile.ai[0]) - 1].Center - base.Center + vector;
            if (vector2.Length() > 200f)
            {
                Vector2 vector3 = Vector2.Normalize(vector2);
                this.position += vector3 * (vector2.Length() - 200f);
            }
        }
References System.Math.Abs(), Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.Entity.Center, int, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.npc, Terraria.Main.projectile, and Terraria.Projectile.type.