Terraria Decompiled: Terraria.Player.SmartInteractLookup
SmartInteractLookup()
void Terraria.Player.SmartInteractLookup () inline
Definition at line 15656 of file Player.cs.
        {
            Main.ClearSmartInteract();
            if (UILinkPointNavigator.InUse || (PlayerInput.UsingGamepad && Main.HoveringOverAnNPC))
            {
                Main.SmartInteractTileCoordsSelected.Clear();
            }
            if ((!PlayerInput.SettingsForUI.ShowGamepadHints && !Main.SmartCursorIsUsed) || !Main.mouseItem.IsAir)
            {
                Player._smartInteractSys.Clear();
                return;
            }
            Vector2 vector;
            int num;
            int num2;
            int num3;
            int num4;
            this.SmartInteractLookup_PrepareCommonlyUsedInfo(out vector, out num, out num2, out num3, out num4);
            Player._smartInteractSys.RunQuery(new SmartInteractScanSettings
            {
                DemandOnlyZeroDistanceTargets = (PlayerInput.SettingsForUI.ShowGamepadHints && !Main.SmartCursorIsUsed),
                FullInteraction = true,
                HX = num2,
                HY = num4,
                LX = num,
                LY = num3,
                mousevec = vector,
                player = this
            });
        }
References Terraria.Player._smartInteractSys, System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.ObjectInteractions.SmartInteractSystem.Clear(), Terraria.Main.ClearSmartInteract(), Terraria.Main.HoveringOverAnNPC, Terraria.UI.Gamepad.UILinkPointNavigator.InUse, Terraria.Item.IsAir, Terraria.Main.mouseItem, Terraria.GameContent.ObjectInteractions.SmartInteractSystem.RunQuery(), Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadHints, Terraria.Main.SmartCursorIsUsed, Terraria.Main.SmartInteractTileCoordsSelected, and Terraria.GameInput.PlayerInput.UsingGamepad.