Terraria Decompiled: Terraria.Player.FindClosest
FindClosest()
static byte Terraria.Player.FindClosest (Vector2 Position, int Width, int Height) inline static
Definition at line 2187 of file Player.cs.
        {
            byte b = 0;
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active)
                {
                    b = (byte)i;
                    break;
                }
            }
            float num = -1f;
            for (int j = 0; j < 255; j++)
            {
                if (Main.player[j].active && !Main.player[j].dead)
                {
                    float num2 = Math.Abs(Main.player[j].position.X + (float)(Main.player[j].width / 2) - (Position.X + (float)(Width / 2))) + Math.Abs(Main.player[j].position.Y + (float)(Main.player[j].height / 2) - (Position.Y + (float)(Height / 2)));
                    if (num == -1f || num2 < num)
                    {
                        num = num2;
                        b = (byte)j;
                    }
                }
            }
            return b;
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.Player.dead, Terraria.Entity.height, Terraria.Main.player, Terraria.Entity.position, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_015_KingSlime_FindTeleportSpot(), Terraria.WorldGen.CheckSign(), Terraria.Player.GetClosestPlayersLuck(), Terraria.Player.GetClosestPlayersLuck(), Terraria.Player.GetClosestRollBadLuck(), Terraria.Player.GetClosestRollBadLuck(), Terraria.Player.GetClosestRollLuck(), Terraria.Player.GetClosestRollLuck(), Terraria.WorldGen.GetPlayerForTile(), Terraria.WorldGen.KillTile_DropBait(), Terraria.WorldGen.KillTile_GetTreeDrops(), Terraria.NPC.NPCLoot(), Terraria.GameContent.UI.EmoteBubble.PickNPCEmote(), Terraria.Projectile.RainbowBoulder_GetAreas(), Terraria.WorldGen.SmashAltar(), Terraria.WorldGen.SpawnFallingObjects(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.NPC.SpawnWOF(), Terraria.GameContent.Events.DD2Event.SummonBetsy(), Terraria.WorldItem.TryGrantingMakeAWishSet(), and Terraria.Main.UpdateTime().