Terraria Decompiled: Terraria.Player.PlaceThing_PaintScrapper_LongMoss
PlaceThing_PaintScrapper_LongMoss()
void Terraria.Player.PlaceThing_PaintScrapper_LongMoss (int x, int y) inline private
Definition at line 40860 of file Player.cs.
        {
            if (Main.tile[x, y].type != 184)
            {
                return;
            }
            this.cursorItemIconEnabled = true;
            if (this.ItemTimeIsZero && this.itemAnimation > 0 && this.controlUseItem)
            {
                ushort type = Main.tile[x, y].type;
                int frameX = (int)Main.tile[x, y].frameX;
                WorldGen.KillTile(x, y, false, false, false);
                if (!Main.tile[x, y].active())
                {
                    this.ApplyItemTime(this.inventory[this.selectedItem]);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                    }
                    if (Main.rand.Next(9) == 0)
                    {
                        int num = 4349 + frameX / 22;
                        switch (frameX / 22)
{
                        case 6:
                            num = 4377;
                            break;
                        case 7:
                            num = 4378;
                            break;
                        case 8:
                            num = 4389;
                            break;
                        case 9:
                            num = 5127;
                            break;
                        case 10:
                            num = 5128;
                            break;
                        }
                        int num2 = Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, num, 1, false, 0, false);
                        NetMessage.SendData(21, -1, -1, null, num2, 1f, 0f, 0f, 0, 0, 0);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Main.tile, and Terraria.Tile.type.