Terraria Decompiled: Terraria.Player.Shellphone_Spawn
Shellphone_Spawn()
void Terraria.Player.Shellphone_Spawn () inline
Definition at line 55481 of file Player.cs.
        {
            int spawnTileX = Main.spawnTileX;
            int spawnTileY = Main.spawnTileY;
            this.Spawn_GetPositionAtWorldSpawn(ref spawnTileX, ref spawnTileY);
            if (Main.netMode != 1 && !Player.Spawn_IsAreaValidSpawn(spawnTileX, spawnTileY, false))
            {
                Player.Spawn_ForceClearArea(spawnTileX, spawnTileY);
            }
            Vector2 vector = new Point(spawnTileX, spawnTileY).ToWorldCoordinates(8f, 0f) - new Vector2((float)(this.width / 2), (float)this.height);
            this.Teleport(vector, 11, 0);
            this.velocity = Vector2.Zero;
            if (Main.netMode == 2)
            {
                RemoteClient.CheckSection(this.whoAmI, this.position, 1);
                NetMessage.SendData(65, -1, -1, null, 0, (float)this.whoAmI, vector.X, vector.Y, 11, 0, 0);
            }
        }
References Terraria.RemoteClient.CheckSection(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Player.Spawn_ForceClearArea(), Terraria.Player.Spawn_IsAreaValidSpawn(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Player.PlayerNoSpaceTeleport().