Terraria Decompiled: Terraria.Player.ApplyEquipFunctional
ApplyEquipFunctional()
void Terraria.Player.ApplyEquipFunctional (int itemSlot, Item currentItem) inline private
Definition at line 12051 of file Player.cs.
        {
            if (currentItem.expertOnly && !Main.expertMode)
            {
                return;
            }
            if (currentItem.type == 3810 || currentItem.type == 3809 || currentItem.type == 3812 || currentItem.type == 3811)
            {
                this.dd2Accessory = true;
            }
            if (!this.hideVisibleAccessory[itemSlot])
            {
                this.UpdateBootVisualEffects(currentItem);
                this.UpdateFishingBobber(currentItem);
                if (currentItem.voiceSlot != 0)
                {
                    this.voiceOverride = currentItem.voiceSlot;
                }
                if (currentItem.type == 5077)
                {
                    this.DoGlassSlipperSparkles();
                }
            }
            int type = currentItem.type;
            if (type <= 4056)
            {
                if (type <= 4007)
                {
                    if (type != 3245)
                    {
                        switch (type)
{
                        case 3990:
                            this.accRunSpeed = 6f;
                            this.autoJump = true;
                            this.jumpSpeedBoost += 1.6f;
                            this.extraFall += 10;
                            break;
                        case 3991:
                            this.manaFlower = true;
                            this.manaCost -= 0.08f;
                            this.aggro -= 400;
                            break;
                        case 3992:
                            this.kbGlove = true;
                            this.autoReuseGlove = true;
                            this.meleeScaleGlove = true;
                            this.meleeSpeed += 0.12f;
                            this.aggro += 400;
                            break;
                        case 3993:
                            this.accRunSpeed = 6f;
                            this.rocketBoots = (this.vanityRocketBoots = 2);
                            break;
                        case 3994:
                            this.autoJump = true;
                            this.jumpSpeedBoost += 1.6f;
                            this.extraFall += 10;
                            this.accFlipper = true;
                            break;
                        case 3995:
                            this.autoJump = true;
                            this.jumpSpeedBoost += 1.6f;
                            this.extraFall += 10;
                            this.accFlipper = true;
                            this.spikedBoots += 2;
                            break;
                        case 3996:
                            this.autoJump = true;
                            this.jumpSpeedBoost += 1.6f;
                            this.extraFall += 10;
                            this.spikedBoots += 2;
                            break;
                        case 3998:
                            this.aggro += 400;
                            break;
                        case 3999:
                            this.fireWalk = true;
                            break;
                        case 4000:
                            this.manaFlower = true;
                            this.manaCost -= 0.08f;
                            this.manaMagnet = true;
                            break;
                        case 4001:
                            this.manaFlower = true;
                            this.manaCost -= 0.08f;
                            this.starCloakItem = currentItem;
                            this.starCloakItem_manaCloakOverrideItem = currentItem;
                            break;
                        case 4002:
                            this.magicQuiver = true;
                            this.arrowDamageAdditiveStack += 0.1f;
                            this.hasMoltenQuiver = true;
                            break;
                        case 4003:
                            this.fireWalk = true;
                            this.lavaRose = true;
                            break;
                        case 4004:
                            this.fireWalk = true;
                            this.lavaRose = true;
                            break;
                        case 4005:
                            this.rangedCrit += 10;
                            this.rangedDamage += 0.1f;
                            this.aggro -= 400;
                            break;
                        case 4006:
                            this.aggro -= 400;
                            this.magicQuiver = true;
                            this.arrowDamageAdditiveStack += 0.1f;
                            break;
                        case 4007:
                            this.honeyCombItem = currentItem;
                            this.armorPenetration += 5;
                            break;
                        }
                    }
                    else
                    {
                        this.boneGloveItem = currentItem;
                    }
                }
                else if (type != 4038)
                {
                    if (type != 4055)
                    {
                        if (type == 4056)
{
                            this.chiselSpeed = true;
                        }
                    }
                    else
                    {
                        this.accRunSpeed = 6f;
                        this.desertBoots = true;
                    }
                }
                else
                {
                    this.fireWalk = true;
                }
            }
            else
            {
                if (type <= 5010)
                {
                    if (type != 4341)
                    {
                        if (type == 4409)
{
                            this.CanSeeInvisibleBlocks = true;
                            goto IL_052E;
                        }
                        if (type != 5010)
{
                            goto IL_052E;
                        }
                        this.treasureMagnet = true;
                        goto IL_052E;
                    }
                }
                else
                {
                    if (type == 5107)
                    {
                        this.hasMagiluminescence = true;
                        this.MountedCenter.ToTileCoordinates();
                        DelegateMethods.v3_1 = new Vector3(0.9f, 0.8f, 0.5f);
                        Utils.PlotTileLine(base.Center, base.Center + this.velocity * 6f, 20f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen));
                        Utils.PlotTileLine(base.Left, base.Right, 20f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen));
                        goto IL_052E;
                    }
                    if (type != 5126)
                    {
                        if (type == 5465)
{
                            this.hasDeadCellsDownDash = true;
                            goto IL_052E;
                        }
                        goto IL_052E;
                    }
                }
                this.portableStoolInfo.SetStats(26, 26, 26);
            }
            IL_052E:
            if (currentItem.type == 3015)
            {
                this.aggro -= 400;
                this.meleeCrit += 5;
                this.magicCrit += 5;
                this.rangedCrit += 5;
                this.meleeDamage += 0.05f;
                this.magicDamage += 0.05f;
                this.rangedDamage += 0.05f;
                this.minionDamage += 0.05f;
            }
            if (currentItem.type == 3016)
            {
                this.aggro += 400;
            }
            if (currentItem.type == 2373)
            {
                this.accFishingLine = true;
            }
            if (currentItem.type == 2374)
            {
                this.fishingSkill += 10;
            }
            if (currentItem.type == 5139 || currentItem.type == 5144 || currentItem.type == 5142 || currentItem.type == 5141 || currentItem.type == 5146 || currentItem.type == 5140 || currentItem.type == 5145 || currentItem.type == 5143)
            {
                this.accFishingBobber = true;
            }
            if (currentItem.type == 2375)
            {
                this.accTackleBox = true;
            }
            if (currentItem.type == 4881)
            {
                this.accLavaFishing = true;
            }
            if (currentItem.type == 3721)
            {
                this.accFishingLine = true;
                this.accTackleBox = true;
                this.fishingSkill += 10;
            }
            if (currentItem.type == 5064)
            {
                this.accFishingLine = true;
                this.accTackleBox = true;
                this.fishingSkill += 10;
                this.accLavaFishing = true;
            }
            if (currentItem.type == 3090)
            {
                this.npcTypeNoAggro[1] = true;
                this.npcTypeNoAggro[16] = true;
                this.npcTypeNoAggro[59] = true;
                this.npcTypeNoAggro[71] = true;
                this.npcTypeNoAggro[81] = true;
                this.npcTypeNoAggro[138] = true;
                this.npcTypeNoAggro[121] = true;
                this.npcTypeNoAggro[122] = true;
                this.npcTypeNoAggro[141] = true;
                this.npcTypeNoAggro[147] = true;
                this.npcTypeNoAggro[183] = true;
                this.npcTypeNoAggro[184] = true;
                this.npcTypeNoAggro[204] = true;
                this.npcTypeNoAggro[225] = true;
                this.npcTypeNoAggro[244] = true;
                this.npcTypeNoAggro[302] = true;
                this.npcTypeNoAggro[333] = true;
                this.npcTypeNoAggro[335] = true;
                this.npcTypeNoAggro[334] = true;
                this.npcTypeNoAggro[336] = true;
                this.npcTypeNoAggro[537] = true;
                this.npcTypeNoAggro[676] = true;
                this.npcTypeNoAggro[667] = true;
            }
            if (currentItem.stringColor > 0)
            {
                this.yoyoString = true;
            }
            if (currentItem.type == 3366)
            {
                if (this.counterWeight == 0)
                {
                    if (Main.rand.Next(7) == 0)
                    {
                        this.counterWeight = 1079;
                    }
                    else
                    {
                        this.counterWeight = 556 + Main.rand.Next(6);
                    }
                }
                this.yoyoGlove = true;
                this.yoyoString = true;
            }
            if (currentItem.type == 5543 && this.CanUseStressBall())
            {
                this.stressBall = true;
            }
            if (currentItem.type == 5540)
            {
                this.magicString = true;
            }
            if (currentItem.type == 5541)
            {
                if (this.counterWeight == 0)
                {
                    if (Main.rand.Next(7) == 0)
                    {
                        this.counterWeight = 1079;
                    }
                    else
                    {
                        this.counterWeight = 556 + Main.rand.Next(6);
                    }
                }
                this.yoyoGlove = true;
                this.yoyoString = true;
                this.magicString = true;
            }
            if (currentItem.type == 5547)
            {
                this.counterWeight = 1079;
            }
            if (currentItem.type >= 3309 && currentItem.type <= 3314)
            {
                this.counterWeight = 556 + currentItem.type - 3309;
            }
            if (currentItem.type == 3334)
            {
                this.yoyoGlove = true;
            }
            if (currentItem.type == 3337)
            {
                this.shinyStone = true;
            }
            if (currentItem.type == 4989)
            {
                this.empressBrooch = true;
                this.moveSpeed += 0.075f;
            }
            if (currentItem.type == 3336)
            {
                this.SporeSac(currentItem);
                this.sporeSac = true;
            }
            if (currentItem.type == 4987)
            {
                this.VolatileGelatin(currentItem);
                this.volatileGelatin = true;
            }
            this.ApplyShader(currentItem.type);
            if (currentItem.type == 2423)
            {
                this.autoJump = true;
                this.jumpSpeedBoost += 1.6f;
                this.extraFall += 10;
            }
            if (currentItem.type == 857)
            {
                this.hasJumpOption_Sandstorm = true;
            }
            if (currentItem.type == 983)
            {
                this.hasJumpOption_Sandstorm = true;
                this.jumpBoost = true;
            }
            if (currentItem.type == 987)
            {
                this.hasJumpOption_Blizzard = true;
            }
            if (currentItem.type == 1163)
            {
                this.hasJumpOption_Blizzard = true;
                this.jumpBoost = true;
            }
            if (currentItem.type == 1724)
            {
                this.hasJumpOption_Fart = true;
            }
            if (currentItem.type == 1863)
            {
                this.hasJumpOption_Fart = true;
                this.jumpBoost = true;
            }
            if (currentItem.type == 1164)
            {
                this.hasJumpOption_Cloud = true;
                this.hasJumpOption_Sandstorm = true;
                this.hasJumpOption_Blizzard = true;
                this.jumpBoost = true;
            }
            if (currentItem.type == 5331)
            {
                this.hasJumpOption_Cloud = true;
                this.hasJumpOption_Sandstorm = true;
                this.hasJumpOption_Blizzard = true;
                this.jumpBoost = true;
                this.noFallDmg = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 1250)
            {
                this.jumpBoost = true;
                this.hasJumpOption_Cloud = true;
                this.noFallDmg = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 1252)
            {
                this.hasJumpOption_Sandstorm = true;
                this.jumpBoost = true;
                this.noFallDmg = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 1251)
            {
                this.hasJumpOption_Blizzard = true;
                this.jumpBoost = true;
                this.noFallDmg = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 3250)
            {
                this.hasJumpOption_Fart = true;
                this.jumpBoost = true;
                this.noFallDmg = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 3252)
            {
                this.hasJumpOption_Sail = true;
                this.jumpBoost = true;
                this.noFallDmg = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 3251)
            {
                this.jumpBoost = true;
                this.honeyCombItem = currentItem;
                this.noFallDmg = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 1249)
            {
                this.jumpBoost = true;
                this.honeyCombItem = currentItem;
            }
            if (currentItem.type == 3241)
            {
                this.jumpBoost = true;
                this.hasJumpOption_Sail = true;
            }
            if ((currentItem.type == 1253 || currentItem.type == 3997) && (double)this.statLife <= (double)this.statLifeMax2 * 0.5)
            {
                this.AddBuff(62, 5, false);
            }
            if (currentItem.type == 1290)
            {
                this.panic = true;
            }
            if ((currentItem.type == 1300 || currentItem.type == 1858 || currentItem.type == 4005) && (this.inventory[this.selectedItem].useAmmo == AmmoID.Bullet || this.inventory[this.selectedItem].useAmmo == AmmoID.CandyCorn || this.inventory[this.selectedItem].useAmmo == AmmoID.Stake || this.inventory[this.selectedItem].useAmmo == 23 || this.inventory[this.selectedItem].useAmmo == AmmoID.Solution))
            {
                this.scope = true;
            }
            if (currentItem.type == 1858)
            {
                this.rangedCrit += 10;
                this.rangedDamage += 0.1f;
            }
            if (currentItem.type == 1301)
            {
                this.meleeCrit += 8;
                this.rangedCrit += 8;
                this.magicCrit += 8;
                this.meleeDamage += 0.1f;
                this.rangedDamage += 0.1f;
                this.magicDamage += 0.1f;
                this.minionDamage += 0.1f;
            }
            if (currentItem.type == 111)
            {
                this.statManaMax2 += 20;
            }
            if (currentItem.type == 982)
            {
                this.statManaMax2 += 20;
                this.manaRegenDelayBonus += 1f;
                this.manaRegenBonus += 25;
            }
            if (currentItem.type == 1595)
            {
                this.statManaMax2 += 20;
                this.magicCuffs = true;
            }
            if (currentItem.type == 2219)
            {
                this.manaMagnet = true;
            }
            if (currentItem.type == 2220)
            {
                this.manaMagnet = true;
                this.magicDamage += 0.15f;
            }
            if (currentItem.type == 2221)
            {
                this.manaMagnet = true;
                this.statManaMax2 += 20;
                this.magicCuffs = true;
            }
            if (this.whoAmI == Main.myPlayer && currentItem.type == 1923)
            {
                Player.tileRangeX++;
                Player.tileRangeY++;
            }
            if (currentItem.type == 1247)
            {
                this.starCloakItem = currentItem;
                this.honeyCombItem = currentItem;
                this.starCloakItem_beeCloakOverrideItem = currentItem;
            }
            if (currentItem.type == 1248)
            {
                this.meleeCrit += 10;
                this.rangedCrit += 10;
                this.magicCrit += 10;
            }
            if (currentItem.type == 854)
            {
                this.discountEquipped = true;
            }
            if (currentItem.type == 855)
            {
                this.hasLuckyCoin = true;
                this.hasLuck_LuckyCoin = true;
            }
            if (currentItem.type == 3033)
            {
                this.goldRing = true;
            }
            if (currentItem.type == 3034)
            {
                this.goldRing = true;
                this.hasLuckyCoin = true;
                this.hasLuck_LuckyCoin = true;
            }
            if (currentItem.type == 3035)
            {
                this.goldRing = true;
                this.hasLuckyCoin = true;
                this.hasLuck_LuckyCoin = true;
                this.discountEquipped = true;
            }
            if (currentItem.type == 53)
            {
                this.hasJumpOption_Cloud = true;
            }
            if (currentItem.type == 3201)
            {
                this.hasJumpOption_Sail = true;
            }
            if (currentItem.type == 54)
            {
                this.accRunSpeed = 6f;
            }
            if (currentItem.type == 3068)
            {
                this.cordage = true;
            }
            if (currentItem.type == 1579)
            {
                this.accRunSpeed = 6f;
            }
            if (currentItem.type == 3200)
            {
                this.accRunSpeed = 6f;
            }
            if (currentItem.type == 128)
            {
                this.rocketBoots = (this.vanityRocketBoots = 1);
            }
            if (currentItem.type == 156)
            {
                this.noKnockback = true;
            }
            if (currentItem.type == 158)
            {
                this.noFallDmg = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 934)
            {
                this.carpet = true;
            }
            if (currentItem.type == 953)
            {
                this.spikedBoots++;
            }
            if (currentItem.type == 975)
            {
                this.spikedBoots++;
            }
            if (currentItem.type == 976)
            {
                this.spikedBoots += 2;
            }
            if (currentItem.type == 977)
            {
                this.dashType = 1;
            }
            if (currentItem.type == 3097)
            {
                this.dashType = 2;
            }
            if (currentItem.type == 963)
            {
                this.blackBelt = true;
            }
            if (currentItem.type == 984)
            {
                this.blackBelt = true;
                this.dashType = 1;
                this.spikedBoots = 2;
            }
            if (currentItem.type == 1131)
            {
                this.gravControl2 = true;
            }
            if (currentItem.type == 1132)
            {
                this.honeyCombItem = currentItem;
            }
            if (currentItem.type == 1578)
            {
                this.honeyCombItem = currentItem;
                this.panic = true;
            }
            if (currentItem.type == 3224)
            {
                this.endurance += 0.17f;
            }
            if (currentItem.type == 3223)
            {
                this.brainOfConfusionItem = currentItem;
            }
            if (currentItem.type == 950)
            {
                this.iceSkate = true;
            }
            if (currentItem.type == 159)
            {
                this.jumpBoost = true;
            }
            if (currentItem.type == 3225)
            {
                this.jumpBoost = true;
            }
            if (currentItem.type == 187)
            {
                this.accFlipper = true;
            }
            if (currentItem.type == 211)
            {
                this.autoReuseGlove = true;
                this.meleeSpeed += 0.12f;
            }
            if (currentItem.type == 223)
            {
                this.manaCost -= 0.06f;
            }
            if (currentItem.type == 285)
            {
                this.moveSpeed += 0.05f;
            }
            if (currentItem.type == 212)
            {
                this.moveSpeed += 0.1f;
            }
            if (currentItem.type == 267)
            {
                this.killGuide = true;
            }
            if (currentItem.type == 1307)
            {
                this.killClothier = true;
            }
            if (currentItem.type == 193)
            {
                this.fireWalk = true;
            }
            if (currentItem.type == 861)
            {
                this.accMerman = true;
                this.wolfAcc = true;
                if (this.hideVisibleAccessory[itemSlot])
                {
                    this.hideMerman = true;
                    this.hideWolf = true;
                }
            }
            if (currentItem.type == 862)
            {
                this.starCloakItem = currentItem;
                this.longInvince = true;
                this.starCloakItem_starVeilOverrideItem = currentItem;
            }
            if (currentItem.type == 860)
            {
                this.pStone = true;
            }
            if (currentItem.type == 863)
            {
                this.waterWalk2 = true;
            }
            if (currentItem.type == 907)
            {
                this.waterWalk2 = true;
                this.fireWalk = true;
            }
            if (currentItem.type == 5044)
            {
                this.hasCreditsSceneMusicBox = true;
            }
            if (currentItem.type == 908 || currentItem.type == 5000)
            {
                this.waterWalk = true;
                this.fireWalk = true;
                this.lavaMax += 420;
                this.lavaRose = true;
            }
            if ((!this.mount.Active || this.mount.Type != 47) && !this.hideVisibleAccessory[itemSlot] && (currentItem.type == 4822 || currentItem.type == 4874))
            {
                this.DoBootsEffect(new Utils.TileActionAttempt(this.DoBootsEffect_PlaceFlamesOnTile));
            }
            if (currentItem.type == 906 || currentItem.type == 4038 || currentItem.type == 3999 || currentItem.type == 4003)
            {
                this.lavaMax += 420;
            }
            if (currentItem.type == 485)
            {
                this.wolfAcc = true;
                if (this.hideVisibleAccessory[itemSlot])
                {
                    this.hideWolf = true;
                }
            }
            if (currentItem.type == 486)
            {
                this.rulerLine = true;
            }
            if (currentItem.type == 2799)
            {
                this.rulerGrid = true;
            }
            if (currentItem.type == 394)
            {
                this.accFlipper = true;
                this.accDivingHelm = true;
            }
            if (currentItem.type == 396)
            {
                this.noFallDmg = true;
                this.fireWalk = true;
                this.hasLuck_LuckyHorseshoe = true;
            }
            if (currentItem.type == 397)
            {
                this.noKnockback = true;
                this.fireWalk = true;
            }
            if (currentItem.type == 399)
            {
                this.jumpBoost = true;
                this.hasJumpOption_Cloud = true;
            }
            if (currentItem.type == 405)
            {
                this.accRunSpeed = 6f;
                this.rocketBoots = (this.vanityRocketBoots = 2);
            }
            if (currentItem.type == 1303)
            {
                if (!this.wet)
                {
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.225f, 0.05f, 0.15f);
                }
                if (this.wet)
                {
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 1.8f, 0.4f, 1.2f);
                }
            }
            if (currentItem.type == 1860)
            {
                this.accFlipper = true;
                this.accDivingHelm = true;
                if (!this.wet)
                {
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.225f, 0.05f, 0.15f);
                }
                if (this.wet)
                {
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 1.8f, 0.4f, 1.2f);
                }
            }
            if (currentItem.type == 1861)
            {
                this.arcticDivingGear = true;
                this.accFlipper = true;
                this.accDivingHelm = true;
                this.iceSkate = true;
                if (!this.wet)
                {
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.05f, 0.15f, 0.225f);
                }
                if (this.wet)
                {
                    Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 1.2f, 1.8f);
                }
            }
            if (currentItem.type == 2214)
            {
                this.equippedAnyTileSpeedAcc = true;
            }
            if (currentItem.type == 2215)
            {
                this.equippedAnyTileRangeAcc = true;
            }
            if (currentItem.type == 2216)
            {
                this.autoPaint = true;
            }
            if (currentItem.type == 2217)
            {
                this.equippedAnyWallSpeedAcc = true;
            }
            if (currentItem.type == 3061)
            {
                this.equippedAnyWallSpeedAcc = true;
                this.equippedAnyTileSpeedAcc = true;
                this.autoPaint = true;
                this.equippedAnyTileRangeAcc = true;
            }
            if (currentItem.type == 5126)
            {
                this.equippedAnyWallSpeedAcc = true;
                this.equippedAnyTileSpeedAcc = true;
                this.autoPaint = true;
                this.equippedAnyTileRangeAcc = true;
                this.treasureMagnet = true;
                this.chiselSpeed = true;
            }
            if (currentItem.type == 3624)
            {
                this.autoActuator = true;
            }
            if (currentItem.type == 897)
            {
                this.kbGlove = true;
                this.autoReuseGlove = true;
                this.meleeScaleGlove = true;
                this.meleeSpeed += 0.12f;
            }
            if (currentItem.type == 1343)
            {
                this.kbGlove = true;
                this.autoReuseGlove = true;
                this.meleeScaleGlove = true;
                this.meleeSpeed += 0.12f;
                this.meleeDamage += 0.12f;
                this.magmaStone = true;
            }
            if (currentItem.type == 1167)
            {
                this.minionKB += 2f;
                this.minionDamage += 0.15f;
            }
            if (currentItem.type == 1864)
            {
                this.minionKB += 2f;
                this.minionDamage += 0.15f;
                this.maxMinions++;
            }
            if (currentItem.type == 1845)
            {
                this.minionDamage += 0.1f;
                this.maxMinions++;
            }
            if (currentItem.type == 1321)
            {
                this.magicQuiver = true;
                this.arrowDamageAdditiveStack += 0.1f;
            }
            if (currentItem.type == 1322)
            {
                this.magmaStone = true;
            }
            if (currentItem.type == 1323)
            {
                this.lavaRose = true;
            }
            if (currentItem.type == 3333)
            {
                this.strongBees = true;
            }
            if (currentItem.type == 938 || currentItem.type == 3997 || currentItem.type == 3998)
            {
                this.noKnockback = true;
                if ((float)this.statLife > (float)this.statLifeMax2 * 0.25f)
                {
                    this.hasPaladinShield = true;
                    if (this.whoAmI != Main.myPlayer && this.miscCounter % 10 == 0)
                    {
                        int myPlayer = Main.myPlayer;
                        if (Main.player[myPlayer].team == this.team && this.team != 0)
{
                            float num = this.position.X - Main.player[myPlayer].position.X;
                            float num2 = this.position.Y - Main.player[myPlayer].position.Y;
                            if ((float)Math.Sqrt((double)(num * num + num2 * num2)) < Player.PaladinsShieldRange)
{
                                Main.player[myPlayer].AddBuff(43, 20, false);
                            }
                        }
                    }
                }
            }
            if (currentItem.type == 936)
            {
                this.kbGlove = true;
                this.autoReuseGlove = true;
                this.meleeScaleGlove = true;
                this.meleeSpeed += 0.12f;
                this.meleeDamage += 0.12f;
            }
            if (currentItem.type == 898)
            {
                this.accRunSpeed = 6.75f;
                this.rocketBoots = (this.vanityRocketBoots = 2);
                this.moveSpeed += 0.08f;
            }
            if (currentItem.type == 1862)
            {
                this.accRunSpeed = 6.75f;
                this.rocketBoots = (this.vanityRocketBoots = 3);
                this.moveSpeed += 0.08f;
                this.iceSkate = true;
            }
            if (currentItem.type == 5000)
            {
                this.accRunSpeed = 6.75f;
                this.rocketBoots = (this.vanityRocketBoots = 4);
                this.moveSpeed += 0.08f;
                this.iceSkate = true;
            }
            if (currentItem.type == 4874)
            {
                this.accRunSpeed = 6f;
                this.rocketBoots = (this.vanityRocketBoots = 5);
            }
            if (currentItem.type == 3110)
            {
                this.accMerman = true;
                this.wolfAcc = true;
                if (this.hideVisibleAccessory[itemSlot])
                {
                    this.hideMerman = true;
                    this.hideWolf = true;
                }
            }
            if (currentItem.type == 1865 || currentItem.type == 3110)
            {
                this.skyStoneEffects = true;
            }
            if (currentItem.type == 899 && Main.dayTime)
            {
                this.skyStoneEffects = true;
            }
            if (currentItem.type == 900 && (!Main.dayTime || Main.eclipse))
            {
                this.skyStoneEffects = true;
            }
            if (currentItem.type == 407)
            {
                this.blockRange++;
            }
            if (currentItem.type == 489)
            {
                this.magicDamage += 0.15f;
            }
            if (currentItem.type == 490)
            {
                this.meleeDamage += 0.15f;
            }
            if (currentItem.type == 491)
            {
                this.rangedDamage += 0.15f;
            }
            if (currentItem.type == 2998)
            {
                this.minionDamage += 0.15f;
            }
            if (currentItem.type == 935)
            {
                this.magicDamage += 0.12f;
                this.meleeDamage += 0.12f;
                this.rangedDamage += 0.12f;
                this.minionDamage += 0.12f;
            }
            if (currentItem.wingSlot != -1)
            {
                this.wingTimeMax = this.GetWingStats((int)currentItem.wingSlot).FlyTime;
            }
            if (currentItem.wingSlot == 26)
            {
                this.ignoreWater = true;
            }
            if (currentItem.type == 5452)
            {
                this.remoteVisionForDrone = true;
            }
            if (currentItem.type == 885)
            {
                this.buffImmune[30] = true;
            }
            if (currentItem.type == 886)
            {
                this.buffImmune[36] = true;
            }
            if (currentItem.type == 887)
            {
                this.buffImmune[20] = true;
            }
            if (currentItem.type == 888)
            {
                this.buffImmune[22] = true;
            }
            if (currentItem.type == 889)
            {
                this.buffImmune[32] = true;
            }
            if (currentItem.type == 890)
            {
                this.buffImmune[35] = true;
            }
            if (currentItem.type == 891)
            {
                this.buffImmune[23] = true;
            }
            if (currentItem.type == 892)
            {
                this.buffImmune[33] = true;
            }
            if (currentItem.type == 893)
            {
                this.buffImmune[31] = true;
            }
            if (currentItem.type == 3781)
            {
                this.buffImmune[156] = true;
            }
            if (currentItem.type == 901)
            {
                this.buffImmune[33] = true;
                this.buffImmune[36] = true;
            }
            if (currentItem.type == 902)
            {
                this.buffImmune[30] = true;
                this.buffImmune[20] = true;
            }
            if (currentItem.type == 903)
            {
                this.buffImmune[32] = true;
                this.buffImmune[31] = true;
            }
            if (currentItem.type == 904)
            {
                this.buffImmune[35] = true;
                this.buffImmune[23] = true;
            }
            if (currentItem.type == 5354)
            {
                this.buffImmune[22] = true;
                this.buffImmune[156] = true;
            }
            if (currentItem.type == 5355 && !this.controlDownHold)
            {
                this.shimmerImmune = true;
            }
            if (currentItem.type == 1921)
            {
                this.buffImmune[46] = true;
                this.buffImmune[47] = true;
            }
            if (currentItem.type == 1612)
            {
                this.buffImmune[33] = true;
                this.buffImmune[36] = true;
                this.buffImmune[30] = true;
                this.buffImmune[20] = true;
                this.buffImmune[32] = true;
                this.buffImmune[31] = true;
                this.buffImmune[35] = true;
                this.buffImmune[23] = true;
                this.buffImmune[22] = true;
                this.buffImmune[156] = true;
            }
            if (currentItem.type == 1613)
            {
                this.buffImmune[46] = true;
                this.noKnockback = true;
                this.fireWalk = true;
                this.buffImmune[33] = true;
                this.buffImmune[36] = true;
                this.buffImmune[30] = true;
                this.buffImmune[20] = true;
                this.buffImmune[32] = true;
                this.buffImmune[31] = true;
                this.buffImmune[35] = true;
                this.buffImmune[23] = true;
                this.buffImmune[22] = true;
                this.buffImmune[156] = true;
            }
            if (currentItem.type == 497)
            {
                this.accMerman = true;
                if (this.hideVisibleAccessory[itemSlot])
                {
                    this.hideMerman = true;
                }
            }
            if (currentItem.type == 535)
            {
                this.pStone = true;
            }
            if (currentItem.type == 536)
            {
                this.kbGlove = true;
                this.meleeScaleGlove = true;
            }
            if (currentItem.type == 532)
            {
                this.starCloakItem = currentItem;
            }
            if (currentItem.type == 554)
            {
                this.longInvince = true;
            }
            if (currentItem.type == 555)
            {
                this.manaFlower = true;
                this.manaCost -= 0.08f;
            }
            if (Main.myPlayer == this.whoAmI)
            {
                if (currentItem.type == 5104 || currentItem.type == 5105)
                {
                    this.ApplyWilsonBeard(currentItem);
                }
                else if (currentItem.type == 576 && Main.rand.Next(540) == 0 && Main.curMusic > 0 && Main.curMusic <= Main.maxMusic && MusicID.Sets.CanBeRecorded[Main.curMusic])
                {
                    SoundEngine.PlaySound(SoundID.Item166, base.Center, 0f, 1f);
                    int num3 = -1;
                    if (Main.curMusic == 1)
                    {
                        num3 = 0;
                    }
                    if (Main.curMusic == 2)
                    {
                        num3 = 1;
                    }
                    if (Main.curMusic == 3)
                    {
                        num3 = 2;
                    }
                    if (Main.curMusic == 4)
                    {
                        num3 = 4;
                    }
                    if (Main.curMusic == 5)
                    {
                        num3 = 5;
                    }
                    if (Main.curMusic == 6)
                    {
                        num3 = 3;
                    }
                    if (Main.curMusic == 7)
                    {
                        num3 = 6;
                    }
                    if (Main.curMusic == 8)
                    {
                        num3 = 7;
                    }
                    if (Main.curMusic == 9)
                    {
                        num3 = 9;
                    }
                    if (Main.curMusic == 10)
                    {
                        num3 = 8;
                    }
                    if (Main.curMusic == 11)
                    {
                        num3 = 11;
                    }
                    if (Main.curMusic == 12)
                    {
                        num3 = 10;
                    }
                    if (Main.curMusic == 13)
                    {
                        num3 = 12;
                    }
                    if (num3 > -1)
                    {
                        currentItem.SetDefaults(num3 + 562, null);
                    }
                    else if (Main.curMusic > 13 && Main.curMusic <= 27)
                    {
                        currentItem.SetDefaults(1596 + Main.curMusic - 14, null);
                    }
                    if (Main.curMusic == 28)
                    {
                        currentItem.SetDefaults(1963, null);
                    }
                    else if (Main.curMusic == 29)
                    {
                        currentItem.SetDefaults(1610, null);
                    }
                    else if (Main.curMusic == 30)
                    {
                        currentItem.SetDefaults(1963, null);
                    }
                    else if (Main.curMusic == 31)
                    {
                        currentItem.SetDefaults(1964, null);
                    }
                    else if (Main.curMusic == 32)
                    {
                        currentItem.SetDefaults(1965, null);
                    }
                    else if (Main.curMusic == 33)
                    {
                        currentItem.SetDefaults(2742, null);
                    }
                    else if (Main.curMusic == 34)
                    {
                        currentItem.SetDefaults(3370, null);
                    }
                    else if (Main.curMusic == 35)
                    {
                        currentItem.SetDefaults(3236, null);
                    }
                    else if (Main.curMusic == 36)
                    {
                        currentItem.SetDefaults(3237, null);
                    }
                    else if (Main.curMusic == 37)
                    {
                        currentItem.SetDefaults(3235, null);
                    }
                    else if (Main.curMusic == 38)
                    {
                        currentItem.SetDefaults(3044, null);
                    }
                    else if (Main.curMusic == 39)
                    {
                        currentItem.SetDefaults(3371, null);
                    }
                    else if (Main.curMusic == 40)
                    {
                        currentItem.SetDefaults(3796, null);
                    }
                    else if (Main.curMusic == 41)
                    {
                        currentItem.SetDefaults(3869, null);
                    }
                    else if (Main.curMusic == 42)
                    {
                        currentItem.SetDefaults(4079, null);
                    }
                    else if (Main.curMusic == 43)
                    {
                        currentItem.SetDefaults(4077, null);
                    }
                    else if (Main.curMusic == 44)
                    {
                        currentItem.SetDefaults(4082, null);
                    }
                    else if (Main.curMusic == 46)
                    {
                        currentItem.SetDefaults(4080, null);
                    }
                    else if (Main.curMusic == 47)
                    {
                        currentItem.SetDefaults(4081, null);
                    }
                    else if (Main.curMusic == 48)
                    {
                        currentItem.SetDefaults(4078, null);
                    }
                    else if (Main.curMusic == 49)
                    {
                        currentItem.SetDefaults(4237, null);
                    }
                    else if (Main.curMusic == 51)
                    {
                        currentItem.SetDefaults(4356, null);
                    }
                    else if (Main.curMusic == 52)
                    {
                        currentItem.SetDefaults(4357, null);
                    }
                    else if (Main.curMusic == 53)
                    {
                        currentItem.SetDefaults(4358, null);
                    }
                    else if (Main.curMusic == 54)
                    {
                        currentItem.SetDefaults(4421, null);
                    }
                    else if (Main.curMusic == 55)
                    {
                        currentItem.SetDefaults(4606, null);
                    }
                    else if (Main.curMusic == 56)
                    {
                        currentItem.SetDefaults(4979, null);
                    }
                    else if (Main.curMusic == 57)
                    {
                        currentItem.SetDefaults(4985, null);
                    }
                    else if (Main.curMusic == 58)
                    {
                        currentItem.SetDefaults(4990, null);
                    }
                    else if (Main.curMusic == 59)
                    {
                        currentItem.SetDefaults(4991, null);
                    }
                    else if (Main.curMusic == 60)
                    {
                        currentItem.SetDefaults(4992, null);
                    }
                    else if (Main.curMusic == 61)
                    {
                        currentItem.SetDefaults(5006, null);
                    }
                    else if (Main.curMusic == 62)
                    {
                        currentItem.SetDefaults(5014, null);
                    }
                    else if (Main.curMusic == 63)
                    {
                        currentItem.SetDefaults(5015, null);
                    }
                    else if (Main.curMusic == 64)
                    {
                        currentItem.SetDefaults(5016, null);
                    }
                    else if (Main.curMusic == 65)
                    {
                        currentItem.SetDefaults(5017, null);
                    }
                    else if (Main.curMusic == 66)
                    {
                        currentItem.SetDefaults(5018, null);
                    }
                    else if (Main.curMusic == 67)
                    {
                        currentItem.SetDefaults(5019, null);
                    }
                    else if (Main.curMusic == 68)
                    {
                        currentItem.SetDefaults(5020, null);
                    }
                    else if (Main.curMusic == 69)
                    {
                        currentItem.SetDefaults(5021, null);
                    }
                    else if (Main.curMusic == 70)
                    {
                        currentItem.SetDefaults(5022, null);
                    }
                    else if (Main.curMusic == 71)
                    {
                        currentItem.SetDefaults(5023, null);
                    }
                    else if (Main.curMusic == 72)
                    {
                        currentItem.SetDefaults(5024, null);
                    }
                    else if (Main.curMusic == 73)
                    {
                        currentItem.SetDefaults(5025, null);
                    }
                    else if (Main.curMusic == 74)
                    {
                        currentItem.SetDefaults(5026, null);
                    }
                    else if (Main.curMusic == 75)
                    {
                        currentItem.SetDefaults(5027, null);
                    }
                    else if (Main.curMusic == 76)
                    {
                        currentItem.SetDefaults(5028, null);
                    }
                    else if (Main.curMusic == 77)
                    {
                        currentItem.SetDefaults(5029, null);
                    }
                    else if (Main.curMusic == 78)
                    {
                        currentItem.SetDefaults(5030, null);
                    }
                    else if (Main.curMusic == 79)
                    {
                        currentItem.SetDefaults(5031, null);
                    }
                    else if (Main.curMusic == 80)
                    {
                        currentItem.SetDefaults(5032, null);
                    }
                    else if (Main.curMusic == 81)
                    {
                        currentItem.SetDefaults(5033, null);
                    }
                    else if (Main.curMusic == 82)
                    {
                        currentItem.SetDefaults(5034, null);
                    }
                    else if (Main.curMusic == 83)
                    {
                        currentItem.SetDefaults(5035, null);
                    }
                    else if (Main.curMusic == 84)
                    {
                        currentItem.SetDefaults(5036, null);
                    }
                    else if (Main.curMusic == 85)
                    {
                        currentItem.SetDefaults(5037, null);
                    }
                    else if (Main.curMusic == 86)
                    {
                        currentItem.SetDefaults(5038, null);
                    }
                    else if (Main.curMusic == 87)
                    {
                        currentItem.SetDefaults(5039, null);
                    }
                    else if (Main.curMusic == 88)
                    {
                        currentItem.SetDefaults(5040, null);
                    }
                    else if (Main.curMusic == 89)
                    {
                        currentItem.SetDefaults(5044, null);
                    }
                    else if (Main.curMusic == 90)
                    {
                        currentItem.SetDefaults(5112, null);
                    }
                    else if (Main.curMusic == 91)
                    {
                        currentItem.SetDefaults(5362, null);
                    }
                    else if (Main.curMusic == 92)
                    {
                        currentItem.SetDefaults(5582, null);
                    }
                    else if (Main.curMusic == 93)
                    {
                        currentItem.SetDefaults(5578, null);
                    }
                    else if (Main.curMusic == 94)
                    {
                        currentItem.SetDefaults(5580, null);
                    }
                    else if (Main.curMusic == 95)
                    {
                        currentItem.SetDefaults(5579, null);
                    }
                    else if (Main.curMusic == 96)
                    {
                        currentItem.SetDefaults(5538, null);
                    }
                    else if (Main.curMusic == 97)
                    {
                        currentItem.SetDefaults(5539, null);
                    }
                    else if (Main.curMusic == 98)
                    {
                        currentItem.SetDefaults(5581, null);
                    }
                    else if (Main.curMusic == 99)
                    {
                        currentItem.SetDefaults(5637, null);
                    }
                    else if (Main.curMusic == 100)
                    {
                        currentItem.SetDefaults(5639, null);
                    }
                    else if (Main.curMusic == 101)
                    {
                        currentItem.SetDefaults(5638, null);
                    }
                    else if (Main.curMusic == 104)
                    {
                        currentItem.SetDefaults(6144, null);
                    }
                    else if (Main.curMusic == 102 || Main.curMusic == 103)
                    {
                        currentItem.SetDefaults(6145, null);
                    }
                }
                this.ApplyMusicBox(currentItem);
            }
            if (this.mount.Active && this.mount.Type == 49)
            {
                this.waterWalk2 = false;
                this.waterWalk = false;
            }
        }
References Terraria.Player.AddBuff(), Terraria.Lighting.AddLight(), Terraria.ID.AmmoID.Bullet, Terraria.ID.MusicID.Sets.CanBeRecorded, Terraria.ID.AmmoID.CandyCorn, Terraria.DelegateMethods.CastLightOpen(), Terraria.Main.curMusic, Terraria.Main.dayTime, Terraria.Main.eclipse, Terraria.Main.expertMode, Terraria.Item.expertOnly, int, Terraria.ID.SoundID.Item166, Terraria.Main.maxMusic, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.PaladinsShieldRange, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.PlotTileLine(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Item.SetDefaults(), Terraria.ID.AmmoID.Solution, System.Math.Sqrt(), Terraria.ID.AmmoID.Stake, Terraria.Item.stringColor, Terraria.Player.team, Terraria.Utils.TileActionAttempt(), Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Item.type, Terraria.Item.voiceSlot, Terraria.Item.wingSlot, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.