Terraria Decompiled: Terraria.Player.Serialize
Serialize()
static void Terraria.Player.Serialize (PlayerFileData playerFile, Player newPlayer, BinaryWriter fileIO) inline static private
Definition at line 54078 of file Player.cs.
        {
            fileIO.Write(newPlayer.name);
            fileIO.Write(newPlayer.difficulty);
            fileIO.Write(playerFile.GetPlayTime().Ticks);
            fileIO.Write(newPlayer.hair);
            fileIO.Write(newPlayer.hairDye);
            fileIO.Write((byte)newPlayer.team);
            BitsByte bitsByte = 0;
            for (int i = 0; i < 8; i++)
            {
                bitsByte[i] = newPlayer.hideVisibleAccessory[i];
            }
            fileIO.Write(bitsByte);
            bitsByte = 0;
            for (int j = 0; j < 2; j++)
            {
                bitsByte[j] = newPlayer.hideVisibleAccessory[j + 8];
            }
            fileIO.Write(bitsByte);
            fileIO.Write(newPlayer.hideMisc);
            fileIO.Write((byte)newPlayer.skinVariant);
            fileIO.Write(newPlayer.statLife);
            fileIO.Write(newPlayer.statLifeMax);
            fileIO.Write(newPlayer.statMana);
            fileIO.Write(newPlayer.statManaMax);
            fileIO.Write(newPlayer.extraAccessory);
            fileIO.Write(newPlayer.unlockedBiomeTorches);
            fileIO.Write(newPlayer.UsingBiomeTorches);
            fileIO.Write(newPlayer.ateArtisanBread);
            fileIO.Write(newPlayer.usedAegisCrystal);
            fileIO.Write(newPlayer.usedAegisFruit);
            fileIO.Write(newPlayer.usedArcaneCrystal);
            fileIO.Write(newPlayer.usedGalaxyPearl);
            fileIO.Write(newPlayer.usedGummyWorm);
            fileIO.Write(newPlayer.usedAmbrosia);
            fileIO.Write(newPlayer.downedDD2EventAnyDifficulty);
            fileIO.Write(newPlayer.taxMoney);
            fileIO.Write(newPlayer.numberOfDeathsPVE);
            fileIO.Write(newPlayer.numberOfDeathsPVP);
            fileIO.Write(newPlayer.hairColor.R);
            fileIO.Write(newPlayer.hairColor.G);
            fileIO.Write(newPlayer.hairColor.B);
            fileIO.Write(newPlayer.skinColor.R);
            fileIO.Write(newPlayer.skinColor.G);
            fileIO.Write(newPlayer.skinColor.B);
            fileIO.Write(newPlayer.eyeColor.R);
            fileIO.Write(newPlayer.eyeColor.G);
            fileIO.Write(newPlayer.eyeColor.B);
            fileIO.Write(newPlayer.shirtColor.R);
            fileIO.Write(newPlayer.shirtColor.G);
            fileIO.Write(newPlayer.shirtColor.B);
            fileIO.Write(newPlayer.underShirtColor.R);
            fileIO.Write(newPlayer.underShirtColor.G);
            fileIO.Write(newPlayer.underShirtColor.B);
            fileIO.Write(newPlayer.pantsColor.R);
            fileIO.Write(newPlayer.pantsColor.G);
            fileIO.Write(newPlayer.pantsColor.B);
            fileIO.Write(newPlayer.shoeColor.R);
            fileIO.Write(newPlayer.shoeColor.G);
            fileIO.Write(newPlayer.shoeColor.B);
            for (int k = 0; k < newPlayer.armor.Length; k++)
            {
                fileIO.Write(newPlayer.armor[k].type);
                fileIO.Write(newPlayer.armor[k].prefix);
            }
            for (int l = 0; l < newPlayer.dye.Length; l++)
            {
                fileIO.Write(newPlayer.dye[l].type);
                fileIO.Write(newPlayer.dye[l].prefix);
            }
            for (int m = 0; m < 58; m++)
            {
                fileIO.Write(newPlayer.inventory[m].type);
                fileIO.Write(newPlayer.inventory[m].stack);
                fileIO.Write(newPlayer.inventory[m].prefix);
                fileIO.Write(newPlayer.inventory[m].favorited);
            }
            for (int n = 0; n < newPlayer.miscEquips.Length; n++)
            {
                fileIO.Write(newPlayer.miscEquips[n].type);
                fileIO.Write(newPlayer.miscEquips[n].prefix);
                fileIO.Write(newPlayer.miscDyes[n].type);
                fileIO.Write(newPlayer.miscDyes[n].prefix);
            }
            for (int num = 0; num < newPlayer.bank.maxItems; num++)
            {
                fileIO.Write(newPlayer.bank.item[num].type);
                fileIO.Write(newPlayer.bank.item[num].stack);
                fileIO.Write(newPlayer.bank.item[num].prefix);
            }
            for (int num2 = 0; num2 < newPlayer.bank2.maxItems; num2++)
            {
                fileIO.Write(newPlayer.bank2.item[num2].type);
                fileIO.Write(newPlayer.bank2.item[num2].stack);
                fileIO.Write(newPlayer.bank2.item[num2].prefix);
            }
            for (int num3 = 0; num3 < newPlayer.bank3.maxItems; num3++)
            {
                fileIO.Write(newPlayer.bank3.item[num3].type);
                fileIO.Write(newPlayer.bank3.item[num3].stack);
                fileIO.Write(newPlayer.bank3.item[num3].prefix);
            }
            for (int num4 = 0; num4 < newPlayer.bank4.maxItems; num4++)
            {
                fileIO.Write(newPlayer.bank4.item[num4].type);
                fileIO.Write(newPlayer.bank4.item[num4].stack);
                fileIO.Write(newPlayer.bank4.item[num4].prefix);
                fileIO.Write(newPlayer.bank4.item[num4].favorited);
            }
            fileIO.Write(newPlayer.voidVaultInfo);
            for (int num5 = 0; num5 < Player.maxBuffs; num5++)
            {
                if (Main.buffNoSave[newPlayer.buffType[num5]])
                {
                    fileIO.Write(0);
                    fileIO.Write(0);
                }
                else
                {
                    fileIO.Write(newPlayer.buffType[num5]);
                    fileIO.Write(newPlayer.buffTime[num5]);
                }
            }
            for (int num6 = 0; num6 < 200; num6++)
            {
                if (newPlayer.spN[num6] == null)
                {
                    fileIO.Write(-1);
                    break;
                }
                fileIO.Write(newPlayer.spX[num6]);
                fileIO.Write(newPlayer.spY[num6]);
                fileIO.Write(newPlayer.spI[num6]);
                fileIO.Write(newPlayer.spN[num6]);
            }
            fileIO.Write(newPlayer.hbLocked);
            for (int num7 = 0; num7 < newPlayer.hideInfo.Length; num7++)
            {
                fileIO.Write(newPlayer.hideInfo[num7]);
            }
            fileIO.Write(newPlayer.anglerQuestsFinished);
            for (int num8 = 0; num8 < newPlayer.DpadRadial.Bindings.Length; num8++)
            {
                fileIO.Write(newPlayer.DpadRadial.Bindings[num8]);
            }
            for (int num9 = 0; num9 < newPlayer.builderAccStatus.Length; num9++)
            {
                fileIO.Write(newPlayer.builderAccStatus[num9]);
            }
            fileIO.Write(newPlayer.bartenderQuestLog);
            fileIO.Write(newPlayer.dead);
            if (newPlayer.dead)
            {
                fileIO.Write(newPlayer.respawnTimer);
            }
            long num10 = DateTime.UtcNow.ToBinary();
            fileIO.Write(num10);
            fileIO.Write(newPlayer.golferScoreAccumulated);
            newPlayer.creativeTracker.Save(fileIO);
            newPlayer.SaveTemporaryItemSlotContents(fileIO);
            CreativePowerManager.Instance.SaveToPlayer(newPlayer, fileIO);
            BitsByte bitsByte2 = default(BitsByte);
            bitsByte2[0] = newPlayer.unlockedSuperCart;
            bitsByte2[1] = newPlayer.enabledSuperCart;
            fileIO.Write(bitsByte2);
            fileIO.Write(newPlayer.CurrentLoadoutIndex);
            for (int num11 = 0; num11 < newPlayer.Loadouts.Length; num11++)
            {
                newPlayer.Loadouts[num11].Serialize(fileIO);
            }
            fileIO.Write((byte)newPlayer.voiceVariant);
            fileIO.Write(newPlayer.voicePitchOffset);
            CraftingRequests.SavePossibleRefunds(fileIO);
            List<string> list = new List<string>(newPlayer.oneTimeDialoguesSeen);
            fileIO.Write(list.Count);
            foreach (string text in list)
            {
                fileIO.Write(text);
            }
        }
References Terraria.Player.anglerQuestsFinished, Terraria.Player.armor, Terraria.Player.ateArtisanBread, Microsoft.Xna.Framework.Color.B, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Player.bartenderQuestLog, Terraria.Main.buffNoSave, Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.Player.builderAccStatus, Terraria.Player.creativeTracker, Terraria.Player.CurrentLoadoutIndex, Terraria.Player.dead, Terraria.Player.difficulty, Terraria.Player.downedDD2EventAnyDifficulty, Terraria.Player.DpadRadial, Terraria.Player.dye, Terraria.Player.enabledSuperCart, Terraria.Player.extraAccessory, Terraria.Player.eyeColor, Terraria.Item.favorited, Microsoft.Xna.Framework.Color.G, Terraria.IO.PlayerFileData.GetPlayTime(), Terraria.Player.golferScoreAccumulated, Terraria.Player.hair, Terraria.Player.hairColor, Terraria.Player.hairDye, Terraria.Player.hbLocked, Terraria.Player.hideInfo, Terraria.Player.hideMisc, Terraria.Player.hideVisibleAccessory, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.Player.inventory, Terraria.Chest.item, System.list, Terraria.Player.Loadouts, Terraria.Player.maxBuffs, Terraria.Chest.maxItems, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.Player.name, Terraria.Player.numberOfDeathsPVE, Terraria.Player.numberOfDeathsPVP, Terraria.Player.oneTimeDialoguesSeen, Terraria.Player.pantsColor, Terraria.Item.prefix, Microsoft.Xna.Framework.Color.R, Terraria.Player.respawnTimer, Terraria.GameContent.Creative.CreativeUnlocksTracker.Save(), Terraria.GameContent.CraftingRequests.SavePossibleRefunds(), Terraria.Player.SaveTemporaryItemSlotContents(), Terraria.GameContent.Creative.CreativePowerManager.SaveToPlayer(), Terraria.EquipmentLoadout.Serialize(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, Terraria.Player.skinVariant, Terraria.Player.spI, Terraria.Player.spN, Terraria.Player.spX, Terraria.Player.spY, Terraria.Item.stack, Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statMana, Terraria.Player.statManaMax, Terraria.Player.taxMoney, Terraria.Player.team, System.text, System.TimeSpan.Ticks, System.DateTime.ToBinary(), Terraria.Item.type, Terraria.Player.underShirtColor, Terraria.Player.unlockedBiomeTorches, Terraria.Player.unlockedSuperCart, Terraria.Player.usedAegisCrystal, Terraria.Player.usedAegisFruit, Terraria.Player.usedAmbrosia, Terraria.Player.usedArcaneCrystal, Terraria.Player.usedGalaxyPearl, Terraria.Player.usedGummyWorm, Terraria.Player.UsingBiomeTorches, System.DateTime.UtcNow, Terraria.Player.voicePitchOffset, Terraria.Player.voiceVariant, Terraria.Player.voidVaultInfo, and System.IO.BinaryWriter.Write().
Referenced by Terraria.Player.InternalSavePlayerFile(), and Terraria.Player.SerializedClone().