Terraria Decompiled: Terraria.Player.TrySpawnDigtoiseAt
TrySpawnDigtoiseAt()
static bool Terraria.Player.TrySpawnDigtoiseAt (int owner, int shoot, IEntitySource projectileSource, int x, int y) inline static private
Definition at line 48720 of file Player.cs.
        {
            while (y < Main.maxTilesY - 10 && !WorldGen.SolidTile(x, y, false) && !WorldGen.SolidTile(x - 1, y, false) && !WorldGen.SolidTile(x + 1, y, false))
            {
                y++;
            }
            for (int i = -1; i <= 1; i++)
            {
                for (int j = -2; j <= -1; j++)
                {
                    if (WorldGen.SolidTile(x + i, y + j, false))
                    {
                        return false;
                    }
                }
            }
            Projectile.NewProjectile(projectileSource, (float)(x * 16 + 8), (float)(y * 16 - 32), 0f, 15f, shoot, 0, 0f, owner, 0f, 0f, 0f, null);
            return true;
        }
References Terraria.Main.maxTilesY, Terraria.Projectile.NewProjectile(), and Terraria.WorldGen.SolidTile().
Referenced by Terraria.Player.SpawnDigtoiseOnCursor().