Terraria Decompiled: Terraria.Player.BuyItem
BuyItem()
bool Terraria.Player.BuyItem (long price, int customCurrency = -1) inline
Definition at line 34192 of file Player.cs.
        {
            if (customCurrency != -1)
            {
                return CustomCurrencyManager.BuyItem(this, price, customCurrency);
            }
            bool flag;
            long num = Utils.CoinsCount(out flag, this.inventory, new int[] { 58, 57, 56, 55, 54 });
            long num2 = Utils.CoinsCount(out flag, this.bank.item, new int[0]);
            long num3 = Utils.CoinsCount(out flag, this.bank2.item, new int[0]);
            long num4 = Utils.CoinsCount(out flag, this.bank3.item, new int[0]);
            long num5 = Utils.CoinsCount(out flag, this.bank4.item, new int[0]);
            if (Utils.CoinsCombineStacks(out flag, new long[] { num, num2, num3, num4, num5 }) < price)
            {
                return false;
            }
            List<Item[]> list = new List<Item[]>();
            Dictionary<int, List<int>> dictionary = new Dictionary<int, List<int>>();
            List<Point> list2 = new List<Point>();
            List<Point> list3 = new List<Point>();
            List<Point> list4 = new List<Point>();
            List<Point> list5 = new List<Point>();
            List<Point> list6 = new List<Point>();
            List<Point> list7 = new List<Point>();
            list.Add(this.inventory);
            list.Add(this.bank.item);
            list.Add(this.bank2.item);
            list.Add(this.bank3.item);
            list.Add(this.bank4.item);
            for (int i = 0; i < list.Count; i++)
            {
                dictionary[i] = new List<int>();
            }
            dictionary[0] = new List<int> { 58, 57, 56, 55, 54 };
            for (int j = 0; j < list.Count; j++)
            {
                for (int k = 0; k < list[j].Length; k++)
                {
                    if (!dictionary[j].Contains(k) && list[j][k].IsACoin)
                    {
                        list3.Add(new Point(j, k));
                    }
                }
            }
            int num6 = 0;
            for (int l = list[num6].Length - 1; l >= 0; l--)
            {
                if (!dictionary[num6].Contains(l) && (list[num6][l].type == 0 || list[num6][l].stack == 0))
                {
                    list2.Add(new Point(num6, l));
                }
            }
            num6 = 1;
            for (int m = list[num6].Length - 1; m >= 0; m--)
            {
                if (!dictionary[num6].Contains(m) && (list[num6][m].type == 0 || list[num6][m].stack == 0))
                {
                    list4.Add(new Point(num6, m));
                }
            }
            num6 = 2;
            for (int n = list[num6].Length - 1; n >= 0; n--)
            {
                if (!dictionary[num6].Contains(n) && (list[num6][n].type == 0 || list[num6][n].stack == 0))
                {
                    list5.Add(new Point(num6, n));
                }
            }
            num6 = 3;
            for (int num7 = list[num6].Length - 1; num7 >= 0; num7--)
            {
                if (!dictionary[num6].Contains(num7) && (list[num6][num7].type == 0 || list[num6][num7].stack == 0))
                {
                    list6.Add(new Point(num6, num7));
                }
            }
            num6 = 4;
            for (int num8 = list[num6].Length - 1; num8 >= 0; num8--)
            {
                if (!dictionary[num6].Contains(num8) && (list[num6][num8].type == 0 || list[num6][num8].stack == 0))
                {
                    list7.Add(new Point(num6, num8));
                }
            }
            return !Player.TryPurchasing(price, list, list3, list2, list4, list5, list6, list7);
        }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.GameContent.UI.CustomCurrencyManager.BuyItem(), Terraria.Utils.CoinsCombineStacks(), Terraria.Utils.CoinsCount(), Microsoft.Xna.Framework.Contains, System.dictionary, System.list, System.stack, and Terraria.Player.TryPurchasing().
Referenced by Terraria.Main.DrawHairWindow(), Terraria.Main.DrawInventory(), Terraria.UI.ItemSlot.HandleShopSlot(), and Terraria.Main.NPCChatText_DoNurseHeal().