Terraria Decompiled: Terraria.Player.Deserialize
Deserialize()
static void Terraria.Player.Deserialize (PlayerFileData data, Player newPlayer, BinaryReader fileIO, int release, out bool gotToReadName) inline static private
Definition at line 54474 of file Player.cs.
        {
            gotToReadName = false;
            newPlayer.name = fileIO.ReadString();
            gotToReadName = true;
            if (release >= 10)
            {
                if (release >= 17)
                {
                    newPlayer.difficulty = fileIO.ReadByte();
                }
                else if (fileIO.ReadBoolean())
                {
                    newPlayer.difficulty = 2;
                }
            }
            if (release >= 138)
            {
                data.SetPlayTime(new TimeSpan(fileIO.ReadInt64()));
            }
            else
            {
                data.SetPlayTime(TimeSpan.Zero);
            }
            newPlayer.hair = fileIO.ReadInt32();
            if (newPlayer.hair >= 228)
            {
                newPlayer.hair = 0;
            }
            if (release >= 82)
            {
                newPlayer.hairDye = fileIO.ReadByte();
            }
            if (release >= 283)
            {
                newPlayer.team = (int)fileIO.ReadByte();
            }
            if (release >= 124)
            {
                BitsByte bitsByte = fileIO.ReadByte();
                for (int i = 0; i < 8; i++)
                {
                    newPlayer.hideVisibleAccessory[i] = bitsByte[i];
                }
                bitsByte = fileIO.ReadByte();
                for (int j = 0; j < 2; j++)
                {
                    newPlayer.hideVisibleAccessory[j + 8] = bitsByte[j];
                }
            }
            else if (release >= 83)
            {
                BitsByte bitsByte2 = fileIO.ReadByte();
                for (int k = 0; k < 8; k++)
                {
                    newPlayer.hideVisibleAccessory[k] = bitsByte2[k];
                }
            }
            if (release >= 119)
            {
                newPlayer.hideMisc = fileIO.ReadByte();
            }
            if (release <= 17)
            {
                if (newPlayer.hair == 5 || newPlayer.hair == 6 || newPlayer.hair == 9 || newPlayer.hair == 11)
                {
                    newPlayer.Male = false;
                }
                else
                {
                    newPlayer.Male = true;
                }
            }
            else if (release < 107)
            {
                newPlayer.Male = fileIO.ReadBoolean();
            }
            else
            {
                newPlayer.skinVariant = (int)fileIO.ReadByte();
            }
            if (release < 161 && newPlayer.skinVariant == 7)
            {
                newPlayer.skinVariant = 9;
            }
            newPlayer.statLife = fileIO.ReadInt32();
            newPlayer.statLifeMax = fileIO.ReadInt32();
            if (newPlayer.statLifeMax > 500)
            {
                newPlayer.statLifeMax = 500;
            }
            newPlayer.statMana = fileIO.ReadInt32();
            newPlayer.statManaMax = fileIO.ReadInt32();
            if (newPlayer.statManaMax > 200)
            {
                newPlayer.statManaMax = 200;
            }
            if (newPlayer.statMana > 400)
            {
                newPlayer.statMana = 400;
            }
            if (release >= 125)
            {
                newPlayer.extraAccessory = fileIO.ReadBoolean();
            }
            if (release >= 229)
            {
                newPlayer.unlockedBiomeTorches = fileIO.ReadBoolean();
                newPlayer.UsingBiomeTorches = fileIO.ReadBoolean();
                if (release >= 256)
                {
                    newPlayer.ateArtisanBread = fileIO.ReadBoolean();
                }
                if (release >= 260)
                {
                    newPlayer.usedAegisCrystal = fileIO.ReadBoolean();
                    newPlayer.usedAegisFruit = fileIO.ReadBoolean();
                    newPlayer.usedArcaneCrystal = fileIO.ReadBoolean();
                    newPlayer.usedGalaxyPearl = fileIO.ReadBoolean();
                    newPlayer.usedGummyWorm = fileIO.ReadBoolean();
                    newPlayer.usedAmbrosia = fileIO.ReadBoolean();
                }
            }
            if (release >= 182)
            {
                newPlayer.downedDD2EventAnyDifficulty = fileIO.ReadBoolean();
            }
            if (release >= 128)
            {
                newPlayer.taxMoney = fileIO.ReadInt32();
            }
            if (release >= 254)
            {
                newPlayer.numberOfDeathsPVE = fileIO.ReadInt32();
            }
            if (release >= 254)
            {
                newPlayer.numberOfDeathsPVP = fileIO.ReadInt32();
            }
            newPlayer.hairColor = fileIO.ReadRGB();
            newPlayer.skinColor = fileIO.ReadRGB();
            newPlayer.eyeColor = fileIO.ReadRGB();
            newPlayer.shirtColor = fileIO.ReadRGB();
            newPlayer.underShirtColor = fileIO.ReadRGB();
            newPlayer.pantsColor = fileIO.ReadRGB();
            newPlayer.shoeColor = fileIO.ReadRGB();
            Main.player[Main.myPlayer].hairColor = newPlayer.hairColor;
            Main.player[Main.myPlayer].skinColor = newPlayer.skinColor;
            Main.player[Main.myPlayer].eyeColor = newPlayer.eyeColor;
            Main.player[Main.myPlayer].shirtColor = newPlayer.shirtColor;
            Main.player[Main.myPlayer].underShirtColor = newPlayer.underShirtColor;
            Main.player[Main.myPlayer].pantsColor = newPlayer.pantsColor;
            Main.player[Main.myPlayer].shoeColor = newPlayer.shoeColor;
            if (release >= 38)
            {
                if (release < 124)
                {
                    int num = 11;
                    if (release >= 81)
                    {
                        num = 16;
                    }
                    for (int l = 0; l < num; l++)
                    {
                        int num2 = l;
                        if (num2 >= 8)
{
                            num2 += 2;
                        }
                        newPlayer.armor[num2].netDefaults(fileIO.ReadInt32());
                        newPlayer.armor[num2].Prefix((int)fileIO.ReadByte());
                    }
                }
                else
                {
                    int num3 = 20;
                    for (int m = 0; m < num3; m++)
                    {
                        newPlayer.armor[m].netDefaults(fileIO.ReadInt32());
                        newPlayer.armor[m].Prefix((int)fileIO.ReadByte());
                    }
                }
                if (release >= 47)
                {
                    int num4 = 3;
                    if (release >= 81)
                    {
                        num4 = 8;
                    }
                    if (release >= 124)
                    {
                        num4 = 10;
                    }
                    for (int n = 0; n < num4; n++)
                    {
                        int num5 = n;
                        newPlayer.dye[num5].netDefaults(fileIO.ReadInt32());
                        newPlayer.dye[num5].Prefix((int)fileIO.ReadByte());
                    }
                }
                if (release >= 58)
                {
                    for (int num6 = 0; num6 < 58; num6++)
                    {
                        int num7 = fileIO.ReadInt32();
                        if (num7 >= (int)ItemID.Count)
{
                            newPlayer.inventory[num6].netDefaults(0);
                            fileIO.ReadInt32();
                            fileIO.ReadByte();
                            if (release >= 114)
{
                                fileIO.ReadBoolean();
                            }
                        }
                        else
{
                            newPlayer.inventory[num6].netDefaults(num7);
                            newPlayer.inventory[num6].stack = fileIO.ReadInt32();
                            newPlayer.inventory[num6].Prefix((int)fileIO.ReadByte());
                            if (release >= 114)
{
                                newPlayer.inventory[num6].favorited = fileIO.ReadBoolean();
                            }
                        }
                    }
                }
                else
                {
                    for (int num8 = 0; num8 < 48; num8++)
                    {
                        int num9 = fileIO.ReadInt32();
                        if (num9 >= (int)ItemID.Count)
{
                            newPlayer.inventory[num8].netDefaults(0);
                            fileIO.ReadInt32();
                            fileIO.ReadByte();
                        }
                        else
{
                            newPlayer.inventory[num8].netDefaults(num9);
                            newPlayer.inventory[num8].stack = fileIO.ReadInt32();
                            newPlayer.inventory[num8].Prefix((int)fileIO.ReadByte());
                        }
                    }
                }
                if (release >= 117)
                {
                    if (release < 136)
                    {
                        for (int num10 = 0; num10 < 5; num10++)
{
                            if (num10 != 1)
{
                                int num11 = fileIO.ReadInt32();
                                if (num11 >= (int)ItemID.Count)
{
                                    newPlayer.miscEquips[num10].netDefaults(0);
                                    fileIO.ReadByte();
                                }
                                else
{
                                    newPlayer.miscEquips[num10].netDefaults(num11);
                                    newPlayer.miscEquips[num10].Prefix((int)fileIO.ReadByte());
                                }
                                num11 = fileIO.ReadInt32();
                                if (num11 >= (int)ItemID.Count)
{
                                    newPlayer.miscDyes[num10].netDefaults(0);
                                    fileIO.ReadByte();
                                }
                                else
{
                                    newPlayer.miscDyes[num10].netDefaults(num11);
                                    newPlayer.miscDyes[num10].Prefix((int)fileIO.ReadByte());
                                }
                            }
                        }
                    }
                    else
                    {
                        for (int num12 = 0; num12 < 5; num12++)
{
                            int num13 = fileIO.ReadInt32();
                            if (num13 >= (int)ItemID.Count)
{
                                newPlayer.miscEquips[num12].netDefaults(0);
                                fileIO.ReadByte();
                            }
                            else
{
                                newPlayer.miscEquips[num12].netDefaults(num13);
                                newPlayer.miscEquips[num12].Prefix((int)fileIO.ReadByte());
                            }
                            num13 = fileIO.ReadInt32();
                            if (num13 >= (int)ItemID.Count)
{
                                newPlayer.miscDyes[num12].netDefaults(0);
                                fileIO.ReadByte();
                            }
                            else
{
                                newPlayer.miscDyes[num12].netDefaults(num13);
                                newPlayer.miscDyes[num12].Prefix((int)fileIO.ReadByte());
                            }
                        }
                    }
                }
                if (release >= 58)
                {
                    for (int num14 = 0; num14 < 40; num14++)
                    {
                        newPlayer.bank.item[num14].netDefaults(fileIO.ReadInt32());
                        newPlayer.bank.item[num14].stack = fileIO.ReadInt32();
                        newPlayer.bank.item[num14].Prefix((int)fileIO.ReadByte());
                    }
                    for (int num15 = 0; num15 < 40; num15++)
                    {
                        newPlayer.bank2.item[num15].netDefaults(fileIO.ReadInt32());
                        newPlayer.bank2.item[num15].stack = fileIO.ReadInt32();
                        newPlayer.bank2.item[num15].Prefix((int)fileIO.ReadByte());
                    }
                }
                else
                {
                    for (int num16 = 0; num16 < 20; num16++)
                    {
                        newPlayer.bank.item[num16].netDefaults(fileIO.ReadInt32());
                        newPlayer.bank.item[num16].stack = fileIO.ReadInt32();
                        newPlayer.bank.item[num16].Prefix((int)fileIO.ReadByte());
                    }
                    for (int num17 = 0; num17 < 20; num17++)
                    {
                        newPlayer.bank2.item[num17].netDefaults(fileIO.ReadInt32());
                        newPlayer.bank2.item[num17].stack = fileIO.ReadInt32();
                        newPlayer.bank2.item[num17].Prefix((int)fileIO.ReadByte());
                    }
                }
                if (release >= 182)
                {
                    for (int num18 = 0; num18 < 40; num18++)
                    {
                        newPlayer.bank3.item[num18].netDefaults(fileIO.ReadInt32());
                        newPlayer.bank3.item[num18].stack = fileIO.ReadInt32();
                        newPlayer.bank3.item[num18].Prefix((int)fileIO.ReadByte());
                    }
                }
                if (release >= 198)
                {
                    for (int num19 = 0; num19 < 40; num19++)
                    {
                        newPlayer.bank4.item[num19].netDefaults(fileIO.ReadInt32());
                        newPlayer.bank4.item[num19].stack = fileIO.ReadInt32();
                        newPlayer.bank4.item[num19].Prefix((int)fileIO.ReadByte());
                        if (release >= 255)
{
                            newPlayer.bank4.item[num19].favorited = fileIO.ReadBoolean();
                        }
                    }
                }
                if (release >= 199)
                {
                    newPlayer.voidVaultInfo = fileIO.ReadByte();
                }
            }
            else
            {
                for (int num20 = 0; num20 < 8; num20++)
                {
                    newPlayer.armor[num20].SetDefaults((int)ItemID.FromLegacyName(fileIO.ReadString(), release), null);
                    if (release >= 36)
                    {
                        newPlayer.armor[num20].Prefix((int)fileIO.ReadByte());
                    }
                }
                if (release >= 6)
                {
                    for (int num21 = 10; num21 < 13; num21++)
                    {
                        newPlayer.armor[num21].SetDefaults((int)ItemID.FromLegacyName(fileIO.ReadString(), release), null);
                        if (release >= 36)
{
                            newPlayer.armor[num21].Prefix((int)fileIO.ReadByte());
                        }
                    }
                }
                for (int num22 = 0; num22 < 44; num22++)
                {
                    newPlayer.inventory[num22].SetDefaults((int)ItemID.FromLegacyName(fileIO.ReadString(), release), null);
                    newPlayer.inventory[num22].stack = fileIO.ReadInt32();
                    if (release >= 36)
                    {
                        newPlayer.inventory[num22].Prefix((int)fileIO.ReadByte());
                    }
                }
                if (release >= 15)
                {
                    for (int num23 = 44; num23 < 48; num23++)
                    {
                        newPlayer.inventory[num23].SetDefaults((int)ItemID.FromLegacyName(fileIO.ReadString(), release), null);
                        newPlayer.inventory[num23].stack = fileIO.ReadInt32();
                        if (release >= 36)
{
                            newPlayer.inventory[num23].Prefix((int)fileIO.ReadByte());
                        }
                    }
                }
                for (int num24 = 0; num24 < 20; num24++)
                {
                    newPlayer.bank.item[num24].SetDefaults((int)ItemID.FromLegacyName(fileIO.ReadString(), release), null);
                    newPlayer.bank.item[num24].stack = fileIO.ReadInt32();
                    if (release >= 36)
                    {
                        newPlayer.bank.item[num24].Prefix((int)fileIO.ReadByte());
                    }
                }
                if (release >= 20)
                {
                    for (int num25 = 0; num25 < 20; num25++)
                    {
                        newPlayer.bank2.item[num25].SetDefaults((int)ItemID.FromLegacyName(fileIO.ReadString(), release), null);
                        newPlayer.bank2.item[num25].stack = fileIO.ReadInt32();
                        if (release >= 36)
{
                            newPlayer.bank2.item[num25].Prefix((int)fileIO.ReadByte());
                        }
                    }
                }
            }
            if (release < 58)
            {
                for (int num26 = 40; num26 < 48; num26++)
                {
                    newPlayer.inventory[num26 + 10] = newPlayer.inventory[num26].Clone();
                    newPlayer.inventory[num26].SetDefaults(0, null);
                }
            }
            if (release >= 11)
            {
                int num27 = 22;
                if (release < 74)
                {
                    num27 = 10;
                }
                if (release >= 252)
                {
                    num27 = 44;
                }
                for (int num28 = 0; num28 < num27; num28++)
                {
                    newPlayer.buffType[num28] = fileIO.ReadInt32();
                    newPlayer.buffTime[num28] = fileIO.ReadInt32();
                    if (newPlayer.buffType[num28] == 0)
                    {
                        num28--;
                        num27--;
                    }
                }
            }
            for (int num29 = 0; num29 < 200; num29++)
            {
                int num30 = fileIO.ReadInt32();
                if (num30 == -1)
                {
                    break;
                }
                newPlayer.spX[num29] = num30;
                newPlayer.spY[num29] = fileIO.ReadInt32();
                newPlayer.spI[num29] = fileIO.ReadInt32();
                newPlayer.spN[num29] = fileIO.ReadString();
            }
            if (release >= 16)
            {
                newPlayer.hbLocked = fileIO.ReadBoolean();
            }
            if (release >= 115)
            {
                int num31 = 13;
                for (int num32 = 0; num32 < num31; num32++)
                {
                    newPlayer.hideInfo[num32] = fileIO.ReadBoolean();
                }
            }
            if (release >= 98)
            {
                newPlayer.anglerQuestsFinished = fileIO.ReadInt32();
            }
            if (release >= 162)
            {
                for (int num33 = 0; num33 < 4; num33++)
                {
                    newPlayer.DpadRadial.Bindings[num33] = fileIO.ReadInt32();
                }
            }
            if (release >= 164)
            {
                int num34 = 8;
                if (release >= 167)
                {
                    num34 = 10;
                }
                if (release >= 197)
                {
                    num34 = 11;
                }
                if (release >= 230)
                {
                    num34 = 12;
                }
                for (int num35 = 0; num35 < num34; num35++)
                {
                    newPlayer.builderAccStatus[num35] = fileIO.ReadInt32();
                }
                if (release < 210)
                {
                    newPlayer.builderAccStatus[0] = 1;
                }
                if (release < 249)
                {
                    bool flag = false;
                    for (int num36 = 0; num36 < 58; num36++)
                    {
                        if (newPlayer.inventory[num36].type == 3611)
{
                            flag = true;
                            break;
                        }
                    }
                    if (flag)
                    {
                        newPlayer.builderAccStatus[1] = 1;
                    }
                }
            }
            if (release >= 181)
            {
                newPlayer.bartenderQuestLog = fileIO.ReadInt32();
            }
            if (release >= 200)
            {
                newPlayer.dead = fileIO.ReadBoolean();
                if (newPlayer.dead)
                {
                    newPlayer.respawnTimer = Utils.Clamp<int>(fileIO.ReadInt32(), 0, 60000);
                }
            }
            newPlayer.lastTimePlayerWasSaved = 0L;
            if (release >= 202)
            {
                newPlayer.lastTimePlayerWasSaved = fileIO.ReadInt64();
            }
            if (release >= 206)
            {
                newPlayer.golferScoreAccumulated = fileIO.ReadInt32();
            }
            if (release >= 218)
            {
                newPlayer.creativeTracker.Load(fileIO, release);
            }
            if (release >= 214)
            {
                newPlayer.LoadTemporaryItemSlotContents(fileIO);
            }
            newPlayer.savedPerPlayerFieldsThatArentInThePlayerClass = new Player.SavedPlayerDataWithAnnoyingRules();
            CreativePowerManager.Instance.ResetDataForNewPlayer(newPlayer);
            if (release >= 220)
            {
                CreativePowerManager.Instance.LoadToPlayer(newPlayer, fileIO, release);
            }
            if (release >= 253)
            {
                BitsByte bitsByte3 = fileIO.ReadByte();
                newPlayer.unlockedSuperCart = bitsByte3[0];
                newPlayer.enabledSuperCart = bitsByte3[1];
            }
            else
            {
                newPlayer.unlockedSuperCart = newPlayer.HasItemInAnyInventory(3353);
            }
            if (release >= 262)
            {
                int num37 = fileIO.ReadInt32();
                newPlayer.CurrentLoadoutIndex = Utils.Clamp<int>(num37, 0, newPlayer.Loadouts.Length - 1);
                for (int num38 = 0; num38 < newPlayer.Loadouts.Length; num38++)
                {
                    newPlayer.Loadouts[num38].Deserialize(fileIO, release);
                }
            }
            if (release >= 280)
            {
                newPlayer.voiceVariant = (int)fileIO.ReadByte();
            }
            else
            {
                newPlayer.skinVariant = (int)MathHelper.Clamp((float)newPlayer.skinVariant, 0f, (float)(PlayerVariantID.Count - 1));
                newPlayer.voiceVariant = (newPlayer.Male ? 1 : 2);
                newPlayer.voicePitchOffset = 0f;
            }
            if (release >= 281)
            {
                newPlayer.voicePitchOffset = fileIO.ReadSingle();
            }
            else
            {
                newPlayer.voicePitchOffset = 0f;
            }
            if (release >= 300)
            {
                newPlayer._pendingRefunds = new Item[fileIO.ReadInt32()];
                for (int num39 = 0; num39 < newPlayer._pendingRefunds.Length; num39++)
                {
                    newPlayer._pendingRefunds[num39] = new Item();
                    newPlayer._pendingRefunds[num39].DeserializeFrom(fileIO, ItemSerializationContext.SavingAndLoading);
                }
            }
            if (release >= 310)
            {
                int num40 = fileIO.ReadInt32();
                for (int num41 = 0; num41 < num40; num41++)
                {
                    newPlayer.oneTimeDialoguesSeen.Add(fileIO.ReadString());
                }
            }
            Player.LoadPlayer_LastMinuteFixes(newPlayer);
        }
References Terraria.Player._pendingRefunds, Terraria.Player.armor, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.Player.builderAccStatus, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Utils.Clamp(), Terraria.Item.Clone(), Terraria.ID.ItemID.Count, Terraria.ID.PlayerVariantID.Count, Terraria.Player.creativeTracker, Terraria.Player.dead, Terraria.EquipmentLoadout.Deserialize(), Terraria.Item.DeserializeFrom(), Terraria.Player.DpadRadial, Terraria.Player.dye, Terraria.Player.eyeColor, Terraria.Item.favorited, Terraria.ID.ItemID.FromLegacyName(), Terraria.Player.hair, Terraria.Player.hairColor, Terraria.Player.HasItemInAnyInventory(), Terraria.Player.hideInfo, Terraria.Player.hideVisibleAccessory, Terraria.GameContent.Creative.CreativePowerManager.Instance, int, Terraria.Player.inventory, Terraria.Chest.item, System.L, Terraria.GameContent.Creative.CreativeUnlocksTracker.Load(), Terraria.Player.Loadouts, Terraria.Player.LoadPlayer_LastMinuteFixes(), Terraria.Player.LoadTemporaryItemSlotContents(), Terraria.GameContent.Creative.CreativePowerManager.LoadToPlayer(), Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.Main.myPlayer, Terraria.Item.netDefaults(), Terraria.Player.oneTimeDialoguesSeen, Terraria.Player.pantsColor, Terraria.Main.player, Terraria.Item.Prefix(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), Terraria.GameContent.Creative.CreativePowerManager.ResetDataForNewPlayer(), Terraria.Item.SetDefaults(), Terraria.IO.PlayerFileData.SetPlayTime(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, Terraria.Player.skinVariant, Terraria.Player.spI, Terraria.Player.spN, Terraria.Player.spX, Terraria.Player.spY, Terraria.Item.stack, Terraria.Player.statLifeMax, Terraria.Player.statMana, Terraria.Player.statManaMax, Terraria.Item.type, Terraria.Player.underShirtColor, and System.TimeSpan.Zero.
Referenced by Terraria.Player.LoadPlayer(), and Terraria.Player.SerializedClone().