Terraria Decompiled: Terraria.Player.ItemCheck_CheckCanUse_KillDirtBlock
ItemCheck_CheckCanUse_KillDirtBlock()
bool Terraria.Player.ItemCheck_CheckCanUse_KillDirtBlock (Item sItem) inline private
Definition at line 51636 of file Player.cs.
        {
            if (sItem.shoot == 17 && this.whoAmI == Main.myPlayer)
            {
                int num;
                int num2;
                this.GetTargetTileWithReverseGravity(out num, out num2);
                if (Player.ItemCheck_IsValidDirtRodTarget(Main.tile[num, num2]))
                {
                    WorldGen.KillTile(num, num2, false, false, true);
                    if (!Main.tile[num, num2].active())
                    {
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 4, (float)num, (float)num2, 0f, 0, 0, 0);
                        }
                        return true;
                    }
                }
                return false;
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Player.ItemCheck_IsValidDirtRodTarget(), Terraria.WorldGen.KillTile(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Item.shoot, and Terraria.Main.tile.