Terraria Decompiled: Terraria.Player.WallClimbMovement
WallClimbMovement()
void Terraria.Player.WallClimbMovement () inline
Definition at line 19989 of file Player.cs.
        {
            bool flag = this.mount.Active && this.mount.Type == 55;
            if (!flag)
            {
                return;
            }
            this.sliding = false;
            if (this.slideDir != 0 && ((this.controlLeft && this.slideDir == -1) || (this.controlRight && this.slideDir == 1)))
            {
                bool flag2 = false;
                float num = this.position.X;
                if (this.slideDir == 1)
                {
                    num += (float)this.width;
                }
                num += (float)this.slideDir;
                float num2 = this.position.Y + (float)this.height + 1f;
                if (this.gravDir < 0f)
                {
                    num2 = this.position.Y - 1f;
                }
                num /= 16f;
                num2 /= 16f;
                if (WorldGen.SolidTile((int)num, (int)num2, false))
                {
                    flag2 = true;
                }
                bool flag3 = (this.controlDown && this.gravDir == -1f) || (this.controlUp && this.gravDir == 1f);
                bool flag4 = (this.controlDown && this.gravDir == 1f) || (this.controlUp && this.gravDir == -1f);
                if (this.spikedBoots >= 2)
                {
                    if (flag2 && (flag3 || flag4 || (this.velocity.Y > 0f && this.gravDir == 1f) || (this.velocity.Y < this.gravity && this.gravDir == -1f)))
                    {
                        float num3 = this.gravity;
                        if (this.slowFall)
{
                            if (this.TryingToHoverUp)
{
                                num3 = this.gravity / 10f * this.gravDir;
                            }
                            else
{
                                num3 = this.gravity / 3f * this.gravDir;
                            }
                        }
                        this.fallStart = (int)(this.position.Y / 16f);
                        if (flag3)
{
                            this.velocity.Y = -3f * this.gravDir;
                            if (!flag || !WorldGen.SolidTile((base.Center + new Vector2(0f, this.velocity.Y).SafeNormalize(Vector2.Zero) * 10f).ToTileCoordinates()))
{
                                int num4 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) + (float)((this.width / 2 - 4) * this.slideDir), this.position.Y + (float)(this.height / 2) + (float)(this.height / 2 - 4) * this.gravDir), 8, 8, 31, 0f, 0f, 0, default(Color), 1f);
                                if (this.slideDir < 0)
{
                                    Dust dust = Main.dust[num4];
                                    dust.position.X = dust.position.X - 10f;
                                }
                                if (this.gravDir < 0f)
{
                                    Dust dust2 = Main.dust[num4];
                                    dust2.position.Y = dust2.position.Y - 12f;
                                }
                                Main.dust[num4].velocity *= 0.1f;
                                Main.dust[num4].scale *= 1.2f;
                                Main.dust[num4].noGravity = true;
                                Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(this.cShoe, this);
                                if (flag)
{
                                    Main.dust[num4].scale *= 0.5f;
                                }
                            }
                        }
                        else if (flag4)
{
                            this.velocity.Y = 4f * this.gravDir;
                            if (!flag || !WorldGen.SolidTile((base.Center + new Vector2(0f, this.velocity.Y).SafeNormalize(Vector2.Zero) * 10f).ToTileCoordinates()))
{
                                int num5 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) + (float)((this.width / 2 - 4) * this.slideDir), this.position.Y + (float)(this.height / 2) + (float)(this.height / 2 - 4) * this.gravDir), 8, 8, 31, 0f, 0f, 0, default(Color), 1f);
                                if (this.slideDir < 0)
{
                                    Dust dust3 = Main.dust[num5];
                                    dust3.position.X = dust3.position.X - 10f;
                                }
                                if (this.gravDir < 0f)
{
                                    Dust dust4 = Main.dust[num5];
                                    dust4.position.Y = dust4.position.Y - 12f;
                                }
                                Main.dust[num5].velocity *= 0.1f;
                                Main.dust[num5].scale *= 1.2f;
                                Main.dust[num5].noGravity = true;
                                Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(this.cShoe, this);
                                if (flag)
{
                                    Main.dust[num5].scale *= 0.5f;
                                }
                            }
                        }
                        else if (this.gravDir == -1f)
{
                            this.velocity.Y = (-num3 + 1E-05f) * this.gravDir;
                        }
                        else
{
                            this.velocity.Y = (-num3 + 1E-05f) * this.gravDir;
                        }
                        this.sliding = true;
                        return;
                    }
                }
                else if (flag2 && (flag3 || flag4 || (this.velocity.Y > 0.5f && this.gravDir == 1f) || (this.velocity.Y < -0.5f && this.gravDir == -1f)))
                {
                    this.fallStart = (int)(this.position.Y / 16f);
                    if (this.controlUp)
                    {
                        this.velocity.Y = -2f * this.gravDir;
                    }
                    else if (this.controlDown)
                    {
                        this.velocity.Y = 4f * this.gravDir;
                    }
                    else
                    {
                        this.velocity.Y = 0.5f * this.gravDir;
                    }
                    this.sliding = true;
                    if (!flag || !WorldGen.SolidTile((base.Center + new Vector2(0f, this.velocity.Y).SafeNormalize(Vector2.Zero) * 10f).ToTileCoordinates()))
                    {
                        int num6 = Dust.NewDust(new Vector2(this.position.X + (float)(this.width / 2) + (float)((this.width / 2 - 4) * this.slideDir), this.position.Y + (float)(this.height / 2) + (float)(this.height / 2 - 4) * this.gravDir), 8, 8, 31, 0f, 0f, 0, default(Color), 1f);
                        if (this.slideDir < 0)
{
                            Dust dust5 = Main.dust[num6];
                            dust5.position.X = dust5.position.X - 10f;
                        }
                        if (this.gravDir < 0f)
{
                            Dust dust6 = Main.dust[num6];
                            dust6.position.Y = dust6.position.Y - 12f;
                        }
                        Main.dust[num6].velocity *= 0.1f;
                        Main.dust[num6].scale *= 1.2f;
                        Main.dust[num6].noGravity = true;
                        Main.dust[num6].shader = GameShaders.Armor.GetSecondaryShader(this.cShoe, this);
                        if (flag)
{
                            Main.dust[num6].scale *= 0.5f;
                        }
                    }
                }
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.dust, System.E, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), int, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Dust.scale, Terraria.Dust.shader, Terraria.WorldGen.SolidTile(), Terraria.Dust.velocity, and Microsoft.Xna.Framework.Vector2.Zero.