Terraria Decompiled: Terraria.Player.DoUnbreakableWallScan
DoUnbreakableWallScan()
void Terraria.Player.DoUnbreakableWallScan (bool force = false) inline private
Definition at line 26982 of file Player.cs.
        {
            if (!Main.dualDungeonsSeed)
            {
                return;
            }
            if (Main.netMode == 1)
            {
                return;
            }
            Vector2 center = base.Center;
            if (!force)
            {
                int num = this._unbreakableWallScanCooldown - 1;
                this._unbreakableWallScanCooldown = num;
                if (num > 0 && Vector2.Distance(center, this._unbreakableWallScanLastPosition) < (float)Player.UnbreakableWallRescanDistance)
                {
                    return;
                }
            }
            bool flag = this.insideUnbreakableWalls;
            this.insideUnbreakableWalls = UnbreakableWallScan.InsideUnbreakableWalls(center.ToTileCoordinates());
            this._unbreakableWallScanCooldown = Player.UnbreakableWallRescanPeriod;
            this._unbreakableWallScanLastPosition = center;
            if (this.insideUnbreakableWalls != flag && Main.netMode == 2)
            {
                UnbreakableWallScan.NetModule.BroadcastChange(this);
            }
        }
References Terraria.GameContent.UnbreakableWallScan.NetModule.BroadcastChange(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dualDungeonsSeed, Terraria.GameContent.UnbreakableWallScan.InsideUnbreakableWalls(), Terraria.Main.netMode, Terraria.Player.UnbreakableWallRescanDistance, and Terraria.Player.UnbreakableWallRescanPeriod.