Terraria Decompiled: Terraria.Player.ApplyPotionDelay
ApplyPotionDelay()
void Terraria.Player.ApplyPotionDelay (Item sItem) inline private
Definition at line 51211 of file Player.cs.
        {
            if (sItem.type == 3001)
            {
                int num = 2400;
                int num2 = 4200;
                this.potionDelay = Main.rand.Next(num, num2 + 1);
                if (this.pStone)
                {
                    this.potionDelay = (int)((float)this.potionDelay * Player.PhilosopherStoneDurationMultiplier);
                }
                this.AddBuff(21, this.potionDelay, false);
                return;
            }
            if (sItem.type == 227 || sItem.type == 126)
            {
                this.potionDelay = this.restorationDelayTime;
                this.AddBuff(21, this.potionDelay, false);
                return;
            }
            if (sItem.type == 1912)
            {
                this.potionDelay = this.eggnogDelayTime;
                this.AddBuff(21, this.potionDelay, false);
                this.TryToResetHungerToNeutral();
                return;
            }
            if (sItem.type == 5)
            {
                this.potionDelay = this.mushroomDelayTime;
                this.AddBuff(21, this.potionDelay, false);
                this.TryToResetHungerToNeutral();
                return;
            }
            this.potionDelay = this.potionDelayTime;
            this.AddBuff(21, this.potionDelay, false);
        }
References int, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.PhilosopherStoneDurationMultiplier, Terraria.Main.rand, and Terraria.Item.type.
Referenced by Terraria.Player.QuickHeal(), and Terraria.Player.QuickMana().