Terraria Decompiled: Terraria.Player.Spawn_SetPositionAtTeamSpawn
Spawn_SetPositionAtTeamSpawn()
void Terraria.Player.Spawn_SetPositionAtTeamSpawn (PlayerSpawnContext context) inline private
Definition at line 36888 of file Player.cs.
        {
            if (!Main.teamBasedSpawnsSeed)
            {
                return;
            }
            Point zero = Point.Zero;
            if (!ExtraSpawnPointManager.TryGetExtraSpawnPointForTeam(this.team, out zero))
            {
                return;
            }
            int x = zero.X;
            int y = zero.Y;
            bool flag = this.Spawn_GetPositionAtSpawn(zero.X, zero.Y, ref x, ref y);
            this.Spawn_SetPosition(x, y);
            if (flag && !Player.Spawn_IsAreaValidSpawn(x, y, false))
            {
                Player.Spawn_ForceClearArea(x, y);
            }
        }
References Terraria.Player.Spawn_ForceClearArea(), Terraria.Player.Spawn_IsAreaValidSpawn(), Terraria.Main.teamBasedSpawnsSeed, Terraria.GameContent.ExtraSpawnPointManager.TryGetExtraSpawnPointForTeam(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Point.Zero.