Terraria Decompiled: Terraria.Player.PlaceThing_Tiles_TryPlacing
PlaceThing_Tiles_TryPlacing()
void Terraria.Player.PlaceThing_Tiles_TryPlacing (int tileToCreate, bool? overrideCanPlace, int? forcedRandom, TileObject data, int placeStyle) inline private
Definition at line 38614 of file Player.cs.
        {
            bool flag = false;
            bool flag2 = false;
            if (overrideCanPlace != null)
            {
                flag = overrideCanPlace.Value;
            }
            else if (TileObjectData.CustomPlace(tileToCreate, placeStyle) && tileToCreate != 82 && tileToCreate != 227 && tileToCreate != 4)
            {
                flag2 = true;
                flag = TileObject.CanPlace(Player.tileTargetX, Player.tileTargetY, (int)((ushort)tileToCreate), placeStyle, this.direction, out data, false, forcedRandom);
                Player.PlaceThing_Tiles_BlockPlacementIfOverPlayers(ref flag, ref data);
                Player.PlaceThing_Tiles_BlockPlacementForRepeatedPigronatas(ref flag, ref data);
                Player.PlaceThing_Tiles_BlockPlacementForRepeatedPumpkins(ref flag, ref data);
                Player.PlaceThing_Tiles_BlockPlacementForRepeatedCoralAndBeachPiles(ref flag, ref data);
                Player.PlaceThing_Tiles_BlockPlacementForRepeatedRainbowBoulders(ref flag, ref data);
            }
            else
            {
                flag = this.PlaceThing_Tiles_BlockPlacementForAssortedThings(flag);
            }
            if (flag)
            {
                this.PlaceThing_Tiles_PlaceIt(flag2, data, tileToCreate);
            }
        }
References Terraria.TileObject.CanPlace(), Terraria.ObjectData.TileObjectData.CustomPlace(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedCoralAndBeachPiles(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedPigronatas(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedPumpkins(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedRainbowBoulders(), Terraria.Player.PlaceThing_Tiles_BlockPlacementIfOverPlayers(), Terraria.Player.tileTargetX, and Terraria.Player.tileTargetY.