Terraria Decompiled: Terraria.Player.GetItem_FillIntoOccupiedSlot
GetItem_FillIntoOccupiedSlot()
bool Terraria.Player.GetItem_FillIntoOccupiedSlot (Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
Definition at line 38335 of file Player.cs.
        {
            if (this.inventory[i].type > 0 && this.inventory[i].stack < this.inventory[i].maxStack && this.CanItemSlotAcceptPickup(this.inventory[i], returnItem))
            {
                if (!settings.NoSound)
                {
                    SoundEngine.PlaySound(newItem.IsACoin ? 38 : 7, -1, -1, 1, 1f, 0f);
                }
                if (returnItem.stack + this.inventory[i].stack <= this.inventory[i].maxStack)
                {
                    this.inventory[i].stack += returnItem.stack;
                    Player.GetItemLogger.Add(this.inventory, i, this.GetFittingItemSlotContext(i), returnItem.stack);
                    if (!settings.NoText)
                    {
                        PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, base.Center, returnItem.stack, false, settings.LongText);
                    }
                    if (!settings.NoCoinMerge)
                    {
                        this.DoCoins(i);
                    }
                    AchievementsHelper.NotifyItemPickup(this, returnItem);
                    settings.HandlePostAction(this.inventory[i]);
                    return true;
                }
                Player.GetItemLogger.Add(this.inventory, i, this.GetFittingItemSlotContext(i), this.inventory[i].maxStack - this.inventory[i].stack);
                AchievementsHelper.NotifyItemPickup(this, returnItem, this.inventory[i].maxStack - this.inventory[i].stack);
                returnItem.stack -= this.inventory[i].maxStack - this.inventory[i].stack;
                if (!settings.NoText)
                {
                    PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, base.Center, this.inventory[i].maxStack - this.inventory[i].stack, false, settings.LongText);
                }
                this.inventory[i].stack = this.inventory[i].maxStack;
                if (!settings.NoCoinMerge)
                {
                    this.DoCoins(i);
                }
                settings.HandlePostAction(this.inventory[i]);
            }
            return false;
        }
References Terraria.DataStructures.PlayerGetItemLogger.Add(), Terraria.Player.GetItemLogger, Terraria.GetItemSettings.HandlePostAction(), Terraria.Item.IsACoin, Terraria.GetItemSettings.LongText, Terraria.Item.maxStack, Terraria.PopupText.NewText(), Terraria.GetItemSettings.NoCoinMerge, Terraria.GetItemSettings.NoSound, Terraria.GetItemSettings.NoText, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Audio.SoundEngine.PlaySound(), System.stack, and Terraria.Item.stack.