Terraria Decompiled: System.Collections.ObjectModel.KeyedCollection.SetItem
SetItem()
override void System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.SetItem (int index, TItem item) inline protected
Definition at line 227 of file KeyedCollection.cs.
        {
            TKey keyForItem = this.GetKeyForItem(item);
            TKey keyForItem2 = this.GetKeyForItem(this.Items[index]);
            if (this.comparer.Equals(keyForItem2, keyForItem))
            {
                if (keyForItem != null && this.dict != null)
                {
                    this.dict[keyForItem] = item;
                }
            }
            else
            {
                if (keyForItem != null)
                {
                    this.AddKey(keyForItem, item);
                }
                if (keyForItem2 != null)
                {
                    this.RemoveKey(keyForItem2);
                }
            }
            base.SetItem(index, item);
        }
References System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.AddKey(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.comparer, System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.dict, System.Collections.IEqualityComparer.Equals(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.GetKeyForItem(), System.index, System.item, and System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.RemoveKey().