Terraria Decompiled: System.Collections.ObjectModel.KeyedCollection.ChangeItemKey
ChangeItemKey()
void System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.ChangeItemKey (TItem item, TKey newKey) inline protected
Definition at line 170 of file KeyedCollection.cs.
        {
            if (!this.ContainsItem(item))
            {
                throw new ArgumentException("The specified item does not exist in this KeyedCollection.");
            }
            TKey keyForItem = this.GetKeyForItem(item);
            if (!this.comparer.Equals(keyForItem, newKey))
            {
                if (newKey != null)
                {
                    this.AddKey(newKey, item);
                }
                if (keyForItem != null)
                {
                    this.RemoveKey(keyForItem);
                }
            }
        }
References System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.AddKey(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.comparer, System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.ContainsItem(), System.Collections.IEqualityComparer.Equals(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.GetKeyForItem(), System.item, and System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.RemoveKey().