Terraria Decompiled: System.Collections.ObjectModel.KeyedCollection.Contains
Contains()
bool System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Contains (TKey key) inline
Definition at line 80 of file KeyedCollection.cs.
        {
            if (key == null)
            {
                throw new ArgumentNullException("key");
            }
            if (this.dict != null)
            {
                return this.dict.ContainsKey(key);
            }
            foreach (TItem titem in this.Items)
            {
                if (this.comparer.Equals(this.GetKeyForItem(titem), key))
                {
                    return true;
                }
            }
            return false;
        }
References System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.comparer, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.dict, System.Collections.IEqualityComparer.Equals(), and System.key.
Referenced by System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.AddKey(), Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddSchema(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.HasCreatorParameter().