Terraria Decompiled: Terraria.Map.MapUpdateQueue.Add
Add() [2/2]
static void Terraria.Map.MapUpdateQueue.Add (Rectangle area) inline static
Definition at line 13 of file MapUpdateQueue.cs.
        {
            if (Main.dedServ || WorldGen.generatingWorld || !Main.mapEnabled)
            {
                return;
            }
            area = WorldUtils.ClampToWorld(area, 0);
            object @lock = MapUpdateQueue._lock;
            lock (@lock)
            {
                MapUpdateQueue._areaUpdateQueue.Add(area);
                for (int i = area.Left; i < area.Right; i++)
                {
                    for (int j = area.Top; j < area.Bottom; j++)
                    {
                        Main.Map.QueueUpdate(i, j);
                    }
                }
            }
        }
References Terraria.Map.MapUpdateQueue._areaUpdateQueue, Terraria.Map.MapUpdateQueue._lock, System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Terraria.Main.dedServ, Terraria.WorldGen.generatingWorld, Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.Map, Terraria.Main.mapEnabled, Microsoft.Xna.Framework.Rectangle.Right, and Microsoft.Xna.Framework.Rectangle.Top.
Referenced by Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.MessageBuffer.GetData(), Terraria.WorldGen.RangeFrame(), Terraria.WorldGen.SectionTileFrame(), and Terraria.WorldGen.TileFrame().