Terraria Decompiled: Terraria.Map.MapUpdateQueue.UpdateAreas
UpdateAreas()
static void Terraria.Map.MapUpdateQueue.UpdateAreas () inline static private
Definition at line 74 of file MapUpdateQueue.cs.
        {
            foreach (Rectangle rectangle in MapUpdateQueue._areaUpdateQueue)
            {
                for (int i = rectangle.Left; i < rectangle.Right; i++)
                {
                    for (int j = rectangle.Top; j < rectangle.Bottom; j++)
                    {
                        if (Main.Map.UpdateType(i, j))
{
                            MapRenderer.QueueChange(i, j);
                        }
                    }
                }
            }
            MapUpdateQueue._areaUpdateQueue.Clear();
        }
References Terraria.Map.MapUpdateQueue._areaUpdateQueue, Microsoft.Xna.Framework.Rectangle.Bottom, System.Collections.Generic.List< T >.Clear(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.Map, Terraria.MapRenderer.QueueChange(), Microsoft.Xna.Framework.Rectangle.Right, and Microsoft.Xna.Framework.Rectangle.Top.
Referenced by Terraria.Map.MapUpdateQueue.Update().