Terraria Decompiled: System.Runtime.Remoting.Channels.CADSerializer.DeserializeMessage
DeserializeMessage()
static IMessage System.Runtime.Remoting.Channels.CADSerializer.DeserializeMessage (MemoryStream mem, IMethodCallMessage msg) inline static package
Definition at line 12 of file CADSerializer.cs.
        {
            BinaryFormatter binaryFormatter = new BinaryFormatter();
            binaryFormatter.SurrogateSelector = null;
            mem.Position = 0L;
            if (msg == null)
            {
                return (IMessage)binaryFormatter.Deserialize(mem, null);
            }
            return (IMessage)binaryFormatter.DeserializeMethodResponse(mem, null, msg);
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.DeserializeMethodResponse(), and System.L.
Referenced by System.AppDomain.ProcessMessageInDomain(), and System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage().