Terraria Decompiled: System.Runtime.Remoting.Channels.CADSerializer.DeserializeObjectSafe
DeserializeObjectSafe()
static object System.Runtime.Remoting.Channels.CADSerializer.DeserializeObjectSafe (byte[] mem) inline static package
Definition at line 37 of file CADSerializer.cs.
        {
            byte[] array = new byte[mem.Length];
            Array.Copy(mem, array, mem.Length);
            return CADSerializer.DeserializeObject(new MemoryStream(array));
        }
References System.array, System.Array.Copy(), and System.Runtime.Remoting.Channels.CADSerializer.DeserializeObject().
Referenced by System.Runtime.Remoting.ObjRef.DeserializeInTheCurrentDomain(), and System.Runtime.Remoting.Messaging.CADMessageBase.GetMethod().