Terraria Decompiled: Microsoft.Win32.Registry.ToKey
ToKey()
static RegistryKey Microsoft.Win32.Registry.ToKey (string keyName, bool setting) inline static private
Definition at line 11 of file Registry.cs.
        {
            if (keyName == null)
            {
                throw new ArgumentException("Not a valid registry key name", "keyName");
            }
            string[] array = keyName.Split('\\', StringSplitOptions.None);
            string text = array[0];
            uint num = <PrivateImplementationDetails>.ComputeStringHash(text);
            RegistryKey registryKey;
            if (num <= 1097425318U)
            {
                if (num != 126972219U)
                {
                    if (num != 457190004U)
                    {
                        if (num == 1097425318U)
{
                            if (text == "HKEY_CLASSES_ROOT")
{
                                registryKey = Registry.ClassesRoot;
                                goto IL_013E;
                            }
                        }
                    }
                    else if (text == "HKEY_LOCAL_MACHINE")
                    {
                        registryKey = Registry.LocalMachine;
                        goto IL_013E;
                    }
                }
                else if (text == "HKEY_CURRENT_CONFIG")
                {
                    registryKey = Registry.CurrentConfig;
                    goto IL_013E;
                }
            }
            else if (num <= 1568329430U)
            {
                if (num != 1198714601U)
                {
                    if (num == 1568329430U)
                    {
                        if (text == "HKEY_CURRENT_USER")
{
                            registryKey = Registry.CurrentUser;
                            goto IL_013E;
                        }
                    }
                }
                else if (text == "HKEY_USERS")
                {
                    registryKey = Registry.Users;
                    goto IL_013E;
                }
            }
            else if (num != 2823865611U)
            {
                if (num == 3554990456U)
                {
                    if (text == "HKEY_PERFORMANCE_DATA")
                    {
                        registryKey = Registry.PerformanceData;
                        goto IL_013E;
                    }
                }
            }
            else if (text == "HKEY_DYN_DATA")
            {
                registryKey = Registry.DynData;
                goto IL_013E;
            }
            throw new ArgumentException("Keyname does not start with a valid registry root", "keyName");
            IL_013E:
            for (int i = 1; i < array.Length; i++)
            {
                RegistryKey registryKey2 = registryKey.OpenSubKey(array[i], setting);
                if (registryKey2 == null)
                {
                    if (!setting)
                    {
                        return null;
                    }
                    registryKey2 = registryKey.CreateSubKey(array[i]);
                }
                registryKey = registryKey2;
            }
            return registryKey;
        }
References System.array, Microsoft.Win32.Registry.ClassesRoot, Microsoft.Win32.RegistryKey.CreateSubKey(), Microsoft.Win32.Registry.CurrentConfig, Microsoft.Win32.Registry.CurrentUser, Microsoft.Win32.Registry.DynData, Microsoft.Win32.Registry.LocalMachine, Microsoft.Win32.RegistryKey.OpenSubKey(), Microsoft.Win32.Registry.PerformanceData, System.text, System.U, and Microsoft.Win32.Registry.Users.
Referenced by Microsoft.Win32.Registry.GetValue(), Microsoft.Win32.Registry.SetValue(), and Microsoft.Win32.Registry.SetValue().