Terraria Decompiled: Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract
JsonArrayContract()
Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract (Type underlyingType) inline
Definition at line 133 of file JsonArrayContract.cs.
            : base(underlyingType)
        {
            this.ContractType = JsonContractType.Array;
            this.IsArray = base.CreatedType.IsArray;
            bool flag;
            Type type;
            if (this.IsArray)
            {
                this.CollectionItemType = ReflectionUtils.GetCollectionItemType(base.UnderlyingType);
                this.IsReadOnlyOrFixedSize = true;
                this._genericCollectionDefinitionType = typeof(List).MakeGenericType(new Type[] { this.CollectionItemType });
                flag = true;
                this.IsMultidimensionalArray = this.IsArray && base.UnderlyingType.GetArrayRank() > 1;
            }
            else if (typeof(IList).IsAssignableFrom(underlyingType))
            {
                if (ReflectionUtils.ImplementsGenericDefinition(underlyingType, typeof(ICollection), out this._genericCollectionDefinitionType))
                {
                    this.CollectionItemType = this._genericCollectionDefinitionType.GetGenericArguments()[0];
                }
                else
                {
                    this.CollectionItemType = ReflectionUtils.GetCollectionItemType(underlyingType);
                }
                if (underlyingType == typeof(IList))
                {
                    base.CreatedType = typeof(List<object>);
                }
                if (this.CollectionItemType != null)
                {
                    this._parameterizedConstructor = CollectionUtils.ResolveEnumerableCollectionConstructor(underlyingType, this.CollectionItemType);
                }
                this.IsReadOnlyOrFixedSize = ReflectionUtils.InheritsGenericDefinition(underlyingType, typeof(ReadOnlyCollection));
                flag = true;
            }
            else if (ReflectionUtils.ImplementsGenericDefinition(underlyingType, typeof(ICollection), out this._genericCollectionDefinitionType))
            {
                this.CollectionItemType = this._genericCollectionDefinitionType.GetGenericArguments()[0];
                if (ReflectionUtils.IsGenericDefinition(underlyingType, typeof(ICollection)) || ReflectionUtils.IsGenericDefinition(underlyingType, typeof(IList)))
                {
                    base.CreatedType = typeof(List).MakeGenericType(new Type[] { this.CollectionItemType });
                }
                if (ReflectionUtils.IsGenericDefinition(underlyingType, typeof(ISet)))
                {
                    base.CreatedType = typeof(HashSet).MakeGenericType(new Type[] { this.CollectionItemType });
                }
                this._parameterizedConstructor = CollectionUtils.ResolveEnumerableCollectionConstructor(underlyingType, this.CollectionItemType);
                flag = true;
                this.ShouldCreateWrapper = true;
            }
            else if (ReflectionUtils.ImplementsGenericDefinition(underlyingType, typeof(IEnumerable), out type))
            {
                this.CollectionItemType = type.GetGenericArguments()[0];
                if (ReflectionUtils.IsGenericDefinition(base.UnderlyingType, typeof(IEnumerable)))
                {
                    base.CreatedType = typeof(List).MakeGenericType(new Type[] { this.CollectionItemType });
                }
                this._parameterizedConstructor = CollectionUtils.ResolveEnumerableCollectionConstructor(underlyingType, this.CollectionItemType);
                this.StoreFSharpListCreatorIfNecessary(underlyingType);
                if (underlyingType.IsGenericType() && underlyingType.GetGenericTypeDefinition() == typeof(IEnumerable))
                {
                    this._genericCollectionDefinitionType = type;
                    this.IsReadOnlyOrFixedSize = false;
                    this.ShouldCreateWrapper = false;
                    flag = true;
                }
                else
                {
                    this._genericCollectionDefinitionType = typeof(List).MakeGenericType(new Type[] { this.CollectionItemType });
                    this.IsReadOnlyOrFixedSize = true;
                    this.ShouldCreateWrapper = true;
                    flag = this.HasParameterizedCreatorInternal;
                }
            }
            else
            {
                flag = false;
                this.ShouldCreateWrapper = true;
            }
            this.CanDeserialize = flag;
        }
References Newtonsoft.Json.Serialization.JsonArrayContract._genericCollectionDefinitionType, Newtonsoft.Json.Serialization.JsonArrayContract.CollectionItemType, Newtonsoft.Json.Utilities.ReflectionUtils.GetCollectionItemType(), System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), Newtonsoft.Json.Serialization.JsonArrayContract.HasParameterizedCreatorInternal, Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition(), Newtonsoft.Json.Utilities.ReflectionUtils.InheritsGenericDefinition(), Newtonsoft.Json.Serialization.JsonArrayContract.IsArray, Newtonsoft.Json.Utilities.ReflectionUtils.IsGenericDefinition(), System.Type.IsGenericType, System.Type.MakeGenericType(), Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor(), and Newtonsoft.Json.Serialization.JsonArrayContract.StoreFSharpListCreatorIfNecessary().