Terraria Decompiled: Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper
CreateWrapper()
IWrappedCollection Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper (object list) inline package
Definition at line 217 of file JsonArrayContract.cs.
        {
            if (this._genericWrapperCreator == null)
            {
                this._genericWrapperType = typeof(CollectionWrapper<>).MakeGenericType(new Type[] { this.CollectionItemType });
                Type type;
                if (ReflectionUtils.InheritsGenericDefinition(this._genericCollectionDefinitionType, typeof(List)) || this._genericCollectionDefinitionType.GetGenericTypeDefinition() == typeof(IEnumerable))
                {
                    type = typeof(ICollection).MakeGenericType(new Type[] { this.CollectionItemType });
                }
                else
                {
                    type = this._genericCollectionDefinitionType;
                }
                ConstructorInfo constructor = this._genericWrapperType.GetConstructor(new Type[] { type });
                this._genericWrapperCreator = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(constructor);
            }
            return (IWrappedCollection)this._genericWrapperCreator(new object[] { list });
        }
References Newtonsoft.Json.Serialization.JsonArrayContract._genericCollectionDefinitionType, Newtonsoft.Json.Serialization.JsonArrayContract._genericWrapperCreator, Newtonsoft.Json.Serialization.JsonArrayContract._genericWrapperType, Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), System.Type.GetConstructor(), System.Type.GetGenericTypeDefinition(), Newtonsoft.Json.Utilities.ReflectionUtils.InheritsGenericDefinition(), System.Type.MakeGenericType(), and Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate().