Terraria Decompiled: Microsoft.Xna.Framework.Rectangle.Intersect
Intersect() [2/2]
static void Microsoft.Xna.Framework.Rectangle.Intersect (ref Rectangle value1, ref Rectangle value2, out Rectangle result) inline static
Definition at line 249 of file Rectangle.cs.
        {
            if (value1.Intersects(value2))
            {
                int num = Math.Min(value1.X + value1.Width, value2.X + value2.Width);
                int num2 = Math.Max(value1.X, value2.X);
                int num3 = Math.Max(value1.Y, value2.Y);
                int num4 = Math.Min(value1.Y + value1.Height, value2.Y + value2.Height);
                result = new Rectangle(num2, num3, num - num2, num4 - num3);
                return;
            }
            result = new Rectangle(0, 0, 0, 0);
        }
References System.Math.Max(), System.Math.Min(), and Microsoft.Xna.Framework.Rectangle.Rectangle().