Terraria Decompiled: Microsoft.Xna.Framework.Rectangle.Contains
Contains() [1/5]
bool Microsoft.Xna.Framework.Rectangle.Contains (int x, int y) inline
Definition at line 129 of file Rectangle.cs.
        {
            return this.X <= x && x < this.X + this.Width && this.Y <= y && y < this.Y + this.Height;
        }
References Microsoft.Xna.Framework.Rectangle.Height.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.GameContent.EmergencyStacking.AnyContains(), Terraria.Graphics.Light.LightingEngine.ApplyPerFrameLights(), Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.Utils.ConstrainedToPointInRectangle(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.ContainsWithFluff(), Terraria.GameContent.TeleportPylonsSystem.DoesPositionHaveEnoughNPCs(), Terraria.Main.DoScrollingInInventory(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds(), Terraria.GameContent.UI.NPCChatPanel.Draw(), Terraria.IngameOptions.Draw(), Terraria.GameContent.UI.IssueReportsIndicator.Draw(), Terraria.GameContent.Skies.LanternSky.Draw(), Terraria.GameContent.Skies.MartianSky.Draw(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.PartySky.Draw(), Terraria.GameContent.Skies.SlimeSky.Draw(), Terraria.GameContent.Skies.SolarSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.GameContent.Skies.VortexSky.Draw(), Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.Draw(), Terraria.Map.MapOverlayDrawContext.Draw(), Terraria.Map.MapOverlayDrawContext.Draw(), Terraria.Main.DrawBestiaryIcon(), Terraria.Main.DrawBuilderAccToggles(), Terraria.Map.MapOverlayDrawContext.DrawClamped(), Terraria.Main.DrawClothesWindow(), Terraria.Main.DrawDefenseCounter(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.GameContent.LeashedEntity.DrawEntities(), Terraria.Main.DrawHairWindow(), Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Terraria.Main.DrawInventory(), Terraria.IngameOptions.DrawLeftSide(), Terraria.Main.DrawLoadoutButtons(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.DrawMapIcon(), Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition(), Terraria.Main.DrawNPCChatBottomRightItem(), Terraria.Main.DrawPVPIcons(), Terraria.GameContent.UI.NewCraftingUI.DrawRecipeSlot(), Terraria.IngameOptions.DrawRightSide(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.DrawSelf(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf(), Terraria.UI.ChestUI.DrawSlots(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.IngameOptions.DrawValue(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawValueBar(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices(), Terraria.NPC.Spawner.FindSpawnTile(), Terraria.Map.MapHelper.GetBackgroundType(), Terraria.GameContent.NearbyChests.GetBanksInRangeOf(), Terraria.Graphics.Light.LightingEngine.GetColor(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.GetSnapPoints(), Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.InDrawRange(), Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordExplosion.InDrawRange(), Terraria.GameContent.UI.Elements.UIScrollbar.LeftMouseDown(), Terraria.IngameOptions.MouseOver(), Terraria.SceneMetrics.ScanNPCPositions(), Terraria.GameContent.Events.DD2Event.ShouldBlockBuilding(), Terraria.NPC.Spawner.SpawnFaelings(), Terraria.Graphics.Capture.CaptureInterface.StartCamera(), Terraria.WorldItem.SyncItemsInSection(), Terraria.WorldGen.TileRunner(), Terraria.Main.TryInteractingWithMoneyTrough(), Terraria.Main.TryInteractingWithVoidLens(), Terraria.Player.TryInterruptingItemUsage(), Terraria.Main.TryPetting(), Terraria.Mount.TryPettingMount(), Terraria.WorldGen.TrySpawnLightningBolt(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Update(), Terraria.Player.Update(), Terraria.Graphics.Capture.CaptureInterface.UpdateButtons(), Terraria.Player.UpdateParticles(), and Terraria.Player.WouldSpotOverlapWithSentry().