Terraria Decompiled: Microsoft.Xna.Framework.Rectangle.Inflate
Inflate()
void Microsoft.Xna.Framework.Rectangle.Inflate (int horizontalValue, int verticalValue) inline
Definition at line 173 of file Rectangle.cs.
        {
            this.X -= horizontalValue;
            this.Y -= verticalValue;
            this.Width += horizontalValue * 2;
            this.Height += verticalValue * 2;
        }
Referenced by Terraria.WorldBuilding.StructureMap.AddProtectedStructure(), Terraria.WorldBuilding.StructureMap.AddStructure(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks_SearchWall(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.WorldGen.CheckForHousesNearAPlayer(), Terraria.Projectile.Colliding(), Terraria.Projectile.Damage_GetHitbox(), Terraria.Mount.DoFailedDismountDust(), Terraria.Mount.DoSpawnDust(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds(), Terraria.GameContent.Events.ScreenObstruction.Draw(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawBareBonesBar(), Terraria.GameContent.LeashedEntity.DrawEntities(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Main.DrawNPCDirect(), Terraria.GameContent.UI.States.UIWorldGenDebug.UIImageButtonWithExtraIcon.DrawSelf(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.GameContent.Biomes.DesertBiome.ExportDescriptionToEngine(), Terraria.Graphics.Light.LightingEngine.ExportToMiniMap(), Terraria.WorldItem.FindOwner(), Terraria.Player.FindSharpTearsSpot(), Terraria.Main.GetBackgroundRect(), Terraria.NPC.GetFairyTreasureCoords(), Terraria.Player.HorizontalMovement(), Terraria.DataStructures.MultiPointHitbox.Intersects(), Terraria.Player.InTileEntityInteractionRange(), Terraria.NPC.IsDeerclopsHostile(), Terraria.Wiring.IsHopperInRangeOf(), Terraria.Player.IsInInteractionRangeToMultiTileHitbox(), Terraria.WorldGen.IsNPCEvictable(), Terraria.Player.JumpMovement(), Terraria.GameContent.Biomes.DungeonControlLine.Paint(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClusters(), Terraria.DataStructures.PlayerIntentionGuesser.PrepareUsageProxy(), Terraria.Graphics.Light.LightingEngine.ProcessScan(), Terraria.Projectile.RainbowBoulder_GetTreasureCoords(), Terraria.Projectile.SpawnMoonLordWhipProc(), Terraria.WorldGen.SpawnStormLightningNearPlayer(), Terraria.Collision.StepConveyorBelt(), Terraria.WorldItem.SyncItemsInSection(), Terraria.Player.TileInteractionsUse(), Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor(), Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.TryFindingNPCToTrack(), Terraria.Main.TryPetting(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Update(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Update(), Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap(), Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition(), Terraria.Main.UpdateSceneMetrics(), Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing(), Terraria.Player.UpdateTeleportVisuals(), Terraria.GameContent.Bestiary.CustomEntryIcon.UpdateUnlockState(), and Terraria.Player.WouldSpotOverlapWithSentry().