Terraria Decompiled: Microsoft.Xna.Framework.Rectangle.Intersects
Intersects() [1/2]
bool Microsoft.Xna.Framework.Rectangle.Intersects (Rectangle value) inline
Definition at line 217 of file Rectangle.cs.
        {
            return value.Left < this.Right && this.Left < value.Right && value.Top < this.Bottom && this.Top < value.Bottom;
        }
References System.value.
Referenced by Terraria.Cloud.addCloud(), Terraria.WorldGen.AddPasses(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_037_Destroyer(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_200_BirdDroppings(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks_SearchWall(), Terraria.NPC.AnyoneNearCultists(), Terraria.Projectile.BombsHurtPlayers(), Terraria.NPC.CanAnyPlayerSeeThisTile(), Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.NPC.CanReflectProjectile(), Terraria.NPC.CheckActive(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.Main.CheckInvasionProgressDisplay(), Terraria.NPC.Spawner.CheckNotSpawningOnScreen(), Terraria.Player.CollideWithNPCs(), Terraria.Projectile.Colliding(), Terraria.Projectile.Damage_TryUsingPowders(), Terraria.Player.DashMovement(), Terraria.Main.DrawDust(), Terraria.Main.DrawInterface_1_2_DrawEntityMarkersInWorld(), Terraria.Main.DrawMouseOver(), Terraria.Main.DrawNPCs(), Terraria.Main.DrawProj(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawSunAndMoon(), Terraria.GameContent.Drawing.TileDrawing.EmitLiquidDrops(), Terraria.Collision.EmptyTile(), Terraria.NPC.FindFrame(), Terraria.WorldItem.FindOwner(), Terraria.NPC.GetHurtByOtherNPCs(), Terraria.NPC.GetMeleeCollisionData(), Terraria.WorldItem.GetPickedUpByMonsters_Money(), Terraria.WorldItem.GetPickedUpByMonsters_Special(), Terraria.Player.GetSparkleGuitarTarget(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Player.GrabItems(), Terraria.Wiring.Hopper(), Terraria.Main.HoverOverNPCs(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Intersects(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.Intersects(), Terraria.DataStructures.MultiPointHitbox.Intersects(), Terraria.NPC.IsDeerclopsHostile(), Terraria.WorldGen.IsNPCEvictable(), Terraria.Player.ItemCheck_CatchCritters(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.JumpMovement(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.meteor(), Terraria.NPC.NearSpikeBall(), Terraria.Dust.NewDust(), Terraria.Player.PlaceThing_Tiles_BlockPlacementIfOverPlayers(), Terraria.WorldGen.PlayerLOS(), Terraria.WorldGen.PoundTile(), Terraria.Player.ProcessHitAgainstNPC(), Terraria.GameContent.ObjectInteractions.NPCSmartInteractCandidateProvider.ProvideCandidate(), Terraria.Projectile.RainbowBoulder_PerformSmartBounce(), Terraria.Projectile.RainbowBoulder_PreventSpam(), Terraria.Projectile.RandomizeInsanityShadowFor(), Terraria.GameInput.LockOnHelper.RefreshTargets(), Terraria.GameContent.Drawing.WindGrid.ScanPlayer(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.ScanWorldForFinds(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.Collision.StepDown(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.TryFindingNPCToTrack(), Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor(), Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryOpenDoor(), Terraria.WorldGen.UnspawnHomelessNPC(), Terraria.WorldGen.UnspawnTravelNPC(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Update(), Terraria.Gore.Update(), Terraria.PopupText.Update(), Terraria.GameContent.UI.UIPopupText.Update(), Terraria.Player.Update_NPCCollision(), Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap(), Terraria.Main.UpdateAudio_DecideOnNewMusic(), Terraria.Main.UpdateAudio_DecideOnTOWMusic(), Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition(), and Terraria.Collision.WalkDownSlope().