Terraria Decompiled: Terraria.DataStructures.SpriteDrawBuffer.Bind
Bind()
void Terraria.DataStructures.SpriteDrawBuffer.Bind () inline private
Definition at line 83 of file SpriteDrawBuffer.cs.
        {
            if (this.preBindVertexBuffers != null)
            {
                return;
            }
            this.preBindVertexBuffers = this.graphicsDevice.GetVertexBuffers();
            this.preBindIndexBuffer = this.graphicsDevice.Indices;
            this.graphicsDevice.SetVertexBuffer(this.vertexBuffer);
            this.graphicsDevice.Indices = this.indexBuffer;
        }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetVertexBuffers(), Terraria.DataStructures.SpriteDrawBuffer.graphicsDevice, Terraria.DataStructures.SpriteDrawBuffer.indexBuffer, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Indices, Terraria.DataStructures.SpriteDrawBuffer.preBindVertexBuffers, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer(), and Terraria.DataStructures.SpriteDrawBuffer.vertexBuffer.
Referenced by Terraria.DataStructures.SpriteDrawBuffer.DrawRange().