Terraria Decompiled: Terraria.DataStructures.SpriteDrawBuffer.CheckBuffers
CheckBuffers()
void Terraria.DataStructures.SpriteDrawBuffer.CheckBuffers () inline private
Definition at line 42 of file SpriteDrawBuffer.cs.
        {
            if (this.vertexBuffer == null || this.vertexBuffer.IsDisposed)
            {
                if (this.vertexBuffer != null)
                {
                    this.vertexBuffer.Dispose();
                }
                this.vertexBuffer = new DynamicVertexBuffer(this.graphicsDevice, typeof(VertexPositionColorTexture), this.bufferSize * 4, BufferUsage.WriteOnly);
            }
            if (this.indexBuffer == null || this.indexBuffer.IsDisposed)
            {
                if (this.indexBuffer != null)
                {
                    this.indexBuffer.Dispose();
                }
                this.indexBuffer = new IndexBuffer(this.graphicsDevice, typeof(ushort), this.bufferSize * 6, BufferUsage.WriteOnly);
                this.indexBuffer.SetData<ushort>(SpriteDrawBuffer.GenIndexBuffer(this.bufferSize));
            }
        }
References Terraria.DataStructures.SpriteDrawBuffer.bufferSize, Microsoft.Xna.Framework.Graphics.IndexBuffer.Dispose(), Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose(), Terraria.DataStructures.SpriteDrawBuffer.GenIndexBuffer(), Terraria.DataStructures.SpriteDrawBuffer.graphicsDevice, Terraria.DataStructures.SpriteDrawBuffer.indexBuffer, Microsoft.Xna.Framework.Graphics.GraphicsResource.IsDisposed, and Terraria.DataStructures.SpriteDrawBuffer.vertexBuffer.
Referenced by Terraria.DataStructures.SpriteDrawBuffer.DrawRange().