Terraria Decompiled: Terraria.DataStructures.SpriteDrawBuffer.Unbind
Unbind()
void Terraria.DataStructures.SpriteDrawBuffer.Unbind () inline
Definition at line 96 of file SpriteDrawBuffer.cs.
        {
            if (this.preBindVertexBuffers == null)
            {
                return;
            }
            this.graphicsDevice.SetVertexBuffers(this.preBindVertexBuffers);
            this.graphicsDevice.Indices = this.preBindIndexBuffer;
            this.preBindVertexBuffers = null;
            this.preBindIndexBuffer = null;
        }
References Terraria.DataStructures.SpriteDrawBuffer.graphicsDevice, Terraria.DataStructures.SpriteDrawBuffer.preBindIndexBuffer, Terraria.DataStructures.SpriteDrawBuffer.preBindVertexBuffers, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers().
Referenced by Terraria.DataStructures.SpriteDrawBuffer.DrawAll(), and Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader().