Terraria Decompiled: Terraria.DataStructures.SpriteDrawBuffer.DrawRange
DrawRange()
int Terraria.DataStructures.SpriteDrawBuffer.DrawRange (int index, int count) inline
Definition at line 109 of file SpriteDrawBuffer.cs.
        {
            this.vertexCount = 0;
            this.CheckBuffers();
            this.Bind();
            this.graphicsDevice.Textures[0] = this.textures[index];
            int num = 0;
            while (count > 0)
            {
                if (this.uploadedSpriteIndex < 0 || index < this.uploadedSpriteIndex || index + count > this.uploadedSpriteIndex + this.bufferSize)
                {
                    this.vertexBuffer.SetData<VertexPositionColorTexture>(this.vertices, index * 4, Math.Min(this.vertices.Length - index * 4, this.bufferSize * 4), SetDataOptions.Discard);
                    this.uploadedSpriteIndex = index;
                }
                int num2 = Math.Min(count, this.bufferSize);
                int num3 = index - this.uploadedSpriteIndex;
                this.graphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, num3 * 4, 0, num2 * 4, 0, num2 * 2);
                count -= num2;
                index += num2;
                num++;
            }
            return num;
        }
References Terraria.DataStructures.SpriteDrawBuffer.Bind(), Terraria.DataStructures.SpriteDrawBuffer.bufferSize, Terraria.DataStructures.SpriteDrawBuffer.CheckBuffers(), System.count, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Terraria.DataStructures.SpriteDrawBuffer.graphicsDevice, System.index, System.Math.Min(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, Terraria.DataStructures.SpriteDrawBuffer.textures, Terraria.DataStructures.SpriteDrawBuffer.uploadedSpriteIndex, Terraria.DataStructures.SpriteDrawBuffer.vertexBuffer, and Terraria.DataStructures.SpriteDrawBuffer.vertices.
Referenced by Terraria.DataStructures.SpriteDrawBuffer.DrawAll(), and Terraria.DataStructures.SpriteDrawBuffer.DrawSingle().