Terraria Decompiled: System.Collections.IDictionary.GetEnumerator
GetEnumerator()
IDictionaryEnumerator System.Collections.IDictionary.GetEnumerator ()
Implements System.Collections.IEnumerable.
Implemented in System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.DictionaryBase, System.Collections.DictionaryBase, System.Collections.EmptyReadOnlyDictionaryInternal, System.Collections.EmptyReadOnlyDictionaryInternal, System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable.SyncHashtable, System.Collections.Hashtable.SyncHashtable, System.Collections.ListDictionaryInternal, System.Collections.ListDictionaryInternal, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.SortedList, System.Collections.SortedList, System.Collections.SortedList.SyncSortedList, System.Runtime.Remoting.Channels.AggregateDictionary, System.Runtime.Remoting.Channels.AggregateDictionary, System.Runtime.Remoting.Channels.BaseChannelObjectWithProperties, System.Runtime.Remoting.Channels.BaseChannelObjectWithProperties, System.Runtime.Remoting.Messaging.MessageDictionary, System.Runtime.Remoting.Messaging.MessageDictionary, Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >, Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >, and Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.
Referenced by System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.CopyTo(), System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.DictionaryEnumerator.DictionaryEnumerator(), System.Runtime.Remoting.Messaging.MessageDictionary.DictionaryEnumerator.DictionaryEnumerator(), System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.GetEnumerator(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.GetEnumerator(), System.Collections.Hashtable.Hashtable(), System.Collections.Hashtable.Hashtable(), System.Runtime.Remoting.Messaging.CADMessageBase.MarshalProperties(), System.Runtime.Remoting.Channels.AggregateEnumerator.MoveNext(), System.Runtime.Remoting.Messaging.LogicalCallContext.PropagateIncomingHeadersToCallContext(), and System.Runtime.Remoting.Channels.AggregateEnumerator.Reset().