Terraria Decompiled: Terraria.Chat.Commands.BossDamageCommand.ProcessIncomingMessage
ProcessIncomingMessage()
void Terraria.Chat.Commands.BossDamageCommand.ProcessIncomingMessage (string text, byte clientId) inline
Implements Terraria.Chat.Commands.IChatCommand.
Definition at line 12 of file BossDamageCommand.cs.
        {
            foreach (NPCDamageTracker npcdamageTracker in NPCDamageTracker.RecentAttempts())
            {
                for (int i = 0; i < 255; i++)
                {
                    if (Main.player[i].active)
                    {
                        ChatHelper.SendChatMessageToClient(npcdamageTracker.GetReport(Main.player[i]), BossDamageCommand.RESPONSE_COLOR, i);
                    }
                }
            }
        }
References Terraria.Player.active, Terraria.GameContent.NPCDamageTracker.GetReport(), Terraria.Main.player, Terraria.GameContent.NPCDamageTracker.RecentAttempts(), Terraria.Chat.Commands.BossDamageCommand.RESPONSE_COLOR, and Terraria.Chat.ChatHelper.SendChatMessageToClient().