Terraria Decompiled: System.Collections.ICollection.CopyTo
CopyTo()
void System.Collections.ICollection.CopyTo (Array array, int index)
Implemented in System.Collections.ArrayList, System.Collections.Hashtable, System.Collections.Hashtable.KeyCollection, System.Collections.Hashtable.ValueCollection, System.Collections.Hashtable.SyncHashtable, System.Collections.Queue.SynchronizedQueue, System.Collections.SortedList, System.Collections.SortedList.KeyList, System.Collections.SortedList.ValueList, System.Collections.Stack.SyncStack, Newtonsoft.Json.Utilities.CollectionWrapper< T >, System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.SyncIList, System.Collections.ArrayList.FixedSizeList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.ArrayList.Range, System.Collections.BitArray, System.Collections.CollectionBase, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Concurrent.ConcurrentQueue< T >, System.Collections.Concurrent.ConcurrentStack< T >, System.Collections.DictionaryBase, System.Collections.EmptyReadOnlyDictionaryInternal, System.Collections.ListDictionaryInternal, System.Collections.ListDictionaryInternal.NodeKeyValueCollection, System.Collections.ObjectModel.Collection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.KeyCollection, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.ValueCollection, System.Collections.Queue, System.Collections.ReadOnlyCollectionBase, System.Collections.SortedList.SyncSortedList, System.Collections.Stack, System.Runtime.Remoting.Channels.AggregateDictionary, System.Runtime.Remoting.Channels.BaseChannelObjectWithProperties, System.Runtime.Remoting.Messaging.MessageDictionary, System.Security.AccessControl.GenericAcl, System.Security.Permissions.KeyContainerPermissionAccessEntryCollection, System.Security.PermissionSet, System.Security.Policy.ApplicationTrustCollection, System.Security.Policy.Evidence, and Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.
Referenced by System.Collections.ArrayList.IListWrapper.CopyTo(), System.Collections.ArrayList.SyncIList.CopyTo(), System.Collections.ArrayList.FixedSizeList.CopyTo(), System.Collections.ArrayList.ReadOnlyList.CopyTo(), System.Runtime.Remoting.Messaging.MessageDictionary.CopyTo(), Newtonsoft.Json.Utilities.CollectionWrapper< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyDictionaryHelpers.CopyToNonGenericICollectionHelper< T >(), System.Runtime.Remoting.RemotingConfiguration.GetRegisteredActivatedClientTypes(), System.Runtime.Remoting.RemotingConfiguration.GetRegisteredActivatedServiceTypes(), System.Runtime.Remoting.RemotingConfiguration.GetRegisteredWellKnownClientTypes(), System.Runtime.Remoting.RemotingConfiguration.GetRegisteredWellKnownServiceTypes(), System.Collections.ArrayList.InsertRange(), System.Collections.ArrayList.SetRange(), System.Collections.SortedList.SortedList(), System.Collections.ArrayList.IListWrapper.ToArray(), and System.Collections.ArrayList.IListWrapper.ToArray().