Terraria Decompiled: System.Globalization.JulianCalendar.AddMonths
AddMonths()
override DateTime System.Globalization.JulianCalendar.AddMonths (DateTime time, int months) inline
Definition at line 145 of file JulianCalendar.cs.
        {
            if (months < -120000 || months > 120000)
            {
                throw new ArgumentOutOfRangeException("months", string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Valid values are between {0} and {1}, inclusive."), -120000, 120000));
            }
            int num = JulianCalendar.GetDatePart(time.Ticks, 0);
            int num2 = JulianCalendar.GetDatePart(time.Ticks, 2);
            int num3 = JulianCalendar.GetDatePart(time.Ticks, 3);
            int num4 = num2 - 1 + months;
            if (num4 >= 0)
            {
                num2 = num4 % 12 + 1;
                num += num4 / 12;
            }
            else
            {
                num2 = 12 + (num4 + 1) % 12;
                num += (num4 - 11) / 12;
            }
            int[] array = ((num % 4 == 0 && (num % 100 != 0 || num % 400 == 0)) ? JulianCalendar.DaysToMonth366 : JulianCalendar.DaysToMonth365);
            int num5 = array[num2] - array[num2 - 1];
            if (num3 > num5)
            {
                num3 = num5;
            }
            long num6 = JulianCalendar.DateToTicks(num, num2, num3) + time.Ticks % 864000000000L;
            Calendar.CheckAddResult(num6, this.MinSupportedDateTime, this.MaxSupportedDateTime);
            return new DateTime(num6);
        }
References System.array, System.Globalization.Calendar.CheckAddResult(), System.Globalization.CultureInfo.CurrentCulture, System.DateTime, System.Globalization.JulianCalendar.DateToTicks(), System.Globalization.JulianCalendar.DaysToMonth365, System.Globalization.Format, System.Globalization.JulianCalendar.GetDatePart(), System.Environment.GetResourceString(), System.L, System.Globalization.JulianCalendar.MaxSupportedDateTime, System.Globalization.JulianCalendar.MinSupportedDateTime, and System.DateTime.Ticks.
Referenced by System.Globalization.JulianCalendar.AddYears().