Terraria Decompiled: System.Globalization.JulianCalendar.ToDateTime
ToDateTime()
override DateTime System.Globalization.JulianCalendar.ToDateTime (int year, int month, int day, int hour, int minute, int second, int millisecond, int era) inline
Definition at line 291 of file JulianCalendar.cs.
        {
            this.CheckYearEraRange(year, era);
            JulianCalendar.CheckMonthRange(month);
            JulianCalendar.CheckDayRange(year, month, day);
            if (millisecond < 0 || millisecond >= 1000)
            {
                throw new ArgumentOutOfRangeException("millisecond", string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Valid values are between {0} and {1}, inclusive."), 0, 999));
            }
            if (hour >= 0 && hour < 24 && minute >= 0 && minute < 60 && second >= 0 && second < 60)
            {
                return new DateTime(JulianCalendar.DateToTicks(year, month, day) + new TimeSpan(0, hour, minute, second, millisecond).Ticks);
            }
            throw new ArgumentOutOfRangeException(null, Environment.GetResourceString("Hour, Minute, and Second parameters describe an un-representable DateTime."));
        }
References System.Globalization.JulianCalendar.CheckDayRange(), System.Globalization.JulianCalendar.CheckMonthRange(), System.Globalization.JulianCalendar.CheckYearEraRange(), System.Globalization.CultureInfo.CurrentCulture, System.DateTime, System.Globalization.JulianCalendar.DateToTicks(), System.Globalization.Format, and System.Environment.GetResourceString().