Terraria Decompiled: Terraria.PopupText.EmitFancyFlashDust
EmitFancyFlashDust()
static void Terraria.PopupText.EmitFancyFlashDust (PopupText somePopup) inline static private
Definition at line 413 of file PopupText.cs.
        {
            Vector2 vector = somePopup.GetTextHitbox();
            float num = 1f / somePopup.scale;
            vector *= num;
            int num2 = 6 + somePopup.effectIntensity / 2;
            int num3 = -3 + somePopup.effectIntensity;
            num3 *= 4;
            if (num3 < 0)
            {
                num3 = 0;
            }
            num2 -= num3;
            if (somePopup.effectStyle == PopupEffectStyle.Potion)
            {
                num2 = 0;
                num3 = 0;
            }
            for (int i = 0; i < num2; i++)
            {
                float num4 = -0.1f + 1.2f * Main.rand.NextFloat();
                float num5 = somePopup.position.X + vector.X * num4;
                float num6 = somePopup.position.Y + vector.Y * (1f + 0.4f * (float)Math.Sin((double)(num4 * 3.1415927f)));
                Dust dust = Dust.NewDustPerfect(new Vector2(num5, num6), 306, new Vector2?(new Vector2(0f, Main.rand.NextFloatDirection())), 0, somePopup.color, 2f);
                dust.noGravity = true;
                dust.noLight = true;
                dust.noLightEmittance = true;
                Dust dust2 = dust;
                dust2.velocity.Y = dust2.velocity.Y + -2f;
                dust.fadeIn = 1.4f * (1f + 0.4f * Main.rand.NextFloat());
                dust.scale = 0.6f + 0.4f * Main.rand.NextFloat();
                if (dust.scale >= 0.9f)
                {
                    Dust dust3 = Dust.CloneDust(dust);
                    dust3.color = new Color(255, 255, 255, 255);
                    dust3.scale *= 0.65f;
                    dust3.fadeIn = 1.1f;
                }
            }
            for (int j = 0; j < num3; j++)
            {
                float num7 = -0.1f + 1.2f * Main.rand.NextFloat();
                float num8 = somePopup.position.X + vector.X * num7;
                float num9 = somePopup.position.Y + vector.Y * (0.6f + 0.4f * (float)Math.Sin((double)(num7 * 3.1415927f)));
                Dust dust4 = Dust.NewDustPerfect(new Vector2(num8, num9), 306, new Vector2?(new Vector2(0f, Main.rand.NextFloatDirection())), 0, somePopup.color, 2f);
                dust4.noLight = true;
                dust4.noLightEmittance = true;
                dust4.velocity.X = dust4.velocity.RotatedBy((double)(6.2831855f * Main.rand.NextFloatDirection()), default(Vector2)).X;
                Dust dust5 = dust4;
                dust5.velocity.Y = dust5.velocity.Y + -2f;
                dust4.fadeIn = 2.4f * (1f + 0.4f * Main.rand.NextFloat());
                dust4.scale = 0.6f + 0.4f * Main.rand.NextFloat();
                if (dust4.scale >= 0.9f)
                {
                    Dust dust6 = Dust.CloneDust(dust4);
                    dust6.color = new Color(255, 255, 255, 255);
                    dust6.scale *= 0.65f;
                    dust6.fadeIn = 1.1f;
                }
            }
        }
References Terraria.Dust.CloneDust(), Microsoft.Xna.Framework.Graphics.Color, Terraria.PopupText.color, Terraria.PopupText.effectIntensity, Terraria.PopupText.effectStyle, Terraria.PopupText.GetTextHitbox(), Terraria.Dust.NewDustPerfect(), Terraria.Main.rand, Terraria.PopupText.scale, System.Math.Sin(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, and System.X.
Referenced by Terraria.PopupText.Update().