Terraria Decompiled: Terraria.PopupText.NewText
NewText() [1/3]
static int Terraria.PopupText.NewText (AdvancedPopupRequest request, Vector2 position) inline static
Definition at line 78 of file PopupText.cs.
        {
            if (!Main.showItemText)
            {
                return -1;
            }
            if (Main.netMode == 2)
            {
                return -1;
            }
            int num = PopupText.FindNextItemTextSlot();
            if (num >= 0)
            {
                string text = request.Text;
                Vector2 vector = FontAssets.MouseText.Value.MeasureString(text);
                PopupText popupText = PopupText.popupText[num];
                PopupText.ResetText(popupText);
                popupText.active = true;
                popupText.position = position - vector / 2f;
                popupText.name = text;
                popupText.stack = 1L;
                popupText.velocity = request.Velocity;
                popupText.lifeTime = request.DurationInFrames;
                popupText.context = PopupTextContext.Advanced;
                popupText.freeAdvanced = true;
                popupText.color = request.Color;
                popupText.PrepareDisplayText();
            }
            return num;
        }
References Terraria.AdvancedPopupRequest.Color, Terraria.AdvancedPopupRequest.DurationInFrames, Terraria.PopupText.FindNextItemTextSlot(), System.L, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.netMode, Terraria.PopupText.popupText, Terraria.PopupText.position, Terraria.PopupText.PrepareDisplayText(), Terraria.PopupText.ResetText(), Terraria.Main.showItemText, System.text, Terraria.AdvancedPopupRequest.Text, ReLogic.Content.Asset< T >.Value, and Terraria.AdvancedPopupRequest.Velocity.
Referenced by Terraria.Player.FillAmmo(), Terraria.Player.GetItem_FillEmptyInventorySlot(), Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag(), Terraria.Player.GetItem_FillIntoOccupiedSlot(), Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag(), Terraria.GameContent.CraftingEffects.OnCraftItemGranted(), Terraria.Main.ReforgeItemInReforgeSlot(), Terraria.Projectile.SetFishingCheckResults(), and Terraria.GameContent.LucyAxeMessage.SpawnPopupText().