Terraria Decompiled: Terraria.PopupText.NewText
NewText() [3/3]
static int Terraria.PopupText.NewText (PopupTextContext context, Item newItem, Vector2 position, int stack, bool noStack = false, bool longText = false) inline static
Definition at line 156 of file PopupText.cs.
        {
            if (!Main.showItemText)
            {
                return -1;
            }
            if (newItem.Name == null)
            {
                return -1;
            }
            if (Main.netMode == 2)
            {
                return -1;
            }
            bool flag = newItem.type >= 71 && newItem.type <= 74;
            for (int i = 0; i < 20; i++)
            {
                PopupText popupText = PopupText.popupText[i];
                if (popupText.active && !popupText.notActuallyAnItem && (popupText.name == newItem.AffixName() || (flag && popupText.coinText)) && !popupText.NoStack && !noStack)
                {
                    string text = string.Concat(new object[]
                    {
                        newItem.Name,
                        " (",
                        popupText.stack + (long)stack,
                        ")"
                    });
                    string text2 = newItem.Name;
                    if (popupText.stack > 1L)
                    {
                        text2 = string.Concat(new object[] { text2, " (", popupText.stack, ")" });
                    }
                    Vector2 vector = FontAssets.MouseText.Value.MeasureString(text2);
                    vector = FontAssets.MouseText.Value.MeasureString(text);
                    if (popupText.lifeTime < 0)
                    {
                        popupText.scale = 1f;
                    }
                    if (popupText.lifeTime < 60)
                    {
                        popupText.lifeTime = 60;
                    }
                    if (flag && popupText.coinText)
                    {
                        long num = 0L;
                        if (newItem.type == 71)
{
                            num += (long)stack;
                        }
                        else if (newItem.type == 72)
{
                            num += (long)(100 * stack);
                        }
                        else if (newItem.type == 73)
{
                            num += (long)(10000 * stack);
                        }
                        else if (newItem.type == 74)
{
                            num += (long)(1000000 * stack);
                        }
                        popupText.AddToCoinValue(num);
                        text = PopupText.ValueToName(popupText.coinValue);
                        vector = FontAssets.MouseText.Value.MeasureString(text);
                        popupText.name = text;
                        if (popupText.coinValue >= 1000000L)
{
                            if (popupText.lifeTime < 300)
{
                                popupText.lifeTime = 300;
                            }
                            popupText.color = new Color(220, 220, 198);
                        }
                        else if (popupText.coinValue >= 10000L)
{
                            if (popupText.lifeTime < 240)
{
                                popupText.lifeTime = 240;
                            }
                            popupText.color = new Color(224, 201, 92);
                        }
                        else if (popupText.coinValue >= 100L)
{
                            if (popupText.lifeTime < 180)
{
                                popupText.lifeTime = 180;
                            }
                            popupText.color = new Color(181, 192, 193);
                        }
                        else if (popupText.coinValue >= 1L)
{
                            if (popupText.lifeTime < 120)
{
                                popupText.lifeTime = 120;
                            }
                            popupText.color = new Color(246, 138, 96);
                        }
                    }
                    popupText.stack += (long)stack;
                    popupText.scale = 0f;
                    popupText.rotation = 0f;
                    popupText.position.X = position.X + (float)newItem.width * 0.5f - vector.X * 0.5f;
                    popupText.position.Y = position.Y + (float)newItem.height * 0.25f - vector.Y * 0.5f;
                    popupText.velocity.Y = -7f;
                    popupText.context = context;
                    popupText.npcNetID = 0;
                    popupText.effectStyle = PopupEffectStyle.None;
                    if (popupText.coinText)
                    {
                        popupText.stack = 1L;
                    }
                    PopupText.PrepareEffects(context, newItem, popupText);
                    if (popupText.AnyEffect)
                    {
                        popupText.framesSinceSpawn = 0;
                    }
                    popupText.PrepareDisplayText();
                    return i;
                }
            }
            int num2 = PopupText.FindNextItemTextSlot();
            if (num2 >= 0)
            {
                string text3 = newItem.AffixName();
                if (stack > 1)
                {
                    text3 = string.Concat(new object[] { text3, " (", stack, ")" });
                }
                Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(text3);
                PopupText popupText2 = PopupText.popupText[num2];
                PopupText.ResetText(popupText2);
                popupText2.active = true;
                popupText2.position.X = position.X - vector2.X * 0.5f;
                popupText2.position.Y = position.Y - vector2.Y * 0.5f;
                popupText2.name = newItem.AffixName();
                popupText2.stack = (long)stack;
                popupText2.velocity.Y = -7f;
                popupText2.lifeTime = 60;
                popupText2.context = context;
                if (longText)
                {
                    popupText2.lifeTime *= 5;
                }
                popupText2.coinValue = 0L;
                popupText2.coinText = newItem.type >= 71 && newItem.type <= 74;
                if (popupText2.coinText)
                {
                    long num3 = 0L;
                    if (newItem.type == 71)
                    {
                        num3 += popupText2.stack;
                    }
                    else if (newItem.type == 72)
                    {
                        num3 += 100L * popupText2.stack;
                    }
                    else if (newItem.type == 73)
                    {
                        num3 += 10000L * popupText2.stack;
                    }
                    else if (newItem.type == 74)
                    {
                        num3 += 1000000L * popupText2.stack;
                    }
                    popupText2.AddToCoinValue(num3);
                    popupText2.ValueToName();
                    popupText2.stack = 1L;
                    if (popupText2.coinValue >= 1000000L)
                    {
                        if (popupText2.lifeTime < 300)
{
                            popupText2.lifeTime = 300;
                        }
                        popupText2.color = new Color(220, 220, 198);
                    }
                    else if (popupText2.coinValue >= 10000L)
                    {
                        if (popupText2.lifeTime < 240)
{
                            popupText2.lifeTime = 240;
                        }
                        popupText2.color = new Color(224, 201, 92);
                    }
                    else if (popupText2.coinValue >= 100L)
                    {
                        if (popupText2.lifeTime < 180)
{
                            popupText2.lifeTime = 180;
                        }
                        popupText2.color = new Color(181, 192, 193);
                    }
                    else if (popupText2.coinValue >= 1L)
                    {
                        if (popupText2.lifeTime < 120)
{
                            popupText2.lifeTime = 120;
                        }
                        popupText2.color = new Color(246, 138, 96);
                    }
                }
                PopupText.PrepareEffects(context, newItem, popupText2);
                popupText2.PrepareDisplayText();
            }
            return num2;
        }
References Terraria.PopupText.active, Terraria.PopupText.AddToCoinValue(), Terraria.Item.AffixName(), Terraria.PopupText.AnyEffect, Terraria.PopupText.coinText, Terraria.PopupText.coinValue, Microsoft.Xna.Framework.Graphics.Color, Terraria.PopupText.context, Terraria.PopupText.FindNextItemTextSlot(), Terraria.Item.height, System.L, Terraria.PopupText.lifeTime, long, Terraria.GameContent.FontAssets.MouseText, Terraria.Item.Name, Terraria.PopupText.name, Terraria.Main.netMode, Terraria.PopupText.NoStack, Terraria.PopupText.notActuallyAnItem, Terraria.PopupText.popupText, Terraria.PopupText.PrepareDisplayText(), Terraria.PopupText.PrepareEffects(), Terraria.PopupText.ResetText(), Terraria.Main.showItemText, Terraria.PopupText.stack, System.text, Terraria.Item.type, ReLogic.Content.Asset< T >.Value, Terraria.PopupText.ValueToName(), Terraria.Item.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.