Terraria Decompiled: Terraria.PopupText.Update
Update()
void Terraria.PopupText.Update (int whoAmI) inline
Definition at line 629 of file PopupText.cs.
        {
            if (this.active)
            {
                this.framesSinceSpawn++;
                float targetScale = PopupText.TargetScale;
                this.alpha += (float)this.alphaDir * 0.01f;
                if ((double)this.alpha <= 0.7)
                {
                    this.alpha = 0.7f;
                    this.alphaDir = 1;
                }
                if (this.alpha >= 1f)
                {
                    this.alpha = 1f;
                    this.alphaDir = -1;
                }
                if (this.expert)
                {
                    this.color = new Color((int)((byte)Main.DiscoR), (int)((byte)Main.DiscoG), (int)((byte)Main.DiscoB), (int)Main.mouseTextColor);
                }
                else if (this.master)
                {
                    this.color = new Color(255, (int)((byte)(Main.masterColor * 200f)), 0, (int)Main.mouseTextColor);
                }
                bool flag = false;
                Vector2 textHitbox = this.GetTextHitbox();
                Rectangle rectangle = new Rectangle((int)(this.position.X - textHitbox.X / 2f), (int)(this.position.Y - textHitbox.Y / 2f), (int)textHitbox.X, (int)textHitbox.Y);
                if (this.AnyEffect && this.framesSinceSpawn == 8)
                {
                    PopupText.EmitFancyFlashDust(this);
                }
                for (int i = 0; i < 20; i++)
                {
                    PopupText popupText = PopupText.popupText[i];
                    if (popupText.active && i != whoAmI)
                    {
                        Vector2 textHitbox2 = popupText.GetTextHitbox();
                        Rectangle rectangle2 = new Rectangle((int)(popupText.position.X - textHitbox2.X / 2f), (int)(popupText.position.Y - textHitbox2.Y / 2f), (int)textHitbox2.X, (int)textHitbox2.Y);
                        if (rectangle.Intersects(rectangle2) && (this.position.Y < popupText.position.Y || (this.position.Y == popupText.position.Y && whoAmI < i)))
{
                            flag = true;
                            int num = PopupText.numActive;
                            if (num > 3)
{
                                num = 3;
                            }
                            popupText.lifeTime = PopupText.activeTime + 15 * num;
                            this.lifeTime = PopupText.activeTime + 15 * num;
                        }
                    }
                }
                if (!flag)
                {
                    this.velocity.Y = this.velocity.Y * 0.86f;
                    if (this.scale == targetScale)
                    {
                        this.velocity.Y = this.velocity.Y * 0.4f;
                    }
                }
                else if (this.velocity.Y > -6f)
                {
                    this.velocity.Y = this.velocity.Y - 0.2f;
                }
                else
                {
                    this.velocity.Y = this.velocity.Y * 0.86f;
                }
                this.velocity.X = this.velocity.X * 0.93f;
                this.position += this.velocity;
                this.lifeTime--;
                if (this.lifeTime <= 0)
                {
                    this.scale -= 0.03f * targetScale;
                    if ((double)this.scale < 0.1 * (double)targetScale)
                    {
                        this.active = false;
                        if (PopupText.sonarText == whoAmI)
{
                            PopupText.sonarText = -1;
                        }
                    }
                    this.lifeTime = 0;
                    return;
                }
                if (this.scale < targetScale)
                {
                    this.scale += 0.1f * targetScale;
                }
                if (this.scale > targetScale)
                {
                    this.scale = targetScale;
                }
            }
        }
References Terraria.PopupText.active, Terraria.PopupText.alpha, Terraria.PopupText.alphaDir, Terraria.PopupText.AnyEffect, Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.PopupText.EmitFancyFlashDust(), Terraria.PopupText.expert, Terraria.PopupText.framesSinceSpawn, Terraria.PopupText.GetTextHitbox(), Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.PopupText.lifeTime, Terraria.PopupText.master, Terraria.Main.masterColor, Terraria.Main.mouseTextColor, Terraria.PopupText.numActive, Terraria.PopupText.popupText, Terraria.PopupText.position, Terraria.PopupText.scale, Terraria.PopupText.sonarText, Terraria.PopupText.TargetScale, Terraria.PopupText.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.PopupText.UpdateItemText().