Terraria Decompiled: Terraria.PopupText.PrepareEffects
PrepareEffects()
static void Terraria.PopupText.PrepareEffects (PopupTextContext context, Item newItem, PopupText somePopup) inline static private
Definition at line 363 of file PopupText.cs.
        {
            if (newItem.rare == -13)
            {
                somePopup.master = true;
            }
            somePopup.expert = newItem.expert;
            CraftingEffectDetails effectDetails = CraftingEffects.GetEffectDetails(newItem);
            if (!somePopup.coinText)
            {
                somePopup.color = Item.GetPopupRarityColor(effectDetails.Rarity);
            }
            if (context == PopupTextContext.ItemCraft)
            {
                somePopup.effectIntensity = effectDetails.Intensity;
                somePopup.effectStyle = effectDetails.Style;
            }
        }
References Terraria.PopupText.coinText, Terraria.PopupText.context, Terraria.Item.expert, Terraria.GameContent.CraftingEffects.GetEffectDetails(), Terraria.Item.GetPopupRarityColor(), Terraria.GameContent.CraftingEffectDetails.Intensity, Terraria.Item.rare, Terraria.GameContent.CraftingEffectDetails.Rarity, and Terraria.GameContent.CraftingEffectDetails.Style.
Referenced by Terraria.PopupText.NewText().