Terraria Decompiled: Terraria.PopupText.DrawItemTextPopups
DrawItemTextPopups()
static void Terraria.PopupText.DrawItemTextPopups (float scaleTarget) inline static
Definition at line 761 of file PopupText.cs.
        {
            SpriteBatch spriteBatch = Main.spriteBatch;
            Vector2 screenPosition = Main.screenPosition;
            int screenHeight = Main.screenHeight;
            for (int i = 0; i < 20; i++)
            {
                PopupText popupText = PopupText.popupText[i];
                if (popupText.active)
                {
                    string text = popupText.displayText;
                    Vector2 vector = FontAssets.MouseText.Value.MeasureString(text);
                    Vector2 vector2 = new Vector2(vector.X * 0.5f, vector.Y * 0.5f);
                    float num = scaleTarget;
                    float num2 = popupText.scale / num;
                    int num3 = (int)(255f - 255f * num2);
                    float num4 = (float)popupText.color.R;
                    float num5 = (float)popupText.color.G;
                    float num6 = (float)popupText.color.B;
                    float num7 = (float)popupText.color.A;
                    num4 *= num2 * popupText.alpha * 0.3f;
                    float num8 = popupText.alpha;
                    float num9 = popupText.alpha;
                    num7 *= num2 * popupText.alpha;
                    Color color = Color.Black;
                    float num10 = 1f;
                    Texture2D texture2D = null;
                    Vector2[] array = null;
                    Color[] array2 = null;
                    PopupTextContext popupTextContext = popupText.context;
                    if (popupTextContext != PopupTextContext.ItemPickupToVoidContainer)
                    {
                        if (popupTextContext != PopupTextContext.SonarAlert)
{
                            if (popupTextContext == PopupTextContext.ItemReforge_Best)
{
                                color = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.6f % 1f, 1f, 0.6f, byte.MaxValue) * 0.6f;
                                num *= 0.5f;
                                num10 = 0.8f;
                            }
                        }
                        else
{
                            color = Color.Blue * 0.4f;
                            if (popupText.npcNetID != 0)
{
                                color = Color.Red * 0.4f;
                            }
                            num10 = 1f;
                        }
                    }
                    else
                    {
                        color = new Color(127, 20, 255) * 0.4f;
                        num10 = 0.8f;
                    }
                    int num11 = 40;
                    float num12 = Utils.Remap((float)popupText.framesSinceSpawn, 0f, (float)num11, 0f, 1f, true);
                    float num13 = (float)Utils.EaseOutCirc((double)num12);
                    if (popupText.effectStyle == PopupEffectStyle.Metal || popupText.effectStyle == PopupEffectStyle.MagicWeapon || popupText.effectStyle == PopupEffectStyle.RangedWeapon || popupText.effectStyle == PopupEffectStyle.SummonWeapon || popupText.effectStyle == PopupEffectStyle.MeleeWeapon)
                    {
                        Vector2 vector3 = new Vector2(0f, -4f);
                        Vector2 vector4 = popupText.position - screenPosition + vector2;
                        float num14 = popupText.scale;
                        num10 = (float)Utils.Lerp(0.6000000238418579, 1.0, (double)num12);
                        Vector3 vector5 = Main.rgbToHsl(popupText.color);
                        Color color2 = Main.hslToRgb(vector5.X, vector5.Y, 1f - num12, byte.MaxValue);
                        color2.A = 0;
                        float num15 = (float)Utils.EaseInCirc((double)Utils.Clamp<float>(num12 * 1.25f, 0f, 1f));
                        color = Color.Lerp(color2, Color.Black, num15);
                        float num16 = Utils.Remap(num12, 0f, 0.1f, 0f, 1f, true) * Utils.Remap(num12, 0.1f, 1f, 1f, 0f, true);
                        float num17 = Utils.Remap(num12, 0f, 0.2f, 0f, 1f, true) * Utils.Remap(num12, 0.2f, 0.8f, 1f, 0f, true);
                        Texture2D value = TextureAssets.Extra[98].Value;
                        Vector2 vector6 = value.Frame(1, 1, 0, 0, 0, 0).Size() / 2f;
                        Vector2 vector7 = new Vector2(1f, vector.X / (float)value.Width);
                        vector7 *= num14;
                        if (num16 > 0f)
{
                            Vector2 vector8 = new Vector2(Utils.Remap(num13, 0f, 1f, -20f, 20f, true), 0f) + vector3;
                            vector8 *= num14;
                            Vector2 vector9 = new Vector2(-60f, 0f);
                            while (vector9.X <= 40f)
{
                                spriteBatch.Draw(value, vector4 + vector8 + vector9 * num14, null, popupText.color * num16, 1.5707964f, vector6, vector7, SpriteEffects.None, 0f);
                                vector9.X += 40f;
                            }
                            Vector2 vector10 = new Vector2(-20f, 0f);
                            while (vector10.X <= 20f)
{
                                spriteBatch.Draw(value, vector4 + vector8 + vector10 * num14, null, new Color(255, 255, 255, 0) * 0.5f * num17, 1.5707964f, vector6, vector7 * 0.5f, SpriteEffects.None, 0f);
                                vector10.X += 20f;
                            }
                        }
                        float num18 = 6.2831855f * num12;
                        float num19 = (float)Utils.EaseOutCirc((double)Utils.Clamp<float>(num12 * 2f, 0f, 1f));
                        float num20 = Utils.Remap(num12, 0.1f, 0.3f, 0f, 1f, true) * Utils.Remap(num12, 0.3f, 0.6f, 1f, 0f, true);
                        Vector2 vector11 = new Vector2(vector.X, 0f) * Utils.Remap(num19, 0f, 1f, -0.8f, 0.4f, true) + vector3;
                        vector11 *= num14;
                        spriteBatch.Draw(value, vector4 + vector11, null, popupText.color * num20, 0f + num18, vector6, num14, SpriteEffects.None, 0f);
                        spriteBatch.Draw(value, vector4 + vector11, null, popupText.color * num20, 1.5707964f + num18, vector6, num14 * 1.3f, SpriteEffects.None, 0f);
                        spriteBatch.Draw(value, vector4 + vector11, null, new Color(255, 255, 255, 0) * num20, 0f + num18, vector6, new Vector2(0.5f, 0.5f) * num14 * 1.3f, SpriteEffects.None, 0f);
                        spriteBatch.Draw(value, vector4 + vector11, null, new Color(255, 255, 255, 0) * num20, 1.5707964f + num18, vector6, new Vector2(0.5f, 0.5f) * num14, SpriteEffects.None, 0f);
                        num18 = 0f;
                        spriteBatch.Draw(value, vector4 + vector11, null, popupText.color * num20, 0f + num18, vector6, num14, SpriteEffects.None, 0f);
                        spriteBatch.Draw(value, vector4 + vector11, null, popupText.color * num20, 1.5707964f + num18, vector6, num14 * 1.3f, SpriteEffects.None, 0f);
                        spriteBatch.Draw(value, vector4 + vector11, null, new Color(255, 255, 255, 0) * num20, 0f + num18, vector6, new Vector2(0.5f, 0.5f) * num14 * 1.3f, SpriteEffects.None, 0f);
                        spriteBatch.Draw(value, vector4 + vector11, null, new Color(255, 255, 255, 0) * num20, 1.5707964f + num18, vector6, new Vector2(0.5f, 0.5f) * num14, SpriteEffects.None, 0f);
                        array2 = popupText.charColors;
                        float num21 = 1f / (float)text.Length;
                        for (int j = 0; j < text.Length; j++)
{
                            float num22 = Utils.Remap(num13, num21 * (float)j, num21 * (float)(j + 1), 0f, 1f, true);
                            array2[j] = Color.Lerp(Color.White, popupText.color, num22);
                        }
                    }
                    if (popupText.effectStyle == PopupEffectStyle.MagicWeapon)
                    {
                        array = popupText.charOffsets;
                        float num23 = 1f / (float)text.Length;
                        for (int k = 0; k < text.Length; k++)
{
                            Utils.Remap(num13 * 1.25f, num23 * (float)k, num23 * (float)(k + 1), 0f, 1f, true);
                            Vector2 vector12 = new Vector2(-(float)Math.Sin((double)(6.2831855f * ((float)(k * 31) / 12f))) * 144f, 0f);
                            array[k] = Vector2.Lerp(vector12, Vector2.Zero, num13);
                        }
                    }
                    if (popupText.effectStyle == PopupEffectStyle.RangedWeapon)
                    {
                        array = popupText.charOffsets;
                        array2 = popupText.charColors;
                        color = Color.Transparent;
                        float num24 = 1f / (float)text.Length;
                        float num25 = Utils.Clamp<float>(num13 * 3f, 0f, 1f);
                        float num26 = Utils.Clamp<float>(num13 * 1.5f, 0f, 1f);
                        for (int l = 0; l < text.Length; l++)
{
                            float num27 = Utils.Remap(num13, num24 * (float)l, num24 * (float)(l + 1), 0f, 1f, true);
                            array2[l] = Color.Lerp(new Color(0, 0, 0, 1), popupText.color, num27);
                            Vector2 vector13 = new Vector2(60f * num27 - 120f * num25, ((float)Math.Sin((double)(6.2831855f * ((float)(l * 31) / 12f))) * 0.5f + 0.5f) * -204f * (1f - num26));
                            array[l] = Vector2.Lerp(vector13, Vector2.Zero, num13);
                        }
                    }
                    if (popupText.effectStyle == PopupEffectStyle.Potion)
                    {
                        array = popupText.charOffsets;
                        float num28 = 1f / (float)text.Length;
                        for (int m = 0; m < text.Length; m++)
{
                            Utils.Remap(num13 * 1.25f, num28 * (float)m, num28 * (float)(m + 1), 0f, 1f, true);
                            Vector2 vector14 = new Vector2(0f, (float)Math.Sin((double)(6.2831855f * ((float)m / 12f))) * 20f);
                            array[m] = Vector2.Lerp(vector14, Vector2.Zero, num13);
                        }
                    }
                    float num29 = (float)num3 / 255f;
                    for (int n = 0; n < 5; n++)
                    {
                        Color color3 = color;
                        float num30 = 0f;
                        float num31 = 0f;
                        if (n == 0)
{
                            num30 -= num * 2f;
                        }
                        else if (n == 1)
{
                            num30 += num * 2f;
                        }
                        else if (n == 2)
{
                            num31 -= num * 2f;
                        }
                        else if (n == 3)
{
                            num31 += num * 2f;
                        }
                        else
{
                            color3 = popupText.color * num2 * popupText.alpha * num10;
                        }
                        if (n < 4)
{
                            num7 = (float)popupText.color.A * num2 * popupText.alpha;
                            color3 = new Color(0, 0, 0, (int)num7);
                        }
                        if (color != Color.Black && n < 4)
{
                            num30 *= 1.3f + 1.3f * num29;
                            num31 *= 1.3f + 1.3f * num29;
                        }
                        float num32 = popupText.position.Y - screenPosition.Y + num31;
                        if (Main.player[Main.myPlayer].gravDir == -1f)
{
                            num32 = (float)screenHeight - num32;
                        }
                        if (color != Color.Black && n < 4)
{
                            Color color4 = color;
                            color4.A = (byte)MathHelper.Lerp(60f, 127f, Utils.GetLerpValue(0f, 255f, num7, true));
                            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(popupText.position.X - screenPosition.X + num30 + vector2.X, num32 + vector2.Y), Color.Lerp(color3, color4, 0.5f), popupText.rotation, vector2, popupText.scale, SpriteEffects.None, 0f, array, null);
                            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(popupText.position.X - screenPosition.X + num30 + vector2.X, num32 + vector2.Y), color4, popupText.rotation, vector2, popupText.scale, SpriteEffects.None, 0f, array, null);
                        }
                        else
{
                            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(popupText.position.X - screenPosition.X + num30 + vector2.X, num32 + vector2.Y), color3, popupText.rotation, vector2, popupText.scale, SpriteEffects.None, 0f, array, (n == 4) ? array2 : null);
                        }
                        if (texture2D != null)
{
                            float num33 = (1.3f - num29) * popupText.scale * 0.7f;
                            Vector2 vector15 = new Vector2(popupText.position.X - screenPosition.X + num30 + vector2.X, num32 + vector2.Y);
                            Color color5 = color * 0.6f;
                            if (n == 4)
{
                                color5 = Color.White * 0.6f;
                            }
                            color5.A = (byte)((float)color5.A * 0.5f);
                            int num34 = 25;
                            spriteBatch.Draw(texture2D, vector15 + new Vector2(vector2.X * -0.5f - (float)num34 - texture2D.Size().X / 2f, 0f), null, color5 * popupText.scale, 0f, texture2D.Size() / 2f, num33, SpriteEffects.None, 0f);
                            spriteBatch.Draw(texture2D, vector15 + new Vector2(vector2.X * 0.5f + (float)num34 + texture2D.Size().X / 2f, 0f), null, color5 * popupText.scale, 0f, texture2D.Size() / 2f, num33, SpriteEffects.None, 0f);
                        }
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Color.A, Terraria.PopupText.active, Terraria.PopupText.alpha, System.array, Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Color.Black, Terraria.PopupText.charColors, Terraria.PopupText.charOffsets, Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Graphics.Color, Terraria.PopupText.color, Terraria.PopupText.context, Terraria.PopupText.displayText, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Utils.EaseInCirc(), Terraria.Utils.EaseOutCirc(), Terraria.PopupText.effectStyle, Terraria.GameContent.TextureAssets.Extra, Terraria.PopupText.framesSinceSpawn, Microsoft.Xna.Framework.Color.G, Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Player.gravDir, Terraria.Main.hslToRgb(), int, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Utils.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.myPlayer, Terraria.PopupText.npcNetID, Terraria.Main.player, Terraria.PopupText.popupText, Terraria.PopupText.position, Microsoft.Xna.Framework.Color.R, Terraria.Utils.Remap(), Terraria.Main.rgbToHsl(), Terraria.PopupText.rotation, Terraria.PopupText.scale, Terraria.Main.screenHeight, Terraria.Main.screenPosition, System.Math.Sin(), Terraria.Main.spriteBatch, System.text, Microsoft.Xna.Framework.Color.Transparent, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector2.Zero.