Terraria Decompiled: Terraria.Initializers.DyeInitializer.LoadBasicColorDye
LoadBasicColorDye() [2/2]
static void Terraria.Initializers.DyeInitializer.LoadBasicColorDye (int baseDyeItem, int blackDyeItem, int brightDyeItem, int silverDyeItem, float r, float g, float b, float saturation = 1f, int oldShader = 1) inline static private
Definition at line 16 of file DyeInitializer.cs.
        {
            Asset<Effect> pixelShaderRef = Main.PixelShaderRef;
            GameShaders.Armor.BindShader<ArmorShaderData>(baseDyeItem, new ArmorShaderData(pixelShaderRef, "ArmorColored")).UseColor(r, g, b).UseSaturation(saturation);
            GameShaders.Armor.BindShader<ArmorShaderData>(blackDyeItem, new ArmorShaderData(pixelShaderRef, "ArmorColoredAndBlack")).UseColor(r, g, b).UseSaturation(saturation);
            GameShaders.Armor.BindShader<ArmorShaderData>(brightDyeItem, new ArmorShaderData(pixelShaderRef, "ArmorColored")).UseColor(r * 0.5f + 0.5f, g * 0.5f + 0.5f, b * 0.5f + 0.5f).UseSaturation(saturation);
            GameShaders.Armor.BindShader<ArmorShaderData>(silverDyeItem, new ArmorShaderData(pixelShaderRef, "ArmorColoredAndSilverTrim")).UseColor(r, g, b).UseSaturation(saturation);
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.PixelShaderRef, and Terraria.Graphics.Shaders.ArmorShaderData.UseSaturation().
Referenced by Terraria.Initializers.DyeInitializer.LoadBasicColorDye(), and Terraria.Initializers.DyeInitializer.LoadBasicColorDyes().