Terraria Decompiled: System.IO.BufferedStream.d__34.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.BufferedStream.d__34.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1118 of file BufferedStream.cs.
            {
                int num2;
                int num = num2;
                BufferedStream bufferedStream = this;
                try
                {
                    try
                    {
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                        if (num != 0)
{
                            if (num == 1)
{
                                ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                                configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                                configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                                num = (num2 = -1);
                                goto IL_0116;
                            }
                            if (bufferedStream._stream == null)
{
                                goto IL_0147;
                            }
                            obj = null;
                            int num3 = 0;
                        }
                        try
{
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                            if (num != 0)
{
                                configuredTaskAwaiter = bufferedStream.FlushAsync().ConfigureAwait(false).GetAwaiter();
                                if (!configuredTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 0);
                                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<DisposeAsync>d__34>(ref configuredTaskAwaiter, ref this);
                                    return;
                                }
                            }
                            else
{
                                ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                                configuredTaskAwaiter = configuredTaskAwaiter2;
                                configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                                num = (num2 = -1);
                            }
                            configuredTaskAwaiter.GetResult();
                        }
                        catch (object obj2)
{
                            obj = obj2;
                        }
                        configuredValueTaskAwaiter = bufferedStream._stream.DisposeAsync().ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num = (num2 = 1);
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, BufferedStream.<DisposeAsync>d__34>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                        IL_0116:
                        configuredValueTaskAwaiter.GetResult();
                        object obj2 = obj;
                        if (obj2 != null)
{
                            Exception ex = obj2 as Exception;
                            if (ex == null)
{
                                throw obj2;
                            }
                            ExceptionDispatchInfo.Capture(ex).Throw();
                        }
                        obj = null;
                        IL_0147:;
                    }
                    finally
                    {
                        if (num < 0)
{
                            bufferedStream._stream = null;
                            bufferedStream._buffer = null;
                        }
                    }
                }
                catch (Exception ex2)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex2);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.IO.BufferedStream._stream, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.IO.BufferedStream.DisposeAsync(), System.IO.Stream.DisposeAsync(), System.IO.BufferedStream.FlushAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted, System.obj, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().