Terraria Decompiled: Terraria.GameContent.PlayerSleepingHelper.StartSleeping
StartSleeping()
void Terraria.GameContent.PlayerSleepingHelper.StartSleeping (Player player, int x, int y) inline
Definition at line 134 of file PlayerSleepingHelper.cs.
        {
            int num;
            Vector2 vector;
            Vector2 vector2;
            PlayerSleepingHelper.GetSleepingTargetInfo(x, y, out num, out vector, out vector2);
            Vector2 vector3 = vector - player.Bottom;
            bool flag = player.CanSnapToPosition(vector3);
            if (flag)
            {
                flag &= Main.sleepingManager.GetNextPlayerStackIndexInCoords((vector + new Vector2(0f, -2f)).ToTileCoordinates()) < 2;
            }
            if (!flag)
            {
                return;
            }
            if (this.isSleeping && player.Bottom == vector)
            {
                this.StopSleeping(player, true);
                return;
            }
            player.StopVanityActions(true);
            player.RemoveAllGrapplingHooks();
            player.RemoveAllFishingBobbers();
            if (player.mount.Active)
            {
                player.mount.TryDismount(player);
            }
            player.Bottom = vector;
            player.ChangeDir(num);
            Main.sleepingManager.AddPlayerAndGetItsStackedIndexInCoords(player.whoAmI, new Point(x, y), out this.sleepingIndex);
            player.velocity = Vector2.Zero;
            player.gravDir = 1f;
            this.SetIsSleepingAndAdjustPlayerRotation(player, true);
            this.visualOffsetOfBedBase = vector2;
            if (Main.myPlayer == player.whoAmI)
            {
                NetMessage.SendData(13, -1, -1, null, player.whoAmI, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Mount.Active, Terraria.Entity.Bottom, Terraria.Player.CanSnapToPosition(), Terraria.Player.ChangeDir(), Terraria.GameContent.PlayerSleepingHelper.GetSleepingTargetInfo(), Terraria.GameContent.PlayerSleepingHelper.isSleeping, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Player.RemoveAllFishingBobbers(), Terraria.Player.RemoveAllGrapplingHooks(), Terraria.NetMessage.SendData(), Terraria.GameContent.PlayerSleepingHelper.SetIsSleepingAndAdjustPlayerRotation(), Terraria.GameContent.PlayerSleepingHelper.sleepingIndex, Terraria.Main.sleepingManager, Terraria.GameContent.PlayerSleepingHelper.StopSleeping(), Terraria.Player.StopVanityActions(), Terraria.Mount.TryDismount(), Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.Zero.