Terraria Decompiled: System.IO.MemoryStream.CopyTo
CopyTo()
override void System.IO.MemoryStream.CopyTo (Stream destination, int bufferSize) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 521 of file MemoryStream.cs.
        {
            StreamHelpers.ValidateCopyToArgs(this, destination, bufferSize);
            if (base.GetType() != typeof(MemoryStream))
            {
                base.CopyTo(destination, bufferSize);
                return;
            }
            int position = this._position;
            int num = this.InternalEmulateRead(this._length - position);
            if (num > 0)
            {
                destination.Write(this._buffer, position, num);
            }
        }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._length, System.IO.MemoryStream._position, System.destination, System.IO.MemoryStream.InternalEmulateRead(), and System.IO.StreamHelpers.ValidateCopyToArgs().
Referenced by Terraria.WorldBuilding.WorldGenSnapshot.ResaveForCurrentVersion().