Terraria Decompiled: System.IO.MemoryStream.WriteByte
WriteByte()
override void System.IO.MemoryStream.WriteByte (byte value) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 816 of file MemoryStream.cs.
        {
            this.EnsureNotClosed();
            this.EnsureWriteable();
            if (this._position >= this._length)
            {
                int num = this._position + 1;
                bool flag = this._position > this._length;
                if (num >= this._capacity && this.EnsureCapacity(num))
                {
                    flag = false;
                }
                if (flag)
                {
                    Array.Clear(this._buffer, this._length, this._position - this._length);
                }
                this._length = num;
            }
            byte[] buffer = this._buffer;
            int position = this._position;
            this._position = position + 1;
            buffer[position] = value;
        }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._capacity, System.IO.MemoryStream._length, System.IO.MemoryStream._position, System.Array.Clear(), System.IO.MemoryStream.EnsureCapacity(), System.IO.MemoryStream.EnsureNotClosed(), System.IO.MemoryStream.EnsureWriteable(), and System.value.
Referenced by System.Threading.Thread.SerializePrincipal().