Terraria Decompiled: System.IO.MemoryStream.ReadAsync
ReadAsync() [1/2]
override Task< int > System.IO.MemoryStream.ReadAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 432 of file MemoryStream.cs.
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer", "Buffer cannot be null.");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Non-negative number required.");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Non-negative number required.");
            }
            if (buffer.Length - offset < count)
            {
                throw new ArgumentException("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.");
            }
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCanceled<int>(cancellationToken);
            }
            Task<int> task;
            try
            {
                int num = this.Read(buffer, offset, count);
                Task<int> lastReadTask = this._lastReadTask;
                Task<int> task2;
                if (lastReadTask == null || lastReadTask.Result != num)
                {
                    task = (this._lastReadTask = Task.FromResult<int>(num));
                    task2 = task;
                }
                else
                {
                    task2 = lastReadTask;
                }
                task = task2;
            }
            catch (OperationCanceledException ex)
            {
                task = Task.FromCancellation<int>(ex);
            }
            catch (Exception ex2)
            {
                task = Task.FromException<int>(ex2);
            }
            return task;
        }
References System.IO.MemoryStream._lastReadTask, System.count, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromCancellation(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.CancellationToken.IsCancellationRequested, System.offset, System.IO.Read, System.Threading.Tasks.Task< TResult >.Result, and System.task.