Terraria Decompiled: System.IO.MemoryStream.Seek
Seek()
override long System.IO.MemoryStream.Seek (long offset, SeekOrigin loc) inline
Definition at line 574 of file MemoryStream.cs.
        {
            this.EnsureNotClosed();
            if (offset > 2147483647L)
            {
                throw new ArgumentOutOfRangeException("offset", "Stream length must be non-negative and less than 2^31 - 1 - origin.");
            }
            switch (loc)
            {
            case SeekOrigin.Begin:
            {
                int num = this._origin + (int)offset;
                if (offset < 0L || num < this._origin)
                {
                    throw new IOException("An attempt was made to move the position before the beginning of the stream.");
                }
                this._position = num;
                break;
            }
            case SeekOrigin.Current:
            {
                int num2 = this._position + (int)offset;
                if ((long)this._position + offset < (long)this._origin || num2 < this._origin)
                {
                    throw new IOException("An attempt was made to move the position before the beginning of the stream.");
                }
                this._position = num2;
                break;
            }
            case SeekOrigin.End:
            {
                int num3 = this._length + (int)offset;
                if ((long)this._length + offset < (long)this._origin || num3 < this._origin)
                {
                    throw new IOException("An attempt was made to move the position before the beginning of the stream.");
                }
                this._position = num3;
                break;
            }
            default:
                throw new ArgumentException("Invalid seek origin.");
            }
            return (long)this._position;
        }
References System.IO.MemoryStream._origin, System.IO.MemoryStream._position, System.IO.MemoryStream.EnsureNotClosed(), int, System.L, long, and System.offset.
Referenced by Ionic.Zip.ZipFile.AddEntry(), Microsoft.Xna.Framework.Graphics.Texture2D.DDSFromStreamEXT(), Microsoft.Xna.Framework.Graphics.TextureCube.DDSFromStreamEXT(), Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb(), System.Reflection.Emit.ModuleBuilder.Save(), Terraria.Player.SerializedClone(), and Ionic.Zlib.ZlibBaseStream.UncompressString().