Terraria Decompiled: System.IO.MemoryStream.WriteAsync
WriteAsync() [1/2]
override Task System.IO.MemoryStream.WriteAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 743 of file MemoryStream.cs.
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer", "Buffer cannot be null.");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Non-negative number required.");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Non-negative number required.");
            }
            if (buffer.Length - offset < count)
            {
                throw new ArgumentException("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.");
            }
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCanceled(cancellationToken);
            }
            Task task;
            try
            {
                this.Write(buffer, offset, count);
                task = Task.CompletedTask;
            }
            catch (OperationCanceledException ex)
            {
                task = Task.FromCancellation<VoidTaskResult>(ex);
            }
            catch (Exception ex2)
            {
                task = Task.FromException(ex2);
            }
            return task;
        }
References System.Threading.Tasks.Task< TResult >.CompletedTask, System.count, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromCancellation(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.CancellationToken.IsCancellationRequested, System.offset, System.task, and System.IO.Write.
Referenced by System.IO.MemoryStream.CopyToAsync().