Terraria Decompiled: System.IO.MemoryStream.ToArray
ToArray()
virtual byte[] System.IO.MemoryStream.ToArray () inline virtual
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 644 of file MemoryStream.cs.
        {
            int num = this._length - this._origin;
            if (num == 0)
            {
                return Array.Empty<byte>();
            }
            byte[] array = new byte[num];
            Buffer.BlockCopy(this._buffer, this._origin, array, 0, num);
            return array;
        }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._origin, System.array, and System.Buffer.BlockCopy().
Referenced by System.Reflection.Emit.AssemblyBuilder.AddUnmanagedResource(), Terraria.Netplay.BroadcastThread(), Ionic.Zlib.DeflateStream.CompressBuffer(), Ionic.Zlib.GZipStream.CompressBuffer(), Ionic.Zlib.ZlibStream.CompressBuffer(), Ionic.Zlib.DeflateStream.CompressString(), Ionic.Zlib.GZipStream.CompressString(), Ionic.Zlib.ZlibStream.CompressString(), System.Security.PermissionSet.ConvertPermissionSet(), Microsoft.Xna.Framework.Graphics.Resources.GetResource(), Terraria.Map.MapHelper.InternalSaveMap(), Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.Achievements.AchievementManager.Save(), System.Runtime.Remoting.RemotingServices.SerializeCallData(), System.Runtime.Remoting.RemotingServices.SerializeExceptionData(), System.AppDomainSetup.SerializeNonPrimitives(), System.Threading.Thread.SerializePrincipal(), System.Security.Policy.ApplicationTrust.ToXml(), Ionic.Zlib.ZlibBaseStream.UncompressBuffer(), and Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure().