Terraria Decompiled: System.IO.MemoryStream.Read
Read() [2/2]
override int System.IO.MemoryStream.Read (Span< byte > buffer) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 414 of file MemoryStream.cs.
        {
            if (base.GetType() != typeof(MemoryStream))
            {
                return base.Read(buffer);
            }
            this.EnsureNotClosed();
            int num = Math.Min(this._length - this._position, buffer.Length);
            if (num <= 0)
            {
                return 0;
            }
            new Span<byte>(this._buffer, this._position, num).CopyTo(buffer);
            this._position += num;
            return num;
        }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._length, System.IO.MemoryStream._position, System.Span< T >.CopyTo(), System.IO.MemoryStream.EnsureNotClosed(), System.Span< T >.Length, and System.Math.Min().