Terraria Decompiled: System.IO.MemoryStream.WriteAsync
WriteAsync() [2/2]
override ValueTask System.IO.MemoryStream.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 783 of file MemoryStream.cs.
        {
            if (cancellationToken.IsCancellationRequested)
            {
                return new ValueTask(Task.FromCanceled(cancellationToken));
            }
            ValueTask valueTask;
            try
            {
                ArraySegment<byte> arraySegment;
                if (MemoryMarshal.TryGetArray<byte>(buffer, out arraySegment))
                {
                    this.Write(arraySegment.Array, arraySegment.Offset, arraySegment.Count);
                }
                else
                {
                    this.Write(buffer.Span);
                }
                valueTask = default(ValueTask);
                valueTask = valueTask;
            }
            catch (OperationCanceledException ex)
            {
                valueTask = new ValueTask(Task.FromCancellation<VoidTaskResult>(ex));
            }
            catch (Exception ex2)
            {
                valueTask = new ValueTask(Task.FromException(ex2));
            }
            return valueTask;
        }
References System.ArraySegment< T >.Array, System.ArraySegment< T >.Count, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromCancellation(), System.Threading.Tasks.Task< TResult >.FromException(), System.ArraySegment< T >.Offset, System.ReadOnlyMemory< T >.Span, and System.IO.Write.