Terraria Decompiled: System.IO.MemoryStream.ReadByte
ReadByte()
override int System.IO.MemoryStream.ReadByte () inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 507 of file MemoryStream.cs.
        {
            this.EnsureNotClosed();
            if (this._position >= this._length)
            {
                return -1;
            }
            byte[] buffer = this._buffer;
            int position = this._position;
            this._position = position + 1;
            return buffer[position];
        }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._length, System.IO.MemoryStream._position, and System.IO.MemoryStream.EnsureNotClosed().
Referenced by System.Threading.Thread.DeserializePrincipal(), and Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb().