Terraria Decompiled: System.IO.MemoryStream.SetLength
SetLength()
override void System.IO.MemoryStream.SetLength (long value) inline
Definition at line 620 of file MemoryStream.cs.
        {
            if (value < 0L || value > 2147483647L)
            {
                throw new ArgumentOutOfRangeException("value", "Stream length must be non-negative and less than 2^31 - 1 - origin.");
            }
            this.EnsureWriteable();
            if (value > (long)(2147483647 - this._origin))
            {
                throw new ArgumentOutOfRangeException("value", "Stream length must be non-negative and less than 2^31 - 1 - origin.");
            }
            int num = this._origin + (int)value;
            if (!this.EnsureCapacity(num) && num > this._length)
            {
                Array.Clear(this._buffer, this._length, num - this._length);
            }
            this._length = num;
            if (this._position > num)
            {
                this._position = num;
            }
        }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._length, System.IO.MemoryStream._origin, System.IO.MemoryStream._position, System.Array.Clear(), System.IO.MemoryStream.EnsureCapacity(), System.IO.MemoryStream.EnsureWriteable(), int, System.L, and System.value.