Terraria Decompiled: System.IO.MemoryStream.Write
Write() [1/2]
override void System.IO.MemoryStream.Write (byte[] buffer, int offset, int count) inline
Definition at line 657 of file MemoryStream.cs.
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer", "Buffer cannot be null.");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Non-negative number required.");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Non-negative number required.");
            }
            if (buffer.Length - offset < count)
            {
                throw new ArgumentException("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.");
            }
            this.EnsureNotClosed();
            this.EnsureWriteable();
            int num = this._position + count;
            if (num < 0)
            {
                throw new IOException("Stream was too long.");
            }
            if (num > this._length)
            {
                bool flag = this._position > this._length;
                if (num > this._capacity && this.EnsureCapacity(num))
                {
                    flag = false;
                }
                if (flag)
                {
                    Array.Clear(this._buffer, this._length, num - this._length);
                }
                this._length = num;
            }
            if (count <= 8 && buffer != this._buffer)
            {
                int num2 = count;
                while (--num2 >= 0)
                {
                    this._buffer[this._position + num2] = buffer[offset + num2];
                }
            }
            else
            {
                Buffer.BlockCopy(buffer, offset, this._buffer, this._position, count);
            }
            this._position = num;
        }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._capacity, System.IO.MemoryStream._length, System.IO.MemoryStream._position, System.Buffer.BlockCopy(), System.Array.Clear(), System.count, System.IO.MemoryStream.EnsureCapacity(), System.IO.MemoryStream.EnsureNotClosed(), System.IO.MemoryStream.EnsureWriteable(), and System.offset.
Referenced by System.IO.MemoryStream.CopyToAsync(), Ionic.Zlib.ZlibBaseStream.UncompressBuffer(), and Ionic.Zlib.ZlibBaseStream.UncompressString().