Terraria Decompiled: System.IO.MemoryStream.EnsureNotClosed
EnsureNotClosed()
void System.IO.MemoryStream.EnsureNotClosed () inline private
Definition at line 127 of file MemoryStream.cs.
        {
            if (!this._isOpen)
            {
                throw Error.GetStreamIsClosed();
            }
        }
References System.IO.MemoryStream._isOpen, and System.IO.Error.GetStreamIsClosed().
Referenced by System.IO.MemoryStream.InternalEmulateRead(), System.IO.MemoryStream.InternalReadInt32(), System.IO.MemoryStream.Read(), System.IO.MemoryStream.Read(), System.IO.MemoryStream.ReadByte(), System.IO.MemoryStream.Seek(), System.IO.MemoryStream.Write(), System.IO.MemoryStream.Write(), System.IO.MemoryStream.WriteByte(), and System.IO.MemoryStream.WriteTo().