Terraria Decompiled: System.IO.MemoryStream.Write
Write() [2/2]
override void System.IO.MemoryStream.Write (ReadOnlySpan< byte > buffer) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 711 of file MemoryStream.cs.
        {
            if (base.GetType() != typeof(MemoryStream))
            {
                base.Write(buffer);
                return;
            }
            this.EnsureNotClosed();
            this.EnsureWriteable();
            int num = this._position + buffer.Length;
            if (num < 0)
            {
                throw new IOException("Stream was too long.");
            }
            if (num > this._length)
            {
                bool flag = this._position > this._length;
                if (num > this._capacity && this.EnsureCapacity(num))
                {
                    flag = false;
                }
                if (flag)
                {
                    Array.Clear(this._buffer, this._length, num - this._length);
                }
                this._length = num;
            }
            buffer.CopyTo(new Span<byte>(this._buffer, this._position, buffer.Length));
            this._position = num;
        }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._capacity, System.IO.MemoryStream._length, System.IO.MemoryStream._position, System.Array.Clear(), System.ReadOnlySpan< T >.CopyTo(), System.IO.MemoryStream.EnsureCapacity(), System.IO.MemoryStream.EnsureNotClosed(), System.IO.MemoryStream.EnsureWriteable(), and System.ReadOnlySpan< T >.Length.