Terraria Decompiled: System.IO.MemoryStream.GetBuffer
GetBuffer()
virtual byte[] System.IO.MemoryStream.GetBuffer () inline virtual
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 217 of file MemoryStream.cs.
        {
            if (!this._exposable)
            {
                throw new UnauthorizedAccessException("MemoryStream's internal buffer cannot be accessed.");
            }
            return this._buffer;
        }
References System.IO.MemoryStream._buffer, and System.IO.MemoryStream._exposable.
Referenced by System.Runtime.Remoting.Messaging.CADMethodCallMessage.CADMethodCallMessage(), System.Runtime.Remoting.Messaging.CADMethodReturnMessage.CADMethodReturnMessage(), System.Resources.ResourceWriter.Generate(), Microsoft.Xna.Framework.Content.ContentManager.GetContentReaderFromXnb(), System.AppDomain.GetMarshalledDomainObjRef(), System.Security.Claims.ClaimsIdentity.GetObjectData(), System.Runtime.Remoting.Channels.CrossAppDomainSink.ProcessMessageInDomain(), System.AppDomain.ProcessMessageInDomain(), System.Security.Claims.ClaimsIdentity.SerializeClaims(), System.Security.Claims.ClaimsPrincipal.SerializeIdentities(), System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(), and Microsoft.Xna.Framework.FNAInternalExtensions.TryGetBuffer().