Terraria Decompiled: System.Reflection.RuntimeEventInfo.GetEventInfo
GetEventInfo()
static MonoEventInfo System.Reflection.RuntimeEventInfo.GetEventInfo (RuntimeEventInfo ev) inline static package
Definition at line 19 of file RuntimeEventInfo.cs.
        {
            MonoEventInfo monoEventInfo;
            RuntimeEventInfo.get_event_info(ev, out monoEventInfo);
            return monoEventInfo;
        }
References System.Reflection.RuntimeEventInfo.get_event_info().
Referenced by System.Reflection.RuntimeEventInfo.GetAddMethod(), System.Reflection.RuntimeEventInfo.GetBindingFlags(), System.Reflection.RuntimeEventInfo.GetOtherMethods(), System.Reflection.RuntimeEventInfo.GetRaiseMethod(), and System.Reflection.RuntimeEventInfo.GetRemoveMethod().