Terraria Decompiled: System.Globalization.TextInfo.ToLowerInternal
ToLowerInternal() [2/2]
unsafe string System.Globalization.TextInfo.ToLowerInternal (string str) inline private
Definition at line 653 of file TextInfo.cs.
        {
            if (str.Length == 0)
            {
                return string.Empty;
            }
            string text = string.FastAllocateString(str.Length);
            fixed (string text2 = str)
            {
                char* ptr = text2;
                if (ptr != null)
                {
                    ptr += RuntimeHelpers.OffsetToStringData / 2;
                }
                fixed (string text3 = text)
                {
                    char* ptr2 = text3;
                    if (ptr2 != null)
                    {
                        ptr2 += RuntimeHelpers.OffsetToStringData / 2;
                    }
                    char* ptr3 = ptr2;
                    char* ptr4 = ptr;
                    for (int i = 0; i < str.Length; i++)
                    {
                        *ptr3 = this.ToLower(*ptr4);
                        ptr4++;
                        ptr3++;
                    }
                    text2 = null;
                }
                return text;
            }
        }
References System.text, and System.Globalization.TextInfo.ToLower().
Referenced by System.Globalization.TextInfo.ToLower(), and System.Globalization.TextInfo.ToLower().