Terraria Decompiled: System.Globalization.TextInfo.OnDeserialized
OnDeserialized() [1/2]
void System.Globalization.TextInfo.OnDeserialized () inline private
Definition at line 46 of file TextInfo.cs.
        {
            if (this.m_cultureData == null)
            {
                if (this.m_cultureName == null)
                {
                    if (this.customCultureName != null)
                    {
                        this.m_cultureName = this.customCultureName;
                    }
                    else if (this.m_win32LangID == 0)
                    {
                        this.m_cultureName = "ar-SA";
                    }
                    else
                    {
                        this.m_cultureName = CultureInfo.GetCultureInfo(this.m_win32LangID).m_cultureData.CultureName;
                    }
                }
                this.m_cultureData = CultureInfo.GetCultureInfo(this.m_cultureName).m_cultureData;
                this.m_textInfoName = this.m_cultureData.STEXTINFO;
            }
        }
References System.Globalization.CultureData.CultureName, System.Globalization.TextInfo.customCultureName, System.Globalization.CultureInfo.GetCultureInfo(), System.Globalization.CultureInfo.m_cultureData, System.Globalization.TextInfo.m_cultureData, System.Globalization.TextInfo.m_cultureName, System.Globalization.TextInfo.m_win32LangID, and System.Globalization.CultureData.STEXTINFO.
Referenced by System.Globalization.TextInfo.OnDeserialization(), and System.Globalization.TextInfo.OnDeserialized().