Terraria Decompiled: System.Security.SecurityManager.ResolveIdentityPermissions
ResolveIdentityPermissions()
static void System.Security.SecurityManager.ResolveIdentityPermissions (PermissionSet ps, Evidence evidence) inline static package
Definition at line 358 of file SecurityManager.cs.
        {
            if (ps.IsUnrestricted())
            {
                return;
            }
            IEnumerator hostEnumerator = evidence.GetHostEnumerator();
            while (hostEnumerator.MoveNext())
            {
                object obj = hostEnumerator.Current;
                IIdentityPermissionFactory identityPermissionFactory = obj as IIdentityPermissionFactory;
                if (identityPermissionFactory != null)
                {
                    IPermission permission = identityPermissionFactory.CreateIdentityPermission(evidence);
                    ps.AddPermission(permission);
                }
            }
        }
References System.Security.PermissionSet.AddPermission(), System.Security.Policy.IIdentityPermissionFactory.CreateIdentityPermission(), System.Collections.IEnumerator.Current, System.Security.Policy.Evidence.GetHostEnumerator(), System.Security.PermissionSet.IsUnrestricted(), System.Collections.IEnumerator.MoveNext(), and System.obj.
Referenced by System.Security.SecurityManager.ResolvePolicy(), and System.Security.SecurityManager.ResolveSystemPolicy().