Terraria Decompiled: System.Security.SecurityManager.ResolvePolicyLevel
ResolvePolicyLevel()
static bool System.Security.SecurityManager.ResolvePolicyLevel (ref PermissionSet ps, PolicyLevel pl, Evidence evidence) inline static package
Definition at line 332 of file SecurityManager.cs.
        {
            PolicyStatement policyStatement = pl.Resolve(evidence);
            if (policyStatement != null)
            {
                if (ps == null)
                {
                    ps = policyStatement.PermissionSet;
                }
                else
                {
                    ps = ps.Intersect(policyStatement.PermissionSet);
                    if (ps == null)
                    {
                        ps = new PermissionSet(PermissionState.None);
                    }
                }
                if ((policyStatement.Attributes & PolicyStatementAttribute.LevelFinal) == PolicyStatementAttribute.LevelFinal)
                {
                    return true;
                }
            }
            return false;
        }
References System.Security.Policy.PolicyStatement.Attributes, System.Security.PermissionSet.Intersect(), System.Security.Policy.PolicyStatement.PermissionSet, and System.Security.Policy.PolicyLevel.Resolve().
Referenced by System.Security.SecurityManager.ResolvePolicy(), and System.Security.SecurityManager.ResolveSystemPolicy().