Terraria Decompiled: System.Security.SecurityManager.IsGranted
IsGranted() [2/2]
static bool System.Security.SecurityManager.IsGranted (IPermission perm) inline static
Definition at line 74 of file SecurityManager.cs.
        {
            return perm == null || !SecurityManager.SecurityEnabled || SecurityManager.IsGranted(Assembly.GetCallingAssembly(), perm);
        }
References System.Reflection.Assembly.GetCallingAssembly(), and System.Security.SecurityManager.IsGranted().
Referenced by System.Security.PermissionSet.Assert(), and System.Security.SecurityManager.IsGranted().