Terraria Decompiled: System.Security.SecurityManager.ResolvePolicyGroups
ResolvePolicyGroups()
static IEnumerator System.Security.SecurityManager.ResolvePolicyGroups (Evidence evidence) inline static
Definition at line 257 of file SecurityManager.cs.
        {
            if (evidence == null)
            {
                throw new ArgumentNullException("evidence");
            }
            ArrayList arrayList = new ArrayList();
            IEnumerator hierarchy = SecurityManager.Hierarchy;
            while (hierarchy.MoveNext())
            {
                object obj = hierarchy.Current;
                CodeGroup codeGroup = ((PolicyLevel)obj).ResolveMatchingCodeGroups(evidence);
                arrayList.Add(codeGroup);
            }
            return arrayList.GetEnumerator();
        }
References System.Collections.ArrayList.Add(), System.Collections.IEnumerator.Current, System.Collections.ArrayList.GetEnumerator(), System.Security.SecurityManager.Hierarchy, System.Collections.IEnumerator.MoveNext(), System.obj, and System.Security.Policy.CodeGroup.ResolveMatchingCodeGroups().