Terraria Decompiled: System.Security.SecurityManager.IsGranted
IsGranted() [1/2]
static bool System.Security.SecurityManager.IsGranted (Assembly a, IPermission perm) inline static package
Definition at line 80 of file SecurityManager.cs.
        {
            PermissionSet grantedPermissionSet = a.GrantedPermissionSet;
            if (grantedPermissionSet != null && !grantedPermissionSet.IsUnrestricted())
            {
                CodeAccessPermission codeAccessPermission = (CodeAccessPermission)grantedPermissionSet.GetPermission(perm.GetType());
                if (!perm.IsSubsetOf(codeAccessPermission))
                {
                    return false;
                }
            }
            PermissionSet deniedPermissionSet = a.DeniedPermissionSet;
            if (deniedPermissionSet != null && !deniedPermissionSet.IsEmpty())
            {
                if (deniedPermissionSet.IsUnrestricted())
                {
                    return false;
                }
                CodeAccessPermission codeAccessPermission2 = (CodeAccessPermission)a.DeniedPermissionSet.GetPermission(perm.GetType());
                if (codeAccessPermission2 != null && perm.IsSubsetOf(codeAccessPermission2))
                {
                    return false;
                }
            }
            return true;
        }
References System.Reflection.Assembly.DeniedPermissionSet, System.Security.PermissionSet.GetPermission(), System.Reflection.Assembly.GrantedPermissionSet, System.Security.PermissionSet.IsEmpty(), System.Security.IPermission.IsSubsetOf(), and System.Security.PermissionSet.IsUnrestricted().