Terraria Decompiled: System.Security.SecurityManager.InitializePolicyHierarchy
InitializePolicyHierarchy()
static void System.Security.SecurityManager.InitializePolicyHierarchy () inline static private
Definition at line 314 of file SecurityManager.cs.
        {
            string directoryName = Path.GetDirectoryName(Environment.GetMachineConfigPath());
            string text = Path.Combine(Environment.UnixGetFolderPath(Environment.SpecialFolder.ApplicationData, Environment.SpecialFolderOption.Create), "mono");
            PolicyLevel policyLevel = new PolicyLevel("Enterprise", PolicyLevelType.Enterprise);
            SecurityManager._level = policyLevel;
            policyLevel.LoadFromFile(Path.Combine(directoryName, "enterprisesec.config"));
            PolicyLevel policyLevel2 = new PolicyLevel("Machine", PolicyLevelType.Machine);
            SecurityManager._level = policyLevel2;
            policyLevel2.LoadFromFile(Path.Combine(directoryName, "security.config"));
            PolicyLevel policyLevel3 = new PolicyLevel("User", PolicyLevelType.User);
            SecurityManager._level = policyLevel3;
            policyLevel3.LoadFromFile(Path.Combine(text, "security.config"));
            SecurityManager._hierarchy = ArrayList.Synchronized(new ArrayList { policyLevel, policyLevel2, policyLevel3 });
            SecurityManager._level = null;
        }
References System.IO.Path.Combine(), System.IO.Path.GetDirectoryName(), System.Security.Policy.PolicyLevel.LoadFromFile(), System.Collections.ArrayList.Synchronized(), and System.text.