Terraria Decompiled: System.Security.SecurityManager.ResolvePolicy
ResolvePolicy() [2/3]
static PermissionSet System.Security.SecurityManager.ResolvePolicy (Evidence evidence, PermissionSet reqdPset, PermissionSet optPset, PermissionSet denyPset, out PermissionSet denied) inline static
Definition at line 224 of file SecurityManager.cs.
        {
            PermissionSet permissionSet = SecurityManager.ResolvePolicy(evidence);
            if (reqdPset != null && !reqdPset.IsSubsetOf(permissionSet))
            {
                throw new PolicyException(Locale.GetText("Policy doesn't grant the minimal permissions required to execute the assembly."));
            }
            if (SecurityManager.CheckExecutionRights)
            {
                bool flag = false;
                if (permissionSet != null)
                {
                    if (permissionSet.IsUnrestricted())
                    {
                        flag = true;
                    }
                    else
                    {
                        IPermission permission = permissionSet.GetPermission(typeof(SecurityPermission));
                        flag = SecurityManager._execution.IsSubsetOf(permission);
                    }
                }
                if (!flag)
                {
                    throw new PolicyException(Locale.GetText("Policy doesn't grant the right to execute the assembly."));
                }
            }
            denied = denyPset;
            return permissionSet;
        }
References System.Security.SecurityManager._execution, System.Security.SecurityManager.CheckExecutionRights, System.Security.PermissionSet.GetPermission(), Locale.GetText(), System.Security.Permissions.SecurityPermission.IsSubsetOf(), System.Security.PermissionSet.IsSubsetOf(), System.Security.PermissionSet.IsUnrestricted(), and System.Security.SecurityManager.ResolvePolicy().