Terraria Decompiled: System.Security.SecurityManager.Decode
Decode() [2/2]
static PermissionSet System.Security.SecurityManager.Decode (IntPtr permissions, int length) inline static package
Definition at line 393 of file SecurityManager.cs.
        {
            PermissionSet permissionSet = null;
            object lockObject = SecurityManager._lockObject;
            lock (lockObject)
            {
                if (SecurityManager._declsecCache == null)
                {
                    SecurityManager._declsecCache = new Hashtable();
                }
                object obj = (int)permissions;
                permissionSet = (PermissionSet)SecurityManager._declsecCache[obj];
                if (permissionSet == null)
                {
                    byte[] array = new byte[length];
                    Marshal.Copy(permissions, array, 0, length);
                    permissionSet = SecurityManager.Decode(array);
                    permissionSet.DeclarativeSecurity = true;
                    SecurityManager._declsecCache.Add(obj, permissionSet);
                }
            }
            return permissionSet;
        }
References System.Security.SecurityManager._declsecCache, System.Security.SecurityManager._lockObject, System.Collections.Hashtable.Add(), System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Security.SecurityManager.Decode(), int, System.length, and System.obj.
Referenced by System.Security.SecurityManager.Decode(), and System.Reflection.RuntimeAssembly.LoadAssemblyPermissions().