Terraria Decompiled: Terraria.GameContent.Creative.CreativeUI.SacrificeItem
SacrificeItem() [2/2]
CreativeUI.ItemSacrificeResult Terraria.GameContent.Creative.CreativeUI.SacrificeItem (ref Item item, out int amountWeSacrificed, bool spawnExcessItem = true, bool onlySacrificeIfItWouldFinishResearch = false) inline
Definition at line 282 of file CreativeUI.cs.
        {
            int num = 0;
            int num2 = 0;
            amountWeSacrificed = 0;
            if (!Main.LocalPlayerCreativeTracker.ItemSacrifices.TryGetSacrificeNumbers(item.type, out num2, out num))
            {
                return CreativeUI.ItemSacrificeResult.CannotSacrifice;
            }
            int num3 = Utils.Clamp<int>(num - num2, 0, num);
            if (num3 == 0)
            {
                return CreativeUI.ItemSacrificeResult.CannotSacrifice;
            }
            int num4 = Math.Min(num3, item.stack);
            bool flag = num4 == num3;
            if (onlySacrificeIfItWouldFinishResearch && !flag)
            {
                return CreativeUI.ItemSacrificeResult.CannotSacrifice;
            }
            NetPacket netPacket = NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(Main.myPlayer, item.type, num4);
            NetManager.Instance.SendToServer(netPacket);
            if (!Main.ServerSideCharacter)
            {
                Main.LocalPlayerCreativeTracker.ItemSacrifices.RegisterItemSacrifice(item.type, num4, null);
            }
            item.stack -= num4;
            if (item.stack <= 0)
            {
                item.TurnToAir(false);
            }
            amountWeSacrificed = num4;
            if (item.stack > 0 && spawnExcessItem)
            {
                item = Main.LocalPlayer.GetItem(item, GetItemSettings.ReturnItemFromSlot);
            }
            if (!flag)
            {
                return CreativeUI.ItemSacrificeResult.SacrificedButNotDone;
            }
            return CreativeUI.ItemSacrificeResult.SacrificedAndDone;
        }
References Terraria.Utils.Clamp(), Terraria.Player.GetItem(), Terraria.Net.NetManager.Instance, System.item, Terraria.Main.LocalPlayer, Terraria.Main.LocalPlayerCreativeTracker, System.Math.Min(), Terraria.Main.myPlayer, Terraria.GetItemSettings.ReturnItemFromSlot, Terraria.Net.NetManager.SendToServer(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(), and Terraria.Main.ServerSideCharacter.