Terraria Decompiled: System.Runtime.Remoting.ConfigHandler.ParseElement
ParseElement()
void System.Runtime.Remoting.ConfigHandler.ParseElement (string name, SmallXmlParser::IAttrList attrs) inline
Definition at line 77 of file ConfigHandler.cs.
        {
            if (this.currentProviderData != null)
            {
                this.ReadCustomProviderData(name, attrs);
                return;
            }
            uint num = <PrivateImplementationDetails>.ComputeStringHash(name);
            if (num <= 1889220888U)
            {
                if (num <= 1338032792U)
                {
                    if (num <= 566383268U)
                    {
                        if (num != 524788293U)
{
                            if (num == 566383268U)
{
                                if (name == "channel")
{
                                    this.ValidatePath(name, new string[] { "channels" });
                                    if (this.currentXmlPath.IndexOf("application") != -1)
{
                                        this.ReadChannel(attrs, false);
                                        return;
                                    }
                                    this.ReadChannel(attrs, true);
                                    return;
                                }
                            }
                        }
                        else if (name == "application")
{
                            this.ValidatePath(name, new string[] { "system.runtime.remoting" });
                            if (attrs.Names.Length != 0)
{
                                this.appName = attrs.Values[0];
                                return;
                            }
                            return;
                        }
                    }
                    else if (num != 653843437U)
                    {
                        if (num == 1338032792U)
{
                            if (name == "wellknown")
{
                                this.ValidatePath(name, new string[] { "client", "service" });
                                if (this.CheckPath("client"))
{
                                    this.ReadClientWellKnown(attrs);
                                    return;
                                }
                                this.ReadServiceWellKnown(attrs);
                                return;
                            }
                        }
                    }
                    else if (name == "interopXmlElement")
                    {
                        this.ValidatePath(name, new string[] { "soapInterop" });
                        this.ReadInteropXml(attrs, false);
                        return;
                    }
                }
                else if (num <= 1457512036U)
                {
                    if (num != 1376955374U)
                    {
                        if (num == 1457512036U)
{
                            if (name == "service")
{
                                this.ValidatePath(name, new string[] { "application" });
                                return;
                            }
                        }
                    }
                    else if (name == "lifetime")
                    {
                        this.ValidatePath(name, new string[] { "application" });
                        this.ReadLifetine(attrs);
                        return;
                    }
                }
                else if (num != 1483009432U)
                {
                    if (num != 1743807633U)
                    {
                        if (num == 1889220888U)
{
                            if (name == "clientProviders")
{
                                this.ValidatePath(name, new string[] { "channelSinkProviders", "channel" });
                                return;
                            }
                        }
                    }
                    else if (name == "customErrors")
                    {
                        this.ValidatePath(name, new string[] { "system.runtime.remoting" });
                        RemotingConfiguration.SetCustomErrorsMode(attrs.GetValue("mode"));
                        return;
                    }
                }
                else if (name == "debug")
                {
                    this.ValidatePath(name, new string[] { "system.runtime.remoting" });
                    return;
                }
            }
            else if (num <= 3082861500U)
            {
                if (num <= 2837523493U)
                {
                    if (num != 2408750110U)
                    {
                        if (num != 2837523493U)
{
                            goto IL_05DF;
                        }
                        if (!(name == "formatter"))
{
                            goto IL_05DF;
                        }
                    }
                    else
                    {
                        if (!(name == "client"))
{
                            goto IL_05DF;
                        }
                        this.ValidatePath(name, new string[] { "application" });
                        this.currentClientUrl = attrs.GetValue("url");
                        return;
                    }
                }
                else if (num != 2866667388U)
                {
                    if (num != 2988283755U)
                    {
                        if (num != 3082861500U)
{
                            goto IL_05DF;
                        }
                        if (!(name == "provider"))
{
                            goto IL_05DF;
                        }
                    }
                    else
                    {
                        if (!(name == "soapInterop"))
{
                            goto IL_05DF;
                        }
                        this.ValidatePath(name, new string[] { "application" });
                        return;
                    }
                }
                else
                {
                    if (!(name == "activated"))
                    {
                        goto IL_05DF;
                    }
                    this.ValidatePath(name, new string[] { "client", "service" });
                    if (this.CheckPath("client"))
                    {
                        this.ReadClientActivated(attrs);
                        return;
                    }
                    this.ReadServiceActivated(attrs);
                    return;
                }
                if (this.CheckPath("application/channels/channel/serverProviders") || this.CheckPath("channels/channel/serverProviders"))
                {
                    ProviderData providerData = this.ReadProvider(name, attrs, false);
                    this.currentChannel.ServerProviders.Add(providerData);
                    return;
                }
                if (this.CheckPath("application/channels/channel/clientProviders") || this.CheckPath("channels/channel/clientProviders"))
                {
                    ProviderData providerData = this.ReadProvider(name, attrs, false);
                    this.currentChannel.ClientProviders.Add(providerData);
                    return;
                }
                if (this.CheckPath("channelSinkProviders/serverProviders"))
                {
                    ProviderData providerData = this.ReadProvider(name, attrs, true);
                    RemotingConfiguration.RegisterServerProviderTemplate(providerData);
                    return;
                }
                if (this.CheckPath("channelSinkProviders/clientProviders"))
                {
                    ProviderData providerData = this.ReadProvider(name, attrs, true);
                    RemotingConfiguration.RegisterClientProviderTemplate(providerData);
                    return;
                }
                this.ValidatePath(name, Array.Empty<string>());
                return;
            }
            else if (num <= 3638887060U)
            {
                if (num != 3588091843U)
                {
                    if (num == 3638887060U)
                    {
                        if (name == "serverProviders")
{
                            this.ValidatePath(name, new string[] { "channelSinkProviders", "channel" });
                            return;
                        }
                    }
                }
                else if (name == "interopXmlType")
                {
                    this.ValidatePath(name, new string[] { "soapInterop" });
                    this.ReadInteropXml(attrs, false);
                    return;
                }
            }
            else if (num != 4033672166U)
            {
                if (num != 4187488551U)
                {
                    if (num == 4226312309U)
                    {
                        if (name == "channels")
{
                            this.ValidatePath(name, new string[] { "system.runtime.remoting", "application" });
                            return;
                        }
                    }
                }
                else if (name == "channelSinkProviders")
                {
                    this.ValidatePath(name, new string[] { "system.runtime.remoting" });
                    return;
                }
            }
            else if (name == "preLoad")
            {
                this.ValidatePath(name, new string[] { "soapInterop" });
                this.ReadPreload(attrs);
                return;
            }
            IL_05DF:
            throw new RemotingException("Element '" + name + "' is not valid in system.remoting.configuration section");
        }
References System.Collections.ArrayList.Add(), System.Runtime.Remoting.ConfigHandler.CheckPath(), System.Runtime.Remoting.ChannelData.ClientProviders, System.Runtime.Remoting.ConfigHandler.currentChannel, System.Runtime.Remoting.ConfigHandler.currentProviderData, System.Runtime.Remoting.ConfigHandler.currentXmlPath, System.name, System.Runtime.Remoting.ConfigHandler.ReadChannel(), System.Runtime.Remoting.ConfigHandler.ReadClientActivated(), System.Runtime.Remoting.ConfigHandler.ReadClientWellKnown(), System.Runtime.Remoting.ConfigHandler.ReadCustomProviderData(), System.Runtime.Remoting.ConfigHandler.ReadInteropXml(), System.Runtime.Remoting.ConfigHandler.ReadLifetine(), System.Runtime.Remoting.ConfigHandler.ReadPreload(), System.Runtime.Remoting.ConfigHandler.ReadProvider(), System.Runtime.Remoting.ConfigHandler.ReadServiceActivated(), System.Runtime.Remoting.ConfigHandler.ReadServiceWellKnown(), System.Runtime.Remoting.RemotingConfiguration.RegisterClientProviderTemplate(), System.Runtime.Remoting.RemotingConfiguration.RegisterServerProviderTemplate(), System.Runtime.Remoting.ChannelData.ServerProviders, System.Runtime.Remoting.RemotingConfiguration.SetCustomErrorsMode(), System.U, and System.Runtime.Remoting.ConfigHandler.ValidatePath().
Referenced by System.Runtime.Remoting.ConfigHandler.OnStartElement().