Terraria Decompiled: System.Runtime.Remoting.ConfigHandler.ReadCustomProviderData
ReadCustomProviderData()
void System.Runtime.Remoting.ConfigHandler.ReadCustomProviderData (string name, SmallXmlParser::IAttrList attrs) inline private
Definition at line 344 of file ConfigHandler.cs.
        {
            SinkProviderData sinkProviderData = (SinkProviderData)this.currentProviderData.Peek();
            SinkProviderData sinkProviderData2 = new SinkProviderData(name);
            for (int i = 0; i < attrs.Names.Length; i++)
            {
                sinkProviderData2.Properties[attrs.Names[i]] = attrs.GetValue(i);
            }
            sinkProviderData.Children.Add(sinkProviderData2);
            this.currentProviderData.Push(sinkProviderData2);
        }
References System.Collections.IList.Add(), System.Runtime.Remoting.Channels.SinkProviderData.Children, System.Runtime.Remoting.ConfigHandler.currentProviderData, System.name, System.Collections.Stack.Peek(), System.Runtime.Remoting.Channels.SinkProviderData.Properties, and System.Collections.Stack.Push().
Referenced by System.Runtime.Remoting.ConfigHandler.ParseElement().