Terraria Decompiled: System.Runtime.Remoting.ConfigHandler.ReadProvider
ReadProvider()
ProviderData System.Runtime.Remoting.ConfigHandler.ReadProvider (string name, SmallXmlParser::IAttrList attrs, bool isTemplate) inline private
Definition at line 490 of file ConfigHandler.cs.
        {
            ProviderData providerData = ((name == "provider") ? new ProviderData() : new FormatterData());
            SinkProviderData sinkProviderData = new SinkProviderData("root");
            providerData.CustomData = sinkProviderData.Children;
            this.currentProviderData = new Stack();
            this.currentProviderData.Push(sinkProviderData);
            for (int i = 0; i < attrs.Names.Length; i++)
            {
                string text = attrs.Names[i];
                string text2 = attrs.Values[i];
                if (text == "id" && isTemplate)
                {
                    providerData.Id = text2;
                }
                else if (text == "type")
                {
                    providerData.Type = text2;
                }
                else if (text == "ref" && !isTemplate)
                {
                    providerData.Ref = text2;
                }
                else
                {
                    providerData.CustomProperties.Add(text, text2);
                }
            }
            if (providerData.Id == null && isTemplate)
            {
                throw new RemotingException("id attribute is required");
            }
            return providerData;
        }
References System.Collections.Hashtable.Add(), System.Runtime.Remoting.Channels.SinkProviderData.Children, System.Runtime.Remoting.ConfigHandler.currentProviderData, System.Runtime.Remoting.ProviderData.CustomProperties, System.Runtime.Remoting.ProviderData.Id, System.name, System.Collections.Stack.Push(), and System.text.
Referenced by System.Runtime.Remoting.ConfigHandler.ParseElement().