Terraria Decompiled: System.Runtime.Remoting.ConfigHandler.ReadPreload
ReadPreload()
void System.Runtime.Remoting.ConfigHandler.ReadPreload (SmallXmlParser::IAttrList attrs) inline private
Definition at line 593 of file ConfigHandler.cs.
        {
            string value = attrs.GetValue("type");
            string value2 = attrs.GetValue("assembly");
            if (value != null && value2 != null)
            {
                throw new RemotingException("Type and assembly attributes cannot be specified together");
            }
            if (value != null)
            {
                SoapServices.PreLoad(Type.GetType(value));
                return;
            }
            if (value2 != null)
            {
                SoapServices.PreLoad(Assembly.Load(value2));
                return;
            }
            throw new RemotingException("Either type or assembly attributes must be specified");
        }
References System.Type.GetType(), System.Reflection.Assembly.Load(), System.Runtime.Remoting.SoapServices.PreLoad(), and System.value.
Referenced by System.Runtime.Remoting.ConfigHandler.ParseElement().