Terraria Decompiled: System.Runtime.Remoting.ConfigHandler.ReadChannel
ReadChannel()
void System.Runtime.Remoting.ConfigHandler.ReadChannel (SmallXmlParser::IAttrList attrs, bool isTemplate) inline private
Definition at line 442 of file ConfigHandler.cs.
        {
            ChannelData channelData = new ChannelData();
            for (int i = 0; i < attrs.Names.Length; i++)
            {
                string text = attrs.Names[i];
                string text2 = attrs.Values[i];
                if (text == "ref" && !isTemplate)
                {
                    channelData.Ref = text2;
                }
                else if (text == "delayLoadAsClientChannel")
                {
                    channelData.DelayLoadAsClientChannel = text2;
                }
                else if (text == "id" && isTemplate)
                {
                    channelData.Id = text2;
                }
                else if (text == "type")
                {
                    channelData.Type = text2;
                }
                else
                {
                    channelData.CustomProperties.Add(text, text2);
                }
            }
            if (isTemplate)
            {
                if (channelData.Id == null)
                {
                    throw new RemotingException("id attribute is required");
                }
                if (channelData.Type == null)
                {
                    throw new RemotingException("id attribute is required");
                }
                RemotingConfiguration.RegisterChannelTemplate(channelData);
            }
            else
            {
                this.channelInstances.Add(channelData);
            }
            this.currentChannel = channelData;
        }
References System.Collections.Hashtable.Add(), System.Collections.ArrayList.Add(), System.Runtime.Remoting.ConfigHandler.channelInstances, System.Runtime.Remoting.ChannelData.CustomProperties, System.Runtime.Remoting.ChannelData.Id, System.Runtime.Remoting.RemotingConfiguration.RegisterChannelTemplate(), System.text, and System.Runtime.Remoting.ChannelData.Type.
Referenced by System.Runtime.Remoting.ConfigHandler.ParseElement().