Terraria Decompiled: System.Runtime.Remoting.ConfigHandler.ParseTime
ParseTime()
TimeSpan System.Runtime.Remoting.ConfigHandler.ParseTime (string s) inline private
Definition at line 392 of file ConfigHandler.cs.
        {
            if (s == "" || s == null)
            {
                throw new RemotingException("Invalid time value");
            }
            int num = s.IndexOfAny(new char[] { 'D', 'H', 'M', 'S' });
            string text;
            if (num == -1)
            {
                text = "S";
            }
            else
            {
                text = s.Substring(num);
                s = s.Substring(0, num);
            }
            double num2;
            try
            {
                num2 = double.Parse(s);
            }
            catch
            {
                throw new RemotingException("Invalid time value: " + s);
            }
            if (text == "D")
            {
                return TimeSpan.FromDays(num2);
            }
            if (text == "H")
            {
                return TimeSpan.FromHours(num2);
            }
            if (text == "M")
            {
                return TimeSpan.FromMinutes(num2);
            }
            if (text == "S")
            {
                return TimeSpan.FromSeconds(num2);
            }
            if (text == "MS")
            {
                return TimeSpan.FromMilliseconds(num2);
            }
            throw new RemotingException("Invalid time unit: " + text);
        }
References System.TimeSpan.FromDays(), System.TimeSpan.FromHours(), System.TimeSpan.FromMilliseconds(), System.TimeSpan.FromMinutes(), System.TimeSpan.FromSeconds(), System.s, and System.text.
Referenced by System.Runtime.Remoting.ConfigHandler.ReadLifetine().