Terraria Decompiled: Microsoft.Xna.Framework.Ray.Intersects
Intersects() [1/7]
float? Microsoft.Xna.Framework.Ray.Intersects (BoundingBox box) inline
Definition at line 58 of file Ray.cs.
        {
            float? num = null;
            float? num2 = null;
            float? num4;
            if (MathHelper.WithinEpsilon(this.Direction.X, 0f))
            {
                if (this.Position.X < box.Min.X || this.Position.X > box.Max.X)
                {
                    return null;
                }
            }
            else
            {
                num = new float?((box.Min.X - this.Position.X) / this.Direction.X);
                num2 = new float?((box.Max.X - this.Position.X) / this.Direction.X);
                float? num3 = num;
                num4 = num2;
                if ((num3.GetValueOrDefault() > num4.GetValueOrDefault()) & ((num3 != null) & (num4 != null)))
                {
                    float? num5 = num;
                    num = num2;
                    num2 = num5;
                }
            }
            float num9;
            if (!MathHelper.WithinEpsilon(this.Direction.Y, 0f))
            {
                float num6 = (box.Min.Y - this.Position.Y) / this.Direction.Y;
                float num7 = (box.Max.Y - this.Position.Y) / this.Direction.Y;
                if (num6 > num7)
                {
                    float num8 = num6;
                    num6 = num7;
                    num7 = num8;
                }
                if (num != null)
                {
                    num4 = num;
                    num9 = num7;
                    if ((num4.GetValueOrDefault() > num9) & (num4 != null))
                    {
                        goto IL_01D2;
                    }
                }
                if (num2 != null)
                {
                    float num10 = num6;
                    num4 = num2;
                    if ((num10 > num4.GetValueOrDefault()) & (num4 != null))
                    {
                        goto IL_01D2;
                    }
                }
                if (num != null)
                {
                    float num11 = num6;
                    num4 = num;
                    if (!((num11 > num4.GetValueOrDefault()) & (num4 != null)))
                    {
                        goto IL_0205;
                    }
                }
                num = new float?(num6);
                IL_0205:
                if (num2 != null)
                {
                    float num12 = num7;
                    num4 = num2;
                    if (!((num12 < num4.GetValueOrDefault()) & (num4 != null)))
                    {
                        goto IL_022E;
                    }
                }
                num2 = new float?(num7);
                goto IL_022E;
                IL_01D2:
                return null;
            }
            if (this.Position.Y < box.Min.Y || this.Position.Y > box.Max.Y)
            {
                return null;
            }
            IL_022E:
            if (!MathHelper.WithinEpsilon(this.Direction.Z, 0f))
            {
                float num13 = (box.Min.Z - this.Position.Z) / this.Direction.Z;
                float num14 = (box.Max.Z - this.Position.Z) / this.Direction.Z;
                if (num13 > num14)
                {
                    float num15 = num13;
                    num13 = num14;
                    num14 = num15;
                }
                if (num != null)
                {
                    num4 = num;
                    num9 = num14;
                    if ((num4.GetValueOrDefault() > num9) & (num4 != null))
                    {
                        goto IL_031E;
                    }
                }
                if (num2 != null)
                {
                    float num16 = num13;
                    num4 = num2;
                    if ((num16 > num4.GetValueOrDefault()) & (num4 != null))
                    {
                        goto IL_031E;
                    }
                }
                if (num != null)
                {
                    float num17 = num13;
                    num4 = num;
                    if (!((num17 > num4.GetValueOrDefault()) & (num4 != null)))
                    {
                        goto IL_0351;
                    }
                }
                num = new float?(num13);
                IL_0351:
                if (num2 != null)
                {
                    float num18 = num14;
                    num4 = num2;
                    if (!((num18 < num4.GetValueOrDefault()) & (num4 != null)))
                    {
                        goto IL_037A;
                    }
                }
                num2 = new float?(num14);
                goto IL_037A;
                IL_031E:
                return null;
            }
            if (this.Position.Z < box.Min.Z || this.Position.Z > box.Max.Z)
            {
                return null;
            }
            IL_037A:
            if (num != null)
            {
                num4 = num;
                num9 = 0f;
                if ((num4.GetValueOrDefault() < num9) & (num4 != null))
                {
                    num4 = num2;
                    num9 = 0f;
                    if ((num4.GetValueOrDefault() > num9) & (num4 != null))
                    {
                        return new float?(0f);
                    }
                }
            }
            num4 = num;
            num9 = 0f;
            if ((num4.GetValueOrDefault() < num9) & (num4 != null))
            {
                return null;
            }
            return num;
        }
References Microsoft.Xna.Framework.Ray.Direction, Microsoft.Xna.Framework.BoundingBox.Max, Microsoft.Xna.Framework.BoundingBox.Min, Microsoft.Xna.Framework.Ray.Position, Microsoft.Xna.Framework.MathHelper.WithinEpsilon(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.BoundingBox.Intersects(), and Microsoft.Xna.Framework.BoundingSphere.Intersects().