Terraria Decompiled: Microsoft.Xna.Framework.Ray.Intersects
Intersects() [6/7]
void Microsoft.Xna.Framework.Ray.Intersects (ref BoundingSphere sphere, out float? result) inline
Definition at line 279 of file Ray.cs.
        {
            Vector3 vector = sphere.Center - this.Position;
            float num = vector.LengthSquared();
            float num2 = sphere.Radius * sphere.Radius;
            if (num < num2)
            {
                result = new float?(0f);
                return;
            }
            float num3;
            Vector3.Dot(ref this.Direction, ref vector, out num3);
            if (num3 < 0f)
            {
                result = null;
                return;
            }
            float num4 = num2 + num3 * num3 - num;
            result = ((num4 < 0f) ? null : new float?(num3 - (float)Math.Sqrt((double)num4)));
        }
References Microsoft.Xna.Framework.Ray.Direction, Microsoft.Xna.Framework.Vector3.Dot(), Microsoft.Xna.Framework.Vector3.LengthSquared(), Microsoft.Xna.Framework.Ray.Position, and System.Math.Sqrt().