Terraria Decompiled: System.Reflection.Assembly.GetReferencedAssemblies
GetReferencedAssemblies() [2/2]
static unsafe AssemblyName[] System.Reflection.Assembly.GetReferencedAssemblies (Assembly module) inline static package
Definition at line 684 of file Assembly.cs.
        {
            AssemblyName[] array2;
            using (SafeGPtrArrayHandle safeGPtrArrayHandle = new SafeGPtrArrayHandle(Assembly.InternalGetReferencedAssemblies(module)))
            {
                int length = safeGPtrArrayHandle.Length;
                try
                {
                    AssemblyName[] array = new AssemblyName[length];
                    for (int i = 0; i < length; i++)
                    {
                        AssemblyName assemblyName = new AssemblyName();
                        MonoAssemblyName* ptr = (MonoAssemblyName*)(void*)safeGPtrArrayHandle[i];
                        assemblyName.FillName(ptr, null, true, false, true, true);
                        array[i] = assemblyName;
                    }
                    array2 = array;
                }
                finally
                {
                    for (int j = 0; j < length; j++)
                    {
                        MonoAssemblyName* ptr2 = (MonoAssemblyName*)(void*)safeGPtrArrayHandle[j];
                        RuntimeMarshal.FreeAssemblyName(ref *ptr2, true);
                    }
                }
            }
            return array2;
        }
References System.array, System.Reflection.AssemblyName.FillName(), Mono.RuntimeMarshal.FreeAssemblyName(), System.Reflection.Assembly.InternalGetReferencedAssemblies(), Mono.SafeGPtrArrayHandle.Length, and System.length.
Referenced by System.Reflection.Emit.AssemblyBuilder.GetReferencedAssemblies(), and System.Reflection.RuntimeAssembly.GetReferencedAssemblies().