Terraria Decompiled: System.Reflection.Assembly.InternalGetSatelliteAssembly
InternalGetSatelliteAssembly()
RuntimeAssembly System.Reflection.Assembly.InternalGetSatelliteAssembly (string name, CultureInfo culture, Version version, bool throwOnFileNotFound, ref StackCrawlMark stackMark) inline package
Definition at line 343 of file Assembly.cs.
        {
            AssemblyName assemblyName = new AssemblyName();
            assemblyName.SetPublicKey(this.GetPublicKey());
            assemblyName.Flags = this.GetFlags() | AssemblyNameFlags.PublicKey;
            if (version == null)
            {
                assemblyName.Version = this.GetVersion();
            }
            else
            {
                assemblyName.Version = version;
            }
            assemblyName.CultureInfo = culture;
            assemblyName.Name = name;
            try
            {
                Assembly assembly = AppDomain.CurrentDomain.LoadSatellite(assemblyName, false, ref stackMark);
                if (assembly != null)
                {
                    return (RuntimeAssembly)assembly;
                }
            }
            catch (FileNotFoundException)
            {
            }
            if (string.IsNullOrEmpty(this.Location))
            {
                return null;
            }
            string text = Path.Combine(Path.GetDirectoryName(this.Location), Path.Combine(culture.Name, assemblyName.Name + ".dll"));
            RuntimeAssembly runtimeAssembly;
            try
            {
                runtimeAssembly = (RuntimeAssembly)Assembly.LoadFrom(text, false, ref stackMark);
            }
            catch
            {
                if (throwOnFileNotFound || File.Exists(text))
                {
                    throw;
                }
                runtimeAssembly = null;
            }
            return runtimeAssembly;
        }
References System.IO.Path.Combine(), System.culture, System.AppDomain.CurrentDomain, System.IO.File.Exists(), System.IO.Path.GetDirectoryName(), System.Reflection.Assembly.GetFlags(), System.Reflection.Assembly.GetPublicKey(), System.Reflection.Assembly.GetVersion(), System.Reflection.Assembly.LoadFrom(), System.AppDomain.LoadSatellite(), System.Reflection.Assembly.Location, System.name, System.Reflection.AssemblyName.Name, System.Reflection.AssemblyName.SetPublicKey(), and System.text.
Referenced by System.Reflection.Assembly.GetSatelliteAssembly(), and System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly().