Terraria Decompiled: System.Reflection.Assembly.GetManifestResourceStream
GetManifestResourceStream() [4/4]
Stream System.Reflection.Assembly.GetManifestResourceStream (Type type, string name, bool skipSecurityCheck, ref StackCrawlMark stackMark) inline package
Definition at line 198 of file Assembly.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            if (type == null)
            {
                if (name == null)
                {
                    throw new ArgumentNullException("type");
                }
            }
            else
            {
                string @namespace = type.Namespace;
                if (@namespace != null)
                {
                    stringBuilder.Append(@namespace);
                    if (name != null)
                    {
                        stringBuilder.Append(Type.Delimiter);
                    }
                }
            }
            if (name != null)
            {
                stringBuilder.Append(name);
            }
            return this.GetManifestResourceStream(stringBuilder.ToString());
        }
References System.Text.StringBuilder.Append(), System.Type.Delimiter, System.Reflection.Assembly.GetManifestResourceStream(), System.name, and System.Text.StringBuilder.ToString().