Terraria Decompiled: Terraria.Social.WeGame.IPCClient.ReadCallback
ReadCallback()
override void Terraria.Social.WeGame.IPCClient.ReadCallback (IAsyncResult result) inline virtual
Reimplemented from Terraria.Social.WeGame.IPCBase.
Definition at line 129 of file IPCClient.cs.
        {
            IPCContent ipccontent = (IPCContent)result.AsyncState;
            base.ReadCallback(result);
            if (!ipccontent.CancelToken.IsCancellationRequested)
            {
                if (this.GetPipeStream().IsConnected)
                {
                    this.BeginReadData();
                    return;
                }
            }
            else
            {
                WeGameHelper.WriteDebugString("ReadCallback cancel", new object[0]);
            }
        }
References System.IAsyncResult.AsyncState, Terraria.Social.WeGame.IPCBase.BeginReadData(), Terraria.Social.WeGame.IPCContent.CancelToken, Terraria.Social.WeGame.IPCClient.GetPipeStream(), System.Threading.CancellationToken.IsCancellationRequested, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().