Terraria Decompiled: Terraria.GameContent.UI.States.UIDebugCommandsList.searchbar_OnSearchContentsChanged
searchbar_OnSearchContentsChanged()
void Terraria.GameContent.UI.States.UIDebugCommandsList.searchbar_OnSearchContentsChanged (string searchContents) inline private
Definition at line 88 of file UIDebugCommandsList.cs.
        {
            if (searchContents == null)
            {
                searchContents = string.Empty;
            }
            string text = searchContents.ToLowerInvariant().Trim();
            bool flag = string.IsNullOrWhiteSpace(text);
            this._commandsList.Clear();
            foreach (UIDebugCommandItem uidebugCommandItem in this._commands)
            {
                if (flag || UIDebugCommandsList.DoesCommandMatchSearch(text, uidebugCommandItem))
                {
                    this._commandsList.Add(uidebugCommandItem);
                }
            }
        }
References Terraria.GameContent.UI.States.UIDebugCommandsList._commands, Terraria.GameContent.UI.States.UIDebugCommandsList._commandsList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.GameContent.UI.States.UIDebugCommandsList.DoesCommandMatchSearch(), and System.text.
Referenced by Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage().