Terraria Decompiled: Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage
BuildPage()
void Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage () inline private
Definition at line 31 of file UIDebugCommandsList.cs.
        {
            base.RemoveAllChildren();
            UIElement uielement = new UIElement();
            uielement.Width.Set(0f, 0.8f);
            uielement.MaxWidth.Set(800f, 0f);
            uielement.MinWidth.Set(600f, 0f);
            uielement.Top.Set(220f, 0f);
            uielement.Height.Set(-220f, 1f);
            uielement.HAlign = 0.5f;
            base.Append(uielement);
            UIPanel uipanel = new UIPanel();
            uipanel.Width.Set(0f, 1f);
            uipanel.Height.Set(-110f, 1f);
            uipanel.BackgroundColor = new Color(33, 43, 79) * 0.95f;
            uielement.Append(uipanel);
            UIWrappedSearchBar uiwrappedSearchBar = new UIWrappedSearchBar(delegate
            {
                UserInterface.ActiveInstance.SetState(this);
            }, null, UIWrappedSearchBar.ColorTheme.Blue)
            {
                Width = new StyleDimension(200f, 0f),
                Top = new StyleDimension(20f, 0f)
            };
            uiwrappedSearchBar.OnSearchContentsChanged += this.searchbar_OnSearchContentsChanged;
            uipanel.Append(uiwrappedSearchBar);
            this._commandsList.Width.Set(-25f, 1f);
            this._commandsList.Height.Set(-60f, 1f);
            this._commandsList.VAlign = 1f;
            this._commandsList.ListPadding = 5f;
            uipanel.Append(this._commandsList);
            UITextPanel<string> uitextPanel = new UITextPanel<string>("Debug Commands", 1f, true);
            uitextPanel.HAlign = 0.5f;
            uitextPanel.Top.Set(-33f, 0f);
            uitextPanel.SetPadding(13f);
            uitextPanel.BackgroundColor = new Color(73, 94, 171);
            uielement.Append(uitextPanel);
            UITextPanel<LocalizedText> uitextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, true);
            uitextPanel2.Width.Set(-10f, 0.5f);
            uitextPanel2.Height.Set(50f, 0f);
            uitextPanel2.VAlign = 1f;
            uitextPanel2.HAlign = 0.5f;
            uitextPanel2.Top.Set(-45f, 0f);
            uitextPanel2.OnMouseOver += UIDebugCommandsList.FadedMouseOver;
            uitextPanel2.OnMouseOut += UIDebugCommandsList.FadedMouseOut;
            uitextPanel2.OnLeftClick += this.GoBackClick;
            uielement.Append(uitextPanel2);
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue);
            uiscrollbar.SetView(100f, 1000f);
            uiscrollbar.Height.Set(0f, 1f);
            uiscrollbar.HAlign = 1f;
            uipanel.Append(uiscrollbar);
            this._commandsList.SetScrollbar(uiscrollbar);
            this.PopulateCommandsList();
        }
References Terraria.GameContent.UI.States.UIDebugCommandsList._commandsList, Terraria.UI.UserInterface.ActiveInstance, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIDebugCommandsList.FadedMouseOut(), Terraria.GameContent.UI.States.UIDebugCommandsList.FadedMouseOver(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.UIDebugCommandsList.GoBackClick(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.MaxWidth, Terraria.UI.UIElement.MinWidth, Terraria.GameContent.UI.States.UIDebugCommandsList.PopulateCommandsList(), Terraria.GameContent.UI.States.UIDebugCommandsList.searchbar_OnSearchContentsChanged(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UserInterface.SetState(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIDebugCommandsList.UIDebugCommandsList().