Terraria Decompiled: Terraria.GameContent.UI.States.UIDebugCommandsList.PopulateCommandsList
PopulateCommandsList()
void Terraria.GameContent.UI.States.UIDebugCommandsList.PopulateCommandsList () inline private
Definition at line 135 of file UIDebugCommandsList.cs.
        {
            List<IDebugCommand> list = ChatManager.DebugCommands.Commands.ToList<IDebugCommand>();
            list.Sort((IDebugCommand x, IDebugCommand y) => StringComparer.OrdinalIgnoreCase.Compare(x.Name, y.Name));
            int num = 0;
            foreach (IDebugCommand debugCommand in list)
            {
                UIDebugCommandItem uidebugCommandItem = new UIDebugCommandItem(debugCommand, num++);
                this._commands.Add(uidebugCommandItem);
                this._commandsList.Add(uidebugCommandItem);
            }
        }
References Terraria.GameContent.UI.States.UIDebugCommandsList._commands, Terraria.GameContent.UI.States.UIDebugCommandsList._commandsList, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.Testing.ChatCommands.DebugCommandProcessor.Commands, System.StringComparer.Compare(), Terraria.UI.Chat.ChatManager.DebugCommands, System.list, Terraria.Testing.ChatCommands.IDebugCommand.Name, and System.StringComparer.OrdinalIgnoreCase.
Referenced by Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage().