Terraria Decompiled: System.IO.BufferedStream.d__38.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.BufferedStream.d__38.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1249 of file BufferedStream.cs.
            {
                int num2;
                int num = num2;
                BufferedStream bufferedStream = this;
                try
                {
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                    if (num != 0)
                    {
                        if (num - 1 <= 2)
{
                            goto IL_008C;
                        }
                        sem = bufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized();
                        configuredTaskAwaiter = sem.WaitAsync().ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num = (num2 = 0);
                            configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<FlushAsyncInternal>d__38>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num = (num2 = -1);
                    }
                    configuredTaskAwaiter.GetResult();
                    IL_008C:
                    try
                    {
                        switch (num)
{
                        case 1:
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                            break;
                        case 2:
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_01B2;
                        case 3:
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_0230;
                        default:
                            if (bufferedStream._writePos > 0)
{
                                configuredTaskAwaiter = bufferedStream.FlushWriteAsync(cancellationToken).ConfigureAwait(false).GetAwaiter();
                                if (!configuredTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 1);
                                    configuredTaskAwaiter2 = configuredTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<FlushAsyncInternal>d__38>(ref configuredTaskAwaiter, ref this);
                                    return;
                                }
                            }
                            else if (bufferedStream._readPos < bufferedStream._readLen)
{
                                if (bufferedStream._stream.CanSeek)
{
                                    bufferedStream.FlushRead();
                                }
                                if (!bufferedStream._stream.CanWrite)
{
                                    goto IL_01B9;
                                }
                                configuredTaskAwaiter = bufferedStream._stream.FlushAsync(cancellationToken).ConfigureAwait(false).GetAwaiter();
                                if (!configuredTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 2);
                                    configuredTaskAwaiter2 = configuredTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<FlushAsyncInternal>d__38>(ref configuredTaskAwaiter, ref this);
                                    return;
                                }
                                goto IL_01B2;
                            }
                            else
{
                                if (!bufferedStream._stream.CanWrite)
{
                                    goto IL_0237;
                                }
                                configuredTaskAwaiter = bufferedStream._stream.FlushAsync(cancellationToken).ConfigureAwait(false).GetAwaiter();
                                if (!configuredTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 3);
                                    configuredTaskAwaiter2 = configuredTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<FlushAsyncInternal>d__38>(ref configuredTaskAwaiter, ref this);
                                    return;
                                }
                                goto IL_0230;
                            }
                            break;
                        }
                        configuredTaskAwaiter.GetResult();
                        goto IL_026C;
                        IL_01B2:
                        configuredTaskAwaiter.GetResult();
                        IL_01B9:
                        goto IL_026C;
                        IL_0230:
                        configuredTaskAwaiter.GetResult();
                        IL_0237:;
                    }
                    finally
                    {
                        if (num < 0)
{
                            sem.Release();
                        }
                    }
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    sem = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_026C:
                num2 = -2;
                sem = null;
                this.<>t__builder.SetResult();
            }
References System.IO.BufferedStream._readLen, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.IO.Stream.CanSeek, System.IO.Stream.CanWrite, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.FlushAsync(), System.IO.BufferedStream.FlushAsyncInternal(), System.IO.BufferedStream.FlushRead(), System.IO.BufferedStream.FlushWriteAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, and System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized().