Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.FilterExtender
FilterExtender()
int Mono.Globalization.Unicode.SimpleCollator.FilterExtender (int i, SimpleCollator::ExtenderType ext, CompareOptions opt) inline private
Definition at line 387 of file SimpleCollator.cs.
        {
            if (ext == SimpleCollator.ExtenderType.Conditional && MSCompatUnicodeTable.HasSpecialWeight((char)i))
            {
                bool flag = SimpleCollator.IsHalfKana((int)((ushort)i), opt);
                bool flag2 = !MSCompatUnicodeTable.IsHiragana((char)i);
                switch (this.Level1(i) & 7)
                {
                case 2:
                    if (flag)
                    {
                        return 65393;
                    }
                    if (!flag2)
                    {
                        return 12354;
                    }
                    return 12450;
                case 3:
                    if (flag)
                    {
                        return 65394;
                    }
                    if (!flag2)
                    {
                        return 12356;
                    }
                    return 12452;
                case 4:
                    if (flag)
                    {
                        return 65395;
                    }
                    if (!flag2)
                    {
                        return 12358;
                    }
                    return 12454;
                case 5:
                    if (flag)
                    {
                        return 65396;
                    }
                    if (!flag2)
                    {
                        return 12360;
                    }
                    return 12456;
                case 6:
                    if (flag)
                    {
                        return 65397;
                    }
                    if (!flag2)
                    {
                        return 12362;
                    }
                    return 12458;
                }
            }
            return i;
        }
References Mono.Globalization.Unicode.MSCompatUnicodeTable.HasSpecialWeight(), Mono.Globalization.Unicode.SimpleCollator.IsHalfKana(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsHiragana(), and Mono.Globalization.Unicode.SimpleCollator.Level1().
Referenced by Mono.Globalization.Unicode.SimpleCollator.CompareInternal(), Mono.Globalization.Unicode.SimpleCollator.GetSortKey(), Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore(), and Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore().