Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.CompareInternal
CompareInternal()
unsafe int Mono.Globalization.Unicode.SimpleCollator.CompareInternal (string s1, int idx1, int len1, string s2, int idx2, int len2, out bool targetConsumed, out bool sourceConsumed, bool skipHeadingExtenders, bool immediateBreakup, ref SimpleCollator::Context ctx) inline private
Definition at line 657 of file SimpleCollator.cs.
        {
            CompareOptions option = ctx.Option;
            int num = idx1;
            int num2 = idx2;
            int num3 = idx1 + len1;
            int num4 = idx2 + len2;
            targetConsumed = false;
            sourceConsumed = false;
            SimpleCollator.PreviousInfo previousInfo = new SimpleCollator.PreviousInfo(false);
            int num5 = 0;
            int num6 = 5;
            int num7 = -1;
            int num8 = -1;
            int num9 = 0;
            int num10 = 0;
            if (skipHeadingExtenders)
            {
                while (idx1 < num3)
                {
                    if (this.GetExtenderType((int)s1[idx1]) == SimpleCollator.ExtenderType.None)
                    {
                        IL_0071:
                        while (idx2 < num4 && this.GetExtenderType((int)s2[idx2]) != SimpleCollator.ExtenderType.None)
{
                            idx2++;
                        }
                        goto IL_0077;
                    }
                    idx1++;
                }
                goto IL_0071;
            }
            IL_0077:
            SimpleCollator.ExtenderType extenderType = SimpleCollator.ExtenderType.None;
            SimpleCollator.ExtenderType extenderType2 = SimpleCollator.ExtenderType.None;
            int num11 = idx1;
            int num12 = idx2;
            bool flag = (option & CompareOptions.StringSort) > CompareOptions.None;
            bool flag2 = (option & CompareOptions.IgnoreNonSpace) > CompareOptions.None;
            SimpleCollator.Escape escape = default(SimpleCollator.Escape);
            SimpleCollator.Escape escape2 = default(SimpleCollator.Escape);
            int num20;
            for (;;)
            {
                if (idx1 < num3)
                {
                    if (SimpleCollator.IsIgnorable((int)s1[idx1], option))
                    {
                        idx1++;
                        continue;
                    }
                }
                while (idx2 < num4 && SimpleCollator.IsIgnorable((int)s2[idx2], option))
                {
                    idx2++;
                }
                if (idx1 >= num3)
                {
                    if (escape.Source == null)
                    {
                        goto IL_0882;
                    }
                    s1 = escape.Source;
                    num = escape.Start;
                    idx1 = escape.Index;
                    num3 = escape.End;
                    num11 = escape.Optional;
                    escape.Source = null;
                }
                else if (idx2 >= num4)
                {
                    if (escape2.Source == null)
                    {
                        goto IL_0882;
                    }
                    s2 = escape2.Source;
                    num2 = escape2.Start;
                    idx2 = escape2.Index;
                    num4 = escape2.End;
                    num12 = escape2.Optional;
                    escape2.Source = null;
                }
                else
                {
                    if (num11 < idx1 && num12 < idx2)
                    {
                        while (idx1 < num3 && idx2 < num4 && s1[idx1] == s2[idx2])
{
                            idx1++;
                            idx2++;
                        }
                        if (idx1 != num3 && idx2 != num4)
{
                            int num13 = num11;
                            int num14 = num12;
                            num11 = idx1;
                            num12 = idx2;
                            idx1--;
                            idx2--;
                            while (idx1 > num13)
{
                                if (this.Category((int)s1[idx1]) != 1)
{
                                    IL_020B:
                                    while (idx2 > num14)
{
                                        if (this.Category((int)s2[idx2]) != 1)
{
                                            IL_0227:
                                            while (idx1 > num13)
{
                                                if (this.IsSafe((int)s1[idx1]))
{
                                                    IL_0245:
                                                    while (idx2 > num14 && !this.IsSafe((int)s2[idx2]))
{
                                                        idx2--;
                                                    }
                                                    goto IL_024B;
                                                }
                                                idx1--;
                                            }
                                            goto IL_0245;
                                        }
                                        idx2--;
                                    }
                                    goto IL_0227;
                                }
                                idx1--;
                            }
                            goto IL_020B;
                        }
                        continue;
                    }
                    IL_024B:
                    int num15 = idx1;
                    int num16 = idx2;
                    byte* ptr = null;
                    byte* ptr2 = null;
                    int num17 = this.FilterOptions((int)s1[idx1], option);
                    int num18 = this.FilterOptions((int)s2[idx2], option);
                    bool flag3 = false;
                    bool flag4 = false;
                    extenderType = this.GetExtenderType(num17);
                    if (extenderType != SimpleCollator.ExtenderType.None)
                    {
                        if (ctx.PrevCode < 0)
{
                            if (ctx.PrevSortKey == null)
{
                                idx1++;
                                continue;
                            }
                            ptr = ctx.PrevSortKey;
                        }
                        else
{
                            num17 = this.FilterExtender(ctx.PrevCode, extenderType, option);
                        }
                    }
                    extenderType2 = this.GetExtenderType(num18);
                    if (extenderType2 != SimpleCollator.ExtenderType.None)
                    {
                        if (previousInfo.Code < 0)
{
                            if (previousInfo.SortKey == null)
{
                                idx2++;
                                continue;
                            }
                            ptr2 = previousInfo.SortKey;
                        }
                        else
{
                            num18 = this.FilterExtender(previousInfo.Code, extenderType2, option);
                        }
                    }
                    byte b = this.Category(num17);
                    byte b2 = this.Category(num18);
                    if (b == 6)
                    {
                        if (!flag && num6 == 5)
{
                            num7 = ((escape.Source != null) ? (escape.Index - escape.Start) : (num15 - num));
                            num9 = (int)this.Level1(num17) << (int)(8 + MSCompatUnicodeTable.Level3(num17));
                        }
                        ctx.PrevCode = num17;
                        idx1++;
                    }
                    if (b2 == 6)
                    {
                        if (!flag && num6 == 5)
{
                            num8 = ((escape2.Source != null) ? (escape2.Index - escape2.Start) : (num16 - num2));
                            num10 = (int)this.Level1(num18) << (int)(8 + MSCompatUnicodeTable.Level3(num18));
                        }
                        previousInfo.Code = num18;
                        idx2++;
                    }
                    if (b == 6 || b2 == 6)
                    {
                        if (num6 == 5)
{
                            if (num9 == num10)
{
                                num8 = (num7 = -1);
                                num10 = (num9 = 0);
                            }
                            else
{
                                num6 = 4;
                            }
                        }
                    }
                    else
                    {
                        Contraction contraction = null;
                        if (extenderType == SimpleCollator.ExtenderType.None)
{
                            contraction = this.GetContraction(s1, idx1, num3);
                        }
                        int num19 = 1;
                        if (ptr != null)
{
                            num19 = 1;
                        }
                        else if (contraction != null)
{
                            num19 = contraction.Source.Length;
                            if (contraction.SortKey != null)
{
                                ptr = ctx.Buffer1;
                                for (int i = 0; i < contraction.SortKey.Length; i++)
{
                                    ptr[i] = contraction.SortKey[i];
                                }
                                ctx.PrevCode = -1;
                                ctx.PrevSortKey = ptr;
                            }
                            else if (escape.Source == null)
{
                                escape.Source = s1;
                                escape.Start = num;
                                escape.Index = num15 + contraction.Source.Length;
                                escape.End = num3;
                                escape.Optional = num11;
                                s1 = contraction.Replacement;
                                idx1 = 0;
                                num = 0;
                                num3 = s1.Length;
                                num11 = 0;
                                continue;
                            }
                        }
                        else
{
                            ptr = ctx.Buffer1;
                            *ptr = b;
                            ptr[1] = this.Level1(num17);
                            if (!flag2 && num6 > 1)
{
                                ptr[2] = this.Level2(num17, extenderType);
                            }
                            if (num6 > 2)
{
                                ptr[3] = MSCompatUnicodeTable.Level3(num17);
                            }
                            if (num6 > 3)
{
                                flag3 = MSCompatUnicodeTable.HasSpecialWeight((char)num17);
                            }
                            if (b > 1)
{
                                ctx.PrevCode = num17;
                            }
                        }
                        Contraction contraction2 = null;
                        if (extenderType2 == SimpleCollator.ExtenderType.None)
{
                            contraction2 = this.GetContraction(s2, idx2, num4);
                        }
                        if (ptr2 != null)
{
                            idx2++;
                        }
                        else if (contraction2 != null)
{
                            idx2 += contraction2.Source.Length;
                            if (contraction2.SortKey != null)
{
                                ptr2 = ctx.Buffer2;
                                for (int j = 0; j < contraction2.SortKey.Length; j++)
{
                                    ptr2[j] = contraction2.SortKey[j];
                                }
                                previousInfo.Code = -1;
                                previousInfo.SortKey = ptr2;
                            }
                            else if (escape2.Source == null)
{
                                escape2.Source = s2;
                                escape2.Start = num2;
                                escape2.Index = num16 + contraction2.Source.Length;
                                escape2.End = num4;
                                escape2.Optional = num12;
                                s2 = contraction2.Replacement;
                                idx2 = 0;
                                num2 = 0;
                                num4 = s2.Length;
                                num12 = 0;
                                continue;
                            }
                        }
                        else
{
                            ptr2 = ctx.Buffer2;
                            *ptr2 = b2;
                            ptr2[1] = this.Level1(num18);
                            if (!flag2 && num6 > 1)
{
                                ptr2[2] = this.Level2(num18, extenderType2);
                            }
                            if (num6 > 2)
{
                                ptr2[3] = MSCompatUnicodeTable.Level3(num18);
                            }
                            if (num6 > 3)
{
                                flag4 = MSCompatUnicodeTable.HasSpecialWeight((char)num18);
                            }
                            if (b2 > 1)
{
                                previousInfo.Code = num18;
                            }
                            idx2++;
                        }
                        idx1 += num19;
                        if (!flag2)
{
                            while (idx1 < num3)
{
                                if (this.Category((int)s1[idx1]) != 1)
{
                                    IL_072B:
                                    while (idx2 < num4 && this.Category((int)s2[idx2]) == 1)
{
                                        if (ptr2[2] == 0)
{
                                            ptr2[2] = 2;
                                        }
                                        ptr2[2] = ptr2[2] + this.Level2((int)s2[idx2], SimpleCollator.ExtenderType.None);
                                        idx2++;
                                    }
                                    goto IL_0731;
                                }
                                if (ptr[2] == 0)
{
                                    ptr[2] = 2;
                                }
                                ptr[2] = ptr[2] + this.Level2((int)s1[idx1], SimpleCollator.ExtenderType.None);
                                idx1++;
                            }
                            goto IL_072B;
                        }
                        IL_0731:
                        num20 = (int)(*ptr - *ptr2);
                        num20 = ((num20 != 0) ? num20 : ((int)(ptr[1] - ptr2[1])));
                        if (num20 != 0)
{
                            break;
                        }
                        if (num6 != 1)
{
                            if (!flag2)
{
                                num20 = (int)(ptr[2] - ptr2[2]);
                                if (num20 != 0)
{
                                    num5 = num20;
                                    if (immediateBreakup)
{
                                        return -1;
                                    }
                                    num6 = (this.frenchSort ? 2 : 1);
                                    continue;
                                }
                            }
                            if (num6 != 2)
{
                                num20 = (int)(ptr[3] - ptr2[3]);
                                if (num20 != 0)
{
                                    num5 = num20;
                                    if (immediateBreakup)
{
                                        return -1;
                                    }
                                    num6 = 2;
                                }
                                else if (num6 != 3)
{
                                    if (flag3 != flag4)
{
                                        if (immediateBreakup)
{
                                            return -1;
                                        }
                                        num5 = (flag3 ? 1 : (-1));
                                        num6 = 3;
                                    }
                                    else if (flag3)
{
                                        num20 = this.CompareFlagPair(!MSCompatUnicodeTable.IsJapaneseSmallLetter((char)num17), !MSCompatUnicodeTable.IsJapaneseSmallLetter((char)num18));
                                        num20 = ((num20 != 0) ? num20 : ((int)(SimpleCollator.ToDashTypeValue(extenderType, option) - SimpleCollator.ToDashTypeValue(extenderType2, option))));
                                        num20 = ((num20 != 0) ? num20 : this.CompareFlagPair(MSCompatUnicodeTable.IsHiragana((char)num17), MSCompatUnicodeTable.IsHiragana((char)num18)));
                                        num20 = ((num20 != 0) ? num20 : this.CompareFlagPair(!SimpleCollator.IsHalfKana((int)((ushort)num17), option), !SimpleCollator.IsHalfKana((int)((ushort)num18), option)));
                                        if (num20 != 0)
{
                                            if (immediateBreakup)
{
                                                return -1;
                                            }
                                            num5 = num20;
                                            num6 = 3;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            return num20;
            IL_0882:
            if (!flag2 && num5 != 0 && num6 > 2)
            {
                while (idx1 < num3 && idx2 < num4 && MSCompatUnicodeTable.IsIgnorableNonSpacing((int)s1[idx1]) && MSCompatUnicodeTable.IsIgnorableNonSpacing((int)s2[idx2]))
                {
                    num5 = (int)(this.Level2(this.FilterOptions((int)s1[idx1], option), extenderType) - this.Level2(this.FilterOptions((int)s2[idx2], option), extenderType2));
                    if (num5 != 0)
                    {
                        break;
                    }
                    idx1++;
                    idx2++;
                    extenderType = SimpleCollator.ExtenderType.None;
                    extenderType2 = SimpleCollator.ExtenderType.None;
                }
            }
            if (num6 == 1 && num5 != 0)
            {
                while (idx1 < num3)
                {
                    if (!MSCompatUnicodeTable.IsIgnorableNonSpacing((int)s1[idx1]))
                    {
                        IL_0939:
                        while (idx2 < num4 && MSCompatUnicodeTable.IsIgnorableNonSpacing((int)s2[idx2]))
{
                            idx2++;
                        }
                        goto IL_093F;
                    }
                    idx1++;
                }
                goto IL_0939;
            }
            IL_093F:
            if (num5 == 0)
            {
                if (num7 < 0 && num8 >= 0)
                {
                    num5 = -1;
                }
                else if (num8 < 0 && num7 >= 0)
                {
                    num5 = 1;
                }
                else
                {
                    num5 = num7 - num8;
                    if (num5 == 0)
                    {
                        num5 = num9 - num10;
                    }
                }
            }
            if (num5 == 0)
            {
                if (idx2 == num4)
                {
                    targetConsumed = true;
                }
                if (idx1 == num3)
                {
                    sourceConsumed = true;
                }
            }
            if (idx1 != num3)
            {
                return 1;
            }
            if (idx2 != num4)
            {
                return -1;
            }
            return num5;
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.PreviousInfo.Code, Mono.Globalization.Unicode.SimpleCollator.CompareFlagPair(), Mono.Globalization.Unicode.SimpleCollator.Escape.End, Mono.Globalization.Unicode.SimpleCollator.FilterExtender(), Mono.Globalization.Unicode.SimpleCollator.FilterOptions(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.SimpleCollator.GetExtenderType(), Mono.Globalization.Unicode.MSCompatUnicodeTable.HasSpecialWeight(), Mono.Globalization.Unicode.SimpleCollator.Escape.Index, int, Mono.Globalization.Unicode.SimpleCollator.IsHalfKana(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsHiragana(), Mono.Globalization.Unicode.SimpleCollator.IsIgnorable(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsIgnorableNonSpacing(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsJapaneseSmallLetter(), Mono.Globalization.Unicode.SimpleCollator.IsSafe(), Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), Mono.Globalization.Unicode.SimpleCollator.Escape.Optional, Mono.Globalization.Unicode.Contraction.Replacement, Mono.Globalization.Unicode.Contraction.SortKey, Mono.Globalization.Unicode.SimpleCollator.PreviousInfo.SortKey, Mono.Globalization.Unicode.Contraction.Source, Mono.Globalization.Unicode.SimpleCollator.Escape.Source, Mono.Globalization.Unicode.SimpleCollator.Escape.Start, and Mono.Globalization.Unicode.SimpleCollator.ToDashTypeValue().
Referenced by Mono.Globalization.Unicode.SimpleCollator.Compare(), and Mono.Globalization.Unicode.SimpleCollator.IsPrefix().