Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.IsIgnorable
IsIgnorable()
static bool Mono.Globalization.Unicode.SimpleCollator.IsIgnorable (int i, CompareOptions opt) inline static private
Definition at line 451 of file SimpleCollator.cs.
        {
            return MSCompatUnicodeTable.IsIgnorable(i, (byte)((((opt & (CompareOptions.OrdinalIgnoreCase | CompareOptions.Ordinal)) == CompareOptions.None) ? 1 : 0) + (((opt & CompareOptions.IgnoreSymbols) != CompareOptions.None) ? 2 : 0) + (((opt & CompareOptions.IgnoreNonSpace) != CompareOptions.None) ? 4 : 0)));
        }
References Mono.Globalization.Unicode.MSCompatUnicodeTable.IsIgnorable().
Referenced by Mono.Globalization.Unicode.SimpleCollator.CompareInternal(), Mono.Globalization.Unicode.SimpleCollator.GetSortKey(), Mono.Globalization.Unicode.SimpleCollator.IndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), and Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore().