Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.GetContraction
GetContraction() [3/4]
Contraction Mono.Globalization.Unicode.SimpleCollator.GetContraction (string s, int start, int end) inline private
Definition at line 156 of file SimpleCollator.cs.
        {
            Contraction contraction = this.GetContraction(s, start, end, this.contractions);
            if (contraction != null || this.lcid == 127)
            {
                return contraction;
            }
            return this.GetContraction(s, start, end, SimpleCollator.invariant.contractions);
        }
References Mono.Globalization.Unicode.SimpleCollator.contractions, Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.SimpleCollator.invariant, Mono.Globalization.Unicode.SimpleCollator.lcid, and System.start.
Referenced by Mono.Globalization.Unicode.SimpleCollator.CompareInternal(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.SimpleCollator.GetSortKey(), Mono.Globalization.Unicode.SimpleCollator.IndexOf(), Mono.Globalization.Unicode.SimpleCollator.IndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), and Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore().