Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore
MatchesBackwardCore()
unsafe bool Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore (string s, ref int idx, int end, int orgStart, int ti, byte * sortkey, bool noLv4, SimpleCollator::ExtenderType ext, ref Contraction ct, ref SimpleCollator::Context ctx) inline private
Definition at line 1942 of file SimpleCollator.cs.
        {
            CompareOptions option = ctx.Option;
            byte* buffer = ctx.Buffer1;
            bool flag = (option & CompareOptions.IgnoreNonSpace) > CompareOptions.None;
            int num = idx;
            int num2 = -1;
            if (ext != SimpleCollator.ExtenderType.None)
            {
                byte b = 0;
                for (int i = idx; i >= 0; i--)
                {
                    if (!SimpleCollator.IsIgnorable((int)s[i], option))
                    {
                        int num3 = this.FilterOptions((int)s[i], option);
                        byte b2 = this.Category(num3);
                        if (b2 != 1)
{
                            num2 = this.FilterExtender(num3, ext, option);
                            *buffer = b2;
                            buffer[1] = this.Level1(num2);
                            if (!flag)
{
                                buffer[2] = this.Level2(num2, ext);
                            }
                            buffer[3] = MSCompatUnicodeTable.Level3(num2);
                            if (ext != SimpleCollator.ExtenderType.Conditional && b != 0)
{
                                buffer[2] = ((buffer[2] == 0) ? (b + 2) : b);
                            }
                            idx--;
                            goto IL_00DA;
                        }
                        b = this.Level2(num3, SimpleCollator.ExtenderType.None);
                    }
                }
                return false;
            }
            IL_00DA:
            if (ext == SimpleCollator.ExtenderType.None)
            {
                ct = this.GetTailContraction(s, idx, end);
            }
            if (ct != null)
            {
                idx -= ct.Source.Length;
                if (!noLv4)
                {
                    return false;
                }
                if (ct.SortKey == null)
                {
                    int num4 = ct.Replacement.Length - 1;
                    return 0 <= this.LastIndexOfSortKey(ct.Replacement, num4, num4, ct.Replacement.Length, sortkey, ti, noLv4, ref ctx);
                }
                for (int j = 0; j < 4; j++)
                {
                    buffer[j] = sortkey[j];
                }
                ctx.PrevCode = -1;
                ctx.PrevSortKey = buffer;
            }
            else if (ext == SimpleCollator.ExtenderType.None)
            {
                if (num2 < 0)
                {
                    num2 = this.FilterOptions((int)s[idx], option);
                }
                idx--;
                bool flag2 = false;
                *buffer = this.Category(num2);
                if (*buffer == *sortkey)
                {
                    buffer[1] = this.Level1(num2);
                }
                else
                {
                    flag2 = true;
                }
                if (!flag && buffer[1] == sortkey[1])
                {
                    buffer[2] = this.Level2(num2, ext);
                }
                else if (!flag)
                {
                    flag2 = true;
                }
                if (flag2)
                {
                    return false;
                }
                buffer[3] = MSCompatUnicodeTable.Level3(num2);
                if (*buffer != 1)
                {
                    ctx.PrevCode = num2;
                }
            }
            if (ext == SimpleCollator.ExtenderType.None)
            {
                int num5 = num + 1;
                while (num5 < orgStart && this.Category((int)s[num5]) == 1)
                {
                    if (!flag)
                    {
                        if (buffer[2] == 0)
{
                            buffer[2] = 2;
                        }
                        buffer[2] = buffer[2] + this.Level2((int)s[num5], SimpleCollator.ExtenderType.None);
                    }
                    num5++;
                }
            }
            return this.MatchesPrimitive(option, buffer, num2, ext, sortkey, ti, noLv4);
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.FilterExtender(), Mono.Globalization.Unicode.SimpleCollator.FilterOptions(), Mono.Globalization.Unicode.SimpleCollator.GetTailContraction(), Mono.Globalization.Unicode.SimpleCollator.IsIgnorable(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOfSortKey(), Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), Mono.Globalization.Unicode.SimpleCollator.MatchesPrimitive(), and System.s.
Referenced by Mono.Globalization.Unicode.SimpleCollator.MatchesBackward().