Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.IndexOf
IndexOf() [4/5]
unsafe int Mono.Globalization.Unicode.SimpleCollator.IndexOf (string s, string target, int start, int length, byte * targetSortKey, ref SimpleCollator::Context ctx) inline private
Definition at line 1436 of file SimpleCollator.cs.
        {
            CompareOptions option = ctx.Option;
            int num = 0;
            while (num < target.Length && SimpleCollator.IsIgnorable((int)target[num], option))
            {
                num++;
            }
            if (num != target.Length)
            {
                Contraction contraction = this.GetContraction(target, num, target.Length - num);
                string text = ((contraction != null) ? contraction.Replacement : null);
                byte* ptr = ((text == null) ? targetSortKey : null);
                bool flag = true;
                char c = '\0';
                int num2 = -1;
                if (contraction != null && ptr != null)
                {
                    for (int i = 0; i < contraction.SortKey.Length; i++)
                    {
                        ptr[i] = contraction.SortKey[i];
                    }
                }
                else if (ptr != null)
                {
                    c = target[num];
                    num2 = this.FilterOptions((int)target[num], option);
                    *ptr = this.Category(num2);
                    ptr[1] = this.Level1(num2);
                    if ((option & CompareOptions.IgnoreNonSpace) == CompareOptions.None)
                    {
                        ptr[2] = this.Level2(num2, SimpleCollator.ExtenderType.None);
                    }
                    ptr[3] = MSCompatUnicodeTable.Level3(num2);
                    flag = !MSCompatUnicodeTable.HasSpecialWeight((char)num2);
                }
                if (ptr != null)
                {
                    num++;
                    while (num < target.Length && this.Category((int)target[num]) == 1)
                    {
                        if (ptr[2] == 0)
{
                            ptr[2] = 2;
                        }
                        ptr[2] = ptr[2] + this.Level2((int)target[num], SimpleCollator.ExtenderType.None);
                        num++;
                    }
                }
                for (;;)
                {
                    int num3;
                    if (text != null)
                    {
                        num3 = this.IndexOf(s, text, start, length, targetSortKey, ref ctx);
                    }
                    else
                    {
                        num3 = this.IndexOfSortKey(s, start, length, ptr, c, num2, flag, ref ctx);
                    }
                    if (num3 < 0)
                    {
                        break;
                    }
                    length -= num3 - start;
                    start = num3;
                    if (this.IsPrefix(s, target, start, length, false, ref ctx))
                    {
                        return num3;
                    }
                    Contraction contraction2 = this.GetContraction(s, start, length);
                    if (contraction2 != null)
                    {
                        start += contraction2.Source.Length;
                        length -= contraction2.Source.Length;
                    }
                    else
                    {
                        start++;
                        length--;
                    }
                    if (length <= 0)
                    {
                        return -1;
                    }
                }
                return -1;
            }
            if (this.IndexOfOrdinal(target, '\0', 0, target.Length) < 0)
            {
                return start;
            }
            return this.IndexOfOrdinal(s, target, start, length);
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.FilterOptions(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.MSCompatUnicodeTable.HasSpecialWeight(), Mono.Globalization.Unicode.SimpleCollator.IndexOf(), Mono.Globalization.Unicode.SimpleCollator.IndexOfOrdinal(), Mono.Globalization.Unicode.SimpleCollator.IndexOfSortKey(), Mono.Globalization.Unicode.SimpleCollator.IsIgnorable(), Mono.Globalization.Unicode.SimpleCollator.IsPrefix(), System.length, Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), Mono.Globalization.Unicode.Contraction.Replacement, Mono.Globalization.Unicode.Contraction.SortKey, Mono.Globalization.Unicode.Contraction.Source, System.start, and System.text.