Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.MatchesBackward
MatchesBackward()
unsafe bool Mono.Globalization.Unicode.SimpleCollator.MatchesBackward (string s, ref int idx, int end, int orgStart, int ti, byte * sortkey, bool noLv4, ref SimpleCollator::Context ctx) inline private
Definition at line 1910 of file SimpleCollator.cs.
        {
            int num = (int)s[idx];
            if (ctx.AlwaysMatchFlags != null && num < 128 && ((int)ctx.AlwaysMatchFlags[num / 8] & (1 << num % 8)) != 0)
            {
                return true;
            }
            if (ctx.NeverMatchFlags != null && num < 128 && ((int)ctx.NeverMatchFlags[num / 8] & (1 << num % 8)) != 0)
            {
                idx--;
                return false;
            }
            SimpleCollator.ExtenderType extenderType = this.GetExtenderType((int)s[idx]);
            Contraction contraction = null;
            if (this.MatchesBackwardCore(s, ref idx, end, orgStart, ti, sortkey, noLv4, extenderType, ref contraction, ref ctx))
            {
                if (ctx.AlwaysMatchFlags != null && contraction == null && extenderType == SimpleCollator.ExtenderType.None && num < 128)
                {
                    byte* ptr = ctx.AlwaysMatchFlags + num / 8;
                    *ptr |= (byte)(1 << num % 8);
                }
                return true;
            }
            if (ctx.NeverMatchFlags != null && contraction == null && extenderType == SimpleCollator.ExtenderType.None && num < 128)
            {
                byte* ptr2 = ctx.NeverMatchFlags + num / 8;
                *ptr2 |= (byte)(1 << num % 8);
            }
            return false;
        }
References Mono.Globalization.Unicode.SimpleCollator.GetExtenderType(), int, Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore(), and System.s.
Referenced by Mono.Globalization.Unicode.SimpleCollator.LastIndexOfSortKey().