Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.LastIndexOf
LastIndexOf() [4/5]
unsafe int Mono.Globalization.Unicode.SimpleCollator.LastIndexOf (string s, string target, int start, int length, byte * targetSortKey, ref SimpleCollator::Context ctx) inline private
Definition at line 1673 of file SimpleCollator.cs.
        {
            CompareOptions option = ctx.Option;
            int num = start;
            int num2 = 0;
            while (num2 < target.Length && SimpleCollator.IsIgnorable((int)target[num2], option))
            {
                num2++;
            }
            if (num2 != target.Length)
            {
                Contraction contraction = this.GetContraction(target, num2, target.Length - num2);
                string text = ((contraction != null) ? contraction.Replacement : null);
                byte* ptr = ((text == null) ? targetSortKey : null);
                bool flag = true;
                int num3 = -1;
                if (contraction != null && ptr != null)
                {
                    for (int i = 0; i < contraction.SortKey.Length; i++)
                    {
                        ptr[i] = contraction.SortKey[i];
                    }
                }
                else if (ptr != null)
                {
                    num3 = this.FilterOptions((int)target[num2], option);
                    *ptr = this.Category(num3);
                    ptr[1] = this.Level1(num3);
                    if ((option & CompareOptions.IgnoreNonSpace) == CompareOptions.None)
                    {
                        ptr[2] = this.Level2(num3, SimpleCollator.ExtenderType.None);
                    }
                    ptr[3] = MSCompatUnicodeTable.Level3(num3);
                    flag = !MSCompatUnicodeTable.HasSpecialWeight((char)num3);
                }
                if (ptr != null)
                {
                    num2++;
                    while (num2 < target.Length && this.Category((int)target[num2]) == 1)
                    {
                        if (ptr[2] == 0)
{
                            ptr[2] = 2;
                        }
                        ptr[2] = ptr[2] + this.Level2((int)target[num2], SimpleCollator.ExtenderType.None);
                        num2++;
                    }
                }
                int num4;
                for (;;)
                {
                    if (text != null)
                    {
                        num4 = this.LastIndexOf(s, text, start, length, targetSortKey, ref ctx);
                    }
                    else
                    {
                        num4 = this.LastIndexOfSortKey(s, start, num, length, ptr, num3, flag, ref ctx);
                    }
                    if (num4 < 0)
                    {
                        break;
                    }
                    length -= start - num4;
                    start = num4;
                    if (this.IsPrefix(s, target, num4, num - num4 + 1, false, ref ctx))
                    {
                        goto Block_16;
                    }
                    Contraction contraction2 = this.GetContraction(s, num4, num - num4 + 1);
                    if (contraction2 != null)
                    {
                        start -= contraction2.Source.Length;
                        length -= contraction2.Source.Length;
                    }
                    else
                    {
                        start--;
                        length--;
                    }
                    if (length <= 0)
                    {
                        return -1;
                    }
                }
                return -1;
                Block_16:
                while (num4 < num && SimpleCollator.IsIgnorable((int)s[num4], option))
                {
                    num4++;
                }
                return num4;
            }
            if (this.IndexOfOrdinal(target, '\0', 0, target.Length) < 0)
            {
                return start;
            }
            return this.LastIndexOfOrdinal(s, target, start, length);
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.FilterOptions(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.MSCompatUnicodeTable.HasSpecialWeight(), Mono.Globalization.Unicode.SimpleCollator.IndexOfOrdinal(), Mono.Globalization.Unicode.SimpleCollator.IsIgnorable(), Mono.Globalization.Unicode.SimpleCollator.IsPrefix(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOfOrdinal(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOfSortKey(), System.length, Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), Mono.Globalization.Unicode.Contraction.Replacement, System.s, Mono.Globalization.Unicode.Contraction.SortKey, Mono.Globalization.Unicode.Contraction.Source, System.start, and System.text.