Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.GetSortKey
GetSortKey() [3/4]
unsafe void Mono.Globalization.Unicode.SimpleCollator.GetSortKey (string s, int start, int end, SortKeyBuffer buf, CompareOptions opt) inline private
Definition at line 485 of file SimpleCollator.cs.
        {
            byte* ptr = stackalloc byte[(UIntPtr)4];
            this.ClearBuffer(ptr, 4);
            SimpleCollator.Context context = new SimpleCollator.Context(opt, null, null, null, null, ptr);
            for (int i = start; i < end; i++)
            {
                int num = (int)s[i];
                SimpleCollator.ExtenderType extenderType = this.GetExtenderType(num);
                if (extenderType != SimpleCollator.ExtenderType.None)
                {
                    num = this.FilterExtender(context.PrevCode, extenderType, opt);
                    if (num >= 0)
                    {
                        this.FillSortKeyRaw(num, extenderType, buf, opt);
                    }
                    else if (context.PrevSortKey != null)
                    {
                        byte* prevSortKey = context.PrevSortKey;
                        buf.AppendNormal(*prevSortKey, prevSortKey[1], (prevSortKey[2] != 1) ? prevSortKey[2] : this.Level2(num, extenderType), (prevSortKey[3] != 1) ? prevSortKey[3] : MSCompatUnicodeTable.Level3(num));
                    }
                }
                else if (!SimpleCollator.IsIgnorable(num, opt))
                {
                    num = this.FilterOptions(num, opt);
                    Contraction contraction = this.GetContraction(s, i, end);
                    if (contraction != null)
                    {
                        if (contraction.Replacement != null)
{
                            this.GetSortKey(contraction.Replacement, 0, contraction.Replacement.Length, buf, opt);
                        }
                        else
{
                            byte* prevSortKey2 = context.PrevSortKey;
                            for (int j = 0; j < contraction.SortKey.Length; j++)
{
                                prevSortKey2[j] = contraction.SortKey[j];
                            }
                            buf.AppendNormal(*prevSortKey2, prevSortKey2[1], (prevSortKey2[2] != 1) ? prevSortKey2[2] : this.Level2(num, extenderType), (prevSortKey2[3] != 1) ? prevSortKey2[3] : MSCompatUnicodeTable.Level3(num));
                            context.PrevCode = -1;
                        }
                        i += contraction.Source.Length - 1;
                    }
                    else
                    {
                        if (!MSCompatUnicodeTable.IsIgnorableNonSpacing(num))
{
                            context.PrevCode = num;
                        }
                        this.FillSortKeyRaw(num, SimpleCollator.ExtenderType.None, buf, opt);
                    }
                }
            }
        }
References Mono.Globalization.Unicode.SortKeyBuffer.AppendNormal(), Mono.Globalization.Unicode.SimpleCollator.ClearBuffer(), Mono.Globalization.Unicode.SimpleCollator.FillSortKeyRaw(), Mono.Globalization.Unicode.SimpleCollator.FilterExtender(), Mono.Globalization.Unicode.SimpleCollator.FilterOptions(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.SimpleCollator.GetExtenderType(), Mono.Globalization.Unicode.SimpleCollator.GetSortKey(), int, Mono.Globalization.Unicode.SimpleCollator.IsIgnorable(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsIgnorableNonSpacing(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), Mono.Globalization.Unicode.SimpleCollator.Context.PrevCode, Mono.Globalization.Unicode.SimpleCollator.Context.PrevSortKey, Mono.Globalization.Unicode.Contraction.Replacement, System.s, Mono.Globalization.Unicode.Contraction.SortKey, and System.start.