Terraria Decompiled: System.Runtime.Remoting.InternalRemotingServices.GetCachedSoapAttribute
GetCachedSoapAttribute()
static SoapAttribute System.Runtime.Remoting.InternalRemotingServices.GetCachedSoapAttribute (object reflectionObject) inline static
Definition at line 28 of file InternalRemotingServices.cs.
        {
            object syncRoot = InternalRemotingServices._soapAttributes.SyncRoot;
            SoapAttribute soapAttribute2;
            lock (syncRoot)
            {
                SoapAttribute soapAttribute = InternalRemotingServices._soapAttributes[reflectionObject] as SoapAttribute;
                if (soapAttribute != null)
                {
                    soapAttribute2 = soapAttribute;
                }
                else
                {
                    object[] customAttributes = ((ICustomAttributeProvider)reflectionObject).GetCustomAttributes(typeof(SoapAttribute), true);
                    if (customAttributes.Length != 0)
                    {
                        soapAttribute = (SoapAttribute)customAttributes[0];
                    }
                    else if (reflectionObject is Type)
                    {
                        soapAttribute = new SoapTypeAttribute();
                    }
                    else if (reflectionObject is FieldInfo)
                    {
                        soapAttribute = new SoapFieldAttribute();
                    }
                    else if (reflectionObject is MethodBase)
                    {
                        soapAttribute = new SoapMethodAttribute();
                    }
                    else if (reflectionObject is ParameterInfo)
                    {
                        soapAttribute = new SoapParameterAttribute();
                    }
                    soapAttribute.SetReflectionObject(reflectionObject);
                    InternalRemotingServices._soapAttributes[reflectionObject] = soapAttribute;
                    soapAttribute2 = soapAttribute;
                }
            }
            return soapAttribute2;
        }
References System.Runtime.Remoting.InternalRemotingServices._soapAttributes, System.Attribute.GetCustomAttributes(), System.Runtime.Remoting.Metadata.SoapAttribute.SetReflectionObject(), and System.Collections.Hashtable.SyncRoot.
Referenced by System.Runtime.Remoting.SoapServices.GetXmlElementForInteropType(), System.Runtime.Remoting.SoapServices.GetXmlTypeForInteropType(), System.Runtime.Remoting.SoapServices.InternalGetSoapAction(), and System.Runtime.Remoting.SoapServices.PreLoad().