Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.MatchesPrimitive
MatchesPrimitive()
unsafe bool Mono.Globalization.Unicode.SimpleCollator.MatchesPrimitive (CompareOptions opt, byte * source, int si, SimpleCollator::ExtenderType ext, byte * target, int ti, bool noLv4) inline private
Definition at line 1903 of file SimpleCollator.cs.
        {
            bool flag = (opt & CompareOptions.IgnoreNonSpace) > CompareOptions.None;
            return *source == *target && source[1] == target[1] && (flag || source[2] == target[2]) && source[3] == target[3] && ((noLv4 && (si < 0 || !MSCompatUnicodeTable.HasSpecialWeight((char)si))) || (!noLv4 && (flag || ext != SimpleCollator.ExtenderType.Conditional) && MSCompatUnicodeTable.IsJapaneseSmallLetter((char)si) == MSCompatUnicodeTable.IsJapaneseSmallLetter((char)ti) && SimpleCollator.ToDashTypeValue(ext, opt) == SimpleCollator.ToDashTypeValue(SimpleCollator.ExtenderType.None, opt) && !MSCompatUnicodeTable.IsHiragana((char)si) == !MSCompatUnicodeTable.IsHiragana((char)ti) && SimpleCollator.IsHalfKana((int)((ushort)si), opt) == SimpleCollator.IsHalfKana((int)((ushort)ti), opt)));
        }
References Mono.Globalization.Unicode.MSCompatUnicodeTable.HasSpecialWeight(), Mono.Globalization.Unicode.SimpleCollator.IsHalfKana(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsHiragana(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsJapaneseSmallLetter(), System.source, and Mono.Globalization.Unicode.SimpleCollator.ToDashTypeValue().
Referenced by Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore(), and Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore().