Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.SimpleCollator
SimpleCollator() [1/2]
Mono.Globalization.Unicode.SimpleCollator.SimpleCollator (CultureInfo culture) inline
Definition at line 10 of file SimpleCollator.cs.
        {
            this.lcid = culture.LCID;
            this.textInfo = culture.TextInfo;
            this.SetCJKTable(culture, ref this.cjkIndexer, ref this.cjkCatTable, ref this.cjkLv1Table, ref this.cjkLv2Indexer, ref this.cjkLv2Table);
            TailoringInfo tailoringInfo = null;
            CultureInfo cultureInfo = culture;
            while (cultureInfo.LCID != 127)
            {
                tailoringInfo = MSCompatUnicodeTable.GetTailoringInfo(cultureInfo.LCID);
                if (tailoringInfo != null)
                {
                    break;
                }
                cultureInfo = cultureInfo.Parent;
            }
            if (tailoringInfo == null)
            {
                tailoringInfo = MSCompatUnicodeTable.GetTailoringInfo(127);
            }
            this.frenchSort = tailoringInfo.FrenchSort;
            MSCompatUnicodeTable.BuildTailoringTables(culture, tailoringInfo, ref this.contractions, ref this.level2Maps);
            this.unsafeFlags = new byte[96];
            foreach (Contraction contraction in this.contractions)
            {
                if (contraction.Source.Length > 1)
                {
                    foreach (char c in contraction.Source)
                    {
                        byte[] array3 = this.unsafeFlags;
                        char c2 = c / '\b';
                        array3[(int)c2] = array3[(int)c2] | (byte)(1 << (int)(c & '\a'));
                    }
                }
            }
            if (this.lcid != 127)
            {
                foreach (Contraction contraction2 in SimpleCollator.invariant.contractions)
                {
                    if (contraction2.Source.Length > 1)
                    {
                        foreach (char c3 in contraction2.Source)
{
                            byte[] array4 = this.unsafeFlags;
                            char c4 = c3 / '\b';
                            array4[(int)c4] = array4[(int)c4] | (byte)(1 << (int)(c3 & '\a'));
                        }
                    }
                }
            }
        }
References Mono.Globalization.Unicode.MSCompatUnicodeTable.BuildTailoringTables(), Mono.Globalization.Unicode.SimpleCollator.cjkCatTable, Mono.Globalization.Unicode.SimpleCollator.cjkIndexer, Mono.Globalization.Unicode.SimpleCollator.cjkLv1Table, Mono.Globalization.Unicode.SimpleCollator.cjkLv2Indexer, Mono.Globalization.Unicode.SimpleCollator.cjkLv2Table, Mono.Globalization.Unicode.SimpleCollator.contractions, System.culture, Mono.Globalization.Unicode.TailoringInfo.FrenchSort, Mono.Globalization.Unicode.MSCompatUnicodeTable.GetTailoringInfo(), int, Mono.Globalization.Unicode.SimpleCollator.invariant, Mono.Globalization.Unicode.SimpleCollator.lcid, System.Globalization.CultureInfo.LCID, Mono.Globalization.Unicode.SimpleCollator.level2Maps, System.Globalization.CultureInfo.Parent, Mono.Globalization.Unicode.SimpleCollator.SetCJKTable(), Mono.Globalization.Unicode.Contraction.Source, and Mono.Globalization.Unicode.SimpleCollator.unsafeFlags.