Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.Level1
Level1()
unsafe byte Mono.Globalization.Unicode.SimpleCollator.Level1 (int cp) inline private
Definition at line 95 of file SimpleCollator.cs.
        {
            if (cp < 12288 || this.cjkLv1Table == null)
            {
                return MSCompatUnicodeTable.Level1(cp);
            }
            int num = this.cjkIndexer.ToIndex(cp);
            if (num >= 0)
            {
                return this.cjkLv1Table[num];
            }
            return MSCompatUnicodeTable.Level1(cp);
        }
References Mono.Globalization.Unicode.SimpleCollator.cjkIndexer, Mono.Globalization.Unicode.SimpleCollator.cjkLv1Table, Mono.Globalization.Unicode.MSCompatUnicodeTable.Level1(), and Mono.Globalization.Unicode.CodePointIndexer.ToIndex().
Referenced by Mono.Globalization.Unicode.SimpleCollator.CompareInternal(), Mono.Globalization.Unicode.SimpleCollator.FillSortKeyRaw(), Mono.Globalization.Unicode.SimpleCollator.FilterExtender(), Mono.Globalization.Unicode.SimpleCollator.IndexOf(), Mono.Globalization.Unicode.SimpleCollator.IndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore(), and Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore().