Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.LastIndexOf
LastIndexOf() [2/5]
unsafe int Mono.Globalization.Unicode.SimpleCollator.LastIndexOf (string s, char target, int start, int length, CompareOptions opt) inline
Implements System.Globalization.ISimpleCollator.
Definition at line 1611 of file SimpleCollator.cs.
        {
            if (opt == CompareOptions.Ordinal)
            {
                throw new NotSupportedException();
            }
            if (opt == CompareOptions.OrdinalIgnoreCase)
            {
                throw new NotSupportedException();
            }
            byte* ptr = stackalloc byte[(UIntPtr)16];
            byte* ptr2 = stackalloc byte[(UIntPtr)16];
            byte* ptr3 = stackalloc byte[(UIntPtr)4];
            byte* ptr4 = stackalloc byte[(UIntPtr)4];
            byte* ptr5 = stackalloc byte[(UIntPtr)4];
            this.ClearBuffer(ptr, 16);
            this.ClearBuffer(ptr2, 16);
            this.ClearBuffer(ptr3, 4);
            this.ClearBuffer(ptr4, 4);
            this.ClearBuffer(ptr5, 4);
            SimpleCollator.Context context = new SimpleCollator.Context(opt, ptr, ptr2, ptr4, ptr5, null);
            Contraction contraction = this.GetContraction(target);
            if (contraction == null)
            {
                int num = this.FilterOptions((int)target, opt);
                *ptr3 = this.Category(num);
                ptr3[1] = this.Level1(num);
                if ((opt & CompareOptions.IgnoreNonSpace) == CompareOptions.None)
                {
                    ptr3[2] = this.Level2(num, SimpleCollator.ExtenderType.None);
                }
                ptr3[3] = MSCompatUnicodeTable.Level3(num);
                return this.LastIndexOfSortKey(s, start, start, length, ptr3, num, !MSCompatUnicodeTable.HasSpecialWeight((char)num), ref context);
            }
            if (contraction.Replacement != null)
            {
                return this.LastIndexOf(s, contraction.Replacement, start, length, ptr3, ref context);
            }
            for (int i = 0; i < contraction.SortKey.Length; i++)
            {
                ptr5[i] = contraction.SortKey[i];
            }
            return this.LastIndexOfSortKey(s, start, start, length, ptr5, -1, true, ref context);
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.ClearBuffer(), Mono.Globalization.Unicode.SimpleCollator.FilterOptions(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.MSCompatUnicodeTable.HasSpecialWeight(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOfSortKey(), System.length, Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), Mono.Globalization.Unicode.Contraction.Replacement, Mono.Globalization.Unicode.Contraction.SortKey, and System.start.