Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.GetExtenderType
GetExtenderType()
SimpleCollator.ExtenderType Mono.Globalization.Unicode.SimpleCollator.GetExtenderType (int i) inline private
Definition at line 300 of file SimpleCollator.cs.
        {
            if (i == 8213)
            {
                if (this.lcid != 16)
                {
                    return SimpleCollator.ExtenderType.None;
                }
                return SimpleCollator.ExtenderType.Conditional;
            }
            else
            {
                if (i < 12293 || i > 65392)
                {
                    return SimpleCollator.ExtenderType.None;
                }
                if (i >= 65148)
                {
                    if (i - 65148 <= 1)
                    {
                        return SimpleCollator.ExtenderType.Simple;
                    }
                    if (i == 65392)
                    {
                        return SimpleCollator.ExtenderType.Conditional;
                    }
                    if (i - 65438 <= 1)
                    {
                        return SimpleCollator.ExtenderType.Voiced;
                    }
                }
                if (i > 12542)
                {
                    return SimpleCollator.ExtenderType.None;
                }
                if (i <= 12338)
                {
                    if (i == 12293)
                    {
                        return SimpleCollator.ExtenderType.Buggy;
                    }
                    if (i - 12337 > 1)
                    {
                        return SimpleCollator.ExtenderType.None;
                    }
                }
                else if (i != 12445)
                {
                    if (i != 12446)
                    {
                        switch (i)
{
                        case 12540:
                            return SimpleCollator.ExtenderType.Conditional;
                        case 12541:
                            return SimpleCollator.ExtenderType.Simple;
                        case 12542:
                            break;
                        default:
                            return SimpleCollator.ExtenderType.None;
                        }
                    }
                    return SimpleCollator.ExtenderType.Voiced;
                }
                return SimpleCollator.ExtenderType.Simple;
            }
        }
References Mono.Globalization.Unicode.SimpleCollator.lcid.
Referenced by Mono.Globalization.Unicode.SimpleCollator.CompareInternal(), Mono.Globalization.Unicode.SimpleCollator.GetSortKey(), Mono.Globalization.Unicode.SimpleCollator.MatchesBackward(), and Mono.Globalization.Unicode.SimpleCollator.MatchesForward().