Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.FilterOptions
FilterOptions()
int Mono.Globalization.Unicode.SimpleCollator.FilterOptions (int i, CompareOptions opt) inline private
Definition at line 274 of file SimpleCollator.cs.
        {
            if ((opt & CompareOptions.IgnoreWidth) != CompareOptions.None)
            {
                int num = MSCompatUnicodeTable.ToWidthCompat(i);
                if (num != 0)
                {
                    i = num;
                }
            }
            if ((opt & CompareOptions.OrdinalIgnoreCase) != CompareOptions.None)
            {
                i = (int)this.textInfo.ToLower((char)i);
            }
            if ((opt & CompareOptions.IgnoreCase) != CompareOptions.None)
            {
                i = (int)this.textInfo.ToLower((char)i);
            }
            if ((opt & CompareOptions.IgnoreKanaType) != CompareOptions.None)
            {
                i = MSCompatUnicodeTable.ToKanaTypeInsensitive(i);
            }
            return i;
        }
References int, Mono.Globalization.Unicode.SimpleCollator.textInfo, Mono.Globalization.Unicode.MSCompatUnicodeTable.ToKanaTypeInsensitive(), System.Globalization.TextInfo.ToLower(), and Mono.Globalization.Unicode.MSCompatUnicodeTable.ToWidthCompat().
Referenced by Mono.Globalization.Unicode.SimpleCollator.CompareInternal(), Mono.Globalization.Unicode.SimpleCollator.GetSortKey(), Mono.Globalization.Unicode.SimpleCollator.IndexOf(), Mono.Globalization.Unicode.SimpleCollator.IndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), Mono.Globalization.Unicode.SimpleCollator.LastIndexOf(), Mono.Globalization.Unicode.SimpleCollator.MatchesBackwardCore(), and Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore().