Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.FillSortKeyRaw
FillSortKeyRaw()
void Mono.Globalization.Unicode.SimpleCollator.FillSortKeyRaw (int i, SimpleCollator::ExtenderType ext, SortKeyBuffer buf, CompareOptions opt) inline private
Definition at line 542 of file SimpleCollator.cs.
        {
            if (13312 <= i && i <= 19893)
            {
                int num = i - 13312;
                buf.AppendCJKExtension((byte)(16 + num / 254), (byte)(num % 254 + 2));
                return;
            }
            UnicodeCategory unicodeCategory = char.GetUnicodeCategory((char)i);
            if (unicodeCategory == UnicodeCategory.Surrogate)
            {
                this.FillSurrogateSortKeyRaw(i, buf);
                return;
            }
            if (unicodeCategory == UnicodeCategory.PrivateUse)
            {
                int num2 = i - 57344;
                buf.AppendNormal((byte)(229 + num2 / 254), (byte)(num2 % 254 + 2), 0, 0);
                return;
            }
            byte b = this.Level2(i, ext);
            if (MSCompatUnicodeTable.HasSpecialWeight((char)i))
            {
                byte b2 = this.Level1(i);
                buf.AppendKana(this.Category(i), b2, b, MSCompatUnicodeTable.Level3(i), MSCompatUnicodeTable.IsJapaneseSmallLetter((char)i), SimpleCollator.ToDashTypeValue(ext, opt), !MSCompatUnicodeTable.IsHiragana((char)i), SimpleCollator.IsHalfKana((int)((ushort)i), opt));
                if ((opt & CompareOptions.IgnoreNonSpace) == CompareOptions.None && ext == SimpleCollator.ExtenderType.Voiced)
                {
                    buf.AppendNormal(1, 1, 1, 0);
                    return;
                }
            }
            else
            {
                buf.AppendNormal(this.Category(i), this.Level1(i), b, MSCompatUnicodeTable.Level3(i));
            }
        }
References Mono.Globalization.Unicode.SortKeyBuffer.AppendCJKExtension(), Mono.Globalization.Unicode.SortKeyBuffer.AppendKana(), Mono.Globalization.Unicode.SortKeyBuffer.AppendNormal(), Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.FillSurrogateSortKeyRaw(), Mono.Globalization.Unicode.MSCompatUnicodeTable.HasSpecialWeight(), Mono.Globalization.Unicode.SimpleCollator.IsHalfKana(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsHiragana(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsJapaneseSmallLetter(), Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), and Mono.Globalization.Unicode.SimpleCollator.ToDashTypeValue().
Referenced by Mono.Globalization.Unicode.SimpleCollator.GetSortKey().