Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore
MatchesForwardCore()
unsafe bool Mono.Globalization.Unicode.SimpleCollator.MatchesForwardCore (string s, ref int idx, int end, int ti, byte * sortkey, bool noLv4, SimpleCollator::ExtenderType ext, ref Contraction ct, ref SimpleCollator::Context ctx) inline private
Definition at line 1806 of file SimpleCollator.cs.
        {
            CompareOptions option = ctx.Option;
            byte* ptr = ctx.Buffer1;
            bool flag = (option & CompareOptions.IgnoreNonSpace) > CompareOptions.None;
            int num = -1;
            if (ext == SimpleCollator.ExtenderType.None)
            {
                ct = this.GetContraction(s, idx, end);
            }
            else if (ctx.PrevCode < 0)
            {
                if (ctx.PrevSortKey == null)
                {
                    idx++;
                    return false;
                }
                ptr = ctx.PrevSortKey;
            }
            else
            {
                num = this.FilterExtender(ctx.PrevCode, ext, option);
            }
            if (ct != null)
            {
                idx += ct.Source.Length;
                if (!noLv4)
                {
                    return false;
                }
                if (ct.SortKey == null)
                {
                    int num2 = 0;
                    return this.MatchesForward(ct.Replacement, ref num2, ct.Replacement.Length, ti, sortkey, noLv4, ref ctx);
                }
                for (int i = 0; i < 4; i++)
                {
                    ptr[i] = sortkey[i];
                }
                ctx.PrevCode = -1;
                ctx.PrevSortKey = ptr;
            }
            else
            {
                if (num < 0)
                {
                    num = this.FilterOptions((int)s[idx], option);
                }
                idx++;
                *ptr = this.Category(num);
                bool flag2 = false;
                if (*sortkey == *ptr)
                {
                    ptr[1] = this.Level1(num);
                }
                else
                {
                    flag2 = true;
                }
                if (!flag && sortkey[1] == ptr[1])
                {
                    ptr[2] = this.Level2(num, ext);
                }
                else if (!flag)
                {
                    flag2 = true;
                }
                if (flag2)
                {
                    while (idx < end && this.Category((int)s[idx]) == 1)
                    {
                        idx++;
                    }
                    return false;
                }
                ptr[3] = MSCompatUnicodeTable.Level3(num);
                if (*ptr != 1)
                {
                    ctx.PrevCode = num;
                }
            }
            while (idx < end && this.Category((int)s[idx]) == 1)
            {
                if (!flag)
                {
                    if (ptr[2] == 0)
                    {
                        ptr[2] = 2;
                    }
                    ptr[2] = ptr[2] + this.Level2((int)s[idx], SimpleCollator.ExtenderType.None);
                }
                idx++;
            }
            return this.MatchesPrimitive(option, ptr, num, ext, sortkey, ti, noLv4);
        }
References Mono.Globalization.Unicode.SimpleCollator.Category(), Mono.Globalization.Unicode.SimpleCollator.FilterExtender(), Mono.Globalization.Unicode.SimpleCollator.FilterOptions(), Mono.Globalization.Unicode.SimpleCollator.GetContraction(), Mono.Globalization.Unicode.SimpleCollator.Level1(), Mono.Globalization.Unicode.SimpleCollator.Level2(), Mono.Globalization.Unicode.MSCompatUnicodeTable.Level3(), Mono.Globalization.Unicode.SimpleCollator.MatchesForward(), and Mono.Globalization.Unicode.SimpleCollator.MatchesPrimitive().
Referenced by Mono.Globalization.Unicode.SimpleCollator.MatchesForward().