Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.Compare
Compare() [3/3]
int Mono.Globalization.Unicode.SimpleCollator.Compare (string s1, string s2) inline
Implements System.Globalization.ISimpleCollator.
Definition at line 614 of file SimpleCollator.cs.
        {
            return this.Compare(s1, 0, s1.Length, s2, 0, s2.Length, CompareOptions.None);
        }
References Mono.Globalization.Unicode.SimpleCollator.Compare().
Referenced by Mono.Globalization.Unicode.SimpleCollator.Compare(), Mono.Globalization.Unicode.SimpleCollator.Compare(), and Mono.Globalization.Unicode.SimpleCollator.IsSuffix().