Terraria Decompiled: Mono.Globalization.Unicode.SimpleCollator.GetSortKey
GetSortKey() [4/4]
SortKey Mono.Globalization.Unicode.SimpleCollator.GetSortKey (string s, int start, int length, CompareOptions options) inline
Definition at line 475 of file SimpleCollator.cs.
        {
            SortKeyBuffer sortKeyBuffer = new SortKeyBuffer(this.lcid);
            sortKeyBuffer.Initialize(options, this.lcid, s, this.frenchSort);
            int num = start + length;
            this.GetSortKey(s, start, num, sortKeyBuffer, options);
            return sortKeyBuffer.GetResultAndReset();
        }
References Mono.Globalization.Unicode.SimpleCollator.frenchSort, Mono.Globalization.Unicode.SortKeyBuffer.GetResultAndReset(), Mono.Globalization.Unicode.SimpleCollator.GetSortKey(), Mono.Globalization.Unicode.SortKeyBuffer.Initialize(), Mono.Globalization.Unicode.SimpleCollator.lcid, System.length, System.options, and System.start.