Terraria Decompiled: System.Threading.ThreadHelper.ThreadStart
ThreadStart() [2/2]
void System.Threading.ThreadHelper.ThreadStart (object obj) inline package
Definition at line 36 of file ThreadHelper.cs.
        {
            this._startArg = obj;
            if (this._executionContext != null)
            {
                ExecutionContext.Run(this._executionContext, ThreadHelper._ccb, this);
                return;
            }
            ((ParameterizedThreadStart)this._start)(obj);
        }
References System.Threading.ThreadHelper._ccb, System.Threading.ThreadHelper._executionContext, System.Threading.ThreadHelper._start, System.obj, System.Threading.ParameterizedThreadStart(), and System.Threading.ExecutionContext.Run().
Referenced by System.Threading.Thread.SetStartHelper().