Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerAV1.GetTexture
GetTexture()
Texture2D Microsoft.Xna.Framework.Media.VideoPlayerAV1.GetTexture () inline
Implements Microsoft.Xna.Framework.Media.IVideoPlayerCodec.
Definition at line 129 of file VideoPlayerAV1.cs.
        {
            base.checkDisposed();
            if (this.Video == null)
            {
                throw new InvalidOperationException();
            }
            if (this.State == MediaState.Stopped || this.context == IntPtr.Zero)
            {
                return this.videoTexture[0].RenderTarget as Texture2D;
            }
            int num = (int)(this.timer.Elapsed.TotalMilliseconds / (1000.0 / this.fps));
            if (num > this.currentFrame)
            {
                if (this.DecodeAndUpdateFrame(num - this.currentFrame) || this.currentFrame == -1)
                {
                    float num2;
                    if (this.bitsPerPixel == 12)
                    {
                        num2 = 16f;
                    }
                    else if (this.bitsPerPixel == 10)
                    {
                        num2 = 64f;
                    }
                    else
                    {
                        num2 = 1f;
                    }
                    this.shaderProgram.Parameters["RescaleFactor"].SetValue(new Vector4(num2, num2, num2, 1f));
                    base.GL_pushState();
                    this.currentDevice.DrawPrimitives(PrimitiveType.TriangleStrip, 0, 2);
                    base.GL_popState();
                }
                this.currentFrame = num;
            }
            if (Bindings.df_eos(this.context) == 1)
            {
                if (this.Video.needsDurationHack)
                {
                    this.Video.Duration = this.timer.Elapsed;
                }
                this.timer.Stop();
                this.timer.Reset();
                Bindings.df_reset(this.context);
                if (this.IsLooped)
                {
                    this.currentFrame = -1;
                    this.timer.Start();
                }
                else
                {
                    this.State = MediaState.Stopped;
                }
            }
            return this.videoTexture[0].RenderTarget as Texture2D;
        }
References Microsoft.Xna.Framework.Media.VideoPlayerAV1.bitsPerPixel, Microsoft.Xna.Framework.Media.VideoPlayerAV1.context, Microsoft.Xna.Framework.Media.BaseYUVPlayer.currentDevice, Microsoft.Xna.Framework.Media.VideoPlayerAV1.currentFrame, Microsoft.Xna.Framework.Media.VideoPlayerAV1.DecodeAndUpdateFrame(), Dav1dfile.Bindings.df_eos(), Dav1dfile.Bindings.df_reset(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives(), int, Microsoft.Xna.Framework.Media.VideoPlayerAV1.IsLooped, Microsoft.Xna.Framework.Media.Video.needsDurationHack, Microsoft.Xna.Framework.Graphics.Effect.Parameters, Microsoft.Xna.Framework.Graphics.RenderTargetBinding.RenderTarget, Microsoft.Xna.Framework.Media.BaseYUVPlayer.shaderProgram, Microsoft.Xna.Framework.Media.VideoPlayerAV1.State, Microsoft.Xna.Framework.Graphics.Texture2D, Microsoft.Xna.Framework.Media.VideoPlayerAV1.timer, Microsoft.Xna.Framework.Graphics.Vector4, Microsoft.Xna.Framework.Media.BaseYUVPlayer.videoTexture, and System.IntPtr.Zero.