Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerAV1.ReadInfo
ReadInfo()
static VideoPlayer.VideoInfo Microsoft.Xna.Framework.Media.VideoPlayerAV1.ReadInfo (string fileName) inline static package
Definition at line 393 of file VideoPlayerAV1.cs.
        {
            IntPtr intPtr;
            Bindings.df_fopen(fileName, out intPtr);
            int num;
            int num2;
            Bindings.PixelLayout pixelLayout;
            byte b;
            Bindings.df_videoinfo2(intPtr, out num, out num2, out pixelLayout, out b);
            double num3;
            if (Bindings.df_guessframerate(intPtr, out num3) == 0)
            {
                num3 = 0.0;
            }
            Bindings.df_close(intPtr);
            return new VideoPlayer.VideoInfo
            {
                fps = num3,
                width = num,
                height = num2
            };
        }
References Dav1dfile.Bindings.df_close(), Dav1dfile.Bindings.df_fopen(), Dav1dfile.Bindings.df_guessframerate(), Dav1dfile.Bindings.df_videoinfo2(), and Microsoft.Xna.Framework.Media.VideoPlayerAV1.fps.