Terraria Decompiled: Microsoft.Xna.Framework.Media.VideoPlayerAV1.Play
Play()
void Microsoft.Xna.Framework.Media.VideoPlayerAV1.Play (Video video) inline
Implements Microsoft.Xna.Framework.Media.IVideoPlayerCodec.
Definition at line 188 of file VideoPlayerAV1.cs.
        {
            base.checkDisposed();
            this.Video = video;
            this.Video.parent = this;
            if (this.context != IntPtr.Zero)
            {
                Bindings.df_close(this.context);
                this.context = IntPtr.Zero;
            }
            if (this.Video.needsDurationHack)
            {
                this.Video.Duration = TimeSpan.MaxValue;
            }
            int num = Bindings.df_fopen(this.Video.handle, out this.context);
            if (this.context == IntPtr.Zero || num == 0)
            {
                throw new FileNotFoundException(this.Video.handle);
            }
            int num2;
            int num3;
            Bindings.PixelLayout pixelLayout;
            try
            {
                byte b;
                Bindings.df_videoinfo2(this.context, out num2, out num3, out pixelLayout, out b);
                if (b == 2)
                {
                    this.bitsPerPixel = 12;
                }
                else if (b == 1)
                {
                    this.bitsPerPixel = 10;
                }
                else
                {
                    this.bitsPerPixel = 8;
                }
                if (Bindings.df_guessframerate(this.context, out this.fps) == 0)
                {
                    this.fps = (double)this.Video.FramesPerSecond;
                }
            }
            catch
            {
                Bindings.df_videoinfo(this.context, out num2, out num3, out pixelLayout);
                this.bitsPerPixel = 8;
                this.fps = (double)this.Video.FramesPerSecond;
            }
            int num4;
            int num5;
            switch (pixelLayout)
            {
            case Bindings.PixelLayout.I420:
                num4 = num2 / 2;
                num5 = num3 / 2;
                break;
            case Bindings.PixelLayout.I422:
                num4 = num2 / 2;
                num5 = num3;
                break;
            case Bindings.PixelLayout.I444:
                num4 = num2;
                num5 = num3;
                break;
            default:
                throw new NotSupportedException("Unsupported pixel layout in AV1 file");
            }
            if (this.Video.Width != num2 || this.Video.Height != num3)
            {
                throw new InvalidOperationException("XNB/OGV width/height mismatch! Width: " + this.Video.Width.ToString() + " Height: " + this.Video.Height.ToString());
            }
            if (this.fps == 0.0)
            {
                throw new InvalidOperationException("Framerate not present in header or manually specified");
            }
            if (Math.Abs((double)this.Video.FramesPerSecond - this.fps) >= 1.0)
            {
                throw new InvalidOperationException("XNB/OGV framesPerSecond mismatch! FPS: " + this.Video.FramesPerSecond.ToString());
            }
            if (this.State != MediaState.Stopped)
            {
                return;
            }
            this.State = MediaState.Playing;
            this.currentFrame = -1;
            if (this.currentDevice != this.Video.GraphicsDevice)
            {
                base.GL_dispose();
                this.currentDevice = this.Video.GraphicsDevice;
                base.GL_initialize(Resources.YUVToRGBAEffectR);
            }
            RenderTargetBinding renderTargetBinding = this.videoTexture[0];
            this.videoTexture[0] = new RenderTargetBinding(new RenderTarget2D(this.currentDevice, num2, num3, false, SurfaceFormat.Color, DepthFormat.None, 0, RenderTargetUsage.PreserveContents));
            if (renderTargetBinding.RenderTarget != null)
            {
                renderTargetBinding.RenderTarget.Dispose();
            }
            base.GL_setupTextures(num2, num3, num4, num5, (this.bitsPerPixel > 8) ? SurfaceFormat.UShortEXT : SurfaceFormat.ByteEXT);
            this.timer.Start();
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Media.VideoPlayerAV1.bitsPerPixel, Microsoft.Xna.Framework.Media.VideoPlayerAV1.context, Microsoft.Xna.Framework.Media.BaseYUVPlayer.currentDevice, Dav1dfile.Bindings.df_close(), Dav1dfile.Bindings.df_fopen(), Dav1dfile.Bindings.df_guessframerate(), Dav1dfile.Bindings.df_videoinfo(), Dav1dfile.Bindings.df_videoinfo2(), Microsoft.Xna.Framework.Graphics.Texture.Dispose(), Microsoft.Xna.Framework.Media.VideoPlayerAV1.fps, Microsoft.Xna.Framework.Media.Video.FramesPerSecond, Microsoft.Xna.Framework.Media.Video.GraphicsDevice, Microsoft.Xna.Framework.Media.Video.handle, System.TimeSpan.MaxValue, Microsoft.Xna.Framework.Media.Video.needsDurationHack, Microsoft.Xna.Framework.Graphics.RenderTargetBinding.RenderTarget, Microsoft.Xna.Framework.Media.VideoPlayerAV1.State, Microsoft.Xna.Framework.Media.VideoPlayerAV1.timer, Microsoft.Xna.Framework.Media.BaseYUVPlayer.videoTexture, Microsoft.Xna.Framework.Media.Video.Width, Microsoft.Xna.Framework.Graphics.Resources.YUVToRGBAEffectR, and System.IntPtr.Zero.