Terraria Decompiled: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.BeginConnection
BeginConnection()
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.BeginConnection () inline
Definition at line 24 of file GameSenseConnection.cs.
        {
            this._mSerializer = new fsSerializer();
            this._mMsgQueue = new LocklessQueue<QueueMsg>(100U);
            this._gameSenseThread = new Thread(new ThreadStart(this._gamesenseWrk));
            this._mGameSenseWrkShouldRun = true;
            this._setClientState(ClientState.Probing);
            try
            {
                this._gameSenseThread.Start();
                this._addGUIDefinedEvents();
            }
            catch (Exception ex)
            {
                GameSenseConnection._logException("Could not start the client thread", ex);
                this._setClientState(ClientState.Inactive);
            }
        }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._addGUIDefinedEvents(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gameSenseThread, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gamesenseWrk(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logException(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._setClientState(), System.Threading.Thread.Start(), System.Threading.ThreadStart(), and System.U.
Referenced by ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.ConnectToGameSense().