Terraria Decompiled: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.RegisterEvents
RegisterEvents()
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.RegisterEvents (Bind_Event[] theEvents) inline private
Definition at line 63 of file GameSenseConnection.cs.
        {
            foreach (Bind_Event bind_Event in theEvents)
            {
                QueueMsg queueMsg;
                if (bind_Event.handlers == null || bind_Event.handlers.Length == 0)
                {
                    queueMsg = new QueueMsgRegisterEvent();
                    queueMsg.data = new Register_Event(this.GameName, bind_Event.eventName, bind_Event.minValue, bind_Event.maxValue, bind_Event.iconId);
                }
                else
                {
                    bind_Event.game = this.GameName;
                    queueMsg = new QueueMsgBindEvent();
                    queueMsg.data = bind_Event;
                }
                this._mMsgQueue.PEnqueue(queueMsg);
            }
        }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._mMsgQueue, SteelSeries.GameSense.Bind_Event.eventName, ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.GameName, SteelSeries.GameSense.Bind_Event.handlers, SteelSeries.GameSense.Bind_Event.iconId, SteelSeries.GameSense.Bind_Event.maxValue, SteelSeries.GameSense.Bind_Event.minValue, and SteelSeries.GameSense.LocklessQueue< T >.PEnqueue().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._addGUIDefinedEvents(), and ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.TryRegisteringEvents().