Terraria Decompiled: ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendJson
SendJson()
void ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendJson (Uri uri, string data, bool isCritical) inline private
Definition at line 284 of file GameSenseConnection.cs.
        {
            GameSenseConnection._logDbgMsg(data);
            try
            {
                this._sendServer(uri, data);
            }
            catch (WebException ex)
            {
                WebExceptionStatus status = ex.Status;
                if (status == 2)
                {
                    throw new ServerDownException(ex.Message);
                }
                if (status != 7)
                {
                    GameSenseConnection._logException("Unexpected status", ex);
                    throw;
                }
                if (isCritical)
                {
                    Stream responseStream = ex.Response.GetResponseStream();
                    string text = new StreamReader(responseStream, Encoding.UTF8).ReadToEnd();
                    responseStream.Close();
                    throw new CriticalMessageIllFormedException(text);
                }
            }
        }
References ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logDbgMsg(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._logException(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendServer(), System.IO.Stream.Close(), System.IO.StreamReader.ReadToEnd(), System.text, and System.Text.Encoding.UTF8.