Terraria Decompiled: System.Reflection.Emit.SignatureHelper.AddArgument
AddArgument() [2/3]
void System.Reflection.Emit.SignatureHelper.AddArgument (Type argument, Type[] requiredCustomModifiers, Type[] optionalCustomModifiers) inline
Definition at line 201 of file SignatureHelper.cs.
        {
            if (argument == null)
            {
                throw new ArgumentNullException("argument");
            }
            if (requiredCustomModifiers != null)
            {
                SignatureHelper.ValidateParameterModifiers("requiredCustomModifiers", requiredCustomModifiers);
            }
            if (optionalCustomModifiers != null)
            {
                SignatureHelper.ValidateParameterModifiers("optionalCustomModifiers", optionalCustomModifiers);
            }
            int num = SignatureHelper.AppendArray(ref this.arguments, argument);
            if (requiredCustomModifiers != null)
            {
                SignatureHelper.AppendArrayAt(ref this.modreqs, requiredCustomModifiers, num);
            }
            if (optionalCustomModifiers != null)
            {
                SignatureHelper.AppendArrayAt(ref this.modopts, optionalCustomModifiers, num);
            }
        }
References System.Reflection.Emit.SignatureHelper.AppendArray(), System.Reflection.Emit.SignatureHelper.AppendArrayAt(), System.Reflection.Emit.SignatureHelper.arguments, System.Reflection.Emit.SignatureHelper.modopts, System.Reflection.Emit.SignatureHelper.modreqs, and System.Reflection.Emit.SignatureHelper.ValidateParameterModifiers().