Terraria Decompiled: System.Reflection.Emit.SignatureHelper.GetSignature
GetSignature()
byte[] System.Reflection.Emit.SignatureHelper.GetSignature () inline
Definition at line 366 of file SignatureHelper.cs.
        {
            TypeBuilder.ResolveUserTypes(this.arguments);
            SignatureHelper.SignatureHelperType signatureHelperType = this.type;
            if (signatureHelperType == SignatureHelper.SignatureHelperType.HELPER_FIELD)
            {
                return this.get_signature_field();
            }
            if (signatureHelperType == SignatureHelper.SignatureHelperType.HELPER_LOCAL)
            {
                return this.get_signature_local();
            }
            throw new NotImplementedException();
        }
References System.Reflection.Emit.SignatureHelper.arguments, System.Reflection.Emit.SignatureHelper.get_signature_field(), System.Reflection.Emit.SignatureHelper.get_signature_local(), System.Reflection.Emit.TypeBuilder.ResolveUserTypes(), and System.Reflection.Emit.SignatureHelper.type.
Referenced by System.Reflection.Emit.ILGenerator.GenerateDebugInfo().