Terraria Decompiled: System.Reflection.Emit.SignatureHelper.Equals
Equals()
override bool System.Reflection.Emit.SignatureHelper.Equals (object obj) inline
Definition at line 315 of file SignatureHelper.cs.
        {
            SignatureHelper signatureHelper = obj as SignatureHelper;
            if (signatureHelper == null)
            {
                return false;
            }
            if (signatureHelper.module != this.module || signatureHelper.returnType != this.returnType || signatureHelper.callConv != this.callConv || signatureHelper.unmanagedCallConv != this.unmanagedCallConv)
            {
                return false;
            }
            if (this.arguments != null)
            {
                if (signatureHelper.arguments == null)
                {
                    return false;
                }
                if (this.arguments.Length != signatureHelper.arguments.Length)
                {
                    return false;
                }
                for (int i = 0; i < this.arguments.Length; i++)
                {
                    if (!signatureHelper.arguments[i].Equals(this.arguments[i]))
                    {
                        return false;
                    }
                }
            }
            else if (signatureHelper.arguments != null)
            {
                return false;
            }
            return SignatureHelper.CompareOK(signatureHelper.modreqs, this.modreqs) && SignatureHelper.CompareOK(signatureHelper.modopts, this.modopts);
        }
References System.Reflection.Emit.SignatureHelper.arguments, System.Reflection.Emit.SignatureHelper.callConv, System.Reflection.Emit.SignatureHelper.CompareOK(), System.Type.Equals(), System.Reflection.Emit.SignatureHelper.modopts, System.Reflection.Emit.SignatureHelper.modreqs, System.Reflection.Emit.SignatureHelper.module, System.obj, System.Reflection.Emit.SignatureHelper.returnType, System.Reflection.Emit.SignatureHelper.SignatureHelper(), and System.Reflection.Emit.SignatureHelper.unmanagedCallConv.
Referenced by System.Reflection.Emit.SignatureHelper.CompareOK().