Terraria Decompiled: System.Reflection.Emit.SignatureHelper.AppendArray
AppendArray()
static int System.Reflection.Emit.SignatureHelper.AppendArray (ref Type[] array, Type t) inline static private
Definition at line 99 of file SignatureHelper.cs.
        {
            if (array != null)
            {
                Type[] array2 = new Type[array.Length + 1];
                Array.Copy(array, array2, array.Length);
                array2[array.Length] = t;
                array = array2;
                return array.Length - 1;
            }
            array = new Type[1];
            array[0] = t;
            return 0;
        }
References System.array, and System.Array.Copy().
Referenced by System.Reflection.Emit.SignatureHelper.AddArgument(), and System.Reflection.Emit.SignatureHelper.AddArgument().