Terraria Decompiled: System.Security.Permissions.ReflectionPermission.Intersect
Intersect()
override IPermission System.Security.Permissions.ReflectionPermission.Intersect (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 79 of file ReflectionPermission.cs.
        {
            ReflectionPermission reflectionPermission = this.Cast(target);
            if (reflectionPermission == null)
            {
                return null;
            }
            if (this.IsUnrestricted())
            {
                if (reflectionPermission.Flags == ReflectionPermissionFlag.NoFlags)
                {
                    return null;
                }
                return reflectionPermission.Copy();
            }
            else if (reflectionPermission.IsUnrestricted())
            {
                if (this.flags == ReflectionPermissionFlag.NoFlags)
                {
                    return null;
                }
                return this.Copy();
            }
            else
            {
                ReflectionPermission reflectionPermission2 = (ReflectionPermission)reflectionPermission.Copy();
                reflectionPermission2.Flags &= this.flags;
                if (reflectionPermission2.Flags != ReflectionPermissionFlag.NoFlags)
                {
                    return reflectionPermission2;
                }
                return null;
            }
        }
References System.Security.Permissions.ReflectionPermission.Cast(), System.Security.Permissions.ReflectionPermission.Copy(), System.Security.Permissions.ReflectionPermission.Flags, System.Security.Permissions.ReflectionPermission.flags, System.Security.Permissions.ReflectionPermission.IsUnrestricted(), and System.Security.Permissions.ReflectionPermission.ReflectionPermission().