Terraria Decompiled: System.Security.Permissions.ReflectionPermission.Union
Union()
override IPermission System.Security.Permissions.ReflectionPermission.Union (IPermission other) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 180 of file ReflectionPermission.cs.
        {
            ReflectionPermission reflectionPermission = this.Cast(other);
            if (other == null)
            {
                return this.Copy();
            }
            if (this.IsUnrestricted() || reflectionPermission.IsUnrestricted())
            {
                return new ReflectionPermission(PermissionState.Unrestricted);
            }
            ReflectionPermission reflectionPermission2 = (ReflectionPermission)reflectionPermission.Copy();
            reflectionPermission2.Flags |= this.flags;
            return reflectionPermission2;
        }
References System.Security.Permissions.ReflectionPermission.Cast(), System.Security.Permissions.ReflectionPermission.Copy(), System.Security.Permissions.ReflectionPermission.flags, System.Security.Permissions.ReflectionPermission.IsUnrestricted(), and System.Security.Permissions.ReflectionPermission.ReflectionPermission().