Terraria Decompiled: System.Buffers.BuffersExtensions.WriteMultiSegment< T >
WriteMultiSegment< T >()
static void System.Buffers.BuffersExtensions.WriteMultiSegment< T > (IBufferWriter< T > writer, in ReadOnlySpan< T > source, Span< T > destination) inline static private
Definition at line 103 of file BuffersExtensions.cs.
        {
            ReadOnlySpan<T> readOnlySpan = source;
            for (;;)
            {
                int num = Math.Min(destination.Length, readOnlySpan.Length);
                readOnlySpan.Slice(0, num).CopyTo(destination);
                writer.Advance(num);
                readOnlySpan = readOnlySpan.Slice(num);
                if (readOnlySpan.Length <= 0)
                {
                    break;
                }
                destination = writer.GetSpan(readOnlySpan.Length);
            }
        }
References System.Buffers.IBufferWriter< T >.Advance(), System.destination, System.Buffers.IBufferWriter< T >.GetSpan(), System.ReadOnlySpan< T >.Length, System.Math.Min(), System.ReadOnlySpan< T >.Slice(), and System.source.