Terraria Decompiled: Terraria.GameContent.Drawing.NextHorizonRenderer.DrawCloud
DrawCloud()
void Terraria.GameContent.Drawing.NextHorizonRenderer.DrawCloud (float globalCloudAlpha, Cloud theCloud, int cloudPass, float cY) inline
Implements Terraria.GameContent.Drawing.IHorizonRenderer.
Definition at line 243 of file NextHorizonRenderer.cs.
        {
            Asset<Texture2D> asset = TextureAssets.Cloud[theCloud.type];
            Vector2 vector = new Vector2(theCloud.position.X, cY) + asset.Size() / 2f;
            Color color = theCloud.cloudColor(Main.ColorOfTheSkies);
            this.OriginalColorsForCloud(theCloud, cloudPass, ref color);
            if (Main.atmo < 1f)
            {
                color *= Main.atmo;
            }
            this._drawData.Add(new DrawData(asset.Value, vector, null, color * globalCloudAlpha, theCloud.rotation, asset.Size() / 2f, theCloud.scale, theCloud.spriteDir, 0f));
        }
References Terraria.GameContent.Drawing.NextHorizonRenderer._drawData, System.Collections.Generic.List< T >.Add(), Terraria.Main.atmo, Terraria.GameContent.TextureAssets.Cloud, Terraria.Cloud.cloudColor(), Terraria.Main.ColorOfTheSkies, Terraria.GameContent.Drawing.NextHorizonRenderer.OriginalColorsForCloud(), Terraria.Cloud.position, Terraria.Cloud.rotation, Terraria.Cloud.scale, Terraria.Cloud.spriteDir, Terraria.Cloud.type, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.X.