Terraria Decompiled: Terraria.GameContent.Drawing.NextHorizonRenderer.LoadTextures
LoadTextures()
void Terraria.GameContent.Drawing.NextHorizonRenderer.LoadTextures () inline private
Definition at line 18 of file NextHorizonRenderer.cs.
        {
            if (NextHorizonRenderer._sunriseTextures != null)
            {
                return;
            }
            NextHorizonRenderer._sunriseTextures = new Asset<Texture2D>[]
            {
                Main.Assets.Request<Texture2D>("Images/Misc/Sunrise/Sunrise_Blue", 1),
                Main.Assets.Request<Texture2D>("Images/Misc/Sunrise/Sunrise_Violet", 1),
                Main.Assets.Request<Texture2D>("Images/Misc/Sunrise/Sunrise_Yellow", 1),
                Main.Assets.Request<Texture2D>("Images/Misc/Sunrise/Sunrise_Aluminum", 1)
            };
            NextHorizonRenderer._sunsetTextures = new Asset<Texture2D>[]
            {
                Main.Assets.Request<Texture2D>("Images/Misc/Sunset/Sunset_Blue", 1),
                Main.Assets.Request<Texture2D>("Images/Misc/Sunset/Sunset_Dark", 1),
                Main.Assets.Request<Texture2D>("Images/Misc/Sunset/Sunset_Pink", 1),
                Main.Assets.Request<Texture2D>("Images/Misc/Sunset/Sunset_Red", 1)
            };
            NextHorizonRenderer._sunflareGradientTexture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/colorgradient", 1);
            NextHorizonRenderer._sunflareGradientDitherTexture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/colorgradientdither", 1);
            NextHorizonRenderer._sunflarePointBlurryTexture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/Lens/PointBlurry", 1);
            NextHorizonRenderer._sunflarePointSharpTexture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/Lens/PointSharp", 1);
            NextHorizonRenderer._sunflare1Texture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/flare1", 1);
            NextHorizonRenderer._sunflare2Texture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/flare2", 1);
            NextHorizonRenderer._bokehTexture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/Lens/Flare1", 1);
            NextHorizonRenderer._spectraTexture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/Lens/Flare2", 1);
        }
References Terraria.GameContent.Drawing.NextHorizonRenderer._sunriseTextures, and Terraria.Main.Assets.
Referenced by Terraria.GameContent.Drawing.NextHorizonRenderer.DrawHorizon(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSun(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSunriseFlare(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSunsetFlare(), and Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSurfaceLayer().