Terraria Decompiled: Terraria.GameContent.Drawing.NextHorizonRenderer.CloudsEnd
CloudsEnd()
void Terraria.GameContent.Drawing.NextHorizonRenderer.CloudsEnd () inline
Implements Terraria.GameContent.Drawing.IHorizonRenderer.
Definition at line 334 of file NextHorizonRenderer.cs.
        {
            if (this._drawData.Count == 0)
            {
                return;
            }
            Main.spriteBatch.End();
            SpriteDrawBuffer spriteBuffer = Main.spriteBuffer;
            foreach (DrawData drawData in this._drawData)
            {
                drawData.Draw(spriteBuffer);
            }
            MiscShaderData miscShaderData = GameShaders.Misc["HorizonClouds"];
            miscShaderData.UseSpriteTransformMatrix(new Matrix?(Main.LatestSurfaceBackgroundBeginner.transformMatrix));
            Color color;
            Color color2;
            HorizonHelper.GetCelestialBodyColors(out color, out color2);
            Color color3 = (Main.dayTime ? color : color2);
            AuroraSky.ModifyTileColor(ref color3, 1f);
            miscShaderData.UseColor(color3);
            Vector2 celestialBodyPosition = NextHorizonRenderer.GetCelestialBodyPosition();
            float num;
            float num2;
            float num3;
            NextHorizonRenderer.GetVisibilities(out num, out num2, out num3);
            float num4 = Math.Max(num, num2) * num3;
            if (!Main.dayTime)
            {
                num4 = Math.Max(num4, num3 * 0.15f);
            }
            num4 *= Utils.Clamp<float>(1f - Main.cloudBGAlpha, 0f, 1f);
            miscShaderData.UseShaderSpecificData(new Vector4(celestialBodyPosition.X, celestialBodyPosition.Y, num4, 0f));
            for (int i = 0; i < this._drawData.Count; i++)
            {
                miscShaderData.Apply(new DrawData?(this._drawData[i]));
                spriteBuffer.DrawSingle(i);
            }
            spriteBuffer.Unbind();
            Main.LatestSurfaceBackgroundBeginner.Begin(Main.spriteBatch);
        }
References Terraria.GameContent.Drawing.NextHorizonRenderer._drawData, Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.DataStructures.SpriteBatchBeginner.Begin(), Terraria.Utils.Clamp(), Terraria.Main.cloudBGAlpha, System.Collections.Generic.List< T >.Count, Terraria.Main.dayTime, Terraria.DataStructures.DrawData.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.Drawing.HorizonHelper.GetCelestialBodyColors(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetCelestialBodyPosition(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetVisibilities(), Terraria.Main.LatestSurfaceBackgroundBeginner, System.Math.Max(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.GameContent.Skies.AuroraSky.ModifyTileColor(), Terraria.Main.spriteBatch, Terraria.Main.spriteBuffer, Terraria.DataStructures.SpriteBatchBeginner.transformMatrix, Terraria.Graphics.Shaders.MiscShaderData.UseColor(), Terraria.Graphics.Shaders.MiscShaderData.UseShaderSpecificData(), Terraria.Graphics.Shaders.MiscShaderData.UseSpriteTransformMatrix(), Microsoft.Xna.Framework.Graphics.Vector4, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.