Terraria Decompiled: Terraria.GameContent.Drawing.NextHorizonRenderer.DrawLensFlare
DrawLensFlare()
void Terraria.GameContent.Drawing.NextHorizonRenderer.DrawLensFlare () inline
Implements Terraria.GameContent.Drawing.IHorizonRenderer.
Definition at line 382 of file NextHorizonRenderer.cs.
        {
            if (!Main.ShouldDrawSurfaceBackground() || !Main.HorizonHelper.SunVisibilityEnabled)
            {
                return;
            }
            SpriteBatch spriteBatch = Main.spriteBatch;
            Vector2 celestialBodyPosition = NextHorizonRenderer.GetCelestialBodyPosition();
            Vector2 vector = Main.ScreenSize.ToVector2() / 2f;
            float num;
            float num2;
            float num3;
            NextHorizonRenderer.GetVisibilities(out num, out num2, out num3);
            float num4 = this.AdjustIntensity(num2, num3);
            float num5 = this.AdjustIntensity(num, num3);
            if ((double)num4 <= 0.01 && (double)num5 <= 0.01)
            {
                return;
            }
            Main.LatestSurfaceBackgroundBeginner.Begin(spriteBatch, SpriteSortMode.Immediate);
            EffectPass effectPass = Main.pixelShader.CurrentTechnique.Passes[0];
            MiscShaderData miscShaderData = GameShaders.Misc["LensFlare"];
            miscShaderData.UseImage1(Main.HorizonHelper.SunVisibilityPixelTexture);
            miscShaderData.Apply(null);
            this.DrawSunriseFlare(spriteBatch, celestialBodyPosition, vector, num4);
            this.DrawSunsetFlare(spriteBatch, celestialBodyPosition, vector, num5);
            spriteBatch.End();
            effectPass.Apply();
        }
References Terraria.GameContent.Drawing.NextHorizonRenderer.AdjustIntensity(), Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.DataStructures.SpriteBatchBeginner.Begin(), Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSunriseFlare(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSunsetFlare(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetCelestialBodyPosition(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetVisibilities(), Terraria.Main.HorizonHelper, Terraria.Main.LatestSurfaceBackgroundBeginner, Terraria.Graphics.Shaders.GameShaders.Misc, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Terraria.Main.ScreenSize, Terraria.Main.ShouldDrawSurfaceBackground(), Terraria.Main.spriteBatch, and Terraria.Graphics.Shaders.MiscShaderData.UseImage1().