Terraria Decompiled: Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSun
DrawSun()
void Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSun (Vector2 sunPosition) inline
Implements Terraria.GameContent.Drawing.IHorizonRenderer.
Definition at line 158 of file NextHorizonRenderer.cs.
        {
            float num;
            float num2;
            float num3;
            NextHorizonRenderer.GetVisibilities(out num, out num2, out num3);
            num *= num3;
            num2 *= num3;
            this.LoadTextures();
            Color color = new Color(255, 255, 255, 0);
            SpriteBatch spriteBatch = Main.spriteBatch;
            spriteBatch.Draw(NextHorizonRenderer._sunflare1Texture.Value, sunPosition, null, color * num * 0.75f, 0f, NextHorizonRenderer._sunflare1Texture.Size() / 2f, 3f, SpriteEffects.None, 0f);
            spriteBatch.Draw(NextHorizonRenderer._sunflare1Texture.Value, sunPosition, null, color * num * 0.35f, 0f, NextHorizonRenderer._sunflare1Texture.Size() / 2f, 2f, SpriteEffects.None, 0f);
            spriteBatch.Draw(NextHorizonRenderer._sunflare2Texture.Value, sunPosition, null, color * num2 * 0.7f * 0.5f, 0f, NextHorizonRenderer._sunflare2Texture.Size() / 2f, 2f, SpriteEffects.None, 0f);
            spriteBatch.Draw(NextHorizonRenderer._sunflare2Texture.Value, sunPosition, null, color * num2 * 0.3f * 0.5f, 0f, NextHorizonRenderer._sunflare2Texture.Size() / 2f, 1.5f, SpriteEffects.None, 0f);
            spriteBatch.Draw(NextHorizonRenderer._sunflare2Texture.Value, sunPosition, null, color * num2 * 0.2f * 0.5f, 0f, NextHorizonRenderer._sunflare2Texture.Size() / 2f, 1f, SpriteEffects.None, 0f);
        }
References Terraria.GameContent.Drawing.NextHorizonRenderer._sunflare1Texture, Terraria.GameContent.Drawing.NextHorizonRenderer._sunflare2Texture, Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetVisibilities(), Terraria.GameContent.Drawing.NextHorizonRenderer.LoadTextures(), Terraria.Main.spriteBatch, and ReLogic.Content.Asset< T >.Value.