Terraria Decompiled: Terraria.GameContent.Drawing.NextHorizonRenderer.DrawHorizon
DrawHorizon()
void Terraria.GameContent.Drawing.NextHorizonRenderer.DrawHorizon () inline
Implements Terraria.GameContent.Drawing.IHorizonRenderer.
Definition at line 58 of file NextHorizonRenderer.cs.
        {
            if (!Main.ShouldDrawSurfaceBackground())
            {
                return;
            }
            this.LoadTextures();
            int sunriseSunsetTextureIndex = this.GetSunriseSunsetTextureIndex();
            Asset<Texture2D> asset = NextHorizonRenderer._sunriseTextures[sunriseSunsetTextureIndex % NextHorizonRenderer._sunriseTextures.Length];
            Asset<Texture2D> asset2 = NextHorizonRenderer._sunsetTextures[sunriseSunsetTextureIndex % NextHorizonRenderer._sunsetTextures.Length];
            float num;
            float num2;
            float num3;
            NextHorizonRenderer.GetVisibilities(out num, out num2, out num3);
            SpriteBatch spriteBatch = Main.spriteBatch;
            Rectangle gradientRect = NextHorizonRenderer.GetGradientRect();
            foreach (BackgroundGradientDrawer backgroundGradientDrawer in SunGradients.BackgroundDrawers)
            {
                backgroundGradientDrawer.Draw();
            }
            if (num2 != 0f)
            {
                spriteBatch.Draw(asset.Value, gradientRect, Color.White * num2);
            }
            if (num != 0f)
            {
                spriteBatch.Draw(asset2.Value, gradientRect, Color.White * num);
            }
        }
References Terraria.GameContent.Drawing.NextHorizonRenderer._sunriseTextures, Terraria.GameContent.Drawing.NextHorizonRenderer._sunsetTextures, Terraria.GameContent.Drawing.SunGradients.BackgroundDrawers, Terraria.GameContent.Drawing.BackgroundGradientDrawer.Draw(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetGradientRect(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetSunriseSunsetTextureIndex(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetVisibilities(), Terraria.GameContent.Drawing.NextHorizonRenderer.LoadTextures(), Terraria.Main.ShouldDrawSurfaceBackground(), Terraria.Main.spriteBatch, and Microsoft.Xna.Framework.Color.White.