Terraria Decompiled: Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColor
BlendColor() [2/2]
void Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColor (ref Color color, Color[] gradient, float opacity) inline private
Definition at line 177 of file NextHorizonRenderer.cs.
        {
            this.BlendColor(ref color, gradient[gradient.Length / 2], opacity);
        }
References Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColor().
Referenced by Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColor(), Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColorAlongGradientBasedOnHeight(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSurfaceLayer(), and Terraria.GameContent.Drawing.NextHorizonRenderer.ModifyHorizonLight().