Terraria Decompiled: Terraria.GameContent.LightningGenerator.StormLightning.Generate
Generate()
static LightningGenerator.Bolt Terraria.GameContent.LightningGenerator.StormLightning.Generate (List< LightningGenerator::Bolt > bolts, uint seed, Vector2 targetPosition, bool calcPositions = true, bool calcRotations = true) inline static
Definition at line 297 of file LightningGenerator.cs.
            {
                LCG32Random lcg32Random = new LCG32Random(seed);
                Vector2 vector = -Vector2.UnitY.RotatedBy((lcg32Random.NextDouble() * 2.0 - 1.0) * (double)LightningGenerator.StormLightning.SourceRotationLimit, default(Vector2));
                return LightningGenerator.StormLightning.Generator.Generate(bolts, seed, targetPosition + vector * LightningGenerator.StormLightning.Length, targetPosition, calcPositions, calcRotations);
            }
References Terraria.GameContent.LightningGenerator.Generate(), Terraria.GameContent.LightningGenerator.StormLightning.Generator, Terraria.GameContent.LightningGenerator.StormLightning.Length, Terraria.Utilities.LCG32Random.NextDouble(), Terraria.GameContent.LightningGenerator.StormLightning.SourceRotationLimit, and Microsoft.Xna.Framework.Vector2.UnitY.
Referenced by Terraria.GameContent.LightningGenerator.StormLightning.CanHitTarget(), Terraria.GameContent.LightningGenerator.StormLightning.GenerateMainBoltPath(), and Terraria.Graphics.Renderers.StormLightningParticle.Prepare().