Terraria Decompiled: System.Collections.Generic.ICollection.Contains
Contains()
bool System.Collections.Generic.ICollection< T >.Contains (T item)
Implemented in System.Collections.Generic.List< T >, System.Collections.Generic.Queue< T >, System.Collections.Generic.Stack< T >, and Newtonsoft.Json.Utilities.CollectionWrapper< T >.
Referenced by Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.Contains(), Newtonsoft.Json.Utilities.CollectionWrapper< T >.Contains(), System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.KeyCollection.Contains(), System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >.ValueCollection.Contains(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.ContainsKey(), System.Runtime.Remoting.Channels.ChannelServices.RegisterChannel(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.Remove(), Newtonsoft.Json.Utilities.CollectionWrapper< T >.Remove(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.Remove(), and Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.TryGetValue().