Terraria Decompiled: Terraria.Graphics.TileBatch.FlushLayered
FlushLayered()
void Terraria.Graphics.TileBatch.FlushLayered () inline private
Definition at line 522 of file TileBatch.cs.
        {
            Array.Sort<TileBatch.LayerBatch>(this._batches, 0, this._batchCount);
            int i = 0;
            this._vertexBufferPosition = 0;
            for (int j = 0; j < this._batchCount; j++)
            {
                TileBatch.LayerBatch layerBatch = this._batches[j];
                Texture2D texture2D = this._passTextures[(int)layerBatch.Texture];
                this._graphicsDevice.Textures[0] = texture2D;
                int num = layerBatch.Length;
                int num2 = j;
                int num3 = 0;
                TileBatch.DataSlice dataSlice = default(TileBatch.DataSlice);
                do
                {
                    if (this._vertexBufferPosition == i)
                    {
                        i = 0;
                        this._vertexBufferPosition = 0;
                        while (i < num)
{
                            if (!this.FillVertexBuffer(this._batches[num2], ref dataSlice, ref num3, ref i))
{
                                break;
                            }
                            num2++;
                            num3 = 0;
                        }
                        while (i < 2048 && num2 < this._batchCount)
{
                            layerBatch = this._batches[num2];
                            if (i + layerBatch.Length > 2048)
{
                                break;
                            }
                            this.FillVertexBuffer(layerBatch, ref i);
                            num2++;
                        }
                        this._vertexBuffer.SetData<VertexPositionColorTexture>(this._vertices, 0, i * 4, SetDataOptions.Discard);
                    }
                    int num4 = Math.Min(num, i - this._vertexBufferPosition);
                    this._graphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, this._vertexBufferPosition * 4, 0, num4 * 4, 0, num4 * 2);
                    this._vertexBufferPosition += num4;
                    num -= num4;
                    this._drawCalls++;
                }
                while (num > 0);
            }
            this._queuedSpriteCount = 0;
            this._batchDataCount = 0;
            this._batchCount = 0;
            this._batchLookup.Clear();
            Array.Clear(this._batchLookupCache, 0, this._batchLookupCache.Length);
            this._passTextureCount = 0;
            this._textureIdLookup.Clear();
            this._currentBatchKey = default(TileBatch.LayerBatchKey);
        }
References Terraria.Graphics.TileBatch._batchCount, Terraria.Graphics.TileBatch._batches, Terraria.Graphics.TileBatch._batchLookup, Terraria.Graphics.TileBatch._batchLookupCache, Terraria.Graphics.TileBatch._drawCalls, Terraria.Graphics.TileBatch._graphicsDevice, Terraria.Graphics.TileBatch._passTextures, Terraria.Graphics.TileBatch._textureIdLookup, Terraria.Graphics.TileBatch._vertexBuffer, Terraria.Graphics.TileBatch._vertexBufferPosition, Terraria.Graphics.TileBatch._vertices, System.Array.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Terraria.Graphics.TileBatch.FillVertexBuffer(), int, Terraria.Graphics.TileBatch.LayerBatch.Length, System.Math.Min(), System.Array.Sort(), Terraria.Graphics.TileBatch.LayerBatch.Texture, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures.
Referenced by Terraria.Graphics.TileBatch.End().