Terraria Decompiled: Terraria.Graphics.TileBatch.Draw
Draw() [3/7]
void Terraria.Graphics.TileBatch.Draw (Texture2D texture, Vector2 position, VertexColors colors) inline
Definition at line 121 of file TileBatch.cs.
        {
            Vector4 vector = default(Vector4);
            vector.X = position.X;
            vector.Y = position.Y;
            vector.Z = 1f;
            vector.W = 1f;
            this.InternalDraw(texture, ref vector, true, ref TileBatch._nullRectangle, ref colors, ref TileBatch._vector2Zero, SpriteEffects.None, 0f);
        }
References Terraria.Graphics.TileBatch._nullRectangle, Terraria.Graphics.TileBatch._vector2Zero, Terraria.Graphics.TileBatch.InternalDraw(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawBackground_DirtBackground(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids(), Terraria.GameContent.Drawing.TileDrawing.DrawPartialLiquid(), Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer(), Terraria.Main.DrawSimpleSurfaceBackground(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_Flames(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_BackRope(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.GameContent.Drawing.TileDrawing.DrawXmasTree(), Terraria.Main.OldDrawBackground(), and Terraria.GameContent.Shaders.WaterShaderData.StepLiquids().