Terraria Decompiled: Terraria.Graphics.TileBatch.InternalDraw
InternalDraw()
unsafe void Terraria.Graphics.TileBatch.InternalDraw (Texture2D texture, ref Vector4 destination, bool scaleDestination, ref Rectangle? sourceRectangle, ref VertexColors colors, ref Vector2 origin, SpriteEffects effects, float rotation) inline private
Definition at line 199 of file TileBatch.cs.
        {
            int num;
            if (this._layeredSortingEnabled)
            {
                if (this._nextLayerStack != null)
                {
                    uint value = this._nextLayerStack.Value;
                    if (texture != this._currentBatchKey.Texture || value != this._currentBatchKey.LayerStack)
                    {
                        this.SwitchBatch(texture, value);
                    }
                }
                else if (texture != this._currentBatchKey.Texture)
                {
                    this.SwitchBatch(texture, this._currentBatchKey.LayerStack + 1U);
                }
                this._nextLayerStack = null;
                num = this.GetNextSpriteIndex(ref this._batches[this._currentBatchIndex]);
            }
            else
            {
                if (this._queuedSpriteCount >= this._spriteDataQueue.Length)
                {
                    Array.Resize<TileBatch.SpriteData>(ref this._spriteDataQueue, this._spriteDataQueue.Length << 1);
                }
                if (this._queuedSpriteCount >= this._spriteTextures.Length)
                {
                    Array.Resize<Texture2D>(ref this._spriteTextures, this._spriteTextures.Length << 1);
                }
                this._spriteTextures[this._queuedSpriteCount] = texture;
                int queuedSpriteCount = this._queuedSpriteCount;
                this._queuedSpriteCount = queuedSpriteCount + 1;
                num = queuedSpriteCount;
            }
            fixed (TileBatch.SpriteData* ptr = &this._spriteDataQueue[num])
            {
                TileBatch.SpriteData* ptr2 = ptr;
                float num2 = destination.Z;
                float num3 = destination.W;
                if (sourceRectangle != null)
                {
                    Rectangle value2 = sourceRectangle.Value;
                    ptr2->Source.X = (float)value2.X;
                    ptr2->Source.Y = (float)value2.Y;
                    ptr2->Source.Z = (float)value2.Width;
                    ptr2->Source.W = (float)value2.Height;
                    if (scaleDestination)
                    {
                        num2 *= (float)value2.Width;
                        num3 *= (float)value2.Height;
                    }
                }
                else
                {
                    float num4 = (float)texture.Width;
                    float num5 = (float)texture.Height;
                    ptr2->Source.X = 0f;
                    ptr2->Source.Y = 0f;
                    ptr2->Source.Z = num4;
                    ptr2->Source.W = num5;
                    if (scaleDestination)
                    {
                        num2 *= num4;
                        num3 *= num5;
                    }
                }
                ptr2->Destination.X = destination.X;
                ptr2->Destination.Y = destination.Y;
                ptr2->Destination.Z = num2;
                ptr2->Destination.W = num3;
                ptr2->Origin.X = origin.X;
                ptr2->Origin.Y = origin.Y;
                ptr2->Effects = effects;
                ptr2->Colors = colors;
                ptr2->Rotation = rotation;
            }
        }
References Terraria.Graphics.TileBatch._batches, Terraria.Graphics.TileBatch._currentBatchIndex, Terraria.Graphics.TileBatch._currentBatchKey, Terraria.Graphics.TileBatch._layeredSortingEnabled, Terraria.Graphics.TileBatch._nextLayerStack, Terraria.Graphics.TileBatch._queuedSpriteCount, Terraria.Graphics.TileBatch._spriteDataQueue, Terraria.Graphics.TileBatch._spriteTextures, System.destination, Terraria.Graphics.TileBatch.GetNextSpriteIndex(), Microsoft.Xna.Framework.Graphics.Texture2D.Height, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Graphics.TileBatch.SwitchBatch(), System.U, System.value, Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.Graphics.TileBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), and Terraria.Graphics.TileBatch.Draw().