Terraria Decompiled: Terraria.Graphics.TileBatch.RenderBatch
RenderBatch()
unsafe void Terraria.Graphics.TileBatch.RenderBatch (Texture2D texture, TileBatch::SpriteData[] sprites, int offset, int count) inline private
Definition at line 423 of file TileBatch.cs.
        {
            this._graphicsDevice.Textures[0] = texture;
            while (count > 0)
            {
                SetDataOptions setDataOptions = SetDataOptions.NoOverwrite;
                int num = count;
                if (num > 2048 - this._vertexBufferPosition)
                {
                    num = 2048 - this._vertexBufferPosition;
                    if (num < 256)
                    {
                        this._vertexBufferPosition = 0;
                        setDataOptions = SetDataOptions.Discard;
                        num = count;
                        if (num > 2048)
{
                            num = 2048;
                        }
                    }
                }
                this.FillVertexBuffer(texture, sprites, offset, num, 0);
                int num2 = this._vertexBufferPosition * sizeof(VertexPositionColorTexture) * 4;
                this._vertexBuffer.SetData<VertexPositionColorTexture>(num2, this._vertices, 0, num * 4, sizeof(VertexPositionColorTexture), setDataOptions);
                int num3 = this._vertexBufferPosition * 4;
                int num4 = num * 4;
                int num5 = this._vertexBufferPosition * 6;
                int num6 = num * 2;
                this._graphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, num3, num4, num5, num6);
                this._vertexBufferPosition += num;
                offset += num;
                count -= num;
                this._drawCalls++;
            }
        }
References Terraria.Graphics.TileBatch._drawCalls, Terraria.Graphics.TileBatch._graphicsDevice, Terraria.Graphics.TileBatch._vertexBuffer, Terraria.Graphics.TileBatch._vertexBufferPosition, Terraria.Graphics.TileBatch._vertices, System.count, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Terraria.Graphics.TileBatch.FillVertexBuffer(), System.offset, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures.
Referenced by Terraria.Graphics.TileBatch.Flush().