Terraria Decompiled: Terraria.Graphics.TileBatch.End
End()
int Terraria.Graphics.TileBatch.End () inline
Definition at line 381 of file TileBatch.cs.
        {
            this._layeredSortingEnabled = false;
            if (this._queuedSpriteCount == 0)
            {
                return 0;
            }
            this.FlushRenderState();
            if (this._passTextureCount > 0)
            {
                this.FlushLayered();
            }
            else
            {
                this.Flush();
            }
            return this._drawCalls;
        }
References Terraria.Graphics.TileBatch._drawCalls, Terraria.Graphics.TileBatch._passTextureCount, Terraria.Graphics.TileBatch._queuedSpriteCount, Terraria.Graphics.TileBatch.Flush(), Terraria.Graphics.TileBatch.FlushLayered(), and Terraria.Graphics.TileBatch.FlushRenderState().
Referenced by Terraria.Main.DoDraw_Waterfalls(), Terraria.Main.DrawBackground(), Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles(), Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids(), Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.GameContent.Drawing.TileDrawingBase.End(), Terraria.Main.OldDrawBackground(), Terraria.Main.RenderBackgroundWater(), Terraria.Main.RenderWater(), Terraria.Graphics.TileBatch.Restart(), and Terraria.GameContent.Shaders.WaterShaderData.StepLiquids().