Terraria Decompiled: Terraria.Graphics.TileBatch.FillVertexBuffer
FillVertexBuffer() [1/3]
unsafe void Terraria.Graphics.TileBatch.FillVertexBuffer (Texture2D texture, TileBatch::SpriteData[] sprites, int offset, int count, int vbSpriteOffset) inline private
Definition at line 460 of file TileBatch.cs.
        {
            float num = 1f / (float)texture.Width;
            float num2 = 1f / (float)texture.Height;
            fixed (TileBatch.SpriteData* ptr = &sprites[offset])
            {
                TileBatch.SpriteData* ptr2 = ptr;
                fixed (VertexPositionColorTexture* ptr3 = &this._vertices[vbSpriteOffset * 4])
                {
                    VertexPositionColorTexture* ptr4 = ptr3;
                    TileBatch.SpriteData* ptr5 = ptr2;
                    VertexPositionColorTexture* ptr6 = ptr4;
                    for (int i = 0; i < count; i++)
                    {
                        float num3;
                        float num4;
                        if (ptr5->Rotation != 0f)
{
                            num3 = (float)Math.Cos((double)ptr5->Rotation);
                            num4 = (float)Math.Sin((double)ptr5->Rotation);
                        }
                        else
{
                            num3 = 1f;
                            num4 = 0f;
                        }
                        float num5 = ptr5->Origin.X / ptr5->Source.Z;
                        float num6 = ptr5->Origin.Y / ptr5->Source.W;
                        ptr6->Color = ptr5->Colors.TopLeftColor;
                        ptr6[1].Color = ptr5->Colors.TopRightColor;
                        ptr6[2].Color = ptr5->Colors.BottomRightColor;
                        ptr6[3].Color = ptr5->Colors.BottomLeftColor;
                        for (int j = 0; j < 4; j++)
{
                            float num7 = TileBatch.CORNER_OFFSET_X[j];
                            float num8 = TileBatch.CORNER_OFFSET_Y[j];
                            float num9 = (num7 - num5) * ptr5->Destination.Z;
                            float num10 = (num8 - num6) * ptr5->Destination.W;
                            float num11 = ptr5->Destination.X + num9 * num3 - num10 * num4;
                            float num12 = ptr5->Destination.Y + num9 * num4 + num10 * num3;
                            if ((ptr5->Effects & SpriteEffects.FlipVertically) != SpriteEffects.None)
{
                                num8 = 1f - num8;
                            }
                            if ((ptr5->Effects & SpriteEffects.FlipHorizontally) != SpriteEffects.None)
{
                                num7 = 1f - num7;
                            }
                            ptr6->Position.X = num11;
                            ptr6->Position.Y = num12;
                            ptr6->Position.Z = 0f;
                            ptr6->TextureCoordinate.X = (ptr5->Source.X + num7 * ptr5->Source.Z) * num;
                            ptr6->TextureCoordinate.Y = (ptr5->Source.Y + num8 * ptr5->Source.W) * num2;
                            ptr6++;
                        }
                        ptr5++;
                    }
                }
            }
        }
References Terraria.Graphics.TileBatch._vertices, Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.Color, Terraria.Graphics.TileBatch.CORNER_OFFSET_X, Terraria.Graphics.TileBatch.CORNER_OFFSET_Y, System.Math.Cos(), System.count, Microsoft.Xna.Framework.Graphics.Texture2D.Height, System.offset, Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.Position, System.Math.Sin(), Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.TextureCoordinate, Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Graphics.TileBatch.FillVertexBuffer(), Terraria.Graphics.TileBatch.FillVertexBuffer(), Terraria.Graphics.TileBatch.FlushLayered(), and Terraria.Graphics.TileBatch.RenderBatch().