Terraria Decompiled: Terraria.Graphics.TileBatch.CreateBatch
CreateBatch()
void Terraria.Graphics.TileBatch.CreateBatch () inline private
Definition at line 344 of file TileBatch.cs.
        {
            Texture2D texture = this._currentBatchKey.Texture;
            ushort num;
            int num2;
            if (!this._textureIdLookup.TryGetValue(texture, out num))
            {
                num = (this._textureIdLookup[texture] = (ushort)this._passTextureCount);
                if (this._passTextureCount == this._passTextures.Length)
                {
                    Array.Resize<Texture2D>(ref this._passTextures, this._passTextures.Length * 2);
                }
                Texture2D[] passTextures = this._passTextures;
                num2 = this._passTextureCount;
                this._passTextureCount = num2 + 1;
                passTextures[num2] = texture;
            }
            if (this._batchCount == this._batches.Length)
            {
                Array.Resize<TileBatch.LayerBatch>(ref this._batches, this._batches.Length * 2);
            }
            int newSpriteBufferSlice = this.GetNewSpriteBufferSlice(2);
            TileBatch.LayerBatch[] batches = this._batches;
            num2 = this._batchCount;
            this._batchCount = num2 + 1;
            batches[this._currentBatchIndex = num2] = new TileBatch.LayerBatch
            {
                LayerStack = this._currentBatchKey.LayerStack,
                Texture = num,
                Head = newSpriteBufferSlice,
                Tail = newSpriteBufferSlice,
                NextSprite = this._batchData[newSpriteBufferSlice].Start
            };
            this._batchLookup[this._currentBatchKey] = this._currentBatchIndex;
        }
References Terraria.Graphics.TileBatch._batchCount, Terraria.Graphics.TileBatch._batchData, Terraria.Graphics.TileBatch._batches, Terraria.Graphics.TileBatch._batchLookup, Terraria.Graphics.TileBatch._currentBatchIndex, Terraria.Graphics.TileBatch._currentBatchKey, Terraria.Graphics.TileBatch._passTextureCount, Terraria.Graphics.TileBatch._passTextures, Terraria.Graphics.TileBatch._textureIdLookup, Terraria.Graphics.TileBatch.GetNewSpriteBufferSlice(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.Graphics.TileBatch.SwitchBatch().