Terraria Decompiled: Terraria.DataStructures.DoubleStack.Clear
Clear()
void Terraria.DataStructures.DoubleStack< T1 >.Clear (bool quickClear = false) inline
Definition at line 155 of file DoubleStack.cs.
        {
            if (!quickClear)
            {
                for (int i = 0; i < this._segmentCount; i++)
                {
                    Array.Clear(this._segmentList[i], 0, this._segmentSize);
                }
            }
            this._start = this._segmentSize / 2;
            this._end = this._start;
            this._size = 0;
        }
References Terraria.DataStructures.DoubleStack< T1 >._segmentCount, Terraria.DataStructures.DoubleStack< T1 >._segmentList, Terraria.DataStructures.DoubleStack< T1 >._segmentSize, Terraria.DataStructures.DoubleStack< T1 >._start, and System.Array.Clear().
Referenced by Terraria.Wiring.HitWire(), and Terraria.Wiring.TripWire().