Terraria Decompiled: System.Reflection.StrongNameKeyPair.StrongName
StrongName()
StrongName System.Reflection.StrongNameKeyPair.StrongName () inline package
Definition at line 172 of file StrongNameKeyPair.cs.
        {
            RSA rsa = this.GetRSA();
            if (rsa != null)
            {
                return new StrongName(rsa);
            }
            if (this._publicKey != null)
            {
                return new StrongName(this._publicKey);
            }
            return null;
        }
References System.Reflection.StrongNameKeyPair._publicKey, System.Reflection.StrongNameKeyPair.GetRSA(), and System.Reflection.StrongNameKeyPair.StrongName().
Referenced by System.Reflection.Emit.AssemblyBuilder.AssemblyBuilder(), and System.Reflection.StrongNameKeyPair.StrongName().