Terraria Decompiled: System.Reflection.StrongNameKeyPair.GetRSA
GetRSA()
RSA System.Reflection.StrongNameKeyPair.GetRSA () inline private
Definition at line 79 of file StrongNameKeyPair.cs.
        {
            if (this._rsa != null)
            {
                return this._rsa;
            }
            if (this._keyPairArray != null)
            {
                try
                {
                    this._rsa = CryptoConvert.FromCapiKeyBlob(this._keyPairArray);
                    goto IL_005A;
                }
                catch
                {
                    this._keyPairArray = null;
                    goto IL_005A;
                }
            }
            if (this._keyPairContainer != null)
            {
                this._rsa = new RSACryptoServiceProvider(new CspParameters
                {
                    KeyContainerName = this._keyPairContainer
                });
            }
            IL_005A:
            return this._rsa;
        }
References System.Reflection.StrongNameKeyPair._keyPairArray, System.Reflection.StrongNameKeyPair._keyPairContainer, System.Reflection.StrongNameKeyPair._rsa, and Mono.Security.Cryptography.CryptoConvert.FromCapiKeyBlob().
Referenced by System.Reflection.StrongNameKeyPair.StrongName(), System.Reflection.StrongNameKeyPair.StrongNameKeyPair(), System.Reflection.StrongNameKeyPair.StrongNameKeyPair(), and System.Reflection.StrongNameKeyPair.StrongNameKeyPair().