Terraria Decompiled: System.Collections.Generic.ArraySortHelper.IntrospectiveSort
IntrospectiveSort() [2/2]
static void System.Collections.Generic.ArraySortHelper< T >.IntrospectiveSort (TKey[] keys, TValue[] values, int left, int length, IComparer< TKey > comparer) inline static package
Definition at line 63 of file ArraySortHelper.2.cs.
        {
            if (length < 2)
            {
                return;
            }
            ArraySortHelper<TKey, TValue>.IntroSort(keys, values, left, length + left - 1, 2 * IntrospectiveSortUtilities.FloorLog2PlusOne(length), comparer);
        }
References System.comparer, System.Collections.Generic.IntrospectiveSortUtilities.FloorLog2PlusOne(), System.Collections.Generic.ArraySortHelper< T >.IntroSort(), System.length, and System.values.
Referenced by System.Collections.Generic.ArraySortHelper< T >.Sort(), System.Collections.Generic.ArraySortHelper< T >.Sort(), System.Collections.Generic.GenericArraySortHelper< T >.Sort(), System.Collections.Generic.ArraySortHelper< T >.Sort(), and System.Collections.Generic.GenericArraySortHelper< T >.Sort().